### ISSUE TITLE
Missing column for ptlen in Section 2.3 of Symmetric Sub-spec

### ISSUE THREAD

**Issue by hbooth** [usnistgov/ACVP#100]
In Section 2.2 of the Symmetric sub-spec, the table contains a row for ptlen that references Section 2.3. This information appears to be missing from Section 2.3.

**Comment by Kritner** [comment]
At one point could table 2.3 have referenced the Column `Payload` as `Payload/PT length` ? If it wasn't there, I know I have seen the two used interchangeably elsewhere - though it may have been CAVS itself, not the spec, I don't recall.

**Comment by hbooth** [comment]
Ok, I see what you are saying. I was just scanning for PT and missed Payload. Maybe consistent terminology would be beneficial?

**Comment by atvassilev** [comment]
I looked at the table in Section 2.2 and think that one cosmetic change may be helpful: increase the width of the first and second columns a bit at the expense of the last column. This could resolve the issue with chopping off keyingOption at the last letter and similarly for Prerequisite. xml2rfc allows manipulating the relative width of columns like:

<ttcol align="left" width="22%">Column1</ttcol>
<ttcol align="left" width="23%">Column2</ttcol>
<ttcol align="left" width="20%">Column3</ttcol>
<ttcol align="left" width="20%">Column4</ttcol>
<ttcol align="left" width="15%">Column5</ttcol>

I am not sure these numbers are the best but one could start with them.

**Comment by atvassilev** [comment]
Oops, it looks like the web edit interface stripped off all of my xml. Bummer, does anyone know how to work around this?

**Comment by celic** [comment]
Try placing your code inside back ticks `

This uses the "code" interface to make it look like...

`<table>Column1</table>`

**Comment by atvassilev** [comment]
@celic thanks.

Here is what I meant to provide as example:
'<ttcol align="left" width="23%">Column1</ttcol>'
'<ttcol align="left" width="22%">Column2</ttcol>'
'<ttcol align="left" width="20%">Column3</ttcol>'
'<ttcol align="left" width="20%">Column4</ttcol>'
'<ttcol align="left" width="15%">Column5</ttcol>'

**Comment by atvassilev** [comment]
Wow, still no luck...

**Comment by celic** [comment]
Sorry, it is a back tick. Same button as ~ but without holding shift. It is a rather obscure character on a keyboard.

**Comment by atvassilev** [comment]
Ah OK,

`<ttcol align="left" width="23%">Column1</ttcol>`
`<ttcol align="left" width="22%">Column2</ttcol>`
`<ttcol align="left" width="20%">Column2</ttcol>`
`<ttcol align="left" width="20%">Column2</ttcol>`
`<ttcol align="left" width="15%">Column2</ttcol>`

Again these are just suggested numbers not necessarily the solution.

**Comment by bfussell** [comment]
I'll be happy to change payload to ptLen in the table 2.3, but I'm failing to see and issue with table 2.2 sizing.  KeyingOption fits perfectly when displayed with Chrome.

**Comment by atvassilev** [comment]
Resolved with PR #113
