### ISSUE TITLE
Demo server Unable to map RSA-KeyGen-FIPS186-4 to an internal algorithm id

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP#1000]
I posted the following to /testSessions. The algorithm object is verbatim from https://usnistgov.github.io/ACVP/draft-celi-acvp-rsa.html#name-required-prerequisite-algor.

```

[{
		"acvVersion": "1.0"
	},
	{
		"isSample": false,
		"algorithms": [{
			"algorithm": "RSA",
			"mode": "KeyGen",
			"revision": "FIPS186-4",
			"prereqVals": [{
				"algorithm": "DRBG",
				"valValue": "1234"
			}, {
				"algorithm": "SHA",
				"valValue": "5678"
			}],
			"infoGeneratedByServer": false,
			"pubExpMode": "random",
			"keyFormat": "crt",
			"capabilities": [{
					"randPQ": "B.3.2",
					"properties": [{
						"modulo": 2048,
						"hashAlg": [
							"SHA2-224"
						]
					}]
				},
				{
					"randPQ": "B.3.4",
					"properties": [{
						"modulo": 3072,
						"hashAlg": [
							"SHA2-224"
						]
					}]
				},
				{
					"randPQ": "B.3.3",
					"properties": [{
						"modulo": 2048,
						"primeTest": [
							"tblC2"
						]
					}]
				},
				{
					"randPQ": "B.3.6",
					"properties": [{
						"modulo": 3072,
						"primeTest": [
							"tblC2",
							"tblC3"
						]
					}]
				},
				{
					"randPQ": "B.3.5",
					"properties": [{
						"modulo": 4096,
						"hashAlg": [
							"SHA2-512"
						],
						"primeTest": [
							"tblC3"
						]
					}]
				}
			]
		}]
	}
]


```

The server replied with "Unable to map RSA-KeyGen-FIPS186-4 to an internal algorithm id".

Is this a demo server issue?

**Comment by Kritner** [comment]
That's a casing issue in the spec, should be "keyGen" rather than "KeyGen"

**Comment by Kritner** [comment]
Things were made a bit more strict around casing with the demo deployment, so there may be a few instances of this occurring throughout the spec (or perhaps in the code depending on the situation)

**Comment by jbarnesweb** [comment]
Thank you!

**Comment by jbarnesweb** [comment]
I see a similar error in ECDSA.

**Comment by Kritner** [comment]
Hmm... yeah it seems it's a bit inconsistent depending on where we look.  Let me double check with some folks internally to make sure we're doing the desired route of "SigGen" or "sigGen" (as examples).

**Comment by smuellerDD** [comment]
Just a note: I see the same error, but my definition seems to use the right camel case:

```
      {
        "revision":"1.0",
        "algorithm":"RSA",
        "mode":"keyGen",
        "infoGeneratedByServer":false,
        "pubExpMode":"random",
        "keyFormat":"standard",
        "capabilities":[
```

```
        "revision":"1.0",
        "algorithm":"RSA",
        "mode":"sigGen",
        "capabilities":[
```

```
        "revision":"1.0",
        "algorithm":"RSA",
        "mode":"sigVer",
        "pubExpMode":"random",
        "capabilities":[
```

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Unable to map RSA-keyGen-1.0 - index 0 to an internal algorithm id.",
      "Unable to map RSA-sigGen-1.0 - index 1 to an internal algorithm id.",
      "Unable to map RSA-sigVer-1.0 - index 2 to an internal algorithm id."
    ]
  }
]
```

**Comment by Kritner** [comment]
@smuellerDD please see #990, sorry I tagged you on the issue at some point, a few RSA modes went through a rename in order to accommodate the release of FIPS186-5. Given your client was sending in "keyGen", "sigGen", and "sigVer" that seems to reinforce that it was just a transposition error on our part when moving over from the old "xml2rfc" specification to the "metanorma" one.

**Comment by smuellerDD** [comment]
Thanks for the pointer - I somehow overlooked the tag.

What about the RSA component tests?

**Comment by celic** [comment]
The component tests are not changing. They are not dependent on changes to the standards.

**Comment by smuellerDD** [comment]
Am Freitag, 11. September 2020, 21:49:30 CEST schrieb Chris Celi:

Hi Chris,

> The component tests are not changing. They are not dependent on changes to
> the standards.

Ok, just for the records, they stay with "1.0"?!

Ciao
Stephan

**Comment by celic** [comment]
Yes, RSA / signaturePrimitive / 1.0 and RSA / decryptionPrimitive / 1.0.

**Comment by Kritner** [comment]
Looks like this is handled from #1000 and/or #990, closing.
