### ISSUE TITLE
KAS-FFC: partialVal invalid function but listed in spec?

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1005]
Hello,

It was recently brought up in https://github.com/cisco/libacvp/issues/474 that partialVal is not considered valid by the server -
`  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "KAS-FFC-Component-1.0: Invalid Functions supplied: partialVal, intersect : 1, supplied: 2"
    ]
  }
]
`

According to #409 , partialVal is not valid for KAS-FFC. Is this intended to still be part of the spec (listed in section 7.4 of KAS-FFC spec)?

Thanks,
Andrew

**Comment by Kritner** [comment]
It should probably not be a part of the 1.0 testing version of the specification.  A FFC partial validation routine has been defined in the SP800-56Ar3 document, but the 1.0 testing existed prior to that document.
