### ISSUE TITLE
General Exception when attempting creating KAS-ECC SP800-56Ar3 Test Session

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#1007]
When trying to create a test session for KAS-ECC (SP800-56Ar3) on demo:
ie
`POST  https://demo.acvts.nist.gov/acvp/v1/testSessions`

I am getting a `400` the following error:
```json
{
    "error": "Validation error(s) on JSON payload.",
    "context": [
        "KAS-ECC-Sp800-56Ar3: General exception. Contact service provider."
    ]
}
```

There isn't a lot of info in there to debug the issue which I'm certain has to do with the registration payload we are supplying - which looks like this:
```json
{
    "algorithm": "KAS-ECC",
    "revision": "Sp800-56Ar3",
    "iutId": "123456ABCD",
    "function": [
        "keyPairGen"
    ],
    "domainParameterGenerationMethods": [
        "P-224",
        "P-256",
        "P-384"
    ],
    "scheme": {
        "staticUnified": {
            "keyConfirmationMethod": {
                "keyConfirmationDirections": [
                    "unilateral"
                ],
                "keyConfirmationRoles": [
                    "provider",
                    "recipient"
                ]
            },
            "kdfMethods": {
                "oneStepKdf": {
                    "auxFunctions": [
                        {
                            "auxFunctionName": "SHA2-512",
                            "macSaltMethods": [
                                "default"
                            ]
                        }
                    ],
                    "encoding": [
                        "concatenation"
                    ],
                    "fixedInfoPattern": "literal[0123456789ABCDEF]"
                }
            },
            "l": 256,
            "kasRole": [
                "initiator",
                "responder"
            ]
        }
    }
}
```

**Comment by Kritner** [comment]
I'll try to take a look this evening, or in the morning if I can't get to it tonight due to family stuff.

**Comment by Kritner** [comment]
The above registration is missing "macMethods" within the key confirmation property: https://usnistgov.github.io/ACVP/draft-hammett-acvp-kas-ecc-sp800-56ar3.html#supmacmet

The ACVP server *should* have been returning a more descriptive error, I'll put in a correction for that.

FWIW after putting in the correction so the above issue is handled, this is the response with your registration:

![image](https://user-images.githubusercontent.com/8814983/93584004-b1a21980-f972-11ea-89db-48fc6b99012e.png)

So it looks like the uPartyInfo and vPartyInfo need to additionally be included as parts to your `fixedInfoPattern`.

**Comment by AlexThurston** [comment]
Nice.  Thanks for the prompt response @Kritner The error is much more helpful now and it looks like I was able to at least create a test session.  Looks like it's taking a little while to generate the vector set though.

Is KAS-ECC one that takes a long time, or is something clogged?  It's possible that I'm also just impatient :P

Test session ID is `116601`
Vector set is `332381`

**Comment by Kritner** [comment]
The change for the general error/unhandled exception for the issue with that registration is now on demo.

Regarding the timing, it does look like demo is getting hit pretty heavy today, including during the time of your registration.  Looks like the prompt file has been out there for a bit at this point though

**Comment by Kritner** [comment]
this change is now on production https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.12
