### ISSUE TITLE
Term change test protocol

### ISSUE THREAD

**Issue by Yoshio123** [usnistgov/ACVP#1008]
**What type of change is being proposed?**
New endpoint, change to existing endpoint, etc.

**Details on suggestion**
What would you like to see changed in the protocol specification?

**Additional information**
Any additional information regarding why this suggestion could be useful to the ACVP Protocol.

**Comment by Kritner** [comment]
@Yoshio123 this looks to be just the issue template submitted as an issue, did you have something you wanted to suggest?
