### ISSUE TITLE
AES-XPN: Says "Within domain" for ivLen when should say "96"?

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1009]
Table 11 in the block cipher spec indicates that the iv length for tests from a server for AES-XPN must be "within domain". My understanding is that XPN has a static 96 bit iv length. Could this be clarified?

Thanks,
Andrew

**Comment by celic** [comment]
Table 11 specifies properties that will appear in the test groups of the prompt. For XPN, you are right, the 96-bit IV is static. The test groups still include the `"ivLen"` property though it will never vary from 96. Seeing as this is done with AES-GCM-SIV in the same table, I'll update this property from "within domain" to "96".

**Comment by abkarcher** [comment]
Thanks @celic - another note, realized the same thing also seems to apply to saltLen in the same table.

**Comment by celic** [comment]
Thanks for the heads up. I'll get it later today.
