### ISSUE TITLE
KAS-SSC-FFC or KAS-FFC-SSC?

### ISSUE THREAD

**Issue by chapman-s** [usnistgov/ACVP#1017]
**Protocol Section**
Is your question regarding a specific section of the protocol?  You can link it here.
https://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56ar3/ssc/ffc/sections/05-capabilities.adoc

**Protocol Question**
What is your question? 
The ACVP github JSON capabilities page for KAS-FFC-SSC claims in Table 1 that the algorithm attribute string is "KAS-SSC-FFC", but in the Registration JSON Example, the algorithm attribute is set to "KAS-FFC-SSC" instead. Which is the correct value?

Thank you

**Comment by Kritner** [comment]
Sorry about that, KAS-[ECC/FFC/IFC]-SSC is the correct version.
