### ISSUE TITLE
KAS-ECC 56Arev3 does not accept what the specs define

### ISSUE THREAD

**Issue by QuentinGouchet** [usnistgov/ACVP#1026]
https://usnistgov.github.io/ACVP/draft-hammett-acvp-kas-ecc-sp800-56ar3.txt lists P-192, B-163 and K-163 as acceptable curves, but the server rejects them:

"KAS-ECC-SSC-Sp800-56Ar3: Invalid DomainParameterGenerationMethods supplied: P192,B163,K163, intersect : 12, supplied: 15"

**Comment by Kritner** [comment]
Can you provide your full registration please?

**Comment by Kritner** [comment]
This seems to be an issue with the specification, as per SP800-56Ar3, the curves listed in the [comment above](https://github.com/usnistgov/ACVP/issues/1026#issue-711517463) don't provide a sufficient security strength:

![image](https://user-images.githubusercontent.com/8814983/94680775-4e0fd880-02f0-11eb-9fd7-88046ad700d9.png)

The specification will need to be updated to exclude those curves.

**Comment by QuentinGouchet** [comment]
That makes sense. Thank you!
