### ISSUE TITLE
TLS 1.3: is it supported?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#1027]
The README indicates TLS v1.3 is supported.

But I am getting the following error:

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Unable to map TLS-v1.3-tls-RFC8446 - index 0 to an internal algorithm id."
    ]
  }
]
```

Request

```
[
  {
    "acvVersion":"1.0"
  },
  {
    "isSample":false,
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "algorithms":[
      {
        "revision":"RFC8446",
        "algorithm":"TLS-v1.3",
        "mode":"tls",
        "prereqVals":[
          {
            "algorithm":"HMAC",
            "valValue":"same"
          },
          {
            "algorithm":"SHA",
            "valValue":"same"
          }
        ],
        "hmacAlg":[
          "SHA2-256",
          "SHA2-384",
          "SHA2-512"
        ]
      }
    ]
  }
]
```

The SPEC for TLS 1.3 is inconsistent for the documentation of the algorithm, mode and revision compared to the shown example.

**Comment by Kritner** [comment]
Ah, looks like there are a few mistakes probably from using the original TLS testing as a template.  These are the mistakes I'm seeing:
![image](https://user-images.githubusercontent.com/8814983/94667528-ee5c0200-02dc-11eb-9107-e84f503ea36e.png)
![image](https://user-images.githubusercontent.com/8814983/94667680-2105fa80-02dd-11eb-9e28-f50312addefa.png)

any instances of "kdf-components" / "tls" / "1.0" should actually be "TLS-v1.3" / "KDF" / "RFC8446"
![image](https://user-images.githubusercontent.com/8814983/94667580-ffa50e80-02dc-11eb-9663-2bc5af434c62.png)

**Comment by smuellerDD** [comment]
Am Mittwoch, 30. September 2020, 11:26:36 CEST schrieb Russ Hammett:

Hi Russ,

> Ah, looks like there are a few mistakes probably from using the original TLS
> testing as a template.  These are the mistakes I'm seeing:
> ![image](https://user-images.githubusercontent.com/8814983/94667528-ee5c020
> 0-02dc-11eb-9107-e84f503ea36e.png)
> ![image](https://user-images.githubusercontent.com/8814983/94667680-2105fa8
> 0-02dd-11eb-9e28-f50312addefa.png)
> 
> any instances of "kdf-components" / "tls" / "1.0" should actually be
> "TLS-v1.3" / "KDF" / "RFC8446"
> ![image](https://user-images.githubusercontent.com/8814983/94667580-ffa50e8
> 0-02dc-11eb-9663-2bc5af434c62.png)

Sweet, this means that my registration request should be appropriate as I base 
it on the example.

Yet, the server rejects my registration.

Ciao
Stephan

**Comment by Kritner** [comment]
Note your registration (as specified in https://github.com/usnistgov/ACVP/issues/1027#issue-711718504) had:

```json
"revision":"RFC8446",
"algorithm":"TLS-v1.3",
"mode":"tls",
```

the "mode" needs to be "KDF" rather than "tls", if after doing that change (or if it was just a typo in opening the issue) it still isn't working, let me know!

**Comment by smuellerDD** [comment]
Am Mittwoch, 30. September 2020, 11:34:59 CEST schrieb Russ Hammett:

Hi Russ,

> Note your registration (as specified in
> https://github.com/usnistgov/ACVP/issues/1027#issue-711718504) had:
> 
> ```json
> "revision":"RFC8446",
> "algorithm":"TLS-v1.3",
> "mode":"tls",
> ```

Using:

```
        "revision":"RFC8446",
        "algorithm":"TLS-v1.3",
        "mode":"KDF",
```

Then I had to add a running mode (the spec indicates it is optional).

> 
> the "mode" needs to be "KDF" rather than "tls", if after doing that change
> (or if it was just a typo in opening the issue) it still isn't working, let
> me know!

After adding DHE as running mode, I get:


```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Invalid JSON provided.",
    "context": "The JSON value could not be converted to System.String. Path: 
$.runningMode | LineNumber: 0 | BytePositionInLine: 256."
  }
]
```

Full registration:

```
[
  {
    "acvVersion":"1.0"
  },
  {
    "isSample":false,
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "algorithms":[
      {
        "revision":"RFC8446",
        "algorithm":"TLS-v1.3",
        "mode":"KDF",
        "prereqVals":[
          {
            "algorithm":"HMAC",
            "valValue":"same"
          },
          {
            "algorithm":"SHA",
            "valValue":"same"
          }
        ],
        "hmacAlg":[
          "SHA2-256",
          "SHA2-384",
          "SHA2-512"
        ],
        "runningMode":"DHE"
      }
    ]
  }
]
```


Ciao
Stephan

**Comment by Kritner** [comment]
`runningMode` should be a `string[]` not a `string` within the registration

**Comment by smuellerDD** [comment]
Confirmed, working - sorry, but the one statement regarding the array is what I overlooked.

Maybe it would be helpful if the example contains a runningMode definition considering it is mandatory.

Please close it at your discretion. Thank you.
