### ISSUE TITLE
Unhelpful server response error for incorrect vector response data

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#1028]
We ran into a situation where we were pushing a response to a vector set provided by the client which resulted in a 500 and `Internal service error. Contact service provider.`

After some debugging of what the vendor provided it turns out that their responses had the key `vsid` rather than `vsId` which was the cause of the error.

The error provided by ACVP wasn't all that helpful in debugging the issue so I thought I'd raise this to see if there was an improvement.  I would have expected a 400 as it was really a bad request and a message describing why.

**Comment by Kritner** [comment]
@AlexThurston can you provide more information about the nature of the error? was it on the post of the bad file, or the attempt as getting the verdict of a successfully posted bad file?  Do you have a vsId for reference?

From the above comment I'm *guessing* it was on the post, not the get, but just wanted to double check.

**Comment by AlexThurston** [comment]
Sorry, I should have given you more info than what I provided.  Although I'm not sure that that the problem is necessarily tied to a specific test session or vector set. I'm pretty sure you could reproduce it using any of them.

Route: **POST** `/testSessions/{testSessionId}/vectorSets/{vectorSetId}/results`
Test Session: `116093`
Vector Set: `330157`

Basically, the response looks like this:
```json
[
    {
        "acvVersion": "1.0"
    },
    {
        "vsid": 330157,
        "testGroups": [
            {...}
        ]
    }  
]
```

Notice the `vsid` key has a lower case `i` where it should have been `vsId`.  This was the problem, but it produced a boilerplate 500 and error which didn't necessarily help debug the issue.  At the very least, it should probably be 400.

**Comment by dmchodnicki** [comment]
This item has been incorporated into a new Error Code Enhancement ticket and is therefore being Closed.  Please refer to #1070  for future updates.
