### ISSUE TITLE
Created OE that causes server to 500 error when fetched.

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1029]
Hi,

I am reasonably certain that I created an OEs that has no dependencies and I suspect whenever it it loaded be it via a search or for example via:

```/acvp/v1/oes?offset=21597&limit=20```

or 

```https://demo.acvts.nist.gov:443/acvp/v1/oes?name[0]=contains:Bouncy```

The Server returns a 500 error.

If I search for something else or navigate to a page where that OES will not be found the server returns a page of results.
Subject that created offending entry:

```EMAILADDRESS=info@cryptoworkshop.com, CN=www.cryptoworkshop.com, O=Crypto Workshop Pty Ltd, L=Melbourne, ST=Victoria, C=AU```

If this is the case then I would like to apologise to everyone.

MW

**Comment by Kritner** [comment]
Thanks @mwcw, a fix for this will be in the next release.

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.13](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.13).

**Comment by Kritner** [comment]
This change is now on prod in release https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.13
