### ISSUE TITLE
ECDSA SigGen K-409 and K-233 R & S padding?

### ISSUE THREAD

**Issue by mtdownz** [usnistgov/ACVP#1034]
When requesting sample vectors and responses from the Demo server for ECDSA Signature Generation using curves K-409 and K-233 (any SHA value) we noticed that the sample responses for the both values 'R' and 'S' are being padded with an additional byte '00' at the beginning. Is this the intended behavior for the these test vectors using these curves? We feel this is incorrect. This behavior was also not present when testing using the NIST CAVS tool.

Thanks.

**Comment by celic** [comment]
Is the padding entirely ignored from the value? As even without the padding there are enough bits to form a 409-bit or 233-bit value?

**Comment by celic** [comment]
If you have a vector set ID available I could look at, that would also be helpful.

**Comment by mtdownz** [comment]
The "vsId" is 308095 URL:  "\/acvp\/v1\/testSessions\/103623\/vectorSets\/308095"

Example of the issue in the response file showing the first byte of r and s is '00':
        "tgId": 17,
        "qx": "0193C7B2E6FE0B1F03DB8E94034AD2CE72E09EE48B8A7A30368931F72F9D",
        "qy": "00FF5CE045B7DB157A8D2C7A8E3A0FAC27CCCCD7940F019DC295D0CBECD0",
        "tests": [
          {
            "tcId": 161,
            "r": "005E5103DCC230BADEBAE3EA7C55C60AA816D94C7FFFD7A1007F38E2A682",
            "s": "0028DBF5B5E54A5CE7E3F53F4596C9B50E6811E503172B138F39FC9196A6"
          },
          {
            "tcId": 162,
            "r": "0061016E1189DF983A739CC1392B63ADE1E0EDAF29D13B37C826797BFF93",
            "s": "003C6E1A049BCD1A3F57C23ECAEE43E8D8C5E7E709D77DD1A89BC6A29899"
          },
          {
            "tcId": 163,
            "r": "006C8257085B86CB1F14F1B9001994B9A7DDE2A7528709B07CED6FECAAF6",
            "s": "0046474D3B01A87064714C0420F323A72798784B562BAFAAC7DC80967B4B"
          },

**Comment by celic** [comment]
This is correct behavior from the server. This group is for a 233-bit curve, so for consistency, all bitstrings have a total of 240 bits in order to have complete bytes. Because 233 is one bit over the byte boundary, the server pads all bitstrings to be 240 bits in length. The client should grab the 233 right most bits to be each value. The padding is intended to make the bitstrings more consistent as some bitstrings will start with `01` and the rest with `00` to represent the odd bit over the byte boundary.

**Comment by mtdownz** [comment]
Thanks Chris.

**Comment by mtdownz** [comment]
Hi Chris, 
In looking at this further we don't think what you are describing is occurring?  The R & S components of an ECDSA signature are not field elements: They are reduced modulo the order of the curve, and the order of K-233 is encoded in 29 bytes rather than 30 (which would be needed to encode a field element):
n = 0x80 00000000 00000000 00000000 00069d5b b915bcd4 6efb1ad5 f173abdf

Can you continue to look into this for us?
