### ISSUE TITLE
500 Errors at login

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1035]
Hi,
Since ~ 10:00am  UTC+10  we have been getting 500 errors at login.

Our login request:

```[{"acvVersion":"1.0"},{"password":"<------->"}]```

SubjectDN:
EMAILADDRESS=info@cryptoworkshop.com, CN=www.cryptoworkshop.com, O=Crypto Workshop Pty Ltd, L=Melbourne, ST=Victoria, C=AU

MW

**Comment by jbarnesweb** [comment]
I'm getting 500 HTTP status, with the error message "Internal service error. Contact service provider."

**Comment by Kritner** [comment]
Thanks, I'll be taking a look shortly

**Comment by Kritner** [comment]
I see the issue.  It's still pretty early here, but once folks start waking up I'll have
someone with access to the environment get it back up and running.

Thanks for the report and your understanding! 👍

**Comment by Kritner** [comment]
The issue has been corrected and the environment should be available.
