### ISSUE TITLE
Odd verdict or testvector-request.json

### ISSUE THREAD

**Issue by QuentinGouchet** [usnistgov/ACVP#1036]
I received strange json files back from the ACVP production server, such as this verdict:
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Orleans Client failed to initialize after several attempts. Is the Orleans cluster running and accessible?"
  }
]

Or this testvector:
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Orleans Grain did not fulfill expectations after retry attempts."
  }
]

Check testID 2780 on production server. Thanks!

**Comment by Kritner** [comment]
Taking a look now

**Comment by Kritner** [comment]
We had an issue with one of our internal services, things should be working their way through the queue now.
