### ISSUE TITLE
SHA3 Zero Message Length - Bug?

### ISSUE THREAD

**Issue by mtdownz** [usnistgov/ACVP#1039]
When requesting vectors (Demo Server) for SHA3 and setting the "inEmpty" field to either true or false the server returns zero length vectors regardless.

Set to false vector set:
/acvp/v1/testSessions/120299/vectorSets/351695

Set to true vector set:
/acvp/v1/testSessions/120300/vectorSets/351696

**Comment by celic** [comment]
Yup, I see the issue. You are right. We are prepping a release soon and I'll see if I can slip this fix in.

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.13](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.13).

**Comment by mtdownz** [comment]
Thanks.

**Comment by Kritner** [comment]
@mtdownz will you have a chance to confirm this change on the demo environment?

**Comment by Kritner** [comment]
This change is now on prod in release https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.13
