### ISSUE TITLE
Cannot post responses on demo server

### ISSUE THREAD

**Issue by QuentinGouchet** [usnistgov/ACVP#1040]
I obtained testvectors yesterday and am trying to post the responses, but keep getting this error:

```
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Internal service error. Contact service provider."
  }
]
```

Quickly followed by:

```
 {
    "acvVersion": "1.0"
  },
  {
    "error": "Access denied! Reason: TOTP Window has already been used"
  }
]
```

because of the re-try.

I am trying to post the vectors for the following testIDs:

120556 120512 120506 120507 120559 120562 120560 120561 120533 120534 120532 120535 120551 120549 120550 120542 120545 120543 120548 120547 120541 120544 120546 120552 120565

Thanks!

**Comment by celic** [comment]
The second response is normal, you cannot use the same TOTP multiple times to obtain a JWT access token. That is not an error. The `internal service error` definitely is however. We will take a look.

**Comment by QuentinGouchet** [comment]
Right, exactly :)
Thanks Chris!

Quentin Gouchet
-----------------------------

**Comment by celic** [comment]
Nothing was POSTed for 120556, 120512, or 120506. Before I check the rest, the error was during the POST request to `/testSessions/120506/vectorSets/352731/results`? We don't have any logs from yesterday or today stating that the POST was even attempted. This is on Demo correct?

**Comment by QuentinGouchet** [comment]
hi Chris,

I attempted to post but it was never successful. The error happens when I
attempt to post the responses.

I generated vectors for those testIDs yesterday yes!

Quentin Gouchet
-----------------------------

**Comment by celic** [comment]
What I am seeing is after GETs on all the individual vector sets, a GET is run on `testSession/<id>/results`, and that's it. Nothing else comes in to the server on that test session, even on the HTTPS level. I'll keep looking and see if I can figure anything out.

**Comment by celic** [comment]
Timestamps of when the requests were made would be very helpful. Also is your client making any other requests simultaneously as the POST of the result?

**Comment by QuentinGouchet** [comment]
hi Chris,

No my client is only handling this one post request. Maybe my client is
failing to even reach out to the ACVP server.

All those requests were Oct 15 between 12pm and 3pm CST.

Quentin Gouchet
-----------------------------

**Comment by celic** [comment]
Do all of these contain RSA vector sets?

**Comment by QuentinGouchet** [comment]
Not all. But many yes!

Those vsID have RSA in it:

Vector set ID 352986 RSA                  sigVer           UNVERIFIED

Vector set ID 352983 RSA                  keyGen           UNVERIFIED

Vector set ID 352985 RSA                  sigGen           UNVERIFIED

Vector set ID 352903 RSA                  sigGen           UNVERIFIED

Vector set ID 352905 RSA                  sigVer           UNVERIFIED

Vector set ID 352901 RSA                  keyGen           UNVERIFIED

Vector set ID 352987 RSA                  sigVer           UNVERIFIED

Vector set ID 352984 RSA                  sigGen           UNVERIFIED

Vector set ID 352982 RSA                  keyGen           UNVERIFIED

Vector set ID 352904 RSA                  sigGen           UNVERIFIED

Vector set ID 352902 RSA                  keyGen           UNVERIFIED

Vector set ID 352906 RSA                  sigVer           UNVERIFIED

**Comment by smuellerDD** [comment]
Am Freitag, 16. Oktober 2020, 20:48:33 CEST schrieb Chris Celi:

Hi Chris,

> Nothing was POSTed for 120556, 120512, or 120506. Before I check the rest,
> the error was during the POST request to
> `/testSessions/120506/vectorSets/352731/results`? We don't have any logs
> from yesterday or today stating that the POST was even attempted. This is
> on Demo correct?

The error happens during refreshing multiple log ins.

Ciao
Stephan

**Comment by QuentinGouchet** [comment]
hi Chris,
I confirm that posting each testID independently works! It's all together
that seems to create issues.

Quentin Gouchet
-----------------------------

**Comment by celic** [comment]
Well one of the bunch should be failing. Did all the testsessions work just fine?

**Comment by QuentinGouchet** [comment]
hi Chris,

I believe we have internally realized what the issue was: another colleague
requested some of the vectors but I was trying to post all the responses.
The certificates and JWT tokens didn't match.

Do you think it would be possible for the ACVP server to send such an error
message, indicating that the users/certs do not match?

Quentin Gouchet
-----------------------------

**Comment by celic** [comment]
Likely no, we do not want to provide too much detail in error messages surrounding authentication. We do not want a user to learn information about anything another user is performing. There are a lot of different errors that can happen around the JWT unfortunately, and we don't want to pass back the exact error every time.
