### ISSUE TITLE
Documentation: PBKDF Documentation appears to be incorrect

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#1042]
**Protocol Section**
https://usnistgov.github.io/ACVP/draft-celi-acvp-pbkdf.html#name-registration-example

The table suggests that the registration contains an array of capabilities, but the example does not show this.

https://usnistgov.github.io/ACVP/draft-celi-acvp-pbkdf.html#section-7.3-3

Wondering which is correct.

**Comment by celic** [comment]
Table is correct. Didn't we talk about/resolve this issue a while ago?

**Comment by AlexThurston** [comment]
I thought we did.  Maybe it was with the old format of the documentation it got lost in translation.

**Comment by celic** [comment]
If the documentation is wrong, there's no reason to close. I just remembered fixing it. Likely it was during that time and somehow got lost in the shift.

**Comment by AlexThurston** [comment]
Sorry, I hit the wrong button.  I mean to comment, not close :P

**Comment by abkarcher** [comment]
Hello,

In an expansion of this, it seems that the spec indicates that the vector set for PDF consists of an "algorithm" and "Mode" similar to other KDFs via table 3 and figure 4  (e.g. "kdf-components" algorithm) - however, upon requesting PBKDF vectors, the vector set just has algorithm value and it is "PBKDF".

Thanks,
Andrew

**Comment by celic** [comment]
Also correct, will fix at the same time.
