### ISSUE TITLE
AES CCM AAD Length - Documentation Error or Bug?

### ISSUE THREAD

**Issue by mtdownz** [usnistgov/ACVP#1043]
Hello,

The posted documentation for AES CCM states that the AAD length is the domain ranging from 0 to 524288 (Table 6). Under the original CAVS testing this field was limited to 256-bits. I tested this field on the demo server and it did indeed accept the full domain range but only returned vectors with a maximum AAD length of 256-bits. Is this a documentation error or a server bug error?

Documentation reference (Table 6)
https://usnistgov.github.io/ACVP/draft-celi-acvp-symmetric.html#name-aes-requirements-covered

Test Vector set:
/acvp/v1/testSessions/121603/vectorSets/360346

**Comment by Kritner** [comment]
It's not really a documentation issue or a bug.  We don't *necessarily* test against the full range of "accepted" values in a registration.  We could introduce additional testing against the registered properties at any point though, so rather than update the spec to change the "allowed values", we could just start testing against values that are greater than 256 bits, as an example.  

That is the intention of this sort thing, it likely exists elsewhere as well, but thanks for calling it out.

**Comment by mtdownz** [comment]
I'm having a small problem with your response. The value 524288 bits is nowhere near what the server can test, and therefore I struggle to understand why this value is being advertised in the documentation. Most max values are what is testable or at least close. We understand that there are other theoretical values that an implemented algorithm can support. However, we need to be clear on what is testable.
If a validation certificate is issued for a CCM algorithm (or any other algorithm) that claims a specific parameter value of up to 524288 bits that in fact was only tested for 256-bits, isn't that a concern?
Thanks.

**Comment by celic** [comment]
The server can test 524288 under the ECMA conformance. It is intended as ECMA has stricter parameter requirements that ACVP made these changes to support.

**Comment by mtdownz** [comment]
To be clear, only 256-bits appears to be supported by the ACVP servers currently. So it sounds like this value will indeed be updated (at some point) to support 524288 or other much larger values? 
Thanks.

**Comment by celic** [comment]
The server does support the larger value. But you need to add a conformance
to ECMA in the registration.

**Comment by mtdownz** [comment]
Okay. So for SP 800-38C conformance we can assume the value will remain as it was with CAVS i.e. 256-bits.
Thanks. This is now clear for me.
