### ISSUE TITLE
TLS v1.3: returned data definition

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#1046]
With the update of the TLS1.3 specification, there is the following result required which neither matches the RFC nor the example:

- serverEarlyTrafficSecret - I guess you mean the early_exporter_master_secret? (example and specification seem to be wrong here)

Also, Chris, you mentioned that you wanted the additional data for debugging. But wouldn't it be equally important to get the early secret, handshake secret and master secret?

**Comment by smuellerDD** [comment]
Just for the records, I was able to have a full complete and passing test round with TLS v1.3 (vsID 364888).

**Comment by smuellerDD** [comment]
One hint: you may want to add to the spec that the provided input data is pre-hashed data.

**Comment by Kritner** [comment]
> serverEarlyTrafficSecret - I guess you mean the early_exporter_master_secret? (example and specification seem to be wrong here)

yes, sorry about that.

**Comment by Kritner** [comment]
This change is on demo

**Comment by Kritner** [comment]
This change is on production in release [v1.1.0.14](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14)

**Comment by bfussell** [comment]
@smuellerDD @Kritner The comment above "you may want to add to the spec that the provided input data is pre-hashed data", are you referring to the ClientHelloRandom, ServerHelloRandom, etc. ?

In addition, are these values then hashed and used in place of hashing the entire ClientHello and ServerHello exchanges since "message construction that is defined by the protocol for messages such as ClientHello, ServerHello, etc" are not in scope ?

Thanks !

**Comment by Kritner** [comment]
It's been a while, but IIRC there was protocol specific information that would normally go into the back and forth between the two parties, that information was encoded within the ClientHelloRandom, ServerHelloRandom, etc.  The information contained within those messages would be things such as capabilities available, perhaps a certificate, other metadata that is used to communicate/negotiation between the parties.

All of that information is outside of the scope of what the testing's intention is - that is to test ***only*** the KDF portion of TLS v1.3.

All inputs from the prompt file are expected to be used as they are given as inputs into the KDF.

As an example for the "derived early secret":

```
earlySecret = _hkdf.Extract(hashOutputLenBits, preSharedKey);

clientEarlyTrafficSecret = DeriveSecret(earlySecret, "c e traffic", clientHelloRandom);
earlyExporterMasterSecret = DeriveSecret(earlySecret, "e exp master", clientHelloRandom);

derivedEarlySecret = DeriveSecret(earlySecret, "derived", BitString.Empty());
```

On our end we'd be checking the above responses from the IUT match our own, given the provided `preSharedKey`, and `clientHelloRandom` in the prompt file - though note there are 2 other steps and several other checked values that go into the full validation process.

**Comment by smuellerDD** [comment]
@bfussell I meant the reference to the shared secret "z" that is provided as part of the test vector. Z usually is the direct output of the DH operation.

RFC 8446 says:

```
Derive-Secret(Secret, Label, Messages) =
            HKDF-Expand-Label(Secret, Label,
                              Transcript-Hash(Messages), Hash.length)
```

It looks to me that Z in the test vector is rather the hashed DH shared secret instead of the plain shared secret.

**Comment by bfussell** [comment]
@smuellerDD @Kritner Thanks guys ! That addressed my confusion.
