### ISSUE TITLE
SP800-56Cr1 include "l" value from registration in each Test Group.

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1054]
Hi,

Would it be possible to include the "l" value from the registration request in each vector "testGroup" please for OneStep please?

This would allow tests runners to resolve the length of the derived keying material without have to pass it out of band or assume a fixed value.

MW

**Comment by Kritner** [comment]
This change will be on demo from release [v1.1.0.14](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14) after the scheduled maintenance.

**Comment by Kritner** [comment]
This change is on production in release [v1.1.0.14](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14)
