### ISSUE TITLE
Test session expired earlier than the expiresOn specified

### ISSUE THREAD

**Issue by kwong-cygnacom** [usnistgov/ACVP#1058]
DEMO returned this error:

[{"acvVersion":"1.0"},{"error":"The provided JWT expired at 2020-10-27 08:31:55Z and is no longer valid. The JWT claims may be refreshed through the renewal process described in the specification."}]

for this test session:

[
  {
    "acvVersion": "1.0"
  },
  {
    "url": "/acvp/v1/testSessions/122650",
    "createdOn": "2020-10-27T04:01:55.6605366-04:00",
    "expiresOn": "2020-11-26T04:01:55.6605381-05:00",
    "vectorSetUrls": [
      "/acvp/v1/testSessions/122650/vectorSets/364666"
    ],
    "publishable": true,
    "passed": false,
    "isSample": false,
    "accessToken": <token>
  }
]

**Comment by Kritner** [comment]
That is *JWT* expiration, not the test session.  You need to renew your JWT.  They only have a lifetime of 30 minutes.

**Comment by celic** [comment]
Also do not post your access tokens to any public forums...

**Comment by kwong-cygnacom** [comment]
Sorry for posting the access token.
