### ISSUE TITLE
KAS-IFC-SSC validation stuck in initial state

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#1060]
Environment: Demo
TestSession: 125794
Validation Request: 15396
Algorithm: KAS-IFC-SSC

***ACVP [STATUS][acvp_run:3270]--> GET Response:

[
  {
    "acvVersion": "1.0"
  },
  {
    "url": "/acvp/v1/requests/15396",
    "status": "initial"
  }
]

If I submit other algorithms such as KAS-FFC-SSC or KAS-ECC-SSC they get approved rather quickly as expected.

A related question once this request is approved. Once we complete the validation on demo we used to be able to GET the whole set of validation information including capabilities and the algorithm support. Is that still supposed to work on demo ? All I get now is:

***ACVP [INFO][log_network_status:1459]--> GET...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/validations/41391
	Resp:
[
  {
    "acvVersion": "1.0"
  },
  {
    "url": "/acvp/v1/validations/41391",
    "validationId": "A10214",
    "moduleUrl": "/acvp/v1/modules/11821",
    "oeUrls": [
      "/acvp/v1/oes/21278",
      "/acvp/v1/oes/21663"
    ]
  }
]

**Comment by celic** [comment]
There's an error on the server certifying 15396. Was this submitted on Tuesday 11/10?

**Comment by bfussell** [comment]
Yes, submitted on Tuesday.

**Comment by celic** [comment]
Fix should go out later today by 4pm.

**Comment by celic** [comment]
The fix is going out with the maintenance scheduled for today. Please test when you get the chance when the servers are back up.

**Comment by bfussell** [comment]
Fix looks good. 
Any input my second query, how to dump the entire validation json, doesn't seem to work like it did previously.
