### ISSUE TITLE
AES-GCM registration documentation issue and/or bug

### ISSUE THREAD

**Issue by kwong-cygnacom** [usnistgov/ACVP#1062]
Documentation for AES-GCM in Table 6 of https://usnistgov.github.io/ACVP/draft-celi-acvp-symmetric.html specifies:

aadlen: {"Min": 0, "Max": 65536, "Inc": any}
ivLen: {"Min": 8, "Max": 1024, "Inc": any}
payloadLen: {"Min": 0, "Max": 65536, "Inc": any}

but SP 800-38D says "Although GCM is defined on bit strings, the bit lengths of the plaintext, the AAD, and the IV shall all be multiples of 8, so that these values are byte strings."

so these table entries should make it clear that an increment that's a multiple of 8 is required.

If any of the following is sent:

"aadLen": [ { "Min": 0, "Max": 104, "Inc": 8 } ]
"ivLen" [ {"Min": 8, "Max": 1024, "Inc": 8} ]
"payloadLen": [ { "Min": 0, "Max": 2048, "Inc": 8 } ]

the server will return these errors:

"ACVP-AES-GCM-1.0: Invalid AadLen Modulus supplied: Invalid Domain Segment supplied.  Domain Segment {Min: 0, Max: 104, Increment 1} contained values (1) that were not a multiple of 8.  AadLen Modulus contained values that were not a multiple of 8"

"ACVP-AES-GCM-1.0: Invalid ivLen Modulus supplied: Invalid Domain Segment supplied.  Domain Segment {Min: 8, Max: 1024, Increment 1} contained values (1) that were not a multiple of 8.  ivLen Modulus contained values that were not a multiple of 8"

"ACVP-AES-GCM-1.0: Invalid PtLen Modulus supplied: Invalid Domain Segment supplied.  Domain Segment {Min: 0, Max: 2048, Increment 1} contained values (1) that were not a multiple of 8.  PtLen Modulus contained values that were not a multiple of 8"

**Comment by celic** [comment]
The proper name in JSON for `Inc` is `Increment` fully spelled out. So the server was acting like you provided the default value (1).

**Comment by celic** [comment]
Specs need to be updated for both issues though.

**Comment by kwong-cygnacom** [comment]
Would the default values be either 0 or 8?

**Comment by celic** [comment]
Default value is 1.

**Comment by kwong-cygnacom** [comment]
Default value of 1 bit does not meet the requirement in SP 800-38D that says "Although GCM is defined on bit strings, the bit lengths of the plaintext, the AAD, and the IV shall all be multiples of 8, so that these values are byte strings."

**Comment by celic** [comment]
Yes I know. That is why you are getting an error here. The property name `"Inc"` is not correct, so the property is assuming the default increment of 1, which is not valid for GCM.

**Comment by kwong-cygnacom** [comment]
Got it. Thank you.
