### ISSUE TITLE
Direction property updates to protocol and symmetric got undone

### ISSUE THREAD

**Issue by atvassilev** [usnistgov/ACVP#107]
Unfortunately, PR#105 undid the direction property updates introduced by PR#95 in the v_0.3 branch. Both protocol and sub_symmetric are affected. This needs to be fixed.

**Comment by bfussell** [comment]
!@#$, I'll get on it this morning.

**Comment by atvassilev** [comment]
resolved with PR #108

**Comment by celic** [comment]
Make sure you update your local repositories before making changes! :+1:
