### ISSUE TITLE
Resubmission of Vector Responses on Production Server after Error?

### ISSUE THREAD

**Issue by mtdownz** [usnistgov/ACVP#1074]
**Protocol Section**
https://github.com/usnistgov/ACVP/wiki/How-to-Handle-a-Failed-Vector-Set-in-Production

**Protocol Question**
This Wiki post states that resubmission of test vectors response files is not allowed on production server. We have customers who sometimes need to format their response files manually and thus can introduce an error, especially with formatting. Can vectors be resubmitted if a formatting issue is detected. E.g. We submitted a file today which was missing a double quote (") and an error was thrown by the server. Can this vector session be recovered and the vectors resubmitted? 

Thanks!

**Comment by celic** [comment]
You may wish to run their responses through something like a [JSON Linter](https://jsonlint.com/) before submitting. Send me an email please on this.
