### ISSUE TITLE
Missing module.vendorUrl Error Message?

### ISSUE THREAD

**Issue by mtdownz** [usnistgov/ACVP#1077]
I am receiving the following error when attempting to validate an algorithm using a relevant metadata file. The error message appears to be stating the vendorURL is missing from the module information. However, the vendorURL is present within the module information so I am not sure where to look next.
  "error": "Validation errro(s) on JSON payload.",
  "context": [
     "module.vendorUrl must be provided."

I am using a metadata file format the I have used successfully previously:
```
{
    "vendors": [
        {
            "name": "Vendor Name",
            "website": "https://vendorname.com",
            "emails" : [ "email@vendor.com" ],
            "phoneNumbers": [
                { "number": "+1 123 345 6789", "type": "voice" }
            ],
            "address": {
                "street1": "123 Some Street",
                "locality": "Some city",
                "region": "Some region",
                "country": "Country",
                "postalCode": "12345"
            },
            "contacts": [
                {
                    "fullName": "first last",
                    "emails": [
                        "somename@vendor.com"
                    ],
		      "phoneNumbers": [
                        {
                          "number": "+1 123 345 6789",
                          "type": "fax"
                        },
                        {
                          "number": "+1 123 345 6789",
                          "type": "voice"
                        }
                    ]
                }
            ]
        }
    ],
    "modules": [
      {
        "name": "module name",
        "version": "1.0",
        "type": "Firmware",
        "vendorUrl": "/acvp/v1/vendors/xxxxx",
        "addressUrl": "/acvp/v1/vendors/xxxxx/addresses/xxxxx",
        "contactUrls": [ "/acvp/v1/persons/xxxxx" ],
        "description": "description"
      }
    ],
    "operating_environments": [
        {
            "name": "OE Name",
            "dependencies" : [
              {
                "type": "Hardware",
                "name": "Some name",
                "description": "description"
              }
            ]
        }
    ]
}
```
Any help on this error would be greatly appreciated? Thanks!

**Comment by celic** [comment]
The snippet here is just a sample right? The `xxxxx` in the URLs is replaced with the IDs you are using, correct? Would you be able to attach the true JSON you are using? Or instead list about the time you sent the request to the server?

**Comment by mtdownz** [comment]
Hi Chris,

This is our template and had all the correct values. Actually, the meta data is near identical to the file I sent to you in nFiles for the vectors you generated.

Thanks.

**Comment by mtdownz** [comment]
I added the vendorURL field into the contacts object and this appeared to solve the problem. I haven't needed to do that until now? I'll plan to make the norm moving forward.
Thanks.
