### ISSUE TITLE
Finding ACVTS Metadata IDs of Legacy Validation Data

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#1078]
We're trying to update some OE information of a CAVP validation by following the [wiki](https://github.com/usnistgov/ACVP/wiki/Finding-ACVTS-Metadata-IDs-of-Legacy-Validation-Data).
But we're still not able to find any information like below for a CAVP validation.
![image](https://user-images.githubusercontent.com/50221973/100029371-3c0c6b00-2e45-11eb-88e4-90a87f90ea7f.png)

May I ask if this feature is available yet?

**Comment by celic** [comment]
It is available. You must perform a GET on the old validation. The ID can be acquired by looking at the validation on CSRC. The ID is the last element in the URL.

**Comment by AndrewHYang** [comment]
Thanks. And is it only available for legacy validations starting from "C"?

I got "Internal service error. Contact service provider." when fetching validation A838

**Comment by celic** [comment]
The ID for A838 is 33434, so you attempted a GET on `/acvp/v1/validations/33434`?

**Comment by AndrewHYang** [comment]
Yes. But I was testing with the Demo server. Is it because they don't exist on Demo server?

And can I use PUT to update the OE list of a validation?

**Comment by celic** [comment]
Correct they do not exist in the database there. When validations come in,
we do not add them to the demo database. There is limited validation
information available there.

Still the ID not existing should provide meaningful feedback to the user.

**Comment by AndrewHYang** [comment]
I'm getting 

> "error": "Internal service error. Contact service provider."

**Comment by celic** [comment]
On the PUT you are getting the error? The GET works just fine for me. Can you send me the data you are trying to PUT?

**Comment by AndrewHYang** [comment]
Sorry. I was talking about when I tried GET on validation not existing will get above error. I have not tried  PUT yet. 

I was asking whether I can use PUT to update the OE list before editing a validation. Just in case.

And if that's possible, then I think this issue can be closed. Thanks

**Comment by celic** [comment]
Yes you can use a PUT to update the OE as long as you are able to find the ID. The method I explained works but may be a little cumbersome. I was able to confirm this yesterday.
