### ISSUE TITLE
Unable to register KTS-IFC (OAEP)

### ISSUE THREAD

**Issue by Seamusfish** [usnistgov/ACVP#1079]
I have been trying to register KTS-IFC vectors.

I had a few formatting issues, which I was able to clear up by comparing my capabilities file to the provided examples in the documentation.  The error messages returned by the server were extremely helpful in this regard.

I have hit a wall where the server is giving me the following error:
    "error": "Validation error(s) on JSON payload.",
                         "context": [
                           "KTS-IFC-Sp800-56Br2: General exception. Contact service provider."

This what I currently trying to register (some values have been made generic in this example) :

```
{
    "algorithm": "KTS-IFC",
    "revision": "Sp800-56Br2",
    "iutId": "123456ABCD",
    "function": [],
    "scheme": {
        "KTS-OAEP-basic": {
            "kasRole": [
                "initiator",
                "responder"
            ],
            "l": 256,
            "ktsMethods": {
                "encoding": [
                    "concatenation"
                ],
                "supportsNullAssociatedData": true,
                "hashAlgs": [
                    "SHA2-256"
                ]
            },
            "keyGenerationMethods": {
                "rsakpg1-basic": {
                    "modulo": [
                        2048
                    ],
                    "fixedPubExp": "010001"
                },
                "rsakpg2-basic": null
            }
        }
    }
}
```
If there is any information that you can offer in regards to why the server is rejecting this input, that would be extremely helpful.

Thank you,
Seamus

**Comment by bfussell** [comment]
I currently use this for my development, about as basic as I could make it.

[{"acvVersion":"1.0"},
 {"algorithms":[
  {"algorithm":"KTS-IFC",
   "revision":"Sp800-56Br2",
   "prereqVals":[{"algorithm":"RSA","valValue":"same"},{"algorithm":"RSADP","valValue":"same"},{"algorithm":"SHA","valValue":"same"},{"algorithm":"DRBG","valValue":"same"}],
   "fixedPubExp":"010001",
   "iutId":"CAFEBABE",
   "modulo":[2048,3072,4096],
   "keyGenerationMethods":["rsakpg1-basic"],
   "function":["keyPairGen","partialVal"],
   "scheme":{"KTS-OAEP-basic":{
               "l":512,
               "kasRole":["responder","initiator"],
               "ktsMethod":{"hashAlgs":["SHA2-256"],
                            "supportsNullAssociatedData":true,
                            "encoding":["concatenation"]
}}}}]}]

**Comment by Seamusfish** [comment]
Thank you bfussell.  This helped tremendously to navigate formatting/nesting issues.

**Comment by Kritner** [comment]
Just to have the two "back to back":

```
{
    "algorithm": "KTS-IFC",
    "revision": "Sp800-56Br2",
    "iutId": "123456ABCD",
    "function": [],
    "scheme": {
        "KTS-OAEP-basic": {
            "kasRole": [
                "initiator",
                "responder"
            ],
            "l": 256,
            "ktsMethods": {
                "encoding": [
                    "concatenation"
                ],
                "supportsNullAssociatedData": true,
                "hashAlgs": [
                    "SHA2-256"
                ]
            },
            "keyGenerationMethods": {
                "rsakpg1-basic": {
                    "modulo": [
                        2048
                    ],
                    "fixedPubExp": "010001"
                },
                "rsakpg2-basic": null
            }
        }
    }
}
```

vs

```
{
  "algorithms": [{
	"algorithm": "KTS-IFC",
	"revision": "Sp800-56Br2",
	"fixedPubExp": "010001",
	"iutId": "CAFEBABE",
	"modulo": [2048, 3072, 4096],
	"keyGenerationMethods": ["rsakpg1-basic"],
	"function": ["keyPairGen", "partialVal"],
	"scheme": {
	  "KTS-OAEP-basic": {
		"l": 512,
		"kasRole": ["responder", "initiator"],
		"ktsMethod": {
		  "hashAlgs": ["SHA2-256"],
		  "supportsNullAssociatedData": true,
		  "encoding": ["concatenation"]
		}
	  }
	}
  }]
}
```

Did you get your registration example from the specification @Seamusfish? I think starting out we did have registrations that were more similar to your registration, but we moved away from that several months ago prior to the algorithm having been tested by anyone.  If the samples are outdated, we can put in a change.

Otherwise, it seems that we're making an assumption on a property being included, I'll have to take out that assumption so you get a better error message.

**Comment by Kritner** [comment]
This change is on production in release [v1.1.0.14](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14)
