### ISSUE TITLE
General Exception, Contact service provider

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1081]
Hi,

We got a 

```[{"acvVersion":"1.0"},{"error":"General exception. Contact service provider."}]``` 
while fetching vectors 
```/acvp/v1/testSessions/129000/vectorSets/391884```

I have attached the full set of transcripts, less the session token.

It was a fairly big request.

[Archive.zip](https://github.com/usnistgov/ACVP/files/5613654/Archive.zip)

MW

**Comment by Kritner** [comment]
Looks like we were missing the HMAC 512/256 in our list of acceptable algorithms.  When this change has been deployed to demo I'll update this issue.

Just curious, is there a specific reasoning behind doing so many individual vector sets, rather than posting a larger single algorithm registration?

**Comment by mwcw** [comment]
Thanks for getting back.

Mainly coverage, we implement the entire spec I was originally including using one capability request and populating the relevant arrays with the curves, aux functions and mac methods but we only obtained a small subset of those in the returned vectors.

I guess having a useful amount of paranoia I was worried about that and what that means in terms of certification. 

Perhaps @dghgit should comment here also.

For example, sorry I don't have the test session / vector set ids but here is a summary, I think it was for MQV1. 
I compiled the following from a set of vectors last Friday.

```
Curve:
Requested: B-233 B-283 B-409 B-571 K-233 K-283 K-409 K-571 P-224 P-256 P-384 P-521
Found: B-233 B-283 B-409 B-571 K-233 K-283 K-409 K-571 P-224 P-256 P-384 P-521

Aux Functions:
Requested: HMAC-SHA2-224 HMAC-SHA2-256 HMAC-SHA2-384 HMAC-SHA2-512 HMAC-SHA2-512/224
HMAC-SHA2-512/256 HMAC-SHA3-224 HMAC-SHA3-256 HMAC-SHA3-384 HMAC-SHA3-512 KMAC-128
KMAC-256 SHA2-224 SHA2-256 SHA2-384 SHA2-512 SHA2-512/224 SHA2-512/256 SHA3-224 SHA3-256 SHA3-384 SHA3-512

Found: HMAC-SHA2-384 HMAC-SHA3-384 KMAC-256 SHA2-512/224 SHA3-224


Mac Methods:
Requested: KMAC-256 HMAC-SHA2-384 HMAC-SHA3-384 KMAC-128 HMAC-SHA2-512 HMAC-SHA2-512/256
HMAC-SHA3-256 HMAC-SHA2-512/224 HMAC-SHA3-512 HMAC-SHA2-224 HMAC-SHA2-256 HMAC-SHA3-224

Found: HMAC-SHA2-384 HMAC-SHA3-512 KMAC-256
```

**Comment by Kritner** [comment]
This change is on production in release [v1.1.0.14](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14)

The other question in this issue is related to https://github.com/usnistgov/ACVP-Server/issues/34.  I need to spend some time making sure we have better coverage of all registered capabilities.
