### ISSUE TITLE
General exception while registering KAS HKDF (sp800-56c)

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1082]
Using this registration:

`[{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"KAS-KDF","mode":"HKDF","revision":"Sp800-56Cr1","fixedInfoPattern":"literal[0123456789ABCDEF]||uPartyInfo||vPartyInfo||context||algorithmId||label||l","encoding":["concatenation"],"hmacAlg":["SHA1","SHA2-224","SHA2-256","SHA2-384","SHA2-512","SHA3-224","SHA3-256","SHA3-384","SHA3-512"],"macSaltMethods":["default","random"],"l":1024,"z":[{"min":224,"max":1024,"increment":8}]}]}]
`

results in getting 

` {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "KAS-KDF-HKDF-Sp800-56Cr1: General exception. Contact service provider."
    ]
  }
`

It seems other people have had success, so I assume its something on my end - anyone spot anything wrong? Not currently testing any implementation, just general purpose library registration. 

On another note, This alg seems to use the string "SHA1" instead of "SHA-1" that is used in other algorithms hmac registrations like PBKDF - it would be nice if that string stayed consistent.

Thanks for any help,
Andrew

**Comment by celic** [comment]
Thanks for the catch on SHA1 vs SHA-1. Looking at the logs, I think that is the error though. Did you try the registration with `SHA-1` instead of `SHA1`?

**Comment by abkarcher** [comment]
Hello,

Yes, i did - the error I get is -

`[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "KAS-KDF-HKDF-Sp800-56Cr1: Error converting value \u0022SHA-1\u0022 to type \u0027NIST.CVP.Crypto.Common.Hash.ShaWrapper.Enums.HashFunctions\u0027. Path \u0027hmacAlg[0]\u0027, line 1, position 254."
    ]
  }
]
`

Thanks,
Andrew

**Comment by celic** [comment]
That's not an error a user should be seeing... From what I see in the code, SHA-1 isn't supported by HKDF here. If it appears in the documentation, then that is a mistake. So please remove SHA-1 from your registration. Regardless, the error message should be better here.

**Comment by abkarcher** [comment]
Ah okay, was following the documentation where it does appear. Makes sense that its not supported though. Thanks!

Andrew

**Comment by dmchodnicki** [comment]
An additional update to remove SHA-1 from the list of "Valid HMAC Functions" is no longer required and this item is being Closed.  SHA-1 was removed from the list with a spec update on 3/9/21.  However, based on work associated with ACVP Issue #1170 it was determined that SHA-1 may indeed be used as a valid HMAC function.  Therefore, it was added back to the list with a spec update on 6/11.
