### ISSUE TITLE
Vectors not available even after 220+ minutes.

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1086]
Hi,

As far as I can see for the last 8 hours or so we have had continual retry for availability of vectors.

It let this run for over 220 minutes and the vectors did not become available.

I have attached the registration request and the response to that request.

MW

[Archive.zip](https://github.com/usnistgov/ACVP/files/5634017/Archive.zip)

**Comment by Kritner** [comment]
Thanks, I confirmed there is an issue with the demo environment.  It's still early here, but I pinged the infrastructure team as a heads up for once they're available.

**Comment by Kritner** [comment]
This should be resolved now.  Let me know if there are any further issues.
