### ISSUE TITLE
overflowCounter in AES CTR

### ISSUE THREAD

**Issue by davyrouillard** [usnistgov/ACVP#1087]
**Protocol Section**
https://usnistgov.github.io/ACVP/draft-celi-acvp-symmetric.html#name-block-cipher-algorithm-capa
**Protocol Question**
Hello,

I do not well understand what is the meaning of the following parameter for AES CTR:
`overflowCounter | Indicates if the implementation can handle a counter exceeding the maximum value`

What is the behaviour of a implementation that can handle a counter exceeding the maximum value ? It must not raise an error, rollback the counter to the initial value, something else ? 

Thanks you
Davy

**Comment by celic** [comment]
This option indicates when the client sees a counter towards the upper limit they can support, it will wrap around back to the minimum after being incremented again. (The CTR mode standard does not specify incrementing or decrementing, so this also applies to the lower bound if the option is enabled).

**Comment by davyrouillard** [comment]
OK, thanks you very much.
