### ISSUE TITLE
RSA Algorithm JSON Specification missing valid hashAlg values

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP#1092]
tables 7, 8, 9, 10, 11 of the spec omits SHA2-512/224 and SHA2-512/256 as valid hashAlg values.  I was able to generate test vectors with those options (see tsId 131859). Also, should the table 7 caption be "sigGen FIPS186-4" instead of "sigGen 1.0"?

**Comment by celic** [comment]
Correct. This spec needs to be updated anyways for the removal of SHA-1 from Signature Generation.
