### ISSUE TITLE
KAS Key Confirmation using KMAC Customization String

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1094]
Hi

We have gotten KMAC and the KDFs working but we are unable to get Key Confirmation and the tags to match.

Is there a customization string for KMAC?

There is not one in the vectors, does it need to be specified, computed or is there a fixed value?

MW

**Comment by Kritner** [comment]
We're using a customization string of "KC" to mimic the customization of "KDF" when using KMAC for a KDF.  This would be a "testing specific" requirement as it is not called out in SP800-56* as such.  

I ***thought*** this was called out in the ACVP specification, but at a glance I didn't find it.  The documentation should be updated to reflect that "KC" is the customization string used for key confirmation when using KMAC.

**Comment by mwcw** [comment]
Sorry I hit the wrong button.
