### ISSUE TITLE
Utilize "length" specified within TestGroup for TestCases

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#110]
This might not be a good title, but through integration testing with `AES-GCM` it became apparent that different (CAVS) implementations of algorithms represent a `zero length hex string` differently.  In `AES-GCM`, a zero length plaintext is represented as `""`, whereas in `AES-CCM`, the same is represented as `"00"`.  

It would be beneficial to decide on a consistent way to represent this, and @celic may have some additional input as it relates to `SHA`.  Regardless of the decision, both the client and server should take into account the `PropertyLen` from the `TestGroup` when parsing hex strings.  As it currently stands, that does not appear to be the case.

**Comment by celic** [comment]
My input here is that when reading in the `plaintext` (or `message` for SHA variations), the specified `ptLen` cannot be ignored. There are bit oriented algorithms that will specify a `messageLen` that must be accounted for when reading in the `message`. 

For example...
```
{
    "msgLen": 1,
    "msg": 80
}
```

corresponds to the bit `1` even though the hex could refer to different messages. The length distinguishes it. This is necessary when using hex to convey messages that can be odd (non-multiple of 8) bit lengths. 

With this in mind, as long as the lengths are read in if specified, `"00"` and `""` will resolve to the same value.

**Comment by atvassilev** [comment]
I think we reached a consensus resolution on this issue. Can it be closed?

**Comment by hbooth** [comment]
Consensus maybe, but has anything been updated in the specifications to reflect this consensus? I think we need to make sure that we add something in the documentation with a SHALL/MUST requirement.

**Comment by atvassilev** [comment]
Well how about the submitter of the issue create a PR with what we discussed on the last call and we go from there? 

I think if someone opens an issue and some action/discussion takes place about it, it falls upon that person to follow up with the resolution of the issue unless someone else is assigned to it.  Alternatively, I could start assigning issues to people but this implicit and informal agreement seems preferable to me.

**Comment by hbooth** [comment]
I rather like the idea of explicit assignments. The github issue tracking system supports that. Perhaps whenever our discussions take place we be sure to "assign" someone to get the issue to a resolution. It would make it easier to determine who is responsible for what and avoid something getting dropped or worked on twice.

**Comment by atvassilev** [comment]
OK, I will triage the current open issues and assign those that are clear. Also, we need to add an agenda item for the weekly algotest calls for assignments of current open issues.
