### ISSUE TITLE
ACVP demo server fails RSA signaturePrimitive for reason outside of spec

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP#1103]
**Protocol Section**
https://usnistgov.github.io/ACVP/draft-celi-acvp-rsa.html#name-rsa-signature-primitive-tes

**Protocol Question**
Given the following response snippet, the ACVP demo server validation fails. It appears to be per the documentation. When I add a "testPassed": true attribute to test case 4, it passes. Is the signature required? Should the spec be updated?

```
          {
            "signature": "3CF38351BE791C17D029012380EEB6104FDF54AA91E57F766F11D2FB04E11D84BA92CBD529E27C8E190D0248EE7E289364E1C888712CCF8204C76D30FDD21457E7D8BA4DC084272DD652E37721C5A5C01FFCAA54D195878AB274576F3B7CA71B0CE1C31ACA4362C1F75545E83FC952BABAD2730E0FE914DB61199B849955FF54C55C334CBC40DEE233300C393E8B9A5B7F64A9461544CB924BCD244495A4E9C5AF34256712FE5BC44BE62B0EB7689A21D51C5E1E65FD0C4DCD458168E69F1CC5D476E47F791C8860118A8AE9E25B34D3F60450B8D3654C4C154FB1DC50F450809279EFF48F3C5BF51E542A71B1BEF9CA57DD302279FA0B91A19ACA79187FEBD1",
            "tcId": 4
          },
          {
            "tcId": 5,
            "testPassed": false
          },

```

**Comment by celic** [comment]
Yes, it appears like the `"testPassed"` property is always expected. Should be a spec update to add those lines.
