### ISSUE TITLE
Question: KAS2 VAL test clarification

### ISSUE THREAD

**Issue by nidhidamodaran** [usnistgov/ACVP#1108]
For VAL tests, https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ssc-ifc.txt says failure cases include (changed Z, Z with leading zero nibble, etc) . Are there more validation other than changed Z, Z with leading zero nibble?

**Comment by smuellerDD** [comment]
Am Montag, dem 11.01.2021 um 07:45 -0800 schrieb Nidhi Damodaran:
> For VAL tests, 
> https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ssc-ifc.txt says failure
> cases include (changed Z, Z with leading zero nibble, etc) . Are there more
> of these ?
> 

56A rev 3 key verification requirements come to mind.

**Comment by nidhidamodaran** [comment]
Thanks @smuellerDD , Will check that. So I am assuming iut/Server keys has to be validated as well for this test.
