### ISSUE TITLE
Valid radix length for FF1 & FF3

### ISSUE THREAD

**Issue by surajshardade** [usnistgov/ACVP#1111]
I am able to pass all the sample test vectors generated for the FF1 algorithm for radix <= 62. But for radix 64 some of the test vectors able to pass and some not.  So I went through some acvp docs and I found valid length for radix is 2-62 (please take a look at the attached snap.). If so, how can I able to get test vectors for radix 63 and 64?

is this provided limit for radix is still applicable for the FF1 and FF3 test vectors?

![ACVP_TABLE](https://user-images.githubusercontent.com/43987488/104571970-b1dcc800-5679-11eb-808c-725c4c03416a.PNG)

**Comment by livebe01** [comment]
This looks like a documentation error. Valid values for radix should be 2-64. Thanks for pointing this out!
