### ISSUE TITLE
ANSI X9.42 - keyLen, zzLen and otherInfoLen Error

### ISSUE THREAD

**Issue by mtdownz** [usnistgov/ACVP#1115]
In re-examining the ANSI X9.42 testing on the ACVP Demo server there appears to be an issue maybe? We are attempting to re-run vectors for one of our vendors that  echo the exact parameters that were used in a past submission; however, the ACVP demo server is now throwing an error. It appears it does not agree to the lengths documented on the NIST page for each parameter (please ref):
https://pages.nist.gov/ACVP/draft-celi-acvp-kdf-ansi-x942.html#name-capabilities-registration

The documentation allows keyLen, zzLen and otherInfoLen to be a Max of 65536 bits. We receive the following error from the Demo server which appears to state the maximum is 4096 (bits or bytes I'm not sure?)

Error Message:
***ACVP [ERR][log_network_status:1491]--> 400 error received from server. Message:
***ACVP [ERR][log_network_status:1492]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "kdf-components-ansix9.42-1.0: Maximum ZzLen must be less than or equal to 4096;Maximum OtherInfoLen must be less than or equal to 4096;Maximum KeyLen must be less than or equal to 4096"
    ]
  }
]

Our request:
[{"acvVersion":"1.0"},{"isSample":true,"algorithms":[{"algorithm":"kdf-components","revision":"1.0","mode":"ansix9.42","prereqVals":[{"algorithm":"SHA","valValue":"same"}],"hashAlg":["SHA2-224","SHA2-256","SHA2-384","SHA2-512","SHA3-224","SHA3-256","SHA3-384","SHA3-512"],"kdfType":["concatenation"],"keyLen":[1,65536],"otherInfoLen":[0,65536],"zzLen":[8,65536]}]}]

From our experience the documentation should be correct (ref alg. cert A888); however, we are not sure why the Demo server is now rejecting the request. Has something changed in this area?

Thank you!

**Comment by Kritner** [comment]
@celic I know you were doing some changes to x9.42 related to DER encoding in https://github.com/usnistgov/ACVP/issues/1056

I see that some max lengths were changed recently in the code around this area, was this an intentional change for non DER encoded fixed/other info?  Should the specification be updated?

**Comment by celic** [comment]
Intentional, specification updates were in a PR that has been merged in now. The values being allowed were too large, there's no need to generate a 64KB key...

**Comment by mtdownz** [comment]
Thank you for updating the documentation. I now see the suppInfoLen information also needed for the DER encoding. Perfect!
