### ISSUE TITLE
Some feedback regarding SP800-56Cr1 spec

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1118]
Hello,
Having recently finished implementing these algs for libacvp, wanted to provide a bit of feedback on some things I noticed:

- for HKDF, "requiresAdditionalNoncePair" is a field provided by server, yet it is not mentioned in spec
- In table 2 for HKDF, Z is mentioned to be a domain, but its "valid values" simply says "l", which is not a domain but a single value
- in table 2 for onestep and twostep, Z is similarly missing some info
- In all of the algs, l is not listed in table 2
- fixedInfoPattern seems like it may be better suited to be a JSON array instead of a tokenized string (or at least, the Literal pattern candidate could be its own field)
- when l is used for fixedInfo, I've found it is expected to be as a big endian byte string (similar to how counter is used in the SP800-56Cr1 algorithms), it would be helpful if this was mentioned in the spec

Thanks,
Andrew

**Comment by dmchodnicki** [comment]
Bullet 1 regarding the presence of a "requiresAdditionalNoncePair" field in a server response is being investigated as a possible server code issue.  The Table 2 issues identified in Bullets 2, 3, and 4 have been addressed with recent spec updates. fixedInfoPattern will not be converted from a string to an array at this point in time.  The potential benefit does not currently justify the development and testing efforts associated with making the change.  A PR is in progress to add a note to the spec covering the big endian expectation referenced in Bullet 6.

**Comment by dmchodnicki** [comment]
ACVP-Server #135 has been opened to investigate the Bullet 1 "requiresAdditionalNoncePair" field concern as a possible server code issue.  The spec update addressing the Bullet 6 big endian concern has been implemented.  Therefore, this issue is being closed.

**Comment by abkarcher** [comment]
Thank you for the updates! 

Andrew
