### ISSUE TITLE
New failure when requesting KMAC vectors. "Unable to pair up input and output lengths"

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1119]
Hi,

We have previously been successful in obtaining vectors for both KMAC-128 and 256, but for KMAC-256 we now receive,

```
[{"acvVersion":"1.0"},{"error":"Unable to pair up input and output lengths"}]
```

I have attached a zip file, the "capabilities.json" is what is submitted to ACVP and "UNKNOWN.req.json" has the error.

Let me know if you need more information.

[xof.zip](https://github.com/usnistgov/ACVP/files/5892691/xof.zip)

MW

**Comment by Kritner** [comment]
Taking a look

**Comment by Kritner** [comment]
This is an issue around the way the gen/vals are generating test cases incorrectly in response to the provided `MathDomain`s, I have a change going through internal testing, will update once the change is on demo.

**Comment by mwcw** [comment]
> This is an issue around the way the gen/vals are generating test cases incorrectly in response to the provided `MathDomain`s, I have a change going through internal testing, will update once the change is on demo.

Thanks for your help!

MW

**Comment by Kritner** [comment]
This change is on demo

**Comment by Kritner** [comment]
This change is on prod in release [v1.1.0.15](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.15)
