### ISSUE TITLE
Inconsistent bits/bytes in symmetric specification

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#112]
The specification for the most part uses a bit representation in its "length" properties.  The AES-CCM table:

![image](https://cloud.githubusercontent.com/assets/8814983/24621036/0b356900-186e-11e7-9d72-722f3af4c87c.png)

Payload, IV/Nonce, Tag, and AAD are represented as bits in the AES-GCM and AES-XTS rows.  However the values in AES-CCM are bytes, though that is not specified.

The AES-CCM values should probably be updated to be specified in bits to remain consistent.  The disadvantage to going this route is the ranges of valid values, as well as (2^16)*8 for max AAD length is a much larger value.

Thoughts?

**Comment by celic** [comment]
It should be noted, in the SHA spec, there is no reference to bits or bytes for things like message length. The intended notion is bit length in terms of SHA, but I think this should be discussed. Perhaps we could have a default of bits unless otherwise specified? I'm not sure how much sense this would make in terms of other algorithms however.

**Comment by atvassilev** [comment]
If you look at SP 800-38C http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38c.pdf, Appendix A, the specification of AES-CCM is defined in bits with the additional constraint that the bit-length of each input string shall be a multiple of 8. So, it seems that the byte-length inputs are something that CAVS came up with and it is not how the standard defines it. 

When in doubt, we should check the standard and if a discrepancy is found, the definition in the standard prevails. 

If we use the bit-oriented definitions in SP 800-38C and change the numbers for AES-CCM in the table above the inconsistency would go away and the sub-symmetric spec will be simpler.

**Comment by atvassilev** [comment]
Resolved with PR #133
