### ISSUE TITLE
ECDSA sigGen question

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP#1120]
**Protocol Section**
https://pages.nist.gov/ACVP/draft-fussell-acvp-ecdsa.html

**Protocol Question**
Is the purpose of the ECDSA sigGen component test to verify the signature components with the public key? If so, I don't understand why this is failing to verify.

Reason: Validation failed: Failed to verify

Here's an example test case.

```
        "componentTest": true,
        "curve": "P-256",
        "hashAlg": "SHA2-256",
        "testType": "AFT",
        "tests": [
          {
            "message": "D52D6BCB4CD9B4A4E8EB87FA54946455089E612A5B213D98CEC256C2E846EE9A",
            "tcId": 1
          },

````

Here's the corresponding result.
```

        "qx": "8935EC92029BDD19E99C3B6A0051B8D2A7B70C56E9431D7C2178008C03958BB7",
        "qy": "F07CEF1CBA1FA56898C20579C08D95186FADDFE3B59E0EE94BEF09709B57E91A",
        "tests": [
          {
            "r": "00C76D2481E2F4461E7FDA9C8A491666F4478F0370CAED33FFFF23093B92262950",
            "s": "00B3357EC9F197BFC610EDAF02EA266885745E215F2B518F5300DB9A7F7D2E6A0D",
            "tcId": 1
          },


```

I wrote a tool to form a public key from x and y (for example public.pem). I also wrote a tool to create a signature from r and s components (for example signature.bin). The xxd tool converts the hex-encoded message to binary (for example, msg.bin).

When I verify with openssl (which isn't the module I'm testing), it verifies.

openssl dgst -sha256 -verify public.pem -signature signature.bin msg.bin
Verified OK

We are also testing with "componentTest": false. Those pass and they execute the same code.

Am I doing the wrong thing with componentTest?

Any help appreciated.

**Comment by eslerd** [comment]
@jbarnesweb my understanding is that if `componentTest` is true, the message has already been hashed and you are strictly testing your ECDSA implementation. It makes sense that `openssl dgst -sha256 -verify public.pem -signature signature.bin msg.bin` would match, since this too would be hashing the already hashed message before signing.

**Comment by jbarnesweb** [comment]
You are exactly right. Thank you!
