### ISSUE TITLE
Table columns misaligned in symmetric block cipher spec (txt and HTML)

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1121]
https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.txt

(Also, the link to AES-GMAC on the ACVP homepage points to the AES spec instead of the MAC spec where it was moved)

**Comment by Kritner** [comment]
I only found one instance of table misalignment, so hopefully that was all you found.  Feel free to re-open and update if I missed something.
