### ISSUE TITLE
Viewing certificates post Validation

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1122]
Hi,

I am asking on behalf of a client that has production access, what is the URL for viewing certificates post validation.

A while back, I think 2019, the url for the demo server was "https://demo.acvts.nist.gov/home".

Could you advise if there is a new url for both prod and demo please?

Sorry if this is in the documentation, I have been unable to find it.

MW

**Comment by Kritner** [comment]
Validations can be viewed on CSRC at: https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/validation-search

**Comment by mwcw** [comment]
Thanks!
