### ISSUE TITLE
Documentation of Location of JSON Web Key Sets

### ISSUE THREAD

**Issue by musterjunk** [usnistgov/ACVP#1124]
I am trying to find the endpoint to grab the key sets that can be used to validate my jwt. Could you guys add that end point to the documentation?

**Comment by Kritner** [comment]
Sorry I don't really understand what's being asked.

You can look at the jwt payload through a decoder such as through jwt.io
which will show what vector sets are claims on the jwt. If you're asking to
verify the jwt, we don't post the signing key.

**Comment by musterjunk** [comment]
That is what I was wanted. The public half of the signing key to validate the token, assuming it was an asymmetric key. I guess you can close this then.
