### ISSUE TITLE
Regarding KAS2 IFC VAL tests

### ISSUE THREAD

**Issue by sreekanth-ys** [usnistgov/ACVP#1126]
Working on KAS-IFC ACVP test vectors. Below are the observations. 

1. For KAS1 IFC VAL tests, able to detect "fail"ed cases correctly as per expected results. For all "fail" cases, decrypted content  of "iutC" with Server private key is not matching with provided "Z". In other way provided "iutZ" and "z" contents also does not match.  The same is observed for all cases where "fail" is expected.

2. For KAS2 IFC VAL tests, unable to detect any "fail"ed cases, though expected results  says that some cases should fail. Below are the tests done.
            -  Validation of Server key Components
            -  Validation of Initiator key Components
            -  Range checks for ServerZ and iutZ , iutC and ServerC.
            - Decrypting iutC with server private key (derived from given RSA components) and comparing with iutZ  and initiator part of Z.
            - Decrypting serverC with initiator private key and comparing with Server part of Z (serverZ).
            - Encrypting iutZ, initiator part of Z with Server public key and comparing with iutC
            - Encrypting ServerZ , with initiators public key and comparing with iutC.

All above tests are passing with openssl implementations as well (even for those which are supposed to "fail" as per expected results). Tried RSA_public_encrypt/RSA_private_decrypt with RSA_NO_PADDING and also with plain modexp invoking BN_mod_exp().

Please suggest if i am missing anything regarding KAS2 VAL checks

Thanks

**Comment by Kritner** [comment]
Do you have a vector set and test cases within that I can take a look at to see why they're marked as "should be failures" on our end?

**Comment by sreekanth-ys** [comment]
Thanks Kritner
Test vector file : https://sreekanth-ys.github.io/ACVP_KAS_IFC_test_vectors/KAS-IFC-SSC.474086.req.json
Expected response: https://sreekanth-ys.github.io/ACVP_KAS_IFC_test_vectors/KAS-IFC-SSC.474086.expected.json

In above test vectors for KAS2 VAL tcId #24 and #26 expected is "false", however unable to find any corrupted keys or changed Z values.  

Please let me know if anything required to share.

**Comment by Kritner** [comment]
Our side wasn't properly communicating the mangled test case data for KAS2 for this failure reason. The fix is on demo in release [v1.1.0.16](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.16)

**Comment by sreekanth-ys** [comment]
Thanks Kritner, Can you please share ETA on when till fix will go in production server

**Comment by Kritner** [comment]
> Thanks Kritner, Can you please share ETA on when till fix will go in production server

Hopefully early next week.  Were you able to confirm this change from your perspective?

**Comment by Kritner** [comment]
This change is on prod in release [v1.1.0.16](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.16)
