### ISSUE TITLE
x9.42 registration missing OID of wrapping algorithm

### ISSUE THREAD

**Issue by mpacumen** [usnistgov/ACVP#1127]
https://pages.nist.gov/ACVP/draft-celi-acvp-kdf-ansi-x942.html#name-registration-example

I need to generate vectors for the three AES OIDs but not DES3. This is something that should be specified at registration time. Currently, the demo server only returns vectors with the DES3 OID.

**Comment by celic** [comment]
I couldn't find OIDs for other algorithms than TDES. What is the OID for AES?

**Comment by mpacumen** [comment]
RFC 3565:

0609608648016503040105 aes-128-wrap
0609608648016503040119 aes-192-wrap
060960864801650304012D aes-256-wrap

**Comment by mpacumen** [comment]
Has this change been pushed to the demo server yet?

**Comment by celic** [comment]
Not yet. Other fixes took priority recently.

**Comment by celic** [comment]
This will be in the next release with some changes in the registration to account for selecting which OIDs to use.

**Comment by mpacumen** [comment]
Any estimate for when the next release will happen?

**Comment by celic** [comment]
Within the next couple of days. It's a large one for us.

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.17](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.17)

**Comment by mpacumen** [comment]
The spec does not say anything about an OID field in the registration. Does the server expect a hex value or something else?

**Comment by Kritner** [comment]
This change is on prod as of release [v1.1.0.17](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.17)

based on @mpacumen's comment https://github.com/usnistgov/ACVP/issues/1127#issuecomment-825965225, still need to do some specification updates as it relates to this change.

The registration now specifies the OIDs to use through a property `oid` in the root of the registration, which is a `string[]`.  the `oid` valid values are:

* TDES
* AES-128-KW
* AES-192-KW
* AES-256-KW

I'll try to get to the specification updates shortly.
