### ISSUE TITLE
Server Accepts HMAC-SHA-1 as Mac Method on ECC / FFC Ar3, KAS1-Party_V-confirmation

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1129]
Hi,

We have found that the server will accept HMAC-SHA-1 without error on the above algorithms as long as it is not the only Mac Method.

Being curious, we removed all other mac methods on the above and got variations on:

```
"KAS-IFC-Sp800-56Br2: macOptions contained no registered MAC algorithms."
```

Depending on what was being requested.

It may be happening elsewhere but we are not in a position to investigate.

MW

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.16](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.16)

**Comment by Kritner** [comment]
This change is on prod in release [v1.1.0.16](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.16)
