### ISSUE TITLE
AES-GCM/GMAC ivGen & ivGenMode support

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#1130]
**Protocol Section**
AES-GCM/GMAC

https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html

**Protocol Question**
Is it possible to make GCM and GMAC's ivGen supports both Internal and External IV simultaneously? And ivGenMode to select both 8.2.1 and 8.2.2?

**Comment by Kritner** [comment]
I *believe* the intention of the "internal iv generation" capability is for IUTs that ***only*** support internal IV generation from an encryption perspective - situations where they can't utilize our generated IV from our prompt files.

Perhaps this would make some sense to change in the next testing revision to GCM/GMAC, but as it's a client breaking change I'm not sure if makes sense to do at the moment.  Perhaps as an alternative, you could include two GCM/GMAC registrations within a single test session one as internal IV generation, one as external?
