### ISSUE TITLE
JSON validation error when submitting CMAC-TDES capabilities

### ISSUE THREAD

**Issue by gavishka** [usnistgov/ACVP#1131]
Whenever I try to create test sessions with a set of capabilities for CMAC-TDES, following error message appears for "keyingOption" field, which is supposed to be an integer value (1, 2) according to the documentation. 
[https://pages.nist.gov/ACVP/draft-fussell-acvp-mac.html#section-9.1](https://pages.nist.gov/ACVP/draft-fussell-acvp-mac.html#section-9.1)
Even though I have an integer value either 1 or 2, this message comes up.

`The JSON value could not be converted to System.Int32. Path: $.capabilities[0].keyingOption | LineNumber: 0 | BytePositionInLine: 229.`

**Comment by abkarcher** [comment]
Hello,

From what I can tell of how we have it implemented, the server currently expects keyingOption to be an array with the keying value integer inside it. Hope this helps in the meantime.

Andrew

**Comment by AlexThurston** [comment]
The documentation should likely be updated to match

![image](https://user-images.githubusercontent.com/3537360/108511698-43011900-728e-11eb-8af9-6953efe56b1e.png)
