### ISSUE TITLE
JSON validation error for ACVP-AES-KWP registration

### ISSUE THREAD

**Issue by gavishka** [usnistgov/ACVP#1133]
Have been trying to register capabilities for ACVP-AES-KWP, I get a JSON Validation error saying,
`ACVP-AES-KWP-1.0: PtLen Domain was not provided.`

I went through the documentation as well to check about this field `PtLen Domain` the error message referring to, couldn't find it anywhere. [https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html#name-block-cipher-algorithm-capa](https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html#name-block-cipher-algorithm-capa)

Please let me know what this message is referring to.

Thank you.

**Comment by Kritner** [comment]
Looks like it's `payloadLen`, is that missing from your registration? i can get it updated on our end to reflect the actual property name.

**Comment by gavishka** [comment]
`payloadLen` is not included in my registration. Documentation doesn't have it as well. If it is required, let me know once it's updated on your end.
![kwp](https://user-images.githubusercontent.com/31833056/108763179-11eb4780-751f-11eb-93fa-b3b86e8bdbb2.PNG)

**Comment by Kritner** [comment]
The `payloadLen` is required, there's no code changes needed to be able to submit it in a registration currently - the issue in the code is around the *label* that is indicating `ptLen` is missing, when it should state that it's `payloadLen` that's missing.  The documentation could additionally use an update it looks like to reflect the required `payloadLen`.

**Comment by Kritner** [comment]
The fix to change the property name `ptLen` -> `payloadLen` is on demo in release [v1.1.0.16](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.16)

**Comment by gavishka** [comment]
Thank you

**Comment by Kritner** [comment]
This change is on prod in release [v1.1.0.16](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.16)
