### ISSUE TITLE
AES-CTR providing IV when external IV is selected

### ISSUE THREAD

**Issue by QuentinGouchet** [usnistgov/ACVP#1137]
I request vectors for AES-CTR both for external and internal IVs as follow:

[
 {
   "acvVersion":"1.0"
 },
 {
   "isSample":false,
   "operation":"register",
   "certificateRequest":"no",
   "debugRequest":"yes",
   "production":"no",
   "encryptAtRest":"yes",
   "algorithms":[
     {
       "revision":"1.0",
       "algorithm":"ACVP-AES-CTR",
       "direction":[
         "encrypt",
         "decrypt"
       ],
       "keyLen":[
         128,
         256
       ],
       "payloadLen":[
         {
           "min":8,
           "max":128,
           "increment":8
         }
       ],
       "ivLen":[
         128
       ],
       "ctrSource":"external",
       "overflowCounter":false,
       "incrementalCounter":true
     },
     {
       "revision":"1.0",
       "algorithm":"ACVP-AES-CTR",
       "direction":[
         "encrypt",
         "decrypt"
       ],
       "keyLen":[
         128,
         256
       ],
       "payloadLen":[
         {
           "min":8,
           "max":128,
           "increment":8
         }
       ],
       "ivLen":[
         128
       ],
       "ctrSource":"internal",
       "overflowCounter":false,
       "incrementalCounter":true
     }
   ]
 }
]

Yet, for both testvector-request.json files, the IVs were provided in the file. I would expected that for internally generated IV, either the IV is not provided, or some field in the JSON would mention "internal" so that the module would know to generate its own IV and not use the provided one:

{
            "tcId": 1,
            "pt": "F7F3AEA559164B3B1BF50C1B1F7F449F",
            "iv": "429BA041C6AD847BAAA8073A336AC33A",             <------------------
            "key": "4D71B28303F07636152BBD83CDDDB252"
          },

**Comment by Kritner** [comment]
@QuentinGouchet `ctrSource` isn't a valid property for use under AES-CTR testing with ACVP, so making changes to that value would have no impact on the vector sets generated.

It looks like `ctrSource` was a property from the CAVS days, when there was no actual testing against counter mode; I did not actually realize this until digging into it just now. We don't currently have testing that supports an internal IV from the "base" counter mode testing. 

There is however the newly introduced RFC testing conformance https://github.com/usnistgov/ACVP/issues/1049 which is currently enabled on demo.

**Comment by QuentinGouchet** [comment]
Thanks Russ good to know, we will update our side to use the RFC CTR
testing then!
