### ISSUE TITLE
X9.63 KDF Spec Page Inaccuracies

### ISSUE THREAD

**Issue by rruss-ldos** [usnistgov/ACVP#1138]
The example registration shows lowercase hashing algorithms. ACVTS appears to be case sensitive for these.

Section 7.3.1 shows valid hash functions as having the SHA- prefix. The actual valid prefixes are SHA2-.

**Comment by celic** [comment]
Due to some changes in our organizational policy, our automatic builds have been disabled. It might be a little bit before this change is reflected on https://pages.nist.gov/ACVP.
