### ISSUE TITLE
OE definition: Why is an OE always required?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#1139]
**Protocol Section**
certificate request during publication

**Protocol Question**
When posting a certificate request, the client has to provide a moduleUrl and an oeUrl.

Now, when omitting the oeUrl, the server returns an error. My question now is why is it always required to have an oeUrl. Assume you have a dedicated device that only does crypto which is to be validated. Now, that device does not have any operational environment as it is fully stand-alone. I would fathom that this module should only have a moduleUrl. If the server would insist on an oeUrl, I am wondering what to state in the OE.

**Comment by celic** [comment]
You are correct. An OE is not always applicable. I've been spending some time trying to figure out the larger OE problem the CAVP has been having. Sometimes descriptions don't cover the information the CMVP or other bodies are looking for, and sometimes very little or no information is available like in a dedicated device. For now, the process is what it is, but we are going to tackle this soon.

**Comment by smuellerDD** [comment]
If you say that there is work done in this area, I see no issue to keep this report open as it should just be a hint to you.
