### ISSUE TITLE
Vector verdict is not received

### ISSUE THREAD

**Issue by QuentinGouchet** [usnistgov/ACVP#1144]
hi,

It seems like testID 5173 does not send the verdict back. After contacting Robert Staples, he mentioned that the verdict was passing. Yet our client constantly re-tries to fetch the verdict without success nor error indicating some kind of failure.

The same seems to happen for those testIDs/vsIDs:

5168/49527
5288/all vsIDs under it
5242/50089
5173/all vsIDs under it

**Comment by Kritner** [comment]
I'm not really sure what endpoint you're having problems with, or what the problem actually is.  All 4 of the test sessions listed above have already been published, so I'm not sure what information you're trying to pull from them.

**Comment by QuentinGouchet** [comment]
hi Russ,

Thanks for the response. I see; our client. was showing that the verdict
was not obtained and I wasn't sure if it had passed. I guess the issue can
be closed, yet it is unclear to me why I cannot re-fetch the verdict.

Quentin Gouchet
-----------------------------

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 17.03.2021 um 07:36 -0700 schrieb Q. Gouchet:
> hi Russ,
> 
> Thanks for the response. I see; our client. was showing that the verdict
> was not obtained and I wasn't sure if it had passed. I guess the issue can
> be closed, yet it is unclear to me why I cannot re-fetch the verdict.

Can you please post the endpoint that is invoked by the client? Re-fetching a
verdict should always be possible. And I verified that indeed that works.

Thus, we should let Russ know the endpoint to find out why the server does not
provide data.

Thanks
Stephan

**Comment by QuentinGouchet** [comment]
hi Russ,

Here is the endpoint I was trying to get verdicts from:

testID URL: https://acvts.nist.gov:443/acvp/v1/testSessions/5242

I was not able to fetch verdicts or resubmit results (which I assume is
because it is already passed but I cannot see it on my end).

Quentin Gouchet
-----------------------------

**Comment by Kritner** [comment]
What is the response (and status code) you're getting?  Are you performing that get using a JWT that has claims to that test session? We only will return information pertaining to a test session if you have the appropriate claims to it.

**Comment by smuellerDD** [comment]
When calling a PUT on /acvp/v1/testSessions/5242, the server responds:

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Test session must be in a passed state to be certified"
    ]
  }
]
```


When re-downloading the verdict the server responds:

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "passed": false,
    "results": [
      {
        "vectorSetUrl": "/acvp/v1/testSessions/5242/vectorSets/50089",
        "status": "passed"
      }
    ]
  }
]
```

This looks like it is affected by the report https://github.com/usnistgov/ACVP-Server/issues/63

**Comment by Kritner** [comment]
> When calling a PUT on /acvp/v1/testSessions/5242, the server responds:
> 
> ```
> [
>   {
>     "acvVersion": "1.0"
>   },
>   {
>     "error": "Validation error(s) on JSON payload.",
>     "context": [
>       "Test session must be in a passed state to be certified"
>     ]
>   }
> ]
> ```

The test session is *already certified*, so it's technically not in a "passed" state from our perspective, but yes, a better response may be in order here.

> 
> When re-downloading the verdict the server responds:
> 
> ```
> [
>   {
>     "acvVersion": "1.0"
>   },
>   {
>     "passed": false,
>     "results": [
>       {
>         "vectorSetUrl": "/acvp/v1/testSessions/5242/vectorSets/50089",
>         "status": "passed"
>       }
>     ]
>   }
> ]
> ```

I just updated the issue you linked asking for clarification around whether or not that test session was already certified, because if so then yes, they are both the same issue and I can take care of that in the next release.

Are these updates clarifications on @QuentinGouchet's behalf? Or is that still separate from these issue updates?

**Comment by smuellerDD** [comment]
I am helping Quentin - this particular issue is covered. And thank you for your hints - the issue was on our side.

But for issue #63 - this is a generic issue that I discovered when trying to "extend" the lifetime of a certification: when re-requesting the verdict before the testsession is published, I get the mentioned error.

**Comment by Kritner** [comment]
This change is on prod as of release [v1.1.0.17](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.17)
