### ISSUE TITLE
KAS-ECC-SSC ECDSA prerequisites

### ISSUE THREAD

**Issue by kettro** [usnistgov/ACVP#1149]
Regarding the KAS-SSC-ECC tests ([here](https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ssc-ecc.html)), It lists a conditional requirement on ECDSA, stating:

>ECDSA KeyGen/KeyVer validation REQUIRED when IUT makes use of the generation/validation of keys within the module boundary.

Does this apply only to situations where the IUT uses the Ephemeral KAS schemes (eg, not StaticUnified)? If not, then is there a situation where the condition is _not_ satisfied?

**Comment by kettro** [comment]
ping?

**Comment by Kritner** [comment]
It would seem to make sense only in the context of *when keys are used as a part of the generation*.  In the case of a static key pair, the key is not being generated as a part of the negotiation, it already existed.
