### ISSUE TITLE
KAS ECC SP80056-AR3 fixedDataOrder for twoStepKDF when kdfMode is counter

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#1151]
**Protocol Section**
https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ecc-sp800-56ar3.html#twostepcapcap

```json
{
    "kdfMethods": {
        "twoStepKdf": {
            "capabilities": [
                {
                    "macSaltMethods": [
                        "default"
                    ],
                    "fixedInfoPattern": "literal[454e4352595054494f4e0a00000000000100010108]||vPartyInfo||literal[0E]||uPartyInfo",
                    "encoding": [
                        "concatenation"
                    ],
                    "kdfMode": "counter",
                    "fixedDataOrder": [
                        "None"
                    ],
                    "counterLength": [
                        8
                    ],
                    "supportsEmptyIv": false,
                    "requiresEmptyIv": false,
                    "macMode": [
                        "HMAC-SHA2-256"
                    ],
                    "supportedLengths": [
                        256
                    ]
                }
            ]
        }
    }
}
```

**Protocol Question**
When trying to register this, I am met with the error
```json
[
    {
        "acvVersion": "1.0"
    },
    {
        "error": "Validation error(s) on JSON payload.",
        "context": [
            "KAS-ECC-Sp800-56Ar3: none FixedDataOrder is not valid with Counter KDF"
        ]
    }
]
```

However, in the documentation, it doesn't mention anything about what `fixedDataOrder`'s are valid with any given `kdfMode`

**Comment by Kritner** [comment]
@AlexThurston Thanks for your patience, this section of the two step configuration would inherit from the [SP800-108 registration](https://pages.nist.gov/ACVP/draft-celi-acvp-kbkdf.html), specifically 

![image](https://user-images.githubusercontent.com/8814983/128722944-13ed56a0-5a0b-4d19-b806-5026d098ba37.png)


Though this isn't documented as well as it could be.  I'm marking this issue as a documentation update for the moment, feel free to PR some additional language about the SP800-108 document, or with an explicit note about the restrictions.

**Comment by Kritner** [comment]
Thanks @dmchodnicki, closing as per #1222
