### ISSUE TITLE
KMAC customization string length needs a limit

### ISSUE THREAD

**Issue by mpacumen** [usnistgov/ACVP#1152]
KMAC customization string length seems to be missing from the capabilities registration.

**Comment by livebe01** [comment]
Hi @mpacumen, can you provide more information/context?

**Comment by mpacumen** [comment]
An unbounded customization string length is not easy for any IUT to deal with. Currently the demo server appears to be returning a max length of 128. That's reasonably small, but can we be sure we won't see 65536 in the future. The max needs to be documented in the spec or else be configurable.

**Comment by livebe01** [comment]
Great, thanks! We'll take a look and see what we can do about adding that info.
