### ISSUE TITLE
KAS-ECC CDH registration fails

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#1156]
[{"acvVersion":"1.0"},{"algorithms":[{
                                 "algorithm":"KAS-ECC",
                                 "revision":"Sp800-56Ar3",
                                 "mode":"CDH-Component",
                                 "prereqVals":[{"algorithm":"ECDSA","valValue":"same"}],
                                "function":["keyPairGen"],
                                 "curve":["P-224"]}]}]
Response is:

  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Unable to map KAS-ECC-CDH-Component-Sp800-56Ar3 - index 0 to an internal algorithm id."

**Comment by Kritner** [comment]
Thanks @bfussell, can you give it another go?

**Comment by bfussell** [comment]
Success ! Thanks for the quick response.

**Comment by Kritner** [comment]
I believe we were going to try for this weekend if nothing of issue is found with the current release on demo.
