### ISSUE TITLE
Change Letter Procedure Steps

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#1157]
General Question regarding a change letter. If it has been discussed I couldn't locate it in the spec or issues.
For a change letter which covers new tests for algorithm support for SP800-56Ar3 do we run the new tests and then PUT the new testSession information using the previous module and OE ?  Or are their alternatives ?

I'm concerned that the module/OE may be updated but the soon to be historical algorithms from SP800-56Ar2 would still be part of the validation information.

Thanks,

Barry

**Comment by celic** [comment]
Sorry, this is best coming in an email to me. 

If the algorithm in the new test session does not already exist in the moduleID, it will be added with a certify request. If the algorithm does already exist it will be overwritten. 

Do not worry about historical information. It is no longer an all-or-nothing element of validations. When an individual algorithm is moved to historical we only mark the relevant capabilities in the validation. Everything else remains valid.
