### ISSUE TITLE
Unable to use `nonceLen` of 104 for KAS ECC

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#1162]
**Protocol Section**
https://pages.nist.gov/ACVP/draft-fussell-acvp-kas-ecc.html#section-7.10

**Protocol Question**
The section for nonceLen is qualified as:
![image](https://user-images.githubusercontent.com/3537360/116452097-55b64200-a82b-11eb-881c-52ff4358fe99.png)

This - to me - means that valid values are: 56, 64, 72, 80, 88, 96, 104

However, registrations using a `nonceLen` of 104 failed with the following error:
```
Invalid AES-CCM Nonce Length supplied: 104
```

It does look like there are certificates that have 104 as a `nonceLen` but it doesn't appear to work so I'm not sure how that was achieved:
![image](https://user-images.githubusercontent.com/3537360/116452397-b0e83480-a82b-11eb-8012-05b340482843.png)

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.18](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.18)

**Comment by Kritner** [comment]
This change has been released to prod in release [v1.1.0.18](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.18).
