### ISSUE TITLE
AES-CCM with Taglen 104 and 120 fail to generate

### ISSUE THREAD

**Issue by rnunez83** [usnistgov/ACVP#1164]
https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.txt Table 6 lists the following taglen possible for AES-CCM: {32, 64, 96, 104, 112, 120, 128} 

When I attempt to request demo vectors from server using taglen of 104 or 120, I see the following error:
ACVPProxy (11:45:54) () Verbose [lib/common/network_helper.c:_acvp_net_op:85]: Process following server response: [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "ACVP-AES-CCM-1.0: Invalid tagLen supplied: 104,120"
    ]
  }
]

**Comment by livebe01** [comment]
Hi @rnunez83, the issue appears to be a typo in the spec. Per SP 800-38C, the Taglen should be "any integer multiple of 16 between 32 and 128, inclusive." In your case, ACVTS is correctly rejecting values of 104 and 120 as they are not multiples of 16. We'll update the spec for the correct values of {32, 48, 64, 80, 96, 112, 128} as soon as we get a chance. 

I noticed some addition typos related to tagLen (i.e., reference to Table 5 and JSON type of domain) in Table 3 that we will fix as well.

Thank you for bringing this to our attention!

**Comment by rnunez83** [comment]
thanks for the explanation.
