### ISSUE TITLE
FIPS 186-4 RSA KeyGen with fixed exponent

### ISSUE THREAD

**Issue by EH-Acumen** [usnistgov/ACVP#1166]
Test vectors for a module implementing FIPS 186-4 RSA KeyGen B.3.6 with a fixed exponent were generated.  The fixedPubExp is set to "FFFFFFFF". 
The request files generated contain the value "e": "010001".  I believe this is a bug on the server side.  The value "e": "FFFFFFFF" should have been used instead.  
See test Session "/acvp/v1/testSessions/176102/vectorSets/549760" for an example of this.

**Comment by Kritner** [comment]
Thanks @EH-Acumen, will get a correction out to fix this shortly.

**Comment by Kritner** [comment]
This is on demo in release [v1.1.0.17-1](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.17-1).

**Comment by Kritner** [comment]
This change is on production in release [v1.1.0.17-1](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.17-1)
