### ISSUE TITLE
FIPS 186-4 RSA KeyGen failure output

### ISSUE THREAD

**Issue by EH-Acumen** [usnistgov/ACVP#1168]
When submitting responses on the Demo server to FIPS 186-4 RSA KeyGen B.3.6 with a random public exponent, the following failing output is received:
**529809: Not passing
        Test case results:
        1: XP1 did not contain enough bits.  Expected 167, got 0.; XP2 did not contain enough bits.  Expected 251, got 0.; XQ1 did not contain enough bits.  Expected 183, got 0.; XQ2 did not contain enough bits.  Expected 250, got 0**
However from the ACVP RSA Algorithm JSON Specification (https://pages.nist.gov/ACVP/draft-celi-acvp-rsa.html#rsa_keyGen_vs_tr_table) it says below Table 27,  **"NOTE 3: If the 'infoGeneratedByServer' test group property is true, then the only response from the client SHALL be the values that directly correspond to the key when appropriate, 'p', 'q', 'n', and 'd' (or 'dmp1', 'dmq1', 'iqmp')."**  
The implementation that is being tested has previously passed on the Demo server with just providing the values 'p', 'q', 'n', and 'd'.  When manually adding the values to the response file, XP1, XP2, XQ1 and XQ2,  as seems to be expected from the failure output, the same failure output is given.  It is unclear why the failing status is being given.

**Comment by Kritner** [comment]
We have a hotfix in the works for a few other RSA related things, this will be taken care with that change as well.

**Comment by awnissen** [comment]
When is the hotfix planned for deployment?  I need to set expectations and a schedule.

**Comment by jarnold01** [comment]
Hi @EH-Acumen  - FYI, I just deployed the hotfix to Demo a few moments ago.

**Comment by EH-Acumen** [comment]
@jarnold01 That is fantastic! The responses are now passing.  When can we expect a fix on Prod?

**Comment by jarnold01** [comment]
@EH-Acumen  In about an hour from now.

**Comment by Kritner** [comment]
This change is on production in release [v1.1.0.17-1](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.17-1)
