### ISSUE TITLE
KTS IFC KTS-OAEP-basic - Hash Alg SHA-1 not supported

### ISSUE THREAD

**Issue by jlramage** [usnistgov/ACVP#1170]
**Protocol Section**
https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ifc.html 

**Protocol Question**
Why is SHA-1 not a supported hash algorithm for OAEP basic? Based on SPs 800-56B and 800-131, the use SHA-1 appears to be approved.
Thanks, Jim.

**Comment by Kritner** [comment]
This change is on demo as a part of release [v1.1.0.19](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.19)

**Comment by jlramage** [comment]
Thanks for your consideration and efforts - we'll start testing this immediately! Cheers, Jim.
