### ISSUE TITLE
KAS-ECC Fixed Info Pattern question

### ISSUE THREAD

**Issue by dennismomy** [usnistgov/ACVP#1171]
I'm fielding this question on behalf of one of our clients in regards to KAS-ECC and fixedInfoPattern.
"Our engineers noticed that after vPartyInfo and uPartyInfo, we have to append the ephemeral key. Is there a way to not have to do this?"

**Comment by Kritner** [comment]
Any ephemeral data contributed in the scheme - be it through an ephemeral key, or ephemeral nonce - is currently required for testing.  

https://github.com/usnistgov/ACVP/issues/1023

Has more on this conversation, but I bring some of this into an internal conversation to get it on our radar for a potential update.
