### ISSUE TITLE
KDF component snmp  test vectors

### ISSUE THREAD

**Issue by dennismomy** [usnistgov/ACVP#1173]
I have a questions regarding KDF  component SNMP.   The capabilities file I am using has the passwordLength set to 64 and 128. 
The tests show an 8 byte password.  Is this the expected behavior.  
  "tests": [
     {
      "tcId": 1,
      "password": "TBvrrAHT"
     },

**Comment by livebe01** [comment]
Hi @dennismomy, can you provide test session and vector set numbers?

**Comment by dennismomy** [comment]
This issue is on my end..  I was assuming that the passwordLength in the capabilities was in bytes but its in bits.
