### ISSUE TITLE
Clarify KBKDF fixedData

### ISSUE THREAD

**Issue by swkeypair** [usnistgov/ACVP#1178]
The precise meaning of _fixedData_ for the KBKDF in counter mode is hard to pin down in the specifications at https://pages.nist.gov/ACVP/draft-celi-acvp-kbkdf.html. 

SP 800-108 (page 12) suggests fixedData is inclusive of Length L:
 _In the following key derivation functions, the fixed input data is a concatenation of a Label, a separation indicator 0x00, the Context, and [L]2_.

However, the example given in [Section 9.1 Example Test Vector Response](https://pages.nist.gov/ACVP/draft-celi-acvp-kbkdf.html#name-example-test-vector-respons) just appears to be a random value, and it leads to some uncertainty about the inclusion of L in _fixedData_.

Suggestion:
- in the ACVP KDF specification, clarify the meaning of fixedData, citing the SP 800-108 page 12 statement; 
- use a reasonably correct, formatted example for fixedData to help users.

For example:, rather than this example which doesn't have the 0x00 separator or a rational L value:
- "fixedData": "FBF14DF02EE6C7DABCA6EF9AF59BB9A2"

How about this example:
- "fixedData": "414356505F4B424B4446004E49532D435352430100"

**Comment by livebe01** [comment]
@swkeypair Thank you for these observations surrounding the KBKDF spec. We plan to make several changes to our documentation that should clarify the issues you mention.
