### ISSUE TITLE
Vector Set Download workflow

### ISSUE THREAD

**Issue by hbooth** [usnistgov/ACVP#118]
Currently the Vector Set download has three official responses:
They are ready and here they are
or
Not yet ready try again
or
expired

Do vector sets need to be available after the client downloads them? -- I would say yes until...
How about after successful result submission? -- I am on the fence on this one I lean toward no, but not sure what others think, if no, then I need a fourth response, processed/passed/something else? reusing expired seems like it would be an overload.

**Comment by hbooth** [comment]
Thinking about this a little bit more, I guess I am looking to see at which point, other than expiration, the server can/will/should no longer provide the vector sets.

**Comment by atvassilev** [comment]
I think the vector sets need to stay on the server until they expire, just in case. This protocol is asynchronous so you don't really know if the client got it even if the server sent them. In another example, even if a client may download them successfully it may crash and loose them afterwards. They may attempt to recover the vector sets from the server.  

Recreating vector sets from scratch is potentially resource greedy and may bog down the server. I think it would be better to trade memory for computational resources.

**Comment by atvassilev** [comment]
Thinking more about this issue, should we allow clients to discard/expire vector sets they requested? By default, expired vector sets on the server will be "garbage collected" after expiration, but a client that has no plans to submit results for some requested vector sets and wants to play nice may inform the server to clean them up earlier.

**Comment by hbooth** [comment]
We have the /cancel workflow step already in the spec? Is that what you were thinking or were you thinking something else?

**Comment by atvassilev** [comment]
My understanding is that the cancel workflow spans the entire session, which may have several vector sets. I was thinking about canceling individual vector sets within a single session, while keeping the rest and the session alive. This may be too much flexibility but still...

**Comment by Kritner** [comment]
Resolved from #392 as per PR message
