### ISSUE TITLE
rsa keygen question

### ISSUE THREAD

**Issue by dmomy** [usnistgov/ACVP#1181]
For B.3.6 RSA key gen:
(1)	Is xP1 in the test vectors corresponding to XP1 in B.3.6 step 4.1?
(2)	Or is it supposed to be the probable prime p1 as in B.3.6. step 4.2?

The ACVP spec says (2), but we suspect it is (1)

**Comment by livebe01** [comment]
Thanks @dmomy, we'll update the spec for this.
