### ISSUE TITLE
Safe Primes vector set in error state

### ISSUE THREAD

**Issue by dmomy** [usnistgov/ACVP#1188]
I tried to process responses for demo session 180376. The customer provided responses were initially incorrect so when the customer provided me with another set of responses I tried to update the test session with the new responses.  The vector set is in a error state not in the failed state which is what I would expect. 
The session is 180376 vector set 574916.

 Here is the error
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "BitStrings are expected to have an even number of hex characters. Value was \"e74c803d576e793a6fc730faf201afbb5a5f22a56214f402fb1252d38f366f46294f36759512ec4f4c48e68785763f106ce5a6ba33836991000e60f52840eb................

**Comment by Kritner** [comment]
As the error message indicates, we expect all bitstrings to be composed of full bytes. We don't want to make the assumption of padding the bitstring out to a full byte from "the wrong end of the bitstring".

**Comment by Kritner** [comment]
This issue is also covered under https://github.com/usnistgov/ACVP-Server/issues/119, and will be corrected on the next prod release (fix is currently on demo in release https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.20)
