### ISSUE TITLE
ACVP-AES-CBC-CS1 validation error on payloadLen

### ISSUE THREAD

**Issue by kwong-cygnacom** [usnistgov/ACVP#1190]
The JSON specification indicated that increment can be any value. I don't why the following request failed validation.
[
  {
    "acvVersion": "1.0"
  },
  {
    "isSample": false,
    "publishable": true,
    "algorithms": [
      {
        "algorithm": "ACVP-AES-CBC-CS1",
        "revision": "1.0",
        "direction": [
          "encrypt",
          "decrypt"
        ],
        "keyLen": [
          128,
          192,
          256
        ],
        "payloadLen": [
          {
            "min": 128,
            "max": 65536,
            "increment": 128
          }
        ]
      }
    ]
  }
]

The Demo server returned this error message:
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "ACVP-AES-CBC-CS1-1.0: PayloadLen domain must contain values that are not the AES block size."
    ]
  }
]

**Comment by Kritner** [comment]
If your implementation only supports exactly the block size for payloads,
then ciphertext stealing is not possible to test. A completely block
aligned ciphertext stealing mode is indistinguishable from normal cbc mode.

You must have some ciphertext to steal from a previous block on order to
test ciphertext stealing mode.

**Comment by kwong-cygnacom** [comment]
Thank you.
