### ISSUE TITLE
ACVP ECDSA Algorithm JSON Specification: What is 'componentTest'

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP#1194]
**Protocol Section**
https://pages.nist.gov/ACVP/draft-fussell-acvp-ecdsa.txt

**Protocol Question**
a note after table 3 says: "NOTE: The 'componentTest' property is only valid for detECDSA /  sigGen / FIPS186-5, ECDSA / sigGen / * and ECDSA / sigVer / *  registrations", but the table does not list 'componentTest'.

this comment looks suspiciously like it shoud be 'conformances' (see section 5.1), but the sample registration JSONs include both 'componentTest' and 'conformances' (although componentTest is always set to 'false').  componentTest is not mentioned in any other part of the spec.  what is it?  i know that CAVS 21.4 had a 'component' test for siggen, but not sigver.  none of the test vectors in section 9 seem to have any mention of 'componentTest'.

**Comment by livebe01** [comment]
Hi @mmccarl, from a cursory look, there do appear to be component tests for ECDSA / sigGen / * and ECDSA / sigVer / *, but perhaps not for detECDSA / sigGen / FIPS186-5. So 'componentTest' should have an entry in Table 3. Let me get back to you on the difference between the component / full tests. And I'll work on updating the spec to make it correct and more clear.
