### ISSUE TITLE
RSA KeyGen (186-4) "infoGeneratedByServer" issue

### ISSUE THREAD

**Issue by DiptanilDRoy** [usnistgov/ACVP#1195]
I have come across an issue for ACVTS - RSA (KeyGen) mode. 

Vendor has selected **InfoGeneratedByServer = True** along with **Appendix B.3.3 (probable primes)**.  But while I am generating the vectors, the request file is getting generated with **InfoGeneratedByServer = False**.  I tried it with Appendix B.3.4 , B.3.5 and B.3.6 as well and found out that no matter what parameter we define for **InfoGeneratedByServer** (either true or False) in the regJSON for B.3.3, B.3.4 & B.3.5 it always generates the request file with **InfoGeneratedByServer = False**. Only exception is B.3.6

So just wanted to get some help/suggestion if someone have had faced this issue before or know what tweaks could be made. Any help is appreciated. Thanks

**Comment by livebe01** [comment]
Hi @DiptanilDRoy, I think what you are experiencing may be due to the InfoGeneratedByServer property only being relevant to the AFT testType groups. 

Can you provide the vector set ids?

**Comment by livebe01** [comment]
Closing this ticket due to inactivity. Feel free to re-open this ticket if you have further questions.
