### ISSUE TITLE
Submit test session for validation with an existing validationId instead of moduleUrl

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#1199]
We've been told that we can submit a test session for validation for the old CAVS certs to test new OEs without creating a new module.
But at this point, we will need to provide a moduleUrl for a test session submission. Is there any feature that we can submit with a validation url/id? If so, is there any documentation?

**Comment by livebe01** [comment]
Hi @AndrewHYang, we keep ACVTS and CAVS validations completely separate as ACVTS testing is significantly improved over CAVS. As such, you can't add ACVTS tests to a CAVS cert. Submitting an ACVTS test session for validation using a moduleUrl from the CAVS validation is completely fine and we want users to do this, but note that it will intentionally create a new certificate.

**Comment by AndrewHYang** [comment]
Got you. Thanks
