### ISSUE TITLE
Symmetric Test Model Lacks Function

### ISSUE THREAD

**Issue by DBugger32** [usnistgov/ACVP#12]
Currently there is no indication in Section 3.1 Test Group or 3.2 Test of what function (encryption or decryption) is being tested.  Believe this probably belongs in Section 3.1.

**Comment by jfigus** [comment]
This is specified by the 'direction' in section 2.2.

**Comment by DBugger32** [comment]
Thanks -- missed that.

**Comment by jfigus** [comment]
No worries.  I'll close this issue.
