### ISSUE TITLE
TDES: spec page examples list "keyLen" in registration, but keylen is not required

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1202]
The specification tables all indicate that TDES does not require a keyLen, but the included example registrations all list them. The server seems to ignore sent values either way as they are inapplicable.

Nitpicky, but might help clear up some confusion for people in the future. 

Thanks!
Andrew

**Comment by Kritner** [comment]
I will try to get to this at some point soon, but feel free to submit a PR removing the erroneous properties from the samples if you'd like.

**Comment by livebe01** [comment]
I just put this change through. Thanks!
