### ISSUE TITLE
SP 800-56Ar3 Component Testing for KAS-FFC

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP#1205]
**Protocol Section**
https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ffc-sp800-56ar3.html

**Protocol Question**
Is there component testing (noKdfNoKc) for KAS-FFC under SP 800-56Ar3? If so, the information seems to be missing from the protocol documentation.

What value should be in the mode attribute of the algorithm capabilities for KAS-FFC?

**Comment by Kritner** [comment]
https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ssc-ffc.html handles the shared secret computation testing (equivalent to the noKdfNoKc testing from the 1.0 revision of testing)

**Comment by jbarnesweb** [comment]
Thank you!
