### ISSUE TITLE
Party U Actions in KAS-ECC C(2e, 0s) scheme with regards to auxiliary function

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP#1212]
**Protocol Section**
https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ecc-sp800-56ar3.html#name-test-vector-responses

**Protocol Question**
Is the produced output for the test case below supposed to be the result of following these actions? I'm unclear as to when the auxiliary function (H = Hash) is supposed to be applied.

1. Generate an ephemeral key pair (de,U, Qe,U) from the domain parameters D as specified in Section 5.6.1.2 of SP 800-56Ar3
2. Verify that Qe,V is a valid ephemeral public key for the parameters D as specified in Section 5.6.2.3.
3. Use the ECC CDH primitive in Section 5.7.1.2 to derive a shared secret Z from the set of domain parameters D, party U’s ephemeral private key de,U, and party V’s ephemeral public key Qe,V. 
4. Use the agreed-upon key-derivation method to derive secret keying material with the specified length from the shared secret value Z and other input (see Section 5.8). 
5. Destroy all copies of the shared secret Z and output the derived keying material.

Given the test case below, do I SHA the result of step 3, 4 or 5?

```
      {
        "domainParameterGenerationMode": "P-521",
        "iutId": "123456ABCD",
        "kasRole": "initiator",
        "kdfConfiguration": {
          "auxFunction": "SHA2-384",
          "fixedInfoEncoding": "concatenation",
          "fixedInfoPattern": "algorithmId||uPartyInfo||vPartyInfo",
          "kdfType": "oneStep"
        },
        "l": 256,
        "scheme": "ephemeralUnified",
        "serverId": "434156536964",
        "testType": "AFT",
        "tests": [
          {
            "ephemeralPublicServerX": "009FFB56EDBA11B36E99E1BBD4CCB1B71D53DC097959670C82DAD938DABFB4F9A767D1E238A3E940E183D12661C2AED5431E00358116E428EEE4F8B7002B716F6A6E",
            "ephemeralPublicServerY": "0180C4EA288D4A2E1D347A496047F3717A5697E4575EAE21EAF98C2B1F4F04853A7DFEC5BD1079AFC3ECCCD582812AEBC89C0B93F25817512B77852FA2841AF11838",
            "kdfParameter": {
              "algorithmId": "60CDCBA8230F3B9C63FE37E68A06F726",
              "kdfType": "oneStep"
            },
            "tcId": 1
          },
          ...
        },
        ...
      }

```

**Comment by Kritner** [comment]
> Use the agreed-upon key-derivation method to derive secret keying material with the specified length from the shared secret value Z and other input (see Section 5.8).

From the SP:

![image](https://user-images.githubusercontent.com/8814983/126829119-1327bc4d-61a0-49cc-b15a-8c233201e5dc.png)


Section 5.8:

![image](https://user-images.githubusercontent.com/8814983/126829181-8b48b213-452c-4d16-9018-84dd37cf249b.png)

From SP800-56Cr2:

![image](https://user-images.githubusercontent.com/8814983/126828720-94a7a546-833e-4106-b770-5da0dd147a7c.png)

It's unfortunately a lot to comb through, but the tldr is the auxiliary function (in your case SHA2-384, using a OneStep KDF) is used within Step 6 within the OneStep KDF process "auxiliary function = `H`" as specified in [SP800-56Cr2](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Cr2.pdf)

**Comment by jbarnesweb** [comment]
Thank you!
