### ISSUE TITLE
Conditioning Component blockcipher_DF should allow requestedBits to be specified

### ISSUE THREAD

**Issue by rnunez83** [usnistgov/ACVP#1218]
In [1], there is no indication of a way to specify length of the derived bits to return. 

The specification for the block cipher df is defined in section 10.3.2 of SP800-90A[2]. It specifies that "no_of_bits_to_return" is an input parameter to the block cipher df with "maximum length (max_number_of_bits) is 512 bits". 

In Conditioning Component BlockCipher_DF Test Responses [3] it states:
      NOTE: In the case of BlockCipher_DF, the output is always
      |  128-bits regardless of the size of the input

references:
[1]https://github.com/usnistgov/ACVP/blob/master/src/conditioning-components/sections/05-capabilities.adoc
[2]https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-90Ar1.pdf
[3]https://github.com/usnistgov/ACVP/blob/master/src/conditioning-components/sections/07-blockcipher-df-responses.adoc

There should be a parameter that allows for the no_of_bits_to_return to be specified with a maximum of 512bits rather than the fixed 128bits that are currently returned.

**Comment by rnunez83** [comment]
UPDATE: 
It appears no_of_bits_to_return is not configurable but instead determined by the key size for both Hash_df and Block_cipher_df. Table 1 in SP800-90B[4] standard defines the output length as "AES key size" for Block_cipher_df and "hash-function output size" for Hash_df. Under Table 1 it states "For  Hash_df  and  Block_cipher_df,  the  output  length  indicated  in  the  table  is  used  as  the  
no_of_bits_to_return input parameter for the invocation of Hash_df and Block_Cipher_df (see SP 
800-90A)."

This means the no_of_bits_to_return should follow the Key Size selected in the request file.

[4] https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-90B.pdf

**Comment by celic** [comment]
The output length of the block_cipher_df should be the key size, as you mentioned, from the table in 90B. The requestedBits should not be specified. It will be defined by that table for all conditioning components tested with ACVTS. I've confirmed the issue on our end and we'll get a fix out soon. Thanks.

**Comment by Kritner** [comment]
An update has been pushed to demo for release [v1.1.0.20](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.20), which updates the output of Conditioning Component block cipher tests to be equal to the key length of the test group.

**Comment by rnunez83** [comment]
Thanks Russ and Chris.

I have confirmed that the fix is implemented.

**Comment by Kritner** [comment]
This change is on production in release [v1.1.0.20](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.20)
