### ISSUE TITLE
No definition or explanation for AFT and MCT testTypes

### ISSUE THREAD

**Issue by hbooth** [usnistgov/ACVP#122]
There doesn't appear to be any definition for AFT and MCT, at a minimum spelling out the acronym would be good. There is a general explanation in the top-level specification, but nothing specific in the symmetric sub-spec or any pointers to how a client would know what to do with an AFT vs MCT testType.

**Comment by bfussell** [comment]
All of the specs need some acronym and definition work.  Regarding how to process AFT and MCT, I thought we decided that an informative reference would cover that.

**Comment by hbooth** [comment]
I recall the same thing, but I figure that logging an issue wouldn't hurt in order to be sure we don't forget to add the reference in.

**Comment by celic** [comment]
I realized this the other day as I was making changes to SHA3 for VOT. Add Variable Output Tests to the list. We don't seem to have anything explaining what the purpose of each these tests are. I'm not sure if there is something pointing these definitions to the Validation Suite documents for each algorithm either.

**Comment by atvassilev** [comment]
Can this issue be closed now?

**Comment by atvassilev** [comment]
I think progress has been made towards addressing this issue but I will keep it alive in the "Far horizons" category.

**Comment by Umayrkaleem** [comment]
MCT = Monte-Carlo Tests
