### ISSUE TITLE
Inconsistent revision for KAS KC

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#1220]
Recently, KAS KC was added within ACVP.  It looks as though its revision is expected to be `Sp800-56`.

https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-kc-sp800-56.html#name-example-registration

```json
[
  {
    "acvVersion": "1.0"
  },
  {
    "id": 178,
    "name": "KAS-KC",
    "revision": "Sp800-56"
  }
]
```

This is different than the other algorithm revisions which designated this normally as `Sp800-56Ar3`.

Is this an intentional deviation or should KAS-KC revision be `Sp800-56Ar3`?

**Comment by Kritner** [comment]
Hey @AlexThurston unfortunately there isn't "one SP" that applies to SP800-56* as it relates to key confirmation.

Given that the KC testing should be valid for either "A" or "B" of SP800-56, I opted to go just the "SP800-56" route - it is not yet on production though so at this point would be simpler to change.  My other thought was potentially "Sp800-56A/B" but I thought the "/" was a bit strange.  

Did you have any suggestions that would allow it to be inclusive to both A and B?

**Comment by AlexThurston** [comment]
I don't, no.  In fact, with this explanation it makes sense.  In reality, because I hadn't encountered this scenario, I thought that it might be a typo so I wanted to make sure that it wasn't the case.
