### ISSUE TITLE
RSA Keygen according to B.3.2 generates wrong seed length

### ISSUE THREAD

**Issue by QuentinGouchet** [usnistgov/ACVP#1226]
RSA Keygen according to B.3.2: ACVP provides vectors with expected responses for 4096-bit RSA key generation with a seed length of 32 bytes. I do not believe that there is currently a way to specify the seed length for expected responses.

FIPS 186-4 specifies that seeds have to be at least 2 * security_strength (section B.3.2.1, step 3). For 4096-bit keys, the seed would have to be 38 bytes long (security_strength = 128, seed length = 256 bits = 32 bytes).

When providing response vectors with a 38-byte seed, those responses failed to verify against ACVP. 2048 and 3072 keys were successfully verified by the ACVP server though, with respectively 28 and 32-byte seeds.

Where do the specs specify what seed length is supported by ACVP? Should the seed be 38 bytes for 4096-bit keys?

**Comment by Kritner** [comment]
The minimum seed length for a 4096-bit key should be 32 bytes.  Where is the addition 6 bytes in your 38 coming from?  Like you said it should be `2*security_strength`, and the estimated security strength of 4096 is 128 bits.

![image](https://user-images.githubusercontent.com/8814983/130620848-e1b4983c-f924-4a43-8f63-ee8e1a6f658f.png)

a 38 byte seed should be valid for RSA, but I would your vsId/test case ids in order to do any sort of verification or confirmation on why a specific test case failed.

**Comment by QuentinGouchet** [comment]
The testIDs/vsIDs failing with a 38-byte seed are: 185745/606921.

The generated keys failed ACVP with 4k size. One example that failed with a 38-byte seed is:

"e":"010001",

"seed":"9bb5386181f34a504f092b684c7a1e735b953d32643898c8991a40157708480203408eeae1da",
            "p":"e58e9bce71f817599f0054e4da8b4884c8caf901537893c3bdddf6a2342c170e4c0c4a49e517698ce654c889891e7c1c96267b287f05b312a390c9ecb8999676dbd8f2e069034113d1ba1c280276e3ce0bcceea0046ca991027fa0eebc3f82f6b6212c3c47f64242b0f7f4655656e91fd6228c08e87f49af5516e1e43a7774903e5761cef8b56c8f7d46204d8156ec526ced1a8eaf4b50334407093cb85b22e01c727080f1ee4c4488109f51d909825c5bbd9d1d7680685248bd4c8b08dd9f0580cdb9d6799bda816569dd61e5be517f51df186baa06af8251ec5ef58d75124a27b0065e32777bfc1fd7edc8d3cbaddd778efeb2e08c0364a423bfec8c255347",
            "q":"c00db690b54c51707892dbf1cc03ffe915bc9de52da0bd14bebca257dc8b63e632f7697ef0ce7a6503582882bf8df1a13490483fceca697306c10363ad712c2c3391c23a0cab4c9655caa2ad0f58c8e10fcff4ace850b049171568aa69ac398d231e1f2f28f1d2b371d97b61382e0c38419ac664045135e8c6267a7dae004cda455f2f4bfdb65ac0d5ecedfc50b523f630398ae8019f3b1f1fbd6bd163e24a46b4628383065de2fc1d442338e9104e9c1b6db21e44995d68da9435bf56d7918f3e805d226d06972987bd41f0e931d22dadab946aa91a6b247741e6bfe87cfed453399285d2552a2c751ab9769ca5d6e341795c4cc9da3fd23c0aab37d3b461df",
            "n":"ac3740cde48487c914a17045baaad3ca269a53cd80d80c25f84b2583f4ec4969703a5a6d9fef5c74a1c34d9a60293275a8625b6086a8ea0d85dd8291b84c669183f057b7df3278884dd86d9870759d4ff6400cd14fb4f20935255462922f21a3f32f385f20cfef636db9f55f496fc9674ab78dffcf238ca894f2cde7257c59fdcd2013756785edc440df5214b2398639ab3307926f47ad8352d34a0c7d755851b6fe5a8766975f521703027894c0720e4a0cf6c9eb23586ee83d34b01a897eb41dbb635e2774673a34f98af8c549dd95d5ba45b74a72308eff878ba8df9f830107f7888f7dc24e8d6dc50c2986d4cfe66dd4867da4f757d12fa303bb6e6addc0dd996cba21cd293be968dded74935297c5ce54c9c45e43ea39622d2aa87be5d175b2c8d2f58f6a1577be5a69066fed4317a82b665b07637fcb399222eb52a53b2a6b96ad184127850228b243e2639e3f8c3c6cc8934b3b3555acc672764d81842df5f82856633268e3056f867c510cee570b67486df8b454f0175b82b2f4303693d44a92cd8ee3ecfc3fbfa8559da76a0d9f1d381706a57eed67e71ceece56533864ec949166d7299ed9c90476512e948c99f0ce484d5e0092091084191ba8d672dc2ab60ff3aa9fad0b79816f4bb5ef87071d20e1eff416d1c09a6107e17d5b2135510001f24f5205c51e3edbbf60cb59433690e1d736d6601d6f4b4bfd71d9",
            "d":"0a568b7330acccb298a49e51994492fa82246689221b16139b704b66bca7b33a7b4c62cc4ce5b8bb9efafde81958afc39a0c44270069186fca6198952326a1a0f4f6286b3720acfffb0855d53e545926b3db76c983e03d5d54783d5f68c8ca8605ddb24e72464e9268990403fdd667953b4a2c8c8c2f3aa238c575f07d1d6b66387a474b6cca55e7ca407db414af83ac123d0f247913539fb15e5206264135403bdcd0ab6b25b01e59ecf4d38493cee4fbb35931ed85cd7e643e49b0e94ee8066ba3299d127f98337425a7743547b0b518c39a0172f1cae772ab278a4783a8561757d7e0a145d8f8557c16e0514c94d464ddcab05fdc4c99c2a325b60a8956196f5a28205e5a2239fd9a36f89fa7ba17ccdf401be9edb42d143e38da4d3f5dc38e4d71550e69db4dbc19607aa59646f69b695725a193cd6a20da8e4402fb39e7894b72bf1e379b0e7a6c8d7afc00bd9214535cbf49a975109dd960f2a75d79ced771b089eb0eb51f03d9bb4316c52c84a39fe37c4fd30d8e13b5a86d46aa7f438c68c9b99f76674bcce6cafe52509aed7221268890c17972c3551bf8e17c107b4ec0e39a2e8eb2960ce5dc3f27148c6fdd10d5edd9c071fb77b62e24049f599dbc12788334fd400edfe16c9125a5899b53cdcd0c8a13c7156f764aa892ab4d933b250ad4274caba1d0b8d9aae33d4fcb1580f8584dd1dfd615d47a7fd4522037"

**Comment by Kritner** [comment]
Comparing intermediate values for this I assume is going to be not fun... I won't be able to jump onto doing so for a bit, but here is what our side is generating as the P/Q given the provided seed of `9bb5386181f34a504f092b684c7a1e735b953d32643898c8991a40157708480203408eeae1da` using SHA2-384 with an exponent of `010001`:

```json
{
  "p": "DCBF497FFB30349790F0FE132AB024041FAE710BEC43222C36B73D2EC4C6DFC1F27DEF71584562B6C27A076A0C025540B9A56EE2B2EC2F164554D4F14AC1A8D29086A992607F59B8A4D104BFA892A9D1F894E7F07B113ED5C37A05F60EE9F77395100B4D3E2BE96EA6072640BC4E906D1BF9BB830357D345FA691BF55C98CEAF3B0F5B78BC9882D90B4C6A3DC1552B886E91B3BE95A38A1D40B2467011CCD25B234978247C3A6165E1275395573C660F65721C8A4EA4FCAFBBF45B00D2387FD60D66C615E0F2D3C3F22473293C2C359D38DBBA77D4141C4FEBF33426DFF9F4C8B5756F2ECDB7833B8EA5F344C98F56B17A1461795A67DE12C38BDAE881EC29A7",
  "q": "D461BCC1C86351E0218C148A5F66858DE924A0436059F990E1BDD95E5706765AE92B2A43FF3A04702DE0233A73C50F8C07584834E4C74496C043985CCC6DE454C61BA8A5F134D79B91177DB41F61F4417BBBD8865703D118FE18C182C779BFB54452BA530D13673C3C5794DF06BF4E3E6487F8BC193DA08A97383B984BF95883A92E080787D4F5D7F7A6F6A4B502F059A279491220673B65A870005A7DD262DDA5D6D49D165FBDC6220ABA245E1B908C6BEEA794F238AA0B622AF33089FAF1455E641BD709E558ACD0DFA674707934F4B67210508BC836AB64778595418461CC1DD67A9016F9F5EA0DC39EB0CF0912DC780F6F9157DB295708F4BE45F87FF593"
}
```

I see this vector set is passing for the lower modulo, just not the 4096 one, have you attempted testing at even higher modulo? I'm curious if it can be narrowed down at all where the issue lies.  Is this a set of testing that has passed previously for you?  

For what it's worth, I checked out a local copy of a previous release and got the same P/Q as the one I posted above, just to help ensure it wasn't something newly introduced with a release.

**Comment by QuentinGouchet** [comment]
Yes, lower moduli passed without problems! When I set the seed to 32 bytes, it passes for 4096-bit keys as well. But not with 38 bytes. I am not sure if the issue comes from the IUT or ACVP, and that's what I am trying to find out as well right now.

I cannot test higher moduli. I do not think that ACVP currently supports anything higher than 4096 for FIPS 186-4 (-5 will support 8192 bits according to the specs).

**Comment by Kritner** [comment]
Ah, yeah sorry I missed that this was 186-4 testing, not 186-5 - you can register for 186-5 testing against the higher mod sizes against demo if you're at all curious about it.

Glancing over the logic of the generation, I'm not sure why we'd be running into an issue offhand... though one thing to watch out for is the ShaweTaylor algorithm, it relies upon hashing numbers, which is seemingly done on `nLen % 32 == 0` bitlength messages - so your 38 byte seed would seemingly require padding up to 320 bits prior to being hashed, for a consistent interoperable hash.

I don't recall the specifics on why this is done as I'm not super familiar with RSA, but I would bet it's a decent area to look at for a potential issue.

**Comment by QuentinGouchet** [comment]
Reading FIPS 186-4, it seems like Shawe-Taylor seems to be used for DSA keys (since L and N are the inputs), whereas B.3.2 has its own way of generating the primes p and q (using appendix C.10). In C.10, I do not think that the seed needs to be of a specific length-it just gets hashed. Let me know if I misunderstand something here.

**Comment by Kritner** [comment]
C.10 makes reference to C.6 however, so it's seemingly in use for both DSA and RSA.

![image](https://user-images.githubusercontent.com/8814983/130657791-6eb8a701-e51c-4b28-a0b1-a2a193c52c4d.png)
![image](https://user-images.githubusercontent.com/8814983/130658082-cf7564b4-b67e-462f-a1b0-9c8c349d02ba.png)
![image](https://user-images.githubusercontent.com/8814983/130658216-03148815-70cc-4e7d-9319-a5d205bf9ebf.png)

Regarding the 32 bitlength for hashing numbers, I don't recall the specifics here unfortunately.  @celic would you happen to be able to shed some light on this?

Using the exact seed lengths that go with 128, 192, and 256 based security strength you never run into this issue as those are all already evenly divisible by 32.  

Regarding the IG 7.5, IIRC there has been some back and forth in the past that the 4096 mod RSA keys should fall back onto the security strength of its "closest symmetric cipher counterpart" from the table - 128 bits in this case.

Will need to do some further research for anything concrete, mostly just documenting what I recall from previous issues and/or conversation.

**Comment by celic** [comment]
Any time a standard says to hash an integer value, it considers the value to be a multiple of 32 bits, which is the common way integer values are stored. This includes multi-precision libraries for integers that exceed 32 bits. They are often stored as a multiple of 32 bits as more space is needed.

**Comment by QuentinGouchet** [comment]
I do not see anywhere where the seed length should be a multiple of 32 bits. Can you point me to it?

**Comment by celic** [comment]
Unfortunately it is not stated anywhere and has a bit of history. I cannot find any historical references to help out here. 

I can point you to FIPS 186-4 Annex C.2.2 which states that `In this Standard, the binary length of the integer C is defined as the smallest integer n that satisfies C < 2^n`. This is noticeably against the current practice. When the CAVP originally came out with testing for DSA and RSA in CAVS, all integers were treated as a multiple of 32-bits regardless of the true bit length. This is likely due to the nature of the multi-precision integer library. When I wrote these algorithms for ACVTS, I couldn't get my tests to match CAVS for exactly this reason. We made the decision then to keep ACVTS testing in-line with CAVS. If modules were passing the CAVS tests, then we wanted them to pass the ACVTS tests as well. 

After FIPS 186-5 is published I believe this will only impact RSA in a limited number of cases. It would be an ideal time to fix this and realign with the standard. Just a thought.

**Comment by QuentinGouchet** [comment]
Do you what happens on your end when we provide a 38-byte seed? Is it truncated, or padded to 320 bits? I wonder if I could artificially do the same on the my end before posting the responses.

**Comment by celic** [comment]
A seed is padded to the next multiple of 32-bits. 0-bits are added to the left side of the value to keep the integer value the same.

**Comment by QuentinGouchet** [comment]
Yup, that did it. I use a 40-byte seed and it passed. So padding was the issue! Good to know, thanks!
