### ISSUE TITLE
In symmetric sub specification it is not clear which capabilities go with which algorithms

### ISSUE THREAD

**Issue by hbooth** [usnistgov/ACVP#123]
Table 2.2 provides a combined list of all of the capabilities for the various symmetric algorithms, but it is not clear from the table which capabilities go with which algorithm. I think removing the optional (and maybe even the valid values) column(s) and creating another table which maps the capabilities to the algorithms may make it more clear.

An additional example of the problem can be seen that ptLen in the table is marked as not optional, but (at least in CAVs) ptLen is not used for some of the algorithm variants.

**Comment by atvassilev** [comment]
resolved with PR #138
