### ISSUE TITLE
Question on EC key verification using P-521 

### ISSUE THREAD

**Issue by krissridhar** [usnistgov/ACVP#1233]
Hi,

I have this strange problem where in order to verify if the Qx and Qy are points on the given curve fails for ACVP tests based on P-521. This is not an ACVP server/parser problem as I see that in case of OpenSSL tests, the very same vectors pass. However I'm trying to run the key verification tests on Go/Elliptic module where I'm facing this trouble. 

I understand, at a very high level that qx and qy would usually have the same bit size that is corresponding to a specific curve. For instance the qx and qy would usually have 48 bytes for P-384 and so on. In case of P-521 however, this may be 65 bytes sometimes and upto 66 bytes. I also realise that the length of qx and qy need to be read accordingly. This is where I can't seem to find a lead on how this is done for P-521. 

Any help here is highly appreciated! 

Thanks,
Krishna

**Comment by Kritner** [comment]
I'm not sure what exactly is being asked here, is it specifically around the padding used for curves?  If so, then this seems to be effectively the same question as the one here: https://github.com/usnistgov/ACVP/issues/1196, specifically https://github.com/usnistgov/ACVP/issues/1196#issuecomment-865001574 and https://replit.com/@Kritner/ExpectedBitLengthOfZ#main.py.  If I am not interpreting the question properly, I'll need some additional information.
