### ISSUE TITLE
Should count in resultsArray example be removed

### ISSUE THREAD

**Issue by hbooth** [usnistgov/ACVP#124]
According to the comment on #41: https://github.com/usnistgov/ACVP/issues/41#issuecomment-273174667 it appears that count should not be inside the resultsArray. Is this correct? If so, we need to update the specification.

**Comment by celic** [comment]
Yeah, count should be implied from an array as the ordering is forced. This is referring to the symmetric spec right?

**Comment by hbooth** [comment]
Yes, sorry. This is for the symmetric sub specification. I should have stated that in my original comment.

**Comment by atvassilev** [comment]
I am reclassifying this as a bug.

**Comment by atvassilev** [comment]
Resolved with PR #126
