### ISSUE TITLE
Maximum message length for SHAKE hash algorithms?

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1240]
Hello!

Currently, there is no way to indicate in the protocol a maximum message length for testing SHAKE. The specification also does not seem to mention a maximum message length unless I am missing it. Is there a hard maximum message length for SHAKE for the sake of testing? I would assume 65536 as with the other hash algorithms, but I am receiving some vectors with message lengths beyond that (66240, 65752 lengths in test session 200002 on demo).

It is favorable to have some sort of programmable max for the sake of input validation in clients.

Thanks,
Andrew

**Comment by livebe01** [comment]
Hi @abkarcher, sorry for the slow reply.  I just added the info you requested for SHAKE to the spec, see [here](https://github.com/usnistgov/ACVP/blob/master/src/sha3/sections/06-test-vectors.adoc). The lengths that you were seeing in your test session are the max lengths for SHAKE-128 and SHAKE-256 as long as inBit is set to 'false' in the capabilities registration. If inBit is set to 'True', then the max values for 'len' are 65,904 for SHAKE-128 and 66,428 for SHAKE-256.

**Comment by abkarcher** [comment]
That is perfect, thank you @livebe01! Closing.
