### ISSUE TITLE
Does ACVP AES-CTR mode testing address SRTP's use of AES-CTR?

### ISSUE THREAD

**Issue by ldgibbons** [usnistgov/ACVP#1242]
**Protocol Section**
Is your question regarding a specific section of the protocol?  You can link it here.
https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html#name-test-types

**Protocol Question**
SRTP encryption described in RFC 3711 uses AES-CTR mode, but increments only the low 16 bits of the 128-bit IV as the encryption/decryption process moves across the VoIP packet, with no rollover into the 17th MSB. The upper 112 bits of the IV are split into fields, with the packet index being incremented for each transmitted/received packet. The low 16 bits of the IV (block index) increment as SRTP moves across the VoIP packet in 16-byte strides. SRTP does not treat the IV as a simple 128-bit counter, yet the test generation parameters offer no options on the description of the counter. Are ACVP AES-CTR tests applicable to SRTP?

**Comment by celic** [comment]
The CTR tests were not designed with SRTP in mind. That said, that doesn't mean they aren't applicable, but they are not required in any way. [SP 800-135r1](https://nvlpubs.nist.gov/nistpubs/legacy/sp/nistspecialpublication800-135r1.pdf) offers no guidance on how the cipher is set up within SRTP. It _could_ be ECB, adding `1` to the plaintext after each call. It _could_ be CTR where the counter is that value, and the plaintext is all `1` bits. Nothing within our testing or guidance suggests one is correct or incorrect. 

I think the answer you are looking for is that no, CTR is not a prerequisite for SRTP. At a minimum, ECB would be a prerequisite. I suppose CTR _could_ be a prerequisite for SRTP, assuming the "incrementingCounter" option is true.
