### ISSUE TITLE
KAS-KDF OneStep CR2 secondary shared secret "t" 

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1243]
Hi,

Could I confirm that it is valid to supply the following fixed info pattern with OneStep please?

```"fixedInfoPattern": "algorithmId||uPartyInfo||vPartyInfo||t",```

The server did not supply vectors with the "t" value in the "kdfParameter" block.

I have attached the capability json, and some returned vectors and sample.

Please let me know if you need any more information!

[OneStep-CR2.zip](https://github.com/usnistgov/ACVP/files/7167309/OneStep-CR2.zip)

**Comment by Kritner** [comment]
@mwcw Yes the `t` value should have been included with the prompt file, I'll get it added in the next release.

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.21](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.21)
