### ISSUE TITLE
KAS-KDF CR2 OneStep accepts performMultiExpansionTests as true but does not return appropriate vectors.

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1245]
Hi,

After making a request for vectors with expansion, the demo server does not return vectors with ```kdfMultiExpansionParameter```.

These vectors pass when treated as non-expanding.

I have attached capability json, vectors + samples returned.

Let me know if you need any more information!

MW
[Archive.zip](https://github.com/usnistgov/ACVP/files/7175341/Archive.zip)

**Comment by Kritner** [comment]
I had misread this initially and thought it was for a TwoStep KDF, the one step KDF does not allow for multiple expansions:

![image](https://user-images.githubusercontent.com/8814983/133624735-58a6de8c-6571-4dce-b4fb-55225841fc9d.png)

**Comment by mwcw** [comment]
Hi, 

Thanks for the clarification and sorry for consuming your time.

I will close the ticket here.
