### ISSUE TITLE
Questions about cSHAKE256 MCT

### ISSUE THREAD

**Issue by tpj** [usnistgov/ACVP#1246]
I've received this MCT test vector for cSHAKE256:
(I set `increment=8` in the algorithm form since our cSHAKE256 only handles bytes.)

Test vector:
```
{
    "vsId": 573821,
    "algorithm": "CSHAKE-256",
    "revision": "1.0",
    "isSample": true,
    "testGroups": [
    ...
        {
            "tgId": 2,
            "testType": "MCT",
            "hexCustomization": false,
            "minOutLen": 16,
            "maxOutLen": 65536,
            "tests": [
                {
                    "tcId": 101,
                    "msg": "E6487934DBA8D81C604F3638832E8BF43796AD8DE34D7683A1EBFFF680C6F6FF",
                    "len": 256,
                    "functionName": "",
                    "customization": ""
                }
            ]
        }
    ]
}
```

Expected result:
```
{
    "tgId": 2,
    "tests": [
        {
            "tcId": 101,
            "resultsArray": [
                {
                    "md": "F392EE3BFC744AE1E7C0B2BAD...",
                    "outLen": 24712
                },
                {
                    "md": "9C1C59EFD5E7561EAA840E151...",
                    "outLen": 8016
                },
                {
                    "md": "37E3032E012206AF5145F2784...",
                    "outLen": 15696
                }
            ]
        }
    ]
}
```

Questions:
- Acccording to the cSHAKE256 MCT (https://pages.nist.gov/ACVP/draft-celi-acvp-xof.html#section-6.2.1) there should be 100 md's in `resultArray`. Why are there only three in the expected result?

- The MCT specifies `Range = (MaxOutLen – MinOutLen + 1)` which gives Range = 65536 - 16 + 1 = 65521. But 65521 is not a multiple of 8. So when we in the inner loop compute

     `OutputLen = MinOutLen + (8 * Rightmost_Output_bits % Range);`

  we end up with a new `OutputLen` that is not a whole number of bytes. Is this the intention?

- In the inner loop we compute

      Rightmost_output_bits = Right(Output[i], 16);
      OutputLen = MinOutLen + (8 * Rightmost_Output_bits % Range);

   In the last line the 16-bit `Rightmost_output_bits` is interpreted as a number. Is this little or big endian?

**Comment by livebe01** [comment]
Hi @tpj, 

I just took a look at your questions related to cSHAKE256 MCT testing. For the first bullet, we only compute the first 3 md's when isSample is set to true in the registration for cSHAKE. isSample set to true is only allowed on demo. Only calculating the first 3 md's is a shortcut we've taken to allow us to generate vector sets more quickly on demo. If you want to perform a test using all 100 rounds, you should be able to accomplish this by setting isSample to false.  

Looking at the 2nd bullet, I believe that OutputLen should always evaluate to a whole number of bytes. `(8 * Rightmost_Output_bits % Range)` will always evaluate to a multiple of 8 and minOutLen is equal to 16 bits. Their sum should always be a multiple of 8.

For #3, 'Rightmost_output_bits' is little endian.

Sorry for not getting back to you before now.

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.22](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.22)

**Comment by livebe01** [comment]
@tpj see also the updates to the MCT pseudocode [here](https://pages.nist.gov/ACVP/draft-celi-acvp-xof.html#name-cshake-monte-carlo-test)

**Comment by livebe01** [comment]
This change is on prod in release [v1.1.0.22](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.22)
