### ISSUE TITLE
KAS-KDF TwoStep kdfParameter missing "l" value.

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1249]
Hi,

KAS-KDF TwoStep vectors are missing the "l" value from the kdfParameter block.

I have attached a set vectors for TwoStep where it is missing in the req file and the capabilities.json we used where the fixedInfoPattern specifies ```"fixedInfoPattern": "l||label||uPartyInfo||vPartyInfo||context||t",```

Please let me know if you need any further information.

MW

[Archive.zip](https://github.com/usnistgov/ACVP/files/7214908/Archive.zip)

**Comment by abkarcher** [comment]
This also seems to be the case for HKDF (at least in SP800-56Cr1 testing). OneStep seems fine in my initial request.

Thanks,
Andrew

**Comment by Kritner** [comment]
This change should be on demo

**Comment by Kritner** [comment]
This change is on prod in release [v1.1.0.21](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.21)
