### ISSUE TITLE
sub_hashmac spec still has references to SHA specific capabilites

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#125]
Section 2.1 needs to go, some of verbiage in section 2 may not be needed as well.

**Comment by atvassilev** [comment]
Generally, I agree. Section 2.2 needs some attention too , to provide some examples for prerequisites for HMAC.

**Comment by bfussell** [comment]
Appendix A has both HMAC and CMAC capailities including prerequisites.  Is that what you are looking for ?

**Comment by atvassilev** [comment]
Yeah, this would work. How about referencing Appendix A in Section 2.2 or in Table 2, just to alert the reader there are examples of prerequisites later in the spec?

**Comment by bfussell** [comment]
will do.

**Comment by atvassilev** [comment]
Resolved with PR #129 .
