### ISSUE TITLE
ACVP-AES-CCM aadLen of [0,496,880] returns only aadLen of 0 and 256

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1250]
Hi,

This was reported by one of our clients for ACVP-AES-CCM aadLen the client needs to specify the domain as an array of values.

The server is accepting the capabilities request but returning unspecified aadLen(s).

I have attached a capability.json and a returned set of vectors.

Please let me know if you need any more information.

I would like to cite the following documents:
```aadLen``` is defined as a domain here: https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html#section-7.3
```domain``` type has an example as an array of ints: https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#section-17.4.1

MW

[Archive.zip](https://github.com/usnistgov/ACVP/files/7214975/Archive.zip)

**Comment by Kritner** [comment]
Sorry for the delay, will be correcting this in the next release

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.22](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.22)

**Comment by Kritner** [comment]
This change is on prod in release [v1.1.0.22](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.22)
