### ISSUE TITLE
SP800-56Cr2 fixedInfoPattern min size

### ISSUE THREAD

**Issue by QuentinGouchet** [usnistgov/ACVP#1256]
We were wondering what the minimum size for the fixedInfoPattern is for the SP800-56Cr2 KDFs, as a standalone KDF or as part of SP800-56Ar3.

We were not able to find the information here:
https://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56ar3/ecc/sections/05-capabilities.adoc#fixedinfopatcon

**Comment by Kritner** [comment]
Hey @QuentinGouchet  I'm not sure what you mean by the minimum size of the pattern - are you asking about the minimum size of the produced fixed info? or the literal string pattern?

In either case currently, there is no real "minimum size", the fixed info pattern for testing purposes ***MUST*** contain both `uPartyInfo` and `vPartyInfo`, anything else is optional.  the party info is a concatenation of ephemeral data provided by both parties as a part of the key agreement, the size of which depends on the domain parameters being used for the generation of keys that are going into the agreement.

Does that answer your question?

**Comment by QuentinGouchet** [comment]
hi Russ,

Yes, I believe it does answer my question thank you!

Quentin Gouchet
-----------------------------

**Comment by SecDino** [comment]
Hi,

I hope you don't mind if I jump in.
The problem would be in case of ACVP testing of resource constrained systems in which the bare minimum literal string pattern length for the _FixedInfo_ should be carefully defined. The mandatory fields are _uPartyInfo_ and _vPartyInfo_ but I am not clear with something regarding the ID literal sizes.

A couple of examples (referring to the ACVP tests):

**Sp800-56Ar3 (KAS-ECC)**
The minimum _FixedInfo_ is the concatenation of the _iutID_ (or the _serverID_ depending on the party) and the public key coordinates. This means min_len(_FixedInfo_)= len(_iutID_) + len(_x_) + len(_y_).
The length of x and y depends on the ECC curve selected but what about the _iutID_? Is this fixed to 32 characters (i.e. 128 bits)? Also, can _iutID_ and _serverID_ have different string lengths?

**Sp800-56Cr1 (KAS-KDF)**
Here the concept is similar with the exception of the naming conventions. The minimum fields of _FixedInfo_ are (the concatenation of) _fixedInfoPartyU.partyId_ and _fixedInfoPartyU.ephemeralData_ (if present). Same happens for _fixedInfoPartyV_. On one hand, _ephemeralData_ has the same length as _z_ but what about fixedInfoParty*. Is it still assumed as 32 characters (i.e. 128 bits)? As above, can fixedInfoPartyU.partyId and fixedInfoPartyV.partyId have different string lengths?

**Comment by Kritner** [comment]
> Same happens for fixedInfoPartyV. On one hand, ephemeralData has the same length as z but what about fixedInfoParty?. 
Is it still assumed as 32 characters (i.e. 128 bits)? 

Based on the last sentence, I'm assuming this was in regards to fixedInfoParty.Id?  The ACVP server (for whichever party) currently uses a static ID to represent it's `partyId`, specifically `434156536964` from the CAVS days.  Regarding the IUT party ID, in the case of the ECC SP800-56Ar3 testing, the IUT is able to provide their own ID, the length of which shouldn't matter save it being not empty/null.  In cases where *we* generate `partyId`s on behalf of either partyU or partyV, those IDs should be at a bitlength of 128, if you find any differences that is likely in error on our end.  All that being said there are no "hard requirements" on the `partyId`, we are simply (currently) using it as a means of testing the party information contributions from the perspective of both party u and party v, to ensure that information is being constructed in the expected manner.

> As above, can fixedInfoPartyU.partyId and fixedInfoPartyV.partyId have different string lengths?

They *CAN* have different lengths yes.  The ACVP server will always use (depending on the test) the static ID of `434156536964` to represent its `partyId`, or a 128 bit random ID.
