### ISSUE TITLE
Release for v0.3 instead of Branch

### ISSUE THREAD

**Issue by celic** [usnistgov/ACVP#127]
Git has the feature of creating 'releases' for repositories. You'll notice these on the main repository page near the branches view. A release just tags files at that specific point in history so that you can go back and view how files were at that time. This is usually preferable to creating a branch as it doesn't create a new copy of the code. If we wanted to update something right now, we would have to push the changes to two separate branches or risk some merging conflicts depending on where the changes originated. 

I've never used the release feature on GitHub, so I'm not entirely sure how to set it up, but it might be worth looking into for our v0.3 release.

**Comment by atvassilev** [comment]
I think this is worth looking into. I am not sure we want to position v0.3 as a release since it will be incomplete - not all algorithms will be ready by the expected timeline for v0.3 - but will go with what the consensus opinion. As the Romans used to say, vox populi vox dei,

**Comment by celic** [comment]
Yeah I'm not sure how to position it with this sort of alpha/internal release, but it seems preferable to workflow over managing multiple leading branches.

**Comment by atvassilev** [comment]
The process appears pretty straightforward - see https://help.github.com/articles/creating-releases/
 We can trigger one of the options listed if/when we agree v0.3 is ready.

**Comment by celic** [comment]
Great! We can indicate the release is a 'pre-release' as well to help avoid any confusion.

**Comment by Kritner** [comment]
Yeah, this threw me when doing work on the spec today, as the comparison on "evenness" with the upstream (this repo) is from my local branch to master, not the v_0.3 branch.

**Comment by celic** [comment]
I'll close this issue as we have moved forward with v0.3.
