### ISSUE TITLE
SPEC: clarifications to ANSI X9.63 needed

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#1271]
Typo: https://github.com/usnistgov/ACVP/blob/master/src/ans9.63/sections/03-supported.adoc refers to ANSI X9.42

Unclear statement: keyDataLength and sharedInfoLength can be a Domain - but the spec is a bit vague here and does not define the step size limitations.

Clarification needed: fieldSize is well defined. But when my IUT may only have one field size as it implements only one curve, the server rejects it:

Request:

```
        "fieldSize":[
          256,
          256
        ],
```

Error:

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "kdf-components-ansix9.63-1.0: Invalid Field Size supplied: "
    ]
  }
]
```

Only after changing the field size to the following, the server accepts it:

```
        "fieldSize":[
          256,
          283
        ],
```

**Comment by livebe01** [comment]
Hi @smuellerDD, thanks for pointing out the X9.42 typo. I'll get a fix in for that.

For keyDataLength and sharedInfoLength, it is true that we accept the domain type for these. I believe that you can specify a step or increment, but, as stated in the Description in table 2, we're only looking for a minimum and maximum for these. If you provide a domain that includes >2 values, we only use the smallest (min) and largest (max) values provided.

Please double check your question regarding fieldSize. Your example includes 2 identical field sizes, not one field size. When I attempt a registration that has 2 identical field sizes, I also get an error. However, when I submit a registration containing only 1 valid field size, I did not get an error on my end.

**Comment by smuellerDD** [comment]
Am Montag, 8. November 2021, 17:01:45 CET schrieb livebe01:

Hi livebe01,

> Hi @smuellerDD, thanks for pointing out the X9.42 typo. I'll get a fix in
> for that.
> 
> For keyDataLength and sharedInfoLength, it is true that we accept the domain
> type for these. I believe that you can specify a step or increment, but, as
> stated in the Description in table 2, we're only looking for a minimum and
> maximum for these. If you provide a domain that includes >2 values, we only
> use the smallest (min) and largest (max) values provided.

All I am suggesting is to update the documentation in this respect.
> 
> Please double check your question regarding fieldSize. Your example includes
> 2 identical field sizes, not one field size. When I attempt a registration
> that has 2 identical field sizes, I also get an error. However, when I
> submit a registration containing only 1 valid field size, I did not get an
> error on my end.

Yes, that works. But the spec seems to indicate that I must have the min and 
max fields.


Ciao
Stephan

**Comment by livebe01** [comment]
Sure, that makes sense. I'm about to push through some changes that I think will make the whole min / max thing a bit more clear.

**Comment by livebe01** [comment]
PS I'll close this ticket w/ the pull request, but if anything seems unclear w/ the changes I made, please ping me.
