### ISSUE TITLE
Enhancement suggestion: request/<ID> endpoint features

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1272]
Hello,

We had some thoughts one one or two enhancements that might help us as users manage the flow of requests to the NIST server.

For one, it might be helpful if doing GET on /acvp/v1/requests/<request ID> showed some info about the request, especially in the initial status. E.G. a validation request showing what URLs (or inline resources) got submitted. 

For two, it might be helpful if DELETE was supported on /acvp/v1/requests/<request ID> for requests in the "initial" status. 

Together, these would allow users to quickly verify and fix any issues with submitted requests without having to get server administrators involved (or having to get lab managers to find logs).

Thanks,
Andrew

**Comment by abkarcher** [comment]
Hi Ben,

Thanks for the response. For the first topic, I agree that the labs have these copies; this would be more a minor convenience for getting info about stalled requests without having to query the copies. It definitely is something labs can already do themselves.

The delete would be useful for stalled requests, but also for correcting requests that maybe included typos or formatting errors before asking for review (in which case, we would delete and create a new request).

Thanks,
Andrew

**Comment by livebe01** [comment]
Thanks Andrew. We'll keep these in mind as v2 feature requests
