### ISSUE TITLE
Unable to generate vectors on production server and demo server

### ISSUE THREAD

**Issue by merihtes** [usnistgov/ACVP#1280]
The issue started on January 4th, 2022 at around 5:30PM Eastern Time.

Production Server Error:

1.

acvp-cli: error: unexpected status code 400 != 200: [
                   {
                     "acvVersion": "1.0"
                   },
                   {
                     "error": "Validation error(s) on JSON payload.",
                     "context": [
                       "Unable to map kdf-components-tls-1.0 - index 18 to an internal algorithm id."
                     ]
                   }
                 ]

2.

"error": "Validation error(s) on JSON payload.",
                     "context": [
                       "Unable to map ACVP-AES-XTS-1.0 - index 1 to an internal algorithm id.",
                       "Unable to map SHA3-256-1.0 - index 14 to an internal algorithm id.",
                       "Unable to map SHA3-512-1.0 - index 21 to an internal algorithm id.",
                       "Unable to map SHA3-224-1.0 - index 25 to an internal algorithm id.",
                       "Unable to map SHA3-384-1.0 - index 26 to an internal algorithm id.",
                       "Unable to map kdf-components-tls-1.0 - index 50 to an internal algorithm id."

Demo Server Error:

1.
                   {
                     "acvVersion": "1.0"
                   },
                   {
                     "error": "Validation error(s) on JSON payload.",
                     "context": [
                       "Unable to map kdf-components-tls-1.0 - index 5 to an internal algorithm id."
                     ]
                   }
                 ]

2.

"error": "Validation error(s) on JSON payload.",
                     "context": [
                       "Unable to map ACVP-AES-XTS-1.0 - index 1 to an internal algorithm id.",
                       "Unable to map SHA3-256-1.0 - index 14 to an internal algorithm id.",
                       "Unable to map SHA3-512-1.0 - index 21 to an internal algorithm id.",
                       "Unable to map SHA3-224-1.0 - index 25 to an internal algorithm id.",
                       "Unable to map SHA3-384-1.0 - index 26 to an internal algorithm id.",
                       "Unable to map kdf-components-tls-1.0 - index 50 to an internal algorithm id."

**Comment by livebe01** [comment]
Hi @merihtes, this is due to the Jan 3, 2022 ACVTS algorithm transition. This transition was announced at ICMC and via a 9/10/21 email to the acvts-prod-users and acvts-demo-users lists. The contents of the email is pasted below.

```
Hi all,
 
At ICMC this past week I announced a series of algorithm testing transitions for the CAVP. Here is a recap of that information.
 
SHA-3 revision “1.0” will be deprecated in favor of SHA-3 revision “2.0”. This is a strict upgrade in testing functionality. The new testing revision “2.0” is capable of supporting all capabilities that the “1.0” revision could handle, and more. This turns the registration for SHA-3 into something more similar to SHA-1 and SHA-2. Specification updates are in progress and will be completed shortly.
AES-XTS revision “1.0” will be deprecated in favor of AES-XTS revision “2.0”. This is also a strict upgrade in testing functionality. CAVS testing and revision “1.0” do not utilize the concept of a “data unit” introduced in the AES-XTS standard. The new revision accounts for the “data unit” and introduces testing where the payload length does not necessarily match the data unit length. This is described in the updated specification available here: https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html#section-7.3-15.
Kdf-component TLS revision “1.0” will be deprecated in favor of TLSv1.2 KDF revision “RFC 7627”. A recent NIST publication, SP 800-52r2, introduces the requirement that TLS server implementations MUST use the extended master secret in Section 3.4.1. The new ACVTS test revision has been updated to include the computation of the extended master secret during the KDF routine. The only versions of TLS that should be supported are TLSv1.2 and TLSv1.3. Because of this the old test is being removed as all the capabilities have been superseded. Specification updates are in progress and will be completed shortly.
 
All three of these new test revisions are available now on the Demo server and Prod server.
 
The date for deprecation of the old revisions is January 3rd, 2022. On this date, the old revisions will be disabled on both the Demo and Prod servers. This means that new registrations that include these algorithms will not be allowed. As well, Certify requests that include these algorithms will not be allowed. The CAVP will not mark these tests as historical on existing validations.
 
If you have any questions or concerns, please let me know as soon as possible.
 
Thanks,
Chris Celi
Acting CAVP Program Manager
```

**Comment by merihtes** [comment]
Hi @celic, 

Thank you for the information.

If I understand correctly, does this also mean that test-sessions where production responses have been processed before Jan 3rd will fail during certification request?

For instance, if there is a project with existing test-session on production and the testing has completed, will the submission for certificate request fail/reject or will only new registrations that include the deprecated algorithms not be allowed? 

Thank you,
Merih Tesfatsion

**Comment by celic** [comment]
You may try to certify existing test sessions. Please send me an email with the requestID after submitting the certify. Christopher.celi at NIST.gov

**Comment by powersmc** [comment]
Just to clarify - it sure seems like you're saying that we can no longer test the TLS 1.0 and 1.1 KDFs at all.  Is that correct @celic?  That doesn't seem consistent with the FIPS 140-2 or FIPS 140-3 standards, which both still list the TLS 1.0 and 1.1 KDFs as Approved algorithms.

See FIPS 140-2 IG G.20, FIPS 140-3 IG 2.4.B, and SP 800-135r1 for references for that.

It seems like SP 800-52r2 even still allows TLS 1.0/1.1, stating "When interoperability with non-government
systems is required, TLS 1.1 and TLS 1.0 may be supported" // "TLS versions 1.1 and 1.0 are approved only when they are
required for interoperability with non-government systems and are configured according to these guidelines"

I guess it was our original understanding that this was just an ACVP protocol update, and not an actual deprecation of the TLS 1.0/1.1 KDFs entirely.

**Comment by celic** [comment]
The intention was for full deprecation to match SP800-52. The idea that any
new TLS server would need to use the updated testing. There still appears
to be purpose for the old testing for TLS clients though.

This may need to start from the CMVP rather than the CAVP to look at those
distinctions and update guidance for the new revision of SP 800-52.

Stay tuned...

**Comment by celic** [comment]
We have reenabled the TLS testing.
