### ISSUE TITLE
RSA SignaturePrimitive (Component) Capabilities

### ISSUE THREAD

**Issue by avaraacumen** [usnistgov/ACVP#1281]
This request pertains to specification of the maximum message length supported for the RSA SignaturePrimitive mode. The ACVP server randomly generates messages that range between 0 to n-1 (n=2048 bits/256 bytes), there is not a provision for specifying a maximum message length at present. 

Per Section 7.8. RSA SignaturePrimitive Mode Capabilities in the ACVP specification:
“In this mode, the only tested capability is the correct exponentiation of 's = msg^d mod n', where 'msg' is a message between '0' and 'n - 1', 'd' is the private exponent and 'n' is the modulus, all supplied by the testing ACVP server.”

This is posing to be an issue for a module that does not support messages greater than 245 bytes in length. We wanted to request and check if a modification could be made to the SignaturePrimitive Mode in order to be able to specify a range of supported message lengths /a maximum message length.

**Comment by livebe01** [comment]
Hi @avaraacumen, sure, this is something we should be able to do. 

Our team is down a developer at present, but we should be able to pick this up shortly.

**Comment by avaraacumen** [comment]
@livebe01 Thank you for your prompt response! As of this morning, the vendor in question has confirmed that they were able to work around this issue so there isn't an urgency here.

**Comment by livebe01** [comment]
Great! I'll close out this ticket then. But if there is a future need, this should be easy enough to do.
