### ISSUE TITLE
 Unable to map - - index 31 to an internal algorithm id

### ISSUE THREAD

**Issue by hvinnakota** [usnistgov/ACVP#1282]
-= Generate =-
Configuring demo server

***Generating vectors***
Loading registration data from evertz_reg.json
Requesting vectors from server...

An error occurred

The server returned an error: 400 (Bad Request)
Error Message: Validation error(s) on JSON payload.

Error Details:
Unable to map - - index 31 to an internal algorithm id.
hat issue should be opened at https://github.com/usnistgov/ACVP-Server/issues/new?template=acvp-bug-template.md

**Comment by celic** [comment]
Can you provide the content of `evertz_reg.json`?

**Comment by hvinnakota** [comment]
It was opened by mistake and I'm closing it.
