### ISSUE TITLE
Unable to submit vector test response for verification

### ISSUE THREAD

**Issue by akpanj** [usnistgov/ACVP#1283]
When I submit the vector test for verification I get the error response as 

[{"acvVersion":"1.0"},{"error":"The provided JWT expired at 2022-01-14 19:10:19Z and is no longer valid. The JWT claims may be refreshed through the renewal process described in the specification."}]
HttpStatus 401
m_req = {m_port=443 m_endpoint=Lhttps://demo.acvts.nist.gov/acvp/v1/testSessions/223153/vectorSets/837097/results ...}

When I logged in again and submitted the test vector results for verification I got 403 error with no error message

Please let me know how to resolve this issue. 

Thanks

Anil Panjwani

Note if this issue is in regards to a suggestion, issue, or question regarding NIST's **implementation** of the ACVP protocol, rather than the protocol itself, that issue should be opened at https://github.com/usnistgov/ACVP-Server/issues/new?template=acvp-bug-template.md

**Comment by Kritner** [comment]
> When I logged in again and submitted the test vector results for verification I got 403 error with no error message

Did you renew your JWT, or just log in again?  The JWT has to be refreshed by logging in passing in the expired JWT as described in the specification https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#name-request.  If you are just logging in again, you will not be issued a JWT that has claims to the test session, and will get a 403 returned.
