### ISSUE TITLE
Server rejects valid RSA signature primitive results smaller than modulus

### ISSUE THREAD

**Issue by tomofod** [usnistgov/ACVP#1294]
The verification process for the RSA signature primitive component test rejects valid signatures if the signature is smaller than the key modulus.

The capabilities section:
https://pages.nist.gov/ACVP/draft-celi-acvp-rsa.html#name-rsa-signatureprimitive-mode
indicates that the test is for `RSASP1` (a numeric operation) from RFC3447 and later states that it tests correct exponentiation (also a numeric operation).

The response section:
https://pages.nist.gov/ACVP/draft-celi-acvp-rsa.html#name-rsa-signature-primitive-tes
simply indicates that the response `signature` field contains the signature in hex. 

Depending on key and message value it is possible the resulting numeric signature/exponentiation value may be shorter than the key modulus by 8 bits or more. When such a value is encoded as hexadecimal it will be a byte shorter than the key.

Results in this form have been rejected by both the ACVP production server and demo server. Experiments showed that simply prepending a zero byte to the shorter signature value allowed a previously failing test to pass.

I would say that either the server verification behavior is incorrect and it should accept/handle results shorter than the modulus, or the test specification needs to be clarified.

**Comment by tomofod** [comment]
I have suggested a tiny change to the documentation to clarify:
https://github.com/usnistgov/ACVP/pull/1293

**Comment by livebe01** [comment]
Thanks @tomofod. Appreciate you adding the note about padding to the spec. I did approve the merge request, but it looks like the build process we use to build and publish updates to the specs is hiccuping. I'll look into resolving that issue and getting your change pushed out.
