### ISSUE TITLE
SHA Test Vector Response for SHA MCT - question about resultsArray

### ISSUE THREAD

**Issue by rcordeau** [usnistgov/ACVP#1295]
**Protocol Section**
Is your question regarding a specific section of the protocol?  You can link it here.
https://pages.nist.gov/ACVP/draft-celi-acvp-sha.html#name-test-vector-responses

**Protocol Question**
In the resultsArray of the SHA2 Test Vector Response for MCT, it says the following

resultsArray | Array of JSON objects that represent each iteration of an MCT. **Each iteration will contain the msg and md** | array of objects containing the md

It seems to be at odds with the example and the description of the array. In the example, the resultsArray of the MCT only contains the md for each iteration, but the description says that each iteration has to contain the msg and the md in the results array. Which one is correct?

**Comment by Kritner** [comment]
Hey @rcordeau this seems to just be a specification error.  At one point I believe we did return both, just must have been missed with one of the testing revisions.  You (or anyone for that matter) can feel free to put in a PR correcting the wording around "msg", as it should not be included in the results array.

**Comment by rcordeau** [comment]
Cool. Thank you.

**Comment by Kritner** [comment]
This still needs a specification update, so I'm reopening until that pr is completed
