### ISSUE TITLE
Symmetric Unique Numeric Test Id Scope

### ISSUE THREAD

**Issue by DBugger32** [usnistgov/ACVP#13]
In Section 3.2, tcId is defined as "Unique numeric identifier for the test case".  Is this id unique within the context of the Test Group or all the Test Cases within the Test Vector?

**Comment by jfigus** [comment]
Unique among the entire vector set.  I'll update the spec to clarify this.

**Comment by jfigus** [comment]
fixed in 121b2c2faf5553f2a03b328f683260fc40105220
