### ISSUE TITLE
Cannot login ACVP server, "Forbidden: Access is denied"

### ISSUE THREAD

**Issue by NorthHill-16** [usnistgov/ACVP#1301]
Hi, I have exact same problem with issue 968, but I still failed with Docker solution.

1. This problem never happened before, just recently about 1 month ago, I cannot login ACVP server through libacvp
2. Environment OS is Ubuntu 20.04
3. Time is sync through NTP
4. Certificates and TOTP are all correct, format all ok.
5. Docker does not work, it is exactly same error log with non-docker
6. I pull the latest code from libacvp, not work, I download old libacvp code, not work.
7. I am using mozzila_trust_anchors.pem

May I request for a online certificate verification? This certificate never reject before, but just reject at sometime in January, 2022.

Following is the --verbose error log, 

root@33eb84a3f01c:~/libacvp# ./app/acvp_app --get /acvp/v1/algorithms --verbose

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  certs/Fortinet_Marc_Boire_Demo.cer
    ACV_KEY_FILE:   certs/privatekey.key

***ACVP [STATUS][acvp_login:2335]--> Logging in...
***ACVP [INFO][acvp_http_user_agent_handler:477]--> HTTP User-Agent: libacvp/1.0;Linux;5.4.0-96-generic;x86_64;Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz;GCC/7.5.0

***ACVP [INFO][log_network_status:1457]--> POST Login...
	Status: 403
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp: Recieved

***ACVP [ERR][log_network_status:1484]--> 403 error received from server. Message:
***ACVP [ERR][log_network_status:1485]--> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>403 - Forbidden: Access is denied.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>403 - Forbidden: Access is denied.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>

***ACVP [STATUS][acvp_login:2347]--> Login Send Failed
***ACVP [ERR][acvp_run:2977]--> Failed to login with ACVP server

**Comment by Kritner** [comment]
That CA filename is pretty suspect to me.  The client (I believe) needs to take in our CA file in order to verify the certificate chain as it is laid out in the certificate generated for you for use against the demo server.  The `mozzila_trust_anchors`, based on the name alone, is likely not the correct one to be providing to libacvp at runtime.

**Comment by jarnold01** [comment]
Hey @NorthHill-16, I'll reach out to you via nfiles about this and work with you directly on it.
