### ISSUE TITLE
When is dkmNonceTypes required?

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP#1302]
**Protocol Section**
https://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56ar2/ecc/sections/05-capabilities.adoc#kas-ecc-kdfnokc

**Protocol Question**
Table 6 in the page linked above contains the `dkmNonceTypes`, required for the staticUnified scheme. The text directly above the table says the following:
```
Contains properties REQUIRED for "kdfNoKc" registration.
```

In other words, according to the specification,  `dkmNonceTypes` is required for the registration of Static Unified *without* key confirmation (KC).

However, looking at the following certificate: https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=C&number=2204, you can see the following text in the `KAS-ECC` Static Unified entries:
```
Derived Keying Material Nonce Types: Random nonce
```
Presumably, this refers to the `dkmNonceTypes` field mentioned above. Yet, this Static Unified entry has the `KDF with Key Confirmation` option. This seems inconsistent with the specification mentioned above. When is `dkmNonceTypes` required?

Additionally, Table 7 in the aforementioned page also seems to contain some copy-paste errors:
`The kdf options for "kdfNoKc"` -> `The kdf options for "kdfKc"`
`The kc options for "kdfNoKc"` -> `The kc options for "kdfKc"`
`The parameterSet options for "kdfNoKc"` -> `The parameterSet options for "kdfKc"`

**Comment by jvdsn** [comment]
Note: this question also applies to FFC, specifically section
https://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56ar2/ffc/sections/05-capabilities.adoc#supported-kas-ffc-mac-options

and the same certificate with the following text in the `KAS-FFC` dhStatic entries:
```
Derived Keying Material Nonce Types: Random nonce
```

**Comment by livebe01** [comment]
@jvdsn Apologies. 'dkmNonceTypes' is relevant to Static Unified for both kdfNoKc and kdfKc. I'm updating both specs to reflect this. Also fixing the Table 7 issues. Thanks for pointing these out!
