### ISSUE TITLE
TLS 1.3 Sample responses are incorrect, or the specification is ambigous

### ISSUE THREAD

**Issue by blackbird1999** [usnistgov/ACVP#1309]
https://pages.nist.gov/ACVP/draft-hammett-acvp-kdf-tls-v1.3.html#name-responses

Typically, the context value used to compute the values for clientApplicationTrafficSecret, serverApplicationTrafficSecret, exporterMasterSecret, and resumptionMasterSecret is the hash of *all* the messages processed so far. For clientApplicationTrafficSecret, serverApplicationTrafficSecret, exporterMasterSecret this would be ClientHello || ServerHello || server finished. For resumptionMasterSecret it would be ClientHello || ServerHello || server finished || client finished.

After much trial and error, I've found that the responses in the TLS 1.3 specification use only the first message and the last message listed (**ClientHello || server finished** instead of **ClientHello || ServerHello || server finished**). 

The ... in the RFC means to include all items between the start and end. The same ... is used in the ACVP document and should mean the same thing. If that is not the case, the specification should be clear what is meant and specify exactly what needs to be hashed to obtain the context.

**Comment by livebe01** [comment]
Hi @blackbird1999, it looks like the examples in the spec are from before we made [this](https://github.com/usnistgov/ACVP-Server/issues/151) change. I'll update the spec to include current examples.

For future reference/help w/ future troubleshooting, you might also check out [this](https://github.com/usnistgov/ACVP-Server/tree/master/gen-val/json-files) part of our ACVP-Server repository. We _try_ to keep up-to-date example files here for each of the algorithms we support.

Cheers!

**Comment by blackbird1999** [comment]
Hi @livebe01,

Thanks for updating the spec and for pointing me to the example file repo. I had no idea the examples existed as they don't seem to be referenced anywhere. Maybe adding a prominent section to the all the ACVP pages pointing people at it would be good. I had actually gone through setting up an ACVP demo account in an attempt to get sample data! As a cryptographic module developer this is extremely helpful information so anything that can be done to make it easier to find would be worthwhile. You made my month by pointing this out to me.

Thanks!!!

**Comment by livebe01** [comment]
Sure, definitely! I was just thinking that too... about linking to the sample data. We've always had this in an internal repository, but about a month ago we open sourced the "gen/vals" portion of our code and it now lives [here](https://github.com/usnistgov/ACVP-Server). If you dig deep enough into it, you can see exactly how we're generating and validating the vector sets. A bit too much information for most folks, but it's there. We're also in the process of redoing a lot of our documentation - the CAVP FAQ, CAVP Management Manual, and our https://csrc.nist.gov pages. We'll take a look and get the examples linked in!

**Comment by upsampled** [comment]
@livebe01 prior to the above commit my code was passing both the given test vector and the CAVP/ACVP tests (several of them). After this commit my code fails for all outputs that use the Master Secret (everything before that is fine). Has just the documentation been updated or have you changed how you are calculating the Master Secret and/or the use of the Server/Client Finish Random Bytes?


New Vector Output
```
        Master Secret: c5eb2b6b4e122a4c1b808165b39e00bd14a02c4ec32c09dfc597c282ea464eba
        Transcript Hash: 4a2bebd40f13bd6ab617e9b6ac690f907d6596463cfc45768778ced2d304d28b
         TestResult:{
            "tcId": 0,
            "clientEarlyTrafficSecret": "6C4A2365493D1AF0F654D59A181EDD2510205F6AE3F22B6EE765B8208C99C66C",
            "earlyExporterMasterSecret": "3C7204D21F2C10CD744915221CD46B8CF914E5E3124C87A822959C4EB58F13B9",
            "clientHandshakeTrafficSecret": "C017D71DB97422E10BF950C1B530AB754A11D4FCF562DDBB47EE6DBAAD72CBA3",
            "serverHandshakeTrafficSecret": "42D17CF61E98CA182AF677E13D40EA513627D950156BC8D80E749AB789930DE7",
            "clientApplicationTrafficSecret": "F0A498E36DF4E85F36BB93AAB65ECF81DDE1BD3DC13B7AA6809296BFFEAF3B4B", //no match
            "serverApplicationTrafficSecret": "48F71B01FC2B6392133BEFB42B005BB7549866C21D0C7B68EE0DAFAF042152F3",//no match
            "exporterMasterSecret": "BD988D051C2A1A8A0712D7290085ED4EDFF1F49554ED1B4CF937730D5627526A",//no match
            "resumptionMasterSecret": "0CD47508010C500345741F26E7CC3E41F2DF7C7AACD81AC63E9ED425DA04715C"//no match
        }
```

Old Vector Output (all match)
```
        Master Secret: c6dfae35ecdac62f4a7b5f3460e06ec40019c7e4893add9dc3e7a6e430809ba2
        Transcript Hash: 7934fe6dca41d796ad0020a327620ffe920f9e817ce96f19798be0f1a22d463b
         TestResult:{
            "tcId": 0,
            "clientEarlyTrafficSecret": "889A0D6D2FEE8A4354FC0B46E1D29BD56425D5BF4C392B35611C8396F79A3155",
            "earlyExporterMasterSecret": "FB91D4B12909086664C55DDAC27AE05ABE5C6F1A75608CA684D5A4C3060CDC12",
            "clientHandshakeTrafficSecret": "C029A02F8BA8EA6B1E6C288060A26865CFFA6E9AC5034DB5EC6AB0813E90A3BD",
            "serverHandshakeTrafficSecret": "EE099247305B84196773FADCAA3A9953655FD127921FA4B392FDC3A891F3F28F",
            "clientApplicationTrafficSecret": "FB2CB3F715EC90A396A2241B561F89462E486DCCE294ABA7356B23A7BE6D1199",
            "serverApplicationTrafficSecret": "8FE3438CAA0BFD48AC0D7022F618DA971491C3060567256B342E23D3CA3454E6",
            "exporterMasterSecret": "0349DD92F3B5D85238E46526923F97FB1529CA8CD33BB37A1658E7003F9B272D",
            "resumptionMasterSecret": "890B83EA14D193DF236F904B8190144A7F1025F8C7CEA8BB099664F261356019"
        }
```

**Comment by livebe01** [comment]
Hi @upsampled. Sorry, I received this message in my email, but can’t seem to find it on GitHub. Your question seems to be related to ACVP issue # 1309, but it’s not clear which commit you’re referring to. Can you please clarify?

Thanks,

Ben



On Aug 11, 2023, at 12:56 PM, upsampled ***@***.***> wrote:



@livebe01<https://github.com/livebe01> prior to the above commit my code was passing both the given test vector and the CAVP/ACVP tests (several of them). After this commit my code fails for all outputs that use the Master Secret (everything before that is fine). Has just the documentation been updated or have you changed how you are calculating the Master Secret and/or the use of the Server/Client Finish Random Bytes?

New Vector Output

        Master Secret: c5eb2b6b4e122a4c1b808165b39e00bd14a02c4ec32c09dfc597c282ea464eba
        Transcript Hash: 4a2bebd40f13bd6ab617e9b6ac690f907d6596463cfc45768778ced2d304d28b
         TestResult:{
            "tcId": 0,
            "clientEarlyTrafficSecret": "6C4A2365493D1AF0F654D59A181EDD2510205F6AE3F22B6EE765B8208C99C66C",
            "earlyExporterMasterSecret": "3C7204D21F2C10CD744915221CD46B8CF914E5E3124C87A822959C4EB58F13B9",
            "clientHandshakeTrafficSecret": "C017D71DB97422E10BF950C1B530AB754A11D4FCF562DDBB47EE6DBAAD72CBA3",
            "serverHandshakeTrafficSecret": "42D17CF61E98CA182AF677E13D40EA513627D950156BC8D80E749AB789930DE7",
            "clientApplicationTrafficSecret": "F0A498E36DF4E85F36BB93AAB65ECF81DDE1BD3DC13B7AA6809296BFFEAF3B4B", //no match
            "serverApplicationTrafficSecret": "48F71B01FC2B6392133BEFB42B005BB7549866C21D0C7B68EE0DAFAF042152F3",//no match
            "exporterMasterSecret": "BD988D051C2A1A8A0712D7290085ED4EDFF1F49554ED1B4CF937730D5627526A",//no match
            "resumptionMasterSecret": "0CD47508010C500345741F26E7CC3E41F2DF7C7AACD81AC63E9ED425DA04715C"//no match
        }


Old Vector Output (all match)

        Master Secret: c6dfae35ecdac62f4a7b5f3460e06ec40019c7e4893add9dc3e7a6e430809ba2
        Transcript Hash: 7934fe6dca41d796ad0020a327620ffe920f9e817ce96f19798be0f1a22d463b
         TestResult:{
            "tcId": 0,
            "clientEarlyTrafficSecret": "889A0D6D2FEE8A4354FC0B46E1D29BD56425D5BF4C392B35611C8396F79A3155",
            "earlyExporterMasterSecret": "FB91D4B12909086664C55DDAC27AE05ABE5C6F1A75608CA684D5A4C3060CDC12",
            "clientHandshakeTrafficSecret": "C029A02F8BA8EA6B1E6C288060A26865CFFA6E9AC5034DB5EC6AB0813E90A3BD",
            "serverHandshakeTrafficSecret": "EE099247305B84196773FADCAA3A9953655FD127921FA4B392FDC3A891F3F28F",
            "clientApplicationTrafficSecret": "FB2CB3F715EC90A396A2241B561F89462E486DCCE294ABA7356B23A7BE6D1199",
            "serverApplicationTrafficSecret": "8FE3438CAA0BFD48AC0D7022F618DA971491C3060567256B342E23D3CA3454E6",
            "exporterMasterSecret": "0349DD92F3B5D85238E46526923F97FB1529CA8CD33BB37A1658E7003F9B272D",
            "resumptionMasterSecret": "890B83EA14D193DF236F904B8190144A7F1025F8C7CEA8BB099664F261356019"
        }

**Comment by livebe01** [comment]
Sounds good. Thanks!

Ben



On Aug 17, 2023, at 10:07 AM, upsampled ***@***.***> wrote:



@livebe01<https://github.com/livebe01> I deleted the comment because I found that Github issue which explains the KDF algorithm change.
