### ISSUE TITLE
Verbose Registration for SHA and SHA3 Specs

### ISSUE THREAD

**Issue by celic** [usnistgov/ACVP#131]
Right now the spec says that you need to submit a new registration for each digest size of a hash function you want to test. Seeing as for the 4 hash functions (SHA1/2/3 and SHAKE) there are a total of 13 different possibilities, this could be simplified. 

The idea is to turn this...
```
{
  "algorithm": "SHA3-256",
  "inBit": "yes",
  "inEmpty": "yes"
}
```
into
```
{
  "algorithm": "SHA3",
  "functions": [
    {
      "type": "sha3",
      "digestSizes": 256, 512
    }
  ]
  "inBit": "yes",
  "inEmpty": "yes"
}
```
so that multiple digest sizes (and modes) can be specified. Examples will be updated in the spec.

**Comment by bfussell** [comment]
Are you suggesting an optional way to register or changing the way we register ?

**Comment by celic** [comment]
This could change the way we register. Along a similar line, I think the various modes of AES right now require separate registrations for each mode. @Kritner  might be able to verify that better. These changes could be made wider to help reduce the verbosity in that aspect.

**Comment by hbooth** [comment]
Certainly for the AES algorithms we are talking about 0.4+ but I also assume that we are talking about these changes for 0.4+ or do you want to see this change in 0.3?

**Comment by celic** [comment]
Ah yes. This should be 0.4+, sorry for any confusion.

**Comment by bfussell** [comment]
0.4+ or not we'll probably need to think about some guidelines about changing stuff that is already implemented and working, ie what justifies rewriting specs and code.

**Comment by atvassilev** [comment]
Agree, we need to find a mechanism  for choosing and prioritizing issues  to be included into releases. This applies even more to enhancements that alter existing implementations.

**Comment by celic** [comment]
It seems that the original solution is a bit redundant (and overly verbose) in some fields. This could be reduced to the following...
```
{
  "algorithm": "SHA2",
  "digestSizes": [
    "224",
    "256",
    "384"
  ],
  "inBit": false,
  "inEmpty": false
}
```
Note that the `digestSizes` are strings due to the truncated digest sizes `512/224` and `512/256`. 

If this is done do all 4 varieties of SHA (1/2/3/SHAKE), it would still reduce the back and forth for registering all 13 combinations of algorithm and digest size. It will also help reduce the number of extra fields. There are a number of fields that are necessary for SHAKE but not for SHA3 for example.

**Comment by bfussell** [comment]
Not sure how it was accomplished via CAVS, but it seems some OEs want to define the options at the digestSize level. How would you represent the capabilities described in 3603 ?

http://csrc.nist.gov/groups/STM/cavp/documents/shs/shaval.html

**Comment by celic** [comment]
It seems a bit silly that they validated SHA-512 as BYTE but SHA-512/224 and SHA-512/256 as BIT... But that's not the point.

CAVS right now lets you specify as many modes of SHA as you would like (separated into SHA1/2 and SHA3/SHAKE) all with the same properties like `inBit` and `inEmpty`. All modes registered at once share those properties. Our back-end was designed the same way as CAVS does it. You can specify many modes of SHA (again separated into SHA1/2 and SHA3/SHAKE) and the properties defined apply to that entire registration. 

If someone wanted to register the capabilities described in 3603, they would need two separate registrations (which is true for CAVS as well.) This could be something we look into for the future, but it would probably end up leading to a lot of redundant JSON if not handled properly.

**Comment by bfussell** [comment]
For the purposes of our demo I think its perfectly reasonable for you to assume all modes use the same properties since that is exactly how our module will register our SHA.

But longer term needing two separate registrations is something we'd want to avoid since 3603 is not an isolated case.

**Comment by celic** [comment]
Understood. The initial design concept was to mimic the functionality of CAVS. As we find cases like this where we could improve we should definitely note them to talk about post-demo.
