### ISSUE TITLE
Generating RSA KTS OAEP vectors with a NULL additional input 

### ISSUE THREAD

**Issue by rnunez83** [usnistgov/ACVP#1311]
I had a question about generating RSA KTS OAEP vectors with a NULL additional input.

In the capabilities section of the 56Br2 ACVP spec table 12 (https://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56br2/sections/05-capabilities.adoc#fixedinfopatcon)  it states:
"Note that for the purposes of testing against the ACVP system, both uPartyInfo and vPartyInfo are REQUIRED to be registered within the fixed info pattern".

I was wondering if an explanation could be provided as to why the module would be required to add support for fixed info pattern when SP800-56Br2 allows it to be NULL.

if you look at section 7.2.2.3 of https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Br2.pdf, it says for input 3. "A: additional input; a byte string (which may be the Null string)"

The spec provides the option for generating some vectors with a NULL associated data by defining "supportsNullAssociatedData" as TRUE. But this still generates some vectors with the required uPartyInfo and vPartyInfo mentioned above.

Can the test server be updated such that an option is provided where only NULL associated data was generated?

**Comment by livebe01** [comment]
I'd think there would be a way to accomplish what you're describing. I'm not sure why this doesn't seem to be the case. We'll get back to you on this.

**Comment by livebe01** [comment]
Hi @rnunez83, 

To test an IUT that only supports null associated data, include "supportsNullAssociatedData": true, but do not include an "associatedDataPattern" in your registration.

To test an IUT that supports both null and non-null associated data, include both "supportsNullAssociatedData": true and an "associatedDataPattern" in your registration.

The note that you referenced regarding "both uPartyInfo and vPartyInfo are REQUIRED to be registered within the fixed info pattern" is from [Section 7.7.1.3 FixedInfoPatternConstruction](https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ifc.html#name-fixedinfopatternconstructio) and assumes a non-null associatedDataPattern.

**Comment by rnunez83** [comment]
> To test an IUT that only supports null associated data, include "supportsNullAssociatedData": true, but do not include an "associatedDataPattern" in your registration.

I tried this option by setting "supportsNullAssociatedData": true and not including "associatedDataPattern" in my registration but  I get the following error reported from the server:

ACVPProxy (11:05:12) () Error [lib/common/network_helper.c:acvp_net_op:124]: Server error response: [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "KTS-IFC-Sp800-56Br2: No Encoding type supplied."
    ]
  }
]

I just want to confirm that this option is possible.

**Comment by livebe01** [comment]
If you include an encoding type (see [https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ifc.html#name-supported-kts-method](https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ifc.html#name-supported-kts-method)), your registration should work. That said, it doesn't make sense for ACVTS to require an encoding type when "supportsNullAssociatedData": true and no "associatedDataPattern" is supplied. I'm in the process of fixing that and this will be fixed when the next release hits demo.

**Comment by livebe01** [comment]
The fix for this is now on Demo, v1.1.0.25.
