### ISSUE TITLE
How to cut/handle gxy when dhlength isn't multiple of 8 in IKEv1

### ISSUE THREAD

**Issue by FW-Fiona** [usnistgov/ACVP#1312]
https://pages.nist.gov/ACVP/draft-celi-acvp-kdf-ikev1.html
I got "dhLength" is 521, gxy "9E50F9E86DAF773F657F5F32BA4C84E707284843F422A74DFC6877D236020F86B115230C3BA57A680AED1AF2F0CE59CBB3C5755D80EFCCC1DD350DE79781AC807180". This gxy is 66 bytes (528 bits)
I tried shift right 7 bits, set the most significant 7 bits to 0, and module 2^521-1, none of them work.
how to handle this case?

Thanks a lot!

**Comment by livebe01** [comment]
Hi @FW-Fiona can you provide us with test session and vector set ids? Thanks

**Comment by livebe01** [comment]
I'm thinking that shifting right 7 bits should be the correct approach. When you're doing this, are you providing a 521-bit string to your implementation? or a 528-bit string?

**Comment by FW-Fiona** [comment]
This is a demo file but not created by me. "vsId": 839512, I don't have vectors.
tried shifting right, the answer doesn't match the result in demo expected file.
As openssl supports input as bytes only, 528 bits are inputed (after shifting, the most 7 significant bits are 0).

**Comment by FW-Fiona** [comment]
223523, maybe this is the session id.

**Comment by livebe01** [comment]
Hmmm, what you're doing sounds right. Your shifting right 7 bits, with the 7 most significant bits as 0 sounds correct, per https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#name-hex-to-bitstring-parsing. Looking at your prompt file, I see test groups with dhLength = 224, 521, and 2048. Are your answers coming out okay for the 224 and 2048 test groups?

**Comment by FW-Fiona** [comment]
225, 2048 works well with same functions.
For shifting right 7 bits, for example, tcid 11, gxy is 9E50F9E86DAF773F657F5F32BA4C84E707284843F422A74DFC6877D236020F86B115230C3BA57A680AED1AF2F0CE59CBB3C5755D80EFCCC1DD350DE79781AC807180. After shifting, it's 013CA1F3D0DB5EEE7ECAFEBE65749909CE0E509087E8454E9BF8D0EFA46C041F0D622A4618774AF4D015DA35E5E19CB397678AEABB01DF9983BA6A1BCF2F035900E3. The answer doesn't match the result in expected JSON.

**Comment by livebe01** [comment]
Ah, okay. Earlier in the ticket, you mentioned that, "As openssl supports input as bytes only, 528 bits are inputed (after shifting, the most 7 significant bits are 0)." If you're testing openssl and openssl only supports input as bytes, then by definition it cannot support a dhLength of 521 bits. Per the definition of IKEv1 from SP 800-135r1, an HMAC is used to calculate SKEYID. Providing a 521 bit vs 528 bit gxy will necessarily yield different results from the HMAC as HMAC is hash-based.

**Comment by FW-Fiona** [comment]
Thank you for this response. It's clear now.

**Comment by livebe01** [comment]
Welcome!
