### ISSUE TITLE
AES-XTS revision 1 Issue

### ISSUE THREAD

**Issue by cgprieto** [usnistgov/ACVP#1317]
I'm trying to register the following capabilities file for AES-XTS revision 1 in the Demo Server:

[
    {
        "acvVersion": "1.0"
    },
    {
        "isSample": true,
        "algorithms": [{
		"algorithm": "ACVP-AES-XTS",
		"revision": "1.0",
		"direction": ["encrypt","decrypt"],
		"keyLen": [128,192,256],
		"payloadLen": [{
                                "min": 0,
                                "max": 65536,
                                "increment": 8
		}],
                        "tweakMode": ["hex"]
	}]
}]

And I'm getting the following error:  "Unable to map ACVP-AES-XTS-1.0 - index 0 to an internal algorithm id."

Are there any issues in the demo server?

**Comment by Kritner** [comment]
https://github.com/usnistgov/ACVP/issues/1280#issuecomment-1005947372
