### ISSUE TITLE
Large Data Tests (LDT) for SHA-1, SHA-2: requirement on how to call/process the large messages.

### ISSUE THREAD

**Issue by locksmithone** [usnistgov/ACVP#1320]
**Protocol Section**
SHA-1 and SHA-2, Large Data Tests (LDT)

https://pages.nist.gov/ACVP/draft-celi-acvp-sha.html#name-large-data-tests-for-sha-1-

**Protocol Question**
Related to #1251.

In the pages section, the explanation for the "performLargeDataTest" option states:

> There are multiple ways hash functions can be implemented in an IUT. The most common are via a single Hash() call on the message or via a series of Init(), any number of Update(), Final() calls. As noted in [[LDT](https://pages.nist.gov/ACVP/draft-celi-acvp-sha.html#LDT)], the difference between these hashing techniques can have consequences in the cryptographic module. _**If both interfaces are offered and accessible for testing, the IUT MUST only utilize a single Update() call for the large message**_.

There seems to be a requirement for how the IUT SHS function must be invoked in the particular, optional case of the large data input, but it is not entirely clear. The question is: if the large data test option is selected, then the IUT *must* use a single call for the large message, **regardless** of what other interfaces it may implement to process SHS digests?

If that is the case, I suggest rewriting the statement so that it is unambiguous.

(Note that the original statement might be interpreted as "if the IUT _does not_ implement both interfaces, then the large message may be processed with multiple update() calls.")

MPortnoi

**Comment by jvdsn** [comment]
Perhaps the CAVP can clarify how the IUT should perform the LDT for each of the three relevant scenarios:
* The IUT only implements a single Hash() function which directly provides the hash output given a message input
* The IUT only implements the Init(), Update(), and Final() functions, where Final() provides the hash output
* The IUT implements all of the above functions

As it stands, it seems like the quote only explains what the IUT should do in the last case (even though it is also not entirely clear what is meant by "interface" here).

**Comment by celic** [comment]
That would be correct. Do not break up the message into multiple updates. It should either be one update, or one hash call.

**Comment by locksmithone** [comment]
May I suggest then to update the "pages" to make this information
unambiguous. For the Large Data Tests (LDT), the input message must be
processed in its entirety in one call.

MP

**Comment by livebe01** [comment]
Sure, will do.

**Comment by livebe01** [comment]
Oops, my bad @locksmithone. I didn't see your pull request until after I'd gone through and made the change separately. But I think the requirement should be clearer now.

**Comment by locksmithone** [comment]
It is clearer, thank you.
