### ISSUE TITLE
CMAC Message Lengths

### ISSUE THREAD

**Issue by mtdownz** [usnistgov/ACVP#1323]
Currently CMAC supports MSGLEN as a domain only which means it is requiring a Min and Max value. We have vendors whose implementation utilizes fixed message lengths only. Where some algorithms allow for a single MSGLEN CMAC currently does not. Is there a work around to request CMAC vectors using a single message length e.g. 32768 bits

    "error": "Validation error(s) on JSON payload.",
    "context": [
      "CMAC-AES-1.0: min must be less than max"

Thank you!

**Comment by livebe01** [comment]
Hi @mtdownz, sure, the registration for this would look like `"msgLen":[32768]`. See [here](https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#name-domain) and [here](https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#name-range).

**Comment by mtdownz** [comment]
Thank you!
