### ISSUE TITLE
Listing All Validations for a Given Set of ACVP Credentials

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#1324]
Is it possible to add to the public ACVP API, a way in which we can list all the validations that have been created for a given set of credentials (user)?

I'm thinking a GET on /validations that would return to me a list of this structure:
https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#section-12.15.1.1

**Comment by AlexThurston** [comment]
And maybe return that date when it was created as well?

**Comment by livebe01** [comment]
Sure, that seems like it would be a useful feature. But not something we'll be able to get to soon. If there is some data you need, we may be able to get that to you out of band. Just send Chris Celi an email.

**Comment by jbrock24** [comment]
Hi @AlexThurston - Unfortunately this is something that likely won't happen for a number of reasons, but at a base level the time investment on something that the usefulness is questionable is one of the big issues. According to NVLAP HB 150-17, the labs are required to keep all of this information within their own records. Thanks for the question!
