### ISSUE TITLE
Kerberos KDF

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#1327]
Has there been any thought to adding Kerberos KDF testing ?
Many of the linux distros utilize it and it supports FIPS compliant crypto for KDF generation.

Thanks !

**Comment by celic** [comment]
Do you have a specification or something that outlines it? I'm not familiar.

**Comment by bfussell** [comment]
RFC3961 has the KDF in section 5.1(exists in openssl 3.0), however there is a bunch of updated/deprecated and best practice RFCs since then.

https://datatracker.ietf.org/doc/search?name=kerberos&sort=&rfcs=on&activedrafts=on&by=group&group=

**Comment by jbrock24** [comment]
Hi @bfussell - Are you looking for an official NIST KDF Kerebos certification implementation, or are just looking for test vector set production and testing?

**Comment by bfussell** [comment]
Neither presently. At that time I was asking since OpenSSL 3.0 had a KDF in their FIPS Providr but it wasn't listed as FIPS approved.

**Comment by jbrock24** [comment]
OK, thanks! Just for the record, the certification would require a CMVP assessment to make sure the algo fits specs, and the test vector set gen/val would be a lack of resources to implement presently given the present need. Thanks for the question!
