### ISSUE TITLE
ECDSA siggen component: why specify/register the SHA functions?

### ISSUE THREAD

**Issue by locksmithone** [usnistgov/ACVP#1329]
The ACVP has the capability of testing the ECDSA siggen _component_, i.e., the signature generation when the digest of the message is pre-computed outside of the boundary of the algorithm. In such case, the only information the algorithm has is the actual length of the digest. However, for this testing, one needs to supply the hash algorithm types (e.g., SHA2-256, SHA2-512, etc.) and those types are also eventually listed in the algorithm certificate.

If the hash computation is performed outside of this algorithm component, why specify (and list in the certificate) the hash algorithm types?

MP

**Comment by livebe01** [comment]
In the case of the ECDSA sigGen component, the supplied hash algorithm types are used to determine the message lengths to test. E.g., a test group where "hashAlg": "SHA2-256" will have messages that are 256 bits in length. On the certificate, the hash algorithms listed denote the scenarios that were tested. E.g., if SHA2-256 is listed on the certificate for an ECDSA sigGen component, this indicates the scenario where a 256 bit digest was used in the signing was tested.

**Comment by locksmithone** [comment]
Yet, technically, from the point of view of the algorithm, it has no
knowledge of the provenance of the data passed in as a digest. For
instance, if the data is of 256 bits of length, it may be a SHA2-256
digest, it may be a SHA3-256 digest, it may be a SHA2-512/256 digest, it
might be not a digest at all.

I understand the goal of specifying the digest algorithms as a manner of
identifying the lengths (and the overall purpose of the component is indeed
to produce a signature from a digest). But, suppose that the ECDSA siggen
component is tested with SHA2-256 as configured. It will sign data composed
of 256 bits, and SHA2-256 bits will be listed in the certificate. Yet, with
this testing the component technically works properly for SHA2-256,
SHA2-512/256, SHA3-256, and truncated forms of approved digests, even if
they are not listed in the certificate. Perhaps it would be "purer" to
specify approved lengths only, and not relate them to SHA algorithms? The
module would not be able to control the originating digest algorithm, but
only trust the caller.

**Comment by livebe01** [comment]
Hi @locksmithone, what you say is definitely correct and valid. I think the answer for why we have it setup this way is that, after/or in conjunction with implementing ECDSA sigGen, this was an easy/simple way to implement the ECDSA sigGen component. Not the purest way, but good enough.
