### ISSUE TITLE
HMAC: keyLen domain range listed in the specification not consistent with ACVP server control

### ISSUE THREAD

**Issue by locksmithone** [usnistgov/ACVP#1330]
**Protocol Section**
HMAC key length (https://pages.nist.gov/ACVP/draft-fussell-acvp-mac.html)

**Protocol Question**
The specification for key length (keyLen) for HMAC algorithms mentions the range from 0 to 524288. However, if one attempts to register a domain with a range starting from zero, the ACVP demo server accuses error. 

For instance, the HMAC algorithms below were submitted for registration with ranges starting from 0. The error follows.

```Error: Server error response: [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "HMAC-SHA-1-1.0: Invalid KeyLen Range supplied: 0.  Values were not between 8 and 524288",
      "HMAC-SHA2-224-1.0: Invalid KeyLen Range supplied: 0.  Values were not between 8 and 524288",
      "HMAC-SHA2-256-1.0: Invalid KeyLen Range supplied: 0.  Values were not between 8 and 524288",
      "HMAC-SHA2-384-1.0: Invalid KeyLen Range supplied: 0.  Values were not between 8 and 524288",
      "HMAC-SHA2-512-1.0: Invalid KeyLen Range supplied: 0.  Values were not between 8 and 524288",
      "HMAC-SHA3-224-1.0: Invalid KeyLen Range supplied: 0.  Values were not between 8 and 524288",
      "HMAC-SHA3-256-1.0: Invalid KeyLen Range supplied: 0.  Values were not between 8 and 524288",
      "HMAC-SHA3-384-1.0: Invalid KeyLen Range supplied: 0.  Values were not between 8 and 524288",
      "HMAC-SHA3-512-1.0: Invalid KeyLen Range supplied: 0.  Values were not between 8 and 524288"
    ]
  }
]
```

The domain limitation in the server and the one listed in the specification are not consistent. (An HMAC key of length less than 112 bits will not do anyway, but nevertheless.)

**Comment by livebe01** [comment]
Thanks for mentioning this. The valid values for keyLen should be: "Min": 8, "Max": 524288, "Increment": 8. We'll fix this in the spec.
