### ISSUE TITLE
KAS-IFC-SSC: Z is provided alongside hashZ?

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1338]
Hello,

Quick question regarding the optional hash in KAS-IFC-SSC. It looks like in VAL tests, the Z value is provided alongside hashZ when a hash function is registered. In practice, is there any need for us to check our results against that Z value on top of just the hashZ? I am trying to determine the best way to handle this test data on the libacvp client side. In my mind, it makes sense to ignore the server-provided Z value in these cases and just check against the hashZ; I imagine there may be some IuTs that only provide the hashZ as output.

Another question - KAS1 VAL tests use both a "z" and "iutZ" (or hashZ and iutHashZ) value that are identical. Based on the spec, is it safe to assume the z/hashZ should be the values we parse here? I am thinking the "iut" variables should be used more in the case of KAS2.

Thanks,
Andrew

**Comment by Kritner** [comment]
The inclusion of `z` when `hashZ` is included was likely just oversight.

Regarding the second question, IIRC in some cases the party U and party V generate separate z values, which then get concatenated `uZ||vZ`, the `z` and `iutZ` could be different in such schemes, I think.  

The complexity of excluding specific properties that don't (necessarily) apply to all the different combinations of scheme, and party, as well as which properties to *then use* when running through validation, was likely not something I wanted to tackle at the time.  It does obviously lead to some confusion, but from the client's perspective, having the varying different properties available, depending on which role they were playing in KAS as well as which scheme was being used, coupled with all the other complexities that exist in kas...  I know we are including and exclusion *some* properties already as a function of scheme/role.  Removing them is possible, though some clients may be reliant on those properties existing at this point.

**Comment by abkarcher** [comment]
Thank you both @Kritner and @livebe01 for the detailed help as usual!

I absolutely understand the complexities involved in including/excluding specific properties; KAS-IFC seems particularly complex in this regard. I may try to set aside some time to help with specification clarity for this if I get a chance.

My questions have been answered, so closing!

Thanks again,
Andrew
