### ISSUE TITLE
Clarification for "SupportedLengths" for KDA-Twostep

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1339]
Hello,

The [specification for KDA-Twostep ](https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-kdf-twostep.html#name-two-step-kda-capabilities) indicates that a "domain" is expected for supportedLengths; the description says "Single range (of literal) expected. " I am not sure I follow what is being asked for.

Every example I can find suggests that a single integer value is what is expected for supportedLengths, but it is in array format. Can multiple supportedLengths be generated?

I tried comparing against the SP800-108 spec, but they indicate a regular domain value for those.

Thanks for your time!
Andrew

**Comment by livebe01** [comment]
Hi @abkarcher, that is confusing. The underlying type for supportedLengths is a domain.  I'm not sure what we were trying to say w/ that text. I'll update it to read, "Registered value(s) must support the L value provided"

**Comment by abkarcher** [comment]
Thank you!
