### ISSUE TITLE
XOF ParallelHash BlockSize is in bits in ACVP, but SP800-185 requires it to be bytes

### ISSUE THREAD

**Issue by blackbird1999** [usnistgov/ACVP#1344]
SP800-185 section 6.1 states: "B is the block size in bytes for parallel hashing. It may be any integer such that 0 < B < 
2^2040"

ACVP (https://pages.nist.gov/ACVP/draft-celi-acvp-xof.html) states: "blockSize | blockSize (in bits) to be used with ParallelHash" and lists {Min: 1, Max: 128, Increment: 1} as properties. 

I think that ACVP is actually using bytes and that the document just needs to be updated to state that BlockSize is in bytes.

**Comment by livebe01** [comment]
Thanks for mentioning this!
