### ISSUE TITLE
Spec is incorrect for TupleHash and ParallelHash

### ISSUE THREAD

**Issue by powersmc** [usnistgov/ACVP#1345]
**environment**
Demo (probably affects Prod as well though)

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
```
            {
                "algorithm": "TupleHash-256",
                "revision": "1.0",
                "xof": [
                    true,
                    false
                ]
                ,
                "hexCustomization": false,
                "outputLen": [
                    {
                        "min": 16,
                        "max": 65536,
                        "increment": 8
                    }
                    
                ]
                ,
                "msgLen": [
                    {
                        "min": 0,
                        "max": 65536,
                        "increment": 8
                    }
                    
                ]
                
            }
```

**Endpoint in which the error is experienced**
/testSessions POST

**Expected behavior**
Based on the spec here;
https://pages.nist.gov/ACVP/draft-celi-acvp-xof.html#appendix-A
https://pages.nist.gov/ACVP/draft-celi-acvp-xof.html#table-3

The server should accept the "camel case" algorithm names TupleHash-128, TupleHash-256, ParallelHash-128, ParallelHash-256.

It does not accept these names, however, and it seems to only accept TUPLEHASH-128, TUPLEHASH-256, PARALLELHASH-128, PARALLELHASH-256, which don't appear in the spec at all.

**Additional context**
No additional context

**Comment by livebe01** [comment]
Thanks for letting us know about this @powersmc

**Comment by livebe01** [comment]
We would like the casing for the two xofs to be `TupleHash` and `ParallelHash` to match SP 800-185, however, the server currently requires the algorithm names to be all caps. We would also like the casing to be `cSHAKE`, but the server currently requires `CSHAKE`. We will address this in an upcoming server release.
