### ISSUE TITLE
Can update requests create new entries?

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1351]
Hello,

The ACVP spec page has this statement in section 12.13.5.2 regarding updating dependencies:

```
A server implementation MAY create a new resource instead of updating the existing resource.
```

This raises many questions from our end:

Will the NIST server ever create a new resource instead of updating the requested one? 
If so, does the NIST server update all references on the back end to the new entry?
If all references do get updated, what happens to the old resource?

In our opinion, this statement in the protocol opens a very large can of worms; especially for labs trying to maintain a list of resources and validations in sync with the NIST server. In my personal opinion, I am not sure that this should be included in the specification; it would be preferable to have the update request rejected and be told to create a new resource.

Thanks,
Andrew

**Comment by celic** [comment]
The server does not create new entries for this update. It _could_ but doesn't. Everything associated with the dependency is also affected. So a change on a dependency would impact everything that relies on that dependency. We generally ask if a submitter realizes what will be impacted by a particular change, but understand that it's not something that's all that apparent or obtainable from the API. 

So, you're on the right track. The protocol is technically allowing something we don't really want and don't currently support, so why does it need to exist...

**Comment by abkarcher** [comment]
Hi @celic,

Thanks as usual for the detailed answer 😄 That answers all of our questions. I will close the issue, but if someone wishes to re-open it for the sake of tracking the question of "should it be in the spec", that is fine too.

Thanks,
Andrew
