### ISSUE TITLE
RSA KeyGen response documentation incomplete for B.3.6

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP#1353]
Why does Table 1 at https://github.com/usnistgov/ACVP/blob/master/src/rsa/sections/07-keygen-responses.adoc not mention Appendix B.3.6 for xP1, xP2, xQ1, and xQ2? When I request a testvector sample, these values are included in the expected output.

**Comment by jbrock24** [comment]
Resolved, thanks for the issue!
