### ISSUE TITLE
Vague error reason to failed SafePrime vector set responses

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#1356]
We have a test session (`13999`)with a vector set (`152295`) for SafePrimes on *production*.  Results have been pushed up that have been flagged as failing for a few of the test cases; however, the error provide doesn't give much information as to why:

```json
{
        "tcId": 1,
        "result": "failed",
        "reason": "Validation failed: Fail"
}
```

Would it be possible to improve the error output to give more details as to the nature of problem?

**Comment by livebe01** [comment]
Sure, we'll take a look. I'm guessing that there's a more descriptive reason that we can provide for this.

**Comment by jbrock24** [comment]
Hi @AlexThurston. Can you rerun this same test and let me know the results as well as the sessions ID. Thanks!

**Comment by jbrock24** [comment]
If we can run this again, I can test it and provide feedback on a solution.
