### ISSUE TITLE
IKEv2 KDF - Varying DKM Lengths

### ISSUE THREAD

**Issue by arthurTheAardvark** [usnistgov/ACVP#1357]
**Protocol Section**
https://pages.nist.gov/ACVP/draft-celi-acvp-kdf-ikev2.html#name-test-groups

**Protocol Question**
This document https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/components/askdfvs.pdf and this commit https://github.com/usnistgov/ACVP/pull/308/files indicate that the IKE_SA and CHILD_SA DKM lengths use to be 2 different fields (dkmLen, dkmChildLen). The latest protocol only allows 1 length field (derivedKeyingMaterialLength).
Our IKEv2 KDF outputs length X for IKE_SA DKMs and length Y for CHILD_SAs. Is there any way to request vectors for this type of implementation?

**Comment by GlennUL** [comment]
@celic Can you provide any insight into this? Thanks!

**Comment by celic** [comment]
@ben might be able to provide an update. I'm out on travel.

**Comment by livebe01** [comment]
Hi @GlennUL, @arthurTheAardvark, what are the IKE_SA DKM and CHILD_SA lengths your implementation supports?

**Comment by arthurTheAardvark** [comment]
Hi @livebe01, when using "aes256gcm16-prfsha384-ecp384" the IKE_SA DKM_LEN is 216 bytes. The CHILD_SA DKM_LEN is 72 bytes.

**Comment by livebe01** [comment]
Thanks @arthurTheAardvark. We're looking at this and will get you an answer.

**Comment by livebe01** [comment]
Hi @arthurTheAardvark, I took a look at the askdfvs.pdf document that you referenced as well as the last available version of CAVS. It appears that there used to be an option for CHILD_SA DKM length in CAVS, but it also appears to have been removed from CAVS at some point with no note as to why. That said, this is something that is simple to add to the IKEv2 testing. It won't make it into the next release (due out later this week if all goes well), but we'll get this out as part of the following one.

**Comment by arthurTheAardvark** [comment]
@livebe01 Thank you very much for looking into it. Do you have an estimate of when the the following release will be?

**Comment by livebe01** [comment]
I’d like to have it out in the next 30 days, but given scheduled leave, ICMC coming up, and the number of lab audits we have lined up, it may take longer.

Ben

**Comment by livebe01** [comment]
This change is on Demo in release [v1.1.0.26](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.26)

**Comment by livebe01** [comment]
This change is on Prod in release [v1.1.0.26](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.26)
