### ISSUE TITLE
SHA3 for hash conditioning?

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1358]
Hello,

It appears that SHA3 is not on the list of supported algorithms for hash_DF conditioning component:
https://pages.nist.gov/ACVP/draft-celi-acvp-conditioning-components.html#name-supported-hash-functions-fo
Are there plans to add support for SHA3? How should sha3 conditioning components be managed/tested in the mean time?

Thanks,
Andrew

**Comment by livebe01** [comment]
Hi @abkarcher, letting you know that we're looking into this and will get you an answer shortly.

**Comment by livebe01** [comment]
ps I assume you have an implementation you'd like to test?

**Comment by abkarcher** [comment]
Hi @livebe01,

Our understanding came to be that regular SHA3 testing sufficed for our case. It would still be good to get more clarification though; for example, it looks like many recent validations for jitter entropy libraries just test SHA-3. I'm pretty much in the dark about this stuff. 

@smuellerDD, do you have any thoughts here? (Thanks!)

Thanks,
Andrew

**Comment by celic** [comment]
Jitter Entropy uses SHA3 as a conditioning component as just the normal function. The Hash_DF operation refers to something specific with SP 800-90A. It's an option for a conditioning component but not what Jitter Entropy uses.

**Comment by livebe01** [comment]
And to follow up on the original question - the reason we don't have SHA3 support for hash_DF is because some ambiguities came up in implementing it. This goes back years. 90A Table 2 lays out the constants that should be used for SHA1 and SHA2, but not SHA3. We've been unable to get answers as to what values we should use for SHA3 and hence the lack of support :).

**Comment by abkarcher** [comment]
Hi all,

Thank you very much for the clarification! That all makes sense. Closing - 

Andrew
