### ISSUE TITLE
RSA Examples have odd public exponent e

### ISSUE THREAD

**Issue by celic** [usnistgov/ACVP#136]
This may have just been a typo while writing the document, but the public exponent for the RSA examples in the specification is hex "100001" which is 1048577 in decimal. I think the intended value was "10001" which corresponds to the more common e value of 65537. I wanted to make sure "10001" was the intended value.

**Comment by celic** [comment]
This is irrelevant as they are examples.

**Comment by atvassilev** [comment]
This is a typo, it should be '10001'. I will fix it.

**Comment by celic** [comment]
Fixed with #137
