### ISSUE TITLE
KDA OneStep/TwoStep multi expansion groups

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP#1360]
**Protocol Section**
* https://github.com/usnistgov/ACVP/tree/master/src/kas/sp800-56c/onestep/sections
* https://github.com/usnistgov/ACVP/tree/master/src/kas/sp800-56c/twostep/sections

Questions:
* Does KDA OneStep support multi expansion groups? The [`07-responses.adoc` file](https://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56c/onestep/sections/07-responses.adoc) has `dkms` listed in Table 3, but [`05-capabilities.adoc`](https://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56c/onestep/sections/05-capabilities.adoc) does not list `performMultiExpansionTests`.
* Does KDA TwoStep support multi expansion groups? The [`07-responses.adoc` file](https://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56c/twostep/sections/07-responses.adoc) file does not have `dkms` listed in Table 3, but [`05-capabilities.adoc`](https://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56c/twostep/sections/05-capabilities.adoc) does list `performMultiExpansionTests`.

**Comment by jbrock24** [comment]
Hello @jvdsn!  Based on the code and the capabilities documentation, the 07-responses files appear to have been reversed. I swapped them back with #1366. Thanks for reporting this!
