### ISSUE TITLE
DEMO Server is down

### ISSUE THREAD

**Issue by ehanson12** [usnistgov/ACVP#1361]
The DEMO server is down. Below is the CISCO ACVP output... It has been down for 2-3 hours...

***ACVP [STATUS][acvp_login:2718]--> Logging in...
***ACVP [STATUS][acvp_login:2738]--> Login successful
***ACVP [STATUS][acvp_register:2119]--> Reading capabilities registration file...
***ACVP [STATUS][acvp_register:2141]--> Sending registration of capabilities...
***ACVP [STATUS][acvp_register:2150]--> Successfully sent registration and received list of vector set URLs
***ACVP [STATUS][acvp_register:2151]--> Test session URL: /acvp/v1/testSessions/281082
***ACVP [STATUS][acvp_run:3495]--> Beginning to download and process vector sets...
***ACVP [STATUS][acvp_retry_handler:2664]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2664]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2664]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2664]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2664]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2664]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2664]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...

**Comment by jarnold01** [comment]
Thanks for reporting this. After investigating the environment, it is not in a non-processing state, it is just under very heavy utilization since this afternoon and is still working through all of the existing submission requests.

**Comment by ehanson12** [comment]
Thanks Jason!
