### ISSUE TITLE
cSHAKE MCT incomplete

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#1363]
After a long hard struggle, I finally got the cSHAKE MCT working. The specification is incomplete.

The spec defines a part of the MCT as:

```
  Output[0] = Msg;
  for (j = 0; j < 100; j++)
  {
    for (i = 1; i < 1001; i++)
    {
      InnerMsg = Left(Output[i-1] || ZeroBits(128), 128);
      Output[i] = CSHAKE(InnerMsg, OutputLen, FunctionName, Customization);
      Rightmost_Output_bits = Right(Output[i], 16);
      OutputLen = MinOutLen + (floor((Rightmost_Output_bits % Range) / OutLenIncrement) * OutLenIncrement);
      Customization = BitsToString(InnerMsg || Rightmost_Output_bits);
    }

    OutputJ[j] = Output[1000];
  }
```

But it should be defined as:

```
  Output[0] = Msg;
  for (j = 0; j < 100; j++)
  {
    for (i = 1; i < 1001; i++)
    {
      InnerMsg = Left(Output[i-1] || ZeroBits(128), 128);
      Output[i] = CSHAKE(InnerMsg, OutputLen, FunctionName, Customization);
      Rightmost_Output_bits = Right(Output[i], 16);
      OutputLen = MinOutLen + (floor((Rightmost_Output_bits % Range) / OutLenIncrement) * OutLenIncrement);
      Customization = BitsToString(InnerMsg || Rightmost_Output_bits);
    }

    OutputJ[j] = Output[1000];
    Output[0] = Output[1000];
  }
```

See the last line. Without it, the MCT defines that the test vector input message is to be used Output[0] for every new inner loop start. But in fact, the ACVP server wants that the last output of the previous inner loop operation is the input to the next start of the inner loop.

This is verified with the ACVP server.

**Comment by jbrock24** [comment]
Hi @smuellerDD, I am currently looking into this. Thanks for contributing!

**Comment by jbrock24** [comment]
Hi @smuellerDD. After further review I've found that you're correct. The issue is that the spec sheet is incomplete. I've made the update to the spec sheet. Thanks again for contributing!
