### ISSUE TITLE
DRBG security strengths

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP#1364]
**Protocol Section**
https://github.com/usnistgov/ACVP/blob/master/src/drbg/sections/03-supported.adoc

**Protocol Question**
1) What is the basis for the security strengths specified in Table 1, specifically for hash-based DRBGs? SP 800-90Ar1 Section 10.1 specifies:
> The maximum security strength that can be supported by each DRBG based on a hash function is the security strength of the hash function for pre-image resistance; these security strengths are provided in [SP 800-107]. [SP 800-57] identifies hash functions that can be used to support a required security strength.
> This Recommendation supports only four security strengths: 112, 128, 192, and 256 bits.

According to SP 800-107r1, Table 1, the pre-image resistance strengths are equal to the output length of the hash function. I copied the relevant row here:

| | SHA-1 | SHA-224 | SHA-256 | SHA-384 | SHA-512 | SHA-512/224 | SHA-512/256 |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Preimage Resistance Strength in bits | 160 | 224 | 256 | 384 | 512 | 224 | 256 |

However, because SP 800-90Ar1 only supports the four listed security strengths (see above), I believe these maximum security strengths need to be adjusted as follows:

| | SHA-1 | SHA-224 | SHA-256 | SHA-384 | SHA-512 | SHA-512/224 | SHA-512/256 |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Hash-based DRBG Maximum Security Strength in bits | 128 | 192 | 256 | 256 | 256 | 192 | 256 |

2) Does Table 1 in the specification only list the maximum security strengths, or the security strengths supported by the ACVP server? This question also applies to the CTR DRBGs. SP 800-90Ar1 Section 8.4 specifies:
> The actual security strength supported by a given instantiation depends on the DRBG implementation and on the amount of entropy provided to the instantiate function. Note that the security strength actually supported by a particular instantiation could be less than the maximum security strength possible for that DRBG implementation (see Table 1). For example, a DRBG that is designed to support a maximum security strength of 256 bits could, instead, be instantiated to support only a 128-bit security strength if the additional security provided by the 256-bit security strength is not required (e.g., by requesting only 128 bits of entropy during instantiation, rather than 256 bits of entropy).
3) Is there a way to test a DRBG using lower security security strengths than specified in Table 1. For example, suppose an IUT implements a SHA-1 Hash_DRBG, which supports both instantiations of 112 and 128 bits of security. How could this be tested using ACVP?

**Comment by jvdsn** [comment]
As an addendum to my first question, SP 800-56 part 1, revision 5, Table 3 also contains the maximum security strengths for  hash-based functions when used for random number generation. This table seems to confirm my adjusted strengths.

**Comment by livebe01** [comment]
Hi @jvdsn, thank you for mentioning this.

1. I believe that the idea of Table 1 was to line up w/ Table 2 of SP 800-90Ar1 which references SP 800-57 for security strengths. It looks like, when constructing Table 1 of the DRBG spec, that the security strengths were pulled from the "Digital Signatures and Other Applications Requiring Collision Resistance" section of Table 3 SP 800-57 when they should have been pulled from the "HMAC, KMAC, Key Derivation Functions, Random Bit Generation" section. I'll remedy this. Incidentally, the wrong values are also used in our testing on the servers. So our testing currently believes that the maximum security strength for Hash DRBG SHA1 is 80 bits when it should be 128. We'll get a fix in for this as well.
2. Table 1 in the specification lists the maximum security strengths. Table 1 should really live in [Section 7](https://pages.nist.gov/ACVP/draft-vassilev-acvp-drbg.html#name-capabilities-registration) of the specification as the values it list are most useful when reading Table 3 and the notes that follow Table 4.
3. No, there is no way to test DRBGs using lower security strengths. See Note 4 in section 7.4. A SHA-1 Hash_DRBG will need to be tested with values (e.g., entropyInputLen, nonceLen, persoStringLen, etc.) derived from a maximum security strength of 128 bits.

PS In addition to correcting the Table 1 values, I'll make some edits to the DRBG spec to make it a bit more readable and so the sections reference each other a bit better.

Thanks again!

**Comment by livebe01** [comment]
Hi @jvdsn, another note on #3. The purpose of listing the maximum security strengths is to aid in calculating the minimums to use for the items in Table 3. Currently, for your SHA-1 Hash_DRBG example, we do not support a minimum entropyInputLen of 112 bits, nonceLen of 56 bits, persoStringLen of 112 bits, and additionalInputLen of 112 bits (or we won't once I update the code). We require minimums of 128, 64, 128, and 128. If you encounter an implementation where the minimum values we support do not match the implementation's capabilities, let us know. It should be simple to support the lower values.

**Comment by livebe01** [comment]
This change is on Demo in release [v1.1.0.26](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.26)

**Comment by livebe01** [comment]
This change is on Prod in release [v1.1.0.26](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.26)
