### ISSUE TITLE
The posting of SHA response fails

### ISSUE THREAD

**Issue by dsikkema-atsec** [usnistgov/ACVP#1374]
This is on the production server.
The testID is 15985 with vsID of 173405.
The error is the following:
"error": "Could not find any recognizable digits."
I am not sure why it fails with this, the response file looks good as far as I can tell.
The module has a second SHA core and those responses posted without issue.
I cannot attach the file as the json format is not supported.
I can paste the first test.
{
    "acvVersion" : "1.0"
  },
  {
    "vsId" : 173405,
    "algorithm" : "SHA2-256",
    "isSample" : false,
    "testGroups" : [
      {
        "tgId" : 1,
        "tests" : [
          {
            "md" : "F0625D49EBAA0C5EDDB41C17D1BC5570E5001DEFF5F6C553193FFF14B9BE048F",
            "tcId" : 1
          },

**Comment by livebe01** [comment]
Hi @dsikkema-atsec, it looks like tcId 445 is the culprit. On our end, the submitted answer is showing as: `{"md":"CD2BED6B3E4ECACA77863244A8AFABA218A26510837FF7DE[INTMGR]","tcId":445}`.

**Comment by dsikkema-atsec** [comment]
Thank you for catching tyhis, I had missed that when reviewing the file.
I will close this issue.
