### ISSUE TITLE
ECDH primitive vs KAS-ECC-SSC

### ISSUE THREAD

**Issue by davyrouillard** [usnistgov/ACVP#1383]
**Protocol Section**
https://pages.nist.gov/ACVP/draft-fussell-acvp-kas-ecc.html
https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ssc-ecc.html

**Protocol Question**
Hi,
I do not well understand the difference between "[KAS ECC CDH-Component](https://pages.nist.gov/ACVP/draft-fussell-acvp-kas-ecc.txt) - [HTML](https://pages.nist.gov/ACVP/draft-fussell-acvp-kas-ecc.html)" and "[KAS ECC SSC ephemeralUnified Sp800-56Ar3](https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ssc-ecc.txt) - [HTML](https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ssc-ecc.html)". Both seem allow to test the Diffie-Hellman primitive specified in [SP 800-56A] that generates a shared secret.
The only difference I can see is the version of SP800-56A covered:

-  "[KAS-ECC Requirements Covered](https://pages.nist.gov/ACVP/draft-fussell-acvp-kas-ecc.html#name-kas-ecc-requirements-covere) refers to SP 800-56Ar2 .
-  [6.2.1. ](https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ssc-ecc.html#section-6.2.1)[Requirements Covered](https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ssc-ecc.html#name-requirements-covered) refers SP 800-56Ar3 

But since the computation shared secret method is the same for ECC CDH in the both cases, I do not know which one to use.
So my question is "how do I choose between this 2 test methods for an implementation that performs key agreement with ECC CDH share secret computation and key derivation are tested individually?"  
Thanks you.
Davy

**Comment by kriskwiatkowski** [comment]
This is my interpretation:

```
FIPS has multiple ways of claiming CAVP-tested compliance of the key agreement schemes. Each of them corresponds to a different use case, for example, the key agreement may or may not include key derivation. Additionally, FIPS also supports key confirmation (i.e. 56Cr3, 5.9) which can be applied to some key agreements. The differences between the certificates:

* KAS-SSC: Compliance with the agreement on shared secret Z (only). The key agreement scheme is the one mentioned in the SP800-56C r3, Section 6. No key derivation is done after Z is agreed upon.

* KAS: Compliance with NIST-approved key agreement AND derivation. Testing is done End-to-End, meaning both operations are done by single security service and a calling sequence is within the module boundary.

* KDA: It relates only to the key derivation part, so testing is NOT done End-to-End. This certificate is given when derivation uses one of the KDF’s described in SP800-56C rev1 or rev2.

Note that SP800-56C rev2 is also mentioned by the IG 2.4.B. My understanding is that in the case of TLS v1.3 we do need SP800-56 rev2, but not necessarily KDA certificate. For KDA compliance, software needs to be tested separately.
```

**Comment by kriskwiatkowski** [comment]
Good question. I think:

* KAS-ECC-CDH: Compliance with the agreement on shared secret Z (only). The key agreement scheme is the one mentioned in the SP800-56C r3, Section 6. No key derivation is done after Z is agreed upon.

* KAS-ECC: Compliance with NIST-approved key agreement AND (optionally) derivation. Testing may be done End-to-End, meaning both operations (derivation and KEX) are done by single security service and a calling sequence is within the module boundary. You may also certify key confirmation (i.e. 56Ar3, 5.9)

So depends what you need, but note that KAS-ECC-CDH is rarely used in practice by it's own. Usually you need to do derivation also at some point.

**Comment by livebe01** [comment]
Hi @davyrouillard, one way to look at this would be to ask what you want the entries on your CMVP cert to look like? I'm a bit removed from that topic these days and I'm aware that there are changes under way with how the CMVP certs will display CAVP certs and algorithms. What I can tell you is that KAS ECC SSC ephemeralUnified Sp800-56Ar3 will result in a KAS-ECC-SSC Sp800-56Ar3 CAVP cert entry which equates to a FIPS 140-2 CMVP cert KAS-SSC algorithm entry and that KAS ECC CDH-Component will get you a KAS-ECC CDH-Component CAVP cert entry which would equal to a FIPS 140-2 CMVP cert CVL algorithm entry. Is that helpful?
