### ISSUE TITLE
ACVP server does not provide d for rsakpg1-crt and rsakpg2-crt tests

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP#1389]
When requesting test vectors for SP 800-56Br2 KAS with `rsakpg1-crt` or `rsakpg2-crt` key generation methods, the server does not provide the d values. However, according to SP 800-56Br2, Section 6.3.1.3:
> rsakpg1-crt is the generator in the RSAKPG1 family such that the private key is in the Chinese Remainder Theorem format (n, e, d, p, q, dP, dQ, qInv).

and Section 6.3.2.3:
> rsakpg2-crt is the generator in the RSAKPG2 family such that the private key is in the Chinese Remainder Theorem format (n, e, d, p, q, dP, dQ, qInv).

Why is d missing from the test vectors if it is part of the private key according to the standard?

The reason I ask is that I have an IUT which refuses to construct an RSA-CRT key when d is not provided.

**Comment by livebe01** [comment]
Hi @jvdsn,

Can you provide sample vector set ids for the scenarios you're describing? The actual details of the registrations you used may/may not impact the observed behavior, but sometimes they do and it helps us to troubleshoot more quickly.

Good to hear from you!

Regards,

Ben

**Comment by jbrock24** [comment]
@jvdsn Hi! How will you use the D value? It's not normally used within the CRT generation.

**Comment by jvdsn** [comment]
> @jvdsn Hi! How will you use the D value? It's not normally used within the CRT generation.

The specific test I'm talking about is the `responder` test, i.e. the IUT decapsulates the secret encapsulated by the server. The IUT I'm talking about is OpenSSL 3, which performs the KAS here:
* https://github.com/openssl/openssl/blob/master/providers/implementations/kem/rsa_kem.c#L293
* https://github.com/openssl/openssl/blob/master/providers/implementations/kem/rsa_kem.c#L317
* https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_crpt.c#L45
* https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_ossl.c#L369
* https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_ossl.c#L440
* https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_ossl.c#L608
* https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_ossl.c#L943-L962

The last link is the critical step, there seems to be some protection against RSA-CRT fault attacks. If a fault is detected, OpenSSL falls back to the `d` parameter.

**Comment by jbrock24** [comment]
Thanks, will look into this, appreciated!

**Comment by jbrock24** [comment]
@jvdsn Thanks for the feedback. Basically, D isn't created (or used) when we make a CRT key. Given the last link, that would need to be handled on openssl's end. Thanks!
