### ISSUE TITLE
KAS1/KAS2 initiator VAL test

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP#1390]
**Protocol Section**
https://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56br2/ssc/sections/04-testtypes.adoc
ttps://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56br2/sections/04-testtypes.adoc

**Protocol Question**
Is a KAS1/KAS2 initiator VAL test really required? Consider OpenSSL, which in version 3.0 provides the following APIs:
* https://www.openssl.org/docs/man3.0/man3/EVP_PKEY_encapsulate.html
* https://www.openssl.org/docs/man3.0/man3/EVP_PKEY_decapsulate.html

They claim it is a compliant implementation for of RSASVE as specified in SP 800-56Br2 (https://www.openssl.org/docs/man3.0/man7/EVP_KEM-RSA.html). If you look closely, you will see that EVP_PKEY_encapsulate does not have a way to provide a secret to the API; instead it's automatically randomly generated.

From a cryptographic point of view, this actually makes sense. The user isn't trusted to generate good random secrets, so OpenSSL generates the secret internally where it can ensure it's got the right format and really is random. I don't see any problems with this approach, and the implementation passes all other tests.

So why is the KAS1/KAS2 initiator VAL really required? If RSASVE.GENERATE is properly implemented, there is no scenario in which the IUT receives a secret from the caller to encapsulate. In fact, RSASVE.GENERATE as specified in SP 800-56Br2 does not take any input parameters except the public key.

**Comment by jbrock24** [comment]
The OpenSSL method that encapsulates is doing what the AFT test does. The ACVP server generates, as with the OpenSSL version, the secret (Z) and then it's distributed to both parties for verification. The VAL test is introducing complexity, variations, errors, etc., that the IUT needs to be able to detect, handle, and report back the issues it discovered. 


`Various types of conditions/errors MUST be introduced in varying portions of the key agreement process (changed Z, Z with leading zero nibble, etc), that the **IUT MUST be able to detect and report on**.`

One test is the functionality (if all things are perfect and as expected) and the other is detecting the various types of issues, and reporting back what it received, i.e., TDD vs BDD.

**Comment by jvdsn** [comment]
I understand that the VAL test is used to ensure the IUT detects issues, however from the *initiator* perspective, what issues can be introduced?

**Comment by jvdsn** [comment]
@jbrock24 did you see my comment last month? Per Figure 6 of SP 800-56Br2, the following steps are performed:

1) Party V sends its PubKey to Party U
2) Party U performs (Z, C) = RSASVE.GENERATE(PubKey V)
3) Party U sends C to Party V
4) Party V performs Z = RSASVE.RECOVER(PrivKey V, C)
5) ...

I can understand the VAL test for the responder (party V), which tests step 4 above (the "unhappy path"). However, what errors would be tested for the VAL test for party U?
