### ISSUE TITLE
Error appears in vector rather than response when creating test session with KAS-ECC registration

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#1399]
I am creating a test session with a `KAS-ECC` revision `Sp800-56Ar3` algorithm registration (ID: 153) with errors within the selection.  Normally, the response from the test session create when it errors contains the reasons why.  However, in this case, the test session appears to be created successfully, but the errors seems to be captured within the vector set.  And example of this is test session ID `333097`

The sessions appears to have been created, but reading vector set `1319450` shows that there were errors in the algorithm capabilities.

**Comment by jbrock24** [comment]
Sorry, to clarify the test was returned as canceled with no files available for me to use/test. Thanks :)

**Comment by jbrock24** [comment]
Thanks!

**Comment by jbrock24** [comment]
After review, the errors are correct from an updated implementation by Ben in November. As far as the how it's reporting errors, it's using the same system as the other algorithms. It generates a response, etc, nothing has changed and it's reusing the same code.

**Comment by AlexThurston** [comment]
But doesn't this make the API a little inconsistent?  In some cases, if I request a test session with algorithm registration values, I will get an error at that time (which I think is good).  However, in other cases, the error will exist in the vector set which will only be discoverable later.

IMO, this makes the API less worse because now a user must go through each and every vector set of a test session to ensure that they have been generated correctly and that the selections are good rather than being notified that a registration selection is incorrect from the time of test session creation.

**Comment by jbrock24** [comment]
Sorry @AlexThurston . I am trying to clean up Github stuff currently and wanted to reply to this. I am keeping this in mind as I agree with you. It's a requirement of the algorithm and the check if it exists should be within the registration by assumption, I am going to look into why this isn't being done there and ways to resolve it.

**Comment by AlexThurston** [comment]
@jbrock24 I was wondering if you had any thoughts on this and if you saw any technical reason why the check wasn't happening during registration.

**Comment by jbrock24** [comment]
Hey @AlexThurston , this actually came up earlier this week from another dev no the team. I'm currently tracking down why this is going on. On the surface it's using the same system, but something somewhere is changing how it functions. Appreciate the feedback and am currently using your registration for testing. Will get back to you sometime soon regarding it.

**Comment by AlexThurston** [comment]
@jbrock24 Awesome.  Let me know if there's anything I can do to help.

**Comment by jbrock24** [comment]
Found the issue and fixed it. It will go out with the next release. Thanks for the ping @AlexThurston and for the info. I'll ping with the release to let you know it's out.

**Comment by AlexThurston** [comment]
NICE!  @jbrock24! You are a scholar and a gentleman!

**Comment by livebe01** [comment]
The fix for this is on Prod in release [v1.1.0.32](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.32).
