### ISSUE TITLE
Symmetric Model Section 3.2 Name Clarification

### ISSUE THREAD

**Issue by DBugger32** [usnistgov/ACVP#14]
Currently we have these sections...
3. Test Vectors
3.1 Test Groups JSON Schema
3.2 Test Vectors JSON Schema

I believe this is confusing as Test Vector is used twice in the hierachy .  Recommend we go to the following...
3. Test Vectors
3.1 Test Groups
3.2 Test Cases

and change all references to Test Vector in the Section 3.2 text to Test Case

> Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test case to be processed by the ACVP client. The following table describes the JSON elements for each test case.

**Comment by jfigus** [comment]
Good catch, I'll make this correction.

**Comment by jfigus** [comment]
Fixed in 121b2c2faf5553f2a03b328f683260fc40105220
