### ISSUE TITLE
RSA Decryption Primitive sp800-56Br2 Standard Calculations, Request for public exponent "e".

### ISSUE THREAD

**Issue by prashantawde** [usnistgov/ACVP#1409]
**What type of change is being proposed?**
Inclusion of public exponent "e" value in input vector set. 

**Details on suggestion**
What would you like to see changed in the protocol specification?
https://pages.nist.gov/ACVP/draft-celi-acvp-rsa.html#name-test-cases-for-rsa-decryptio
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Br2.pdf Section: 7.1.2.2

**Additional information**
As per Section 7.1.2.2 of the NIST.SP.800-56Br2.pdf, we need to provide (p, q, d) and ciphertext to the API of Crypto modules.
![image](https://user-images.githubusercontent.com/123559489/215037455-8f9b9896-d9ba-49e5-ac28-79d22ab84d0a.png)

Same values we are getting from ACVP server as part of test vectors:
![image](https://user-images.githubusercontent.com/123559489/215040887-1e236155-9e17-4c43-b9b8-ff4e8a726e08.png)

But we have seen that some of the vendor's crypto modules are required to feed with public exponent "e" value to retrieve proper results from them. We have to put a workaround to calculate the public exponent "e" manually before given as input to crypto module APIs to get desired results, otherwise, we are always getting wrong and different results for the same input vectors.

Requesting to guide on same.

**Comment by jbrock24** [comment]
Hi @prashantawde. We are currently refactoring this algo to include the correct outputs. This will be released shortly. Thanks for the feedback!

**Comment by jbrock24** [comment]
I will reply here when the update is done and pushed!

**Comment by ehanson12** [comment]
@jbrock24 Is the update done and pushed?

**Comment by jbrock24** [comment]
Hi @ehanson12 , sorry I missed this. This is along the same lines as RSASP, it's being worked side-by-side, and will release after review to demo for testing, and then sometime after - once sufficiently publicly tested - released to production.

**Comment by ehanson12** [comment]
@jbrock24 Thanks Joel!

**Comment by jbrock24** [comment]
Hi @ehanson12 & @prashantawde, the recent update hotfix for v1.1.0.28 corrects this issue. It should be on both demo and prod by looks of the notes. Thanks for the input!

**Comment by ehanson12** [comment]
@jbrock24 Much appreciated Joel!

**Comment by prashantawde** [comment]
Thanks for fix @jbrock24. I will check and update.

**Comment by jbrock24** [comment]
No worries!
