### ISSUE TITLE
Difference between outputLen and macLen for KMAC

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP#1410]
**Protocol Section**
XOF: https://github.com/usnistgov/ACVP/blob/master/src/xof/sections/05-capabilities.adoc
Table 2

**Protocol Question**
What is the difference between `outputLen` and `macLen` for KMAC? When is `outputLen` expected and when is `macLen` expected?

**Comment by jbrock24** [comment]
I removed those from the requirements as they aren't used by KMAC. Thanks!

**Comment by jvdsn** [comment]
> I removed those from the requirements as they aren't used by KMAC. Thanks!

@jbrock24 I believe you removed the wrong columns for KMAC? `msgLen` is empty now :)

**Comment by jbrock24** [comment]
Sorry, just noticed this. Yup, wrong column, should be fixed!
