### ISSUE TITLE
incorrect info in table 5 of "ACVP SP800-108 Key Derivation Function JSON Specification"

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP#1411]
table 5 in  https://pages.nist.gov/ACVP/draft-celi-acvp-kbkdf.html  indicates that 'macMode' is a string but should be an array of strings and the min value for keyDerivationKeyLength should be 112, not 8.

"TestSession": [
            {
                "acvVersion": "1.0"
            },
            {
                "error": "Validation error(s) on JSON payload.",
                "context": [
                    "KDF-KMAC-Sp800-108r1: Minimum Key Derivation Key Length must be greater than or equal to 112"
                ]
            }
        ]

**Comment by jbrock24** [comment]
Thanks @mmccarl for making us aware of this. I updated tables 4 and 5 macMode's to be an array of strings and not single string. I also updated the keyDerivationKeyLength to be in of 112 as well after reviewing the algo.
