### ISSUE TITLE
predResistanceEnabled vs reseedImplemented

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP#1412]
**Protocol Section**
https://github.com/usnistgov/ACVP/blob/master/src/drbg/sections/05-capabilities.adoc

**Protocol Question**
How do predResistanceEnabled and reseedImplemented interact? Is there some kind of implicit dependency, i.e. predResistanceEnabled == true requires reseedImplemented == true? What happens if predResistanceEnabled == true but reseedImplemented == false?

**Comment by smuellerDD** [comment]
Am Mittwoch, 8. Februar 2023, 00:03:53 CET schrieb Joachim Vandersmissen:

Hi Joachim,

> **Protocol Section**
> https://github.com/usnistgov/ACVP/blob/master/src/drbg/sections/05-capabilit
> ies.adoc
> 
> **Protocol Question**
> How do predResistanceEnabled and reseedImplemented interact? Is there some
> kind of implicit dependency, i.e. predResistanceEnabled == true requires
> reseedImplemented == true? What happens if predResistanceEnabled == true
> but reseedImplemented == false?

You can freely mix-n-match both.


Ciao
Stephan

**Comment by jvdsn** [comment]
Conceptually speaking, what is the expected behavior if reseed is not implemented but prediction resistance is set to true? How can a DRBG provide prediction resistance if it is unable to reseed with fresh entropy?

**Comment by smuellerDD** [comment]
Am Mittwoch, 8. Februar 2023, 16:21:32 CET schrieb Joachim Vandersmissen:

Hi Joachim,

> Conceptually speaking, what is the expected behavior if reseed is not
> implemented but prediction resistance is set to true? How can a DRBG
> provide prediction resistance if it is unable to reseed with fresh entropy?

PR is a DRBG-internal reseed operation. I.e. no interfaces to callers is 
needed.

Reseeding is a caller-triggered reseed operation. I.e. the DRBG must offer an 
interface to provide the reseed data.

Ciao
Stephan
