### ISSUE TITLE
Exception running generator, HMAC SHA2-384 on ACVTS server

### ISSUE THREAD

**Issue by Ai510** [usnistgov/ACVP#1416]
![cc2c66ac-ad43-46ba-a9b0-83938a3c1a43](https://user-images.githubusercontent.com/125464099/219033437-6a0cb7c4-015f-49f1-bf4c-5b61a7b71f9b.jpg)

Currently while performing algorithm testing, while verifying the uploaded vector sets for a particular test session, there was the above error which we came across for vsId: 186980( algorithm: HMAC SHA2-384). The error was **"Exception running generator**" but the same algorithm was verified for some other vsID. I have attached the screenshot above.Please note the current error to check if any possible solution if available for it. 
While re-verifying the vector, it gave **error 404** which means the data for the vector ID cannot be found for that particular vsID. I am attaching the screenshot for error 404 below. Please check regarding the error for the given vsID. 
Could **CAVP** please assist in resolving the above issue? We would greatly appreciate it!
![4ac1e640-1bc6-4bce-b6f6-b9e399a32cfd](https://user-images.githubusercontent.com/125464099/219040075-451eb663-2b3c-45e6-97ee-c97673de1e76.jpg)

**Comment by livebe01** [comment]
Hi @Ai510,

Just to confirm, 186980 is the vsId you're interested in? VsId 186980 is from April of 2020 and is expired.

Thanks,

Ben

**Comment by Ai510** [comment]
Hi @livebe01,

Thank you for your response. Yes, I am interested in VsID 186980 for the test session 17422.

**Comment by livebe01** [comment]
Okay, it wasn't clear which environment you were interacting with, i.e., Demo vs Prod. I reran some processes on our end and you should be able to verify that the vector set is now "passed".

**Comment by Ai510** [comment]
Yes, now it says "passed". Thank you @livebe01
