### ISSUE TITLE
DRBG SP800-90A: which version (2012 or 2015)?

### ISSUE THREAD

**Issue by davyrouillard** [usnistgov/ACVP#1417]
Hello,

**Algorithm page**
https://pages.nist.gov/ACVP/draft-vassilev-acvp-drbg.html

**Question**
The ACVP documentation for DRBG refers to "SP800-90A version January 2012" when the current revision is [SP800-90A Rev. 1 June 2015](https://csrc.nist.gov/publications/detail/sp/800-90a/rev-1/final).
Is it voluntary or an error in the documentation?
Does it means that some tests could fail on a implementation compliant to [SP800-90A Rev1]?

Thank you,
Davy

**Comment by davyrouillard** [comment]
To complete my question, the two SP800-90A versions differs on the counter DBRG by the possibility offered by the 2015 version to have  a counter with 4 ≤ ctr_len ≤ blocklen. With  ctr_len=4, a rollback of the counter will appear after 2^4 loops.
In case of AES-256 counter DRBG , the expect result will be different on the two versions if the request random string is greater than 2048. That why it is important to know which version is implemented by the Server. 


 From my understanding, if a implementation

**Comment by jbrock24** [comment]
@davyrouillard Thanks for the clarification and guidance! Sorry, I've been trying to get to this. I am currently researching the answer and will respond soon when done.

**Comment by jbrock24** [comment]
Hi @davyrouillard, the documentation is correct, it's [SP800-90A](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-90a.pdf).
