### ISSUE TITLE
SP 800-56Br2 KTS-OAEP testing does not currently support mismatching H and MGF hash functions

### ISSUE THREAD

**Issue by rruss-ldos** [usnistgov/ACVP#1419]
SP 800-56Br2, Section 7.2.2.1 explicitly states that the hash functions selected for H and MGF need not be the same. [Currently, KTS-OAEP testing assumes that the same hash function is used for H and MGF.](https://github.com/usnistgov/ACVP-Server/blob/b633d3fd5fabd375ef572f9b4feb38cd26932596/gen-val/src/crypto/src/NIST.CVP.ACVTS.Libraries.Crypto/KTS/KtsFactory.cs#L62)

We request optional functionality be added to the [spec](https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ifc.html#name-supported-kts-method)/server to support mismatching H and MGF hash functions.

**Comment by livebe01** [comment]
This sounds like a reasonable request. I assume that you need this feature to test an implementation. Is that correct?

**Comment by rruss-ldos** [comment]
Correct, we have a vendor who wishes to test this functionality.

**Comment by livebe01** [comment]
Thanks, we'll get this implemented and out as soon as possible.

**Comment by livebe01** [comment]
UPDATE: CAVP will not implement testing for the scenario where H != MGF. It is sufficient to only test the cases where H = MGF.

Thank you!
