### ISSUE TITLE
Documentation: discrepancy between github's .adoc and pages.nist

### ISSUE THREAD

**Issue by locksmithone** [usnistgov/ACVP#1428]
Reading the README file, one assumes that any update to the .adoc documentation automatically propagates to the HTML/txt pages at pages.nist (accessible through the links in the README file). However, I have seen many discrepancies between those, and thus it is more difficult to assess which version is the most up-to-date one.

1. Would the .adoc files in github be the most up-to-date ones?
2. Are those .adoc in fact automatically, and immediately, propagated to pages.nist?

**Comment by jbrock24** [comment]
Hi @locksmithone, yes the pages we edit through the github propogate the pages.nist files. Can you provide me an example(s) of this issue so I can look into it more? Thanks!

**Comment by locksmithone** [comment]
Yes.

For instance, let's compare the SP800-56Arev3 KAS ECC.

In https://pages.nist.gov/ACVP/draft-fussell-acvp-kas-ecc.html, we have this description in Section 7.11.1:

```
uPartyInfo

uPartyId { || ephemeralKey } { || ephemeralNonce } { || dkmNonce }
```

In https://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56ar3/ecc/sections/05-capabilities.adoc, the same bit appears as below:

```
uPartyInfo

uPartyId { || ephemeralKey } { || ephemeralNonce } { || dkmNonce } { || c }
```

See the addition of `{ || c}`. This field is also not explained in the .adoc.

**Comment by livebe01** [comment]
@locksmithone https://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56ar3/ecc/sections/05-capabilities.adoc maps to https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ecc-sp800-56ar3.html vs https://pages.nist.gov/ACVP/draft-fussell-acvp-kas-ecc.html

**Comment by locksmithone** [comment]
Aha. So the link in the README file is incorrect, then. I will prepare a
pull request to correct the link.

**Comment by locksmithone** [comment]
I am then corrected. I was looking at the wrong link (from KAS ECC *SSC* algorithm).
