### ISSUE TITLE
Definition of uPartyInfo and vPartyInfo: what is the defintion of the components?

### ISSUE THREAD

**Issue by locksmithone** [usnistgov/ACVP#1434]
**Protocol Section**
SP800-56Arev3 KAS ECC, Section 7.5.1.3
https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ecc-sp800-56ar3.html#fixedinfopatcon

**Protocol Question**
This section gives the definition of uPartyInfo and vPartyInfo. For uPartyInfo, for instance:

`uPartyId { || ephemeralKey } { || ephemeralNonce } { || dkmNonce } { || c }`

What is the `c`?

**Comment by Kritner** [comment]
think it might just be a "reuse" (copy/paste issue) from the RSA based KAS construction.

**Comment by jbrock24** [comment]
Thanks @locksmithone. I've looked through the documentation and the code and can't find this as a valid parameter, I have removed it from the documentation in #1436. Thanks!

**Comment by jbrock24** [comment]
FYI, this is pushed.
