### ISSUE TITLE
FIPS 186-2 sigVer does not allow SHA512/224 and SHA512/256

### ISSUE THREAD

**Issue by afazio2** [usnistgov/ACVP#1435]
**environment**
Demo

**testSessionId**
Not able to register algorithm.

**vsId**
Not able to register algorithm.

**Algorithm registration**
{
        "revision":"FIPS186-2",
        "algorithm":"RSA",
        "mode":"sigVer",
        "pubExpMode":"fixed",
        "fixedPubExp":"010001",
        "capabilities":[
          {
            "sigType":"pkcs1v1.5",
            "properties":[
              {
                "modulo":1024,
                "hashPair":[
                  {
                    "hashAlg":"SHA2-224",
                    "saltLen":28
                  },
                  {
                    "hashAlg":"SHA2-256",
                    "saltLen":32
                  },
                  {
                    "hashAlg":"SHA2-384",
                    "saltLen":48
                  },
                  {
                    "hashAlg":"SHA2-512",
                    "saltLen":62
                  },
                  {
                    "hashAlg":"SHA2-512/224",
                    "saltLen":28
                  },
                  {
                    "hashAlg":"SHA2-512/256",
                    "saltLen":32
                  }
                ]
              },
              {
                "modulo":1536,
                "hashPair":[
                  {
                    "hashAlg":"SHA2-224",
                    "saltLen":28
                  },
                  {
                    "hashAlg":"SHA2-256",
                    "saltLen":32
                  },
                  {
                    "hashAlg":"SHA2-384",
                    "saltLen":48
                  },
                  {
                    "hashAlg":"SHA2-512",
                    "saltLen":64
                  },
                  {
                    "hashAlg":"SHA2-512/224",
                    "saltLen":28
                  },
                  {
                    "hashAlg":"SHA2-512/256",
                    "saltLen":32
                  }
                ]
              }
            ]
          },
          {
            "sigType":"pss",
            "properties":[
              {
                "modulo":1024,
                "hashPair":[
                  {
                    "hashAlg":"SHA2-224",
                    "saltLen":28
                  },
                  {
                    "hashAlg":"SHA2-256",
                    "saltLen":32
                  },
                  {
                    "hashAlg":"SHA2-384",
                    "saltLen":48
                  },
                  {
                    "hashAlg":"SHA2-512",
                    "saltLen":62
                  },
                  {
                    "hashAlg":"SHA2-512/224",
                    "saltLen":28
                  },
                  {
                    "hashAlg":"SHA2-512/256",
                    "saltLen":32
                  }
                ]
              },
              {
                "modulo":1536,
                "hashPair":[
                  {
                    "hashAlg":"SHA2-224",
                    "saltLen":28
                  },
                  {
                    "hashAlg":"SHA2-256",
                    "saltLen":32
                  },
                  {
                    "hashAlg":"SHA2-384",
                    "saltLen":48
                  },
                  {
                    "hashAlg":"SHA2-512",
                    "saltLen":64
                  },
                  {
                    "hashAlg":"SHA2-512/224",
                    "saltLen":28
                  },
                  {
                    "hashAlg":"SHA2-512/256",
                    "saltLen":32
                  }
                ]
              }
            ]
          }
        ],
        "prereqVals":[
          {
            "algorithm":"SHA",
            "valValue":"same"
          },
          {
            "algorithm":"DRBG",
            "valValue":"same"
          }
        ]
      }

**Expected behavior**
Expect to receive the vector request.
Received the following error:
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "RSA-sigVer-FIPS186-2: Invalid Hash Algorithms supplied: SHA2-512/224;Invalid Hash Algorithms supplied: SHA2-512/256;Invalid Hash Algorithms supplied: SHA2-512/224;Invalid Hash Algorithms supplied: SHA2-512/256;Invalid Hash Algorithms supplied: SHA2-512/224;Invalid Hash Algorithms supplied: SHA2-512/256;Invalid Hash Algorithms supplied: SHA2-512/224;Invalid Hash Algorithms supplied: SHA2-512/256"
    ]
  }
]

**Comment by jbrock24** [comment]
Hi @afazio2. That is by design, `FIPS186-2` doesn't support SHA2 truncated modes since it didn't exist when 186-2 was the published standard. This is something that won't get implemented, the [documentation](https://pages.nist.gov/ACVP/draft-celi-acvp-rsa.txt) was in error, which I will fix. Thanks for bringing that to our attention!

**Comment by jbrock24** [comment]
FYI, this is pushed.
