### ISSUE TITLE
Hash Based Signature Support

### ISSUE THREAD

**Issue by ashman-p** [usnistgov/ACVP#1437]
**Protocol Section**
ACVP HSS 

**Protocol Question**
ACVP demo server currently supports LMS. Will HSS be added? Will HSS incorporate LMS per RFC 8554
where the level is added.

**Comment by livebe01** [comment]
Yes. The plan for the SP 800-208 algorithms is to tackle HSS first, then XMSS after.

**Comment by jvdsn** [comment]
@livebe01 LMS was added a while ago, but that PR didn't seem to include HSS. Does the server support HSS? There is a lot of HSS code on the other repository: https://github.com/search?q=repo%3Ausnistgov%2FACVP-Server%20HSS&type=code

**Comment by livebe01** [comment]
No, there's no support for HSS. We're working on Dilithium, Kyber, and Sphincs+ right now. It's a bit backwards, but HSS and XMSS will come after them.
