### ISSUE TITLE
Monte Carlo tests for SHA-1 and SHA-2 - forwarding registered minimum messageLength

### ISSUE THREAD

**Issue by null0link** [usnistgov/ACVP#1441]
If I understand correctly [MCT algorithm](https://pages.nist.gov/ACVP/draft-celi-acvp-sha.html#section-6.2-5) for SHA-1 and SHA-2, when hash algorithm has been registered with `"messageLength": [ { "min": X } ]` then value `SmallestSupportedMessageLengthGreaterThanZero` should be equal to `X` when `X > 0`, or `1` when `X == 0`.

**What type of change is being proposed?**
If the above is correct, please forward registration entry `messageLength` (or its `min` member) to the test request vector.

**Additional information**
Lack of this value in the test vectors forces the testing harness tool to obtain the value from the registration file, which introduces additional dependency when parsing the vectors.

**Comment by jbrock24** [comment]
Hi @null0link I understand what you're saying. I'll look into this. Thanks for bringing it to my attention.

**Comment by null0link** [comment]
Thank you.

**Comment by null0link** [comment]
I think there is a difference between [algorithm](https://pages.nist.gov/ACVP/draft-celi-acvp-sha.html#name-monte-carlo-tests-for-sha-1) and its [implementation](https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/src/crypto/src/NIST.CVP.ACVTS.Libraries.Crypto/SHA/MCT/ShaMct.cs#L135):

If `GetRandomBitsOfLength()` is random how does the ACVP server verify IUT response as these random bits are not outputted in the test response? 
In the implementation I can see that it is using `seedMessage || seedMessage || seedMessage` as an input. If so, then those are not random bits and IUT under have to support both `SupportedMessageLengths.Contains(3*digestSize)`  and `SupportedMessageLengths.Contains(3*seedSize)`. Is this correct? If so, I received from ACVP server a test case which forces IUT to use unsupported message length.

**Comment by livebe01** [comment]
Hi @null0link, the `SEED` in https://pages.nist.gov/ACVP/draft-celi-acvp-sha.html#name-monte-carlo-tests-for-sha-1 corresponds with the `msg` value provided for the MCT test case in the prompt. This is a value provide by the ACVTS server. 

You mention receiving a test case which forces IUT to use unsupported message length. It sounds like you may be experiencing the same issue described [here](https://github.com/usnistgov/ACVP-Server/issues/266). Can you provide the vsId of the vector set in question?

**Comment by null0link** [comment]
Hi @livebe01, I posted vectors on the topic that you provided. What I don't get is highlighted line below:
![MCT_alg](https://github.com/usnistgov/ACVP/assets/132047334/4d85d2df-e57c-4031-a263-67b5a9f1d9ef)
My second point is that in the algorithm of updated Monte Carlo Test for SHA-1 and SHA-2 first line:
`if SupportedMessageLengths.Contains(3*digestSize):`
should be changed to:
`if SupportedMessageLengths.Contains(3*digestSize) and SupportedMessageLengths.Contains(3*seedSize):`

otherwise unsupported message length case still can be hit.

**Comment by null0link** [comment]
Does this pseudo code show a server algorithm, not client one, and I got confused?

**Comment by jbrock24** [comment]
@null0link Good morning from the US! in the above line, the digestSize IS the seedSize. In the above scenarios, we get a seed of DigestSize, and in the else we create a seed of a custom size instead. This is the Server side creating vector sets based on the settings requested.

**Comment by null0link** [comment]
@jbrock24 Good morning. Yes, when I thought that it may be the server generation algorithm, it made sense for me. At first glance it seems that it is an algorithm that testing harness tool have to perform. Now there is nothing more that I can say other that kindly suggest to state on the web page that this is an algorithm for generating test vectors and its valid response.

**Comment by jbrock24** [comment]
Ah, OK. I'll speak with the others in the Team to see what we can do to make this more obvious, apologies. Closing this out, thanks for the feedback!

**Comment by livebe01** [comment]
Hi @null0link, the pseudocode _is_ exactly  "an algorithm that testing harness tool have to perform." But when we wrote the pseudocode we were also focused on implementing it for ACVTS, hence the confusion. I made an edit [here](https://github.com/usnistgov/ACVP/commit/baff6487312cbc64bb27de15602924c89c2d8bbc) that should remove the confusion.

**Comment by null0link** [comment]
Thanks, looks good!
