### ISSUE TITLE
LMS example capabilities registration is incorrect

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP#1442]
On https://pages.nist.gov/ACVP/draft-celi-acvp-lms.html#section-7.3.3, a couple of example LMS capabilities registrations are shown. However, when I try to submit these exact same registrations to the server, I get the following response:
```
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "LMS-keyGen-1.0: Either specificCapabilities or Capabilities must be provided, not both.",
      "LMS-sigGen-1.0: Either specificCapabilities or Capabilities must be provided, not both.",
      "LMS-sigVer-1.0: Either specificCapabilities or Capabilities must be provided, not both."
    ]
  }
```

I feel like the specification also doesn't make it very clear that this is an exclusive choice.

**Comment by livebe01** [comment]
Hi @jvdsn. Just letting you know that we've received this and are looking into it.
