### ISSUE TITLE
ACVP RSA Algorithm JSON Specification issues

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP#1451]
There are a couple issues in the ACVP RSA Algorithm JSON Specification that I noticed:

1. Table 13 indicates that the JSON value "modulo" is to be included in the RSA/signaturePrimitive/2.0 registration, however the sample JSON has "modulus".  Submitting with "modulo" generates the error message "RSA-signaturePrimitive-2.0: No modulo supplied.".  Both the spec and the error message need to be updated to say "modulus".
2. The Figure 1 and the example of an RSA/signaturePrimitive/2.0 registration includes "isSample" within the algorithm entry, but isSample is not in Table 13.  "isSample" should probably not be included in any of the example registrations.

**Comment by jbrock24** [comment]
Just to clarify, this is complete, it will go out with the next release!

**Comment by livebe01** [comment]
The fix for this is on Demo in release [v1.1.0.31](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.31).

**Comment by livebe01** [comment]
The fix for this is on Prod in release [v1.1.0.31](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.31).
