### ISSUE TITLE
What does "katReceieved" status for a test vector mean?

### ISSUE THREAD

**Issue by amasino** [usnistgov/ACVP#1455]
When trying to post/send a test vector response in the production environment, I received the following protocol message:

ACVPProxy (13:39:09) (vid250424) Error: Server error response: [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Vector set not in \u0027processed\u0027 status.",
      "Unable to submit results when vector set in \u0027katReceieved\u0027 status."
    ]
  }
]

The json response file is correct, I don't see this status in the protocol definition. What does it mean, and is it a recoverable status?

Thanks,
Alejandro Masino
atsec information security corp.

**Comment by jbrock24** [comment]
Hi @amasino, it appears this is the case when a failure has occurred previously; instead of a POST, you'll need to PUT it to the server. Hopefully the bottom of this previous issue helps:

https://github.com/usnistgov/ACVP/issues/1104#issuecomment-952824436

> this:
> 
> ACVPProxy (11:56:33) (vid729596) Error: Server error response: [
> {
> "acvVersion": "1.0"
> },
> {
> "error": "Validation error(s) on JSON payload.",
> "context": [
> "Vector set not in \u0027processed\u0027 status.",
> "Unable to submit results when vector set in \u0027failed\u0027 status."
> ]
> }
> ]
> appears to be a message we would pass back from the POST endpoint, the POST endpoint only ever expects the answers to be submit when in a "processed" state (the status after prompt file generation, and before any answers are received), if your vector set is already in a failed status due to having not passed a validation attempt previously, then the PUT verb should be used.
