### ISSUE TITLE
Question: Algorithm Update Hierarchy on Certificates

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP#1456]
When updating an algorithm on an existing certificate, the updated algorithm essentially 'bumps' the existing algorithm from the certificate. This typically requires re-testing of some of the algorithm options along with the option being updated in order to maintain everything on the certificate.

Is there a rule (or rules) by which we can determine if a particular algorithm/mode/version would be 'bumped' from a cert?

**Comment by livebe01** [comment]
Hi @mmccarl, I think this wiki page should answer your question: https://github.com/usnistgov/ACVP/wiki/Guidelines-on-Test-Session-Capabilities

**Comment by mmccarl** [comment]
yes, i've read that, but does 'algorithm' include the mode and version, e.g. would testing 'RSA/sigGen/FIPS186-4' displace 'RSA/sigGen/FIPS186-5' if 186-5 was not retested?

**Comment by livebe01** [comment]
That's a good clarifying point. We'll update the wiki page.

"algorithm" is name/mode/version, so no, 186-5 won't be impacted by anything done with 186-4
