### ISSUE TITLE
Clarification request: 8.2.2 and 8.2.1 are supported with external IV generation for GMAC as well as GCM

### ISSUE THREAD

**Issue by kaleb-himes** [usnistgov/ACVP#1458]
**Protocol Section**
https://github.com/usnistgov/ACVP/blob/master/src/mac/sections/05-gmac-capabilities.adoc

**Protocol Question**
For GCM "Table 6. Authenticated Block Cipher Algorithm Capabilities Applicability Grid" https://github.com/usnistgov/ACVP/blob/master/src/symmetric/sections/05-capabilities.adoc is clear that 8.2.1 and 8.2.2 IV construction is supported for both Internal and External IV generation. However for GMAC the statement preceding "8.2.1 and 8.2.2" makes it sounds as if one can not test 8.2.1 and 8.2.2 when IV is Externally generated. Statement reads: "The IV generation mode for use when the IUT is internally generating IVs"

However the DEMO and PROD servers both support testing GMAC with 8.2.2 and 8.2.1 with External IV generation. Could we get an amendment to the capabilities table for gmac to make it clear that both IV construction methods can be tested with external IV  generation in GMAC the same as GCM?

**Comment by jbrock24** [comment]
@kaleb-himes Thanks for letting us know. I've changed the documentation to reflect, thanks!
