### ISSUE TITLE
pubExpMode random provides non-approved e values

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP#1460]
Technically, this is a duplicate of https://github.com/usnistgov/ACVP/issues/1116, which @celic marked as a duplicate of https://github.com/usnistgov/ACVP/issues/1061. However, I'd like to open the discussion again, and my request is more constrained than the other two issues.

For pubExpMode random, the server sometimes provides e values that are not approved. For example, for test session 429889, vector set 1781060, test group 25, I got an e value of "03". This is clearly not conformant to FIPS 186-4 and FIPS 186-5, which was pointed out in https://github.com/usnistgov/ACVP/issues/1116.

The ACVP server should not provide those values; it should only provide random values within the range specified by FIPS 186-4 and FIPS 186-5: "The exponent e shall be an odd, positive integer such that $2^{16} < e < 2^{256}$."

I currently don't care about any other constraints/ranges. Thus, this change shouldn't require a protocol update, simply a server update.

**Comment by jvdsn** [comment]
Any update on this?

**Comment by jbrock24** [comment]
Hi @jvdsn , currently working on it, will let you know soon.

**Comment by jbrock24** [comment]
Was able to track down the culprit behind this, the fix will go out with the next release. I'll post here when it's ready, thanks @jvdsn

**Comment by livebe01** [comment]
The fix for this is on Prod in release [v1.1.0.31](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.31).
