### ISSUE TITLE
SigGen and SigVer 186-5 modulo support

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#1463]
**Protocol Section**

https://github.com/usnistgov/ACVP/blob/master/src/rsa/sections/05-siggen-capabilities.adoc
https://github.com/usnistgov/ACVP/blob/master/src/rsa/sections/05-sigver-capabilities.adoc

**Protocol Question**
What is your question? 

Are FIPS 186-5 compliant sigGen and SigVer supposed to support a modulo up to 8192 ?

**Comment by jbrock24** [comment]
Hi @bfussell,

[Table 2: Security Strengths Supported by Commonly Used Modulus Lengths17](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Br2.pdf)

Within the above documentation, it does state that the strength you listed is a "Commonly Used Modulus Length", but ACVP doesn't currently support anything other than `{2048, 3072, 4096}`. I imagine it's a speed thing, but I will create a ticket in our system to discuss the reasoning for not going larger, and possible increase, at our next dev meeting.

Thanks for the post!

**Comment by jbrock24** [comment]
Hi @bfussell, 8192 is only for some KAS schemes, and it's too big for us to really do testing for RSA. It's not impossible to add, but at this time the benefit doesn't outweigh the extra time to take for testing.
