### ISSUE TITLE
RSA OAEP Decryption per SP800-56Br2

### ISSUE THREAD

**Issue by ckc505** [usnistgov/ACVP#1468]
**Protocol Question**
RSA OAEP Decryption per Section 7.2.2.4 of NIST SP 800-56Br2 does not seem to be testable. Since the understanding is that it is approved per 56Br2 we are trying to understand why it is not testable?

Currently the supported testing according to SP800-56Br2 only seems to be available for RSADP, KAS IFC SSC KAS1, KAS IFC SSC KAS2 and KAS KC.

**Comment by livebe01** [comment]
Hi @ckc505. Sure, RSA OAEP Decryption per Section 7.2.2.4 of NIST SP 800-56Br2 is testable via KTS IFC. See https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ifc.html.
