### ISSUE TITLE
HKDF fixed info 'L' field explicit size requirement

### ISSUE THREAD

**Issue by rnunez83** [usnistgov/ACVP#1470]
**Protocol Section**
In the ACVTS definition of HKDF, the definition of one of the fixed field parameters 'l', is specified as being required to be 4 bytes by ACVTS. It states in the Fixed Info Pattern Candidates description section: 
https://github.com/usnistgov/ACVP/blob/master/src/kas/sp800-56c/hkdf/sections/05-capabilities.adoc#fixedinfopatternconstruction

that for 'l' : "The length of the derived keying material in bits, **MUST be represented in 32 bits for ACVP testing**"

but RFC5869 makes no mention of this length requirement:
https://datatracker.ietf.org/doc/html/rfc5869

**Protocol Question**
What is your question?

We are working with a vendor who implements HKDF according to SPDM protocol. This protocol requires the 'l' value to be 2 Bytes and thus we would like to know whether they need to modify their test environment to support this or whether the CAVP could make this field size accept 2 Byte values.

**Comment by rnunez83** [comment]
> Hi @rnunez83, either approach will work. If they can modify their test environment, that would be the quickest for us. Otherwise, we can create custom vector sets for them (will require some coordination with us and some manual labor on our end).

@livebe01 , thanks for confirming it would be acceptable to modify the test environment to support a 4 byte 'L'. 

I would like to confirm that the approach would be acceptable for SP800-108 KDF as well? In the spec for kbkdf, there is a note: "The fixedData or fixed input data string that is used by the IUT is needed by the ACVP server to verify that the IUT correctly derived the keying material. The server does not validate the correct construction of the fixed input data string".

If the test vectors are modified to meet the test case, but the real implementation follows the protocol, is that acceptable?

**Comment by livebe01** [comment]
I'm not sure that I understand your question related to the kbkdf implementation. I think that with the kbkdf testing the IUT supplies the actual fixedData used. If that's the case, then I don't think it matters how many bits the IUT is using to represent L as long as it is actually including it in the fixedData as required by the SP.

**Comment by rnunez83** [comment]
hi @livebe01. can you confirm what the registration is supposed to include for the salt length registration?
in Table 2 of the capabilities.adoc, it says that the key should be "SaltLen**s**" and the value should be an integer array, but in test-vectors.adoc it has the key as "SaltLen" (without the 's). I tried to generate test vectors with the following registration, but the saltlength generated is not the length I specified.

  {
    "acvVersion":"1.0"
  },
  {
    "isSample":true,
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "algorithms":[
      {
        "revision":"Sp800-56Cr1",
        "algorithm":"KDA",
        "mode":"HKDF",
        "prereqVals":[
          {
            "algorithm":"HMAC",
            "valValue":"same"
          }
        ],
        "hmacAlg":[
          "SHA2-384"
        ],
        "z":[
          384
        ],
        "l":384,
        "macSaltMethods":[
          "default"
        ],
        "saltLens":[
          384
        ],
        "fixedInfoPattern":"l||uPartyInfo||vPartyInfo",
        "encoding":[
          "concatenation"
        ]
      }
    ]
  }


but the testvector.json generated shows the default salt length (1024):
        "tgId": 1,
        "testType": "AFT",
        "kdfConfiguration": {
          "kdfType": "hkdf",
          "l": 384,
          "saltLen": 1024,
          "saltMethod": "default",
          "fixedInfoPattern": "l||uPartyInfo||vPartyInfo",
          "fixedInfoEncoding": "concatenation",
          "hmacAlg": "SHA2-384"
        },
        "zLength": 384,
        "tests": [
          {
            "tcId": 1,
            "kdfParameter": {
              "kdfType": "hkdf",
              "salt": "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
