### ISSUE TITLE
A module's vendor and contact

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#1474]
My question is related to the relationship between a module's vendor and contacts.

I was under the assumption that if a module is assigned to a particular vendor, then it's contacts should also come from that vendor.  Is that the case?  By the same token, should a module's address also come from that vendor and only that vendor?

I ask because I've found modules in production where the contact of the module does not belong to the vendor of the module.

**Comment by rstaplesnist** [comment]
As far as what's considered the best practice, yes, they should come from the same vendor.  However, there's nothing enforcing any constraints along these lines on the server side, nor am I aware of any plans to add such constraints into code.

If there are existing cases of this that you wish to update, we we would encourage you to do so via the standard update process.  Or bring them to our attention in email at acvts-prod@nist.gov and we can investigate.
