### ISSUE TITLE
RSA SignaturePrimitive 2.0: Extra "signature" field in table

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1476]
Hello,

this table: https://pages.nist.gov/ACVP/draft-celi-acvp-rsa.html#section-8.10

Indicates that a "signature" should be included with test case data for signature primitive 2.0. However, it does not seem to be included (and would be probably, in my opinion, an odd inclusion). 

Thanks,
Andrew

**Comment by jbrock24** [comment]
Thanks @abkarcher, I'll take care of it.
