### ISSUE TITLE
RSA KeyGen B.3.5 

### ISSUE THREAD

**Issue by Ani11226** [usnistgov/ACVP#1484]
Hello,

For RSA KeyGen capabilities registration as follows: 
         {
            "algorithm":"RSA",
            "mode":"keyGen",
            "revision":"FIPS186-4",
            "prereqVals":[
               {
                  "algorithm":"DRBG",
                  "valValue":"1234"
               },
               {
                  "algorithm":"SHA",
                  "valValue":"5678"
               }
            ],
            "infoGeneratedByServer":true,
            "pubExpMode":"fixed",
		"fixedPubExp": "010001",
            "keyFormat":"standard",
            "capabilities":[
               {
                  "randPQ":"B.3.5",
                  "properties":[
                     {
                        "modulo":2048,
                        "hashAlg":[
                           "SHA2-512"
                        ],
                        "primeTest":[
                           "tblC3"
                        ]
                     }
                  ]
               }
            ]
         }
Our vendor would like for the above to be tested but the module at hand does not support the e/seed/bitlen/Xp Xq inputs that seem to be provided by default in the request vectors/files as a result of the selections made. The module does supports providing these as part of the response vectors. 
Could the CAVP please advise as to whether there is a workaround to this wherein these inputs can be suppressed?

**Comment by livebe01** [comment]
Hi @Ani11226, can you try toggling the value that you're using for `"infoGeneratedByServer"`, i.e., try using `"infoGeneratedByServer":false,` in your registration vs `"infoGeneratedByServer":true,` and let me know if that solves your issue?

**Comment by Ani11226** [comment]
Hello @livebe01, I tried toggling the value by using "infoGeneratedByServer":false, as well as "infoGeneratedByServer":true, in the registration file, it still gave the same issue and resulted in giving the same inputs for both in the request file. 
I am attaching the test session ID of the generated request vectors just so that it helps as reference: 473263 for true and 473258 for false

If you could please look into it and suggest any other alternative, then it will be really helpful.

**Comment by livebe01** [comment]
Hi @Ani11226, please try `"infoGeneratedByServer":false` in conjunction with `"isSample": false`. I allude to it in [this](https://github.com/usnistgov/ACVP/issues/1479#issuecomment-1881547648) comment (different ticket), but "isSample": true vs "isSample": false can sometimes produce different results... something to keep in mind for future troubleshooting

**Comment by livebe01** [comment]
Hi, can this ticket be closed?
