### ISSUE TITLE
ECDSA  PKV sample prompt 

### ISSUE THREAD

**Issue by ehanson7** [usnistgov/ACVP#1494]
Is it possible to validate ECDSA  PKV ?

**Comment by livebe01** [comment]
Hi @ehanson7, ACVTS supports the testing listed here: https://pages.nist.gov/ACVP/draft-fussell-acvp-ecdsa.html#name-supported-ecdsa-algorithms. 

I.e., 
ECDSA / keyGen / 1.0
ECDSA / keyVer / 1.0
ECDSA / sigGen / 1.0
ECDSA / sigVer / 1.0
ECDSA / keyGen / FIPS186-5
ECDSA / keyVer / FIPS186-5
ECDSA / sigGen / FIPS186-5
ECDSA / sigVer / FIPS186-5
DetECDSA / sigGen / FIPS186-5

See section 6 of FIPS 186-5.

**Comment by ehanson7** [comment]
Thank You,!
