### ISSUE TITLE
SHAKE - additional line "outLen" in expectedResults from Demo Server for each testcase

### ISSUE THREAD

**Issue by Karen32123** [usnistgov/ACVP#1512]
**Protocol Section**
[Is your question regarding a specific section of the protocol?  You can link it here.]

https://pages.nist.gov/ACVP/draft-celi-acvp-sha3.html#name-test-vector-responses

**Protocol Question**
For the Shake response vectors there is only an outLen specified in the resultsArray of the MCT tests according to the Protocol Section. However, when requesting result vectors from the demo server, there are additional "outLen" entries given for each testcase e.g. 

          {
            "tcId": 215,
            "md": "378CBF39235A278EA4A10D02137C6A50",
            "outLen": 128
          }
        ]
      },
      {
        "tgId": 2,
        "tests": [
          {
            "tcId": 216,
            **"outLen": 0,**
            "resultsArray": [
              {
                "md": (..) 3BF1AEEFC2E82F50F107D74B561EA8FAF678D8B26C437F4D5D081E39C611E4FCBD415A56E28B50FFB",
                _"outLen": 36608_
              }
The bold ones are the ones, that are not specified according to the protocol, the italic one is expected according to the protocol (since this is an MCT test).

On validation with the Demo or productive Server: would the test fail depending on whether we put the additional (bold) outLen lines or not? Or does it not matter, whether we put those there?

**Comment by jbrock24** [comment]
Hi @Karen32123, thanks for the feedback - I'll get to this by next week once we get caught up.

**Comment by jbrock24** [comment]
Hi @Karen32123, can you please perform this test again and provide the tsid/vsid for me. I'm having trouble reproducing this, and would like to provide a tested response rather than what it _should_ be. It _should_ be ignored by the JSON serializer, but I want to test that specifically.

Thanks.

**Comment by Karen32123** [comment]
Hello jbrock24,

in the meantime we have been able to successfully validate our results with the productive server, hence from my point of view, we could close this.

Thanks,
Karen
