### ISSUE TITLE
GMAC testing with same GCM parameters

### ISSUE THREAD

**Issue by sowndarraja** [usnistgov/ACVP#1519]
We would like to confirm, if testing AES-GMAC is needed if AES-GCM with zero payload is already tested with same parameters across both the algorithms.

**Comment by locksmithone** [comment]
I have heard that the acvp server automatically creates a GMAC test vector when GCM with zero payload is presented, but let's have the acvp team confirm.

**Comment by livebe01** [comment]
Yes, if you wish or need to have AES-GMAC on your certificate, then you will need to test it as well.

**Comment by sowndarraja** [comment]
Thanks, closing the issue.
