### ISSUE TITLE
DRBG nonce lengths

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP#1520]
According to #1432, the ACVP now supports DRBG capabilities with 0-length nonces, as long as the combination of entropy input+nonce is greater than 3/2 * security strength. 

However, the table on https://github.com/livebe01/ACVP/blob/master/src/drbg/sections/05-capabilities.adoc still lists a minimum value for the nonces of all derivation function-based DRBGs. Is the table outdated?

**Comment by livebe01** [comment]
Hi @jvdsn, [this](https://github.com/livebe01/ACVP/commit/aea1dd08d70b8ee739b1388a41c1b22abb86b634) is how I updated the documentation to address the change.

**Comment by jvdsn** [comment]
@livebe01 right, but that table still shows a minimum nonce length. Would it not be more accurate to set the minimum nonce length to 0 for all of them? Then the maximum entropy length would also need to be updated to support the case where entropy_input_len = 3/2*s and nonce_len = 0

**Comment by livebe01** [comment]
Hi @jvdsn, to confirm, are you referring to [Table 4](https://pages.nist.gov/ACVP/draft-vassilev-acvp-drbg.html#name-supported-drbg-values)?

**Comment by jvdsn** [comment]
@livebe01 correct

**Comment by jvdsn** [comment]
That looks reasonable to me

**Comment by livebe01** [comment]
Great, thank you. I do think that's more clear. If you have any other thoughts, let me know.
