### ISSUE TITLE
Query Available Vector Sets should provide more info

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP#1524]
It would be great if the response from the 'availablevectorsets' not only showed the number of vector sets available or 'unlimited', but also the expiration date of the unlimited vectors AND the number of non-expiring vector sets available.

the current response looks like this:
    {
      "acvVersion": "1.0"
    },
  
    {
      "available": "unlimited"
    }

where 'unlimited' is replaced by the actual number of vector sets if a specific count was purchased.

There are 2 problems with this:

1. in the case of 'unilmited', the expiration date and active fiscal year is not provided. 
2. if an unlimited purchase is made but the lab also has remaining non-expiring vector sets, the non-expiring vector sets are not shown.

a possible solution could be:

    {
      "acvVersion": "1.0"
    },
  
    {
      "available": [
           {"quantity": "unlimited", "fy": "2024", "expires": "2024-10-31"},
           {"quantity": "unlimited", "fy": "2025", "expires": "2025-10-31"},
           {"quantity": "175", "fy": null, "expires": "never"}
      ]
    }

with the above response, we would know that even if the 2025 vector sets expire, we would still have 175 vector sets available (possibly from a much earlier purchase of 500 vector sets) and could keep functioning.

**Comment by livebe01** [comment]
Thank you for the feedback @mmccarl. I see that Chris already gave it the thumbs-up! I'm going to close this out and add it to the internal system that we use to track feature requests.
