### ISSUE TITLE
Typo in 05-hmac-capabilities.adoc

### ISSUE THREAD

**Issue by torin-atsec** [usnistgov/ACVP#1532]
https://github.com/usnistgov/ACVP/blob/master/src/mac/sections/05-hmac-capabilities.adoc

In table 1, column "description" of row "prereqVals", prerequistie should be prerequisite.

**Comment by livebe01** [comment]
Thanks @torin-atsec. Done.

Ben



On Aug 20, 2024, at 4:56 PM, torin-atsec ***@***.***> wrote:



https://github.com/usnistgov/ACVP/blob/master/src/mac/sections/05-hmac-capabilities.adoc

In table 1, column "description" of row "prereqVals", prerequistie should be prerequisite.
