### ISSUE TITLE
ML-DSA and HashML-DSA signature tests

### ISSUE THREAD

**Issue by adrianogaibotti** [usnistgov/ACVP#1535]
**Protocol Section**
https://pages.nist.gov/ACVP/draft-celi-acvp-ml-dsa.html

**Protocol Question**
It is not clear for me if ACVP will cover the certification for ML-DSA and HashML-DSA signature generation/verification as specified in the final version of FIPS204 (Algorithms 2 to 5) (https://csrc.nist.gov/pubs/fips/204/final), or will the certification will be just for the "internal" functions (Algorithms 7 and 8). Looking at current protocol it seems that the second option is the one implemented.
Will these function be added in future versions of the protocol?

Best regards,
Adriano

**Comment by livebe01** [comment]
Our original intent was to only test Algorithms 7 and 8 and that's what we have implemented right now. See the bullets in [section 6.1](https://pages.nist.gov/ACVP/draft-celi-acvp-ml-dsa.html#name-test-types) of the ACVP ML-DSA spec. 

Based on feedback we've received, we do also plan to implement Algorithms 2 to 5. You can see some discussion related to this in the "_When will test vectors for FIPS 203-205 be published?_" thread of pqc-forum@list.nist.gov. We'd like to have this updated testing available in October.

-Ben

**Comment by adrianogaibotti** [comment]
Thank you for the prompt answer. I missed the note in section 6.1.
I close the issue.

Best regards,
Adriano
