### ISSUE TITLE
`UsesHybridSharedSecret: false` is treated as if UsesHybridSharedSecret was NULL

### ISSUE THREAD

**Issue by the-over-ape** [usnistgov/ACVP#1536]
We have the following error when submitting the below registration.json:

```
Failed to create test session: acvp: HTTP error [\r\n {\r\n \"acvVersion\": \"1.0\"\r\n },\r\n {\r\n \"error\": \"Validation error(s) on JSON payload.\",\r\n \"context\": [\r\n \"KDA-TwoStep-Sp800-56Cr2: The UsesHybridSharedSecret registration property is required for algo/mode/revision KDA_TwoStep_Sp800_56Cr2 testing, but was not provided.\"\r\n ]\r\n }\r\n]\n"}
```

This is the error we expect to get when we do not have the `UsesHybridSharedSecret` key in the file at all, where it is expected based on [this code](https://github.com/usnistgov/ACVP-Server/blob/65370b861b96efd30dfe0daae607bde26a78a5c8/gen-val/src/generation/src/NIST.CVP.ACVTS.Libraries.Generation/KDA/Sp800_56Cr2/TwoStep/ParameterValidator.cs#L268) and [this documentation](https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-kdf-twostep.html#name-property-registration)

We used very similar files last year for another device and `UsesHybridSharedSecret` was not yet required, probably the fix for [this issue](https://github.com/usnistgov/ACVP/issues/1377) had not made it to public facing servers.

-------------

registration.json:

```
[
	{
		"acvVersion": "1.0"
	},
	{
		"isSample": false,
        "publishable": true,
		"algorithms": [
			{
				"algorithm": "KDA",
				"capabilities": [
					{
						"counterLength": [
							8
						],
						"encoding": [
							"concatenation"
						],
						"fixedDataOrder": [
							"after fixed data"
						],
						"fixedInfoPattern": "uPartyInfo||vPartyInfo",
						"kdfMode": "feedback",
						"macMode": [
							"HMAC-SHA2-256"
						],
						"macSaltMethods": [
							"random",
							"default"
						],
						"requiresEmptyIv": true,
						"supportedLengths": [
							{
								"increment": 64,
								"max": 1024,
								"min": 128
							}
						],
						"supportsEmptyIv": true
					}
				],
				"l": 1024,
				"mode": "TwoStep",
                "UsesHybridSharedSecret": false,
				"revision": "Sp800-56Cr2",
				"z": [
					256,
					384
				]
			}
		]
	}
]
```

**Comment by woodbe** [comment]
+1, we are seeing this issue as well. Last year the same settings (minus the UsesHybridSharedSecret) worked just fine, but this year trying to use it will not accept. We need to either change to Sp800-56Cr1 or set the UsesHybridSharedSecret to true (which then of course asks for more unsupported parameters).

**Comment by livebe01** [comment]
closing as a duplicate
