### ISSUE TITLE
Legacy curves in ECDSA 186-5

### ISSUE THREAD

**Issue by aryeharcher** [usnistgov/ACVP#1537]
ACVP does not list P-192, B-163, or K-163 as supported for keyver or sigver under FIPS 186-5. Ref:
https://pages.nist.gov/ACVP/draft-fussell-acvp-ecdsa.html#name-the-keyver-mode-capabilitie
https://pages.nist.gov/ACVP/draft-fussell-acvp-ecdsa.html#name-sigver-capabilities-for-revi

However, these curves are included in SP 800-186 (https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-186.pdf) - see sections 3.2.1.1, 3.3.1.1 and 3.3.2.1 . The section for each of these curves indicates "This curve is for legacy-use only. See FIPS 186-4 for the specification." 
We believe this inclusion indicates that these curves are approved for legacy verification under FIPS 186-5.

Can you please add verification for these curves to FIPS 186-5 testing or clarify why they should not be included in 186-5?

For context, we are attempting to meet the 186-5 requirements for new CAVP testing from the recently revised additional comment 2 in IG C.K (Transition from FIPS 186-4 to FIPS 186-5 and SP 800-186):
"For FIPS 186-4 CAVP tests that are mathematically identical to FIPS 186-5 CAVP tests, a module may claim FIPS 186-5 compliance for these tests. As of the Last Modified Date of this IG, this allowance is applicable to all FIPS 186-4 tests that are also part of the FIPS 186-5 tests (e.g., tests other than DSA and RSA X9.31 FIPS 186-4 tests). However, if new CAVP testing is required for a module (e.g., code changes were made within the algorithm executable per CAVP FAQ GEN.9, or to test the algorithms on a new OE) then these new CAVP tests shall be the FIPS 186-5 CAVP tests and cannot be the FIPS 186-4 tests."

**Comment by livebe01** [comment]
Hi @aryeharcher. I can see where you're coming from.

The approach we took was to limit the scope of ECDSA sigVer FIPS186-5 and ECDSA keyVer FIPS186-5 testing to verifying signatures and keys that were generated per FIPS186-5. FIPS186-5 does not allow Implementations to generate P-192, B-163, and K-163 keys and signatures and so we do not support P-192, B-163, and K-163 for FIPS186-5 sigVer and keyVer. 

To test P-192, B-163, and K-163, use the ECDSA 1.0/FIPS186-4 sigVer and keyVer testing.

We could have implemented this differently, but this was what made the most sense to us at the time. You can see how we've broken things up better if you look at the RSA spec. There you will see the sigVer testing is broken out into FIPS186-2, FIPS186-4 and FIPS186-5.

The CMVP is aware of how we've structured the testing and we've communicated with them regarding what older tests they need to accept.

**Comment by aryeharcher** [comment]
Acknowledged, thanks for taking a look.
