### ISSUE TITLE
Generating test vectors gets error: macOptions contained no registered MAC algorithms

### ISSUE THREAD

**Issue by chih-kao** [usnistgov/ACVP#1546]
I ran the examples from
https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ifc.html#name-example-kas-ifc-registratio
https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ifc.html#name-example-kts-ifc-registratio
, and getting the following messages:

KAS-IFC-Sp800-56Br2: macOptions contained no registered MAC algorithms.
KTS-IFC-Sp800-56Br2: macOptions contained no registered MAC algorithms.

**Comment by jbrock24** [comment]
Issue covered with #@1544
