### ISSUE TITLE
Generating test vectors gets error: KDA-TwoStep-Sp800-56Cr1: Provided L value of 2048 was not contained within the SupportedLengths domain

### ISSUE THREAD

**Issue by chih-kao** [usnistgov/ACVP#1547]
I ran the examples from
https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-kdf-twostep.html#name-registration-example
, and getting the following message:

KDA-TwoStep-Sp800-56Cr1: Provided L value of 2048 was not contained within the SupportedLengths domain.

**Comment by jbrock24** [comment]
Issue covered with #1544
