### ISSUE TITLE
[Potential]  Symmetric spec - break out "grouped" property tables into individual own sections

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#166]
The symmetric spec has numerous tables where all properties for every algorithm are listed in the same table.  As more algorithms are added and refined in the spec, with a single table for "testGroup" information (as an example) it is becoming increasingly difficult to filter out which pieces belong to one algorithm over another.

It may be beneficial to separate out into new sections, each individual algorithm, at least where the algorithm's properties differ from the norm.

Group examples (as far as broken out in the spec is concerned):

* Symmetric
  * AES-ECB
  * AES-CBC / AES-OFB / AES-CFB1 / AES-CFB8 / AES-CFB128
  * AES-XTS
  * TDES-ECB
  * TDES-CBC / TDES-CBC-I / TDES-CFB1 / TDES-CFB8 / TDES-CFB64 / TDES-CFB-P1 / TDES-CFB-P8 / TDES-CFB-P64 / TDES-OFB / TDES-OFB-I

* Symmetric Authenticated
  * AES-KW / AES-KWP
  * TDES-KW
  * AES-GCM
  * AES-XPN
  * AES-CCM
  
etc.

If they are broken out in groups as each bullet indicates, we can specify more clearly which properties belong to which modes, and how the corresponding JSON differs for each as well.

Thoughts?

**Comment by atvassilev** [comment]
This issue will have to wait for now - putting it in the "Far horizons" milestone until we decide how to prioritize it.

**Comment by celic** [comment]
I think this was tackled in the recent Symmetric spec changes.
