### ISSUE TITLE
RSA Support for CRT Representation of Private Key

### ISSUE THREAD

**Issue by celic** [usnistgov/ACVP#168]
Instead of `p`, `q`, `e`, `d`, `n`, we need to be able to support...

`p`, `q`, `e`, `dmp1`, `dmq1`, `iqmp`, `n` for faster decryption actions.

Where 
* `dmp1 = d mod (p-1)`
* `dmq1 = d mod (q-1)`
* `iqmp = q^-1 mod p`

**Comment by atvassilev** [comment]
I get the need to support CRT representations on the server to speed up processing. However, if I understand your request correctly, enforcing this would mean we will mandate CRT for any RSA implementation that wants to get validated. Would this be OK with the industry at large?

**Comment by celic** [comment]
Oh sorry for the confusion. I mean the server (and protocol) should be able to support both options. CRT and the standard format.

**Comment by celic** [comment]
#169
