### ISSUE TITLE
mac spec keyLen

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#174]
I noticed that for the mac spec, we're using `keyLen` somewhat inconsistently.

`keyLen` for HMAC is good - we're specifying the bits in the key
`keyLen` for CMAC-AES* does not have any json sample, but assuming would be either 128, 192, or 256.
`keyLen` for CMAC-TDES is (seemingly) being used as the equivalent of "number of keys". In the TDES spec, keyingOption was used to indicate the keys used.  keyingOption 1 = 3 distinct keys, keyingOption 2 = 2 distinct keys, keying option 3 = 1 single key.

Should something similar be done in the mac spec?  Perhaps specify a `keyingOption` property that is valid only for TDES CMAC?  Another option would be to use `CMAC-TDES-keyOption3` and `CMAC-TDES-keyOption2` (or similar) to signify different key options within the registration.  Note for CMAC the `keyLen` will always be the same, it's simply the option that may vary.

**Comment by bfussell** [comment]
I'd vote for the TDES section should be consistent with what the TDES spec uses, ie keyingOption.

**Comment by Kritner** [comment]
@pavelgutin is currently working on CMAC-TDES, it may make sense to have him handle this issue while working on the crypto and gen/vals.  He is not currently selectable on assignee's list, and I'm not sure what controls this, perhaps needs to be added as a contributor?

**Comment by bfussell** [comment]
Yes, he needs to be added as a contributor to https://github.com/usnistgov/ACVP
which I thought was controlled by Apostol. I don’t see a collaborators option in
my settings so I don’t think I can add someone.

Barry
