### ISSUE TITLE
field name proliferation in RSA sub spec...

### ISSUE THREAD

**Issue by sam1689** [usnistgov/ACVP#177]
We've made a lot of progress in trying to simplify our specs and I'd like to offer a suggestion that I think will make supporting ACVP simpler in the long run and ease the coding burden on clients and servers...

In master/src/acvp_sub_rsa.xml right now we have need to specify the following fields that are used in the registration of capabilities and in the test vectors:

modulo
hashAlg
saltLen

The values of these fields or arrays are consistent but the field names themselves have grown to the following list:

modulo
modRSA
modRSASigGen
modRSASigVer
modKeyGen
modLegacySigGen
hashAlg
hashSigGen
hashSigVer
hashLegacySigVer
saltLen
saltSigGen
saltSigVer
saltLegacySigVer

I would vote that we revert all these various field names back to one of the three as appropriate - either "modulo", "hashAlg", or "saltLen" ...  I can't think of a good justification for 14 field names that could be easily covered with 3...

This will simplify the RSA sub spec, make it easier to maintain, and ease the technical burden on implementors going forward.

I will adjust the src files if we can agree on the field names?

**Comment by atvassilev** [comment]
@sam1689 , this is a good catch and I see the need to clean this up, given that some of these fields are not even used after definition.  Most of this mess is my fault, having started from the original definitions in CAVS, but now is a good time to refactor the spec and make it simpler.

**Comment by atvassilev** [comment]
Forgot to add, I am fine with the three names proposed.

**Comment by celic** [comment]
Yes I agree and can fix this when I start on RSA SigGen for the server. My intention was to go through and look at something similar as I started on each of the parts of RSA. I have completed the check for KeyGen which cleaned up some of this but with the other two modes left, it wasn't very apparent. I'll just do the rest altogether when I pick up RSA SigGen.

**Comment by celic** [comment]
Fixed with #182
