### ISSUE TITLE
Minor inconsistency in the mac spec

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#178]
I noticed that in the mac spec, the key size range which is specified as an array is labeled "keyRange1" and "keyRange2" in Table 2, but then is labeled "keySize1" and "keySize2" in the examples at the bottom of the doc.

Hoping we can choose one and get that resolved!

**Comment by Kritner** [comment]
Addressed in https://github.com/usnistgov/ACVP/commit/219e39c833a12a8c27ca81d62a3684cd2e3dcced
