### ISSUE TITLE
DSA PQGGen request information question

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#179]
Looking at the DSA2VS spec(http://csrc.nist.gov/groups/STM/cavp/documents/dss2/dsa2vs.pdf) there
appears to be an option which allows the domain_parameter_seed to be passed to the DUT as
firstseed || pseed || qseed, see section 6.2.  I’ve never seen that from CAVS, is that still a viable
way to send that information ?

I’d prefer to have a single way which is to provide the entire seed in one parameter.
Comments ?

**Comment by atvassilev** [comment]
If you select PQG Gen for DSA2 in CAVS with for example 'Provable Primes p and q" and 'Canonical Generation of g"  then CAVS passes in the  .req file the explicit values of firstseed, pseed and qseed. These values are needed for the validation of the primes values p and q generation.  The algorithm in A.1.2.2. in FIPS 186-4 uses these explicit values to validate the prime generation.

However, these explicit distinct values do not appear to be necessary for the generation and validation of the generator g. The three seeds are output from the p and q generation routines and I think all of them can be provided as one parameter for the purposes of the generator g.

**Comment by bfussell** [comment]
DSA doc has been updated to reflect this #180
