### ISSUE TITLE
Key wrap registration and response keywords

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#184]
Trying to finish up AES/TDES keywrap and had a few questions on the implementation. Also was
planning to add examples to the doc since we don't have those yet.

I assume, unlike CAVS, we will use "key", "ct" and "pt" for the test case request/response information just like the other symmetric algorithms. CAVS used K, C and P.

I also assume we need a capability to indicate whether we support padding or not for AES.
If the server has implemented that, what keyword and values are you looking for ?

For decrypt operations there can be a failure. Are we using the same response format that
is defined for GCM, ie "decryptFail": true ?

Thanks !

**Comment by Kritner** [comment]
I'm coming at this from the gen/val perspective, so the driver perspective may differ slightly, but my thoughts...

> I assume, unlike CAVS, we will use "key", "ct" and "pt" for the test case request/response information just like the other symmetric algorithms. CAVS used K, C and P.

I would say the the most part yes, though I have a similar question as it applies to TDES keywrapping.
With the TDES algo itself, the keys were separated between key1, key2, and key3.  Do we want to do the same for TDES-KW?  While doing it this way would keep it consistent with TDES, it will make it inconsistent with AES-KW.

I see the options as:

Option 1 -----

TDES:
```
key1 : "",
key2 : "",
key3 : ""
```

AES:
```
key: ""
```

TDES-KW
```
key1 : "",
key2 : "",
key3 : ""
```

AES-KW, AES-KWP
```
key: ""
```

Option 2

TDES:
```
key1 : "",
key2 : "",
key3 : ""
```

AES:
```
key: ""
```

TDES-KW, AES-KW, AES-KWP
```
key : ""
```

> I also assume we need a capability to indicate whether we support padding or not for AES.
If the server has implemented that, what keyword and values are you looking for ?

The spec had the difference between AES and AES w/ Padding as a change in the registration:

`AES-KW` vs `AES-KWP` for the algo.

> For decrypt operations there can be a failure. Are we using the same response format that
is defined for GCM, ie "decryptFail": true ?

Correct

**Comment by bfussell** [comment]
Right, I found the AES-KWP after looking a bit closer.

I guess I'm on the other side of the options you listed since we use the same processing
for AES/TDES as we do AES-KW, AES-KWP and TDES-KW.

Thanks
