### ISSUE TITLE
 Access to ACVP demo server, demo.acvts.nist.gov

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#191]
Hi, 

We are working on implementing ACVP for the Bouncy Castle FIPS API.

Would you advise me on the process to either obtain a peer certificate or have  Crypto Workshop or BouncyCastle CA added to the list of accepted CAs for the demo server please.

I have previously emailed 'algotest@nist.gov' with the same request.

Thanking you in advance.

**Comment by bfussell** [comment]
Harold Booth @hbooth is the contact that handles certificate requests.  I thought I saw you two exchange
emails on this previously, but maybe it just your request.

Booth, Harold (Fed) <harold.booth@nist.gov>

**Comment by hbooth** [comment]
@mwcw please send me an email and I will handle it. I did not see the email to algotest@nist.gov, but if you are not a member of the list it is in a holding bin waiting for approval and the only person who can approve those messages is on vacation until next week.
