### ISSUE TITLE
Group Structures in Results Files

### ISSUE THREAD

**Issue by celic** [usnistgov/ACVP#197]
From the discussion on 10/5... RSA SigGen involves the server generating a bunch of messages inside of test cases for each group that are passed to the client. The client generates a single key pair for each group, signs the message, and passes along the public key with the signature in the results file.

In the current specification, the public key information is duplicated for each test case because the results file has no concept of a group of test cases. All test cases within the test vector set are flattened down to a single array instead of how they are presented in the prompt as single array per group. 

Should the results file preserve the same group structure the prompt outlines, or is the work-around of duplicating the group information inside each test case sufficient?

As a note, this same problem appears in DSA KeyGen and SigGen. It is likely to appear in ECC (not sure yet) and perhaps in algorithms that utilize signature primitives.

**Comment by atvassilev** [comment]
In my view the answer to how to handle this issue depends on the nature of the SigGen test. If the test expects a single RSA key to be used in all test cases then there is no need to repeat the public exponent and modulus for each test case. If the test envisions different keys to be used, then it would make sense to have the e and n components specified in each case. 

It appears that currently this test uses are single test so I would be in favor of grouping test results for a single key.

**Comment by celic** [comment]
This will be completed as a part of the v0.5 release.

**Comment by celic** [comment]
The associated spec updates will be done later and likely involve some other things.
