### ISSUE TITLE
Put ACVP draft in repo

### ISSUE THREAD

**Issue by jfigus** [usnistgov/ACVP#2]
Should we commit the current ACVP draft into this repo?  I've started a sub-specification to define the JSON for symmetric ciphers.  But the main ACVP draft isn't in the repo.  Do we want to convert the main spec to RFC form first?

**Comment by atvassilev** [comment]
I would say let's commit the ACVP in its current form and then convert to RFC format. Granted, the current draft is a word document and may not be handled nicely by svn but still, this is the start.

**Comment by jfigus** [comment]
The v0.2 ACVP spec has been add to the repo in 52b6a05e81117bc32a9c4bc9c13d03df57e9a262.
