### ISSUE TITLE
Consistency Issues within symmetric ciphers

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#207]
Need to make AES-CFB1 work like TDES-CFB1 since the pt/ct format is completely different.
Need to make all symmetric ciphers use dataLength in capabilities to be consistent.

**Comment by elliemdaw** [comment]
For reference, here are the names for the field and the corresponding modes.
"ptLen" = AES-GCM, CCM, KW
"dataLen" = AES-ECB, CBC, CFB, OFB
"dataLength" = AES-CTR

**Comment by elliemdaw** [comment]
Oh, and I believe all TDES use "ptLen"

**Comment by celic** [comment]
SHA also uses "messageLen" (or something similar). It could also be brought in line.

**Comment by smuellerDD** [comment]
The JSON structures are intended to be processed automatically. To ensure simple code, a particular keyword should not have multiple data types.

For example, ptLen is defined as an array, but it can also be a range for CCM. If it is really needed to define a range, can you please define a different keyword? This should keep the code simple and clean without too many conditionals.

Further, I feel that a range can be equally be represented by an array. Thus, may I propose to disregard the definition of a range entirely?

**Comment by smuellerDD** [comment]
In the specification for symmetric ciphers, ivLen is defined as an array in section 2.2 and as a range in 2.3 for CCM. Which data type should it be?

**Comment by smuellerDD** [comment]
The ACVP protocol defines the keyword "cpe" without seemingly defining what shall be communicated with this keyword. Can you please elaborate?

**Comment by smuellerDD** [comment]
The ACVP protocol defines the keyword "features" which seems to be some kind of flags type. If so, which particular values are allowed?

If it is a free-form data field, please add that hint to the documentation.

**Comment by smuellerDD** [comment]
The ACVP protocol specifies the use of dependencies. However, from the protocol definition it is not fully clear for which ciphers dependencies must be defined. Could you please elaborate?

**Comment by smuellerDD** [comment]
What is the data type of the vsID and accessToken fields? Is vsID a 32bit integer? Is the accessToken a string?

**Comment by smuellerDD** [comment]
The ACVP protocol spec refers to HTTP/1.2 in the POST header. However, I am unaware of a HTTP/1.2 value. HTTP seemingly is only defined for 1.0, 1.1 or 2. Could you please elaborate what the value HTTP/1.2 shall indicate?

**Comment by smuellerDD** [comment]
The ACVP protocol specification section 4.1 has a different URL specified than used in the example of section 4.2. I guess the example in 4.2 would need to be updated.

**Comment by smuellerDD** [comment]
The DRBG specification defines the range type in table 3 for various keywords. However, the examples in appendix A seem to define an array. Which data type is the correct one?

**Comment by smuellerDD** [comment]
The DRBG specification requires in table 3 that the personalization string minimum must be equal to the security strength of the DRBG without being optional. SP800-90A, however defines the personalization string as optional.

**Comment by smuellerDD** [comment]
The DRBG specification requires in table 3 that the additional information string minimum must be equal to the security strength of the DRBG without being optional. SP800-90A, however defines the additional information string as optional.

**Comment by atvassilev** [comment]
@smuellerDD, the DRBG spec in the fourth column "Valid values" of Table 3 says for Additional Input and Perso String "Set all to zero (0) if not supported". So, these parameters are still optional, only this is specified differently.

**Comment by smuellerDD** [comment]
Thanks for pointing the additional input and perso string nuance out. Please disregard the two comments then.

**Comment by smuellerDD** [comment]
The prerequisite definition for the symmetric ciphers differs from the DRBG prerequisites. May I ask to consolidate them to have one data type?

**Comment by celic** [comment]
Hi. It's been a while since we've had someone go through some of these specs with such detail. I don't want to discourage you from doing this at all. It's plenty helpful in the long run. Unfortunately, making so many comments on so many different topics on a single GitHub issue doesn't promote the level of discussion or detail we'd like on these issues. At your discretion, you are welcome to submit multiple new issues with these questions/requests. That helps keep some of the discussion on the single topic, and helps us address the issues with the changes relevant. As commits and pull requests are made on the repository, they can reference those individual issues to help determine if they solve the problem.

Thanks for the feedback!

**Comment by atvassilev** [comment]
I think @smuellerDD was following an earlier suggestion to post inconsistencies under #207. However, @celic makes a great point about the usefulness of having finer-grain separation of issues that can be tracked separately.

**Comment by smuellerDD** [comment]
Ok, I will post new items separately.

**Comment by atvassilev** [comment]
Re-prioritizing for v0.5

**Comment by celic** [comment]
I think these consistencies were resolved with the recent Symmetric Spec updates.

**Comment by smuellerDD** [comment]
I thought you wanted to replace „i“ with iv or tweak?

**Comment by smuellerDD** [comment]
Sorry, mixup: The test vectors still use SHA-224 instead of SHA2-224, for example.
