### ISSUE TITLE
CMAC KeyLen parsing issue

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#208]
When registering CMAC:

If "keyLen" is left out, we can an error that the field is missing. When included, the following error is given:

"Incorrectly formatted JSON (95:28): maximum number of values exceeed for field: macLen”

**Comment by Kritner** [comment]
Hey @elliemdaw, assuming this is related to the registration that hit the email group:

(snippet)
```
	"capabilityExchange": {
		"algorithms": [{
				"algorithm": "CMAC-AES-128",
				"prereqVals": [{
					"algorithm": "AES",
					"valValue": "same"
				}],
				"direction": [
					"gen",
					"ver"
				],
				"msgLen": [
					1024,
					0,
					2048,
					0,
					0
				],
				"macLen": [
					64,
					256
				],
				"keyLen": [
					128
				]
			},
			{
				"algorithm": "CMAC-TDES",
				"prereqVals": [{
					"algorithm": "AES",
					"valValue": "same"
				}],
				"direction": [
					"gen",
					"ver"
				],
				"msgLen": [
					1024,
					0,
					2048,
					0,
					0
				],
				"macLen": [
					64,
					256
				],
				"keyLen": [
					128
				]
			}
		]
	}
```

A few things:
* The `algorithm` should actually just be “CMAC-AES”, the lengths are specified in the `keyLen` array property. There was a PR #204 that changed a bit on how the CMAC registration for AES was handled.  This change is not yet reflected within the JSON above or within the driver - we have a ticket in on our end to have the driver end updated for CMAC-AES hopefully within the next few days.
* `macLen` for both AES and TDES exceeds the valid maximum for `macLen` for those algos, should be at a max the block size (so 128 for AES, 64 for TDES)
* `keyLen` doesn’t apply to CMAC-TDES, but `keyingOption` does, and is a required field. 
    * Looking at the specification, this field is in the sample JSON, but is not depicted in the description of the fields, I can apply this update in a PR
* `msgLen` provided values look a bit strange, I’m guessing that the 0s are to equate to how CAVS currently takes input for message lengths?  Would you be able to utilize the “Domain Object” for this sort of registration as described at: http://htmlpreview.github.io/?https://github.com/USNistGov/ACVP/blob/master/artifacts/acvp_protocol.html#rfc.section.14.3 ?

I believe CMAC-TDES is in a state that could be tested (once the issues with the registration are corrected), but CMAC-AES has a small change needed on our side.  Will keep this issue updated as updates come along.

**Comment by elliemdaw** [comment]
Great, thanks for the updates @Kritner!

**Comment by elliemdaw** [comment]
@Kritner CMAC-TDES works as expected. I'll look out for updates on CMAC-AES. Thanks for your help!

**Comment by Kritner** [comment]
@elliemdaw No problem!

**Comment by Kritner** [comment]
@elliemdaw a change has been pushed out to demo related to CMAC-AES - should be good for you to start hitting that algo with the registration changes mentioned above.

**Comment by elliemdaw** [comment]
@Kritner thank you!

**Comment by celic** [comment]
Has this been resolved?

**Comment by elliemdaw** [comment]
@celic yes, I haven't run into any issues with the registration parsing for CMAC!

**Comment by celic** [comment]
Awesome.
