### ISSUE TITLE
Consistency for optional vs required parameters

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#209]
If a field is listed as optional in the spec, it would make sense for the registration to be successful without it being included.

**Comment by Kritner** [comment]
Copying from #210, as I think it is directly related to this issue:

> I'm not sure for properties that are used for only certain algorithms, if it makes sense to say "Optional: No (Required for CMAC-TDES)", or "Optional: Yes (Required for CMAC-TDES)". The idea that I'm attempting to convey is, the property is required for CMAC-TDES, but not relevant for other MAC modes like CMAC-AES and HMAC*

> Perhaps some of the confusion could be alleviated by further breaking out specifications, but am curious what makes the most sense to others.

**Comment by atvassilev** [comment]
It seems this issue was fixed with PR #210.
