### ISSUE TITLE
CTR mode request: expected field name was not provided: dataLength

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#215]
The server replied the following when registering a CTR test
```
{
  "acv_version" : "0.4",
  "error" : "Incorrectly formatted JSON (151:10): expected field name was not provided: dataLength"
}
```
The submitted request compliant to theversion 0.4 protocol definition: (note, there is a dataLen in the acvp_sub_symmetric.html but not in the acvp_sub_symmetric.txt, but the HTML file specifies version 0.3.
```
{
          "algorithm":"AES-CTR",
          "direction":[
            "encrypt",
            "decrypt"
          ],
          "keyLen":[
            128,
            192,
            256
          ],
          "ptLen":[
            128,
            256,
            512,
            1024
          ],
          "ivLen":[
            128
          ],
          "ctrSource":"external"
        },
```

**Comment by elliemdaw** [comment]
AES-CTR expects "dataLength" in place of "ptLen"... issue #207 has a list of what each mode currently parses in the meantime :)

**Comment by smuellerDD** [comment]
Am Montag, 26. Februar 2018, 16:32:07 CET schrieb Ellie Marie:

Hi Ellie,

> AES-CTR expects "dataLength" in place of "ptLen"... issue #207 has a list of
> what each mode currently parses in the meantime :)

Thanks -- can we expect that it is made consistent before the public release?

Besides, there are other areas of seemingly JSON inconsistencies, where can 
that be reported and discussed?

Ciao
Stephan

**Comment by bfussell** [comment]
There is already an issue opened on this inconsistency.  If you find others please feel
free to include them here:

https://github.com/usnistgov/ACVP/issues/207

**Comment by atvassilev** [comment]
I think this issue has been captured in #207. Closing.
