### ISSUE TITLE
Multiple prerequisite definitions

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#216]
The prerequisite definition for the symmetric ciphers differs from the DRBG prerequisites. May I ask to consolidate them to have one data type?

**Comment by celic** [comment]
I believe this is being considered for v0.5. @hbooth might have more information on that, but our focus for the next few weeks are solidifying v0.4.

**Comment by smuellerDD** [comment]
As NIST asked folks to start testing the code and potentially start implementing their own support code, the JSON data definitions should become stable now.

Note, the transition period of one year from the old to the new CAVS is quite short.

**Comment by hbooth** [comment]
Everything is currently a work in progress. While some parts are more stable than others, we recognize that certain things must change prior to finalizing in order to support a functioning program. We are encouraging early engagement and developing all of this in a collaborative manner to allow early feedback to be sure everyone will be familiar with this process. We do appreciate any feedback we receive and will work to address comments where we can.
The current plan is to have the JSON stable and complete with basic documentation sometime this June and finalizing the documentation late summer of 2018.

**Comment by smuellerDD** [comment]
Are you saying that work by vendors or labs to integrate with actual modules at this stage does not make sense? If so, then I would be silent until more stable definitions are available. Note, I solely base my work on the specs.

When you say that some specs are more mature than others, is it possible to indicate which specs are kind of stable?

**Comment by atvassilev** [comment]
@smuellerDD, no, we are not saying this. We are working with willing partners to develop the technology in an iterative manner, going forth and back between specifications and actual implementations, progressing by one algorithm at a time. An example of this progress is the list of supported algorithms in the Readme, for the project which have been tested with the libacvp tool by Cisco. It is possible that at some stages there will be discrepancies between the specs and the actual implementations. This is regrettable but inevitable given the scope and pace of this project.  

We have ideas for how to improve on both ends: the specifications and the implementations. The majority of these improvements are necessary for the official release of the technology and the roll-out of the new validation program. I have published milestones for the project that should help to identify the major stages we see the project evolving through. They may help you determine when you want to engage. 

In any case, as many of my colleagues have stated, we appreciate your feedback on the specs.

**Comment by atvassilev** [comment]
@smuellerDD, we looked carefully at the prereq requirements for symmetric and DRBG and could not see any content differences. The only possible differences may just be formatting issues of the presentation. I am closing this issue but can reopen it if you can provide a specific example of the discrepancy you see.
