### ISSUE TITLE
Symmetric ciphers: do not use multiple data types for one keyword

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#222]
The JSON structures are intended to be processed automatically. To ensure simple code, a particular keyword should not have multiple data types.

For example, ptLen is defined as an array, but it can also be a range for CCM. If it is really needed to define a range, can you please define a different keyword? This should keep the code simple and clean without too many conditionals.

Further, I feel that a range can be equally be represented by an array. Thus, may I propose to disregard the definition of a range entirely?

**Comment by Kritner** [comment]
There is some inconsistency in when using `Array`, `Range` and `Domain`, I believe in most cases the specs should specify `Domain` when a series of valid numeric values is expected.

As described at http://htmlpreview.github.io/?https://github.com/USNistGov/ACVP/blob/master/artifacts/acvp_protocol.html#rfc.section.14.3, the domain can be used to specify literal values, and/or a range of values.  The intention is to give flexibility on the client end, allowing them to either register using a handful of literal values, or the entire range their algorithm implementation supports.

This response seems to apply to multiple recently opened issues: #207, #217 , #221, and #223

**Comment by smuellerDD** [comment]
Am Dienstag, 27. Februar 2018, 15:54:03 CET schrieb Russ Hammett:

Hi Russ,

> There is some inconsistency in when using `Array`, `Range` and `Domain`, I
> believe in most cases the specs should specify `Domain` when a series of
> valid numeric values is expected.
> 
> As described at
> http://htmlpreview.github.io/?https://github.com/USNistGov/ACVP/blob/master
> /artifacts/acvp_protocol.html#rfc.section.14.3, the domain can be used to
> specify literal values, and/or a range of values.  The intention is to give
> flexibility on the client end, allowing them to either register using a
> handful of literal values, or the entire range their algorithm
> implementation supports.
> 
> This response seems to apply to multiple recently opened issues: #207, #217
> , #221, and #223

Thanks for the clarification. But in order to close those items, could you 
please indicate which of the issues use the domain specification and which do 
not?


Ciao
Stephan

**Comment by Kritner** [comment]
I believe this spec discprepancy has been addressed in #225.  If not, feel free to update.
