### ISSUE TITLE
HTTP 401: JWT was not provided

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#226]
The server responded with the following answer on my register request:

[{"acvVersion":"0.4"},{"capabilityResponse":{"vectorSets":[{"vsId":455},{"vsId":456},{"vsId":457},{"vsId":458},{"vsId":459}]},"testSession":{"testId":26},"accessToken":"eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJlNDJiMGU1OC04MGMwLTQ0NzktODZlZS04M2M2MDliYTU0ZDIiLCJpYXQiOjE1MTk4ODgzODQsInN1YiI6IkVNQUlMQUREUkVTUz1zbXVlbGxlckBhdHNlYy5jb20sIENOPVN0ZXBoYW4gTXVlbGxlciwgT1U9QUNWUCBEZXZlbG9wbWVudCwgTz1hdHNlYyBpbmZvcm1hdGlvbiBzZWN1cml0eSBjb3JwLCBMPUF1c3RpbiwgU1Q9VGV4YXMsIEM9VVMiLCJpc3MiOiJOSVNUIEFDVlRTIiwidGVzdFNlc3Npb25JZCI6IjI2IiwiZXhwIjoxNTIwMTQ3NTg0fQ.UbOTBwkwc7IwU-FB0v285OQ2p2OxGHA0n0IeEj0r7Y8"}]

I followed up with the following GET resuest:

GET //acvp/validation/acvp/vectors?vsId=455 HTTP/1.1
Host: demo.acvts.nist.gov
User-Agent: ACVPRetriever/0.0.1
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJlNDJiMGU1OC04MGMwLTQ0NzktODZlZS04M2M2MDliYTU0ZDIiLCJpYXQiOjE1MTk4ODgzODQsInN1YiI6IkVNQUlMQUREUkVTUz1zbXVlbGxlckBhdHNlYy5jb20sIENOPVN0ZXBoYW4gTXVlbGxlciwgT1U9QUNWUCBEZXZlbG9wbWVudCwgTz1hdHNlYyBpbmZvcm1hdGlvbiBzZWN1cml0eSBjb3JwLCBMPUF1c3RpbiwgU1Q9VGV4YXMsIEM9VVMiLCJpc3MiOiJOSVNUIEFDVlRTIiwidGVzdFNlc3Npb25JZCI6IjI2IiwiZXhwIjoxNTIwMTQ3NTg0fQ.UbOTBwkwc7IwU-FB0v285OQ2p2OxGHA0n0IeEj0r7Y8

I.e. the request contains the JWT auth token.

The server replies:

< HTTP/1.1 401 Unauthorized
< Server: Apache-Coyote/1.1
< Pragma: No-cache
< Cache-Control: no-cache
< Expires: Wed, 31 Dec 1969 19:00:00 EST
< Content-Type: application/json;charset=ISO-8859-1
< Content-Length: 67
< Date: Thu, 01 Mar 2018 07:13:07 GMT
<
CAVS driver - Debug: Retrieved data: {
  "acv_version" : "0.4",
  "error" : "JWT was not provided."
}

This indicates that the server does not seem to accept my JWT auth token even though I seemingly send the same that I received.

**Comment by atvassilev** [comment]
@smuellerDD, it appears that yesterday's feature rollout caused the server to deviate from the normal handling of jwt. @hbooth is investigating what happened and will know more later today.  Below is the brief summary.

During this maintenance window, the following changes are included:

-	Multi-threaded driver node processing is enabled
-	RSA-KeyGen, RSA-SigGen and RSA-SigVer algorithm modes is added
-	A bug fix for SHA is applied
-	More informative error responses are now presented

**Comment by hbooth** [comment]
Fixed to work as described in the spec.
