### ISSUE TITLE
CTR: cannot handle multiple dataLength array entries

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#229]
Sending a request with one dataLength array entry to the server returns a test vector. Sending two or more array entries fails with:
< HTTP/1.1 400 Bad Request
< Server: Apache-Coyote/1.1
< Content-Type: application/json;charset=ISO-8859-1
< Content-Length: 176
< Date: Fri, 02 Mar 2018 07:03:15 GMT
< Connection: close

Here the passing JSON:
`[
  {
    "acvVersion":"0.4"
  },
  {
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "oeInformation":{
      "vendor":{
        "name":"atsec corp.",
        "website":"www.atsec.com",
        "contact":[
          {
            "name":"Stephan Müller",
            "email":"smueller@atsec.com"
          }
        ]
      },
      "module":{
        "name":"libgcrypt",
        "version":"1.8",
        "type":"software"
      },
      "operationalEnvironment":{
        "dependencies":[
          {
            "type":"software",
            "name":"Fedora 27",
            "cpe":"XXXXUNCLEARXXXX"
          },
          {
            "type":"processor",
            "manufacturer":"Intel",
            "family":"X86",
            "name":"Intel(R) Core(TM) i7-5557U",
            "series":"Broadwell",
            "features":[
              "rdrand",
              "aes-ni",
              "clmulni"
            ]
          }
        ]
      },
      "implementationDescription":"atsec library generic C implementations"
    },
    "capabilityExchange":{
      "algorithms":[
        {
          "algorithm":"AES-CTR",
          "prereqVals":[
          ],
          "direction":[
            "encrypt",
            "decrypt"
          ],
          "keyLen":[
            128,
            192,
            256
          ],
          "dataLength":[
            128
          ],
          "ivLen":[
            128
          ],
          "ctrSource":"external"
        }
      ]
    }
  }
]`

Here the failing JSON:
`[
  {
    "acvVersion":"0.4"
  },
  {
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "oeInformation":{
      "vendor":{
        "name":"atsec corp.",
        "website":"www.atsec.com",
        "contact":[
          {
            "name":"Stephan Müller",
            "email":"smueller@atsec.com"
          }
        ]
      },
      "module":{
        "name":"libgcrypt",
        "version":"1.8",
        "type":"software"
      },
      "operationalEnvironment":{
        "dependencies":[
          {
            "type":"software",
            "name":"Fedora 27",
            "cpe":"XXXXUNCLEARXXXX"
          },
          {
            "type":"processor",
            "manufacturer":"Intel",
            "family":"X86",
            "name":"Intel(R) Core(TM) i7-5557U",
            "series":"Broadwell",
            "features":[
              "rdrand",
              "aes-ni",
              "clmulni"
            ]
          }
        ]
      },
      "implementationDescription":"atsec library generic C implementations"
    },
    "capabilityExchange":{
      "algorithms":[
        {
          "algorithm":"AES-CTR",
          "prereqVals":[
          ],
          "direction":[
            "encrypt",
            "decrypt"
          ],
          "keyLen":[
            128,
            192,
            256
          ],
          "dataLength":[
            128,
            256
          ],
          "ivLen":[
            128
          ],
          "ctrSource":"external"
        }
      ]
    }
  }
]`

**Comment by Kritner** [comment]
@smuellerDD did you receive any response information from the server?  I would imagine in the form of JSON?

**Comment by smuellerDD** [comment]
No data except the HTTP header was replied.

**Comment by hbooth** [comment]
When I send the failing JSON this is what I get back:
{
  "acv_version" : "0.4",
  "error" : "Property value(256) for (dataLen) in Algorithm (AES-CTR (null)) is not valid. Validation: (Number Between (1) and (128) modulus 1)"
}

**Comment by celic** [comment]
I don't think this is a bug. AES-CTR requires that the smallest data length in the registration be between 1 and 128. You must support 128 bit data as well, otherwise your implementation cannot run normal AES KATs. This rejection is intended. The issue here may be the spec not outlining this requirement.

**Comment by smuellerDD** [comment]
I do not find anything regarding dataLength in the symmetric cipher spec. As there is even no CAVS test spec, I would not really know what this field is intended for. Can you please point me to its definition?

**Comment by celic** [comment]
The definition isn't formally specified yet. These AES-CTR tests are new tests not from CAVS. This needs to be added to the spec.

**Comment by atvassilev** [comment]
Resolved with PR #287
