### ISSUE TITLE
acvp_sub_symmetric EBC should be ECB

### ISSUE THREAD

**Issue by DBugger32** [usnistgov/ACVP#23]
Under 2.3. Supported Symmetric Algorithms
AES-EBC should be AES-ECB
TDES-EBC should be AES-ECB

**Comment by jfigus** [comment]
Thanks for finding this.  PR #24 addresses this.

**Comment by Kritner** [comment]
I was reviewing open issues to see if there was one that answers a question I have, when I happened upon this one.  This issue can probably be closed as it was already merged in PR #24 yes?

**Comment by atvassilev** [comment]
Closing based on @Kritner's review.
