### ISSUE TITLE
Incorrectly supplying the value of the authorization token causes an internal error

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#232]
When uploading the test results to the server, the server responds with:

< HTTP/1.1 100 Continue
< HTTP/1.1 500 Internal Server Error
< Server: Apache-Coyote/1.1
< Content-Type: application/json;charset=ISO-8859-1
< Content-Length: 113
< Date: Fri, 02 Mar 2018 08:49:18 GMT
< Connection: close

It appears that when the authorization token is not supplied a bad message is returned to the user. Better handling is necessary to provide better feedback.

**Comment by smuellerDD** [comment]
It seems to be a general issue, uploading with other AES, TDES and SHA results fails the same way.

**Comment by hbooth** [comment]
Looking at the logs it appears that the authorization token is not being provided correctly.
A header value of the form
```
Authorization: Bearer <jwt>
```
is what is expected so an example is:
```
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJmZDE0ZDFjZC1lOTk2LTRkMGYtYTdhOC1iZmFjZTRkNjNlZWEiLCJpYXQiOjE1MTk3NjYwNTMsInN1YiI6IkNOPWhib290aCwgT1U9VEVTVCwgT1U9SVRMLCBPPU5JU1QsIEM9VVMiLCJpc3MiOiJOSVNUIEFDVlRTIiwidGVzdFNlc3Npb25JZCI6IjgiLCJleHAiOjE1MjAwMjUyNTN9.ocDzLUHNFK6lqURC50wDr56JcXzyViCknQ0lBtEM38M
```

**Comment by smuellerDD** [comment]
Correct. This issue was on my side. Apologies.

**Comment by atvassilev** [comment]
I would keep this open until the server implements more robust handling of bad authorization tokens.

**Comment by hbooth** [comment]
Fix for the error message issue was deployed earlier today.
