### ISSUE TITLE
TDES CTR: undefined  testType entries in test vectors

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#233]
The TDES CTR JSON test vector contains the following testType entries:

  }, {
    "direction" : "encrypt",
    "testType" : "InversePermutation",

or 

  }, {
    "direction" : "encrypt",
    "testType" : "Permutation",

Others are also found.

These test types are not defined.

**Comment by celic** [comment]
Duplicate of #248 which has been resolved.
