### ISSUE TITLE
CMAC register fails

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#234]
The server rejects the following with 400: I would think that it matches the spec:
```
[
  {
    "acvVersion":"0.4"
  },
  {
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "oeInformation":{
      "vendor":{
        "name":"atsec corp.",
        "website":"www.atsec.com",
        "contact":[
          {
            "name":"Stephan Müller",
            "email":"smueller@atsec.com"
          }
        ]
      },
      "module":{
        "name":"libgcrypt",
        "version":"1.8",
        "type":"software"
      },
      "operationalEnvironment":{
        "dependencies":[
          {
            "type":"software",
            "name":"Fedora 27",
            "cpe":"XXXXUNCLEARXXXX"
          },
          {
            "type":"processor",
            "manufacturer":"Intel",
            "family":"X86",
            "name":"Intel(R) Core(TM) i7-5557U",
            "series":"Broadwell",
            "features":[
              "rdrand",
              "aes-ni",
              "clmulni"
            ]
          }
        ]
      },
      "implementationDescription":"atsec library generic C implementations"
    },
    "capabilityExchange":{
      "algorithms":[
        {
          "algorithm":"AES-ECB",
          "direction":[
            "encrypt",
            "decrypt"
          ],
          "keyLen":[
            128,
            192,
            256
          ],
          "ptLen":[
            128
          ]
        },
        {
          "algorithm":"CMAC-AES",
          "prereqVals":[
            {
              "algorithm":"AES",
              "valValue":"same"
            }
          ],
          "direction":[
            "gen",
            "ver"
          ],
          "keyLen":[
            128,
            192,
            256
          ],
          "msgLen":[
            {
              "min":16,
              "max":524288,
              "increment":8
            }
          ],
          "macLen":[
            128
          ]
        }
      ]
    }
  }
]
```

**Comment by atvassilev** [comment]
400 responses should come with additional information. Could you provide it to help us triage this problem?

**Comment by smuellerDD** [comment]
That is the point, I receive nothing apart from the HTTP header I posted.

**Comment by hbooth** [comment]
When I submit this is what I get back:
{
  "acv_version" : "0.4",
  "error" : "Property value(524288) for (msg) in Algorithm (CMAC-AES (null)) is not valid. Validation: (Number Between (0) and (65536) modulus 8)"
}

What client are you using to submit and get back responses?

**Comment by atvassilev** [comment]
It looks like we have a discrepancy between the implementation and the spec, which gives the maximum msgLen value as 524288.

**Comment by atvassilev** [comment]
The spec is slightly misleading because it does not specify that the maximum msgLen value is in bits. In contrast, the spec does specify that the maximum keyLen value is in bits. 

The way I see it there are a couple of followups here: 

1. fix the server to incorporate the proper max value (in bits) for msgLen.  
2. fix the spec, Table 2, to explicitly state that msgLen is in bits.

**Comment by smuellerDD** [comment]
@hbooth: The server does not reply anything back. This is all I get:

< HTTP/1.1 400 Bad Request
< Server: Apache-Coyote/1.1
< Content-Type: application/json;charset=ISO-8859-1
< Content-Length: 178
< Date: Fri, 02 Mar 2018 16:48:59 GMT
< Connection: close
<

After my client sees the Connection close, the connection is terminated.

I am using libcurl version 7.55 as found on Fedora 27. And the program obtains all data the server would ever send. For debugging purposes I also store the data for analysis. Yet, I do not get any HTTP body with any JSON data.

**Comment by Kritner** [comment]
@atvassilev I'm pretty sure we had a ticket at some point to update ***every*** byte value in the spec to its bit value.  Bit's should be the default unless otherwise specified AFAIK

**Comment by smuellerDD** [comment]
@hbooth when I change the max val to 65536, I can register and get the vectors for CMAC-AES. But for CMAC-TDES it still fails with 400.
```
        {
          "algorithm":"CMAC-TDES",
          "prereqVals":[
            {
              "algorithm":"TDES",
              "valValue":"same"
            }
          ],
          "direction":[
            "gen",
            "ver"
          ],
          "keyLen":[
            168
          ],
          "msgLen":[
            {
              "min":8,
              "max":65536,
              "increment":8
            }
          ],
          "macLen":[
            64
          ]
        }
```

**Comment by atvassilev** [comment]
@Kritner I know we had agreed on it and it is possible to deduce it from the context of the mac spec but having said this, the spec is somewhat inconsistent in that the requirement to use values in bits is stated explicitly everywhere but one spot, namely for msgLen in Table 2. I think it would be best to just add "in bits" to the second column.

**Comment by Kritner** [comment]
@smuellerDD `CMAC-TDES` requires a `keyingOption` property that wasn't supplied.  `keyLen` is not a valid proeprty for `CMAC-TDES`

**Comment by smuellerDD** [comment]
@Kritner: right, the bug sits between desk and chair :-) - strstr instead of strncmp is the key to detect whether I process TDES related data sets.

All works -- the issue could be closed on my end, but I see that there is discussion ongoing.

**Comment by hbooth** [comment]
@smuellerDD I would be interested in understanding why you are not receiving a payload with the 400 status codes. You should be receiving some sort of message that would let you know what the problem is. I have been using a browser (and some other tools without issue) but I have not been using curl.

The deployment earlier today did resolve the msgLen issue and will not accept the full range described in the spec.

I will leave this open until @atvassilev  and @Kritner have resolved the spec issue.

**Comment by smuellerDD** [comment]
I do receive the error messages from the server now. Sorry, there was a bug in my implementation that did not display the responses in POST messages.
