### ISSUE TITLE
SHA response submission fails

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#237]
The SHA response submission fails for every type of SHA. The server answers:
< HTTP/1.1 100 Continue
< HTTP/1.1 400 Bad Request
< Server: Apache-Coyote/1.1
< Content-Type: application/json;charset=ISO-8859-1
< Content-Length: 131
< Date: Fri, 02 Mar 2018 17:04:31 GMT
< Connection: close

As snippet of the JSON for SHA-1:
```
  {
    "acvVersion":"0.4"
  },
  {
    "vsId":687,
    "testResults":[
      {
        "tcId":1,
        "md":"da39a3ee5e6b4b0d3255bfef95601890afd80709"
      },
      {
        "tcId":2,
        "md":"999a0a8cad102eb519ca788d6e0cd48ee9e6ca3e"
      },
```

and

```
     {
        "tcId":130,
        "resultsArray":[
          {
            "count":"0",
            "md":"3a234df4571bcc45baff3712ca288ee3c7eba43b"
          },
          {
            "count":"1",
            "md":"35bc8fd47a7bebc957de7154164edd650fa2d704"
          },
          {
            "count":"2",
            "md":"02124b597645ef7b15de4386dc31ae7ff77f18e9"
          },
```

**Comment by celic** [comment]
Is count supposed to be a string or an integer?

**Comment by smuellerDD** [comment]
I just reviewed the latest spec and the count value is gone entirely. When using the following JSON for the MCT, the server accepts it:

```
      {
        "tcId":130,
        "resultsArray":[
          {
            "md":"3a234df4571bcc45baff3712ca288ee3c7eba43b"
          },
          {
            "md":"35bc8fd47a7bebc957de7154164edd650fa2d704"
          },
```
However, the server responds: with the error: "reason" : "ResultsArray did not contain expected element Message" when fetching the result.


Note, the following example in the SHA spec does not seem to be valid JSON as an array does not contain key-value pairs:
```
   [
     { "acvVersion": "0.4" },
     { "vsId": 1564,
       "testResults": [
       {
           "tcId": 2175,
           "resultsArray": [
               "md": "23d1f8655a7c9c2bc3bb56868483611e67cb1b3a",
               "md": "d3d672efb8e569dc7a37c991a9fc51282412196f"
           ]
       }]
     }]
```

**Comment by smuellerDD** [comment]
I rerun the tests for SHA-1, SHA-224 through SHA-512 and get the same issue for all of them.

The test verdict indicates a pass for all AFT results, and the above indicated formatting failure for the MCT.

**Comment by celic** [comment]
I think the proper format for this is... 
```
{
      "tcId": 2175,
      "resultsArray": [
        {
          "msg": "9A1715BD92D39C637B512366D7C99A68592FCB4BF35E275CA339DAC37AA668039A1715BD92D39C637B512366D7C99A68592FCB4BF35E275CA339DAC37AA668039A1715BD92D39C637B512366D7C99A68592FCB4BF35E275CA339DAC37AA66803",
          "md": "23d1f8655a7c9c2bc3bb56868483611e67cb1b3a"
        },
        {
          "msg": "D218269A50674064D2E09BB4F341FEF8E88C27BF1E24F241EFF11CDE4378979DD218269A50674064D2E09BB4F341FEF8E88C27BF1E24F241EFF11CDE4378979DD218269A50674064D2E09BB4F341FEF8E88C27BF1E24F241EFF11CDE4378979D",
          "md": "d3d672efb8e569dc7a37c991a9fc51282412196f"
        },
        {
          "msg": "CFC57846FB0770767F1D78C45208F527FF22F281B61A5789DD350787B489165DCFC57846FB0770767F1D78C45208F527FF22F281B61A5789DD350787B489165DCFC57846FB0770767F1D78C45208F527FF22F281B61A5789DD350787B489165D",
          "md": "35bc8fd47a7bebc957de7154164edd650fa2d704"
        }
      ]
    },
```

even though the message is just 3x the previous digest. The example appears to be incorrect (in addition to not being valid JSON). If you use the format I mention here, it should work. 

The real issue then is that the message is not necessary in the results file and I believe was included for debugging purposes... that way we could tell if the client set up the MCT correctly before having them dive into their crypto. For now, it will remain this way, but the spec example needs to be cleaned up a bit.

**Comment by atvassilev** [comment]
From what I can see, the spec needs to be cleaned up, possibly the server implementation too.
