### ISSUE TITLE
CTR DRBG: perso string length of 0 not accepted

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#240]
The server responds with the following error when using a perso string length of 0:

```
{
  "acv_version" : "0.4",
  "error" : "Property value(0) for (persoString) in Algorithm (ctrDRBG (null)) is not valid. Validation: (Number Between (128) and (34359738368) modulus 8)"
}
```

If I read the spec right, a zero value is acceptable.

**Comment by atvassilev** [comment]
It appears that this issue is also reported separately in #241. Closing here and will track it there. Please reopen it if you think something important will be missed.

**Comment by smuellerDD** [comment]
Sorry for the confusion, this bug report addresses the personalization string length, #241 covers the additional input string len

**Comment by atvassilev** [comment]
OK, reopening.
