### ISSUE TITLE
CTR DRBG: additional input string length of < 128 not allowed

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#241]
The server responds with the following if supplying a perso string length of 0:

```
{
  "acv_version" : "0.4",
  "error" : "Property value(0) for (additionalInput) in Algorithm (ctrDRBG (null)) is not valid. Validation: (Number Between (128) and (34359738368) modulus 8)"
}
```

The spec seems to allow a perso string length of 0.

**Comment by atvassilev** [comment]
Both SP 800-90A and the spec do allow perso string length of 0, as a way of saying it is not used.
