### ISSUE TITLE
AES CTR: some test responses require an IV?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#245]
The AES CTR test responses submitted to the server in generall recevied a passing verdict. However, a subset of 6 test results received the following failure:

```
    }, {
      "tcId" : 61,
      "result" : "fail",
      "reason" : "IVs was not present in the TestCase"
    }, {
      "tcId" : 62,
      "result" : "fail",
      "reason" : "IVs was not present in the TestCase"
    }, {
      "tcId" : 63,
      "result" : "fail",
      "reason" : "IVs was not present in the TestCase"
    }, {
      "tcId" : 64,
      "result" : "fail",
      "reason" : "IVs was not present in the TestCase"
    }, {
      "tcId" : 65,
      "result" : "fail",
      "reason" : "IVs was not present in the TestCase"
    }, {
      "tcId" : 66,
      "result" : "fail",
      "reason" : "IVs was not present in the TestCase"
    }, {
```

Note, the test response I sent for these tcIDs is formatted identically to all other (passing) responses, i.e. without an IV.

The failing request is defined in the test request as follows:

```
  }, {
    "direction" : "decrypt",
    "keyLen" : 256,
    "testType" : "AFT",
    "overflow" : false,
    "incremental" : false,
```

**Comment by smuellerDD** [comment]
Yes, the AFT vectors which are started by the mentioned meta data require some IV in the test response. All other test specifications in the same JSON test vector pass without an IV provided in the test response.

**Comment by celic** [comment]
Are those 6 the only failing AFTs? Or did all AFTs fail with that same reason?

**Comment by smuellerDD** [comment]
Only those 6 fail for the missing IV. All others pass without providing an IV. Here is an example of the passing responses:
```
  {
    "vsId":736,
    "testResults":[
      {
        "tcId":1,
        "cipherText":"9fa15de7ee22778402fc08bb98200ec9"
      },
      {
        "tcId":2,
        "cipherText":"b5a1aca1dd3f5b46abda298954c70a16"
      },
      {
        "tcId":3,
        "cipherText":"66ee1102f5ef1216f669b1ce442e0440"
      },
```

The failing responses are formatted identically -- I just did not paste them here, because the data is very long.

**Comment by smuellerDD** [comment]
And here are some passing decryption results:
```
      {
        "tcId":33,
        "plainText":"67e08a7f335724eda5c3d64788ca363e"
      },
      {
        "tcId":34,
        "plainText":"7bc186983725bf9085d4a1e3938ca209"
      },
      {
        "tcId":35,
        "plainText":"1af4ce4d6c2029557e246250005bafef"
      },
      {
        "tcId":36,
        "plainText":"c3c358c5591f85077c6306cf6c93f44d"
      },
      {
        "tcId":37,
        "plainText":"3c7ff4ea0332a102f7c7571b81eae02a"
      },
      {
        "tcId":38,
        "plainText":"466fbc23aae4caefccaf254a614af901"
      },
```

**Comment by celic** [comment]
What is the vsId on this?

**Comment by bfussell** [comment]
Can you also check on the reason for changing from pt/ct to plainText/cipherText when all the other symmetrix ciphers use the former ?

**Comment by smuellerDD** [comment]
736

**Comment by smuellerDD** [comment]
Am Mittwoch, 7. März 2018, 00:30:20 CET schrieb Barry Fussell:

Hi Barry,

> Can you also check on the reason for changing from pt/ct to
> plainText/cipherText when all the other symmetrix ciphers use the former ?

In one of the example in the symmetric spec mandates these different keywords. 
I would like to have the pt/ct used, though.

Are you saying that pt/ct works?

Ciao
Stephan

**Comment by bfussell** [comment]
No ct/pt does not work. I opened issue #250 to cover this.  We should use the same keywords throughout all symmetric ciphers.

**Comment by celic** [comment]
These are not AFTs. These are a different test type. They are counter tests. They do require a list of IVs. I'm going to close this issue as there is no problem.

**Comment by bfussell** [comment]
@celic Are you saying that we need to return the IV because the testType is not AFT ?
Those failing tests in AES-CTR have testType set to AFT.

**Comment by celic** [comment]
In the JSON you receive the test type is set to AFT? When I look at the JSON generated on the back-end, it is not. The test type is "counter" indicating that a list of IVs are needed. This may be an issue for @hbooth then.

**Comment by celic** [comment]
Ah yeah there is an issue for this on our end. I will close the issue when I get confirmation that the fix has been deployed.

**Comment by bfussell** [comment]
Thanks !

**Comment by celic** [comment]
The fix has been pushed out.

**Comment by celic** [comment]
This would be under #122 as right now none of the documentation explains any of the test types. An email went out to the algotest mailing list explaining the new tests. There is an example in the symmetric specification, but the general flow of the test is the following... 

In the registration there are a couple of Boolean properties on whether the IUT supports an increasing or decreasing counter, and whether the IUT supports overflow in the counter. Based on these, the server generates a single long message that spans many blocks, a single key, and a starting IV. The IUT computes the encryption (or decryption) using its counter mechanism and returns a single long ciphertext (or plaintext) and a list of all the IVs used in the process. The server verifies that these IVs have the properties that a counter mechanism should ensure, and that the encryption/decryption is correct.

**Comment by smuellerDD** [comment]
Am Donnerstag, 8. März 2018, 18:49:42 CET schrieb Chris Celi:

Hi Chris,

> This would be under #122 as right now none of the documentation explains any
> of the test types. An email went out to the algotest mailing list
> explaining the new tests. There is an example in the symmetric
> specification, but the general flow of the test is the following...

#122 does not specify the structure of the response information. Do you have 
another pointer?
> 
> In the registration there are a couple of Boolean properties on whether the
> IUT supports an increasing or decreasing counter, and whether the IUT
> supports overflow in the counter. Based on these, the server generates a
> single long message that spans many blocks, a single key, and a starting
> IV. The IUT computes the encryption (or decryption) using its counter
> mechanism and returns a single long ciphertext (or plaintext) and a list of
> all the IVs used in the process. The server verifies that these IVs have
> the properties that a counter mechanism should ensure, and that the
> encryption/decryption is correct.

This is a real challenge in a lot of implementations: it is usually very hard 
to get the IV out of a cipher context as this is commonly nothing that is 
needed.

Besides, if you have the ciphertext / plaintext, it could be very easy to 
extract the IV (simply XOR the plaintext with the ciphertext which you both 
have). Thus, may I ask to drop the requirement for needing an IV?

Note, I am not aware of any implementation where it is legal to read the IV 
after a cipher operation. Of course, some implementations allow it, but with 
potentially undefined results. Considering hardware implementations, you 
usually do not get the IV out.

Ciao
Stephan

**Comment by celic** [comment]
I like this suggestion. I'll create a separate issue with this information and see about modifying the server code for this. I cannot promise an immediate change however as this is slightly more involved than the normal bug fixes we have been doing.

**Comment by smuellerDD** [comment]
Thanks a lot. As my CTR AFT test results all succeed apart from this specific test, I would then disregard developing this specific counter IV generation support and trying to modify the modules we are considering (which apply to a large number of CTR AES implementations).

I keep my fingers crossed that you could implement the suggestion outlined above which would ease the pain on the vendor side significanly.
