### ISSUE TITLE
CTR DRBG: prediction resistance false and additional entropy

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#246]
When selecting prediction resistance false, the CTR DRBG test vectors contain additional entropy in otherInfo. How shall that be processed considering the CAVS specification of the DRBG? In the CAVS specification, there is at most additional input between generate requests, but no additional entropy.

Here is an example test vector with prediction resistance false, but still with additional entropy that I received from the server:
```
{
    "testType" : "AFT",
    "mode" : "AES-128",
    "derFunc" : true,
    "predResistance" : false,
    "entropyInputLen" : 128,
    "reSeed" : false,
    "nonceLen" : 128,
    "persoStringLen" : 128,
    "additionalInputLen" : 128,
    "returnedBitsLen" : 512,
    "tests" : [ {
      "tcId" : 1,
      "entropyInput" : "D1C90793DDF3B857F1E149B8D473F730",
      "nonce" : "142D4D2203D9AA496F299389D0D6FEBF",
      "persoString" : "BCFB2DC4DEB61BB928C96768E1379B50",
      "otherInput" : [ {
        "additionalInput" : "1CAA4ADD6D16AD355769E7CFF78DDE8B",
        "entropyInput" : "0ACFDE700E8B03CD9DEB89A98E8C2E7C"
      }, {
        "additionalInput" : "83BF7E72FC5834C594EC039FE653AB4C",
        "entropyInput" : "DBB8BBDC64139AB0C76B9FC0F3861DAF"
      } ]
    }, {
```

**Comment by atvassilev** [comment]
This is a bug in the gen/val layer of the server. The DRBG spec shows that for all examples where predResistance is false, the entropyInput should be empty.

**Comment by Kritner** [comment]
I will take a look at this shortly.

@atvassilev I may be misunderstanding something, but it looks like there is still entropy input provided for a reseed when using options `"predResistance": false, "reSeed": true`

This seems to match up with the sample DRBG test vectors downloaded from: https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/random-number-generators#DRBG

Snippet from test vector:

```
[AES-128 use df]
[PredictionResistance = False]
[EntropyInputLen = 128]
[NonceLen = 64]
[PersonalizationStringLen = 0]
[AdditionalInputLen = 0]
[ReturnedBitsLen = 512]

COUNT = 0
EntropyInput = 0f65da13dca407999d4773c2b4a11d85
Nonce = 5209e5b4ed82a234
PersonalizationString = 
EntropyInputReseed = 1dea0a12c52bf64339dd291c80d8ca89
AdditionalInputReseed = 
AdditionalInput = 
AdditionalInput = 
ReturnedBits = 2859cc468a76b08661ffd23b28547ffd0997ad526a0f51261b99ed3a37bd407bf418dbe6c6c3e26ed0ddefcb7474d899bd99f3655427519fc5b4057bcaf306d4
```

IIRC the "otherInput" property supplies the entropy/additionalInput regardless of a "generate" or "reseed" operation - though I'll need to some re-acclimating time to say for sure.

Yes I agree that additional entropy should not be produced in the "otherInput" property for the scenario being inquired about, but just want to get clarification on what @atvassilev said above.

**Comment by atvassilev** [comment]
@Kritner, my comment concerns the specific case of predResitance = false, reSeed=false. If predResitance=false and reSeed = true, there is some entropy passed, but be careful as to how many inputs per reseed test - check the examples in the spec.

**Comment by Kritner** [comment]
This fix is going through internal testing and should be pushed out with the next release

**Comment by hbooth** [comment]
Fix has been deployed.
