### ISSUE TITLE
RSA sigGen missing "saltLen" error

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#247]
I am getting an error about missing "saltLen" for ansx9.31 and pkcs1v1.5. I think only pss mode should be expecting this value.

**Comment by celic** [comment]
Correct. Could you paste in the exact error message if you have it on hand?

**Comment by celic** [comment]
For now, you can just use `"saltLen": 0` to get the tests done, the value is ignored for anything other than PSS.

**Comment by elliemdaw** [comment]
Sure, here you go. I will update our code with that workaround for now!
"error" : "Incorrectly formatted JSON (59:42): expected field name was not provided: saltLen"

**Comment by celic** [comment]
Ok thanks. This was fixed on the back-end and should be reflected externally soon. I'll post notification when that update goes out and close this issue then.

**Comment by elliemdaw** [comment]
Sounds good, thanks!!

**Comment by celic** [comment]
This is fixed.

**Comment by elliemdaw** [comment]
This issue is still occurring

**Comment by celic** [comment]
Sorry about that. We are looking into it.

**Comment by hbooth** [comment]
Are you still seeing the specific error saying the saltLen is required for registration or are you getting a different error message? I just double-checked and saltLen is configured to be optional now. What is the registration you are using?

**Comment by elliemdaw** [comment]
I ran this again - looks like it is working as expected for sigGen, but not for sigVer. The error is the same as before, but I believe that saltLen should only be required for PSS on sigVer as well?

**Comment by atvassilev** [comment]
@elliemdaw is correct, saltLen is for PSS only.

**Comment by hbooth** [comment]
Miscommunication resulted in the change not applied to sigVer as well. Please try now it should be fine.
