### ISSUE TITLE
TDES-CTR testType Values

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#248]
Our rule has been just use AFT for all the various varkey, vartext, permutation, etc. I'm not aware of any real value those other testTypes provide.

**Comment by celic** [comment]
Internally we represent them differently than they should be externally. This is an issue for @hbooth or @pavelgutin.

**Comment by celic** [comment]
This was an issue larger than just TDES-CTR, there were several TDES modes with this bug. This has been fixed on the back-end and will be deployed soon.

**Comment by bfussell** [comment]
Thanks !

**Comment by bfussell** [comment]
@hbooth @pavelgutin 

I think there are still some incorrect testTypes

  "vsId" : 862,
  "algorithm" : "TDES-CTR",
  "testGroups" : [ {
    "direction" : "encrypt",
    "testType" : "singleblock",
....
    "testType" : "partialblock",

**Comment by celic** [comment]
Ah ok. A separate but related issue. This is also fixed on the back-end and will be deployed soon.

**Comment by celic** [comment]
This fix was deployed.
