### ISSUE TITLE
AES-XTS tweakMode field format

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#249]
tweakMode(code) or tweakFormat(spec) does not have an example of proper capabilities registration.

**Comment by celic** [comment]
The appropriate values for this are "hex" or "number". So in a registration it would look like...
```
    "TweakMode":[
        "hex",
        "number"
    ]
```

where "hex" refers to a 128-bit hexadecimal string used as a tweak value, and "number" refers to a data unit sequence number (integer) used as a tweak value. The spec needs to be updated to reflect this if it is not there.
