### ISSUE TITLE
Sample JSON in section 11.2 is not consistent with symmetric cipher sub-spec

### ISSUE THREAD

**Issue by jfigus** [usnistgov/ACVP#25]
The "mode" value is no longer defined in the sub-spec.  The length names are no longer plural.

 "mode" : "both",
   "ivGen" : "internal",
   "ivGenMode" : "8.2.1",
   "keyLens" : [
               128,
               256
                ],
   "tagLens" : [
               96
                  ],
   "ivLens" : [
               96
                  ],
   "ptLens" : [
               0,
               128,
               136
                  ],
"aadLens" : [

**Comment by atvassilev** [comment]
PR #31 and #33  resolve this issue.
