### ISSUE TITLE
AES-XTS has no testType and "iv" is represented as "i"

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#251]
"acvVersion" : "0.4"
}, {
  "vsId" : 867,
  "algorithm" : "AES-XTS",
  "testGroups" : [ {
    "direction" : "encrypt",
    "keyLen" : 128,
    "tweakMode" : "hex",
    "ptLen" : 128,
    "tests" : [ {
      "tcId" : 1,
      "key" : "891E6F5EA8AA35A4296FE2681105DCD4918394455697D6A5B8B78B613D686DD2",
      "i" : "355A0FE12C983FFEF0501EB1B8B3019D",
      "pt" : "281DE8E6C4DCFBA456BCE41CFFE99D2B"

**Comment by celic** [comment]
"i" is correct here. It is a tweak value represented as hex. According to XTS this undergoes a process to become similar to an IV for other AES modes. The test type should be AFT, but as there are no other test types, it was omitted.
