### ISSUE TITLE
Question on the AES-CTR counter format

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#252]
Lots of data so I've removed some.

            {
                "tcId": 31,
                "cipherText": "69778FE8929EA9B124D6D2BAA3C475C95DA59D822E746A8116233C810C9D853F39E54EDD84A680A9973C8B7D92D5293F5FA9F3A156A5CFCFEB84E22EB0BE6E6794CFE2F7F20A650F67B12327FB4CD687AEDA75D........55A57EE008F34062B481193",
                "ivs": [
                    "FFFFFFFFFFFFFE6A",
                    "FFFFFFFFFFFFFE6B",
......
                    "FFFFFFFFFFFFFE5C",
                    "FFFFFFFFFFFFFE5D"
                ]
            },

I get this response after submitting that:

***ACVP [ERR][acvp_submit_vector_responses:480]--> {
  "acv_version" : "0.4",
  "error" : "Incorrectly formatted JSON (132:25): Unknown or disallowed submission property: ivs"
}

**Comment by celic** [comment]
This is an error in the server. We will fix it shortly. Thanks!

**Comment by celic** [comment]
This would need to be applied to TDES-CTR as well.

**Comment by atvassilev** [comment]
Is this still an issue? Please let me know since we are approaching the v0.4 milestone.

**Comment by celic** [comment]
This is part of the set of fixes hitting our internal environment now. It should be reflected externally soon.

**Comment by hbooth** [comment]
Fix has been deployed if you see any additional problems open a new issue and let us know.
