### ISSUE TITLE
Investigate removal of IV from CTR mode tests

### ISSUE THREAD

**Issue by celic** [usnistgov/ACVP#254]
Quote from another issue from Stephan...

> If the CAVS server would perform the steps outlined above, all would benefit as follows:
>1. The developer would not need a debug build of their code.
>2. The developer could simply perform a standard en/decryption (i.e. AFT) just like for the other modes.
>3. CAVS would get a result from the implementation that is shipped to customers (i.e. no debug build, no simulation testing, etc.)

**Comment by atvassilev** [comment]
I am scheduling this for v0.5, if you can do it earlier this would be fine too.

**Comment by bfussell** [comment]
Would that mean that testType "counter" would no longer be required ?

**Comment by celic** [comment]
It will still be required. We would just like to look into restructuring how the test operates to see if it can be made easier to complete.

**Comment by celic** [comment]
This is done in terms of the gen/vals, but requires some server updates. This is scheduled for some time during v0.5.
