### ISSUE TITLE
RSA SigVer expects "pubExpMode"

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#255]
When trying to register for sigVer PSS, the following error is given:

"error" : "Incorrectly formatted JSON (66:18): expected field name was not provided: pubExpMode"

**Comment by celic** [comment]
I think this value is required. Is it not outlined in the spec? The property mimics the property of the same name for SigGen and KeyGen. It accepts "fixed" or "random", and if the value is "fixed", then you must provide `"fixedPubExpValue": <hex>`.

**Comment by elliemdaw** [comment]
Ahh you are right. I was looking at sigGen, thanks!
