### ISSUE TITLE
RSA KeyGen vector set results error

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#257]
When registering for keygen I am getting the following error when querying for vector set results:

[ {
  "acvVersion" : "0.4"
}, {
  "results" : {
    "vsId" : 1001,
    "disposition" : "error",
    "message" : "validation executable failed for: 1001"
  }
} ]

I got the same error for vector set 1000 as well. Here is the registration:

               {
                    "algorithm": "RSA",
                    "mode": "keyGen",
                    "prereqVals": [
                        {
                            "algorithm": "SHA",
                            "valValue": "same"
                        },
                        {
                            "algorithm": "DRBG",
                            "valValue": "same"
                        }
                    ],
                    "infoGeneratedByServer": true,
                    "pubExpMode": "fixed",
                    "fixedPubExp": "010001",
                    "keyFormat": "standard",
                    "algSpecs": [
                        {
                            "randPQ": "B.3.4",
                            "capabilities": [
                                {
                                    "modulo": 2048,
                                    "hashAlg": [
                                        "SHA2-224"
                                    ],
                                    "primeTest": [
                                        "tblC2"
                                    ]
                                }
                            ]
                        }
                    ]
                }

**Comment by celic** [comment]
Bitlens should not be included in the response when `"infoGeneratedByServer": true`. Outside of that, the json looks fine. The responses don't seem to match what the server computed, but that should return a "failed" validation and a reason for each test case.

**Comment by elliemdaw** [comment]
Ahh because the server already knows them. Makes sense... I'll give that a shot later this afternoon. Thanks!

**Comment by celic** [comment]
There seems to be a different issue causing this problem however. We are trying to fix it still.

**Comment by celic** [comment]
We are going to do a redeploy to see if the problem has been fixed. Please confirm this when you can!

**Comment by elliemdaw** [comment]
Everything seems to be going through just fine for keygen now! Thanks!!

**Comment by celic** [comment]
Awesome.
