### ISSUE TITLE
Resubmitting results never returns a disposition.

### ISSUE THREAD

**Issue by hbooth** [usnistgov/ACVP#258]
If a user attempts to submit results a disposition is never returned. This issue was initially described in the comments for  #214. Separating this issue out so it can be tracked.

**Comment by atvassilev** [comment]
@hbooth, could #238 be related to this problem too?

**Comment by hbooth** [comment]
Possibly. Stephan, can you confirm that the error for #238 happens when attempting to resubmit? Or are you following a different series of steps?

**Comment by atvassilev** [comment]
I am not sure how GitHub works for notifications on issues that have not been created by a specific user who is not on the project collaborator list. So I don't know if Stephan would see this. I will ping him through the #238 thread to make sure.

**Comment by smuellerDD** [comment]
Issue #238 happens after a resubmit. Thus, it would be covered by this new bug report.

**Comment by hbooth** [comment]
Fix has been deployed. It should be possible to submit multiple times without error.
