### ISSUE TITLE
RSA KeyGen "primeTest" attribute

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#259]
The server is expecting a non-empty array of "primeTest" table names for all keygen modes. I don't think they need to be specified for B.3.2 (Random provable) or B.3.4 (provable primes with conditions).

I am running tests for B.3.4 and if I include an arbitrary "primeTest" attribute I am able to successfully process vectors.

Error: "Incorrectly formatted JSON (73:34): expected field name was not provided: primeTest" or "Incorrectly formatted JSON (73:52): minimum number of values were not provided for field: primeTest".

However for reference, vs 1347 passes all tests and I registered with the following:
                "algSpecs": [
                        {
                            "randPQ": "B.3.4",
                            "capabilities": [
                                {
                                    "modulo": 2048,
                                    "hashAlg": [
                                        "SHA2-256"
                                    ],
                                    "primeTest": [
                                        "tblC2"
                                    ]
                                }
                            ]
                        }
                    ]

**Comment by elliemdaw** [comment]
Sorry about the formatting there... not sure what happened.

**Comment by celic** [comment]
You are correct. This is an issue for @hbooth. `"primeTest"` is only needed when `"randPQ": "B.3.3", "B.3.5", or "B.3.6"`.

Along these lines, `"hashAlg"` is only needed for `"randPQ": "B.3.2", "B.3.4", or "B.3.5"`. I suspect that will need fixing as well.

**Comment by celic** [comment]
A fix for this is going out today. Please test this when you get a chance.

**Comment by hbooth** [comment]
Fix is now out in demo.

**Comment by elliemdaw** [comment]
The server is still expecting "primeTest" as part of a registration for B.3.4

**Comment by elliemdaw** [comment]
@celic I am not sure who to tag here, but this is still an issue after the server update. I also noticed that the examples in the spec don't reflect that this attribute isn't required for certain randPQ values... I am happy to update some of the examples and open a PR if that helps!

**Comment by celic** [comment]
It would be awesome if you could fix the examples. You mention as well that this is still a problem even with the roll-out last night? I'll get this fixed.

**Comment by elliemdaw** [comment]
Sounds good! I should get to that by the end of the week. And yes, still an issue even after last night's rollout. Thanks!

**Comment by atvassilev** [comment]
@celic does this problem affect the Web server layer or the gen/val code or both?

**Comment by celic** [comment]
Web server only. So this is something for @pavelgutin or @hbooth
