### ISSUE TITLE
Need failure reason in test results response from ACVP server

### ISSUE THREAD

**Issue by jfigus** [usnistgov/ACVP#26]
Do we want to add a reason failure to the test results in section 11.4 for failed test cases? The JSON response would look something like this...

   {
   "version" : "0.2",
   "results" : {
       "vsId" : 1437,
       "disposition" : "incomplete",
       "tests" : [
               { "tcId" : 12340, "result" : "passed", "reason" : "" },
               { "tcId" : 12341, "result" : "incomplete", "reason" : "" },
               { "tcId" : 12342, "result" : "failed", "reason" : "Authentication tag failure" }
                 ]
      }
}

**Comment by atvassilev** [comment]
I am in favor.

**Comment by bfussell** [comment]
Sounds good to me.  As we have discussed on a few occasions the error reporting is presently
pretty weak and we need to make sure we continue to enhance it.  I still have an action item
to review the CAVS tool and make sure we cover all errors it detected.

Barry

**Comment by sam1689** [comment]
Good idea - I think it will enhance the value of the testing and save everyone more time if we can include a decent failure reason in the results.

-Sam

**Comment by atvassilev** [comment]
PR #31 resolves this.
