### ISSUE TITLE
RSA sigGen mod 4096 error

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#260]
I get the following error when I try to register any sigGen types with mod 4096. The other modulo values seem to work just fine!

200 OK [ {
  "acvVersion" : "0.4"
}, {
  "vsId" : 1417,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 1417"
} ]

**Comment by celic** [comment]
Mod 4096 is not supported (even though the spec says it is). This is neither a spec error nor a server error unfortunately. We are waiting on test data to ensure that our implementation is correct. Perhaps we can get that assurance by working with you guys.

**Comment by elliemdaw** [comment]
Oh gotcha. Okay, I will leave it out for now and we can revisit later on! Thanks for getting back to me so quickly!
