### ISSUE TITLE
retry:30 issue appears again

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#261]
After a successful upload of test vectors and getting test results, I downloaded another set of vectors. For those new vectors, the server does not return the verdicts after submitting the response.

Following this failure, I tried to register again to get new vectors. And now, even the vectors are not provided any more.

The server always returns retry:30

**Comment by elliemdaw** [comment]
I am also seeing significant delays on RSA... I tried to run a full set of RSA algs last night and it gave me retry:30 for 90+ mins before I killed it on my side. This morning I pared it down to just one sigGen type and one sigVer type and it has been giving retry for quite some time again. At least an hour...

**Comment by hbooth** [comment]
@elliemdaw give RSA a try again
I think I know what is causing some of the issues Stephan is describing and it may be a little bit before a fix makes it way all the way out to demo.

**Comment by bfussell** [comment]
@hbooth @elliemdaw Harold is it accurate that the vsId increments for each request ? I noticed that it has gone from ~1560 this morning to ~1890 now and I don't think Ellie or I were running anything until just now when I did a SHA test and the vsID hit 1900.  Was wondering if that is indicative of a whole bunch of clients hitting the server.

**Comment by hbooth** [comment]
Yes, the vsId increments for each request. There are a number of users who have been accessing the demo environment, but that didn't seem to be the issue. There was a blip that was not handled gracefully which was causing this particular issue. An internal issue has been created to track and once it is resolved we can close this.

**Comment by elliemdaw** [comment]
@hbooth RSA seems to be endlessly giving retry:30 again when querying for the vector set :(

**Comment by elliemdaw** [comment]
Most recently while asking for vsId 2674

**Comment by smuellerDD** [comment]
Yesterday, all symmetric ciphers and hashes were particularly fast (generation and verdict creation). But RSA is not returning anything as already mentioned.

Last night though, symmetric ciphers and hashes did not produce vectors after waiting for 7 hours.

**Comment by celic** [comment]
There was a problem with RSA KeyGen that caused some of the trouble here. Essentially the process was getting hung up, and so no other tasks were started until the previous task finished. This has been resolved and will be deployed soon. There may be some other issues with this that need to be resolved, but we will be adding in some better error checking on our end to prevent this from happening.

**Comment by smuellerDD** [comment]
Just as a note: so far, it seems to work with all types of ciphers.

**Comment by smuellerDD** [comment]
I may have hosed your server again by trying to parallel download some 30 test vectors and at the same time uploading some 30 responses and at the same time terminating some other register operation.

That said, could you please shed some light on the cancel operation? I am currently not using this function as the the definition is unclear to me. The spec states that this URL is used without a vsID which does not compute as I would think that one shall cancel an operation on a given vsID. Thus, can you please help me understand whether I need to invoke a cancel operation when I try to terminate a vector generation operation.

**Comment by elliemdaw** [comment]
@celic I know some of the server issues were with RSA, esp keygen. I haven't been able to retrieve a vector set today... I tried to register for just one mod for keygen and it has been giving retry:30 for 3+ hours. It is looking for vs 3676... is there a certain parameter I should avoid for now?

**Comment by celic** [comment]
@smuellerDD are you on the Algo Test email list? With that you'll get notice on things like server updates (like the one that occurred this weekend). I don't think we have a nice way of looking at the status of vsIds that are in progress yet. I'll look into this.

**Comment by celic** [comment]
The server is currently on vsId 3674 right now. There was downtime over the weekend which would have stalled everything in the queue. If @smuellerDD also hit the server with a lot of registrations, it's likely that your RSA KeyGen registration came later in the queue. Obviously if the queue doesn't progress, that's when we have a problem. But noting long delays like this helps us justify resource appropriation.

**Comment by smuellerDD** [comment]
Am Montag, 26. März 2018, 22:47:56 CEST schrieb Chris Celi:

Hi Chris,

> @smuellerDD are you on the Algo Test email list? With that you'll get notice
> on things like server updates (like the one that occurred this weekend). I
> don't think we have a nice way of looking at the status of vsIds that are
> in progress yet. I'll look into this.

I am on no email list.

We got a notification from Jason Arnold that we are not entitled to get on 
mailing lists (I hope I have not mis-quoted him though).

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Montag, 26. März 2018, 23:12:44 CEST schrieb Chris Celi:

Hi Chris,

> The server is currently on vsId 3674 right now. There was downtime over the
> weekend which would have stalled everything in the queue. If @smuellerDD
> also hit the server with a lot of registrations, it's likely that your RSA
> KeyGen registration came later in the queue. Obviously if the queue doesn't
> progress, that's when we have a problem. But noting long delays like this
> helps us justify resource appropriation.

I hit the issue on Friday. Over the weekend I only added support for 
additional IUTs to my code without involving the server.

Ciao
Stephan

**Comment by elliemdaw** [comment]
Thanks! I caught that on my end yesterday morning and updated it, so it should be fine now. Still seeing some delay… but based on your comments from earlier I think it must mean there is a queue ahead of me :)

**Comment by hbooth** [comment]
Fix has been deployed if you see any additional problems open a new issue and let us know.
