### ISSUE TITLE
RSA spec: A.1 inconsistent with 2.4.1

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#262]
According to 2.4.1, the capability definitions of "infoGeneratedByServer", "pubExpMode", and "keyFormat" should be part of algSpecs. The example in A.1 shows them one level higher up in the JSON definition.

My JSON based on 2.4.1 looks like:

```
        {
          "algorithm":"RSA",
          "prereqVals":[
            {
              "algorithm":"SHA",
              "valValue":"same"
            },
            {
              "algorithm":"DRBG",
              "valValue":"same"
            }
          ],
          "mode":"keyGen",
          "algSpecs":[
            {
              "randPQ":"B.3.3",
              "infoGeneratedByServer":false,
              "pubExpMode":"random",
              "keyFormat":"standard",
              "capabilities":[
                {
                  "modulo":2048,
                  "hashAlg":[
                    "SHA-1",
                    "SHA2-224",
                    "SHA2-256",
                    "SHA2-384",
                    "SHA2-512"
                  ]
...
```

Though, I did not test this JSON with the server yet.

**Comment by celic** [comment]
They should be moved up yes. This change was done a while ago but it seems some examples were missed.

**Comment by celic** [comment]
Ah I read too quickly. This is the same with #264 . Neither have an issue as the capabilities described in the spec do not contain those additional properties.
