### ISSUE TITLE
RSA spec: A.3 inconsistent with 2.4.3

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#264]
The location of the pubExpMode in the example in A.3 is inconsistent with 2.4.3. The JSON according to 2.4.3 is the following

```
 "algSpecs":[
            {
              "sigType":"pkcs1v1.5",
              "capabilities":[
                {
                  "modulo":2048,
                  "hashPair":[
                    {
                      "hashAlg":"SHA2-224"
                    },
                    {
                      "hashAlg":"SHA2-256"
                    },
                    {
                      "hashAlg":"SHA2-384"
                    },
                    {
                      "hashAlg":"SHA2-512"
                    }
                  ],
                  "pubExpMode":"fixed",
                  "fixedPubExp":"010001"
                },
```

**Comment by celic** [comment]
I don't believe this is the case. The capabilities array is said to contain objects that are a single modulo each, and at least one hashPair object as an array. The `pubExpMode` and `fixedPubExp` are not part of the capabilities array according to the description there, so it is consistent with the example.

**Comment by smuellerDD** [comment]
Ok, I agree. Though, what confused me is that the different JSON hierarchies (capabilities vs algSpecs) are all in one table. May I recommend to use one table per JSON object?

**Comment by atvassilev** [comment]
Closing per discussion.
