### ISSUE TITLE
RSA spec: make fixedPubExp an integer

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#265]
fixedPubExp is defined to be a hex representation of the pub Exp. As this value is an integer, I would recommend to use a JSON integer for this value. Using an integer seems to be more suitable for this value.

**Comment by celic** [comment]
This value could be up to 4096 bits (or whatever modulo length is being used) which would be too large for a JSON integer. While most public exponent values are small, we cannot impose this restriction on all clients.

**Comment by smuellerDD** [comment]
Am Freitag, 16. März 2018, 23:01:26 CET schrieb Chris Celi:

Hi Chris,

> This value could be up to 4096 bits (or whatever modulo length is being
> used) which would be too large for a JSON integer. While most public
> exponent values are small, we cannot impose this restriction on all
> clients.

Right, please disregard this comment then.


Ciao
Stephan
