### ISSUE TITLE
AEAD: taglen allows only up to 6 tag values

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#269]
When providing an AEAD cipher specification with 6 tag values (e.g. 64, 96, 104, 112, 120, 128) for either GCM or CCM, the server accepts the request. However, when providing 7 values (32, 64, 96, 104, 112, 120, 128), the server rejects the setting with the error:

```

  "acv_version" : "0.4",
  "error" : "Incorrectly formatted JSON (1:1798): maximum number of values exceeed for field: tagLen"
}
```

Note, the old CAVS tool allowed the 7 tag values.

**Comment by hbooth** [comment]
this should be fixed now as well
