### ISSUE TITLE
CCM: only up to 2 aadlen entries allowed

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#270]
When providing a CCM specification with 3 aadlen values, the server responds:

```
{
  "acv_version" : "0.4",
  "error" : "Incorrectly formatted JSON (1:1944): maximum number of values exceeed for field: aadLen"
}
```

Note, I try to use the settings I used for the old CAVS tool: aadlen of 0, 256, 524288

**Comment by hbooth** [comment]
I believe this has been resolved (quite some ago actually)
