### ISSUE TITLE
TestGroup Property testType missing for XTS and other Algs

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#271]
For XTS vectors, the testType is missing

**Comment by celic** [comment]
They are all AFT. This might happen on more algorithms that only have a single test type though...

**Comment by smuellerDD** [comment]
Am Dienstag, 20. März 2018, 16:42:17 CET schrieb Chris Celi:

Hi Chris,

> They are all AFT. This might happen on more algorithms that only have a
> single test type though...

May I request to have that added to ensure a full machine-parsable JSON data 
set is issued? To ensure efficient machine-readability, common structures 
should always be adhered to.

Thanks.

Ciao
Stephan

**Comment by celic** [comment]
I agree. This is on our agenda internally. I'll leave this ticket open for now. This may not be an immediate fix unfortunately. If you see a test group without a testType, assume that it is an AFT.

**Comment by smuellerDD** [comment]
Am Dienstag, 20. März 2018, 17:19:15 CET schrieb Chris Celi:

Hi Chris,

> I agree. This is on our agenda internally. I'll leave this ticket open for
> now. This may not be an immediate fix unfortunately. If you see a test
> group without a testType, assume that it is an AFT.

I have developed very generic parser which is agnostic of any data, but knows 
the information structure. This parser is fed with a data model for the 
different cipher specifications. Thus, lacking such structural differences is 
not trivial to handle in my parser.

Since we are in a test mode, I can handle to manually add the AFT though. But 
I am asking for structural consistency before the release.

Ciao
Stephan

**Comment by celic** [comment]
If you notice it missing in an algorithm, let's build a list under this issue to make sure everything gets covered.

**Comment by smuellerDD** [comment]
Am Dienstag, 20. März 2018, 18:14:34 CET schrieb Chris Celi:

Hi Chris,

> If you notice it missing in an algorithm, let's build a list under this
> issue to make sure everything gets covered.

So far, I did not come across any other example. But I will note it if I spot 
such an issue.

Ciao
Stephan

**Comment by smuellerDD** [comment]
ECDSA seems to have no testType (according to the spec).

**Comment by celic** [comment]
All algos should have testType now with our recent JSON parser changes.
