### ISSUE TITLE
XTS: IV is marked as "i" in test vectors

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#272]
Please replace the "i" keywrod with "iv" as used in other symmetric ciphers.

Example test vector:
```
[ {
  "acvVersion" : "0.4"
}, {
  "vsId" : 3062,
  "algorithm" : "AES-XTS",
  "testGroups" : [ {
    "testType" : "AFT",
    "direction" : "encrypt",
    "keyLen" : 128,
    "tweakMode" : "hex",
    "ptLen" : 128,
    "tests" : [ {
      "tcId" : 1,
      "key" : "18D61B9C889EFF759B1FBFD114ACA769F9CC66FB14B92E814B9A3E28D07DF993",
      "i" : "66AF129F285BE2D9D4A70B80EC6D475E",
      "pt" : "ED6B21422FC3FE02ADE105D948C69836"
    }, {
```

**Comment by celic** [comment]
`i` is correct here. This does not refer to the IV. It refers to the tweak value. The choice in variable was modeled after CAVS. Perhaps that needs to change, as this issue was brought up previously.

**Comment by smuellerDD** [comment]
Am Dienstag, 20. März 2018, 16:41:01 CET schrieb Chris Celi:

Hi Chris,

> `i` is correct here. This does not refer to the IV. It refers to the tweak
> value. The choice in variable was modeled after CAVS. Perhaps that needs to
> change, as this issue was brought up previously.

It is not documented in the spec. And it would be great to change this keyword 
to something that is more understandable like "tweakValue" or similar.

Note, the tweak is usually handled similar to an IV. A lot of APIs that have 
XTS implemented get their tweak via the IV pointer as XTS does not need a 
"real" IV.

Ciao
Stephan

**Comment by celic** [comment]
Makes sense. I'm totally on board for making the name more understandable (considering this is the second time I'm answering this issue...) I'm not in favor of using `"iv"` because it isn't directly an IV for XTS in the same way other symmetric ciphers use the IV. I do like `"tweakValue"` because that is directly relevant to the context of XTS, and people working with the algorithm would be able to recognize that.

**Comment by smuellerDD** [comment]
Am Dienstag, 20. März 2018, 17:22:41 CET schrieb Chris Celi:

Hi Chris,

> Makes sense. I'm totally on board for making the name more understandable
> (considering this is the second time I'm answering this issue...) I'm not
> in favor of using `"iv"` because it isn't directly an IV for XTS in the
> same way other symmetric ciphers use the IV. I do like `"tweakValue"`
> because that is directly relevant to the context of XTS, and people working
> with the algorithm would be able to recognize that.

Perfect, I am all for "tweakValue".


Ciao
Stephan

**Comment by atvassilev** [comment]
Where do we stand with respect to this issue? Can it be closed?

**Comment by celic** [comment]
The server and gen/vals need to be updated to reflect the spec changes.

**Comment by smuellerDD** [comment]
The current XTS vectors still look like the initial ones:
```
[ {
  "acvVersion" : "0.5"
}, {
  "vsId" : 75,
  "algorithm" : "AES-XTS",
  "isSample" : false,
  "testGroups" : [ {
    "tgId" : 1,
    "testType" : "AFT",
    "direction" : "encrypt",
    "keyLen" : 128,
    "ptLen" : 128,
    "tweakMode" : "hex",
    "tests" : [ {
      "tcId" : 1,
      "key" : "16E4E18B603FAD659AB4C926E685E0D7F7712F9E3767FEBAE079E836E2F40D14",
      "pt" : "28F568D6FDCCAF14DA12C82C66CDF2F0",
      "i" : "E43CDA602EACED7808C175BDE4A9059E"
    }, {
```

I thought we replace "i" somehow?

**Comment by celic** [comment]
Sorry. With the update to v0.5, we updated our JSON parser and some of these changes slipped. This is fixed and will appear in our next update.

**Comment by smuellerDD** [comment]
Confirmed, working
