### ISSUE TITLE
RSA keygen: spec inconsistency with real test vector

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#275]
The following inconsistencies are visible:

- testType of "kat" not defined
- testType of "gdt" not defined
- primeResult should be of type boolean (the example indicates it is a text field)

The vector for testType of gdt contains
```
  }, {
    "modulo" : 2048,
    "testType" : "gdt",
    "randPQ" : "B.3.3",
    "pubExpMode" : "random",
    "keyFormat" : "standard",
    "primeTest" : "tblC2",
    "tests" : [ {
      "tcId" : 103,
      "deferred" : true
    }, {
      "tcId" : 104,
      "deferred" : true
```

What shall I do with that?

**Comment by celic** [comment]
The GDT testType refers to Section 6.2.2.2 in this document https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/dss2/rsa2vs.pdf

**Comment by smuellerDD** [comment]
How shall the output be formatted?

**Comment by celic** [comment]
This is listed in the examples of the RSA spec. See section C.1. They are the last test cases in that example.

**Comment by smuellerDD** [comment]
Thanks for the hints. But may I ask to incorporate that into the spec?

With that, I can generate the results.

**Comment by celic** [comment]
Of course. That is something we would like to include more of... actually explaining what process the tests are exercising and why.

**Comment by celic** [comment]
With #276 I'm going to close this issue. Though this relates back to #48

**Comment by celic** [comment]
Sorry, issue #122
