### ISSUE TITLE
RSA siggen: spec inconsistency with real test vector

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#276]
The following inconsistencies are visible:

* testType "GDT" is not defined
* hashAlg string is different from the hash ciphers (SHA2-XXX vs SHA-XXX) - please make it consistent

**Comment by celic** [comment]
Do you have an example in the spec for the hashAlg? Or an example of what you got back from the server with a mismatch?

**Comment by smuellerDD** [comment]
I just changed the subject. I meant siggen with this issue.

Here is what I got

```
[ {
  "acvVersion" : "0.4"
}, {
  "vsId" : 3173,
  "algorithm" : "RSA",
  "mode" : "sigGen",
  "testGroups" : [ {
    "sigType" : "pkcs1v1.5",
    "modulo" : 2048,
    "hashAlg" : "SHA2-224",
    "testType" : "GDT",
    "tests" : [ {
```

**Comment by celic** [comment]
So where in the spec does it differ? I just went through and I couldn't find what you were referring to.

**Comment by atvassilev** [comment]
I am reviewing your PR #277 and compile a list of inconsistencies - will publish it shortly.

**Comment by smuellerDD** [comment]
I would like that the "hashAlg" uses the same strings as used for the hash. 

The hash spec:

3.  Supported Hash Algorithms

   The following hash algorithms may be advertised by this ACVP
   compliant crypto module:

   o  SHA-1

   o  SHA-224

   o  SHA-256

   o  SHA-384

   o  SHA-512

   o  SHA-512/224

The RSA spec does not say anything, but the test vector uses a different string for the hash reference.

**Comment by atvassilev** [comment]
@celic I think I resolved the conflicts and the SHA spec artifacts are now in sync.

**Comment by atvassilev** [comment]
Closing per discussion.

**Comment by smuellerDD** [comment]
Please note that the test vectors returned by the server still contain SHA-XXX instead of SHA2-XXX

**Comment by smuellerDD** [comment]
The SHA ciphers for the hashing algorithms are still not in sync with the other use cases of SHA:

For example:

```
[ {
  "acvVersion" : "0.5"
}, {
  "vsId" : 85,
  "algorithm" : "SHA-224",
```

**Comment by Kritner** [comment]
Just to double check - this issue applies to what the server is responding with for the SHA2 capabilities and is unrelated to RSA at this point, correct?

**Comment by smuellerDD** [comment]
That is correct. It only applies to SHA2 registrations. For all other cases where SHA2 is used (signatures, DRBG, etc) the naming of SHA2-XXX is used.

**Comment by smuellerDD** [comment]
confirmed, working.
