### ISSUE TITLE
Feature request: add expected results for failing verdicts

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#280]
As discussed previously, when a test verdict is issued, a vcID is closed and cannot be reused again.

May I propose that in the verdict reply, the server returns the expected result in case an error is triggered? I am aware that this is only possible for a subset of tests, i.e. those operating as KAT. But this would be already more than nothing.

I would propose to add a new JSON object to a failing tcID that contains exactly the correctly formatted response. Example for a verdict response: of a HMAC

```
  "results" : {
    "vsId" : 3259,
    "disposition" : "passed",
    "tests" : [ {
      "tcId" : 1,
      "result" : "passed"
    }, {
      "tcId" : 2,
      "result" : "fail"
      "expected": {
          "mac":"e991a29bbd5692c4dd8b41267ac1c1972884efe4"
      }
    }, {
...
```

**Comment by hbooth** [comment]
The fact that you cannot resubmit is currently considered a bug and is not intended behavior.

Coincidentally, we discussed this very issue on Tuesday and came up with the exact same solution you describe for returning answers. An internal issue has already been added for tracking and will likely be worked on in a future sprint for us. In the meantime we are adding in a feature for requesting a "sample"
that will allow for clients to register and then request vectors and expected results. We plan to add both of these features into the spec as it gets implemented.

**Comment by atvassilev** [comment]
This will have to wait for v0.5, being worked on now but will released later.

**Comment by Kritner** [comment]
This feature is now on demo, it can be exercised with the following POST/PUT to the `/acvp/v1/testSessions/{tsId}}/vectorSets/{vsId}/results` endpoint:

```json
[
  {
    "acvVersion": "{acv_version}"
  },
  {
    "vsId": {vs_id},
    "showExpected": true,
    "testGroups": {test_results}
  }
]
```

Note `"showExpected": true` being the important bit.

I'm not sure if we want to update the specification and tag this issue, or have a separate issue for specification updates, but the function is now available on demo.

**Comment by smuellerDD** [comment]
Am Dienstag, 26. Mai 2020, 15:45:35 CEST schrieb Russ Hammett:

Hi Russ,

> This feature is now on demo, it can be exercised with the following POST/PUT
> to the `/acvp/v1/testSessions/{tsId}}/vectorSets/{vsId}/results` endpoint:
> 
> ```json
> [
>   {
>     "acvVersion": "{acv_version}"
>   },
>   {
>     "vsId": {vs_id},
>     "showExpected": true,
>     "testGroups": {test_results}
>   }
> ]
> ```
> 
> Note `"showExpected": true` being the important bit.
> 
> I'm not sure if we want to update the specification and tag this issue, or
> have a separate issue for specification updates, but the function is now
> available on demo.

Just a question: why can't the existing endpoint for getting sample vectors be 
used?

Ciao
Stephan

**Comment by Kritner** [comment]
`sample` is a bit different than `showExpected`.  The idea behind sample is, at registration time, the ACVP server will act as both parties to the test session, meaning it generates everything up front, all files that will be needed from both the server and client perspective.  the `showExpected` flag on a results POST/PUT will change only the validation response from the ACVP server to the client, giving "the server version" of the answer in comparison to what the client provided, on a per test case basis.

the `sample`s have a slightly different "target audience" than the `showExpected` I would say.  Samples would seemingly help give a better overall understanding of the "flow" of a specific algorithm, whereas `showExpected` will help for debugging a specific algorithm's answers in comparison to the acvp server.

Hopefully that makes sense!

**Comment by smuellerDD** [comment]
Am Dienstag, 26. Mai 2020, 16:12:20 CEST schrieb Russ Hammett:

Hi Russ,

> `sample` is a bit different than `showExpected`.  The idea behind sample is,
> at registration time, the ACVP server will act as both parties to the test
> session, meaning it generates everything up front, all files that will be
> needed from both the server and client perspective.  the `showExpected`
> flag on a results POST/PUT will change only the validation response from
> the ACVP server to the client, giving "the server version" of the answer in
> comparison to what the client provided, on a per test case basis.
> 
> the `sample`s have a slightly different "target audience" than the
> `showExpected` I would say.  Samples would seemingly help give a better
> overall understanding of the "flow" of a specific algorithm, whereas
> `showExpected` will help for debugging a specific algorithm's answers in
> comparison to the acvp server.
> 
> Hopefully that makes sense!

It does.

Confirmed, working:

```
      {
        "tcId": 1,
        "result": "failed",
        "reason": "Cipher Text does not match",
        "expected": {
          "cipherText": "0336763E966D92595A567CC9CE537F5E"
        },
        "provided": {
          "cipherText": "0336763E966D92595A567CC9CE537F5F"
        }
      },

```

Ciao
Stephan
