### ISSUE TITLE
RSA: case of testType values 

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#281]
The case of the testType keyword is capital for all cipher except RSA. Especially this is of importance for testType "AFT" (all other ciphers) or testType "aft" (for RSA B.3.2 keygen).

Please use consistent cases.

**Comment by atvassilev** [comment]
Has this been resolved by the recent RSA spec updates?

**Comment by celic** [comment]
It is not a spec issue. This is a gen/val problem and will be addressed in v0.5 along with #271

**Comment by celic** [comment]
This was fixed some time ago, but is noted as done with Server release v0.5.2.
