### ISSUE TITLE
RSA keygen: bitlens field

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#282]
The RSA spec contains the bitlens keyword that needs to be returned for some keygens. However, this value was never required to be returned in the "old" CAVS testing.

May I ask to check whether this field is really necessary to be returned by an IUT?

**Comment by celic** [comment]
This field is required for when the IUT generates the values to be used for testing. The server needs to know the exact bitlength of XP1, XP2, XQ1, XQ2. I believe this was the case in CAVS again when the IUT generated the values for testing.

**Comment by smuellerDD** [comment]
Am Freitag, 23. März 2018, 17:01:41 CET schrieb Chris Celi:

Hi Chris,

> This field is required for when the IUT generates the values to be used for
> testing. The server needs to know the exact bitlength of XP1, XP2, XQ1,
> XQ2. I believe this was the case in CAVS again when the IUT generated the
> values for testing.

I am just updating an existing CAVS test harness for a given module to ACVP. 
There I have a key gen with provable primes (B.3.2). I can fill all data with 
teh existing code, except the bitlens field. Thus, the bitlens is something 
additional (at least for B.3.2) compared to the old CAVS testing. Note, B.3.2 
does not return XP1 and friends, but only n, d, p, q and e. Thus, I would even 
wonder why the bitlens field is needed.

Ciao
Stephan

**Comment by celic** [comment]
Bitlens is not a required field for B.3.2. If you are running into a situation where it is being expected for a B.3.2 registration, then that would be a bug. It is hard to express these "sometimes required" fields in the spec, which is something we have noted before.

**Comment by smuellerDD** [comment]
Am Freitag, 23. März 2018, 17:16:39 CET schrieb Chris Celi:

Hi Chris,

> Bitlens is not a required field for B.3.2. If you are running into a
> situation where it is being expected for a B.3.2 registration, then that
> would be a bug. It is hard to express these "sometimes required" fields in
> the spec, which is something we have noted before.

The spec for bitlens states:

 | bitlens    | the length of p1, p2, q1,    | array of   | Yes      |
   |            | and q2 for prime generation  | ints       |          |
   |            | according to [FIPS186-4],    |            |          |
   |            | Appendix B.3.2, B.3.4, B.3.5 |            |          |
   |            | or the length of xP1, xP2,   |            |          |
   |            | xQ1, and xQ2 for B.3.6       |            |          |

So, the spec indicates it would be needed for B.3.2. Maybe the spec needs to 
be updated?

Ciao
Stephan

**Comment by celic** [comment]
You would be correct.

**Comment by celic** [comment]
I think this was handled with #303 and can be closed. There is no bug in the gen/val code.
