### ISSUE TITLE
RSA sigver: all signatures are correct?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#283]
RSA sigver PKCS 1.5 test vectors: when processing the vectors with two different cipher implementations, all signatures match. Is this really intended?

Granted, I cannot verify my result with the server yet, because of the already discussed formatting issue.

**Comment by celic** [comment]
This is not the intended behavior. Could you please send the vsId?

**Comment by celic** [comment]
I think I've identified the bug on the back end. Thank you for pointing this out. I'll work on a fix soon.

**Comment by celic** [comment]
I'd still like the vsId if possible.

**Comment by smuellerDD** [comment]
Am Freitag, 23. März 2018, 18:41:24 CET schrieb Chris Celi:

Hi Chris,

> I'd still like the vsId if possible.

Just downloaded a fresh set: 3622



Ciao
Stephan

**Comment by celic** [comment]
The fix for this was deployed to our internal environment. I'll update this ticket when it becomes available externally.

**Comment by hbooth** [comment]
Fix has been deployed.
