### ISSUE TITLE
XTS: maximum plaintext size

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#289]
The ptlen size is defined to be in bits. The old CAVS tool allowed to specify that for XTS, the maximum plaintext is 2^16. Thus, the ptlen size would be 524288.

However, the server only accepts 65536 which seems to be too low:
```
{
  "acv_version" : "0.4",
  "error" : "Property value(524288) for (pt) in Algorithm (AES-XTS (null)) is not valid. Validation: (Number Between (128) and (65536) modulus 1)"
}
```

**Comment by celic** [comment]
2^16 bytes or bits? The value looks correct for bits which is what ACVP uses when size is concerned by default. CAVS I believe uses bits for this form as well capping the registration at 2^16 bits, or 65536 bits. Though CAVS does not reference bits or bytes directly on those boxes...

**Comment by smuellerDD** [comment]
Am Mittwoch, 28. März 2018, 16:18:12 CEST schrieb Chris Celi:

Hi Chris,

> 2^16 bytes or bits?

Hm, this is the question. I was under the impression that the old CAVS tool 
requested the size in bytes.

The XTS test spec says: "Specify the largest block size supported by the 
implementation or check
the 2^16 box, whichever is larger."

Thus, it sounds to be that the value is in bytes.

> The value looks correct for bits which is what ACVP uses
> when size is concerned by default. CAVS I believe uses bits for this form
> as well capping the registration at 2^16 bits, or 65536 bits. Though CAVS
> does not reference bits or bytes directly on those boxes...

So, are you saying that the quote above implies bits?

Ciao
Stephan

**Comment by celic** [comment]
I can't find anything in this document https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/aes/XTSVS.pdf that says whether that value is bits or bytes. When implementing XTS for the server, I made the assumption that it was bits. I'm going to do a bit more digging and have some discussions on our end.

**Comment by celic** [comment]
I generated some files with CAVS and they do come out to be 65536 bits, not bytes, when the 2^16 check box is selected.
