### ISSUE TITLE
DRBG valid values

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#291]
I know that some of the acceptable values for DRBG are outlined in other NIST docs... is it intended to be more explicitly outlined in the ACVP specs somewhere down the line? If so, the RSA spec could use some more detail in this area as well :) not a blocking issue, just thought I'd ask since it could simplify the process of constructing a client registration if all the details were in one document.

Thank you!

**Comment by celic** [comment]
Please see pg 38 and 49 from [SP800-90A](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-90Ar1.pdf) for the allowed fields. At some point down the road, these tables should be added into this spec (or at least referenced...)

**Comment by Kritner** [comment]
@hbooth this commit (currently slated for a 0.5 change), has some driver related changes to min/max requirements on capability registration
