### ISSUE TITLE
RSA keygen errors

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#295]
I am getting this when I query for the disposition after RSA keygen

      "result" : "fail",
      "reason" : "Unexpected failure"

But I implemented the "isSample" attribute and the values that I get back from that are matching what I am sending over.

**Comment by atvassilev** [comment]
Can this issue be closed now?

**Comment by elliemdaw** [comment]
The vectors took significantly longer to retrieve again, but they all passed as expected.

**Comment by atvassilev** [comment]
OK, thanks for confirming. We will be looking into performance improvements in v0.5.
