### ISSUE TITLE
CMAC: use JSON boolean for testType "ver"

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#298]
The CMAC testType "ver" requires the string "pass" and "fail". Please convert to boolean.

**Comment by atvassilev** [comment]
This seems also related to #244

**Comment by smuellerDD** [comment]
Indeed, it is similar to #244, but the required strings are different. Thus, I have different unparser for CMAC ver and RSA. I would like to get rid of those and use my generic boolean unparser. :-)

**Comment by atvassilev** [comment]
Once we agree on #244, we will clean up all remaining specs, including this one.

**Comment by Kritner** [comment]
FYI this will be covered under issue #244, closing as it has been accounted for in list of algos that need updating.
