### ISSUE TITLE
TOTP authtoken refresh: server side thread safe?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#300]
As you know, I am using a threaded retrieval and submission of test vectors and responses. I.e. my tool supports up to 32 concurrent connections for either fetching test vectors or submitting responses and getting the verdict.

That all worked flawless until TOTP. I am not yet sure where the issue is, so I am simply asking the question to the server developers to try to track down the issue.

During the initial fetching of the test vectors, threading works flawless. Threading is also flawless when submitting the results to the server within the 30 minutes window where the original auth token is valid.

Though, when I have several test responses available whose test vectors were obtained more than 30 minutes ago, my code automatically performs a authentication token refresh. That works single threaded. When doing multiple threads in parallel, each thread performs its refresh authentication before the real data submission:

```
[{"acvVersion":"0.4"},{"password":"xxxx","accessToken":"yyy"}]
```

The first thread gets a valid refreshed authentication token. But all other threads receive:

```
{
  "acv_version" : "0.4",
  "error" : "The supplied one time password could not be verified"
}
```

Note, the 6 digit password is identical for all threads, which is expected because all start at the same time and thus have the same TOTP value.

**Comment by smuellerDD** [comment]
Additional note: when I have the mentioned multiple results with expired auth tokens and I submit them in a serial fashion (with the same auth token refresh code), I can authenticate.

**Comment by atvassilev** [comment]
Thinking through your scenario, I find it problematic. Supplying the same TOTP value several times to the same server would have to succeed the first time and fail every subsequent time until the next time step. Otherwise, what is the point of calling it a one-time-password? I think conceptually you need to handle authentication differently, not on a per-thread basis. You may want to think about a single thread taking care of authentication, token refreshing, etc and allow the other threads to impersonate that thread when accessing the server by borrowing its fresh token.

**Comment by smuellerDD** [comment]
Am Montag, 2. April 2018, 18:00:01 CEST schrieb Apostol Vassilev:

Hi Apostol,

> Thinking through your scenario, I find it problematic. Supplying the same
> TOTP value several times to the same server would have to succeed the first
> time and fail every subsequent time until the next time step. Otherwise,
> what is the point of calling it a one-time-password? I think conceptually
> you need to handle authentication differently, not on a per-thread basis.
> You may want to think about a single thread taking care of authentication,
> token refreshing, etc and allow the other threads to impersonate that
> thread when accessing the server by borrowing its fresh token.

What this means is that if I want to upload, say, 50 results, I have to wait 
25 minutes to just get the token refreshed?

But for refreshing, you need the OTP + the previous auth token. Thus, in this 
case having multiple identical OTP values should not violate the basic 
requirements you need the OTP value for as you have 2 tokens for the refhresh 
authentication token.

Ciao
Stephan

**Comment by atvassilev** [comment]
I am not saying you should wait 25 minutes but you should redesign your authentication logic to handle it more gracefully for the multi-threaded client.

**Comment by smuellerDD** [comment]
Am Montag, 2. April 2018, 19:32:40 CEST schrieb Apostol Vassilev:

Hi Apostol,

> I am not saying you should wait 25 minutes but you should redesign your
> authentication logic to handle it more gracefully for the multi-threaded
> client.

Sorry for not being clear. Let us assume I have 50 vsIDs that I have test 
results for. Now I want to upload them to the server to get answers. Each vsID 
has its own authtoken. All 50 vsIDs have been obtained more than 30 minutes 
ago. Thus, I would at least need to wait 30 seconds between each vsID upload 
(i.e. the step size of TOTP) before I can obtain a new auth token.

In total, that would mean that it takes me 25 minutes to get all authtokens 
updated and thus all vsIDs submitted.

(Naturally would I upload a vsID immediately once I have its authtoken 
updated.)

Ciao
Stephan

**Comment by locksmithone** [comment]
I see the point of the multi-threaded client unique TOTP issue...

Yet, RFC 6238 does state that the TOTP value must only be accepted once
within the time window. Section 5.2:
"

Note that a prover may send the same OTP inside a given time-step
   window multiple times to a verifier.  The verifier MUST NOT accept
   the second attempt of the OTP after the successful validation has
   been issued for the first OTP, which ensures one-time only use of an
   OTP."


MP

**Comment by atvassilev** [comment]
@smuellerDD, again you should consider delegating the authentication to a single thread tasked to manage this and assist all other worker threads with it. In this way, you will mimic most modern OS who use a similar mechanism for delegating access and privileges to working processes and threads.

**Comment by smuellerDD** [comment]
Am Montag, 2. April 2018, 20:46:44 CEST schrieb Apostol Vassilev:

Hi Apostol,

> @smuellerDD, again you should consider delegating the authentication to a
> single thread tasked to manage this and assist all other worker threads
> with it. In this way, you will mimic most modern OS who use a similar
> mechanism for delegating access and privileges to working processes and
> threads.

That would only work if a given authentication token is not related to a vsID. 
Would that be the case?

Ciao
Stephan

**Comment by smuellerDD** [comment]
I now added a grace time of 35 seconds between each re-auth attempt to ensure I have different passcodes. Yet, the server rejects my second passcode. Even sometimes it rejects my first passcode.

**Comment by smuellerDD** [comment]
After base64 decoding the auth token, I see a list of vsIDs in there. Does that mean that one auth token pertains to this set of vsIDs? If so, does the ACVP server somehow provides an identifier which vsIDs belong to one session covered by one auth token?

Does this ultimately mean that I need to refresh the auth token for the given set of vsIDs once and then reuse it for all communication for these vsIDs?

**Comment by hbooth** [comment]
I apologize for joining this discussion late, I was playing a bit of catch-up yesterday unfortunately. There is a concept of a "Test Session" and each "Test Session" has one or more "Vector Sets" associated with it. A single registration covers a single "Test Session" and every vector set id associated with the "Test Session" can be accessed using the access token provided with the registration response.

One issue with failures may be some clock skew. The NIST servers are synchronized with the NIST time servers. Please verify that the time you are using is also synchronized with the NIST time server. The current TOTP implementation is fairly simplistic, but over time we will consider adding additional features that can account for synchronization issues and will reject multiple OTP submissions.

**Comment by smuellerDD** [comment]
Am Dienstag, 3. April 2018, 15:12:12 CEST schrieb Harold Booth:

Hi Harold,

> I apologize for joining this discussion late, I was playing a bit of
> catch-up yesterday unfortunately. There is a concept of a "Test Session"
> and each "Test Session" has one or more "Vector Sets" associated with it. A
> single registration covers a single "Test Session" and every vector set id
> associated with the "Test Session" can be accessed using the access token
> provided with the registration response.

Thanks to both for pointing me to the test session. I disregarded that concept 
up to now. Now it is more clear.

I will use the test session-based auth credentials management.
> 
> One issue with failures may be some clock skew. The NIST servers are
> synchronized with the NIST time servers. Please verify that the time you
> are using is also synchronized with the NIST time server. The current TOTP
> implementation is fairly simplistic, but over time we will consider adding
> additional features that can account for synchronization issues and will
> reject multiple OTP submissions.

I also have a fairly simplistic TOTP algo. My time is set based on NTP.


Ciao
Stephan
