### ISSUE TITLE
AES-OFB: How to interpret "00000000000000000000000000000000"?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#301]
I have tested the following type of data with two different cipher implementations. Both implementations return the same data. Yet, the server flags my results as a failure:

```
    "tests" : [ {
      "tcId" : 1,
      "iv" : "00000000000000000000000000000000",
      "key" : "00000000000000000000000000000000",
      "pt" : "F34481EC3CC627BACD5DC3FB08F273E6"
    }, {
      "tcId" : 2,
      "iv" : "00000000000000000000000000000000",
      "key" : "00000000000000000000000000000000",
      "pt" : "9798C4640BAD75C7C3227DB910174E72"
    }, {
```

I.e all vectors with iv and key "00000000000000000000000000000000", I have a 16 byte buffer which contains all zeros. As the server flags my results shown below as failure, I would imply that I somehow have to interpret the data differently.

Results:
```
    "testResults":[
      {
        "tcId":1,
        "ct":"95adca38d34c0b81451139a2c2c658c8"
      },
      {
        "tcId":2,
        "ct":"f1718fb0e42759fc4b6e87e0da23655c"
      },
      {
```

**Comment by smuellerDD** [comment]
Note, I saw some changes in the OFB test vectors between now and a week or two ago. Previously, I have not seen such zero buffers.

**Comment by celic** [comment]
The only place where a key/iv pair like this should appear is in a KAT testType group. Can you confirm that this is the case? Or is this in a different testGroup?

**Comment by smuellerDD** [comment]
Am Montag, 2. April 2018, 19:02:31 CEST schrieb Chris Celi:

Hi Chris,

> The only place where a key/iv pair like this should appear is in a KAT
> testType group. Can you confirm that this is the case? Or is this in a
> different testGroup?

Confirmed.

Ciao
Stephan

**Comment by celic** [comment]
Sorry, just to be super clear. This is in a KAT testType group? I'll take a look to make sure what's happening. I have an idea on this. There are some KATs that do provide 0s for two fields, but I'm not sure on the exact status of OFB.

**Comment by celic** [comment]
Your data is interpreted correctly and running the server-side crypto library returns the same result you got. I'm going to keep investigating, but I wanted to inform you of that much.

**Comment by celic** [comment]
And one last question, does the server return a failed test when you run other AES modes with KATs?

**Comment by Kritner** [comment]
@celic IIRC "KAT"s are remapped to "AFT" on the driver end, I believe AES only has "AFT" and "MCT" test groups.

**Comment by celic** [comment]
@Kritner you are correct. (I forgot about that). But I did find the KAT with that exact plaintext with a different ciphertext. I know OFB does some shuffling of the data though so I'm trying to figure out where the discrepancy comes in.

**Comment by celic** [comment]
This has been fixed and we are deploying it shortly.

**Comment by celic** [comment]
Try it again now @smuellerDD and let me know the results.

**Comment by smuellerDD** [comment]
Am Dienstag, 3. April 2018, 17:04:57 CEST schrieb Chris Celi:

Hi Chris,

> Try it again now @smuellerDD and let me know the results.

It may take me a bit as I am half way through reorganizing the authentication 
logic.

Ciao
Stephan

**Comment by celic** [comment]
No rush. Feel free to close the issue when you can confirm the fix is satisfactory.

**Comment by smuellerDD** [comment]
Confirmed that the change fixes the issue.

My new test response for an OFB is marked passing by the ACVP server
