### ISSUE TITLE
Server error: clock skew

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#302]
Whie requesting a CTR-DRBG test vector, I get:

```
{
  "acv_version" : "0.4",
  "error" : "JWT expired at 2018-04-02T12:59:44Z. Current time: 2018-04-02T12:59:54Z, a difference of 10351 milliseconds.  Allowed clock skew: 0 milliseconds."
}
```

**Comment by smuellerDD** [comment]
I see that now for SHA test response submissions.

**Comment by hbooth** [comment]
While the error message is admittedly a tad confusing (it is coming straight from the JWT library we are using) this appears to be indicating that the JWT has expired (only ten seconds prior interestingly enough). One of the improvements I would like to make is to have a small list of error codes specific to the ACV protocol itself (as opposed to using HTTP status codes) that will allow the server to communicate these types of errors. All we can throw right now is a 401 unauthorized, but we aren't able to communicate (except in text) that the error is the result of a JWT expiration.

**Comment by smuellerDD** [comment]
I am in the process of updating the TOTP handling to a per-testsession basis. I will close the issue for now as I think it may relate to the authtoken refresh logic.
