### ISSUE TITLE
SHA-1: server error

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#317]
When requesting a SHA-1 test vector, I get:

```
{
  "vsId" : 381,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 381"
} ]
```

**Comment by celic** [comment]
We were able to reproduce this internally and are testing a fix now. Thanks!

**Comment by celic** [comment]
This is fixed. Try it again, and close the issue if the problem is gone.

**Comment by smuellerDD** [comment]
Confirmed, working.
