### ISSUE TITLE
RSA keygen B.3.3 testtype KAT: server side test response validation seems broken

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#318]
I am very sure that my module implementation is currently unable to process the B.3.3 data correctly because it overwrites the provided p/q values with their own, newly generated values. This implies that all test results for the KAT test type are "pass". However, I tested with another cipher implementation that some test vectors will cause the RSA keygen to fail.

Now, when submitting the all passing test responses, the server tells me that the verdict is pass for those. This cannot be correct.

VsID: 393

**Comment by celic** [comment]
I'm sorry for needing clarity here... but you are saying that the server says all the KATs should be "passed"?

**Comment by smuellerDD** [comment]
Am Montag, 9. April 2018, 21:04:44 CEST schrieb Chris Celi:

Hi Chris,

> I'm sorry for needing clarity here... but you are saying that the server
> says all the KATs should be "passed"?

Sorry for being unclear.

The test requires the module to process some provided Ps and Qs to generate an 
RSA key. Some of those Ps and Qs are modified in order for the RSA keygen to 
fail.

However, my IUT will overwrite the the Ps and Qs with newly generted ones 
which will *always* successfully generate an RSA key. This means that for 
*all* Ps and Qs provided by the ACVP server, my IUT returns a passing RSA 
keygen (even though it should fail some). 

Yet, the ACVP server returns the verdict of pass for all responses knowing 
that for some that this is not true.

Note, I verified with a different implementation that some of the Ps and Qs 
will fail an RSA keygen.

Ciao
Stephan

**Comment by celic** [comment]
Yes. So if you compare the resulting P and Q from your module against the original from the prompt file, if there is a change in either value, then you should return "failed" to the server. If there is no change in P and Q, then you should return "passed". These KATs are set up to determine if the IUT can tell if the key pair is valid. Ideally this reduces the risk of a validated implementation using this method to generate bad keys. 

If you have any other questions about this let me know. Otherwise, please mark this as closed.

**Comment by smuellerDD** [comment]
Am Montag, 9. April 2018, 21:13:22 CEST schrieb Chris Celi:

Hi Chris,

> Yes. So if you compare the resulting P and Q from your module against the
> original from the prompt file, if there is a change in either value, then
> you should return "failed" to the server. If there is no change in P and Q,
> then you should return "passed". These KATs are set up to determine if the
> IUT can tell if the key pair is valid. Ideally this reduces the risk of a
> validated implementation using this method to generate bad keys.

I am not pointing out that my IUT has a problem. I am trying to point out that 
the ACVP server returns a verdict that my wrong answers are all given a "pass" 
verdict.

I.e. the ACVP server verdict seems to be wrong.
> 
> If you have any other questions about this let me know. Otherwise, please
> mark this as closed.



Ciao
Stephan

**Comment by celic** [comment]
Ah ok. Sorry I misunderstood. I'll investigate this.

**Comment by celic** [comment]
Found the issue. I'll get a fix deployed soon. I'll update this ticket when I get confirmation that it is on the external environment.

**Comment by celic** [comment]
This was deployed, try it again just to confirm the problem has been fixed.

**Comment by smuellerDD** [comment]
Confirmed working: I see the expected failing verdict.
