### ISSUE TITLE
ECDSA keyGen error

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#320]
"error" : "Algorithm ECDSA (keyGen) is unknown or not currently supported."

when registering with:
                    "algorithm": "ECDSA",
                    "mode": "keyGen", ...

**Comment by celic** [comment]
This is against the specification though. And should occur on DSA as well. We will fix this quickly.

**Comment by celic** [comment]
This has been fixed, try it again just to confirm. The server should be in line with the spec now and use `"keyGen"` for mode.

**Comment by elliemdaw** [comment]
Yes, this is fixed. Thank you!
