### ISSUE TITLE
Case sensitivity in ECDSA

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#321]
Related to #320 - the "hashAlg" attribute seems to also be case sensitive. I am including the hashAlgs in all caps like the spec has them (as well as the other algs that the server supports) and getting the following error:

"Property value(SHA2-224) for (hashAlg) in Algorithm (ECDSA (sigGen)) is not valid. Validation: (Values must be one of: sha2-224, sha2-256, sha2-384, sha2-512, sha2-512/224, sha2-512/256)"

**Comment by celic** [comment]
Thanks for catching this. I've updated the schema on the back-end to match the spec and other algorithms.

**Comment by hbooth** [comment]
Fix deployed
