### ISSUE TITLE
RSA spec: hashAlg data type inconsistent

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#322]
The RSA spec defines the hashAlg as a JSON value in 3.1 but the examples show it as array.

Furthermore, 2.4.4 specifies hashAlg as an array.

May I ask to use one data type for hashAlg?

**Comment by smuellerDD** [comment]
Please disregard this report - I mixed capabilities with test vectors.

**Comment by celic** [comment]
Are there any other tcIds producing the wrong disposition like this? Or is this the only one?

**Comment by smuellerDD** [comment]
There are others, some with missing Q, some with both P and Q.

Note, there is always the possibility that my IUT has an issue (or my parser). But since I think (or I hope) I did not change anything for RSA keygen in my parser and considering that the IUT worked in the past, I needed to raise the question whether there is an issue on the server side. As I only have one IUT that has a working B.3.3 support, I cannot even verify that with a different IUT.

**Comment by celic** [comment]
Yeah clearly that test case is intended to fail. And that is what the server reports as well. What was your vsId so I can take a look at exactly what was submitted?

**Comment by smuellerDD** [comment]
Am Mittwoch, 11. April 2018, 20:48:07 CEST schrieb Chris Celi:

Hi Chris,

> Yeah clearly that test case is intended to fail. And that is what the server
> reports as well. What was your vsId so I can take a look at exactly what
> was submitted?

743

Ciao
Stephan

**Comment by celic** [comment]
Ah yeah. Unfortunately the server expects just "result" not "primeResult" here. We will fix that in the future for v0.5, but as for v0.4 and the meantime, it will stay as is. Sorry about that.

**Comment by smuellerDD** [comment]
ok, I changed that
