### ISSUE TITLE
Linked docs in GitHub README

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#325]
The doc links for the TOTP specs in the README require permissions to be able to read them. Is this the intention?

Thanks!

**Comment by atvassilev** [comment]
Yes, for now. We are not allowed to post documents for public viewing without approval from NIST. The spec is undergoing internal review and when finished, it will be published on GitHub as public. Sorry about this inconvenience and thanks for your patience.

**Comment by atvassilev** [comment]
Closing this issue, will publish the spec when internal review process completes.
