### ISSUE TITLE
RSA Siggen PSS

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#327]
All my signatures compliant to PSS are rejected by the server with the following statement:

```
{
      "tcId" : 81,
      "result" : "fail",
      "reason" : "Could not verify signature: RSA PSS Verify: DB incorrect, '01' byte not found"
    }
```

Could you please give me a helping hand what that means? Note, the IUT that generated the signatures as well as the CAVS harness used to work with the old CAVS system for RSA PSS signatures.

Of course, tt may very well be the case that the IUT changed since then or my invoker code somehow messes things up.

**Comment by smuellerDD** [comment]
Hm, maybe the salt needs to be handled differently?!

**Comment by celic** [comment]
Yeah that's a very specific problem to RSA PSS. In order to get this error, it is likely the implementation changed. This does have to deal with handling the salt. The server implementation is also checked against CAVS and seems to verify correctly from that.

**Comment by celic** [comment]
The terminology used in the error messages comes directly from the RFC that standardizes PSS. That might be of use for diagnosing a problem.

**Comment by smuellerDD** [comment]
thanks, I will close the issue and check the IUT

**Comment by smuellerDD** [comment]
Am Mittwoch, 11. April 2018, 21:22:21 CEST schrieb Chris Celi:

Hi Chris,

> If you need anything from me (intermediate data or anything) feel free to
> let me know.

Thanks a lot. Let me first dig though it myself.

Ciao
Stephan
