### ISSUE TITLE
ECDSA sigver: test verdict "none"

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#328]
Some of my ECDSA sigver test results are returned by the server with the following verdict:

```
{
      "tcId" : 173,
      "result" : "fail",
      "reason" : "none"
    }
```

The majority pass. Could you give me a helping hand in what went wrong?

vsID 749

**Comment by celic** [comment]
Most likely the signature was intended to pass and you submitted "failed" instead.

**Comment by smuellerDD** [comment]
right :-)

Again, for your 0.5 version it would be nice to get better information logs
