### ISSUE TITLE
2-factor auth sometimes fails

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#329]
Just this morning during my first request for new vectors, I received:

```
{
  "acv_version" : "0.4",
  "error" : "The supplied one time password could not be verified"
}
```

Restarting the request some seconds afterwards gave me a successful authentication.

I guess it is related to some small differences in time.

Would it be possible on the server side to have a grace period of, say, 5 seconds? I.e. the server does

1. totp(now_time)
2. totp(now_time - 5 seconds)
3. totp(now_time + 5 seconds)

And if any one of the three TOTP values pass, the server authenticates.

**Comment by hbooth** [comment]
Conceptually, what you are asking for is already being done, although in a different manner.

Recall, that, T, one of the inputs into the HOTP is calculated as follows:
```
long T = (time - T0) / timeStepSeconds;
```
We check T, T-1 and T+1 to see if the supplied one time password matches any of those. Given the 30 second time step, this gives a fairly broad window. I see in the log files what time the error occurred. Do you happen to know what the password value you were trying to provide at that time was? If so, I can try to determine how far off it was, or put another way, whether I need to add some "drift" for you. If you do have it, please don't post here, just send it to me via nfiles. If we do find some drift, we may need to add a synchronize function to the login to allow automated setting of this type of value.

**Comment by smuellerDD** [comment]
Am Donnerstag, 12. April 2018, 14:04:28 CEST schrieb Harold Booth:

Hi Harold,

> Conceptually, what you are asking for is already being done, although in a
> different manner.
> 
> Recall, that, T, one of the inputs into the HOTP is calculated as follows:
> ```
> long T = (time - T0) / timeStepSeconds;
> ```
> We check T, T-1 and T+1 to see if the supplied one time password matches any
> of those. Given the 30 second time step, this gives a fairly broad window.

Great.

> I see in the log files what time the error occurred. Do you happen to know
> what the password value you were trying to provide at that time was?

I do not have that password recorded, unfortunately. All I can say is that the 
seed is always pulled straight from the file I received from you and the TOTP 
/ HOTP code was not recompiled between the two access attempts.

Note, it was just seconds between both access attempts (10 or 20 at most).

> If so,
> I can try to determine how far off it was, or put another way, whether I
> need to add some "drift" for you.

Well, my system uses NTP from the Fedora / Red Hat time servers. Checking it 
with my mobile devices' clocks, they are all within one second 
synchronization.

Thus, I am not sure my system drifts from the "real" time.

> If you do have it, please don't post
> here, just send it to me via nfiles. If we do find some drift, we may need
> to add a synchronize function to the login to allow automated setting of
> this type of value.

I do not think it is the time/clock that we are using as I guess your system 
also takes the time from some time server.

Ciao
Stephan

**Comment by hbooth** [comment]
If this continues to be an issue and you can get me a token along with the approximate time (I can check logs to get exact time) I can troubleshoot to see if I can pinpoint any issues. The time window is 90 seconds wide, and I would hope that time would not be an issue, but since you are seeing occasional problems there is something going on that deserves a look.

**Comment by smuellerDD** [comment]
Am Donnerstag, 12. April 2018, 14:27:48 CEST schrieb Harold Booth:

Hi Harold,

> If this continues to be an issue and you can get me a token along with the
> approximate time (I can check logs to get exact time) I can troubleshoot to
> see if I can pinpoint any issues. The time window is 90 seconds wide, and I
> would hope that time would not be an issue, but since you are seeing
> occasional problems there is something going on that deserves a look.

Ok, I have added some debug code that will print out the used passcode and the 
time it happened.

I will respond once it happens again.

Ciao
Stephan

**Comment by smuellerDD** [comment]
The error mentioned above occurred during response submission. Now, when I try to resubmit the yet unsubmitted data, I can authenticate, but the server responds

```
{
  "acv_version" : "0.4",
  "error" : "vsId was not found in the JWT"
}
```

So, somehow the vsIDs vanished? Note, some of the vsIds belonging to the test session were successfully uploaded and I received my verdict.

vsIDs in question: 1254, 1253

**Comment by smuellerDD** [comment]
Note, I can now reproduce that issue quite frequently (albeit not deterministically) as I moved to threading the testid register / submissions as well. I.e. I have now different parallel login sessions running (but ensuring that a OTP password is only used once -- i.e. the threads are spawned in 30 seconds intervalls).

**Comment by atvassilev** [comment]
It seems likely this is related to the client architecture/implementation. We will need to discuss this further to see how to approach it. Perhaps the upcoming ICMC 2018 would be a good venue for this. Let's try to meet and chat there.

**Comment by smuellerDD** [comment]
Yes, let us discuss it next week.

Note, the behavior of the server while rejecting my passcode seems to be triggered when I have multiple threads running concurrently. If for one thread the (re)login fails, subsequent logins (with a different OTP) fail within the next few minutes. After waiting some time, the server starts accepting my passcodes again.

To debug that further, I used a separate implementation of the TOTP and verified that the passcode send at that very time that was rejected in fact is correct with respect to the TOTP specification. So, I am not sure what I shall debug further. Though, maybe a joint debug session next week would help.

**Comment by smuellerDD** [comment]
Shortly before the server update yesterday, I almost got authentication errors on a constant basis. After the server was updated, it vanished and I was able to log on.

Though, when I started a download for 17 test sessions with some 190 vsIDs I received again 2 authentication failures during this exercise during reauthentication events. All other (re)authentication events for this exercise were successful.

**Comment by smuellerDD** [comment]
Authentication error appeared again:

ACVPProxy (22:40:29) Error: Falure in authentication with passcode xxxxxx (time: 1526503229 20180516_22-40-29)

Note, I am in MEST (+6 h compared to EDT)

**Comment by smuellerDD** [comment]
@hbooth: I saw the following pattern over the last login failures: all failures were due to my client sending 7 digit numbers (i.e. my client omits the leading zero). I.e. my current code to generate the passcode string (hm, string, shouln't it be a JSON integer?) is the following:

```
snprintf(totp_val_string, sizeof(totp_val_string), "%u", totp_val);
```

I have now updated it to the following guaranteeing it will always be 8 digits including leading zeros:

```
snprintf(totp_val_string, sizeof(totp_val_string), "%.08u", totp_val);
```

Do you think that this may be an issue? I am testing the code delivering always 8 digits and have not seen a failure (after some couple authentication attempts).

**Comment by hbooth** [comment]
that absolutely could be the issue. It's treated as a string and the '0' leading or otherwise is considered part of the PIN.

**Comment by smuellerDD** [comment]
And I think this was the issues. I am using the server over night and even now without any authentication failure.

It is the first time I can complete the full OpenSSL download with 191 vsIDs.

May I suggest to add this piece of information into the OTP spec that the passcode string must include leading zeros?

Thanks
