### ISSUE TITLE
HMAC DRBG SHA-1: server side implementation broken?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#330]
I have two IUTs which I feed with the same HMAC DRBG SHA-1 vectors obtained from the server. Both generate the same result.

Yet, the server responds that the returned data does not comply with the expected data.

For other HMAC types, the server returns a passing verdict (and the two IUTs also agree on the return data).

Could you please check whether my answers are broken?

vsID 1064

**Comment by Kritner** [comment]
@smuellerDD I'm not seeing anything glaringly obviously wrong, though it is interesting - in the vector set 1064, the responses for sha1 are passing for `"predResist": true` tests, but not `"predResist": false`.  All other hash modes with `"predResist": false` are passing.

Very strange, no answers yet but I'll keep looking.

**Comment by Kritner** [comment]
@smuellerDD I still haven't seen anything weird on our end that would account for this behavior... I'm not sure if it'll help, but here are the answers on our end for the vsId 1064:

```
    {
      "tcId": 1,
      "returnedBits": "79172CC43FD3511BF0AD1D42F0FE21EE8A955326617987B175F12458BA8BFB9BB06C9E22CAB23CCD"
    },
    {
      "tcId": 2,
      "returnedBits": "41A99A26D3F7AA8EA1A2EF7FC254F3E59AA6A9A12767ECDC749540E03BE4E53FAB1F8756EE514635"
    },
    {
      "tcId": 3,
      "returnedBits": "0F2D4B9A5764F0DA4C8B7F0F1B6C1933EA941DB28FA5E592D22417DAB6228B069F5A7B833CC8EFDE"
    },
    {
      "tcId": 4,
      "returnedBits": "97434A8C5389AE12F510E0CF70B1E0FCBE2EC5234A852A60E30B853C150F281EFADFE35C0AC385D4"
    },
    {
      "tcId": 5,
      "returnedBits": "D0A3F584E3807BA485E0A9AB8003C549B6B64C9DD2743000C711F6243B6A76DC81105038B93318A5"
    },
    {
      "tcId": 6,
      "returnedBits": "C37CD8952A6C9360F01CAEEDB0B8D3516178B04663DACEF3B6E70A7DB02590AAD7BBF5F46F5E0748"
    },
    {
      "tcId": 7,
      "returnedBits": "9061D22F1E17F4DA12D5FAB7453A8B51FC1A8EBA88959D66E316CFEC94E4C2AC3EA4F57E05359B1B"
    },
    {
      "tcId": 8,
      "returnedBits": "7EEB62740E8EFBC92CE5468E0B8B0F8B7A72FFF7981A398837F19F03F4D69E8F7E514E76C4F1B012"
    },
    {
      "tcId": 9,
      "returnedBits": "32FA4543AED486663AB7610811C795024F4D01907F423E8F2B5F11B041544D321A8C60EAAC19C399"
    },
    {
      "tcId": 10,
      "returnedBits": "B41F62C698D8524846913439F10CB1AE5032858A58BD2ABFA98EC5E5F0D7DDAF2019A219DF8C398B"
    },
    {
      "tcId": 11,
      "returnedBits": "33AFC419890545822C04BBCFE2D6386C498A1BA5BF1D4F33365DD63EE42CBC69369B093DC9E2B909"
    },
    {
      "tcId": 12,
      "returnedBits": "E3155D47C3422926A6823104E4D8ECE7E9DC38ADCF9B385E623AE57C0EC89DFD5CB65F826D762874"
    },
    {
      "tcId": 13,
      "returnedBits": "A46AF5AD3B5AEE121878BEEE4CF5EC5F4CC9234DE44B449BA97321F9BB7C3D4D2C3EDC9EE8F66D4B"
    },
    {
      "tcId": 14,
      "returnedBits": "789D8D075EB9A96EB61656221C48BB601030A6BFD3ED4A9564BD9F5968B7945403E9CA8BAE06DD05"
    },
    {
      "tcId": 15,
      "returnedBits": "D9F32C805F05D11B4BDA553204578134915580BBEB3079F548B1846FA1D9C43E480FF700A6C24D09"
    },
    {
      "tcId": 16,
      "returnedBits": "A3C5B1FA526B900D3BB58EEC23D6164CF87D96D021884E0695363E427544805402BE9164D51DE5EA071A1EA31A386A667886E664E68695FD1652777AE5066FDA1C9AF81026C5FA4AF9470A6C87E17C8EA3D5EAF7573A2587C5AB315AB1F4EA52A7B3644BD9080ECD5ADA2D4261BE8D54A34EEEF312097D6297CC941BE8EBEAF2"
    }
```

In comparison to what was submitted to the server:

```
    {
    "tcId" : 1,
    "returnedBits" : "e6ca2caa56d99e16b5150acd6139f50b88b9c2036fc9a700ff2296fa395977a94b31dda5d20d3150"
  }, {
    "tcId" : 2,
    "returnedBits" : "71272f6e0537b2304366fac63016fdc9f009d065e2df9bad1ddab24c2ced8a5930376267db0b812f"
  }, {
    "tcId" : 3,
    "returnedBits" : "9e362b9f88a43f3bdcbd0c509cc97b8f9b242db21b5dee2b5ebe3a3727469a9b2e6648d4eae685f3"
  }, {
    "tcId" : 4,
    "returnedBits" : "ed76c7e7ce92d2dedb62ae291078b1519babe542fcd870874aa9073421b58ca718ccc7d5e9018723"
  }, {
    "tcId" : 5,
    "returnedBits" : "01db75a2ad22310f5d4d34bebaa06ff671fe4a20f7a9b4e73087b012956adf367031d3f87c0d5446"
  }, {
    "tcId" : 6,
    "returnedBits" : "cb15a969ed1d7d9d77ff130c50d19f07d8272b5902a6d487a382cd142ae0eea57bc059787018262e"
  }, {
    "tcId" : 7,
    "returnedBits" : "abb271c96d076f313061081ced6a18a46801f6669edfb6006fd1dcb1de831d74bf13df81f87f583d"
  }, {
    "tcId" : 8,
    "returnedBits" : "55d8d953fbd9451b44f4136a0b74166388cd5613d42f0e2c88df8fd5aad99a0633a5538a58c64c28"
  }, {
    "tcId" : 9,
    "returnedBits" : "ee8a452b05712abc73315817bb9cf2fcdcdacfbdd93bb358127b9e50c666062c047a7749d513aa26"
  }, {
    "tcId" : 10,
    "returnedBits" : "6708ddbfbd50bc444aacf53c08f79a5cf233fd0325484e57470b322122b72fc57edb5776748668e5"
  }, {
    "tcId" : 11,
    "returnedBits" : "1d019d050d4cf1e6f3b1e73214a72543cf0e43be81d05246ef026917e7b855b0a7f5c07c593745ea"
  }, {
    "tcId" : 12,
    "returnedBits" : "071625b9f01c31c3ae9610c8cbfacb97e76f898a01a9408abcc286bf7dfcdebcdd9935cd6939a762"
  }, {
    "tcId" : 13,
    "returnedBits" : "c9a1209c8ea6ef019b558ac17c28c22b4db3a8d1f786c9c165aacdd0b2509629bc7463f1fcabaf3e"
  }, {
    "tcId" : 14,
    "returnedBits" : "9be80f6b6992f4d0247f52660665092acec120d8d0c3d41a44228d723e2c1a250df14881ec40ff39"
  }, {
    "tcId" : 15,
    "returnedBits" : "34f54f1d733daffa0c20be599e3f6004253cfd059ab49beb08b7cacd3e9be2dd6477f12077142ddc"
  }, {
    "tcId" : 16,
    "returnedBits" : "a3c5b1fa526b900d3bb58eec23d6164cf87d96d021884e0695363e427544805402be9164d51de5ea071a1ea31a386a667886e664e68695fd1652777ae5066fda1c9af81026c5fa4af9470a6c87e17c8ea3d5eaf7573a2587c5ab315ab1f4ea52a7b3644bd9080ecd5ada2d4261be8d54a34eeef312097d6297cc941be8ebeaf2"
  }
```

It is quite odd, considering we don't have logic specific to sha1 in comparison to sha2 flavors/digests.

I would have expected something like this, since we have a (snippet) of a product going like:

| predResist | sha | passes |
| ----- | ----- | ----- |
| false | sha1 | false |
| false | sha2-256 | true |
| false | sha2-512 | true |
| true | sha1 | true |
| true | sha2-256 | true |
| true | sha2-512 | true |

I would have expected that either ***all*** sha1 would pass or fail, or that ***all*** predResist false would pass or fail, but we're in the weird situation that we're disagreeing only on sha1 AND predResist false.

**Comment by smuellerDD** [comment]
Am Freitag, 20. April 2018, 20:52:25 CEST schrieb Russ Hammett:

Hi Russ,

Just to recap:

- two totally different implementations of HMAC/Hash DRBG produce the same 
output

- my tool has one parser irrespective of the used hash type. I.e. the very 
same parser code is used for SHA1 and SHA2

- dto for the test invocation: For each IUT I have the identical code path for 
testing SHA1 and SHA2 

To track this one down, allow us to focus on the very first test, tcId 1. In 
the following, I would like to present what my parser is doing and what I get 
in response from the IUT

1. Instantiate the DRBG:
CAVS driver - Debug: cipher: SHA-1 (HMAC DRBG)
CAVS driver - Debug: entropy = 32126a0733b4cdbea918c214287850c105e2bb34
CAVS driver - Debug: nonce = 8c730117d5757d17ee21b36b8f1027281e2a20f3
CAVS driver - Debug: personalization string = 
9adcc49014efd2ff0e9d94daca9b8add45dba3db

2, Inject the additional data
CAVS driver - Debug: addtla = 9e40e545505686f6061cdf58419229a060bde93f

3. Get a random number
CAVS driver - Debug: random tmp = 
d9385bc3c0cf69c0b2e69b179fcd352654df05cc5b37759daedb276b77f75d710420f49a77398fac

4. Inject the 2nd additional data
CAVS driver - Debug: addtlb = b3a57ae5f24cd9245345618e45ef1316d6b4468b

5. Get a random number
CAVS driver - Debug: random = 
e6ca2caa56d99e16b5150acd6139f50b88b9c2036fc9a700ff2296fa395977a94b31dda5d20d3150

Step 5 is my final output.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Freitag, 20. April 2018, 20:52:25 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD I still haven't seen anything weird on our end that would
> account for this behavior... I'm not sure if it'll help, but here are the
> answers on our end for the vsId 1064:

I think I found the issue. I can produce the very same result that you posted. 

Your test instantiates the *Hash* DRBG although the *HMAC* DRBG shall be 
tested.

I.e. the vector set we discuss here (1064) is for HMAC DRBG. Whe I process the 
vector set with *Hash* DRBG, I get the very same output as you provided.


Ciao
Stephan

**Comment by Kritner** [comment]
Ah, yeah seems that's the issue!  Though it's interesting, this should be the issue *across the board* for DRBG-HMAC, but from the submitted results, only 15 out of 90 submitted failed validation.  The 75 the passed between our end and your IUT, managed to come up with the same answers, even though we were operating in DRBG-Hash mode while you were operating in DRBG-HMAC?

**Comment by smuellerDD** [comment]
Am Sonntag, 22. April 2018, 13:48:03 CEST schrieb Russ Hammett:

Hi Russ,

> Ah, yeah seems that's the issue!  Though it's interesting, this should be
> the issue *across the board* for DRBG-HMAC, but from the submitted results,
> only 15 out of 90 submitted failed validation.  The 75 the passed between
> our end and your IUT, managed to come up with the same answers, even though
> we were operating in DRBG-Hash mode while you were operating in DRBG-HMAC?

I think I always operate in HMAC mode when hmacDRBG is requested. Note, my 
parser is agnostic of the underlying SHA size or the IUT implementation.

Thus I would rather consider that the ACVP server only mixes all up for SHA-1 
HMAC/Hash DRBG.

Ciao
Stephan

**Comment by smuellerDD** [comment]
I reviewed and retested my implementation. I found a bug where all Hash DRBG where treated as HMAC DRBG. Though, all HMAC DRBG test vectors were processed as HMAC DRBG.

Thus, I would think that all responses returned as vsID 1064 are HMAC DRBG responses and I guess that the ACVP server applies Hash DRBG for SHA-1.

Furthermore, for the responses for vsID 1065 (which is a Hash DRBG test vector) are processed as HMAC DRBG. As the ACVP returned that all are pass except for SHA-1, I would assume that the ACVP server also partially treats them as HMAC DRBG.

**Comment by Kritner** [comment]
Ah good to know @smuellerDD.  Yeah the issue on our end seemed to be that only the first group in the registration was processed as the incorrect hash drbg, where the others were processed as HMAC.  Working on a test internally and will update once it has been deployed.

**Comment by smuellerDD** [comment]
i rerun the tests and found that the Hash DRBG is now working. But for the HMAC DRBG, I still get failing verdicts.

vsID: 3448

**Comment by Kritner** [comment]
The fix has been deployed, please update this issue if there any problems.  Closing for now.
