### ISSUE TITLE
DSA Spec questions

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#331]
When I register for DSA I get:
  "error" : "Incorrectly formatted JSON (84:18): expected field name was not provided: capabilities"
however I don't see "capabilities" anywhere in the DSA spec.

Some questions on the keywords as well.
 HashAlgs in the registration and hashAlgs in the vectors
We define pqgGen and PQGen, seems inconsistent in the camel case. Same with GGen.
testType GDT, is that accurate ?

The spec uses L and N in the registration, but l and n in the vectors.

registration:

        "capabilityExchange": {
            "algorithms": [
                {
                    "algorithm": "DSA",
                    "mode": "pqgGen",
                    "prereqVals": [
                        {
                            "algorithm": "SHA",
                            "valValue": "same"
                        },
                        {
                            "algorithm": "DRBG",
                            "valValue": "same"
                        }
                    ],
                    "algSpecs": [
                        {
                            "PQGen": [
                                "probable",
                                "provable"
                            ],
                            "GGen": [
                                "unverifiable",
                                "canonical"
                            ],
                            "L": 2048,
                            "N": 224,
                            "HashAlgs": [
                                "sha2-224",
                                "sha2-256",
                                "sha2-384",
                                "sha2-512"
                            ]
                        }
                    ]
                }
            ]

**Comment by smuellerDD** [comment]
In addition, the spec defines the keyword "hashAlg" whereas the examples use "HashAlgs".

**Comment by Kritner** [comment]
@celic it looks like on the gen/val end we're expecting `capabilities`, in place of the `algSpecs` as per the specification.  Is this just a mapping issue on the driver end?  I feel like `capabilities` is used elsewhere in other specs, so wanted to check in with you prior to pursuing a fix.

**Comment by bfussell** [comment]
This should explain the difference between the spec and server implementation. Here is what was accepted by the server and differs from the spec: upper-case SHA, capabilities instead of algSpecs, and hashAlg instead of hashAlgs, l and n are lowercase.

            "algorithms": [
                {
                    "algorithm": "DSA",
                    "mode": "pqgGen",
                    "prereqVals": [
                        {
                            "algorithm": "SHA",
                            "valValue": "same"
                        },
                        {
                            "algorithm": "DRBG",
                            "valValue": "same"
                        }
                    ],
                    "capabilities": [
                        {
                            "PQGen": [
                                "probable",
                                "provable"
                            ],
                            "GGen": [
                                "unverifiable",
                                "canonical"
                            ],
                            "l": 2048,
                            "n": 224,
                            "hashAlg": [
                                "SHA2-224",
                                "SHA2-256",
                                "SHA2-384",
                                "SHA2-512"
                            ]
                        }
                    ]
                }
            ]
        }

**Comment by smuellerDD** [comment]
Update from my side: I now can download DSA vectors too. I had my JSON objects in a different order which seems to be not well received by the ACVP server. Ordering it such as @bfussell listed it works.

**Comment by atvassilev** [comment]
It seems this can be closed now.
