### ISSUE TITLE
DSA: hashAlg vs hashPair

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#332]
The DSA spec defines the array of hashes with the keyword hashAlg wheras RSA uses hashPair. May I suggest to consolidate that?

**Comment by celic** [comment]
RSA uses HashPair because it is a different object than the one used in DSA. RSA (specifically PSS) has the option to use a SaltLength in association with a hash algorithm which is where the pair comes in. A HashPair is a combination of a HashAlg and a SaltLen. DSA does not have such a constraint and can just use a normal HashAlg.

**Comment by celic** [comment]
Though everything should be using "HashAlg" for consistency!

**Comment by celic** [comment]
hashAlg. We have been talking a bit internally about the case sensitivity of these properties. Do you have any quick thoughts on the matter?

**Comment by smuellerDD** [comment]
Am Donnerstag, 19. April 2018, 17:26:24 CEST schrieb Chris Celi:

Hi Chris,

> hashAlg. We have been talking a bit internally about the case sensitivity of
> these properties. Do you have any quick thoughts on the matter?

Keywords in JSON are commonly case sensitive.

JSON parsers should be expected to be very strict and would enforce case 
sensitivity. IIRC, mine would be sensitive to the case.

Thus, case sensitivity is required.

On the other hand, how you name your keywords, does not really matter IMHO. 
Though, it should be consistent throughout the entire ACVP spec. To make all 
our lives easy, I would use only one case, i.e. either upper or lower, but no 
mixed cases as it is done right now. This means that nobody has to think about 
the cases when he hears a keyword as he knows how to reference it.

Ciao
Stephan

**Comment by atvassilev** [comment]
We agreed on adopting Camel case for all specs. The decision was made after some of the drafts were published, hence some leftover inconsistencies are still there. Going forward we must stick to consistently using Camel case: helloWorld.

**Comment by smuellerDD** [comment]
Am Donnerstag, 19. April 2018, 17:57:38 CEST schrieb Apostol Vassilev:

Hi Apostol,

> We agreed on adopting Camel case for all specs. The decision was made after
> some of the drafts were published, hence some leftover inconsistencies are
> still there. Going forward we must stick to consistently using Camel case:
> helloWorld.

Ok, if this is the decision, we should not divert from it then. All I am 
asking for is consistency :-)

Ciao
Stephan

**Comment by celic** [comment]
As the original question was resolved, I'm going to mark this as closed. hashPair is intentionally a different (despite being very similar) object than hashAlg.
