### ISSUE TITLE
DSA sigver: PQG missing?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#334]
The test vectors for DSA sigVer contain

```
{
      "tcId" : 1,
      "message" : "77250571BC47EA07BE1D1B700C2BFF5526B53B96",
      "y" : "8C1BBD4586A31AC43FB4C16315F509306837E5B8BC62091CC663D5301326F094832175C1BB19E1F35D4438E11B07B714CBD71C0364E5051F0B9F3ABE418971CE3CD667E09243828279A27D5E470F2E8B82431DA31537F3D0D81D12321CDCBFE861A08D71A45DDE741A611ECE686F33F8F3CB4E35BC30DFCEAF0793F49E5751C9",
      "r" : "94B7ED20B5F69CF3AADDD18CA73D160A89B8CD04",
      "s" : "6D19A5CB5490547A903381E6A30D1930CF54F7D8"
    }
```

I wonder whether the PQG values are missing here? Or how shall an IUT come by these values?

**Comment by Kritner** [comment]
@smuellerDD agreed, it seems that P, Q, and G should be included as group level properties.  I will move forward with an internal fix.  @celic are you confirm this fix is valid?  Seems that sig verify requires the PQG as a parameter, but we not currently including that in our projections to the IUT.

**Comment by Kritner** [comment]
The fix has been deployed, please update this issue if there any problems.  Closing for now.

**Comment by smuellerDD** [comment]
Confirmed, working.
