### ISSUE TITLE
DSA pqgGen: server failed to generate vector

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#338]
The server failed to generate pqgVer vectors with the error:

```
[ {
  "acvVersion" : "0.4"
}, {
  "vsId" : 2136,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 2136"
} ]
```

My request was:

```
        {
          "algorithm":"DSA",
          "mode":"pqgGen",
          "prereqVals":[
            {
              "algorithm":"SHA",
              "valValue":"same"
            },
            {
              "algorithm":"DRBG",
              "valValue":"same"
            }
          ],
          "capabilities":[
            {
              "l":3072,
              "n":256,
              "PQGen":[
                "probable"
              ],
              "GGen":[
                "unverifiable"
              ],
              "hashAlg":[
                "SHA2-256"
              ]
            }
          ]
        }
```

**Comment by Kritner** [comment]
Same issue as: https://github.com/usnistgov/ACVP/issues/337#issuecomment-383115695

**Comment by Kritner** [comment]
The fix has been deployed, please update this issue if there any problems.  Closing for now.

**Comment by smuellerDD** [comment]
Am Donnerstag, 10. Mai 2018, 19:50:48 CEST schrieb Russ Hammett:

Hi Russ,

> The fix has been deployed, please update this issue if there any problems. 
> Closing for now.

Currently I have heavy authentication issues I need to sort out with Harold. 
Furthermore, just right now, I get a 404 error from the server even when 
trying to log on.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Donnerstag, 10. Mai 2018, 19:52:21 CEST schrieb Stephan Mueller:

Hi,

> Am Donnerstag, 10. Mai 2018, 19:50:48 CEST schrieb Russ Hammett:
> 
> Hi Russ,
> 
> > The fix has been deployed, please update this issue if there any problems.
> > Closing for now.
> 
> Currently I have heavy authentication issues I need to sort out with Harold.
> Furthermore, just right now, I get a 404 error from the server even when
> trying to log on.

It seems that is cleared now and was due to the server update. Please 
disregard my earlier message.
> 
> Ciao
> Stephan



Ciao
Stephan

**Comment by Kritner** [comment]
Thanks @smuellerDD will do

**Comment by smuellerDD** [comment]
Sorry, but server still reports:

```
[ {
  "acvVersion" : "0.4"
}, {
  "vsId" : 55,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 55"
} ]
```

**Comment by Kritner** [comment]
@smuellerDD I haven't been able to reproduce an issue here, and am not seeing anything strange in our logs.  Just to be sure could you try running your registration of:

```
{
	"algorithm": "DSA",
	"mode": "pqgGen",
	"isSample": false,
	"capabilities": [{
		"l": 2048,
		"n": 224,
		"pqGen": ["provable"],
		"gGen": ["canonical"],
		"hashAlg": ["SHA2-224", "SHA2-256", "SHA2-384", "SHA2-512"]
	}]
}
```

again?

**Comment by smuellerDD** [comment]
Done: vsid 277, still failing.

**Comment by celic** [comment]
Hi Stephan, the error being reported by the logs is a bit unexpected. Can you confirm the problem still persists when you try again? The server maintenance is done and everything should be available to try.

**Comment by smuellerDD** [comment]
Am Mittwoch, 16. Mai 2018, 22:19:08 CEST schrieb Chris Celi:

Hi Chris,

> Hi Stephan, the error being reported by the logs is a bit unexpected. Can
> you confirm the problem still persists when you try again? The server
> maintenance is done and everything should be available to try.

Just started a download for some 190 vsIDs. I will report about the result 
tomorrow.

Ciao
Stephan

**Comment by celic** [comment]
I believe Harold has tested a fix for the issue. It is unrelated to DSA, but rather the parallel nature of your client. It's a good bug to find and fix. It will be deployed to the external ACVP server after some internal testing.
