### ISSUE TITLE
DSA PQG: where is firstseed?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#339]
For provable PQ generation as well as for canonical G generation, the first seed is needed.

In the old CAVS tool, for PQ generation, first seed needed to be returned. For PQ verification,  G generation and G verification it was provided.

Where is it now? The spec does not indicate its presence.

**Comment by smuellerDD** [comment]
The spec mentions that this is the seed for the "probable" P/Q generation 
method. But the firstseed is needed for the provable method.

But looking at the examples, it is only given for probable PQ verification. I 
am very puzzled about that. I thought first seed is an output for provable PQ 
generation and input for provable PQ verification. Could you please give me a 
helping hand?

Besides, may I suggest to add a hint about the fact that domainSeed is 
firstseed, because FIPS186-4 only speaks of firstseed.

**Comment by celic** [comment]
I pushed out a fix for this (at least for PQG Ver) which will go online when the ACVP server is brought back up after the maintenance. I am still looking in to PQG Gen.

**Comment by bfussell** [comment]
Still no seed for PQGVer.

  }, {
    "l" : 2048,
    "n" : 256,
    "hashAlg" : "SHA2-256",
    "testType" : "GDT",
    "gMode" : "canonical",
    "tests" : [ {
      "tcId" : 6,
      "p" : "F26FB4D25C168495C108CCCAC60217E1ED4C32FBDEF4ADD0D0C83C9F996F562E8DA2422A3B8B209F52BC35E50DB0E567BEE671FA4E12473F4669840B8AC7C45D44694F302E4CFAF98F095B24395623B5ABA50C4379126440BD36F17E62386100195796CAA547F7B37317729AE4786D91BEBD002FCFDBECE6FDB89B7F89259F59EDDFDA64A62317EBDB67A6208220238922411B4FDB7E9F257AE23253E3F02CF58BAA153B9822286C2CBF10A57DB63845F3CC4A0F5AC7B4125012D1503C614EF058DE509B8F63DAABFB6EF15A0F2B1B8350576F34DACE6A3A2C1C38F4B087E816AB365104116D13D37597C67CF9345A4BA1C82FFFB844762D8722A4C908FBDB8B",
      "q" : "8AEE2A86E244A71E4629D1400135EF69109EF4A2889FA6A0AA0AFB010821254B",
      "g" : "71C6256B164230F3F2B7160549D5AFF277F6D7396FE1BE97E71E71325AB817B53EEB6C9E3997067194E04D1371F5E730932DC5C8EF9045DD645F031DB3C4D33FCA88FB310643203CBEC6CAB4BF23F6EB3B24F72DF7E23E3A1D72E159D3C5385E950C3668E023558B5BBDAA2DCB625046B8D7E2EB23684C00F0DC555BCE7BF969F495170F69AEC21E101A9643E32E1672CEAFD4CD2E2CF4AC1C9F16A34265A6F1008D5CE2D41EF68CA41118171568A0067F97C1746CFAF65177EB2E5F3B66302832ABAC833596098F2441C7257E6C984BFF5209728ED89DAD119179DDAE1ACE6C379683ADB39F5889094F4D0AA807E3F0C9DC7909D267BEB65960228E1F13DF71",
      "index" : "4B"
    }, {
      "tcId" : 7,

**Comment by celic** [comment]
The fix for this has been deployed. `domainSeed` should be present for PQGVer when `"gMode": "canonical"`.

**Comment by smuellerDD** [comment]
Confirmed, working.
