### ISSUE TITLE
Missing content-length header on vector response.

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#341]
Hi,

After issuing a vector request and going through a couple of retries, the response with the vectors had no content length. 
At the moment we are using a strict http client which expects a content-length header. 
This can be changed but I would like to confirm that the absences of content length headers is to be expected?

The following are the headers returned by the demo server while attempting to fetch vectors.

Initial response to request for vectors:
```
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Pragma: no-cache
Cache-Control: no-cache, no-store, must-revalidate
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: application/json;charset=ISO-8859-1
Content-Length: 72
Date: Thu, 26 Apr 2018 07:00:40 GMT
Connection: close

[ {
 "acvVersion" : "0.4"
}, {
 "vsId" : 3142,
 "retry" : 30
} ]
```

After retry period, resubmit the request.

```
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Pragma: no-cache
Cache-Control: no-cache, no-store, must-revalidate
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: application/json;charset=ISO-8859-1
Content-Length: 72
Date: Thu, 26 Apr 2018 07:01:15 GMT
Connection: close

[ {
 "acvVersion" : "0.4"
}, {
 "vsId" : 3142,
 "retry" : 30
} ]
```

The following response with the vectors has no content-length header also the Expires date is in the EST timezone but the other responses the Expires date is in GMT.

```
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Pragma: No-cache
Cache-Control: no-cache
Expires: Wed, 31 Dec 1969 19:00:00 EST
Content-Type: application/json;charset=ISO-8859-1
Date: Thu, 26 Apr 2018 07:01:49 GMT
Connection: close
```

Cheers Megan

**Comment by Kritner** [comment]
A fix was deployed for this.  Please let us know if there are any problems.
