### ISSUE TITLE
DSA siggen: "Invalid v, does not match provided r"

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#343]
When submitting a DSA siggen result, the server replies"

```
{
  "results" : {
    "vsId" : 3512,
    "disposition" : "fail",
    "tests" : [ {
      "tcId" : 1,
      "result" : "fail",
      "reason" : "Validation failed: Invalid v, does not match provided r"
    }, {
      "tcId" : 2,
      "result" : "fail",
      "reason" : "Validation failed: Invalid v, does not match provided r"
    }, {
      "tcId" : 3,
      "result" : "fail",
      "reason" : "Validation failed: Invalid v, does not match provided r"
    }
```

What does that mean?

vsID 3512

**Comment by celic** [comment]
This comes from [FIPS 186-4](https://nvlpubs.nist.gov/nistpubs/fips/nist.fips.186-4.pdf). When a client provides an `r` value, the server performs some of the SigVer computations which tries to match that `r` value with `v`. These variable names come from the FIPS specification.

**Comment by smuellerDD** [comment]
Thank you, that clears it up.

**Comment by celic** [comment]
Yeah, I understand the confusion when new variable names are introduced 'out of thin air'. Almost always (I'd be surprised if there isn't such a case) these values come from the relevant crypto specification.
