### ISSUE TITLE
CFB1 spec request: use different keyword for pt / ct

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#344]
The JSON keywords imply a data type. For the keywords of ct/pt, the data type is the hex representation of bytes.

For CFB-1, however, pt and ct are supposed to be representations of one bit. To support generic parsers, may I suggest to use a different key word that can be associated with the different data type?

Thanks

**Comment by Kritner** [comment]
@smuellerDD I'm assuming this is in regards to AES only?  The current plan was for the 0.5 version of the spec to update to make AES-CFB1 consistent with TDES-CFB1's implementation; which uses hex like everything else.

**Comment by smuellerDD** [comment]
Am Montag, 30. April 2018, 15:04:17 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD I'm assuming this is in regards to AES only?  The current plan
> was for the 0.5 version of the spec to update to make AES-CFB1 consistent
> with TDES-CFB1's implementation; which uses hex like everything else.

Perfect, the TDES specification is good for me.

Consistency is all I ask for :-)

Ciao
Stephan
