### ISSUE TITLE
AES-ECB: pt / ct keyword not known

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#347]
Submitting an AES-ECB encryption result, I get the following error:

```
{
  "acv_version" : "0.4",
  "error" : "Incorrectly formatted JSON (4289:19): Unknown property: pt"
}
```

As I am doing encryption only, this is found in the MCT. If I take out the pt information, I get:

```
{
  "acv_version" : "0.4",
  "error" : "Incorrectly formatted JSON (4289:19): Unknown property: ct"
}
```

**Comment by Kritner** [comment]
@smuellerDD we're taking a look into this now

**Comment by Kritner** [comment]
Sorry for the delay in this, we're currently testing a solution internally.  Will update once a fix is deployed.

**Comment by celic** [comment]
Yeah this was a bit wider than just AES-ECB, so part of the delay was diagnosing the full problem and fixing it systematically.

**Comment by hbooth** [comment]
recent deployment should have resolved this.
