### ISSUE TITLE
CTR DRBG: failure to generate test vector

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#348]
The server responds as follows for a CTR DRBG generation request:

```
[ {
  "acvVersion" : "0.4"
}, {
  "vsId" : 47,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 47"
} ]
```

**Comment by Kritner** [comment]
@smuellerDD the registration for vs47:

```
{
	"algorithm": "ctrDRBG",
	"isSample": false,
	"predResistanceEnabled": [false],
	"reseedImplemented": true,
	"capabilities": [{
		"mode": "AES-256",
		"derFuncEnabled": false,
		"entropyInputLen": [256],
		"nonceLen": [256],
		"persoStringLen": [256],
		"additionalInputLen": [256],
		"returnedBitsLen": 512
	}]
}
```

The rejection appears to be accurate, though more information could potentially be displayed.  With no derivation function for aes-256, the minimum entropy input is 384, but 256 was provided.

**Comment by smuellerDD** [comment]
Am Freitag, 11. Mai 2018, 11:33:24 CEST schrieb Russ Hammett:

Hi Russ,

> The rejection appears to be accurate, though more information could
> potentially be displayed.  With no derivation function for aes-256, the
> minimum entropy input is 384, but 256 was provided.

Due to another issue opened a while ago, the noncelen was not allowed to be 
zero. Are you saying that this is fixed and I can use the proper option of 
noncelen = 0 and entropylen = 256?



Ciao
Stephan

**Comment by smuellerDD** [comment]
I updated my request to the options I actually really want which are the following:

```
        {
          "algorithm":"ctrDRBG",
          "prereqVals":[
            {
              "algorithm":"AES",
              "valValue":"same"
            }
          ],
          "predResistanceEnabled":[
            false
          ],
          "reseedImplemented":true,
          "capabilities":[
            {
              "mode":"AES-256",
              "derFuncEnabled":false,
              "entropyInputLen":[
                256
              ],
              "nonceLen":[
                0
              ],
              "persoStringLen":[
                0
              ],
              "additionalInputLen":[
                0
              ],
              "returnedBitsLen":512
            }
          ]
        }
```

The server replies:

```[ {
  "acvVersion" : "0.4"
}, {
  "vsId" : 269,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 269"
} ]
```

**Comment by Kritner** [comment]
@smuellerDD seems I missed updating some tickets that were a part of the deployment, do you happen to have that issue number handy?

The 0 values for `nonceLen`, `persoStringLen`, and `additionalInputLen` are implemented, but the `entropyLen` provided above https://github.com/usnistgov/ACVP/issues/348#issuecomment-388329502 is 256, where the minimum for aes-256 no DF is 384.

**Comment by smuellerDD** [comment]
After changing the entropylen to 384, I get data.

Thus, I think this issue was on my side. Closing the issue.

**Comment by smuellerDD** [comment]
PS: the issues I was referring to were 239 through 241. They are closed, but I saw the issue over the last weeks. But now, it seems that they are really fixed.
