### ISSUE TITLE
Re-download of test vector: server cannot validate passcode

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#349]
I have downloaded a test vector for a particular vsID. Now, assume you have deleted and you want to download it again.

The re-download request contains the OTP and the allowed and valid accessToken from the previous attempt (both are valid because I can upload test responses for the test session).

Yet, the server responds with:

```
{
  "acv_version" : "0.4",
  "error" : "The supplied one time password could not be verified"
}
```

Example vsID: 379

Side note: During the initial download of vsID 379 the server already gave me an authentication error (i.e. I was not able to download the test vector). I restarted the download the same way as outlined above and I was able to obtain the test vector. Only after deleting my copy and re-trying the download yet again, the server gives me the error outlined above.

**Comment by smuellerDD** [comment]
@hbooth: After our discussion last week about the authentication failures and seeing this failure in the case above, I would start to think that this error does not relate to authentication at all. The error above seem to be triggered by not being able to fetch some data. But it is not due to wrong passcodes or the like.

Could that be a similar issue that I see when trying to obtain test vectors? I.e. would it make sense that instead of dissecting the authentication logic, you rather look into other areas of the server triggering an error that ultimately lead to an error response of failing authentication?

**Comment by hbooth** [comment]
@smuellerDD
Given that you have identified the source of the authentication issues is this still a problem?

**Comment by smuellerDD** [comment]
Am Donnerstag, 24. Mai 2018, 23:02:38 CEST schrieb Harold Booth:

Hi Harold,

> @smuellerDD
> Given that you have identified the source of the authentication issues is
> this still a problem?

I have not seen that issue again. 

Ciao
Stephan
