### ISSUE TITLE
Consistent property name for "curve" ECDSA/KAS-ECC/KAS-ECC-CDH-Component

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#351]
ECDSA, KAS-ECC, and KAS-ECC-Component use inconsistent property names for `curve`.  `curves`, `curve`, and `curveName` appear to be all the properties used.

Just going off of the decision for `hashAlgs` -> `hashAlg`, I'm going to make an assumption that `curve` should be used.

**Comment by smuellerDD** [comment]
Are you saying that KAS is already available?
