### ISSUE TITLE
HMAC DRBG: perso string len < 128 not supported

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#353]
Just got the following message from the server:

```
{
  "acv_version" : "0.4",
  "error" : "Property value(0) for (persoString) in Algorithm (hmacDRBG (null)) is not valid. Validation: (Number Between (128) and (34359738368) modulus 8)"
}
```

**Comment by celic** [comment]
I see the problem. This isn't on the gen/val side but rather the server side. It's rejecting the inputs a bit to stringently. We'll get this fixed. Thanks.

**Comment by celic** [comment]
This has been fixed and deployed. Please test again and let me know if there are any issues.

**Comment by smuellerDD** [comment]
Server still responds:

```
{
  "acv_version" : "0.4",
  "error" : "Property value(0) for (persoString) in Algorithm (hmacDRBG (null)) is not valid. Validation: (Number Between (128) and (34359738368) modulus 8)"
}
```

**Comment by celic** [comment]
Sorry about that. A database update got left behind a bit. This has been fixed and you should notice an immediate impact.

**Comment by smuellerDD** [comment]
Confirmed, working.
