### ISSUE TITLE
Question on DSA PQGGen

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#357]
@smuellerDD @Kritner 
Is PQGGen working for anyone yet ?  My registration below still results in:

200 OK [ {
  "acvVersion" : "0.4"
}, {
  "vsId" : 1189,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 1189"
} ]

Registration:

        "capabilityExchange": {
            "algorithms": [
                {
                    "algorithm": "DSA",
                    "mode": "pqgGen",
                    "prereqVals": [
                        {
                            "algorithm": "SHA",
                            "valValue": "same"
                        },
                        {
                            "algorithm": "DRBG",
                            "valValue": "same"
                        }
                    ],
                    "capabilities": [
                        {
                            "pqGen": [
                                "probable"
                            ],
                            "gGen": [
                                "canonical"
                            ],
                            "l": 2048,
                            "n": 224,
                            "hashAlg": [
                                "SHA2-224"
                            ]
                        }
                    ]
                }
            ]

**Comment by smuellerDD** [comment]
Am Dienstag, 22. Mai 2018, 21:18:45 CEST schrieb Barry Fussell:

Hi Barry,

> @smuellerDD @Kritner
> Is PQGGen working for anyone yet ?  My registration below still results in:
> 
> 200 OK [ {
>   "acvVersion" : "0.4"
> }, {
>   "vsId" : 1189,
>   "status" : "error during vector generation",
>   "message" : "failed to generate tests for: 1189"
> } ]

Getting the same error. But somehow I thought Chris is working on that and 
thus I did not create an issue entry.

Ciao
Stephan

**Comment by celic** [comment]
You may have to re-register it. I hate saying "just try it again" without much of a reason... I don't see anything from the back-end indicating that something bad happened or even an error occurred.

I'll keep digging... The original error was fixed, and verified on our internal environment.

**Comment by bfussell** [comment]
It's not responding with "failed to generate tests" any longer, it's just not responding. Looping on retry.

**Comment by celic** [comment]
We have found the problem. This is related to the `isSample` optional flag used in some registrations to get quicker (smaller) responses. When that flag is not included, some of the deferred algorithms (where the IUT does the majority of the computation) would have trouble. I'm taking a look to make sure no other algorithms besides PQGGen are affected by this. We plan on getting a fix for this out today.

**Comment by Kritner** [comment]
A fix has been deployed that should resolve this issue, let us know if anything else is needed.
