### ISSUE TITLE
KDF spec consistency

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#358]
The JSON registrations for the KDFs in the specs don't seem to match and I am wondering which one I should go with.

KDF108 has alg: "KDF", mode: "counter", etc.
KDF135-TPM has alg: "TPM"
Most of the rest have alg: "kdf-componenets", mode: "snmp", etc

**Comment by elliemdaw** [comment]
Also, I haven't gotten through full interop for the KDFs that are implemented already, but the ones I have tested seem to be expecting the "kdf-components" version of the above

**Comment by celic** [comment]
There are two different KDF types. One is from SP800-108 and those are just "KDF" for the algo, with no mode. The "counter", "double pipeline iterator" and "feedback" are part of the capabilities.

The other type of KDF is a broad spectrum from SP800-135, and those are "kdf-components" for the algo with the mode being the specific component being tested, such as "snmp". All of those specs are separated out from each other in this repo. 

Specifically for TPM as a kdf-component, it is technically the same as a KDF with a double pipeline iterator, and so there is no corresponding gen/val process for specifically TPM. We are trying to figure out what to do about this for the CAVP. CAVS redirects you to use KDF with a double pipeline iterator.

**Comment by elliemdaw** [comment]
Okay awesome, so the 135's and 108 should be good to go for now but I will wait on making adjustments to TPM?

Thanks Chris!

**Comment by celic** [comment]
CAVS technically didn't support TPM, it just pointed you back to the SP800-108 KDF page instead. TPM as a standalone registration might be something we add in the future, but for now use a double pipeline iterator KDF.

**Comment by elliemdaw** [comment]
For KDF108 I am registering with a JSON that is set up exactly like the example JSON registration in the KDF108 spec and getting the following error:
"error" : "Incorrectly formatted JSON (101:18): expected field name was not provided: capabilities"

The spec doesn't show any place for a "capabilities" attribute

**Comment by celic** [comment]
This issue is captured in #386 and will be updated there.
