### ISSUE TITLE
KAS ECC SPEC: superfluous information

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#361]
The JSON value "mode" seems to be superfluous as follows: noKdfNoKc mandates component mode whereas kdfNoKc, kdfKc do not. This seems to imply that the value for mode can be derived from the presence of the respective objects. Besides what shall be the mode if tests for both, noKdfNoKc and kdfNoKc shall be defined?

**Comment by smuellerDD** [comment]
This applies to KAS FFC, too.

**Comment by Kritner** [comment]
@smuellerDD I agree that the registration for the component only version of the registration could change, but at the least it matches the same structure as `kdfNoKc` and `kdfKc`.

The intention of separating was to make it more apparent the differences between an algorithm registration (both `kdfNoKc` and `kdfKc`) and the component registration of `noKdfNoKc`.

Is this problematic?

**Comment by smuellerDD** [comment]
It is not problematic. But as the JSON is not intended to be immediately human-understandable, I feel that superfluous information helping human interpretation is should be removed.

The reason is that such duplication of information tends to only cause confusion and inconsistencies down the road when the spec is changed, since one may forget about such duplications.

**Comment by Kritner** [comment]
We may reevaluate this json representation at some point, but for the moment it's consistent between the different "modes" of kas.  Perhaps we can pick this up at some point if needed after the 1.0 release.
