### ISSUE TITLE
KAS ECC SPEC: How to define ECC CDH?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#367]
In the old CAVS tool, one could obtain a CVL for the raw ECDH shared Z computation by testing ECC CDH.

In the current ECC KAS Spec, I am unable to identify how to define such component testing. May I ask for a pointer? Thanks

**Comment by Kritner** [comment]
Hi @smuellerDD, have you taken a look at [ECC CDH Component Test](https://htmlpreview.github.io/?https://github.com/usnistgov/ACVP/blob/master/artifacts/acvp_sub_kas_ecc.html#rfc.section.5), [Appendix G](https://htmlpreview.github.io/?https://github.com/usnistgov/ACVP/blob/master/artifacts/acvp_sub_kas_ecc.html#rfc.appendix.G), [Appendix H](https://htmlpreview.github.io/?https://github.com/usnistgov/ACVP/blob/master/artifacts/acvp_sub_kas_ecc.html#rfc.appendix.H), and [Appendix I](https://htmlpreview.github.io/?https://github.com/usnistgov/ACVP/blob/master/artifacts/acvp_sub_kas_ecc.html#rfc.appendix.I) of the KAS ECC spec?

If you have already seen it, can you elaborate on the issue you're experiencing?

**Comment by smuellerDD** [comment]
I did not as I overlooked those -- I was focusing on chapter 2 as I thought that is the chapter defining the request structure.

Thanks for the pointer.

**Comment by Kritner** [comment]
I am now seeing there are at a minimum some formatting/content issues in that table I linked. I'll be making updates to the spec, but hopefully that's enough to get started

**Comment by smuellerDD** [comment]
Am Dienstag, 29. Mai 2018, 17:04:00 CEST schrieb Russ Hammett:

Hi Russ,

> I am now seeing there are at a minimum some formatting/content issues in
> that table I linked. I'll be making updates to the spec, but hopefully
> that's enough to get started

Thanks. If not, I will report back :-)

Ciao
Stephan
