### ISSUE TITLE
KAS ECC spec: local private key needed in test results?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#370]
The spec defines ephemeralPrivateIut which it seems the test response must return. This was not the case with the old CAVS.

May I sincerely request that this is dropped? Note, I have seen that the private key is not easily extractable. Thus, if the ACVP testing can live with only the public key (as it should be able to), NIST will allow ECDH / DH testing on production systems (as opposed to some development builds that make the private key available).

**Comment by Kritner** [comment]
@smuellerDD I would need to double check, but from what I can recall, one of the KAS test types provides both parties sets of information - both "server" and "IUT", and the iut is tasked with determining if given that information a successful negotiation can be performed.

If the spec shows that the IUT should be providing a private key to us, that is likely an error in the spec.

**Comment by smuellerDD** [comment]
I totally understand when the ACVP server needs to send the private key. But in Appendix E, there are test response examples which contain the private key. I.e. the IUT seems to be required to send the private key back to the ACVP server that it used for the shared secret generation. And I would like to ensure that the IUT's private key does not need to be sent.

**Comment by Kritner** [comment]
@smuellerDD thanks for catching this, I'll update the sample JSON to reflect this, note it also impacts the FFC spec
