### ISSUE TITLE
KDF135 SSH SPEC: test vector cipher definition

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#376]
The KDF135 SSH test vector uses as cipher definition the string "aes-128" and such. The DRBG which uses the very same concept uses "AES-128".

May I ask to make both implementations consistent?

**Comment by celic** [comment]
Yes. All of these should use the proper names of the algorithms... so "AES-128" would be correct.

**Comment by smuellerDD** [comment]
Am Montag, 4. Juni 2018, 18:44:38 CEST schrieb Chris Celi:

Hi Chris,

> Yes. All of these should use the proper names of the algorithms... so
> "AES-128" would be correct.

Yes, it is. I would suggest to keep that issue open to track the spec change.

Ciao
Stephan

**Comment by smuellerDD** [comment]
confirmed, working.

I leave the report open to track the spec update.

**Comment by smuellerDD** [comment]
Fixed by Russ with cc27d17bcd529ac1785d2d0495bb2df5659c692f and 2eb8ae3c7ee84e9422cdfdfdd3dcad2338f375e8
