### ISSUE TITLE
KDF IKEv2 SPEC: values in bits or bytes?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#379]
Please add an indicator whether integer values are bits or bytes.

For example, in section 2.3 this is not clear.

**Comment by smuellerDD** [comment]
This issue applies to KDF IKEv1, too.

**Comment by smuellerDD** [comment]
This applies to 800-108 KDF

**Comment by celic** [comment]
Everything should be assumed to be bits unless otherwise indicated. But of course clarity is preferred.

**Comment by smuellerDD** [comment]
Fixed with pull request #417.
