### ISSUE TITLE
KDF IKEv2 SPEC: Change algSpecs to capabilities

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#381]
When I register the following JSON request, the server responds with an error.

```
        {
          "algorithm":"kdf-components",
          "mode":"ikev2",
          "prereqVals":[
            {
              "algorithm":"HMAC",
              "valValue":"same"
            },
            {
              "algorithm":"SHA",
              "valValue":"same"
            }
          ],
          "algSpecs":[
            {
              "initiatorNonceLength":[
                64,
                65,
                128,
                177,
                256,
                512
              ]
            },
            {
              "responderNonceLength":[
                64,
                89,
                377,
                777,
                1024
              ]
            },
            {
              "diffieHellmanSharedSecretLength":[
                224,
                384,
                777,
                8192
              ]
            },
            {
              "derivedKeyingMaterialLength":[
                160,
                384,
                777,
                16384
              ]
            },
            {
              "hashAlg":[
                "SHA-1",
                "SHA2-256",
                "SHA2-384",
                "SHA2-512"
              ]
            }
          ]
        }
```

The error is:

```
{
  "acv_version" : "0.4",
  "error" : "Incorrectly formatted JSON (1:1890): expected field name was not provided: responderNonceLength"
}
```

**Comment by smuellerDD** [comment]
I saw that I used a wrong JSON format. I updated my format to the following which seems to be consistent with the SPEC. The aforementioned error still persists.

```
        {
          "algorithm":"kdf-components",
          "mode":"ikev2",
          "prereqVals":[
            {
              "algorithm":"HMAC",
              "valValue":"same"
            },
            {
              "algorithm":"SHA",
              "valValue":"same"
            }
          ],
          "algSpecs":[
            {
              "initiatorNonceLength":[
                64,
                65,
                128,
                177,
                256,
                512
              ],
              "responderNonceLength":[
                64,
                89,
                377,
                777,
                1024
              ],
              "diffieHellmanSharedSecretLength":[
                224,
                384,
                777,
                8192
              ],
              "derivedKeyingMaterialLength":[
                160,
                384,
                777,
                16384
              ],
              "hashAlg":[
                "SHA-1",
                "SHA2-256",
                "SHA2-384",
                "SHA2-512"
              ]
            }
          ]
        }
```

**Comment by celic** [comment]
Try this without the `algSpecs` object. So all the property arrays are flat in a single json object like this...

```
{
  "algorithm":"kdf-components",
  "mode":"ikev2",
  "prereqVals":[
    {
      "algorithm":"HMAC",
      "valValue":"same"
    },
    {
      "algorithm":"SHA",
      "valValue":"same"
    }
  ],
  "initiatorNonceLength":[
    64,
    65,
    128,
    177,
    256,
    512
  ],
  "responderNonceLength":[
    64,
    89,
    377,
    777,
    1024
  ],
  "diffieHellmanSharedSecretLength":[
    224,
    384,
    777,
    8192
  ],
  "derivedKeyingMaterialLength":[
    160,
    384,
    777,
    16384
  ],
  "hashAlg":[
    "SHA-1",
    "SHA2-256",
    "SHA2-384",
    "SHA2-512"
  ]
}
```

**Comment by celic** [comment]
This is an error in that the versions between the spec and the code are slightly out of alignment. The `algSpecs` object was something intended for v0.5 in code, but I think it occurs in the v0.4 spec.

**Comment by smuellerDD** [comment]
Am Montag, 4. Juni 2018, 17:01:18 CEST schrieb Chris Celi:

Hi Chris,

> Try this without the `algSpecs` object. So all the property arrays are flat
> in a single json object like this...

That returns:

```
{
  "acv_version" : "0.4",
  "error" : "Property value(160) for (derivedKeyingMaterialLength) in 
Algorithm (kdf-components (ikev2)) is not valid. Validation: (Number Between 
(512) and (16384) modulus 1)"
}
```

Note, the spec allows 160. When setting it to 512 as lowest value, it works.

I would suggest to keep it open to track the update of the SPEC.

Ciao
Stephan

**Comment by celic** [comment]
That error might require a separate issue. It is related to the server side validation. 160 is a valid value there.

**Comment by smuellerDD** [comment]
Am Montag, 4. Juni 2018, 19:47:59 CEST schrieb Chris Celi:

Hi Chris,

> That error might require a separate issue. It is related to the server side
> validation. 160 is a valid value there.

Ok, I will open another issue

Ciao
Stephan

**Comment by smuellerDD** [comment]
I am not sure I should change the spec now -- is the algSpecs component to be added in v0.5 or not?

If it will be added, I will leave the spec unchanged and we can close the issue.

**Comment by celic** [comment]
Some algorithms use "algSpecs", others use "capabilities". We should change
everything to use "algSpecs".

**Comment by smuellerDD** [comment]
Am Freitag, 6. Juli 2018, 17:16:35 CEST schrieb Chris Celi:

Hi Chris,

> Some algorithms use "algSpecs", others use "capabilities". We should change
> everything to use "algSpecs".

I am all for using a common definition.

In my pull request I have updated algSpecs to capabilities for several ciphers 
where I did not get an indication that algSpecs is the planned keyword. I 
guess that these patches should be dropped for 0.5?

Ciao
Stephan

**Comment by celic** [comment]
Sorry I commented without looking at the others. Yeah "capabilities" seems to be more common anyways, and is probably a bit more descriptive of the field.
