### ISSUE TITLE
KDF 800-108 SPEC: HMAC specification inconsistency

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#385]
Section 2.5 and the examples use HMAC-SHA224 and the like.

Other SPECs use HMAC-SHA2-224 and the like. May I ask to make it consistent?

**Comment by celic** [comment]
This has been deployed, please test again.

**Comment by smuellerDD** [comment]
Confirmed, working for Counter KDF.

The Feedback and Double Pipeline KDF fails:

```
}, {
  "vsId" : 4457,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 4457"
} ]
```

**Comment by celic** [comment]
Found the issue for these. It would affect any feedback or double pipeline iterator KDF that didn't have "none" as one of the fixed data orders. It has been fixed locally and I'll update when it gets deployed.
