### ISSUE TITLE
SHA cipher request uses old SHA string

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#387]
The SHA spec defines the use of SHA2-224 and the like as cipher string.

The server, however, only accepts SHA-224 and the like.

**Comment by celic** [comment]
Is this for a particular algorithm/mode? Or for a SHA2 registration in general?

**Comment by smuellerDD** [comment]
Am Montag, 4. Juni 2018, 18:51:03 CEST schrieb Chris Celi:

Hi Chris,

> Is this for a particular algorithm/mode? Or for a SHA2 registration in
> general?

This comment applies to all SHA2 algos when registering for the SHA cipher 
testing. I have not tested SHA3.

All other cipher register operations that require some hash reference use 
SHA2-256 et al. Only when registering for SHA ciphers, it uses SHA-256 et al.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Confirmed, working.
