### ISSUE TITLE
IKEv2: derivedKeyingMaterialLength implementation mismatch

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#388]
The ACVP server requires the derivedKeyingMaterialLength to be 512 at a minimum.

The SPEC allows 160 at a minimum.

**Comment by celic** [comment]
This has been fixed locally, and we will test it before pushing it out.

**Comment by celic** [comment]
This has been deployed. Please test again.

**Comment by smuellerDD** [comment]
confirmed, working
