### ISSUE TITLE
KAS FFC partial 

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#390]
Is there plans to support partial validation like CAVS does ?
KAS ECC has it in ACVP as well.

Thanks !

**Comment by celic** [comment]
Would you mind clarifying what you mean by a partial validation? Do you mean like KAS FFC/ECC with no KDF and no Key Confirmation?

**Comment by bfussell** [comment]
The CAVS file description is:
FFC Validity Test for dhEphem Key Agreement Role Responder  - DLC PRIMITIVE TESTING ONLY

The CAVs tool allows the following options:
1. Domain Parameter Generation
2. Domain Parameter Validation
3. Key Pair Generation
4. Full Validation
5. Partial Validation  <---- this one is not included in the ACVP docs
6. Key Regeneration
