### ISSUE TITLE
KAS ECC SPEC: response JSON keyword use unclear

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#393]
Section 3.2 of the spec outlines the different keywords. But it is unclear which keywords apply to which ECDH test schema.

For example, I am working on the onePassDh. There is no example provided and I have no clue which of the keywords I should use for the responses. I guess it is staticPrivateIut, staticPublicIutX and staticPublicIutY, but I am not sure.

**Comment by smuellerDD** [comment]
I guess I was wrong - I am following the keyword usage that is present in the corresponding VAL specification.

**Comment by atvassilev** [comment]
Stephan,

Thanks for going so thoroughly through the spec. I wonder if it would make things easier for everybody if you could simply submit a PR with a proposed fix for each inconsistency you find in a spec. We are currently short on resources to handle both the spec and implementation issues and would appreciate it if you could help us with that. If you are open to this, I will send you an invite to join the collaborator's team on ACVP and will go from there.

**Comment by smuellerDD** [comment]
Sure.

**Comment by smuellerDD** [comment]
Fixed with pull request #417.
