### ISSUE TITLE
KDF135 SSH SPEC: document that K is an MPINT

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#397]
I am working on the SSH KDF testing. All test results that I return receive a false verdict from the ACVP server. Knowing that my IUT implementation is correct, I dug a bit deeper.

For the discussion, let us focus on the example in the KDF135 SSH spec Appendix B and C where we have a test vector and a result.

That test vector has a K value of 260(!) bytes. When I pipe in that value into my IUT I get totally different results than provided in Appendix C.

Assuming that a standard DH MODP group is used and given the size, I speculate that group14 is used which is a 2048 bit group. That implies that the shared secret must by definition be 256 bytes. Now, when playing around, I removed the first 4 bytes from the K value in Appendix B. With that, my IUT calculates the expected results.

Note, leading zeros would be no issue in my implementation, but the removed 4 bytes contain values other than a zero.

That now makes me wonder: the K value in the test case seems to be not just the shared secret, but something more. Thus, may I ask for clarification what K really contains? Or on the other hand, may I request that the K value is truly the shared secret with the length defined by the used DH parameters?

**Comment by celic** [comment]
K was given a specific format by the IETF mpint. First, if the leading bit in K was a `"1"`, then `"00"` would be appended to the front. After that, the length of K would also be appended to the front of K, and that value was sent to the IUT. So we package K as an mpint and the IUT should unpackage it (stripping off either the first 4 or 5 bytes) and sending it through the KDF.

**Comment by smuellerDD** [comment]
Thanks for pointing that one out. After parsing the string as an MPINT as defined in RFC4251, it works.

I changed the title of the issue and leave it open as this must be mentioned in the SPEC.


Though, may I ask you to check a spurious error (i.e. all tcIds passed even for subsequent vsIDs): vsID 6146, tcId 342 shows an error verdict and I have no clue what went wrong. I see that K is an MPINT with 4 bytes length header and another zero byte before the real value is provided. Yet, that is taken care of (with or without the leading zeros, my implementation returns the same values).

**Comment by smuellerDD** [comment]
Fixed with pull request #417.
