### ISSUE TITLE
Max file upload size limited to 4MB

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#398]
For the test responses for IKEv2, I always get the following error from the server:

```
<html><head><title>JBWEB000065: HTTP Status 401 - JBWEB000009: No client certificate chain in this request</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>JBWEB000065: HTTP Status 401 - JBWEB000009: No client certificate chain in this request</h1><HR size="1" noshade="noshade"><p><b>JBWEB000309: type</b> JBWEB000067: Status report</p><p><b>JBWEB000068: message</b> <u>JBWEB000009: No client certificate chain in this request</u></p><p><b>JBWEB000069: description</b> <u>JBWEB000121: This request requires HTTP authentication.</u></p><HR size="1" noshade="noshade"></body></html>
```

This is reproducible every time I try to upload. I even obtained a fresh vector set, but even for this one I get this error.

vsIDs: 6031, 6071

**Comment by hbooth** [comment]
are the responses large?

**Comment by smuellerDD** [comment]
Yes, they are around 5.5 MB.

As I have seen that error in other situations, maybe I bumped against a maximum upload size as well?

**Comment by celic** [comment]
Yes, there is a maximum file upload size of 4MB. Please try to break up the registration into several smaller registrations.

**Comment by smuellerDD** [comment]
Am Mittwoch, 20. Juni 2018, 20:07:27 CEST schrieb Chris Celi:

Hi Chris,

> Yes, there is a maximum file upload size of 4MB. Please try to break up the
> registration into several smaller registrations.

It is not the registration, it is the test response file.

Ciao
Stephan

**Comment by celic** [comment]
Yes, the response file is large likely because there are many different properties selected in the registration. The two are directly related.

**Comment by smuellerDD** [comment]
Am Mittwoch, 20. Juni 2018, 20:20:14 CEST schrieb Chris Celi:

Hi Chris,

> Yes, the response file is large likely because there are many different
> properties selected in the registration. The two are directly related.

Are you saying I still should break up the request in order to reduce the size 
of the test response?

Ciao
Stephan

**Comment by atvassilev** [comment]
It seems to me, it is time to enable HTTP compression to reduce the size of the exchanged files.

**Comment by hbooth** [comment]
yes, for now.
this is a recognized limitation at the moment and we need to figure out a reasonable to resolve this

**Comment by celic** [comment]
@smuellerDD exactly. Sorry if I wasn't clear on that. For example, have one registration for each of the hash functions you wish to use. This will lead to smaller prompt files and thus smaller response files. It's obviously not a perfect solution as @atvassilev mentioned though.

**Comment by smuellerDD** [comment]
It is already registering :-)

I report back.

**Comment by smuellerDD** [comment]
Splitting it up works.

**Comment by hbooth** [comment]
we actually want to fix this, the prior suggestions were only workarounds

**Comment by hbooth** [comment]
@smuellerDD also, a question and an idea, maybe. When you try to post your response to the endpoint is this the first endpoint you are attempting to hit on the server after more than a minute? If so, could you try hitting the login (perhaps renew your JWT) and then immediately try the POST? It's a shot in the dark on my part.

**Comment by smuellerDD** [comment]
Am Mittwoch, 20. Juni 2018, 21:39:17 CEST schrieb Harold Booth:

Hi Harold,

> @smuellerDD also, a question and an idea, maybe. When you try to post your
> response to the endpoint is this the first endpoint you are attempting to
> hit on the server after more than a minute? If so, could you try hitting
> the login (perhaps renew your JWT) and then immediately try the POST? It's
> a shot in the dark on my part.

I am slightly unsure about your idea.

What my client does is:

1. it verifies whether the JWT token is stale (older than 30 minutes). If so, 
it re-login into the server.

2. immediately after the step 1 (regardless whether a login was performed or 
not), the POST starts.

Thus, if the response is sent within 30 minutes of the request, no re-login is 
done. Otherwise it is.

Over the last days, I tried to upload one and only one test result whose 
request was generated days ago. That implies that my client re-logs in 
followed by an immediate POST. Here is a log to give you some ideas:

```
ACVPProxy (08:46:05) Status: Logging into ACVP server to refresh existing auth 
token
ACVPProxy (08:46:14) Error: Process following server response: 
<html><head><title>JBWEB000065: HTTP Status 401 - JBWEB000009: No client 
certificate chain in this request</title><style><!--H1 {font-
family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:
22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-
color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-
serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-
family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-
family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-
family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A 
{color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </
head><body><h1>JBWEB000065: HTTP Status 401 - JBWEB000009: No client 
certificate chain in this request</h1><HR size="1" 
noshade="noshade"><p><b>JBWEB000309: type</b> JBWEB000067: Status report</
p><p><b>JBWEB000068: message</b> <u>JBWEB000009: No client certificate chain 
in this request</u></p><p><b>JBWEB000069: description</b> <u>JBWEB000121: This 
request requires HTTP authentication.</u></p><HR size="1" noshade="noshade"></
body></html>
ACVPProxy (08:46:14) Error: Failure to submit testID 886 with vsID 6032
ACVPProxy (08:46:14) Status: Processing completed for testID 886 with vsID 
6032 with return code -111
```

Note, the log indicates that the re-login operation was successful (otherwise 
an error message would be shown). I.e. the Error message in the log was the 
result of the POST operation.

Are you suggesting another approach?


Ciao
Stephan

**Comment by hbooth** [comment]
The test you showed was basically the one I was asking for. Thanks.
Further investigation will be required.
I was hoping that the TLS negotiation in the login phase would create a "session" that would avoid another negotiation for the POST phase but that does not appear to have been the case and they are treated independently.

**Comment by hbooth** [comment]
@smuellerDD can you see if adding the "Keep-Alive" header changes the behavior?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive
https://tools.ietf.org/id/draft-thomson-hybi-http-timeout-01.html

(I tried to find an authoritative reference describing the Keep-Alive header but failed to find anything as final.)

Both of the links above seem to agree though.

**Comment by smuellerDD** [comment]
Just as an FYI: I received AES-GCM test vectors of 12 MB where the response is more than 5 MB. So, I cannot upload that vector. Surely, I can cut the vector by, say, having individual tag and AAD lengths in the request. But I guess that is not really user friendly.

vsID 11229

**Comment by hbooth** [comment]
This, I believe, is resolved with the large file size upload. If there are any issues with that processing, a new issue would be a better way to track this moving forward.

**Comment by smuellerDD** [comment]
Am Montag, 1. April 2019, 17:32:14 CEST schrieb Harold Booth:

Hi Harold,

> This, I believe, is resolved with the large file size upload. If there are
> any issues with that processing, a new issue would be a better way to track
> this moving forward.

I agree that we can close this issue. But the large file upload support is 
non-operational as far as I see.

See issue #532

Ciao
Stephan
