### ISSUE TITLE
no-certificate option

### ISSUE THREAD

**Issue by atvassilev** [usnistgov/ACVP#4]
Should we add a 'no-certificate' option to ACVP in the registration? There are cases where a company may want to validate a crypto implementation without getting a public certificate. Example scenarios are beta versions of unannounced products - the company may want to ensure the beta is good but does not want to preempt a public product release. 

If this option is set, the validation server would perform all validation work except it would not publish a certificate. The server would only return a success, e.g. 200 OK, just like it is described in Section 11.4 of the current ACVP spec. 

What do you all think?

**Comment by DBugger32** [comment]
Yes, I think that is an excellent idea.  It also provides a path for
re-thinking the meaning of "certificate" and the utility of "publishing".

**Comment by bfussell** [comment]
Seems like a reasonable addition to the protocol spec.  I’ll look into adding that.

Thanks,

Barry

**Comment by atvassilev** [comment]
Resolved with Barry's commit (fd56017cf426b30665c30c5d474214bb9fe4f294) of today.
