### ISSUE TITLE
KAS FFC: partialValidation missing?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#409]
SP800-56A section 5.6.2.3.2 defines the partial validation of the public key. The KAS FFC spec does not allow to define it. Also when sending partialVal to the server during the register operation, the ACVP server rejects it.

Is the partial validation not testable?

**Comment by bfussell** [comment]
FFC does not have that option in CAVS, at least the version I've seen. does not
The CAVS that I  have seen says:
5. Partial Validation (as specified inSection 5.6.2.6, ECC only)

**Comment by smuellerDD** [comment]
Am Montag, 25. Juni 2018, 19:26:07 CEST schrieb Chris Celi:

Hi Chris,

> @bfussell had a similar issue opened #390 which has been closed. Perhaps
> that could help?

If I understand correctly, #390 was about component testing. I am referring to 
the partial validation of the public key as defined in SP800-56A section 
5.6.2.3.2. Or maybe I mmisunderstand what these flags are.


Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Montag, 25. Juni 2018, 19:46:08 CEST schrieb Barry Fussell:

Hi Barry,

> FFC does not have that option in CAVS, at least the version I've seen. does
> not The CAVS that I  have seen says:
> 5. Partial Validation (as specified inSection 5.6.2.6, ECC only)

Is this an oversight or intentional? As I am trying to fix the Linux kernel, I 
am wondering whether a partial validation support is sufficient or whether a 
full validation is required for FFC.

Ciao
Stephan

**Comment by bfussell** [comment]
I have no idea, it's just an observation I made after I opened the #390

**Comment by celic** [comment]
So from what I have heard, newer versions of CAVS ignored these fields and they were deemed out of scope of algorithm testing. This issue came up a bit with #389 but not quite in this way. Right now in the server, these are used to modify the test cases given to the IUT. 

It does seem like KAS-FFC 'forgets' this assurance is valid when checking the registration file. Let me do some digging just to make sure this wasn't intentional, it's been a little while since this was originally developed.

**Comment by celic** [comment]
Yup, CAVS says that Partial Validation is only a valid option for KAS-ECC, not KAS-FFC. Unfortunately I don't have any insight to the reasoning behind that decision. I can look into that if you are curious @smuellerDD, but for now there is no issue in ACVP here.

**Comment by smuellerDD** [comment]
Am Donnerstag, 28. Juni 2018, 21:08:20 CEST schrieb Chris Celi:

Hi Chris,

> Yup, CAVS says that Partial Validation is only a valid option for KAS-ECC,
> not KAS-FFC. Unfortunately I don't have any insight to the reasoning behind
> that decision. I can look into that if you are curious @smuellerDD, but for
> now there is no issue in ACVP here.

Thanks. It is curiousity only. Thus, do not spend precious cycles on chasing 
it down. Yet, if you find an answer, I would be grateful for having it, 
because folks do ask.

Ciao
Stephan
