### ISSUE TITLE
KDF135 SNMP

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#410]
The SNMP spec defines that passwordLength should be a bit value, but as far as I can tell, the server is returning passwords with the specified numbers of bytes, not bits. I suspect this mismatch may be causing the following error when I try to specify the number of bytes I want in the passwords:

    "vsId" : 10455,
    "status" : "error during vector generation",
    "message" : "failed to generate tests for: 10455"

Usually I see this error when there is some invalid combination of parameters, which is why I suspect somewhere bit and byte lengths are getting confused

**Comment by celic** [comment]
Yeah that'll be a spec error. It should be in bytes not bits. As the password is some [a-z0-9] value, it really doesn't make sense to be in bits when each character is a single byte unlike the normal hex values ACVP deals with.

**Comment by elliemdaw** [comment]
I am not able to get vectors when I treat the value as a byte length... it always returns the error I mentioned above :( more specifically, when I ask for a password length of anything less than 64, the server gives an error that it failed to generate tests

**Comment by celic** [comment]
Ah the server code gets a bit confused between bits and bytes here. I see the problem. The registration is supposed to be in bytes, but the part of the server checking to see if the registration is valid expects bits. 

The easiest solution here would be to have all the password lengths be treated as bits (so the spec and registration validation are correct). This requires an update on our end to have the test cases consider each character to be 1 byte. I'll update this when we can get the fix pushed out.

**Comment by celic** [comment]
Try this again now. Register the password length as bits.

**Comment by elliemdaw** [comment]
Works for me now, thanks for your quick response! :)
