### ISSUE TITLE
Sample CTR DRBG registration anyone ?

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#425]
We had this working a while back, but I'm unable to get the right combination
to get vectors now, seeing:
  
"vsId" : 1210,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 1210"

**Comment by Kritner** [comment]
From Registration:
```
{
	"algorithm": "ctrDRBG",
	"isSample": false,
	"predResistanceEnabled": [true],
	"reseedImplemented": false,
	"capabilities": [{
		"mode": "AES-128",
		"derFuncEnabled": true,
		"entropyInputLen": [{
			"min": 128,
			"max": 256,
			"increment": 128
		}],
		"nonceLen": [{
			"min": 0,
			"max": 64,
			"increment": 64
		}],
		"persoStringLen": [{
			"min": 0,
			"max": 256,
			"increment": 256
		}],
		"additionalInputLen": [{
			"min": 0,
			"max": 256,
			"increment": 256
		}],
		"returnedBitsLen": 256
	}]
}
```

With `derFuncEnabled`, `nonceLen` must be at a minimum half the `keyLength`, IIRC that equates to security strength in some manner, I would need to double check on that however.

**Comment by bfussell** [comment]
Hmmm, used your exact json and still got the same error last night.
Today, however I get no vsId:

200 OK [{"acvVersion":"0.4"},{"capabilityResponse":{"vectorSets":[]},"testSession":{"testId":541}

**Comment by Kritner** [comment]
Sorry Barry, that JSON I posted was ***your*** JSON, I didn't make any corrections to it

**Comment by bfussell** [comment]
Ha ! I had tried so many different options I didn't recognize that :)
The nonceLen change did the trick, Thanks !
