### ISSUE TITLE
v0.5: dependencies

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#432]
After updating the implementation to v0.5, I am scratching my head about the /dependencies definition., Surely, it is very nice to have that at the level of sophistication specified in the SPEC.

But I would think it is safe to assume it will end up in a mess when every user can create entries there. For software, SWIDs or CPEs are suggested. But still, those are subjective. For processors, Intel has a nice reference with their ARK database. But will every user adhere to it? What about other processor vendors which may not have such fine-grained specification? In this case, multiple different entries for the same are to be expected.

Are there plans that this dependency database is maintained by a central body like NIST?

PS: This note is *not* about complaining about implementing the dependency handling. It is only a discussion about how to actually make use of it.

**Comment by hbooth** [comment]
I have started some discussions along these very lines a couple of months ago. I hope to have a document describing the best process for maintaining this data and providing a shared repository of this information. At the current moment that work is in a temporary hibernation while we work to get the ACVP code completed, but I expect to restart this work as soon as I am able.
After I have a rough draft and have passed it around some internal stakeholders I plan to engage the CMUF and other interested stakeholders to get input. More to come as time becomes available to further develop this.

**Comment by smuellerDD** [comment]
Am Dienstag, 28. August 2018, 14:10:09 CEST schrieb Harold Booth:

Hi Harold,

Ok, so I guess it would be permissible for me to implement the dependency 
handling to the best of my knowledge know, knowing that even I may cause a 
mess in the (development) ACVP database?!

I.e. we can see that the "mechanics" of the dependency handling works, but it 
will be by far not optimal for maintaining a consistent database.

Ciao
Stephan

**Comment by hbooth** [comment]
The demo environment can be and is expected to be messy. We will likely need to reset it on occasion when it becomes too much. The demo environment is exactly where you should test getting everything working.
Once we develop a reasonable process for managing the data I also hope that demo would become a place for testing out the process as well; within an environment where errors are expected.

**Comment by smuellerDD** [comment]
Ok
