### ISSUE TITLE
v0.5: publish request and signature

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#435]
The v0.5 specification outlines in section 11.7.4.1 that the JSON data to be sent with the PUT operation to publish the data must contain some "signature" and "certificate".

Can you please either point me to the specification or provide a rationale of what I shall do here? Thanks.

**Comment by hbooth** [comment]
Signature will be removed from 1.0 version. It may be added back in if we find that this feature is needed.
