### ISSUE TITLE
KDF135 IKEv1 Spec: Discrepancy under "optional" for preSharedKeyLength

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#436]
Hello!

In Table 2, for preSharedKeyLength the value under the Optional column is "no".
Later on in Table 5, the value under the Optional column is "yes".
I believe the value in Table 2 needs to be changed to "yes".

Also related, it would be good to make it explicitly known to the reader that the preSharedKeyLength and preSharedKey JSON key:value will only be present during the PSK authentication method.

Please let me know if you need more information or clarification.

Thanks,
Philip

**Comment by celic** [comment]
Ah yes you are correct. I think the intention for Table 2 was "no when the authentication method is PSK", but that information didn't seem to make it into the specification.
