### ISSUE TITLE
TDES CFB1 MCT decrypt error

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#437]
15887
The vectorSet ID displaying the issue

I finally managed to get TDES CFB1 MCT implemented. I tested my IUT and my MCT implemented with CAVS 21.4. Encrypt and decrypt match the fax files after manually matching the JSON output with fax files.

However, the ACVP server tells me that my CFB1 MCT decryption responses are wrong starting with the 3rd iteration (the initial results are correct). May I ask you to check on your end whether you see whether the ACVP server response is appropriate?

Thanks

**Comment by Kritner** [comment]
From last comment https://github.com/usnistgov/ACVP/issues/438#issuecomment-418706184:

> vsID: 16774
> 
> Note, I just rechecked the MCT CFB1 decrypt operation with an example from
> CAVS 21.4 and I get the expected keys/pt/ct/IVs.

I'm not seeing anything obviously wrong on our end either unfortunately.  I did run your particular set's results against our expectations, and here's a snippet of that:

```
Info GenValApp Validate Test Vectors
----- PASS ----- tcId: 962, index: 0 -----
----- FAIL ----- tcId: 962, index: 1 -----
Expected key: 3D4045C47C3B7337A4AB6864EF5EE07932AB8C62E5465D52 
Actual key: 3D4045C47C3B7337A4AB6864EF5EE07932AB8C62E5465D52
Expected iv: 8C9D8543354A117E 
Actual iv: 8C9D8543354A117E
Expected ct: 0 Actual ct: 1
Expected pt: 0 Actual pt: 1
----- FAIL ----- tcId: 962, index: 2 -----
Expected key: 8337D0FE10FE98151CDAE98AB64AA808A7CD8FCEB6ADD55E 
Actual key: EF971638E9251F8C9D805E94A23B3BC7027098580EDF5852
Expected iv: 95D28CE9DBBC591E 
Actual iv: 4EB2CE548C0A2496
Expected ct: 0 Actual ct: 1
Expected pt: 0 Actual pt: 1
```

In the above, it looks like the first round (index 0) is fine, everything matches - `key`, `iv`, `pt`, `ct`.  Second round, looks like we're mostly ok - starting `key` and `iv` match, but the starting `ct`s don't, which then throws everything off going forward (including the `pt` for that same round).

I haven't had a chance to really dig into the internals of this algo but I was curious, have you tested CFB with any other shift sizes against ACVP?  We're using the same implementations of MCT, with just a shift size variant; so if you saw the issue in cfb1 decrypt mct, it should also be present for 8 and 64.

Additionally, I have taken some test vectors from CAVS for CFB MCT decrypt and run them against our crypto impl, and had success.  It ***could*** be an issue with our serialization given that, but I'm curious if you've had luck with the other CFB shift sizes, because if CFB1 is broken, they should all be broken (regarding MCT CFB* decrypt).

**Comment by smuellerDD** [comment]
The error was fully on my side, I recalculated the new round CT wrongly (the CAVS21.4 check matched only for the first 5 entries and I did not check further :-( ).

Sorry for the noise.

But after having implemented the AES and TDES MCT, may I formally ask to reconsider the requirement for these MCT tests? I see absolutely no value added for these tests to identify problems in the cipher. If one round of encryption (with one or more cipher blocks) works, how can multiple interleaved blocks not work? I.e. I consider the MCT test as only a verification whether one can write a harness complying with the (very convoluted TDES) MCT specification. AES is more sane, but TDES is the worst. Even, for CFB and OFB you need to reach inside the cipher to get intermediate values that for some implementations you simply cannot get to using the final product. Only with a debug build you could get such intermediate values.

Thus may I inquire to consider dropping the MCT tests? Potentially replace them with more AFT tests.

**Comment by atvassilev** [comment]
@smuellerDD I understand your frustration but don't quite share the view that the MCT should be replaced with more AFT's. I think the way to look at this is through a code coverage perspective. The AFT's are designed to be deterministic tests that result in a somewhat limited code coverage. The purpose of the MCT is to implement (pseudo) random tests with valid yet not fully predictable inputs aiming to exercise different branches in the implementation and ultimately achieve good code coverage. One may think of some sort of fuzzing to get similar assurance but I am not aware of how to measure the coverage for a truly random test. 

So when you say 'replace them with more AFT tests', my question is what kind of AFT's would give us assurance of reasonable code coverage? If there is a test that would provide better quantifiable code coverage than MCT, we would consider replacing it.

**Comment by atvassilev** [comment]
@Kritner Yes, I phrased it poorly. Even though the current AFT's test with some random inputs, their code coverage is still limited.

**Comment by smuellerDD** [comment]
Am Mittwoch, 5. September 2018, 20:08:57 CEST schrieb Apostol Vassilev:

Hi Apostol,

Let me deconstruct the MCT to make my case. For starters, please let us 
disregard the specialities of the TDES OFB and CFB MCT which require to read 
out the final IV from the state.

All MCT have the following concept:

1. provide key, IV, pt/ct

2. invoke the cipher and get ct/pt

3. shuffle the key from step 1 in some form, shuffle the IV from step 1 in 
some form, shuffle the pt/ct from step 1 in some form

4. go to step 1.


The cipher invocation in step 2 is always and solely performed with the 
external interfaces, e.g. AES-CBC(key, IV, pt). The shuffling of the input 
data using the output of the cipher does not seem to me to trigger any special 
code paths in the cipher that would otherwise not be triggered.

Thus, an individual round of MCT is nothing more than an AFT with some 
(pseudo-)random input values. The pseudo-randomness comes from the fact that 
the cipher output behaves like white noise.

Thus, why not have some AFT with randomly generated input? I see absolutely no 
difference between an AFT with random input compared to one round of MCT. The 
entire shuffling of the input data is solely performed by the CAVS harness and 
does not trigger any code paths in the cipher implementations.


Now to the TDES OFB/CFB IV: If you want to test that the cipher IV management 
is appropriate, why not providing input data for an AFT that is a multiple of 
the block size? With multiple blocks, the cipher must advance its IV and you 
see the proper advancement of the IV. If the IV would not be properly 
advanced, the ciphertext (or plaintext) would not be as expected. The 
intermediate IV required by TDES OFB/CFB MCT is only used to shuffle the input 
data. So, again, I fail to see how that special shuffling triggers any special 
code path that would otherwise not be triggered with random input?


As the MCT only shuffles the input data in some (more or less) non-
deterministic way and require the cipher invocation with that modified input 
data using the standard processing interface, I see no benefit in terms of a 
better code coverage or similar using MCT.

The only value-add I can think of is delivered with testing using the 
intermediate IV for TDES CFB/OFB. But that can be replaced with a test using 
multiple input blocks.


What strikes me really odd though is that the AFT tests allow the testing of 
exactly one block of AES. The AFT should always mandate to test at least 2 
blocks. The block chaining logic is never fully triggered when invoking a 
cipher with only one block.

Ciao
Stephan

**Comment by celic** [comment]
Yes, @atvassilev means the sheer number of times the algorithm must be run with the "random" data means we get much wider coverage. Getting the algorithm to run with such random data would be impossible for strictly specified AFTs. However, there is something to be said that perhaps the methods used to create the new keys or new messages could be made simpler (yet still seem "random" to the implementation)...

I think Apostol mentioned it briefly in conversation to me a while back that the most common problem in MCTs was the client's implementation not the crypto implementation. As the tests have merit and aren't going away, perhaps they can be made simpler to implement.

**Comment by smuellerDD** [comment]
Am Mittwoch, 5. September 2018, 20:43:36 CEST schrieb Chris Celi:

Hi Chris,

> I think Apostol mentioned it briefly in conversation to me a while back that
> the most common problem in MCTs was the client's implementation not the
> crypto implementation. As the tests have merit and aren't going away,
> perhaps they can be made simpler to implement.

I see. Yes, I fully concur that you can have one input vector to cover a large 
number of pseudo-random input data. For that, I can understand if we leave 
MCT.

But for that, I would recommend some changes:

- have one and only one type of simple key shuffling (e.g. XOR the input data 
with as many copies of the output data -- no "remembering" of the last but one 
or last but two outputs, etc).

- have two or more blocks per MCT round to guarantee you include the block 
chaining testing

I can live with the AES MCT which has no real exception, it only misses the 
two blocks or more of input.

But TDES is over the top. Each block chaining mode and each direction has its 
own way of shuffling.

Ciao
Stephan

**Comment by atvassilev** [comment]
Well, the MCT relies on a pseudo random process to generate the inputs for each round, starting from an initial condition. The pseudo random process is implemented by two parts: the block cipher and the "input shuffling" part in the harness. So, in this sense, the MCT is like the pseudo-random generators in Knuth's book The Art of Computer Programming, volume 2. Getting a part of this pseudo random number generator will get you in trouble and it has gotten many people. 

Now, I am not saying this is the perfect irreplaceable method. I am saying however, give me something better if we are going to go through the trouble of changing it. Intuitively, we all say it has to be random if we are going to get some code coverage in an unknown to us implementation (a black box). The question is what kind of randomness?

**Comment by atvassilev** [comment]
@smuellerDD How bout the flip side: transmitting large amounts of explicit test data is not the best way, especially if the communication line may be limited in some way? You already have experienced the limitations around the size of the JSON files our server can currently handle. 

I think the MCT gives you a way to define very economically a large amount of pseudo-random tests, meaning with minimal transmission costs. If nothing else, this property is valuable. 

Again, I am not saying the current implementation of MCT is perfect. I am inclined to think one can improve the test while keeping the nice properties. This is something to consider for after the first release of ACVP this fall. We will let you know when we get serious about this and you can bug us if for some reason you don't hear from us for a while.

**Comment by smuellerDD** [comment]
Am Mittwoch, 5. September 2018, 23:23:52 CEST schrieb Chris Celi:

Hi Chris, Apostol,

First, thanks for being open to rework the MCT. I agree that this is not high-
priority though and should be considered after ACVP becomes stable.

Re debug support: Chris, the current output rounds are not helpful for debug. 
What would be really helpful for debugging is, say, the first 5 rounds after 
one shuffle operation. I.e. it would be the outputs after the first 5 inner 
loops at the beginning and the first 5 outer loops. Here one can see whether 
their shuffle operation is implemented correctly.

Ciao
Stephan
