### ISSUE TITLE
TDES CFB1: test failures

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#438]
When testing the IUT and my JSON tool with CAVS 21.4, the CFB1 encryption and decryption operation return the expected results.

However, the ACVP server flags all my (non-MCT) test results as failures. The JSON response does *not* contain the ctLen or ptLen key words as I thought that they are not necessary any more and are just a leftover that needs to be cleaned up to be consistent with all other cipher implementations.

May I ask what I am missing for CFB1?

vsiD: 15887

**Comment by Kritner** [comment]
@smuellerDD it looks like the `ptLen` and `ctLen` are currently required (though for some reason not validated as being present). Since v0.4 is on its way out, we were considering not updating this set to validate the required pt/ctLen inclusion - would you be able to include it in your responses ? I believe that should correct the issue.  

This *could* be related to your #437, but it's strange that encrypt would validate, but not decrypt.  Might need a closer look.

**Comment by smuellerDD** [comment]
Am Dienstag, 4. September 2018, 15:14:26 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD it looks like the `ptLen` and `ctLen` are currently required
> (though for some reason not validated as being present). Since v0.4 is on
> its way out, we were considering not updating this set to validate the
> required pt/ctLen inclusion - would you be able to include it in your
> responses ? I believe that should correct the issue.

Thanks for the clarification. I am just downloading TDES vectors which for now 
takes me more than an hour without getting any vectors so far. I will report 
back once I got the vectors.

I am not sure I understand the way forward: I would like to suggest to drop 
the requirements for ptlen and ctlen as this information is implicit -- it is 
always one bit per definition.
> 
> This *could* be related to your #437, but it's strange that encrypt would
> validate, but not decrypt.  Might need a closer look.

I will check with ptlen/ctlen.

Ciao
Stephan

**Comment by Kritner** [comment]
> I would like to suggest to drop
the requirements for ptlen and ctlen as this information is implicit -- it is
always one bit per definition.

by per definition are you talking about per test case?  This is true in ***most*** cases, but the multi block message tests (which I believe are lumped in with the "AFT" types from the IUT perspective) have an increasing number of bits per case within the group.

**Comment by smuellerDD** [comment]
Am Dienstag, 4. September 2018, 15:14:26 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD it looks like the `ptLen` and `ctLen` are currently required
> (though for some reason not validated as being present). Since v0.4 is on
> its way out, we were considering not updating this set to validate the
> required pt/ctLen inclusion - would you be able to include it in your
> responses ? I believe that should correct the issue.
> 
> This *could* be related to your #437, but it's strange that encrypt would
> validate, but not decrypt.  Might need a closer look.

I submit the following:

AFT encrypt part

```
  {
    "vsId":16767,
    "testResults":[
      {
        "tcId":1,
        "ct":"80",
        "ctlen":"1"
      },
```

AFT decrypt part
```
      {
        "tcId":471,
        "pt":"00",
        "ptlen":"1"
      },
```

MCT encrypt part
```
      {
        "tcId":961,
        "resultsArray":[
          {
            "key1":"6164f75ff073f880",
            "key2":"e50efb15c611a377",
            "key3":"bce9a8879886815c",
            "pt":"80",
            "ct":"80",
            "iv":"a1cafea55ea21660",
            "ctlen":"1"
          },
```

MCT decrypt part
```
      {
        "tcId":962,
        "resultsArray":[
          {
            "key1":"0936433eca1c5f07",
            "key2":"c5aa190eceab012b",
            "key3":"ff570777b500d73a",
            "ct":"00",
            "pt":"00",
            "iv":"03348a6593d5a7ae",
            "ptlen":"1"
          },
```

I receive:

```
{
  "acv_version" : "0.4",
  "error" : "Incorrectly formatted JSON (11:18): Unknown or disallowed 
submission property: ctlen"
}
```

Note, I receive that error even when I format the ptlen/ctlen as JSON integers 
(the spec is not consistent here).

PS: For AES-CFB1, I get passing resutls *without* the ctlen/ptlen.

vsID: 16767

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, 4. September 2018, 16:58:49 CEST schrieb Russ Hammett:

Hi Russ,

> > I would like to suggest to drop
> 
> the requirements for ptlen and ctlen as this information is implicit -- it
> is always one bit per definition.
> 
> by per definition are you talking about per test case?

Yes, for each test -- as you always get as many output bits as you insert, the 
ACVP server a-priori knows how many bits it has to expect. Thus, I do not see 
the need for the length parameter.

> This is true in
> ***most*** cases, but the multi block message tests (which I believe are
> lumped in with the "AFT" types from the IUT perspective) have an increasing
> number of bits per case within the group.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, 4. September 2018, 17:22:16 CEST schrieb Russ Hammett:

Hi Russ,

> > Yes, for each test -- as you always get as many output bits as you insert,
> > the
> ACVP server a-priori knows how many bits it has to expect. Thus, I do not
> see the need for the length parameter.
> 
> Indeed, it may make sense to not include it in v0.5 from the IUT end, will
> need to look at that possibility.

Thank you.

> I'm not sure if AES-CFB and TDES-CFB are
> apples to apples comparisons for v0.4 are they?  I was thinking AES-CFB was
> still passing around individual bits, rather than our standard hex
> `BitString`.

Hm, now I am starting to get unsure -- did I really test AES-CFB1 with the 
ACVP server or only by comparing my implementation to CAVS? I guess I only did 
the CAVS cross-check.

That said, I think there was a recent change to update the CFB spec for AES to 
be more in line with the TDES-CFB spec. Hence, I can test my AES-CFB1 support 
with ACVP for 0.5.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, 4. September 2018, 17:30:04 CEST schrieb Harold Booth:

Hi Harold,

> have you tried ctLen?

that is the trick -- the ACVP server accepted it now.

Ciao
Stephan

**Comment by hbooth** [comment]
Until we get everything completely working you can try this in the future:

List all available algorithms:
`https://demo.acvts.nist.gov/acvp/validation/acvp/register/help/algorithm/list`

`https://demo.acvts.nist.gov/acvp/validation/acvp/register/help/algorithm/{name}[/{mode}]`

Where `{name}` is the name of the algorithm from the list and `{mode}` is optional
// Example detail for an algorithm
```
https://demo.acvts.nist.gov/acvp/validation/acvp/register/help/algorithm/TDES-CFB1
https://demo.acvts.nist.gov/acvp/validation/acvp/register/help/algorithm/AES-CFB1
https://demo.acvts.nist.gov/acvp/validation/acvp/register/help/algorithm/RSA/keyGen
```
The output is not the easiest but it is only intended as a debugging output.

**Comment by smuellerDD** [comment]
Am Dienstag, 4. September 2018, 17:30:04 CEST schrieb Harold Booth:

Hi Harold,

> have you tried ctLen?

The AFT tests pass now.

The MCT encrypt test still passes.

The MCT decrypt now fails completely even for the first entry.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, 4. September 2018, 17:36:46 CEST schrieb Harold Booth:

Hi Harold,

> Until we get everything completely working you can try this in the future:
> 
> List all available algorithms:
> `https://demo.acvts.nist.gov/acvp/validation/acvp/register/help/algorithm/li
> st`
> 
> `https://demo.acvts.nist.gov/acvp/validation/acvp/register/help/algorithm/{n
> ame}[/{mode}]`
> 

Is this online now or only after 0.5 is enabled?

Ciao
Stephan

**Comment by hbooth** [comment]
it is online now and is specific to 0.4 for the moment, some of this functionality will be available 0.5 but with different endpoints.

**Comment by Kritner** [comment]
@smuellerDD can you provide the vsId for the session you're referring too in the most recent comment:

> The MCT decrypt now fails completely even for the first entry.

from https://github.com/usnistgov/ACVP/issues/438#issuecomment-418417908?

**Comment by smuellerDD** [comment]
Am Mittwoch, 5. September 2018, 13:41:47 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD can you provide the vsId for the session you're referring too in 
the most recent comment:
> > The MCT decrypt now fails completely even for the first entry.
> 
> from https://github.com/usnistgov/ACVP/issues/438#issuecomment-418417908?

vsID: 16774

Note, I just rechecked the MCT CFB1 decrypt operation with an example from 
CAVS 21.4 and I get the expected keys/pt/ct/IVs.

Ciao
Stephan

**Comment by Kritner** [comment]
Since it looks like the base issues around cfb are resolved, I'll take up the MCT decrypt issues in #437.
