### ISSUE TITLE
KDF108 Spec: Missing "deferred" in table

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#440]
Hello,

I have a few things to discuss.

1) In Table 6, the "deferred" JSON appears to be missing.

2) In Table 6, it might be good to explicitly include a new element "ivLength" for the iv in bits, or indicate as to how the length can be implicitly inferred from another element (i.e. macMode). To make sure I'm understanding correctly, if the macMode is HMAC-SHA1 then the length of "iv" in bits would match the HMAC output length (160 in this case).

3) In Table 6, it would be great to also have an explicit length similar to point 2 above, or explanation how to calculate the length. Looking through some server JSON, it does not appear to be based on the macMode

4) In Table 9, it may be beneficial to give some more details on the expected fixedData. For instance, does it have a min/max length? Maybe point the reader to 800-108 document? I have read through 800-108 document and don't have a clear idea on what is expected from fixedData. An explanation, if only in this issue, would help me personally :)

Particularly for 2 and 3, knowing the expected length will help libraries that want to perform string length checks.

Hope that all made sense. If I'm misunderstanding anything please let me know.

Thanks!
Philip

**Comment by smuellerDD** [comment]
Am Freitag, 7. September 2018, 18:27:39 CEST schrieb Philip Perricone:

Hi Philip,

> Hello,
> 
> I have a few things to discuss.
> 
> 1) In Table 6, the "deferred" JSON appears to be missing.
> 
> 2) In Table 6, it might be good to explicitly include a new element
> "ivLength" for the iv in bits, or indicate as to how the length can be
> implicitly inferred from another element (i.e. macMode). To make sure I'm
> understanding correctly, if the macMode is HMAC-SHA1 then the length of
> "iv" in bits would match the HMAC output length (160 in this case).

Why would you need an IV length parameter? The IV parameter is part of the 
test vector. Thus you have the full IV to be used.
> 
> 3) In Table 6, it would be great to also have an explicit length similar to
> point 2 above, or explanation how to calculate the length. Looking through
> some server JSON, it does not appear to be based on the macMode

Check for keyOutLength in Table 5.
> 
> 4) In Table 9, it may be beneficial to give some more details on the
> expected fixedData. For instance, does it have a min/max length? Maybe
> point the reader to 800-108 document? I have read through 800-108 document
> and don't have a clear idea on what is expected from fixedData. An
> explanation, if only in this issue, would help me personally :)

This is an arbitrary string. Ok, maybe it is beneficial to give some ACVP 
server limits. But other than this technical detail, there is no mathematical 
limit -- see the CAVS test specification on 800-108 KDFs.
> 
> Particularly for 2 and 3, knowing the expected length will help libraries
> that want to perform string length checks.
> 
> Hope that all made sense. If I'm misunderstanding anything please let me
> know.
> 
> Thanks!
> Philip



Ciao
Stephan

**Comment by fliphil** [comment]
Hi Stephan,

For the IV, it would be at least useful for the reader to know what the maximum length of IV to expect. This is helpful for languages like C, where I'm using strnlen or something similar to try and validate that the server has sent the correct IV, or that the JSON wasn't somehow altered to make the string super long.

The keyIn length does not appear to correspond to the keyOutLength. I'm looking at some server JSON that has 384 (bits) for the keyOutLength, but the length of the hexstring is 32 (128 bits).

Philip

**Comment by smuellerDD** [comment]
Am Freitag, 7. September 2018, 18:48:25 CEST schrieb Philip Perricone:

Hi Philip,

> Hi Stephan,
> 
> For the IV, it would be at least useful for the reader to know what the
> maximum length of IV to expect. This is helpful for languages like C, where
> I'm using strnlen or something similar to try and validate that the server
> has sent the correct IV, or that the JSON wasn't somehow altered to make
> the string super long.

I have the entire ACVP client side protocol implemented in plain C which works 
well for me. Irrespective of the length parameter, I guess you would and 
should always enforce an upper boundary on your side. What happens otherwise 
if the server provides you with a long length value? Or there could be 
inconsistencies between the length value and the actual string.

My approach is to:

1. Limit the overall vector size to something reasonable and store it in a 
file.

2. mmap the file and parse it with the JSON parser to find the pointer to your 
value.

3. Use strlen and friends to get the actual value of the string and compare it 
with the supported string length of the IUT to limit it to an appropriate 
size.
> 
> The keyIn length does not appear to correspond to the keyOutLength. I'm
> looking at some server JSON that has 384 (bits) for the keyOutLength, but
> the length of the hexstring is 32 (128 bits).

Why should there be a correspondence? The keyIn is the keying material (Ko in 
SP800-108 speak). This key corresponds with the selected cipher. The 
keyOoutLenth value defines the number of bits your KDF shall generate. Barring 
restrictions from the implementation, this value can have an arbitrary size.

If your value is not as expected, you should register with a different size 
with the supported_length keyword in the register JSON structure.

Ciao
Stephan

**Comment by fliphil** [comment]
Hello Stephan,

I agree that setting an upper threshold is necessary and good coding practices. However, I hold the view that it is better to have the spec define the thresholds, if they do indeed exist. For instance, if the IV will always have the bit length of the macMode then why not include that detail in the spec for more clarity?
I want to emphasize that there is a difference between arbitrarily setting an upper bound, which is like making a guess in the dark, opposed to making an informed decision on the threshold based upon what is defined in the spec.

In regards to you response about keyIn, let me make a clarification. From my original post in this thread, for point 3 I was referencing the keyIn entry. Please excuse my accidental omission of the field name. Your immediate comment was: "Check for keyOutLength in Table 5.". Thus I thought you were suggesting that the keyIn and keyOutLength were related.
Are you saying that the keyIn bit length will be set to a value somewhere between the supportedLengths provided by the client?

Thanks!
Philip

**Comment by smuellerDD** [comment]
Am Montag, 10. September 2018, 16:28:33 CEST schrieb Philip Perricone:

Hi Philip,

> Hello Stephan,
> 
> I agree that setting an upper threshold is necessary and good coding
> practices. However, I hold the view that it is better to have the spec
> define the thresholds, if they do indeed exist. For instance, if the IV
> will always have the bit length of the macMode then why not include that
> detail in the spec for more clarity? I want to emphasize that there is a
> difference between arbitrarily setting an upper bound, which is like making
> a guess in the dark, opposed to making an informed decision on the
> threshold based upon what is defined in the spec.

The IV value you get via the JSON data should be taken as face value. For 
sanity only you should define an arbitrary upper limit.

As far as I have seen, the IV is equal to the digest size of the used hash.

I think, you are right in having the threshold added to the spec, if there is 
any defined by the ACVP server. But I am not sure there should be a JSON field 
in the JSON test vector containing any IV length value.
> 
> In regards to you response about keyIn, let me make a clarification. From my
> original post in this thread, for point 3 I was referencing the keyIn
> entry. Please excuse my accidental omission of the field name. Your
> immediate comment was: "Check for keyOutLength in Table 5.". Thus I thought
> you were suggesting that the keyIn and keyOutLength were related. Are you
> saying that the keyIn bit length will be set to a value somewhere between
> the supportedLengths provided by the client?

Yes, keyIn is the value defined by supported_lengths register operation -- if 
this field is defined as a range, the ACVP server selects one or more lengths 
from that range. If it is set to one or more integers, the ACVP server selects 
one or more from that set of integers.

> 
> Thanks!
> Philip



Ciao
Stephan

**Comment by fliphil** [comment]
Totally agree on the IV threshold (if it exists) being added to only the spec and not the actual JSON.
Thanks for explaining how the keyIn and supportedLengths are related, that helps very much!

Cheers,
Philip

**Comment by atvassilev** [comment]
Looks to me you both identified a spec issue. Would @fliphil and/or @smuellerDD start a PR on this, like what you did previously? We could very much use your help here.

**Comment by fliphil** [comment]
What is "deferred" used for? I checked the SP 800-108 document and don't see any reference to it. Please point me in the right direction, so that I can write an accurate snippet in the Description column.

Thanks!
Philip

**Comment by atvassilev** [comment]
Hmm, this is a good question. Especially since “deferred” is not even a defined property in this spec. It looks like it was introduced back in April, https://github.com/usnistgov/ACVP/commit/038e068e760f1162527994dc228e225805e93675#diff-0ebf395305d1e74f344e831600f5ab98.

**Comment by atvassilev** [comment]
Thanks @smuellerDD. This explanation needs to make its way into the spec though.

**Comment by fliphil** [comment]
To be clear, by input data you mean the "keyIn" and "iv" correct? In that case, the client also needs to attach those fields to each test case response.

Thanks,
Philip

**Comment by smuellerDD** [comment]
Am Montag, 17. September 2018, 16:02:02 CEST schrieb Philip Perricone:

Hi Philip,

> To be clear, by input data you mean the "keyIn" and "iv" correct?

Yes.

> In that
> case, the client also needs to attach those fields to each test case
> response.

They do not need to be part of the response. Here you have an example output.

Counter:

```
  {
    "vsId":20877,
    "testResults":[
      {
        "tcId":1,
        "fixedData":"0dda0dc29b2639bb",
        "keyOut":"207d0c784edb6de092e53ba440a99204"
      },
      {
        "tcId":2,
        "fixedData":"d88b9e6527c85e73",
        "keyOut":"63e2d8f07ba2cf302bf0c5e69d834d0a"
      },
```

Feedback mode
```  {
    "vsId":20878,
    "testResults":[
      {
        "tcId":1,
        "fixedData":"1c409bea406f8671",
        "keyOut":"4ec3617961aea2c7b6cb6fdced13596172076106bfc6a3bc8b28b27ad651c4bd2c6fb214ef8f3380c514386dcfa9f65cc21ce8befafbc066b83f4923ae22187f7c727dd1c260cb7c4eeeb9d06dde25d2225695d995f3265df771fd1d30a2b68f69a0bee0cf281caab58919a6721e3e45b1e2d04542a84350dfbcac968c5ab51bc8fda02f5c567f3835a7b628cb618a92d776ea3941f146666b7d1cd66a86597e4438cee4b9c3dd1b42b320f59ed4891ffe24337082aef8039dc6aeae3cd3afeaf90a2bdf79fa5a5fb08654595f370b35cb5d561c48afae91e6e2c38c259971ab5129615ac30a5a2a163fb877863be6b2d253c3ea2a2ad544d83cdd0b27972ec27adf88bb1867d7f8eed01953b5db57570d7ffcedd4d3e104b7019d6dffc9f5462378ab12a603979e55407eadc2e92647be184ab47499f8bea1115703836a785b0e8d47a195892177dc3a809eafe68540bda963ea639795576d3c99ee50f850c76d7ba78742a2052aae02373225915ab8eb678c407b37c2d20f772e12516aa9c3de2e8c1f5eef0d1f806c8c0a5087d7b52ee0466ac3190f14d1fe3dc48a56f555213415d71eeee44ad57a40a79343caa5a32947f045a611eb44d8bac2efc7e7f8713fbf686743529614a35836b82ada0c7a6c7b510b0718b473c94e6a0dc5d9a04d06e38119402790b10f25f444681754c360c4bac64ab1d69044cc6dde79adf3"
      },
      {
        "tcId":11,
        "fixedData":"832960d10fe3e123",
        "keyOut":"2f3f85c455f68d5aac"
      },

```

Double pipeline mode:

```
    "testResults":[
      {
        "tcId":1,
        "fixedData":"b9a649814a916479",
        "keyOut":"e9fa8cb01ddc78242b6cd58346e8c45d1894972ba256e650be0d0d127c4367a6f9b5937b09c8e3ce7406a99170b28de32dc5da14a924c8c47f5a1acdd622ad19aebd389c5cee145fbdc42d4711d6869c200624d0ce35ced520f132683aacd2d802c205a76f2e3843492d5ca4c94e086ab7e73e6e9463cc61c25a584caeb70b6a6bc027875531f88e4204eb7a3e981d711da494497110a01bca7e94415f98d6cfce5f578117801cc303106e594c23ddc9209f21291e04c91405608ceab84554abef182abe093ae124dc735241c52ffde7da2122de04e11de04b9f380e6234d154ad6cecd7e5be63ca523fa08344271858c4296a8d9f71badc35db3210b71cd0aae0a6654a54b769f7fd5ade3be5e97767caead5ced68fb871239e4295ff5401e4de0c514d6ff057e5f40fa0469988ab4ba495d0f4d9a6d6896bcb5b274cc89cd330896126d49ced144ddd627c89b836c11d7c173fa537519290675adef1154e93e3c7c5c443f1dbf327b5b60b09f9691b9d17d83a95c1fde5d1d60dece036ed4b5d8d2709cdfcde5fd0fa02a834c29002e9dd3456b3e8f1a959142192e0698649c33527fb57a569776db4ea7159abe297"
      },
```
> 
> Thanks,
> Philip



Ciao
Stephan

**Comment by elliemdaw** [comment]
Correct me if I am wrong, but it sounds like the "deferred" attribute has the same behavior as "infoGeneratedByServer" in the RSA test vectors... maybe we can name these consistently? @atvassilev what are your thoughts on this?

Thanks!!
Ellie

**Comment by atvassilev** [comment]
@elliemdaw, this is a good catch, thanks for bringing it up. There are indeed several similarities between the two flags. From the RSA spec when "infoGeneratedByServer" set to false, "... the client is responsible for providing the details by running an instance of the appropriate Key Generation method for each test." This is similar to the expectation for the client when "deferred" is set to true in this spec.

I fully support using same terminology to indicate similar behavior. In this case, it seems to me that the terminology used in the RSA spec is more intuitive/easier to understand. The term used in the KDF spec seems rather cryptic to me. That said, I would be for improving both of them if there are better proposals for them. Let me know what you all think.

**Comment by elliemdaw** [comment]
Agreed - I think the attribute name in the RSA spec is much clearer!

**Comment by celic** [comment]
`deferred` was the word chosen originally and is reflected as a general TestCase property (always set by the server) in ALL algorithms. `infoGeneratedByServer` is a registration property that is set by the client. There is a distinction between the two here. 

The server "chooses" whether or not a TestCase should be `deferred`, but the client chooses in some cases whether or not the server should generate content (`infoGeneratedByServer`). 

To touch on the original issue, `deferred` should come from the base protocol specification. It is not specific to KDF-108. Again, it is a property that is technically defined in ALL algorithms.

**Comment by awolf-bc** [comment]
Just found this discussion while I was looking for a reason why ```deferred``` was missing from the test vectors I received. It seems to me that the KDF108 spec in section 3.2 states that this field is 'mandatory' (it  can have the value ```true``` or ```false```).

The current DEMO server implementation of the HMAC-KDF for this spec does **not** send it.
Should the 'Test Case' table in that section read 'optional'?
