### ISSUE TITLE
Spec section 4 seems overly specific/restrictive.

### ISSUE THREAD

**Issue by gkruitbosch** [usnistgov/ACVP#441]
What ACV architectures will be acceptable?  
The identification of the ACV Client as being inside the DUT neglects the reality that many CMVP modules are incapable of this design.  Furthermore, NIST has indicated that communication with the official ACV Server will require some level of NVLAP accreditation which vendors may not wish to perform.  Tangentially related; the labeling of "Crypto Module" as being a subset of the DUT along with the JSON tag names containing "module" leads me to believe that "module" in this context is an "Algorithm Implementation" as currently described by the CAVP (see CAVFAQ GEN.3).  Currently the spec clearly indicates that the ACV Client is always part of the DUT and even if a proxy is used it is on the Vendor/Customer Premise. All of this leads to confusion when reading this section.   
Will labs be able to register, request and submit on behalf of a vendor?  If so this scenario (ACV Client at a lab - vectors and responses manually exchanged with vendor) should be identified; possibly in a section 4.3.  And, while it may not belong in the ACVP spec, some advanced information regarding any additional requirements relating to labs/vendors this scenario would be helpful (e.g., can the lab digitally sign submissions on behalf of the vendor using the labs key or will each vendor be required to obtain a certificate for signing submissions?)

**Comment by gkruitbosch** [comment]
I agree a protocol document is not the place to document policy or enumerate every possible architecture.  Simply indicating that the figures are "possible configurations" would eliminate confusion that the specific architecture indicated is required.

**Comment by smuellerDD** [comment]
Am Samstag, 15. September 2018, 18:40:30 CEST schrieb gkruitbosch:

Hi gkruitbosch,

> I agree a protocol document is not the place to document policy or enumerate
> every possible architecture.  Simply indicating that the figures are
> "possible configurations" would eliminate confusion that the specific
> architecture indicated is required.

I do not think that any archtecture of the ACVP client site is prescribed. You 
have the ACVP server on the one side offering the documented JSON protocol and 
the module/IUT to be tested on the other side. How you connect both, is you to 
your decision.

The only basic requirement from CAVS still applies (and should probably be 
spelled out in the ACVP spec): The functionality invoking the IUT must only 
pass the test vector to the IUT without implementing any part of the cipher to 
be tested.

Ciao
Stephan

**Comment by atvassilev** [comment]
I am closing this issue based on the responses given. As @bfussell indicated, we will keep refining the text of the spec, especially in the context of the IETF effort.
