### ISSUE TITLE
SHA server json missing "len" for MCT

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#445]
Hello,

The server JSON appears to be missing the "len" field for all of the SHA versions when testType is MCT.
The spec (https://github.com/usnistgov/ACVP/blob/master/artifacts/acvp_sub_sha.txt) currently says that this field is not optional.

Thanks,
Philip

**Comment by smuellerDD** [comment]
Am Montag, 24. September 2018, 19:30:14 CEST schrieb Philip Perricone:

Hi Philip,

> Hello,
> 
> The server JSON appears to be missing the "len" field for all of the SHA
> versions when testType is MCT. The spec
> (https://github.com/usnistgov/ACVP/blob/master/artifacts/acvp_sub_sha.txt)
> currently says that this field is not optional.

Maybe it makes sense to remove that length field because its value is already 
implicit with the other provided data?
> 
> Thanks,
> Philip



Ciao
Stephan

**Comment by fliphil** [comment]
Hey @smuellerDD, I would be okay with that as long as the max bit length is given in the spec (from what I've seen that looks like 100Kb). @elliemdaw does that sound reasonable, or can you think of any cases where we need the real bit length?

**Comment by celic** [comment]
For SHA1, 2, 3 when MCT is used the message length is always a multiple of the digest size so yes, the length could be implied. The specification should however tell you what lengths to expect. 

The exact bit length is needed for SHAKE MCTs as the inputs and outputs can vary in length. We have some specification updates planned for the next week or so. Stay tuned.

**Comment by celic** [comment]
This has been fixed and len will be included in MCT groups.
