### ISSUE TITLE
0.5: Update spec to better describe URI

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#452]
According to the SPEC, we have:

section 5.1: https://acvts.nist.gov/acvp/validation/acvp/login

and

section 5.2:

POST /acvp/v1/testSessions HTTP/1.1

Using the login URI works.

Using the prefix of /acvp/v1 for testSessions does not work as I get a 404 back. Or using the login prefix, I also get a 404 back: https://demo.acvts.nist.gov:443/acvp/validation/acvp/testSessions. I also tried https://demo.acvts.nist.gov:443/acvp/v0.5/testSessions which returns 404.

May I ask for the prefix to be used?

Thanks

**Comment by Kritner** [comment]
@smuellerDD try: https://demo.acvts.nist.gov/acvp/acvp/v1/login. `https://demo.acvts.nist.gov/acvp` being the root, everything after being related to the endpoint. @hbooth I don't recall the entirety of the explanation, could you expand on that?

**Comment by smuellerDD** [comment]
Ok, that worked.

I leave the issue open as this would need to be reflected in the SPEC

**Comment by hbooth** [comment]
Agreed that the spec needs some updating. I will use this issue to remind me to work on that.

server name for demo: acvts.nist.gov

context is: acvp

and resource prefix:
  acvp/v1

so login is:
https://demo.acvts.nist.gov/acvp/acvp/v1/login

If that is something that should change let me know and I can update.

**Comment by smuellerDD** [comment]
Am Dienstag, 16. Oktober 2018, 14:38:18 CEST schrieb Harold Booth:

Hi Harold,

> Agreed that the spec needs some updating. I will use this issue to remind me
> to work on that.
> 
> server name for demo: acvts.nist.gov

you mean demo.actvs.nist.gov?
> 
> context is: acvp
> 
> and resource prefix:
>   acvp/v1
> 
> so login is:
> https://demo.acvts.nist.gov/acvp/acvp/v1/login
> 
> If that is something that should change let me know and I can update.

This is a minor issue though, but I am not sure it makes sense to have acvp 
twice - do you fathom any other "context" in conjunction with the resource 
prefix of acvp/v1?


Ciao
Stephan

**Comment by hbooth** [comment]
I will investigate changing this, but it won't happen until 0.4 is no longer available.

**Comment by smuellerDD** [comment]
Am Dienstag, 16. Oktober 2018, 15:00:07 CEST schrieb Harold Booth:

Hi Harold,

> I will investigate changing this, but it won't happen until 0.4 is no longer
> available.

Sure, no worries - this is a small nit. Implementors should have a central 
place in their code where that is set. Hence, a change should be effordless. 
:-)

Ciao
Stephan

**Comment by elliemdaw** [comment]
@smuellerDD did you get this working with the other URI endpoints? Mine works with login, but nothing else (404s). Trying to track this down on my end - especially if yours works for everything now? Thanks!

**Comment by smuellerDD** [comment]
Hi Ellie,

Yes, I completed a full test run including register, test vector download, test response upload and void/test session verdict download.

Ciao
Stephan

Cui bono?

**Comment by elliemdaw** [comment]
With all of the URIs using /acvp/acvp/v1?

**Comment by elliemdaw** [comment]
Ahh, so I can login, and use testSessions, etc. but not OEs, vendors, modules, dependencies.

**Comment by smuellerDD** [comment]
Hi Ellie,

Precisely. Only the test vector related endpoints are available so far.

**Comment by smuellerDD** [comment]
@hbooth: I started a new register / testvector download operation this morning European time around 8.30am for one AES-CBC vector and it is still running (12pm European time).

**Comment by hbooth** [comment]
@smuellerDD do you have the vsId?

**Comment by smuellerDD** [comment]
Am Mittwoch, 17. Oktober 2018, 14:32:40 CEST schrieb Harold Booth:

Hi Harold,

> @smuellerDD do you have the vsId?

testID 63 / vsID 245

It finished 30 minutes ago - the entire duration is 005:16:55h

Ciao
Stephan

**Comment by hbooth** [comment]
I just found out there was a power outage last night where the servers were brought down until about 8am (ET) this morning which would explain the length of time you saw.

**Comment by hbooth** [comment]
URI description updated with PR #610
