### ISSUE TITLE
v0.5: AES CBC encrypt error

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#453]
**vsId**
29

**Algorithm registration**
AES-CBC

**Endpoint in which the error is experienced**
N/A

I just finished the first round of ACVP v0.5 test session. Almost all AES CBC test responses I sent back are accepted except for tcID 2079 and following.

I invoked two different IUTs (OpenSSL and Linux kernel crypto API) with the same input data and they produce the same resulting data as I uploaded. Thus, I would like to ask whether you can check if the ACVP server has an issue.

affected tcIDs: 2079 - 2138

**Comment by Kritner** [comment]
Hey @smuellerDD confirmed there's an issue on our end, taking a look into it now

**Comment by smuellerDD** [comment]
Am Mittwoch, 17. Oktober 2018, 16:55:54 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD FYI have a fix in and tested locally, should make it out to demo
> with our next deployment

Thanks - let me know when it is uploaded, I will test it immediately.

Ciao
Stephan

**Comment by Kritner** [comment]
@smuellerDD a push has been completed on demo.  Please confirm the fix at your earliest convenience, thanks!

**Comment by smuellerDD** [comment]
Confirmed, working.
