### ISSUE TITLE
v0.5: capabilities or algorithms keyword

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#459]
The current MAC specification still contains the keyword "capabilities" in the spec. The ACVP server with protocol 0.5 also requires the capabilities keyword during registering.

All other ciphers use the "algorithms" keyword.

Can we expect it will change for MAC to the common keyword of "algorithms"? Note, for HMAC, "algorithms" is accepted by ACVP. For CMAC "capabilities" is required.

PS:  Also for TDES, "capabilities" is still required, but I would expect that this is corrected once TDES is brought to 0.5.

PS: I just successfully downloaded test vectors for the following ciphers using 0.5: AES, SHA, HMAC, RSA, DRBG, DSA, ECDSA. KAS-ECC, KAS-FFC.

**Comment by celic** [comment]
It may have been a while since you ran against v0.4, but how was the wait for vector sets on v0.5? We have more improvements coming.

**Comment by celic** [comment]
As for "algorithms" vs "capabilities", I think "capabilities" is the more consistently used word (as well to not overload "algorithms" with the identifier for the algorithm). I'll go through all of our algos and make sure they are consistent and use "capabilities"

**Comment by smuellerDD** [comment]
Re wait time: I saw no real noticeable difference, but that is just a feeling. As this was my first 0.5 full download, I sometimes had to interrupt it and restart it several times. So, that feeling is not really trustworthy :-)

I also just uploaded my first full 0.5 responses with manual interventions.

In the next couple of days I will watch the time more closely for up and download and report.

**Comment by celic** [comment]
The fix has been pushed out. Please test when you have the chance.

**Comment by smuellerDD** [comment]
Am Montag, 5. November 2018, 15:42:36 CET schrieb Chris Celi:

Hi Chris,

> The fix has been pushed out. Please test when you have the chance.

What would be the resolution? Testing with TDES:

- using "capabilities" returns an empty response without any vectorSetUrls

- using "algorithms: returns an error that I should use capabilities

Testing with AES ECB, "algorithms" works.

Ciao
Stephan

**Comment by celic** [comment]
Would you mind posting either registration (in full)? I have an idea we may be talking about different things here.

**Comment by smuellerDD** [comment]
Example for TDES:

```
[
  {
    "acvVersion":"0.5"
  },
  {
    "isSample":false,
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "algorithms":[
      {
        "algorithm":"TDES-CBC",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          168
        ],
        "ptLen":[
          64,
          128,
          256,
          512
        ],
        "ivLen":[
          64
        ],
        "keyingOption":[
          1
        ]
      },
      {
        "algorithm":"TDES-CBC",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          168
        ],
        "ptLen":[
          64,
          128,
          256,
          512
        ],
        "ivLen":[
          64
        ],
        "keyingOption":[
          1
        ]
      },
      {
        "algorithm":"TDES-CBC",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          168
        ],
        "ptLen":[
          64,
          128,
          256,
          512
        ],
        "ivLen":[
          64
        ],
        "keyingOption":[
          1
        ]
      },
      {
        "algorithm":"TDES-OFB",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          168
        ],
        "ptLen":[
          64,
          128,
          256,
          512
        ],
        "ivLen":[
          64
        ],
        "keyingOption":[
          1
        ]
      },
      {
        "algorithm":"TDES-CBC",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          168
        ],
        "ptLen":[
          64,
          128,
          256,
          512
        ],
        "ivLen":[
          64
        ],
        "keyingOption":[
          1
        ]
      },
      {
        "algorithm":"TDES-ECB",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          168
        ],
        "ptLen":[
          64,
          128,
          256,
          512
        ],
        "keyingOption":[
          1
        ]
      },
      {
        "algorithm":"CMAC-TDES",
        "prereqVals":[
          {
            "algorithm":"TDES",
            "valValue":"same"
          }
        ],
        "direction":[
          "gen",
          "ver"
        ],
        "keyLen":[
          168
        ],
        "keyingOption":[
          1
        ],
        "msgLen":[
          64,
          128,
          72,
          136,
          524288
        ],
        "macLen":[
          64
        ]
      }
    ]
  }
]
```

vs

```
[
  {
    "acvVersion":"0.5"
  },
  {
    "isSample":false,
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "capabilities":[
      {
        "algorithm":"TDES-CBC",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          168
        ],
        "ptLen":[
          64,
          128,
          256,
          512
        ],
        "ivLen":[
          64
        ],
        "keyingOption":[
          1
        ]
      },
      {
        "algorithm":"TDES-CBC",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          168
        ],
        "ptLen":[
          64,
          128,
          256,
          512
        ],
        "ivLen":[
          64
        ],
        "keyingOption":[
          1
        ]
      },
      {
        "algorithm":"TDES-CBC",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          168
        ],
        "ptLen":[
          64,
          128,
          256,
          512
        ],
        "ivLen":[
          64
        ],
        "keyingOption":[
          1
        ]
      },
      {
        "algorithm":"TDES-OFB",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          168
        ],
        "ptLen":[
          64,
          128,
          256,
          512
        ],
        "ivLen":[
          64
        ],
        "keyingOption":[
          1
        ]
      },
      {
        "algorithm":"TDES-CBC",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          168
        ],
        "ptLen":[
          64,
          128,
          256,
          512
        ],
        "ivLen":[
          64
        ],
        "keyingOption":[
          1
        ]
      },
      {
        "algorithm":"TDES-ECB",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          168
        ],
        "ptLen":[
          64,
          128,
          256,
          512
        ],
        "keyingOption":[
          1
        ]
      },
      {
        "algorithm":"CMAC-TDES",
        "prereqVals":[
          {
            "algorithm":"TDES",
            "valValue":"same"
          }
        ],
        "direction":[
          "gen",
          "ver"
        ],
        "keyLen":[
          168
        ],
        "keyingOption":[
          1
        ],
        "msgLen":[
          64,
          128,
          72,
          136,
          524288
        ],
        "macLen":[
          64
        ]
      }
    ]
  }
]
```
Here is a working AES-ECB example
```
[
  {
    "acvVersion":"0.5"
  },
  {
    "isSample":false,
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "algorithms":[
      {
        "algorithm":"AES-ECB",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          128,
          192,
          256
        ],
        "ptLen":[
          128,
          256,
          512,
          1024
        ]
      }
    ]
  }
]
```

**Comment by celic** [comment]
This field should always be "algorithms". It should be specified as such in the protocol document (and if it isn't that is a problem).

**Comment by smuellerDD** [comment]
Am Montag, 5. November 2018, 16:51:58 CET schrieb Chris Celi:

Hi Chris,

> This field should always be "algorithms". It should be specified as such in
> the protocol document (and if it isn't that is a problem).

And that is the key issue: TDES the request given before with the following 
answer:

```
{
  "acvVersion" : "0.5",
  "error" : "Incorrectly formatted JSON (1:1123): expected field name was not 
provided: capabilities"
}
```

CMAC has a similar issue.

Ciao
Stephan

**Comment by celic** [comment]
If "capabilities" is used, it is nested inside of the "algorithms" object. So for CMAC and AES-ECB it would look like this...
```
    "algorithms":[
      {
        "algorithm":"AES-ECB",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          128,
          192,
          256
        ],
        "ptLen":[
          128,
          256,
          512,
          1024
        ]
      },
      {
        "algorithm":"CMAC-TDES",
        "prereqVals":[
          {
            "algorithm":"TDES",
            "valValue":"same"
          }
        ],
        "capabilities":[
            {
                "direction":[
                  "gen",
                  "ver"
                ],
                "keyLen":[
                  168
                ],
                "keyingOption":[
                  1
                ],
                "msgLen":[
                  64,
                  128,
                  72,
                  136,
                  524288
                ],
                "macLen":[
                  64
                ]
              }
            ]
        }
    ]

**Comment by smuellerDD** [comment]
Am Montag, 5. November 2018, 17:13:47 CET schrieb Chris Celi:

Hi Chris,

> If "capabilities" is used, it is nested inside of the "algorithms" object.
> So for CMAC and AES-ECB it would look like this...

Ok. Strange that CMAC adds this capabilities field as a subordinate hierarchy. 
But ok.

But what about TDES symmetric ciphers?

Ciao
Stephan

**Comment by celic** [comment]
They do not have this capabilities field as a subordinate hierarchy. CMAC does this to allow interchangeability in the cipher used without needing a separate registration, similar to CAVS in the past.

**Comment by smuellerDD** [comment]
Am Montag, 5. November 2018, 17:20:15 CET schrieb Chris Celi:

Hi Chris,

> They do not have this capabilities field as a subordinate hierarchy. CMAC
> does this to allow interchangeability in the cipher used without needing a
> separate registration, similar to CAVS in the past.

Thanks for the clarification. But when sending the aforementioned TDES-ECB/
TDES-CBC / etc. request with "algorithms", the ACVP server replies it wants to 
see some "capabilities" field. And I do not understand where that keyword is 
requested.

Ciao
Stephan

**Comment by celic** [comment]
Then that is an error. There should not be a "capabilities" field when registering TDES-ECB/CBC. I will look into this.

**Comment by celic** [comment]
Does this occur when you register only for TDES-ECB? Using "algorithms". I'll see if I can replicate this locally.

**Comment by smuellerDD** [comment]
Am Montag, 5. November 2018, 18:24:39 CET schrieb Chris Celi:

Hi Chris,

> Does this occur when you register only for TDES-ECB? Using "algorithms".
> I'll see if I can replicate this locally.

Sorry, it is not related to symmetric TDES. This works. I had CMAC-TDES 
included into the request. Thus, please disregard the TDES issue.

I.e. this issue report is solely about the CMAC cipher definition.

Ciao
Stephan

**Comment by celic** [comment]
In CMAC, `keyLen` is no longer an array. Different key lengths should be separate capabilities in that array.

**Comment by smuellerDD** [comment]
Am Montag, 5. November 2018, 18:30:33 CET schrieb Chris Celi:

Hi Chris,

> In CMAC, `keyLen` is no longer an array. Different key lengths should be
> separate capabilities in that array.

Uh, why this inconsistency with symmetric ciphers?

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Montag, 5. November 2018, 18:30:33 CET schrieb Chris Celi:

Hi Chris,

> In CMAC, `keyLen` is no longer an array. Different key lengths should be
> separate capabilities in that array.

Also the keyingOption is now an integer - again, why would that be 
inconsistent to the symmetric ciphers?

Ciao
Stephan

**Comment by celic** [comment]
`direction` is also no longer an array. This is to match the concept of a "validation" from CMAC in CAVS. The data CAVS collected was in this modular style. In order to unify old CAVS data with new ACVP data, some compromises were needed. These tend to shift things to be as modular as possible.

**Comment by smuellerDD** [comment]
Am Montag, 5. November 2018, 18:45:23 CET schrieb Chris Celi:

Hi Chris,

> `direction` is also no longer an array. This is to match the concept of a
> "validation" from CMAC in CAVS. The data CAVS collected was in this modular
> style. In order to unify old CAVS data with new ACVP data, some compromises
> were needed. These tend to shift things to be as modular as possible.

I would praise that. But now you mandate to spell out all permutations like 
with the keyLen.

Previously, the spec defined:

direction: [gen, ver]
keyLen: [128, 192, 256]

This implied that all permutations of these options are applied (i.e. 6 
permutations).

Now, you require the requestor to spell out all 6 permutations in the request 
file.

With the old style I could also have the fine-grained specification if I would 
liked to do so:

{
direction: [gen]
keyLen: [128]
},

{
direction: [ver]
keyLen: [192]
}

So, although I praise the motive for the change, I am not that the change 
actually meets the motive.


Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Montag, 5. November 2018, 18:51:46 CET schrieb Chris Celi:

Hi Chris,

> The way I see it, CMAC registrations could be made as a blend of the two
> styles. The "direction", "keyLen", "keyingOption" properties would be an
> array that contains 1 or more values. We could keep the "capabilities"
> object to allow for other options, such as if a different "keyLen" supports
> different "macLen"s. This is not the current implementation though.
> 
> You seem to share my thoughts. I'll see if this can get done this week.

Precisely, I fully concur with you. I.e. allow one or more array entries. If 
you have multiple array entries for one capability, all permutations of all 
these array entries are requested.

Ciao
Stephan

**Comment by celic** [comment]
We've made this change. It should be pushed out in our next release. We will probably try to accumulate some other bugs (as they appear) in this fix so it may be a couple of days.

**Comment by smuellerDD** [comment]
Confirmed, working.
