### ISSUE TITLE
v0.5: DRBG PR flag

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#460]
I have a CTR DRBG test vector obtained from ACVP v0.5. I think it is a prediction resistance vector, because there are two "generate" other input entries. Yet, the predResistance is set to false:

```
    "tgId" : 7,
    "testType" : "AFT",
    "derFunc" : true,
    "predResistance" : false,
    "reSeed" : true,
    "entropyInputLen" : 128,
    "nonceLen" : 64,
    "persoStringLen" : 0,
    "additionalInputLen" : 0,
    "returnedBitsLen" : 512,
    "mode" : "AES-128",
    "tests" : [ {
      "tcId" : 91,
      "entropyInput" : "53ACC11F447CA1852678760450B12859",
      "nonce" : "0AE276873B88F62E",
      "persoString" : "",
      "otherInput" : [ {
        "intendedUse" : "generate",
        "additionalInput" : "",
        "entropyInput" : "AE1A6A955190C7D5A08E5AA8240C0F6F"
      }, {
        "intendedUse" : "generate",
        "additionalInput" : "",
        "entropyInput" : "EC485AA8B529B04130FB65A0D016D95D"
      } ]
```

vsID 10354

**Comment by Kritner** [comment]
@smuellerDD there are two `generate` function calls for all permutations of DRBG testing - it's only the reseed call that is included or excluded depending on options.

**Comment by smuellerDD** [comment]
Agreed, but isn't entropy for the generate call only supplied if you have PR enabled? At least that is how it used to be defined in the DRBGVS.pdf CAVS spec where the entropy/generate used to be called EntropyInputPR.

What I am saying is that I would see that if you have entropyInput/generate data, the test vector must be a predResistance true vector.

**Comment by Kritner** [comment]
Ah gotcha - I'll take a look at this and update the ticket once a fix has been deployed

**Comment by Kritner** [comment]
Pushed a fix out with the demo deploy

**Comment by smuellerDD** [comment]
Confirmed, working
