### ISSUE TITLE
v0.5 DRBG otherInput field order

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#461]
The current DRBG otherInput field for PR looks like:

```
      "otherInput" : [ {
        "intendedUse" : "generate",
        "additionalInput" : "",
        "entropyInput" : "AE1A6A955190C7D5A08E5AA8240C0F6F"
      }, {
        "intendedUse" : "generate",
        "additionalInput" : "",
        "entropyInput" : "EC485AA8B529B04130FB65A0D016D95D"
      } ]
```

The idea is that the first entry is used for the first generate operation and the 2nd entry for the 2nd generate operation.

This, however, does not comply with the JSON definitions. JSON does not prescribe an order of entries. So, the aforementioned JSON array must not be assumed to have the assumed order or to be processed with that order. That means the order required for the DRBG testing cannot be guaranteed with JSON.

Hence, the intendedUse keywords need to change, such as "generate1" and "generate2".

**Comment by smuellerDD** [comment]
Or instead of using the indendedUse keyword, do rather:

```
"generate1": {
       "additionalInput" : "",
        "entropyInput" : "AE1A6A955190C7D5A08E5AA8240C0F6F"
},
"generate2" : {
         "additionalInput" : "",
        "entropyInput" : "EC485AA8B529B04130FB65A0D016D95D"
}
```

I know we had that discussion before, but we may have missed that a JSON array does not have any order.

**Comment by hbooth** [comment]
from json.org:

`An array is an ordered collection of values.`

contrasted with object:

`An object is an unordered set of name/value pairs.`

It would seem to me the whole point of an array is to have an ordered data structure.

**Comment by smuellerDD** [comment]
Ok, I must have read something wrong then.

Sorry for the noise.
