### ISSUE TITLE
v0.5: RSA sigGen: keywords 'mode' and 'sigType' mixup?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#463]
The RSA sigGen vector shows:
```
  "testGroups" : [ {
    "tgId" : 1,
    "mode" : "pkcs1v1.5",
    "modulo" : 2048,
    "hashAlg" : "SHA-1",
    "saltLen" : 0,
    "testType" : "GDT",
    "tests" : [ {
      "tcId" : 1,
```

The mode key word does now have the information what used to be in sigType.  The spec still says that the keyword sigType is to be used.

**Comment by celic** [comment]
Got it. Thanks.

**Comment by celic** [comment]
This is also the case for RSA-SigVer. It has also been fixed and will be in our next deploy.

**Comment by celic** [comment]
The fix has been pushed out. Please test when you have the chance.

**Comment by smuellerDD** [comment]
Confirmed. Working,
