### ISSUE TITLE
v0.5: RSA key gen data missing

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#464]
The RSA key gen vectors seem to miss some input data"

```
[ {
  "acvVersion" : "0.5"
}, {
  "algorithm" : "RSA",
  "mode" : "keyGen",
  "isSample" : false,
  "testGroups" : [ {
    "tgId" : 1,
    "infoGeneratedByServer" : false,
    "modulo" : 2048,
    "tests" : [ {
      "tcId" : 1,
      "e" : "DF28AB",
      "p" : "E021757C777288DACFE67CB2E59DC02C70A8CEBF56262336592C18DCF466E0A4ED405318AC406BD79ECA29183901A557DB556DD06F7C6BEA175DCB8460B6B1BC05832B01EEDF86463238B7CB6643DEEF66BC4F57BF8FF7EC7C4B8A8AF14F478980AABEDD42AFA530CA47849F0151B7736AA4CD2FF37F322A9034DE791EBE3F51",
      "q" : "ED1571A9E0CD4A42541284A9F98B54A6AF67D399D55EF888B9FE9EF76A61E892C0BFBB87544E7B24A60535A65DE422830252B45D2033819CA32B1A9C4413FA721F4A24EBB5510DDC9FD6F4C09DFC29CB9594650620FF551A62D53EDC2F8EBF10BEB86F483D463774E5801F3BB01C4D452ACB86ECFADE1C7DF601CAB68B065275"
    }, {
```

E.g. randPQ seems missing.

**Comment by celic** [comment]
You are correct. Nothing here tells you which prime generator was used! This will be fixed in our next release as well.

**Comment by celic** [comment]
Would it happen to be at the bottom of the testGroup definition? Nothing I see would indicate that it isn't included, just that the order isn't intuitive.

**Comment by celic** [comment]
I'll go ahead and move it up to the top, but considering this is JSON, it technically shouldn't matter. This will be included in our next release.

**Comment by smuellerDD** [comment]
The order is immaterial. In fact, my parser found randPQ (do I need my glasses being corrected?).

But pRand/qRand was changed to p/q. That was the culprit. I fixed it in my parser.

Sorry for the noise.
