### ISSUE TITLE
v0.5: AES-CFB1: errors with full AES block input data

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#467]
I am trying to debug AES-CFB1 errors I receive from the ACVP server.

The ACVP server flags all my responses for the one bit input data as correct.

However, all responses for the multi-byte data is marked as wrong. Unfortunately I only have one IUT with CFB-1 and cannot cross check. Also the old CAVS tool does not provide good input data.

Thus, may I ask for help to see where the error is?

vsID: 10356

All failing tcIDs are 2079 - 2138

Thanks a lot

**Comment by Kritner** [comment]
@smuellerDD I'm looking into and #468 now.  Was curious if you've tested tdes-cfb1 on v0.5?  We're using the same block mode implementation just with a swapped engine (aes vs tdes) for our cfb implementation.  If you're having a similar issue (or not) on tdes-cfb1 that could help me determine where I need to dig in.

**Comment by smuellerDD** [comment]
Am Freitag, 2. November 2018, 15:04:46 CET schrieb Russ Hammett:

Hi Russ,

> @smuellerDD I'm looking into and #468 now.  Was curious if you've tested
> tdes-cfb1 on v0.5?

Not yet as I manually have to tweak the capabilities/algorithms keyword. But I 
will do that shortly.

> We're using the same block mode implementation just
> with a swapped engine (aes vs tdes) for our cfb implementation.  If you're
> having a similar issue (or not) on tdes-cfb1 that could help me determine
> where I need to dig in.

Give me some minutes.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Freitag, 2. November 2018, 15:04:46 CET schrieb Russ Hammett:

Hi Russ,

> @smuellerDD I'm looking into and #468 now.  Was curious if you've tested
> tdes-cfb1 on v0.5?  We're using the same block mode implementation just
> with a swapped engine (aes vs tdes) for our cfb implementation.  If you're
> having a similar issue (or not) on tdes-cfb1 that could help me determine
> where I need to dig in.

#470 blocks me from getting TDES at the moment.

Ciao
Stephan

**Comment by Kritner** [comment]
I do see something off in that we're generating entirely too large of PTs/CTs to test multi block functionality with, which I'm putting in a correction for.  Additionally the `dataLen` property is not being properly sent, which I'm also putting in a correction for.

Though, I'm not seeing anything that would speak to the actual problem at a glance.

Interestingly enough, our answers are matching up to a point of the resulting CT.  Example:

```json
{
          "tcId": 2089,
          "dataLen": 0,
          "iv": "036F2CDFD380CFBB84F39782EB7A849D",
          "pt": "DAB986DE204481D8D04D4E7823DEF85F",
          "key": "B36C419C9A28B15DD5AD731B2368208AB06F5BF7B2083184",
          "ct":    "BB60FA967D66BF73AA4C050FE4BFBD4D",
          "iutCt": "bb6086de204481d8d04d4e7823def85f"
        },
        {
          "tcId": 2090,
          "dataLen": 0,
          "iv": "B09BCE0D38EA9279FA7068C1012BA5FF",
          "pt": "30F5DAF34C68E42CF32D83E1721454C4433D1E5D2DC36FD464B42AE558982D89",
          "key": "0522FC188A0F3C919C26C6D4131715CF73CE14A86F112442",
          "ct":    "F68B5656A7F3A4D3194805AA7A60AE43ABE5831590B8B6474995BC59CE79E6E8",
          "iutCt": "f68b56564c68e42cf32d83e1721454c4433d1e5d2dc36fd464b42ae558982d89"
        },
        {
          "tcId": 2091,
          "dataLen": 0,
          "iv": "07648CB835C68AEDECB9BB89227C8B72",
          "pt": "0E2FB9ADF643C586E498565976035EA0C38EEEDB41991CA567B1CDE802700B0245186BCBB7BACBBD661F1A6CCBA3A186",
          "key": "ABECA1676C16F73DCF8ADD804F253BEFB9C8985E0136A57A",
          "ct":    "CF9FA96C3015AB8A69B0BAA0881F54B8DF4B5438903CDC04E5DE4016191D3FFBFC641D501754163673380520AD675A1E",
          "iutCt": "cf9fa96c3015c586e498565976035ea0c38eeedb41991ca567b1cde802700b0245186bcbb7bacbbd661f1a6ccba3a186"
        },
```

I'm not sure if this is somehow related to the changes I spoke of above, but thought I'd throw it out there to show that we are partially getting the same answers.  It's interesting in the first example they're equal for the first 2 bytes, in the second they're equal for 4, and in the third they're equal for 6.

I'll keep digging.

**Comment by smuellerDD** [comment]
Am Freitag, 2. November 2018, 15:45:49 CET schrieb Russ Hammett:

Hi Russ,

> I do see something off in that we're generating entirely too large of
> PTs/CTs to test multi block functionality with, which I'm putting in a
> correction for.  Additionally the `dataLen` property is not being properly
> sent, which I'm also putting in a correction for.

I see, dataLen is the replacement for ctLen/ptLen?
> 
> Though, I'm not seeing anything that would speak to the actual problem at a
> glance.
> 
> Interestingly enough, our answers are matching up to a point of the
> resulting CT.  Example:

Thanks, let me also dig into that on my side.

> I'm not sure if this is somehow related to the changes I spoke of above, but
> thought I'd throw it out there to show that we are partially getting the
> same answers.  It's interesting in the first example they're equal for the
> first 2 bytes, in the second they're equal for 4, and in the third they're
> equal for 6.

I would have no real answer why this is the case. I will see whether something 
is amiss also on my side.
> 
> I'll keep digging.



Ciao
Stephan

**Comment by Kritner** [comment]
> I see, dataLen is the replacement for ctLen/ptLen?

Yeah - I believe it's only needed really for the CFB1 mode, since all other modes of CFB work on a byte boundary.

**Comment by Kritner** [comment]
We pushed out a change that should address the `dataLen` and incorrect `pt`/`ct` values produced, I'm not sure if it would correct the problem you were seeing, but it should at least be something closer.

**Comment by Kritner** [comment]
Hey @smuellerDD I ended up writing some tests on CAVS to run some of the problem tests from this issue. They were matching with what ACVP was producing, not what the IUT was sending back.

**Comment by smuellerDD** [comment]
Am Montag, 5. November 2018, 16:40:07 CET schrieb Russ Hammett:

Hi Russ,

> Hey @smuellerDD I ended up writing some tests on CAVS to run some of the
> problem tests from this issue. They were matching with what ACVP was
> producing, not what the IUT was sending back.

Thanks for letting me know -- once #459 is sorted out, I will focus on CFB-1

Ciao
Stephan

**Comment by smuellerDD** [comment]
CFB-1 works completely now when using dataLen
