### ISSUE TITLE
v0.5: AES CFB: ptLen / ctLen

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#469]
The symmetric cipher sipec does not contain the definition of the keywords of ptLen and ctLen any more that used to be present for CFB. The AES-CFB1/8 vectors do not contain the keyword nor do the responses need that keyword.

Though, the examples in the spec still contain ptLen/ctLen. I guess they would need to be removed?

**Comment by Kritner** [comment]
@smuellerDD I saw you commented on the PR, so I'm closing this issue.  Let me know if something comes up!
