### ISSUE TITLE
v0.5: no vectorSet URLs provided

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#470]
When registering a request, the ACVP server returns no vectorSet URLs.

request straight from the network logging:
```
[{"acvVersion":"0.5"},{"isSample":false,"operation":"register","certificateRequest":"no","debugRequest":"yes","production":"no","encryptAtRest":"yes","capabilities":[{"algorithm":"AES-OFB","direction":["encrypt","decrypt"],"keyLen":[128,192,256],"ptLen":[128,256,512,1024],"ivLen":[128]},{"algorithm":"AES-CFB1","direction":["encrypt","decrypt"],"keyLen":[128,192,256],"ptLen":[128,256,512,1024],"ivLen":[128]},{"algorithm":"AES-CFB8","direction":["encrypt","decrypt"],"keyLen":[128,192,256],"ptLen":[128,256,512,1024],"ivLen":[128]},{"algorithm":"AES-CFB128","direction":["encrypt","decrypt"],"keyLen":[128,192,256],"ptLen":[128,256,512,1024],"ivLen":[128]},{"algorithm":"AES-ECB","direction":["encrypt","decrypt"],"keyLen":[128,192,256],"ptLen":[128,256,512,1024]},{"algorithm":"AES-XTS","direction":["encrypt","decrypt"],"keyLen":[128,256],"ptLen":[128,256],"tweakFormat":["128hex"],"tweakMode":["hex"]},{"algorithm":"AES-CTR","direction":["encrypt","decrypt"],"keyLen":[128,192,256],"dataLength":[128],"ivLen":[128],"ctrSource":"external"},{"algorithm":"AES-KW","direction":["encrypt","decrypt"],"keyLen":[128,192,256],"ptLen":[128,256,512,1024],"ivLen":[64],"kwCipher":["cipher"]},{"algorithm":"AES-KWP","direction":["encrypt","decrypt"],"keyLen":[128,192,256],"ptLen":[8,72,32,96,888],"ivLen":[64],"kwCipher":["cipher"]},{"algorithm":"AES-CCM","prereqVals":[{"algorithm":"AES","valValue":"same"}],"direction":["encrypt","decrypt"],"keyLen":[128,192,256],"ptLen":[256],"ivLen":[56,64,72,80,88,96,104],"aadLen":[0,256,65536],"tagLen":[32,48,64,80,96,112,128]},{"algorithm":"CMAC-AES","prereqVals":[{"algorithm":"AES","valValue":"same"}],"direction":["gen","ver"],"keyLen":[128,192,256],"keyingOption":[1],"msgLen":[128,256,136,264,524288],"macLen":[128]}]}]
```

Response:
```
[{"acvVersion":"0.5"},{"url":"/acvp/v1/testSessions/10156","vectorSetUrls":[],"accessToken":"...
```
Note, I also tested it with a TDES request with the same result.
Up to yesterday it worked, but not any more.

**Comment by Kritner** [comment]
Acknowledged - looking into it, thanks!

**Comment by smuellerDD** [comment]
Just FYI: this one is still pending and does not allow me to test the new fixes.

**Comment by Kritner** [comment]
Hey @smuellerDD I'm not seeing anything obviously wrong - we are having successful test sessions come through.  Would it be possible for you to try a smaller subset of a registration? 

Not sure if there could be something not handled properly with that big of a registration, or a specific algorithm in your registration, or something else. Attempting a smaller registration may help point us in a direction to look for an issue.

**Comment by smuellerDD** [comment]
Am Montag, 5. November 2018, 13:40:13 CET schrieb Russ Hammett:

Hi Russ,


request:

```
[{"acvVersion":"0.5"},
{"isSample":false,"operation":"register","certificateRequest":"no","debugRequest":"yes","production":"no","encryptAtRest":"yes","capabilities":
[{"algorithm":"AES-ECB","direction":["encrypt","decrypt"],"keyLen":
[128,192,256],"ptLen":[128,256,512,1024]}]}]
```

response:

```
[{"acvVersion":"0.5"},{"url":"/acvp/v1/testSessions/49","vectorSetUrls":
[],"accessToken":"...
```


Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Montag, 5. November 2018, 13:40:13 CET schrieb Russ Hammett:

Hi Russ,

> Hey @smuellerDD I'm not seeing anything obviously wrong - we are having
> successful test sessions come through.  Would it be possible for you to try
> a smaller subset of a registration?
> 
> Not sure if there could be something not handled properly with that big of a
> registration, or a specific algorithm in your registration, or something
> else. Attempting a smaller registration may help point us in a direction to
> look for an issue.

Just found it: I used the keyword "capabilities" as discussed in the other bug 
report.

When I revert to the keyword "algorithms" it works.

Could you please help me to identify where I need "capabilities" and where 
"algorithms"? 

Also, may I ask to unify the use of these keywords? Thanks a lot.

Ciao
Stephan

**Comment by Kritner** [comment]
Yeah, we'll want to take care of this sooner rather than later. Adding reference to issue #459 for visibility.

**Comment by smuellerDD** [comment]
Note, I cannot download the vectors that require "capabilities" such as TDES. I can only download vectors that allow "algorithms".

**Comment by hbooth** [comment]
This leads me to something that I am wondering how to resolve. Currently, the server will silently ignore "extra" properties (although it does log them internally). I have one of two options, I could add warning section to the response, listing all of the ignored properties or send back an error if any unrecognized property is sent by the client. There is currently no mechanism for sending back warning in the response (it would need to be added to the protocol) and sending an error would effectively disallow extensions.
A third option could be to allow the client to specify a "strict" mode such that extra properties would trigger an error, but otherwise the behavior of the server would remain the same as it is today where it would ignore extra/unknown properties.

I am open to other thoughts or solutions if others have them.

**Comment by sam1689** [comment]
From my perspective I think it might be worth adding a warning
      for this in the error section because a warning has at least to
      desirable benefits:
    
    1. Allows the clients to add functionality that may be ahead of
      where the server is without the server failing/rejecting the other
      valid inputs - which is more flexible.
    
    2. Provides feedback to clients about properties they may think
      are valid but are not properly structured for some reason (better
      than silent ignore)...
    Regards,
    Sam
    
    
    On 11/5/18 8:44 AM, Harold Booth wrote:
    
    
      
      This leads me to something that I am wondering how to resolve.
        Currently, the server will silently ignore "extra" properties
        (although it does log them internally). I have one of two
        options, I could add warning section to the response, listing
        all of the ignored properties or send back an error if any
        unrecognized property is sent by the client. There is currently
        no mechanism for sending back warning in the response (it would
        need to be added to the protocol) and sending an error would
        effectively disallow extensions.
        A third option could be to allow the client to specify a
        "strict" mode such that extra properties would trigger an error,
        but otherwise the behavior of the server would remain the same
        as it is today where it would ignore extra/unknown properties.
      I am open to other thoughts or solutions if others have them.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/usnistgov/ACVP","title":"usnistgov/ACVP","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/usnistgov/ACVP"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hbooth in #470: This leads me to something that I am wondering how to resolve. Currently, the server will silently ignore \"extra\" properties (although it does log them internally). I have one of two options, I could add warning section to the response, listing all of the ignored properties or send back an error if any unrecognized property is sent by the client. There is currently no mechanism for sending back warning in the response (it would need to be added to the protocol) and sending an error would effectively disallow extensions.\r\nA third option could be to allow the client to specify a \"strict\" mode such that extra properties would trigger an error, but otherwise the behavior of the server would remain the same as it is today where it would ignore extra/unknown properties.\r\n\r\nI am open to other thoughts or solutions if others have them."}],"action":{"name":"View Issue","url":"https://github.com/usnistgov/ACVP/issues/470#issuecomment-435878084"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/usnistgov/ACVP/issues/470#issuecomment-435878084",
"url": "https://github.com/usnistgov/ACVP/issues/470#issuecomment-435878084",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [usnistgov/ACVP] v0.5: no vectorSet URLs provided (#470)",
"sections": [
{
"text": "",
"activityTitle": "**Harold Booth**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@hbooth",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"usnistgov/ACVP\",\n\"issueId\": 470,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"usnistgov/ACVP\",\n\"issueId\": 470\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/usnistgov/ACVP/issues/470#issuecomment-435878084"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 405728643\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by smuellerDD** [comment]
Am Montag, 5. November 2018, 15:34:32 CET schrieb Sam @ Cisco:

Hi ,

>     From my perspective I think it might be worth adding a warning
>       for this in the error section because a warning has at least to
>       desirable benefits:
> 
>     1. Allows the clients to add functionality that may be ahead of
>       where the server is without the server failing/rejecting the other
>       valid inputs - which is more flexible.
> 
>     2. Provides feedback to clients about properties they may think
>       are valid but are not properly structured for some reason (better
>       than silent ignore)...

I would concur with this proposal. Send the log messages in addition to the 
response. The client may ignore that information. But for development 
purposes, having this information is nice.

Maybe add another flag to the initial request allowing the client to flag 
whether it wants to have such auxiliary log messages. Possibly you could have 
various log levels. In my case, I have a granular log setting starting from 
Error logs to Debug log output, I could fathom that my client would not obtain 
such auxiliary server log data when the caller only wants Error log messages.

Just note, for the current "capabilities" issue however the ACVP server 
neither returns an HTTP error, nor error log messages nor vectorSetUrls. That 
probably should be improved.


Ciao
Stephan

**Comment by smuellerDD** [comment]
Closed: wrong formatting of the requests.
