### ISSUE TITLE
v0.5: TLS KDF generation failed

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#472]
The ACVP server failed to generate a KDF test vector:

```
[ {
  "acvVersion" : "0.5"
}, {
  "vsId" : 119,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 119"
} ]
```

**Comment by Kritner** [comment]
just wanted to double check - I'm seeing under vector set 119 a failed DSA.SigVer generation, I see 120 is a kdf-components tls that was successfully generated.  Is this just a typo on the issue label, or did i miss something?

**Comment by smuellerDD** [comment]
Sorry, I guess I need my glasses replaced :-)

TLS works well
