### ISSUE TITLE
Status on test vector generation duration

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#476]
The following list enumerates the test vector generation duration, i.e. the time between submitting a test vector and the time to get a vector.

Note, some Algorithm entries are empty due to the just opened bug reports. But please note that the time until the error is returned took some time as well.

**Comment by smuellerDD** [comment]
Here is a status with also the upload times.

[test_duration_with_upload.txt](https://github.com/usnistgov/ACVP/files/2552155/test_duration_with_upload.txt)

**Comment by smuellerDD** [comment]
Just FYI: I do not have the feeling that the time to download the test vectors decreased. For example, when I downloaded a plain AES-ECB without anyting else in the test session, it took me 02:44.745 min.

This time is similar when I reperformed the download.

**Comment by smuellerDD** [comment]
Asymmetric vectors like RSA siggen seem to be generated much faster.

**Comment by elliemdaw** [comment]
ECDSA has seemed quite slow though, at least for me.

**Comment by smuellerDD** [comment]
Am Donnerstag, 8. November 2018, 22:39:51 CET schrieb Ellie Marie:

Hi Ellie,

> ECDSA has seemed quite slow though, at least for me.

Right, I should have been more precise: RSA I checked :-)

Ciao
Stephan

**Comment by celic** [comment]
The "quick" vector sets such as normal block ciphers may not have much of a speed-up right now. We have plans for them in the near future. The bulk of our effort was helping our asymmetric crypto operations. Again we have further plans in the near future. Though I was also noticing some slowness in ECDSA when testing in our local environment that might be worth a look on our end. 

Thanks for the feedback all.

**Comment by smuellerDD** [comment]
Am Donnerstag, 8. November 2018, 22:54:35 CET schrieb Chris Celi:

Hi Chris,
> 
> Thanks for the feedback all.

How do you want to continue on this one? Shall I continue to report some 
status here or shall we close the issue?

Ciao
Stephan

**Comment by smuellerDD** [comment]
@hbooth: Please remember our following discussion: When I send a register request and wait for the ACVP server to generate the test vector, I can interrupt the waiting and resume the HTTP GET operation. When resuming the HTTP GET operation after interruption, I usually get the test vector much faster than when I wait. I.e. the ACVP server sends the 30-second wait notification for waiting, but when I interrupt the request, I usually get the test vector immediately (or with a much shorter waiting time).

Now, I implemented the same interruption support for the verdict retrieval. I.e. I can upload the test responses and wait for the verdict. When I interrupt the waiting for the verdict, my client can resume the HTTP GET operation without re-submitting the test responses. In this case, the HTTP GET is again much faster.

For example, I have a request for one AES-ECB test. When I upload the response, I usually wait about 2 minutes for the reply. When I upload the response, interrupt it and resume it after, say, some 10 or 15 seconds, I get the verdict immediately.

**Comment by hbooth** [comment]
One thing I want to mention, is that the 30-second retry time is basically a fixed value that is long enough so that many will be ready and that it puts a long enough delay to avoid excessive load on the server, but short enough that it won't cause the process to take overly long.
The server doesn't really know how long it's going to take at this point to actually get you the results. So stopping and restarting before the 30 seconds is up may get you the results file (many of the requests take less than 15 seconds). That's more or less a feature and not bug.

The issues I have been looking at were ones relating to the excessively long delay between when a validation submission would be processed and when a test session would be updated to it's new state, as well as the delay relating to the validation results file. There were also some threading/db deadlock issues which were (hopefully) resolved that would sometimes cause a submission to never be available/processed to the web api.

**Comment by smuellerDD** [comment]
Am Mittwoch, 21. November 2018, 17:41:13 CET schrieb Harold Booth:

Hi Harold,

> One thing I want to mention, is that the 30-second retry time is basically a
> fixed value that is long enough so that many will be ready and that it puts
> a long enough delay to avoid excessive load on the server, but short enough
> that it won't cause the process to take overly long. The server doesn't
> really know how long it's going to take at this point to actually get you
> the results. So stopping and restarting before the 30 seconds is up may get
> you the results file (many of the requests take less than 15 seconds).
> That's more or less a feature and not bug.

Agreed and understood. But I consider it a bug when for one given request, the 
server lets me wait 2 minutes (4 times 30 second wait periods) but with a 
termination/restart I get the data within a total time of 30 seconds (i.e. the 
server leaves me waiting for 2 to 3 30 second wait periods that seem to be not 
necessary.

Ciao
Stephan

**Comment by hbooth** [comment]
> server lets me wait 2 minutes (4 times 30 second wait periods) but with a termination/restart I get the data within a total time of 30 seconds (i.e. the server leaves me waiting for 2 to 3 30 second wait periods that seem to be not necessary.

I am not sure there is anything in the server that would cause this (although I won't rule it out). The server doesn't maintain any state relating to a particular connection. If you are seeing behavior where terminating your client and then hitting the server immediately yields different results than letting the client run, perhaps something is on the client side? Is your client maintaining a response and reusing it (I know some browsers do this, although I believe these responses do indicate to not cache them).

If you are able to reproduce this, I would like to better understand what the triggers are if it is a server-side issue.

**Comment by smuellerDD** [comment]
Am Mittwoch, 21. November 2018, 17:55:22 CET schrieb Harold Booth:

Hi Harold,

> > server lets me wait 2 minutes (4 times 30 second wait periods) but with a
> > termination/restart I get the data within a total time of 30 seconds
> > (i.e. the server leaves me waiting for 2 to 3 30 second wait periods that
> > seem to be not necessary.
> I am not sure there is anything in the server that would cause this
> (although I won't rule it out). The server doesn't maintain any state
> relating to a particular connection. If you are seeing behavior where
> terminating your client and then hitting the server immediately yields
> different results than letting the client run, perhaps something is on the
> client side? Is your client maintaining a response and reusing it (I know
> some browsers do this, although I believe these responses do indicate to
> not cache them).

My client is not maintaining any state other than keeping the auth token and a 
state regarding the OTP generation (i.e. when an OTP value is generated in 
less than 30 seconds, it waits until a new OTP is generated). 
> 
> If you are able to reproduce this, I would like to better understand what
> the triggers are if it is a server-side issue.

I will open source the code quite soon now. You will be able to test it for 
yourself :-)

Ciao
Stephan

**Comment by smuellerDD** [comment]
I will close that - if you want to have more details again, please reopen.
