### ISSUE TITLE
v0.5: DSA sigver 3072/256 test vector generation failed

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#477]
The ACVP server failed to generate 3072/256 DSA sigver vectors (2048/256 and 2048/224 worked).

vsID 119.

**Comment by celic** [comment]
I ran the registration myself in the same environment and could not replicate the error. The error had something to do with our async calls. Was this a part of a really large registration?

**Comment by celic** [comment]
I think all these issues are related. These are all long-running tests. I'm wondering if the issue happened because they were run at (nearly) the same time. When I ran one individually it worked without issue. Perhaps you can run them individually and see if they work? That would at least provide the assurance that the error is somewhere when lots of "hard" algos are run at once.

**Comment by smuellerDD** [comment]
let me run it again

**Comment by smuellerDD** [comment]
Am Dienstag, 6. November 2018, 19:30:58 CET schrieb Chris Celi:

Hi Chris,

> I think all these issues are related. These are all long-running tests. I'm
> wondering if the issue happened because they were run at (nearly) the same
> time. When I ran one individually it worked without issue. Perhaps you can
> run them individually and see if they work? That would at least provide the
> assurance that the error is somewhere when lots of "hard" algos are run at
> once.

Just finished downloading ECDSA and RSA vectors: They still fail as reported.

Gathered ECDSA vectors: 271 and 272 (keygen and keyver). Failures 272 and 273 
(siggen/sigver).

Failed RSA vectors: 270, 269, 268

DSA is still loading.

testSession 129.

Ciao
Stephan

**Comment by celic** [comment]
Apologies, I meant running each algorithm alone as the only content of the testSession. This should still provide us with some meaningful data on the failure however.

**Comment by smuellerDD** [comment]
Am Dienstag, 6. November 2018, 20:54:24 CET schrieb Chris Celi:

Hi Chris,

> Apologies, I meant running each algorithm alone as the only content of the
> testSession. This should still provide us with some meaningful data on the
> failure however.

Ok, running them separately without regard to the dependencies.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, 6. November 2018, 20:54:24 CET schrieb Chris Celi:

Hi Chris,

> Apologies, I meant running each algorithm alone as the only content of the
> testSession. This should still provide us with some meaningful data on the
> failure however.

tcID 343 (RSA keygen) 

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, 6. November 2018, 20:54:24 CET schrieb Chris Celi:

Hi Chris,

> Apologies, I meant running each algorithm alone as the only content of the
> testSession. This should still provide us with some meaningful data on the
> failure however.

RSA siggen: tcID 344.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, 6. November 2018, 20:54:24 CET schrieb Chris Celi:

Hi Chris,

> Apologies, I meant running each algorithm alone as the only content of the
> testSession. This should still provide us with some meaningful data on the
> failure however.

RSA siggver: tcID 345

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, 6. November 2018, 20:54:24 CET schrieb Chris Celi:

Hi Chris,

> Apologies, I meant running each algorithm alone as the only content of the
> testSession. This should still provide us with some meaningful data on the
> failure however.

ECDSA sigver seems to take forever, it is still loading: vsID 347.

Shall I continue with DSA?

Ciao
Stephan

**Comment by celic** [comment]
I can see that 347 is done processing. It is ready for retrieval. Did you get it?

**Comment by smuellerDD** [comment]
Am Dienstag, 6. November 2018, 22:52:32 CET schrieb Chris Celi:

Hi Chris,

> I can see that 347 is done processing. It is ready for retrieval. Did you
> get it?

Yes, got it now.

Ciao
Stephan

**Comment by celic** [comment]
Did any of these fail during generation? The one I saw (347) looked successful after generation.

**Comment by smuellerDD** [comment]
Am Mittwoch, 7. November 2018, 19:33:50 CET schrieb Chris Celi:

Hi Chris,

> Did any of these fail during generation? The one I saw (347) looked
> successful after generation.

347 was successful (ECDSA sigver. The others (RSA, ECDSA siggen) were 
unsuccessful.

Ciao
Stephan

**Comment by Kritner** [comment]
Some updates were pushed out in demo that ***may*** have addressed some of the issue found here. @smuellerDD could you try one of the multi algo registrations and see if you end up successfully getting the full set?

I'm not positive that the recent tweaks to this functionality would have addressed this issue, but it could have.

**Comment by smuellerDD** [comment]
confirmed, working.

**Comment by Kritner** [comment]
awesome, thanks!
