### ISSUE TITLE
v0.5: KW: Plaintext requested by ACVP server in case of authentication errors

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#479]
The ACVP server verdict states the following errors:

```
  }, {
    "tcId" : 953,
    "result" : "failed",
    "reason" : "PlainText was not present in the TTestCase"
  },
```

This type of error occurs always when my IUT identifies a decryption error and returns testPassed:false.

As all decryption errors are flagged with the mentioned error, it seems that the ACVP server requires some plaintext data along with the decryption errors. But I cannot send plaintext as the module will not give me plaintext.

vsID 77

**Comment by smuellerDD** [comment]
Note, this applies also to KWP

**Comment by Kritner** [comment]
A fix for this should be in the next release.  It looked like this would also apply to TDES-KW, had you experienced that as well?

**Comment by smuellerDD** [comment]
Am Dienstag, 6. November 2018, 15:44:28 CET schrieb Russ Hammett:

Hi Russ,

> A fix for this should be in the next release.  It looked like this would
> also apply to TDES-KW, had you experienced that as well?

I currently have no TKW implementation to play with.

Ciao
Stephan

**Comment by Kritner** [comment]
Ah ok, just wanted to double check.
