### ISSUE TITLE
[Request] Add "Website" to front page of repository

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#486]
A project maintainer could add a "website" with a link to the new github pages (note I cannot do this as a contributor).  

Here are the steps:
* From the repo front page [https://github.com/usnistgov/ACVP](https://github.com/usnistgov/ACVP)
* Click Edit
![image](https://user-images.githubusercontent.com/8814983/48132265-f8943380-e260-11e8-8f1f-77a858ac4f72.png)
* Add website https://usnistgov.github.io/ACVP/, and save:
![image](https://user-images.githubusercontent.com/8814983/48132317-1feb0080-e261-11e8-8344-86f58953025c.png)
* Should look like this when done
![image](https://user-images.githubusercontent.com/8814983/48132393-617bab80-e261-11e8-9c52-7ff489dde5b7.png)

**Comment by atvassilev** [comment]
@Kritner what would be the value of having a web site that simply mimics the GitHub repository for ACVP?

**Comment by Kritner** [comment]
This would be done so people can find the github pages URL from #466, and are able to more easily find the "non raw" view of the HTML specifications.

**Comment by atvassilev** [comment]
OK, I added it.
