### ISSUE TITLE
v0.5: global test session verdict wrong

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#490]
The global verdict provided with the test session verdict seems wrong.

The only vsID in the test session shows a passing verdict. Yet, the test session verdict shows:

```
[{"acvVersion":"0.5"},{"passed":false,"results":[{"vectorSetUrl":"/acvp/v1/testSessions/198/vectorSets/430","status":"passed"}]}]
```

PS: A small nit: In all cases of JSON data, the ACVP server uses nicely formatted JSON (i.e. proper indentation). This verdict is the only exception. However, this verdict is most likely the one read by humans. Thus, may I suggest to also use the nice JSON format for this one?

**Comment by celic** [comment]
@hbooth this is for you.

**Comment by hbooth** [comment]
Added a fix to pretty print the output. Also, added an update to now immediately attempt to update the test session status. Currently, there is a background process which updates this status. If you were to wait ~5 minutes after you get the response back from the server that should guarantee that the status has been updated.

Both of these fixes have not yet been deployed to demo and I will update this issue once it is out there.

**Comment by hbooth** [comment]
Just noticed this is (mostly) a duplicate to #455.
I will close this one and update #455 once deployed.

**Comment by smuellerDD** [comment]
When uploading a test response and constantly retrying, the ACVP server returns the proper test session verdict.

However, when I upload the test response, wait, say, for one retry session, terminate the HTTP link, and then re-restablish the download request for the verdict, the vsID verdict is downloaded and show all pass. Yet, the testsession verdict shows:

```
[ {
  "acvVersion" : "0.5"
}, {
  "passed" : false,
  "results" : [ {
    "vectorSetUrl" : "/acvp/v1/testSessions/99/vectorSets/434",
    "status" : "unreceived"
  } ]
} ]
```

Again, the vsID verdict for vsID 434 is received after the interruption with the resumed download request.

@hbooth you can now try it with the published code:

```
./acvp-proxy -m Nettle -f --testid 99
ACVPProxy (16:10:48) Status - File backend: Start processing testID 99 with vsID 434
ACVPProxy (16:10:51) Status: (Re)Try testID 99 / vsID 434 (0 / 1 done)
^\ACVPProxy (16:10:53) Status - Signal handler: Canceling the outstanding download operations
Not all testIDs were processed cleanly. Invoke ACVP Proxy with the following options to continue processing the remaining test vectors possibly with the --request option:
--testid 99
```

The download was interrupted with a SIGSTOP which simply terminates the ACVP Proxy. Or you can simply sever your network link.

Resume the download:

```
$ ./acvp-proxy -m Nettle -f --testid 99
ACVPProxy (16:11:02) Status - File backend: Start processing testID 99 with vsID 434
ACVPProxy (16:11:02) Status: (Re)Try testID 99 / vsID 434 (0 / 1 done)
ACVPProxy (16:11:34) Status: (Re)Try testID 99 / vsID 434 (0 / 1 done)
ACVPProxy (16:11:36) Status: Verdict obtained for testID 99 / vsID 434 (completed vsIDs 1 / 1)
ACVPProxy (16:11:36) Status - File backend: Processing completed for testID 99 with vsID 434 with return code 0

The following vsIDs passed:
434
```

Interestingly, when I re-download the testsession verdict, it shows all as pass:

```
rm testvectors/atsec_corp_/Nettle__Common_/3.4/99/verdict.json
$ ./acvp-proxy -m Nettle -f --testid 99
ACVPProxy (16:18:35) Status - TOTP MQ System: Requesting OTP value, waiting ...
ACVPProxy (16:18:35) Status: Logging into ACVP server to refresh existing auth token
ACVPProxy (16:18:37) Status: (Re)Try testID 99
```

**Comment by hbooth** [comment]
Is this still a problem?

**Comment by smuellerDD** [comment]
Just tried it and it works as expected.
