### ISSUE TITLE
v0.5: AES-CTR: IUTs do not agree with ACVP server

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#491]
My IUTs produce the very same AES-CTR output. Yet, the ACVP server flags some results (especially the ones with the long strings) as wrong:

```
  }, {
    "tcId" : 61,
    "result" : "failed",
    "reason" : "Unexpected counter underflow at IV 0"
  }, {
    "tcId" : 62,
    "result" : "failed",
    "reason" : "Unexpected counter underflow at IV 0"
  }, {
    "tcId" : 63,
    "result" : "failed",
    "reason" : "Unexpected counter underflow at IV 0"
  }, {
    "tcId" : 64,
    "result" : "failed",
    "reason" : "Unexpected counter underflow at IV 0"
  }, {
    "tcId" : 65,
    "result" : "failed",
    "reason" : "Unexpected counter underflow at IV 0"
  }, {
    "tcId" : 66,
    "result" : "failed",
    "reason" : "Unexpected counter underflow at IV 0"
  }, {
```

The IUTs are OpenSSL and libgcrypt.

vsID: 20

**Comment by celic** [comment]
The CTR tests do some back-computing to determine the list of IVs used for the long message. I'll take a look to see what's happening. To be clear, this happened for two separate IUTs (two separate vector sets)?

**Comment by celic** [comment]
Just to be sure, on this registration you left off some properties... `overflowCounter` and `incrementalCounter` which assumed some default values as a result. Those default values were incorrect for what you intended. Please include these properties and try again.

**Comment by smuellerDD** [comment]
Am Donnerstag, 8. November 2018, 17:42:55 CET schrieb Chris Celi:

Hi Chris,

> The CTR tests do some back-computing to determine the list of IVs used for
> the long message. I'll take a look to see what's happening. To be clear,
> this happened for two separate IUTs (two separate vector sets)?

Two separate IUTs

Ciao
Stephan

**Comment by smuellerDD** [comment]
Thanks for the pointers, I missed those.

Confirmed. Working.
