### ISSUE TITLE
KDF108 vectors missing "deferred" property

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#496]
**testSessionId**
60

**vsId**
225

**Endpoint in which the error is experienced**
GET https://demo.acvts.nist.gov:443/acvp/acvp/v1/testSessions/60/vectorSets/225

The kdf108 spec defines "deferred" to be a required property in each "test" object, but it is missing from the vectors retrieved from the server:
    "tests" : [ {
      "tcId" : 1,
      "keyIn" : "35A8E6B2963D95266F610751A822CAC4"
    }, ...

**Comment by celic** [comment]
The spec is wrong there due to the whole "optional" column on those tables being hard to configure with the case-per-case basis... In other words, `deferred` should only be included when the counter location is "middle fixed data".

**Comment by celic** [comment]
Would it be possible to test this again? This fix should have gone out with v0.5.4.

**Comment by bfussell** [comment]
I don't see "deferred" with "after fixed data". IS that what you were looking for ?
