### ISSUE TITLE
v0.5: SHA3 MCT errors

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#503]
**testSessionId**
118

**vsId**
832, 833, 834, 835

The ACVP server does not accept the SHA-3 MCT results I present.

I use the MCT approach defined for SHA-1 and SHA-2. Is there a different MCT approach defined?

**Comment by Kritner** [comment]
@smuellerDD The SHA1/2 vs SHA3 MCT tests do seem to vary ever so slightly.  I believe @celic's changes in PRs #489 and #498 would cover the actual MCT test pseudocode, but in the interim, ACVP will match the CAVS implementations which can be found https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/shs/SHAVS.pdf and https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/sha3/sha3vs.pdf

SHA1/2:

```
INPUT: Seed - A random seed n bits long
{
	for (j=0; j<100; j++) {
		MD0 = MD1 = MD2 = Seed;
		for (i=3; i<1003; i++) {
			Mi = MDi-3 || MDi-2 || MDi-1;
			MDi = SHA(Mi);
		}
		MDj = Seed = MD1002;
		OUTPUT: MDj
	}
}
```

SHA3:

```
INPUT: A random Seed n bits long
{
	MD0 = Seed;
	for (j=0; j<100; j++) {
		for (i=1; i<1001; i++) {
			Msgi = MDi-1;
			MDi = SHA3(Msgi);
		}
	MD0 = MD1000;
	OUTPUT: MD0
	}
}
```

**Comment by smuellerDD** [comment]
My bad to have missed this subtle nuance. 

After fixing it, it works.

Thanks!
