### ISSUE TITLE
AES CFB: MCT decrypt successful although IUT CFB decryption is broken

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#505]
I would like to report a strange result that I am not sure how to interpret.

My IUT's CFB implementation decryption operation is broken as outlined in [1]. The CFB decryption testing rightfully fails.

But for CFB-128, the MCT decryption fully passes! This is unexpected.

test session 119, vsID 840:

The MCT tests with tcID 2139 through 2144 covering encrypt/decrypt all pass. The preceding AFT decrypt tests all fail. How can that be?

[1] https://marc.info/?l=linux-crypto-vger&m=153999011904457&w=2

**Comment by Kritner** [comment]
Hey @smuellerDD I'll try to take a look into some of this at some point today/this weekend - but one way MCT could pass but AFTs fail is some AFT work on multi block, where as MCT do not.  Have you done any checking into if it's only AFT tests more than a single block that are failing?  (note I have not checked your vector sets yet either)

**Comment by smuellerDD** [comment]
> Am 09.11.2018 um 20:10 schrieb Russ Hammett <notifications@github.com>:
> 
> Hey @smuellerDD I'll try to take a look into some of this at some point today/this weekend - but one way MCT could pass but AFTs fail is some AFT work on multi block, where as MCT do not. Have you done any checking into if it's only AFT tests more than a single block that are failing? (note I have not checked your vector sets yet either)

It fails also on one block operation (e.g. tcID 1040 and following). I will also keep looking, but I just wanted to raise the issue.

**Comment by Kritner** [comment]
and just to double check, this is specific to AES-CFB-128 decrypt only? all other segment sizes with all directions are ok?

**Comment by smuellerDD** [comment]
Am Freitag, 9. November 2018, 20:36:45 CET schrieb Russ Hammett:

Hi Russ,

> and just to double check, this is specific to AES-CFB-128 decrypt only? all
> other segment sizes with all directions are ok?

The error applies to all decryption operations with all key sizes. I.e. *only* 
encryption is supposed to work correctly with the IUT.



Ciao
Stephan

**Comment by Kritner** [comment]
![image](https://user-images.githubusercontent.com/8814983/48287003-6729ea80-e435-11e8-928c-19bd1e0fceb6.png)
![image](https://user-images.githubusercontent.com/8814983/48287013-727d1600-e435-11e8-8d32-ba5397219aa1.png)

@smuellerDD just posting the above images so for reference... Could your MCT test harness be using CFB-128 encrypt, rather than decrypt?  That would seemingly produce the appropriate behavior for the single block tests done through MCT.

example:

```cs
key = new "E43C2AABC73B1167B7490D18E5D22A4E";
iv = "98A45C3157B41799E62B5932BCC7349D";
plaintext = "3CCD3145122047DCFEE1F37E9C71ED91";

ct = enc(key, iv, pt)
```
ct = "02B80EBBACFFDCB78D7CEDFBDD1CFEA9"

and

```cs
key = "E43C2AABC73B1167B7490D18E5D22A4E";
iv = "98A45C3157B41799E62B5932BCC7349D";
plaintext = "02B80EBBACFFDCB78D7CEDFBDD1CFEA9";

ct = enc(key, iv, pt);
```
ct = "3CCD3145122047DCFEE1F37E9C71ED91"

**Comment by smuellerDD** [comment]
My harness implements the MCT Independent from the IUT. The IUT specific interface used by the MCT logic just offers encryption and decryption. The MCT logic should work as other IUTs with CFB pass the test. That said the MCT logic invokes the faulty decryption operation of my broken IUT. 

Though it could be very much possible that the error makes CFB dec behave like encrypt. If so, how can the MCT dec pass? If it passes, wouldn’t be the MCT definition problematic?

Ciao
Stephan

**Comment by Kritner** [comment]
Hmm, I'm really not sure then! At a glance, it looks like our MCT impl is working properly - matches with CAVS and your results do in fact match our results.  I could look into this a bit closer at some point after this week, but just trying to tighten everything else up with v0.5 until then.

Also, some of this MCT stuff may be handled at some point in the future based on the discussion that took place in #437

**Comment by smuellerDD** [comment]
Not sure what we should do here - shall we simply close the issue?

**Comment by Kritner** [comment]
Perhaps... it is still a little concerning. @bfussell do you guys test AES-CFB? Are you able to confirm that you're successfully getting through a vector set?

The MCT "passing" with a bugged implementation is strange, but the MCT isn't supposed to be the "all encompassing test", there are other test types being utilized that would theoretically catch other issues - so hopefully that is enough to close the issue for now.  I am curious about @bfussell's response though.

**Comment by bfussell** [comment]
Yes, AES-CFB1, AES-CFB8 and AES-CFB128 all pass for us.

**Comment by Kritner** [comment]
Thanks @bfussell.  @smuellerDD I guess I'll close this issue for now.
