### ISSUE TITLE
v0.5: CTR definition

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#510]
During the discussion with issue #207 I briefly mentioned that the CTR mode uses the keyword "dataLength" whereas all other symmetric ciphers use "ptLen". The SPEC actually does not refer to dataLength, but I still use it.

```
      {
        "algorithm":"AES-CTR",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          128,
          192,
          256
        ],
        "dataLength":[
          128
        ],
        "ivLen":[
          128
        ],
        "ctrSource":"external",
        "overflowCounter":false,
        "incrementalCounter":true
      },
```

May I ask whether dataLength is still needed or can be replaced with ptLen?

**Comment by smuellerDD** [comment]
Am Dienstag, 13. November 2018, 13:25:30 CET schrieb Russ Hammett:

Hi Russ,

> @smuellerDD once #497 is merged in, the symmetric ciphers will be using a
> consistent `payloadLen` across the board.

Great. Just to clarify: this applies to both, the register JSON data as well 
as the testvectors/responses?

> Hopefully this won't cause too
> much trouble for folks, but as it was pointed out, consistency wasn't there
> - I went with `payloadLen` in the hopes that it would be a bit less
> ambiguous than `dataLen`.  The change will hit the demo server in the next
> deploy and/or when #497 is merged in.

In my code, this is a trivial change.

Ciao
Stephan

**Comment by Kritner** [comment]
> Great. Just to clarify: this applies to both, the register JSON data as well
as the testvectors/responses?

Correct

**Comment by smuellerDD** [comment]
Clarified
