### ISSUE TITLE
v0.5: EDDSA siggen and sigver vectors are not generated by ACVP server

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#513]
The ACVP server returns the following answer for both, EDDSA siggen and sigver:

```
[ {
  "acvVersion" : "0.5"
}, {
  "vsId" : 1489,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 1489"
} ]
```

vsID 1488 and 1489

Register request:

```
      {
        "algorithm":"EDDSA",
        "mode":"sigGen",
        "curve":[
          "ED-25519"
        ],
        "pure":true,
        "preHash":true,
        "prereqVals":[
          {
            "algorithm":"SHA",
            "valValue":"same"
          },
          {
            "algorithm":"DRBG",
            "valValue":"same"
          }
        ]
      },
      {
        "algorithm":"EDDSA",
        "mode":"sigVer",
        "curve":[
          "ED-25519"
        ],
        "pure":true,
        "preHash":true,
        "prereqVals":[
          {
            "algorithm":"SHA",
            "valValue":"same"
          },
          {
            "algorithm":"DRBG",
            "valValue":"same"
          }
        ]
      }
```

**Comment by elliemdaw** [comment]
I am running into the same error for ECDSA siggen:
```json
{
        "algorithms": [
            {
                "algorithm": "ECDSA",
                "mode": "sigGen",
                "prereqVals": [
                    {
                        "algorithm": "SHA",
                        "valValue": "same"
                    },
                    {
                        "algorithm": "DRBG",
                        "valValue": "same"
                    }
                ],
                "capabilities": [
                    {
                        "curve": [
                            "P-224",
                            "P-256",
                            "P-384",
                            "P-521",
                            "K-233",
                            "K-283",
                            "K-409",
                            "K-571",
                            "B-233",
                            "B-283",
                            "B-409",
                            "B-571"
                        ],
                        "hashAlg": [
                            "SHA2-224",
                            "SHA2-256",
                            "SHA2-384",
                            "SHA2-512"
                        ]
                    }
                ]
            }
        ]
    }
```

**Comment by Kritner** [comment]
@smuellerDD I'm pretty sure EDDSA is rough at best at the moment - we were concentrating on getting the other v0.5 algorithms working prior to doing too much with EDDSA (AFAIK).  We can try to take a look at this within the coming weeks, but is less of a priority compared to the other algorithms.

@elliemdaw what was your test session and vsid? what failure did you receive?

**Comment by smuellerDD** [comment]
Am Mittwoch, 14. November 2018, 23:21:59 CET schrieb Russ Hammett:

Hi Russ,

> @smuellerDD I'm pretty sure EDDSA is rough at best at the moment - we were
> concentrating on getting the other v0.5 algorithms working prior to doing
> too much with EDDSA (AFAIK).  We can try to take a look at this within the
> coming weeks, but is less of a priority compared to the other algorithms.

Sure, no worries. I just wanted to give it a try and see where I end up with.

Ciao
Stephan

**Comment by elliemdaw** [comment]
@Kritner the most recent was 1693 showing the same error that Stephan was seeing!
```
{
  "vsId" : 1693,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 1693"
}
```

**Comment by Kritner** [comment]
thanks @elliemdaw I do see an issue here, and it looks like it could at a minimum be causing part of the issue @smuellerDD was experiencing.  Working on a fix now, should be in the next release.

This issue looks like it could have also been affecting DSA.KeyGen and DSA.SigGen, but I have not yet confirmed that.

**Comment by smuellerDD** [comment]
confirmed, working (for EDDSA that is).

@elliemdaw please close issue after you confirmed ECDSA is working for you.

**Comment by Kritner** [comment]
This original issue seems to be resolved, and haven't heard back negatives regarding ECDSA. Closing unless something further comes up.
