### ISSUE TITLE
change vsID verdicts to use JSON booleans

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#525]
The verdicts returned for vsIDs are still string-based pass/fail statements. May I propose to use JSON booleans for that?

Note, the testsession verdicts contain JSON booleans.

**Comment by hbooth** [comment]
I think this is a good suggestion and easy to change in the code if someone wants to take on getting the spec updated. That will be the major hang-up for me at this point. I already have a pile of spec changes I will need to make.

**Comment by hbooth** [comment]
I take back my earlier comment. I just took a look at this. I am assuming you are talking about the `disposition` property on the `GET /testSessions/{testSessionId}/vectorSets/{vectorSetId}/results` request. For that request disposition can have multiple values. Or are you talking about a different property and request?

**Comment by smuellerDD** [comment]
Am Freitag, 29. März 2019, 22:18:15 CET schrieb Harold Booth:

Hi Harold,

> I take back my earlier comment. I just took a look at this. I am assuming
> you are talking about the `disposition` property on the `GET
> /testSessions/{testSessionId}/vectorSets/{vectorSetId}/results` request.
> For that request disposition can have multiple values. Or are you talking
> about a different property and request?

I am refering to the "result" keyword in the per vsID verdict which contain a 
"passed" or "failed". Is there another answer than these two?

Note, I am not referring to the the disposition keyword.

Ciao
Stephan

**Comment by Kritner** [comment]
This change sounds fine to me - is this something we want pre 1.0? it would seemingly be a simpler change to do prior to 1.0 rather than. post 1.0, but would also mean code changes now from the ACVP server and client perspectives,

Is there a reason you wouldn't want to change disposition as well?

Currently we have:

```json
{
  "vsId": 42,
  "disposition": "passed",
  "tests": [
    {
      "tcId": 1,
      "result": "passed"
    }
}
```

We could convert both to a boolean, but it would probably make the most sense to change the property name as well to make it more boolean like... something like:

```json
{
  "vsId": 42,
  "setPassed": true
  "tests": [
    {
      "tcId": 1,
      "testPassed": true
    }
}
```

@hbooth would such a change impact you in any way? aren't you looking at these files to determine the success/failure of the session as a whole?

This looks to be a fast change from my perspective, but want to be more sure of the repercussions to making such a late in the game change (assuming we wanted the change pre 1.0)

**Comment by Kritner** [comment]
FYI - after looking at the code, I see that we do use more than just "passed" and "failed" within the current `result` property.  We also will mark this as "missing" if the IUT does not include information for a specific test.

While this could be covered under "fail", it does unfortunately mean there's a bit more logic to this property than I originally realized.  Not saying that it still can't be changed, but it's going to be a bit bigger of a change on my end than I initially thought - so I don't know if that will impact any decisions on whether or not the change should be made before or after 1.0.

**Comment by Kritner** [comment]
@smuellerDD I did like the idea of this, but since we're currently using more than just "passed" and "failed" within this field under certain circumstances, it's probably safer to hold off on making this change this late in the game.  Perhaps this can be revisited in a future release?

**Comment by smuellerDD** [comment]
Am Montag, 1. April 2019, 20:34:45 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD I did like the idea of this, but since we're currently using
> more than just "passed" and "failed" within this field under certain
> circumstances, it's probably safer to hold off on making this change this
> late in the game.  Perhaps this can be revisited in a future release?

Sure, close the issue at your discretion.

Ciao
Stephan

**Comment by Kritner** [comment]
Will close for now, can revisit in the future
