### ISSUE TITLE
CFB1 payloadLen required ?

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#526]
The sample data for AES and TDES differ wrt to payloadLen. Here is an AES AFT and MCT.
Its included in each AFT test case response and prior to the results Array level for MCT.

```json
      "tcId" : 588,
      "payloadLen" : 10,
      "pt" : "9BC0"
    } ]
  }, {
    "tgId" : 11,
    "tests" : [ {
      "tcId" : 589,
      "payloadLen" : 1,
      "resultsArray" : [ {.....
```

Here is TDES AFT and MCT, its not included in either.
```json
                    {
                        "tcId": 688,
                        "pt": "C4C0"
                    }
                ]
            },
            {
                "tgId": 13,
                "tests": [
                    {
                        "tcId": 689,
                        "resultsArray": [
                            {
                                "key1": "A45E252A11ACFEF3",
                                "key2": "0AB457A7D6F36C4B",
                                "key3": "11DFB1B01E28BDA9",
                                "iv": "897DB2FFD1570550",
                                "pt": "00",
                                "ct": "80"
                            },
```

**Comment by Kritner** [comment]
The `payloadLen` should not be required when the IUT sends their response.  I think this is just a spec issue, could you confirm you're able to submit w/o `payloadLen`?

**Comment by bfussell** [comment]
Yes, the response works for both AES and TDES without including paloadLen. In addition to the spec issue, the sample response is a bit misleading as well since it includes the payloadLen.

**Comment by Kritner** [comment]
>  In addition to the spec issue, the sample response is a bit misleading as well since it includes the payloadLen.

Can you elaborate @bfussell? I thought the spec issue ***was*** the samples?  I'm not seeing a reference to `payloadLen` within the body of the responses section:

https://usnistgov.github.io/ACVP/artifacts/draft-celi-block-ciph-00.html#rfc.section.6

**Comment by bfussell** [comment]
Correct, no issue in section 6 response section. The spec issue is in the examples in the appendices.
In addition, the "sample" responses from the server when using "isSample" : true include payloadLen as well.

**Comment by Kritner** [comment]
Oh ok sorry, from the initial post talking about sample data, I was thinking that was in regards to the specification.  I'll put in a fix so that property is not included for `isSample` files.

**Comment by Kritner** [comment]
I've made an update to the specification to remove the `payloadLen` from the IUT response back to the ACVP server.  I'll update this ticket once the change has gone out to demo (regarding the `isSample` response).

**Comment by Kritner** [comment]
The latest release to demo should have addressed this issue, let me know if there are any problems.
