### ISSUE TITLE
CTR mode registration for overflow and incremental

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#527]
It appears the server is using these options as they registered, however the JSON sent with the test vectors always has these two options set to false regardless of how it is registered. For example, this registration:
        "algorithms": [
            {
                "algorithm": "AES-CTR",
                "direction": [
                    "encrypt",
                    "decrypt"
                ],
                **"incrementalCounter": true,
                "overflowCounter": true,**
                "keyLen": [
                    128,
                    192,
                    256
                ],
                "payloadLen": [
                    128
                ]
            },
            {
                "algorithm": "TDES-CTR",
                "direction": [
                    "encrypt",
                    "decrypt"
                ],
                **"incrementalCounter": true,
                "overflowCounter": true,**
                "keyingOption": [
                    1
                ],
                "keyLen": [
                    192
                ],
                "payloadLen": [
                    64
                ]
            }
        ]
always returns this with the test vectors:

  "vsId" : 2210,
  "algorithm" : "AES-CTR",
  "isSample" : false,
  "testGroups" : [ {
    "tgId" : 1,
    "testType" : "AFT",
    "direction" : "encrypt",
    "keyLen" : 128,
    **"incremental" : false,
    "overflow" : false,**
    "tests" : [ {
      "tcId" : 1,
...

  "vsId" : 2211,
  "algorithm" : "TDES-CTR",
  "isSample" : false,
  "testGroups" : [ {
    "tgId" : 1,
    "direction" : "encrypt",
    "keyingOption" : 1,
    **"incrementalCounter" : false,
    "overflowCounter" : false,**
    "testType" : "AFT",
    "tests" : [ {
      "tcId" : 1,

**Comment by smuellerDD** [comment]
I think this is display only. When processing the data with incremental == true at least, it passes for me.

**Comment by celic** [comment]
I'll take a look at this. Incremental determines the direction of the counter. Overflow, if true, should add an extra CTR group to test the boundary cases. I'll double check this.

**Comment by celic** [comment]
On vsId 2210, this is the registration I see...
```
{
    "vsId":2210,
    "isSample":false,
    "algorithm":"AES-CTR",
    "direction":["encrypt","decrypt"],
    "incrementalCounter":true,
    "overflowCounter":false,
    "keyLen":[128,192,256],
    "payloadLen":[128]
}
```
which seems to differ from what you originally mention.

The error that I see in these files is that `incremental` and `overflow` are being included in the non-CTR groups. That is incorrect and those properties should only exist in CTR groups (where it appears correctly based on this registration).

**Comment by bfussell** [comment]
@celic  Is your JSON from a query for vsId information or when you GET the whole vector set when performing testing ?

**Comment by celic** [comment]
This is from an internal endpoint used to quickly pull vsIds and testSessions for debugging. It may not be the exact JSON you sent (hence the vsId being added). To speak exactly, this is the JSON that the Java server sends our C# application that creates the prompt files. 

I'm a bit curious as to why there is a difference in this file I can see versus the one you originally posted for `overflowCounter`.

**Comment by bfussell** [comment]
That difference you see on 2210 probably my bad cut/paste, Look at vsId 2156 for a case where I registered true on both and the vector sets came back from the server with false on both.

**Comment by celic** [comment]
Yeah. Those properties are only set for CTR groups. All other groups that show them are defaulted (which happens to be false). They play no effect in those groups which is why you are able to pass these vector sets without issue. I have fixed this for v0.5.4 so that those properties will only appear in the prompt for CTR groups.

**Comment by celic** [comment]
Please check in on this. The fix should have gone out with the latest v0.5.4 deploy.

**Comment by bfussell** [comment]
I see neither of those fields in the request vectors for AES-CTR or TDES-CTR. Was that the intent ?

**Comment by celic** [comment]
They should only appear in `"testType": "CTR"` groups in the prompt.

**Comment by bfussell** [comment]
Yep, that's what I see. I registered for true/true, but I see testGroups that have true/true and then another group with true/false. vsIds 685(AES) and 687(TDES).

From 685:
    "tgId" : 18,
    "testType" : "CTR",
    "direction" : "decrypt",
    "keyLen" : 256,
    "incremental" : true,
    "overflow" : false,
    "tests" : [ {

From 687:
    "tgId" : 6,
    "direction" : "encrypt",
    "keyingOption" : 1,
    "incrementalCounter" : true,
    "overflowCounter" : false,
    "testType" : "CTR",
    "tests" : [ {

:

**Comment by celic** [comment]
Incremental will always match what was registered, as the counters can only operate in one direction (increasing or decreasing).

Overflow will be both if you select `true`, because there is a chance the counter will overflow (if the starting IV is high enough to cause an overflow), and a chance that the counter will not overflow (if the starting IV is low enough to not cause an overflow). Both operations are supported and valid. 

It looks like everything is working as expected here.

**Comment by bfussell** [comment]
OK, looks good then. You can close this one.
