### ISSUE TITLE
Feature request - HTTP error unique id

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#531]
Hello,

Would it be possible to have the server send a unique ID in the message body when an HTTP error code is sent to client?

For example, a 401 is sent for when the JWT is expired and also when it is rejected (bad value). Currently, there is a message describing what went wrong, but that is subject to change in the future (being a sentence). It would be great to have a UID field that never changes. This will immensely help the client take different behavior paths depending upon what error it receives. Something along these lines may work...

"error" : { "id": "expired_jwt",
"msg": "The provided JWT is expired and no longer valid. Please re-enroll."
}

"error" : { "id": "bad_jwt",
"msg": "The provided JWT value is not valid."
}

**Comment by fliphil** [comment]
@elliemdaw @bfussell

**Comment by fliphil** [comment]
Not sure if anyone saw this, so bumping.

**Comment by celic** [comment]
@hbooth
