### ISSUE TITLE
Couple of document review comments for sha/sha-3

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#535]
draft-celi-sha3-00:
Section 4: block cipher algorithms to the ACVP server. ACVP REQURIES

draft-celi-sha-00:
Section 3: block padding etc.) are opertaing correctly.
Section 3: under test under stenuous circumstances.
Section 4: ACVP server. ACVP REQURIES cryptographic modules

**Comment by celic** [comment]
Thanks. Will address by Thursday.
