### ISSUE TITLE
Review comments for acvp-iana draft

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#536]
Section 7, add xref to ACVP protocol spec.

**Comment by celic** [comment]
Also, the IANA doc lists ACVP-AES-GMAC which we don't explicitly have listed in the symmetric spec. It would be ACVP-AES-GCM with specific parameters to qualify as GMAC.

**Comment by celic** [comment]
The previous comment is outdated now. We offer both ACVP-AES-GCM and ACVP-AES-GMAC as separate registrations. The symmetric specification reflects this.
