### ISSUE TITLE
Review comments for celi-block-ciph draft

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#537]
Section 2: Do we have to change the algs in section 2 to use the IANA definitions ?

Section 3: implentation (twice)
third bullet: AES-MCT and TDES-MCT, should be AES-CTR and TDES-CTR ?

3.1.11/12: Would it be helpful to note that CFB1, CFB8 and CFB64 all utilize these MCT flows ?

Section 8: add IANA xref

Normative References: add IANA draft

Update the normative reference to link to:
    https://github.com/usnistgov/ACVP/blob/master/artifacts/draft-fussell-acvp-spec-00.txt

**Comment by celic** [comment]
Thanks for the comments. I'll do these before Thursday. As a heads up, for Section 2, yes we intend on updating the names for algorithms to the IANA definitions in this document, the server, and gen/vals.
