### ISSUE TITLE
RSA: component decryption request definition

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#539]
For the RSA component decryption, the request requires the modulo value. The SPEC defines the request layout as 

```
     {
         "algorithm": "RSA",
         "mode": "decryptionPrimitive",
         "modulo": 2048,
         "prereqVals"
...
```

For all other RSA requests requiring the modulo value, it is found inside a capabilities array. This allows specifying multiple modulo values with one request.

May I propose to change the component decryption request to the following:

```
      {
        "algorithm":"RSA",
        "mode":"decryptionPrimitive",
        "capabilities":[
          {
            "modulo":2048
          },
          {
            "modulo":3072
          }
        ],
        "prereqVals":[
...
```

**Comment by celic** [comment]
Decryption Primitive should not have `modulo` in the registration. It may be mentioned in the `prompt.json` as a group property for clarity but is a static value at `2048`.

**Comment by celic** [comment]
If the specification is requiring a `modulo`, then that is incorrect. The server has no concept of a `modulo` for RSA Decryption Primitive.
