### ISSUE TITLE
SHA Specification does not allow for restricted input sizes

### ISSUE THREAD

**Issue by Rasstrelnikov** [usnistgov/ACVP#540]
The SHA specification does not allow for the case that the vendor's implementation restricts the size of the input string to be hashed. It is currently possible to validate a SHA implementation with this restriction using CAVS by manually checking the response files and adding a note to the validation letter (SHA.1 in the CAVP FAQ). Is it possible to address this in the specification? We have at least 1 vendor for which this will probably come up again in the future.

**Comment by celic** [comment]
This will be addressed in the future. The "solution" for CAVS is a workaround and isn't "officially" supported. It is still allowed with that note. Our current release was focused on the functionality of CAVS. The previous solution was a slight abuse of the old tool. We will have a proper structure worked into the JSON down the road. I don't know of a specific deadline, but it is definitely on our radar.

**Comment by Rasstrelnikov** [comment]
Okay, good to know that it is coming eventually. And I agree that the CAVS "solution" is not the best.

**Comment by acronymhaterheidi** [comment]
Resolved by #563
