### ISSUE TITLE
DSA probable PQ gen: spurious error

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#541]
**testSessionId**
1985

**vsId**
11762

**Algorithm registration**

DSA PQG generation, SHA2-256, probable

The IUT generates a probable PQ set for tcID 5. However, this is rejected by the ACVP server. Other PQ generation tests pass.

The server reply is not helpful to dissect the issue. Could it be that the first byte of the domainSeed is zero and that the ACVP server somehow mangles that? Note, the domain seed has the right length of 32 bytes which includes the first byte to be zero.

**Comment by smuellerDD** [comment]
A very similar issue with also the domain seed having a zero byte at the beginning is found testID 1985, vsID 11763, tcID 3. The ACVP server flags it as false.

**Comment by smuellerDD** [comment]
I did not see that error any more. Closing

**Comment by bfussell** [comment]
I still this issue, but its rare. It only occurs if the domainSeed has leading zeroes.  Since the seed is supposed to be 32 bytes I think the leading zeroes are supposed to be there and included.

This test case fails, from today, "vsId": 4332,

                        "tcId": 40,
                        "p": "DDF05405F7F34BC38F2940D575D3EFC7A4ED577C596000C776F43C0BD6F9D0E93189FAEE6BE4B4EF56CB15641883B1F63BE777FAE4AD4398931C3F19FB108DFB740DE328973935ABEBA70DE74EB3C75097909004D2AC5C34B6C2A296C91386AEC025DED0DF2FCC97478355B1487912D4BDD0882AB1D4A730B8FB70FA2FF628B50649E9A2B24092C58358B8A4249FBD52585CCCD1E4D89CBA831B66C1CD47C5A5A5C24B000F032D15E8B20CAE61385A6EAA05126DB0E9CF42A1B91F05BF360E95DEEBA18E5CC564D4D6A9BC09E189752EB78B31FBBA8A8CF9C9F5D239382D8E72A07A22672898185050F5B42495E98D6538D65A6F739EE64A6BC2B156103892BEF8833A00691EA7EE963DC7B05EADEBE61A3A934D178C97FD6EBE26DC498358FADF248892765FDD4773C10F0943F826CEB6ADBA4D7C627C340D5037D40825D5A3C28C656438773316283A99305F71DD6734BF9AC9F3E9A58E3235953CDE87186E6BDC48BC106E160FCB0564EE2517BE2B0A3CE4CB9BB8B2DE1B5269CE47E6DDAD",
                        "q": "DF9CEC2AB0999C72973E0A83BC21F4296B9AE529DEE158750A1A52718BC26627",
                        "domainSeed": "00F9D8C234891D211182E4874F9888CE051AB327B6E73F4CD3A40FC83D108473",
                        "counter": 423

**Comment by smuellerDD** [comment]
I see that issue also in: vsID 5316, tcId 1.

**Comment by smuellerDD** [comment]
This issue is still present:

test session ID 14411, vsID 42119, tcID 4

**Comment by celic** [comment]
I was just looking at this today and was going to ask. @Kritner should be able to get on this next week.

**Comment by Kritner** [comment]
A fix regarding this issue has been deployed to demo

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. Mai 2019, 11:44:24 CEST schrieb Russ Hammett:

Hi Russ,

> A fix regarding this issue has been deployed to demo

Ok, then let us close the issue. Since it is hard to reproduce we can assume 
it is fixed. If it shows up again, we could reopen the issue.

Ciao
Stephan

**Comment by Kritner** [comment]
Sounds good, yeah this is a hard one to test for :)
Did confirm with some new tests that a seed value starting with a 00 byte does now work at least.
