### ISSUE TITLE
RSA signature primitive expects incorrect case in server

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#542]
I register with the following structure:

```
      {
        "algorithm":"RSA",
        "mode":"signaturePrimitive",
        "keyFormat":"standard"
      },
```

The server responds:
```
{
  "acvVersion" : "0.5",
  "error" : "Incorrectly formatted JSON (1:3638): unknown algorithm: RSA with mode: signaturePrimitive"
}
```

**Comment by Kritner** [comment]
@smuellerDD can you try "SignaturePrimitive" with a capital "S" instead?  I'm not sure what it's supposed to be, but it looks like that's what expected (currently).

**Comment by smuellerDD** [comment]
Am Freitag, 1. Februar 2019, 14:04:36 CET schrieb Russ Hammett:

Hi Russ,

> @smuellerDD can you try "SignaturePrimitive" with a capital "S" instead? 
> I'm not sure what it's supposed to be, but it looks like that's what
> expected (currently).

Yes, that is accepted by the server. I leave the bug open as the 
implementation does not match the spec and violates the camel case base 
definitions.

Ciao
Stephan

**Comment by Kritner** [comment]
A fix for this has been pushed out to demo.  Note that this also impacted the `decryptionPrimitive` as well.
