### ISSUE TITLE
DSA sigver: ACVP server failed to generate test vector

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#544]
**testSessionId**
51

**vsId**
536

The ACVP server failed to generate the test vector with the following response:

```
[ {
  "acvVersion" : "0.5"
}, {
  "vsId" : 536,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 536"
} ]
```

**Comment by smuellerDD** [comment]
Note, the very same request generated a test vector: see test session 34, vsID 333

**Comment by smuellerDD** [comment]
In the last days since the deployment of 0.5.4 I get more and more HTTP errors from the ACVP server. See for example test ID 166 vsID 1875 or test ID 159 and vsID 1839.

**Comment by smuellerDD** [comment]
Now the ACVP server always generates this error irrespective of the cipher to be registered.

**Comment by Kritner** [comment]
Thanks @smuellerDD, looking into it.  And just to be clear is this any mode/registration of DSA SigVer, or every algorithm you've tried not specific to DSA SigVer?

**Comment by smuellerDD** [comment]
Am Montag, 11. Februar 2019, 13:55:15 CET schrieb Russ Hammett:

Hi Russ,

> Thanks @smuellerDD, looking into it.  And just to be clear is this any
> mode/registration of DSA SigVer, or every algorithm you've tried not
> specific to DSA SigVer?

This applies to all registration (I failed to get a SHA2 or SHA1 test vector 
or a HMAC vector).

Ciao
Stephan

**Comment by Kritner** [comment]
Hey @smuellerDD can you try now? This won't fix the original issue, but the other algorithms should be responding to requests.

**Comment by smuellerDD** [comment]
Am Montag, 11. Februar 2019, 15:06:46 CET schrieb Russ Hammett:

Hi Russ,

> Hey @smuellerDD can you try now? This won't fix the original issue, but the
> other algorithms should be responding to requests.

Now they work - I tested SHA and SSH KDF.

Ciao
Stephan

**Comment by bfussell** [comment]
Are you sure its working again ? I haven't been able to get SHA to work since late this morning.
Tried HMAC and KDF - same problem.

**Comment by smuellerDD** [comment]
I got test vectors. But when uploading the responses the server left me waiting indefinitely.

Ciao
Stephan

—
Cui bono?

**Comment by Kritner** [comment]
Is this still any issue for either of you @smuellerDD @bfussell ? The original issue and/or the subsequent issue? The original issue I still need to take a look into, but there was some maintenance on the day of the secondary issue that should have resolved the hanging of receiving responses.

**Comment by bfussell** [comment]
Saw one yesterday, but I think it was on ECDSA sigVer.

  "vsId" : 4499,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 4499"
} ]

**Comment by Kritner** [comment]
This was related to some resource contention issues that I believe have been mostly (hopefully completely?) solved.  I was going to close this for now, but we can reopen or submit new if the problems arise again.
