### ISSUE TITLE
SHAKE "outputLength" registration JSON rejected

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#545]
Here's the error...

`{
  "acvVersion" : "0.5",
  "error" : "Incorrectly formatted JSON (1:642): expected array value and detected scalar: outputLength"
}`

**Algorithm registration**
`[{"acvVersion":"0.5"},{"algorithms":[{"algorithm":"SHA-1","inBit":false,"inEmpty":true},{"algorithm":"SHA2-224","inBit":false,"inEmpty":true},{"algorithm":"SHA2-256","inBit":false,"inEmpty":true},{"algorithm":"SHA2-384","inBit":false,"inEmpty":true},{"algorithm":"SHA2-512","inBit":false,"inEmpty":true},{"algorithm":"SHA3-224","inBit":false,"inEmpty":true},{"algorithm":"SHA3-256","inBit":false,"inEmpty":true},{"algorithm":"SHA3-384","inBit":false,"inEmpty":true},{"algorithm":"SHA3-512","inBit":false,"inEmpty":true},{"algorithm":"SHAKE-128","inBit":false,"inEmpty":true,"outBit":false,"outputLength":{"min":16,"max":65536,"increment":8}},{"algorithm":"SHAKE-256","inBit":false,"inEmpty":true,"outBit":false,"outputLength":{"min":16,"max":65536,"increment":8}}]}]`

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443/acvp/acvp/v1/testSessions| POST

**Expected behavior**
It should accept the "outputLength" according to this document: https://github.com/usnistgov/ACVP/blob/master/artifacts/draft-celi-sha3-00.txt

**Comment by Rasstrelnikov** [comment]
I would guess this is because your value for outputLength is not an array. A domain is an array that contains ranges (which is the object you have) or integers. So I believe
 ```"outputLength":[{"min":16,"max":65536,"increment":8}]```

**Comment by celic** [comment]
@acronymhaterheidi is correct. A domain could be an array of individual values, mixed with these mentioned range objects.

**Comment by fliphil** [comment]
Okay thanks. I was confused because the example in that spec document doesn't show an array. I think the document Appendix A. needs to be updated to the correct array value.

**Comment by celic** [comment]
If the spec is incorrect here, then it needs to be corrected. Feel free to submit a PR if you are interested or have the opportunity.

**Comment by Kritner** [comment]
This seems to be resolved with @acronymhaterheidi's PR in #547
