### ISSUE TITLE
SHA3 server JSON contains incorrect "testType"

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#548]
The vector set for SHA3 (maybe SHAKE as well) has "testType": "aft" which is incorrect. 

**vsId**
3471

**Algorithm registration**
`[{"acvVersion":"0.5"},{"isSample":true,"algorithms":[{"algorithm":"SHA3-224","inBit":false,"inEmpty":true}]}]`

**Endpoint in which the error is experienced**
`GET https://demo.acvts.nist.gov:443/acvp//acvp/v1/testSessions/381/vectorSets/3471`

**Expected behavior**
The string value "aft" should be all capitalized to "AFT". This is according to the spec https://github.com/usnistgov/ACVP/blob/master/artifacts/draft-celi-sha3-00.txt

**Comment by Kritner** [comment]
This correction should be present in the next push to demo

**Comment by Kritner** [comment]
Pushed to demo. Let me know if there are any issues!
