### ISSUE TITLE
Review comments for draft-fussell-acvp-spec-00

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#553]
Section 3.0 - "an encoding and message format". To me encoding and format means how the message data is packed across the wire. Since JSON is used as the encoding/format maybe "JSON message structure" is more accurate? Just a thought

**Comment by fliphil** [comment]
Section 3.2 - "A validation authority SHALL use HTTPS [RFC7230], TLS 1.2 [RFC5246] or greater and mutual
authentication.". Clarifying phrase here would be "a combination of". Also in a sentence further below, "chose" should be corrected to "choose".

**Comment by fliphil** [comment]
Section 4 defines the roles of each entity. I think a sub-section that explains the usage of JSON for the message format (along with reference to RFC 7159) would be good. This would be good for the reader to know before reading about the roles, which being to reference JSON.

**Comment by fliphil** [comment]
In the section 4.4 "Prompt" represents the JSON sent from server to client that contains the vectorSet(s). I believe "request" should be swapped for "prompt" at lines 217, 475, 735 in order to be aligned with the terminology.

**Comment by celic** [comment]
In the description of the registration, we need to add the concept of "revision"... for example...
```
{
    "algorithm": "ACVP-AES-GCM",
    "revision": "1.0.0",
    "prereqVals": ...,
    "direction": ...
}
```

This is in line with the IANA document.

**Comment by bfussell** [comment]
@celic In section 10.10.4.1 ?

**Comment by celic** [comment]
Sorry I'm not sure the section number because I'm looking at the XML... Under `Request`, there's example JSON that would need a `"revision"` property after the `"algorithm"`. Basically everywhere `"algorithm"` is referenced in JSON, there would need to be an accompanying "`revision`" as an additional field.
