### ISSUE TITLE
Endpoint /algorithms painfully slow

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#556]
I am trying to fetch the current list of cipher and cipher options from the algorithms list. Whereas getting the list of algorithms from /agorithms works decently, getting the individual algorithm options from /algorithms/<NUMBER> is painfully slow.

I started an iteration over all definitions about 12 hours ago and yet got only 37 definitions.

**Comment by smuellerDD** [comment]
Strange, now it works with the performance expected.

**Comment by celic** [comment]
The server can be bottlenecked at times depending on who/what is hitting it. We have optimizations in the works (optimizations is probably an understatement here... 99%+ speed-ups in most cases), but aren't ready to release them yet. 

If you keep track of which algorithms seems to take a while to respond, that would help us with further improvements.

**Comment by smuellerDD** [comment]
Am Dienstag, 19. Februar 2019, 20:23:16 CET schrieb Chris Celi:

Hi Chris,

> The server can be bottlenecked at times depending on who/what is hitting it.
> We have optimizations in the works (optimizations is probably an
> understatement here... 99%+ speed-ups in most cases), but aren't ready to
> release them yet.

That is awesome! After deploying it, we should also engage in testing the 
limits of threading. As I have seen that you server seems to define a maximum 
number of concurrent threads below 32, we should explore how much we can 
increase the value without melting it.
> 
> If you keep track of which algorithms seems to take a while to respond, that
> would help us with further improvements.

My acvp-proxy keeps always track on all upload and download durations. Thus, 
we can review the duration at any time.

Ciao
Stephan
