### ISSUE TITLE
SHAKE server JSON test_case missing "outputLen"

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#562]
For both SHAKE128/SHAKE256, the vectorSet test_cases for VOT sent from server are missing the key/value pair of "outputLen".

**vsId**
4668, 4669

**Algorithm registration**
[{"acvVersion":"0.5"},{"isSample":true,"algorithms":[{"algorithm":"SHAKE-128","inBit":false,"inEmpty":true,"outBit":false,"outputLength":[{"min":16,"max":65536,"increment":8}]},{"algorithm":"SHAKE-256","inBit":false,"inEmpty":true,"outBit":false,"outputLength":[{"min":16,"max":65536,"increment":8}]}]}]

**Expected behavior**
The "outputLen" should be included in each VOT test_case to indicate the variable-output-length digest that the client is expected to produce.
According to spec: https://github.com/usnistgov/ACVP/blob/master/artifacts/draft-celi-sha3-00.txt

**Comment by Kritner** [comment]
This seems like it could be a specification update to be consistent with what the gen/vals are currently producing `outputLen` -> `outLen`. Hopefully that will be simpler from everyone's perspective since it will match what's currently being produced.

**Comment by smuellerDD** [comment]
This issue relates to #587 and does not only seem to be a spec issue.

**Comment by Kritner** [comment]
Hey @smuellerDD the spec was using "outputLen" instead of "outLen". The "outLen" was not being included in the VOT tests, which I believe is now fixed on demo.

However #587 is also valid, the `outLen` was not present in AFT tests either.

**Comment by smuellerDD** [comment]
Am Montag, 1. April 2019, 20:14:10 CEST schrieb Russ Hammett:

Hi Russ,

> Hey @smuellerDD the spec was using "outputLen" instead of "outLen". The
> "outLen" was not being included in the VOT tests, which I believe is now
> fixed on demo.

You are right: it is fixed for VOT, but AFT still misses the outLen
> 
> However #587 is also valid, the `outLen` was not present in AFT tests
> either.


Ciao
Stephan
