### ISSUE TITLE
EDDSA sigver: IUT / ACVP results mismatch

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#565]
The IUT successfully verifies a signature. The ACVP server, however, sometimes rejects this positive answer and expects that the signature verification should have failed.

Foir some sigver results with both, passing and failing verdicts, the IUT and ACVP agree.

Usually I would try to check the IUT for errors. But here the IUT states that a signature successfully verifies. This is highly improbable if the input data is modified. Thus, I would assume the ACVP server did not modify the test vector data even though it wanted to. Note, the IUT/ACVP inconsistencies only happen when the IUT says a signature successfully verifies and the ACVP server says it should fail.

The ACVP server answer is:

```
  }, {
    "tcId" : 3,
    "result" : "failed",
    "reason" : "modify r",
    "expected" : {
      "testPassed" : "False"
    },
    "provided" : {
      "testPassed" : "True"
    }
  }, {
    "tcId" : 4,
    "result" : "failed",
    "reason" : "modify s",
    "expected" : {
      "testPassed" : "False"
    },
    "provided" : {
      "testPassed" : "True"
    }
  }, {
    "tcId" : 5,
    "result" : "failed",
    "reason" : "modify r",
    "expected" : {
      "testPassed" : "False"
    },
    "provided" : {
      "testPassed" : "True"
    }
```

PS: I like very much the verbosity of the ACVP answers! Thanks.

vsID 5433, 5428,

**Comment by celic** [comment]
There are several reasons in EdDSA... "modify s", "modify message", "modify r", and "modify key"... Do you notice the error in all of these reasons? As well, just to confirm, signatures that ACVP says should succeed do succeed from your IUT? The issue only exists in signatures ACVP says should fail? Is it ALL of those signatures or only some?

**Comment by celic** [comment]
Hmm... I think I see the issue... it is only with the "modify r" and "modify s" cases. Consider this fixed in the new release.

**Comment by Kritner** [comment]
This was release to demo. Let me know if there are any issues.

**Comment by smuellerDD** [comment]
Am Montag, 1. April 2019, 15:37:06 CEST schrieb Russ Hammett:

Hi Russ,

> This was release to demo. Let me know if there are any issues.

confirmed, working

Ciao
Stephan
