### ISSUE TITLE
EDDSA key verification

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#566]
I am testing the EDDSA key verification. The ACVP server and my IUT do not agree on most results.

I am not aware that there is a full specification how the key verification shall be done (i.e. which tests are to be implemented), I am unsure where the error is. Note, I am using libsodium which is considered to be THE reference implementation of EDDSA (it is a direct derivative of the original libnacl from Bernstein). I am using crypto_core_ed25519_is_valid_point() with the provided Q value for the key verification. Unfortunately, libnacl does not seem to have a key verification function.

May I ask for the specification the ACVP server key verification implementation is based on?

**Comment by celic** [comment]
There are a few reasons for a key to be rejected... The ones we test are "point not on curve" and "out of range" (being that one of the coordinates is not in simplest form). 

In terms of our KeyVerification process, we follow the steps outlined in FIPS 186-5 which I'm not sure is available for comments yet. Essentially this process checks the private component `D` to ensure it is within the domain. Then it checks public point `Q` to make sure it is on the curve and not the neutral element `(0, 1)`. The last check on `Q` is to make sure when multiplied by the curve order, it leads to the neutral element (which should be true of any point on the curve really). 

Hopefully that helps. This is a bit awkward to work around when I can't find a public release of FIPS 186-5.

**Comment by smuellerDD** [comment]
I will close the issue and work with the developers on this issue. If we have further questions, I will open another ticket. Thanks.
