### ISSUE TITLE
RSA Typos and PSS SaltLen Question

### ISSUE THREAD

**Issue by acronymhaterheidi** [usnistgov/ACVP#569]
The examples in A.1, A.2, and A.3 in the RSA spec are invalid json (missing or additional commas). 

Additionally, I am a little confused by the notes regarding the saltLen for sigGen, sigVer, and legacySigVer. The notes for the three of them are:

* sigGen: Note: the salt length for each hash algorithm used in PSS signature generation is between 0 and the length of the corresponding hash function output block (in bytes), the end points included.

* sigVer: Note: the salt length for each hash algorithm used in PSS signature generation is between 0 and the length of the corresponding hash function output block (in bytes), the end points included. The exception to this rule is using "SHA2-512" with a modulo of 1024. The maximum salt length for this combination is 62 bytes instead of the expected 64 bytes.

* legacySigVer: Note: the salt length for each hash algorithm used in PSS signature generation is between 0 and the length of the corresponding hash function output block (in bytes), the end points included.

All three of them reference signature generation and sigVer has a different rule than the others. Section 5.5 of 186-4 did not clarify if this only applies to signature generation (I am not very familiar with PSS). All three of the examples have 64 as a saltLen for SHA2-512. 

Lastly, is the legacySigVer capabilities table outdated? It has hashPair, hashAlg, and saltLen all as arrays, which does not make very much sense. The example for legacySigVer does not have a hashPair key.

**Comment by acronymhaterheidi** [comment]
Taking another look at 186-4, it looks to me that 0 ≤sLen ≤hLen – 2 for generation and verification. Which would I believe mean that the examples should have 62 as a salt length rather than 64.

**Comment by celic** [comment]
As far as I know, this is only the case for a modulo of 1024 bits for signature verification (because there is no signature generation for 1024 anymore). Larger modulo sizes can receive the full 64 byte salt.

**Comment by acronymhaterheidi** [comment]
Whoops, a total failure of reading comprehension, sorry.

**Comment by acronymhaterheidi** [comment]
A.1, A.2 and A.3 still have invalid json examples

**Comment by acronymhaterheidi** [comment]
I also do think that either (or both) the capabilities table for legacySigVer are incorrect. The table includes hashPair, hashAlg and saltLen all as arrays rather than hashPair as an array with objects consisting of hashAlg and saltLen properties. 

The example does not include hashPair, just hashAlg and saltLen arrays on the same level as modulo, which contradicts the capabilities table.
