### ISSUE TITLE
SHAKE generation of test vectors failed

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#582]
**testSessionId**
18428, 18429

Server reply:

```
[ {
  "acvVersion" : "0.5"
}, {
  "vsId" : 18428,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 18428"
} ]
```

**Comment by Kritner** [comment]
@smuellerDD here's your registration:

```json
{"vsId":18428,"isSample":false,"algorithm":"SHAKE","inBit":false,"inEmpty":true,"outBit":false,"outputLength":[{"min":16,"max":65536,"increment":1}],"digestSize":["128"]}
```

according to the current implementation, a increment of 1 on the outputLength is only valid for `"inBIt": true`.  When `inBit` is false, mod 8 is expected.

**Comment by smuellerDD** [comment]
Am Montag, 1. April 2019, 15:19:24 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD here's your registration:
> 
> ```json
> {"vsId":18428,"isSample":false,"algorithm":"SHAKE","inBit":false,"inEmpty":t
> rue,"outBit":false,"outputLength":[{"min":16,"max":65536,"increment":1}],"di
> gestSize":["128"]} ```
> 
> according to the current implementation, a increment of 1 on the
> outputLength is only valid for `"inBIt": true`.  When `inBit` is false, mod
> 8 is expected.

Ahh, the increment *is* needed. The Shake spec and the answers regarding the 
domain led me believe that only min/max is needed. So I guess I need to set 
increment to 8.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Montag, 1. April 2019, 15:19:24 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD here's your registration:
> 
> ```json
> {"vsId":18428,"isSample":false,"algorithm":"SHAKE","inBit":false,"inEmpty":t
> rue,"outBit":false,"outputLength":[{"min":16,"max":65536,"increment":1}],"di
> gestSize":["128"]} ```
> 
> according to the current implementation, a increment of 1 on the
> outputLength is only valid for `"inBIt": true`.  When `inBit` is false, mod
> 8 is expected.

confirmed, working.

Ciao
Stephan
