### ISSUE TITLE
values for payloadLen, aadLen for AES-GCM

### ISSUE THREAD

**Issue by n3rddud3** [usnistgov/ACVP#583]
Hi I'm a bit confused with the draft, which describes the Capabilities JSON fields payloadLen/aadLen in min/max/inc format.  Do we use this format, or do we need to explicit specify 5 values, which are {0, 2 values of mod 128, 2 values of non-mod-128}?  Thanks.

**Comment by smuellerDD** [comment]
Am Donnerstag, 28. März 2019, 18:50:40 CET schrieb n3rddud3:

Hi n3rddud3,

> Hi I'm a bit confused with the draft, which describes the Capabilities JSON
> fields payloadLen/aadLen in min/max/inc format.  Do we use this format, or
> do we need to explicit specify 5 values, which are {0, 2 values of mod 128,
> 2 values of non-mod-128}?  Thanks.

Please see the definition of a "Domain" in section 15.4 of the ACVP spec.

A domain has two representations: either with min/max/inc representation or 
with an array of allowed parameters.

Ciao
Stephan

**Comment by Kritner** [comment]
@n3rddud3 did @smuellerDD's give you everything you need? I'll close this for now, but please feel free to update if the provided documentation is unclear.
