### ISSUE TITLE
SHAKE: test vector misses outLen?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#587]
The ACVP server produced the following test vector:

```
  "vsId" : 18957,
  "algorithm" : "SHAKE-256",
  "isSample" : false,
  "testGroups" : [ {
    "tgId" : 1,
    "tests" : [ {
      "tcId" : 1,
      "msg" : "",
      "len" : 0
    }, {
      "tcId" : 2,
      "msg" : "ED",
      "len" : 8
    }, {
      "tcId" : 3,
      "msg" : "F515",
      "len" : 16
    }, {
```

According to the spec, I would expect outLen somewhere to know the message digest size to produce.

**Comment by Kritner** [comment]
This fix has been deployed to demo.  Let me know if there are any issues.

**Comment by smuellerDD** [comment]
confirmed, fixed.

But I reopened the issue as the SPEC contains still references to "outputLen:

**Comment by smuellerDD** [comment]
For the SHAKE MCT, we need two values: the MinOutBytes and the MaxOutBytes according to the SHA3 CAVS definition. Where would we find those? I guess the MaxOutBytes is outLen/8 provided by the vector. But MinOutBytes?

**Comment by Kritner** [comment]
I opened a new issue for your previous comment, will try to take a look at that shortly, but didn't want to lose track of it in this issue.

The `outputLen` vs `outLen` was just a failure to regenerate artifacts in the recent PR, that has been corrected.
