### ISSUE TITLE
Paging: next pointer does not advance

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#589]
I am starting with the paging work. For testing, I am trying the HTTP GET operation of the /vendors endpoint.

I start with

```
GET /acvp/acvp/v1/vendors HTTP/1.1
```

The server returns"

```
[ {
  "acvVersion" : "0.5"
}, {
  "totalCount" : 10582,
  "incomplete" : true,
  "links" : {
    "first" : "/acvp/v1/vendors?offset=0&limit=20",
    "next" : "/acvp/v1/vendors?offset=20&limit=20",
    "prev" : null,
    "last" : "/acvp/v1/vendors?offset=10580&limit=20"
  },
  "data" : [ {
    "url" : "/acvp/v1/vendors/1"
...
```

I use the next pointer for the next GET request:

```
GET /acvp/acvp/v1/vendors?offset=20&limit=20 HTTP/1.1
```

The server responds:

```
[ {
  "acvVersion" : "0.5"
}, {
  "totalCount" : 10582,
  "incomplete" : true,
  "links" : {
    "first" : "/acvp/v1/vendors?offset=0&limit=20",
    "next" : "/acvp/v1/vendors?offset=20&limit=20",
    "prev" : null,
    "last" : "/acvp/v1/vendors?offset=10580&limit=20"
  },
  "data" : [ {
    "url" : "/acvp/v1/vendors/1",
    "name" : "STMicroelectronics",
```

You see that the next pointer does not advance. So I am stuck in an endless loop.

**Comment by smuellerDD** [comment]
Am Montag, 1. April 2019, 22:32:40 CEST schrieb Harold Booth:

Hi Harold,

> @smuellerDD I just double-checked manually and everything is working as
> expected. Can you confirm that you are calling the url with the correct
> parameters?

First request uses https://demo.acvts.nist.gov:443/acvp/acvp/v1/vendors

Next pointer: /acvp/v1/vendors?offset=20&limit=20
Prev pointer: null

2nd request uses https://demo.acvts.nist.gov:443/acvp/acvp/v1/vendors?
offset=20&limit=20

Next pointer: /acvp/v1/vendors?offset=20&limit=20
Prev pointer: null

The data array of the first and 2nd request contains the same information.


PS: The used URLs are confirmed by a debug printf as well as by the debug log 
from libcurl.

Ciao
Stephan

**Comment by smuellerDD** [comment]
It seems the server does not honor the parameters at all. For testing, I used the "last" pointer data with the URL of https://demo.acvts.nist.gov:443/acvp/acvp/v1/vendors?offset=10580&limit=20. Yet, the data the ACVP server returns is the first page.

**Comment by hbooth** [comment]
I am able to get the appropriate response by manually visiting the server (I even used your link above). If you could send me an email (not through git) with your IP address, I can take a look at the logs and see what you are passing in.

**Comment by hbooth** [comment]
Following up on this, I just looked and can see your requests. From the logs it appears the requests are coming in fine. Are you able to confirm the output from each request?

**Comment by smuellerDD** [comment]
Palmface. Please disregard my noise. I did not free the buffer that is intended to hold the incoming request. My network handler in this case will simply realloc the buffer to extend it.

So, after freeing to to prevent a realloc, but have a pure malloc, I see the subsequent pages.
