### ISSUE TITLE
POST to /vendor forbidden?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#590]
```
POST /acvp/acvp/v1/vendors HTTP/1.1
```

returns HTTP/1.1 403 Forbidden

```
{
  "acvVersion" : "0.5",
  "error" : "The current user is not authorized for the requested action."
}
```

Is that intended?

**Comment by hbooth** [comment]
did you supply a jwt?

**Comment by smuellerDD** [comment]
Yes:

```
> POST /acvp/acvp/v1/vendors HTTP/1.1
Host: demo.acvts.nist.gov
User-Agent: ACVPProxy/0.6.6
Accept: */*
Content-Type: application/json
Authorization: Bearer  ...
Content-Length: 189

* upload completely sent off: 189 out of 189 bytes
* old SSL session ID is stale, removing
< HTTP/1.1 403 Forbidden
```

**Comment by hbooth** [comment]
I found the problem. We need to configure your account. The error is accurate. You are not currently authorized for that action. Once it is set-up I will let you know.

**Comment by hbooth** [comment]
try now

**Comment by smuellerDD** [comment]
Ok, I was able to upload.

The server returns the status of "initial". How is the actual workflow from here on? Is the client expected to poll or is there a manual step required?

**Comment by hbooth** [comment]
There is a manual step on the backend for our implementation at the moment, so please don't poll. We plan to add a notification back to the user to let them know it was successful.

**Comment by hbooth** [comment]
I just accepted your submission and you should now see what an accepted response should look like

**Comment by smuellerDD** [comment]
What would be expected process be? Something like this:

1. HTTP POST of new data

2. store the request URL unless the status indicates success

3. wait for NIST to manually indicate that the request is approved

4. HTTP GET the request URL to fetch a success status and the new resource URL

?

**Comment by hbooth** [comment]
something like that. The expectation is that users will use what is already there where it exists, and that once a steady state is reached data creation and manipulation will occur at a relatively minimal rate. If we that assumption is proved wrong (which is quite possible) we will need to adjust some things on the back end to alleviate any bottlenecks.

**Comment by smuellerDD** [comment]
I got the message. But the server returns "approved" whereas the spec says "accepted.

**Comment by hbooth** [comment]
Spec is incorrect...i'll fix it now...

**Comment by hbooth** [comment]
fix merged into spec
