### ISSUE TITLE
SPEC: 10.7.3.1 contactUrl -> Url

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#594]
The address URL obtained via /vendor is marked with the keyword Url.

**Comment by smuellerDD** [comment]
section 10.9.2.1: example: name -> fullName

**Comment by hbooth** [comment]
contactsUrl within the vendor object looks to be ok. What's the issue?

the url keyword within the address object is intentional since the url is in the context of the address object.

fixed examples to use `fullName` instead of `name`

sidenote: section numbers changed recently, so please be sure to look at the master branch

**Comment by smuellerDD** [comment]
Am Mittwoch, 3. April 2019, 14:58:08 CEST schrieb Harold Booth:

Hi Harold,

> contactsUrl within the vendor object looks to be ok. What's the issue?

The server returns it as "url". I see no contactsUrl from the server.
> 
> the url keyword within the address object is intentional since the url is in
> the context of the address object.
> 
> fixed examples to use `fullName` instead of `name`
> 
> sidenote: section numbers changed recently, so please be sure to look at the
> master branch

Ok, will go to master now.


Ciao
Stephan

**Comment by hbooth** [comment]
This is the ouput I see for a vendor right now:
```json
{
    "url" : "/acvp/v1/vendors/2",
    "name" : "Thales e-Security",
    "website" : "www.thalesesec.com",
    "emails" : [ ],
    "phoneNumbers" : [ ],
    "contactsUrl" : "/acvp/v1/vendors/2/contacts",
    "addresses" : [ {
      "url" : "/acvp/v1/vendors/2/addresses/2",
      "street1" : "2200 North Commerce Parkway",
      "street2" : "Suite 200",
      "street3" : null,
      "locality" : "Weston",
      "region" : "Weston",
      "country" : "USA",
      "postalCode" : "33326"
    } ]
  }
```

contactsUrl could be missing in the event that a vendor has no contacts.

**Comment by smuellerDD** [comment]
Sorry, I mixed up the contactUrl and the url in the address field. Please disregard this issue.

Close the issue at your discretion after the other update is completed.

**Comment by hbooth** [comment]
spec was updated earlier today

**Comment by hbooth** [comment]
All updates are on master branch now: https://github.com/usnistgov/ACVP/blob/master/artifacts/draft-fussell-acvp-spec-00.html
