### ISSUE TITLE
Where is new endpoint documentation?

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#598]
Hello,

I'm wondering is there a doc or update to a spec that outlines the new oes, vendors, modules, and dependencies endpoints? Also am I missing any other endpoints from that list?

I've been using the main spec as a guide, but that appears to be outdated according to the Server error messages that my client is receiving.

Thanks,
Phil

**Comment by fliphil** [comment]
Oh wait, I see the file was updated 7 hour ago... I'll take a look and let you know if that doesn't answer my questions!

**Comment by hbooth** [comment]
yeah, we have been updating the spec to document the updates.

The spec should be feature complete now for what we are intending to start with. We will continue to add clarifications and fix any shortcomings.

For anyone else wondering the documentation can be viewed here:

https://github.com/usnistgov/ACVP/blob/master/artifacts/draft-fussell-acvp-spec-00.html
