### ISSUE TITLE
Authentication failure: "vsId was not found in the JWT"

### ISSUE THREAD

**Issue by mikolaj-Rianta** [usnistgov/ACVP#599]
I've been trying to post results and I'm getting the following response:
{
  "acvVersion" : "0.5",
  "error" : "vsId was not found in the JWT"
}
It all worked 2 hours ago;

Instead of using the access token from login I've tried to set the header's "Bearer" values to the access token I got from when I registered my session but didn't work either. The response was as follows:
{
  "acvVersion" : "0.5",
  "error" : "JWT expired at 2019-04-03T15:24:50Z. Current time: 2019-04-03T15:41:42Z, a difference of 1012156 milliseconds.  Allowed clock skew: 0 milliseconds."
}

**Comment by hbooth** [comment]
The latest push closed a loophole where the JWT claims were not being properly checked. You should use the accessToken you received from registering your session to interact with the session moving forward.
Once the JWT has expired (like the above) you will need to use the /login endpoint to "renew" your JWT token by sending in the accessToken (See the Login section currently labeled as Section 9) and then using the "renewed" accessToken in the response from the login to again interact with that session.

**Comment by mikolaj-Rianta** [comment]
Harold,
Thanks very much! All is working fine now.

**Comment by hbooth** [comment]
Glad to hear that. Closing this now.
