### ISSUE TITLE
For the SHAKE MCT, we need two values: the MinOutBytes and the MaxOutBytes according to the SHA3 CAVS definition. Where would we find those? I guess the MaxOutBytes is outLen/8 provided by the vector. But MinOutBytes?

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#601]
For the SHAKE MCT, we need two values: the MinOutBytes and the MaxOutBytes according to the SHA3 CAVS definition. Where would we find those? I guess the MaxOutBytes is outLen/8 provided by the vector. But MinOutBytes?

_Originally posted by @smuellerDD in https://github.com/usnistgov/ACVP/issues/587#issuecomment-479809600_

**Comment by Kritner** [comment]
Maybe @celic can confirm, but it looks like the min/max out bytes is equivalent to the provided `outputLength` (but its byte equiv) from the capabilities registration.

**Comment by smuellerDD** [comment]
Well, I do not see the min value in the test vector. So, it should be there to prevent guessing.

**Comment by celic** [comment]
The domain for SHAKE is required to just express a minimum and a maximum. The values for MCT are pulled from there. If they are not put into the JSON, then that could be an error.

**Comment by celic** [comment]
From what I see, there aren't any test group properties for SHA3/SHAKE being sent in the prompt files. That is definitely a bug. For the values for MCT, I am adding `minOutputLength` and `maxOutputLength`. This should go out with the next release.

**Comment by smuellerDD** [comment]
Am Donnerstag, 4. April 2019, 23:13:05 CEST schrieb Chris Celi:

Hi Chris,

> From what I see, there aren't any test group properties for SHA3/SHAKE being
> sent in the prompt files. That is definitely a bug. For the values for MCT,
> I am adding `minOutputLength` and `maxOutputLength`. This should go out
> with the next release.

Just a nit: The keyword for output length is outLen. Thus, wouldn't you want 
to use maxOutLen and minOutLen?

Ciao
Stephan

**Comment by celic** [comment]
Will do. Thanks.

**Comment by Kritner** [comment]
This has been deployed to demo.  Let us know if there are any issues.
