### ISSUE TITLE
Change ACVP version for server implementation from 0.5 -> 1.0

### ISSUE THREAD

**Issue by hbooth** [usnistgov/ACVP#606]
As we are approaching the finish-line on the spec with the last few changes to include `revision` as part of the algorithm definition we will need to update the ACV protocol version from 0.5 to 1.0. Clients will need to be aware of this in order to gracefully handle the transition.

**Comment by smuellerDD** [comment]
There are open issues: SHAKE MCT for one.

Thus, do you want to have those protocol issues closed before 1.0 is announced? There is at least a potential that the SHAKE definition needs to be adjusted.

From the client side: thanks for the warning, I will be ready.

**Comment by Kritner** [comment]
> There are open issues: SHAKE MCT for one.

@smuellerDD did you see:
https://github.com/usnistgov/ACVP/issues/601#issuecomment-479859022

does that suffice?  I don't know much about the shake MCT, but at a glance it looks like the registration constrains the MCT test already.

**Comment by Kritner** [comment]
This has been deployed to demo.  Let us know if there are any issues.
