### ISSUE TITLE
Insufficient JWT claim provided for vsId

### ISSUE THREAD

**Issue by mikolaj-Rianta** [usnistgov/ACVP#607]
I was trying to get expected results for test session 2655 vector set 19612; in response I got the following:
{
  "acvVersion" : "0.5",
  "error" : "Insufficient JWT claim provided for vsId"
}

Test session 2655 was created yesterday Apr 3, 2019 before the server update.
I've no problem getting expected results for vector set belonging the test session I created today: testSession 2733, vectorId 19750

**Comment by mikolaj-Rianta** [comment]
BTW I'm getting the same behavior when I try to post my results

**Comment by hbooth** [comment]
The accessToken is specific to the testSession it is associated with.

I almost forgot, accessTokens before the update are not compatible with ones before the update. Apologies, for not relaying that information earlier.

**Comment by fliphil** [comment]
Are you sure this issue is resolved? I got this error when trying to get the vector set to run:
***ACVP [ERR][log_network_status:748]--> {
  "acvVersion" : "0.5",
  "error" : "vsId was not found in the JWT"
}

**Comment by mikolaj-Rianta** [comment]
"error" : "vsId was not found in the JWT" was resolved by following the new login procedure where you add the "accessToken" from the session registration into /login PUT

"error" : "Insufficient JWT claim provided for vsId" is when you try to access sessions created before Apr 3, 2019 server update

That is how things have been explained to me and, since Apr 3, 2019, I've been able to create mutiple test aessions, get and submit vectors. One of the sessions (2798) is ready for certification now

**Comment by fliphil** [comment]
Hello @mikolaj-Rianta this is the flow that our client has been following for many months now. The server sends over the JWT in the HTTP header "Authorization: Bearer <token>". Are you saying that something else has changed? The error makes me think that the server expects the vector-set ID to be included in the JWT?

**Comment by mikolaj-Rianta** [comment]
what I was trying to say that I've not seen 'vsId was not found in the JWT' since (based on Harold's advice) I've been adding testSession's accessToken to my login POST  content while trying to access testSession related resources.
The vector-set ID in the error message must have been there because I was trying to access vestorSet resources (just a guess)

**Comment by fliphil** [comment]
I think I see now, the JWT provided in the reponse from POST /login is used to register. Then the response from registering at POST /testSessions containers another "accessToken" which must then be used for that session going forward.
