### ISSUE TITLE
Utilize build system to manage artifacts?

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#608]
We may be able to utilize Travis-CI or something similar to take in the "/src/*.xml" files and build them with `xml2rfc`.  

Building the src files in such a manner would allow a few things:
* No more merge conflicts due to ".txt" and ".html"
* No more having to run the artifact generation locally (though it would still be a good idea to make sure it will pass on the PR
* Automatic updates to artifacts on the github pages

This would likely require some additional permissions and/or tokens set up on the NIST github, but I think would be a good change.

There's probably additional benefits, but this could be a quality of life change to implement at some point, time permitting.

**Comment by celic** [comment]
This would be very good for PRs as well. We can have a tool checkout the branch and run the `xml2rfc` tool to determine if a PR is capable of producing artifacts properly.

**Comment by Kritner** [comment]
Ah right, I totally meant to put that in as a bullet point 👍

**Comment by celic** [comment]
This is largely done. We just need to remove the artifacts from the master branch as they are no longer needed.
