### ISSUE TITLE
DNS issues

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#612]
Not sure whether this is an ACVP problem, but I report it anyways: demo.acvts.nist.gov is not well resolved via DNS. Funnily, the dig command resolves it always. Tools like libcurl does not. Dig shows a massive DNS entry.

When adding the IP address to the /etc/hosts file (preventing a DNS resolution), all works, but now the ACVP server has an issue:

```
{
  "acvVersion" : "0.5",
  "error" : "Unable to locate gov.nist.cvp.validation.model.Address with id: 10586"
}
```

**Comment by smuellerDD** [comment]
The DNS entry of demo.acvts.nist.gov seems to be resolved again, but the aforementioned error from the ACVP server remains.

**Comment by hbooth** [comment]
What resource are you attempting to access?
The error message is trying to indicate that the `Address` resource with id 10586 could not be found, which indicates an error with the request. The extra information around address `gov.nist.cvp.validation.model.` is unnecessary and I will remove that.

**Comment by smuellerDD** [comment]
Am Montag, 8. April 2019, 17:59:35 CEST schrieb Harold Booth:

Hi Harold,

> What resource are you attempting to access?
> The error message is trying to indicate that the `Address` resource with id
> 10586 could not be found, which indicates an error with the request. The
> extra information around address `gov.nist.cvp.validation.model.` is
> unnecessary and I will remove that.

I am trying to POST the following to /modules

```
  {
    "name":"OpenSSL (64 bit) (AESNI_AVX)",
    "version":"1.1.0",
    "type":"Software",
    "vendorUrl":"/acvp/v1/vendors/10646",
    "addressUrl":"/acvp/v1/vendors/10646/addresses/10586",
    "contactUrls":[
      "/acvp/v1/persons/14125"
    ],
    "description":"OpenSSL library implementation providing cryptographic 
services to Linux user space software components. The module was tested with 
64 bit word size."
  }
```



Ciao
Stephan

**Comment by smuellerDD** [comment]
With the new error message, bug on my side found. No issue on ACVP server
