### ISSUE TITLE
Manual update and /modules endpoint

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#613]
The metadata endpoints for /vendors, /oes, /dependencies and /persons are (rightfully) expected to cover rather static data. Thus, a manual verification by NIST seems appropriate.

Yet, for the /module endpoint this assumption is not correct. In fact, it is quite unlikely that you will every have to requests with the same module. The reason is (at least) the version number. One vendor will commonly only register a newer version (unless it is a 1A or 1B SUB - both are rather marginal in number). Thus, I would fear that a manual step here may provide significant hiccups:

- NIST will constantly chase register requests

- Vendors / labs always have to wait for the manual approval

**Comment by bfussell** [comment]
TBH, if you're going to have to do manual verification at each of those levels of the registration it might as well be moved out of the protocol. It's no longer "automated". Your first bullet is my biggest concern, how long will we have to wait from registration submission until we can actually complete the submission ? How long will we have to retain state(when the verifier goes on vacation) ? These new manual steps are putting a bottle neck back in the process.

Personally I do see oes/ dependencies/ and persons/ changing/growing some.  Especially in the case of adding oes/. We continually get algorithm test requests for CC to add oes/ to existing modules. I don't think they will be as static as the vendor/, at least not in our case.

**Comment by bfussell** [comment]
@fliphil @hbooth @atvassilev @smuellerDD My concerns comes down to 3 issues.  First is the duplicates which must be managed by the server. They should not exist and I think that's well understood and would help tremendously with the other 2 items.

Second is what was discussed in in the last few comments in #609. Why does the client need to walk the server DB ? Shouldn't there be a way to easily obtain /vendor, /module, etc. with some sort of "find" request ? 

The final item is a bit more involved and surrounds the automatic acceptance of the meta-data. I'd like some more discussion on when the human acceptance is performed on the meta-data. Is it really necessary before publication on the validation website ? And is it really needed on the demo server at all ? 

I feel like these items need to be flushed out prior to production roll out.

**Comment by atvassilev** [comment]
@bfussell, I hear you. Let's discuss this on a call this week. I can schedule a call if we can agree on time. Thursday, 09:00-10:00 or 13:00-17:00, Friday, 09:30-10:30 or 15:30-17:00 work for me. Please let me know what works for you and suggest appropriate people to add to the discussion.

**Comment by bfussell** [comment]
@atvassilev Thursday 9-10 sounds good. Philip, Sam, Michael and myself from our side.. Thanks !

**Comment by smuellerDD** [comment]
As this issue has been discussed, let us close the issue
