### ISSUE TITLE
unknown algorithm: SHA-1 with mode: null

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#616]
I'm getting this error when sending over the following registration.

[{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"SHA-1","revision":"1.0.0","messageLength":[{"min":0,"max":65528,"increment":8}]},{"algorithm":"SHA2-224","revision":"1.0.0","messageLength":[{"min":0,"max":65528,"increment":8}]},{"algorithm":"SHA2-256","revision":"1.0.0","messageLength":[{"min":0,"max":65528,"increment":8}]},{"algorithm":"SHA2-384","revision":"1.0.0","messageLength":[{"min":0,"max":65528,"increment":8}]},{"algorithm":"SHA2-512","revision":"1.0.0","messageLength":[{"min":0,"max":65528,"increment":8}]}]}]

The draft-celi-acvp-sha-00 doesn't say anything about needing a "mode" value.

**Comment by ABUBSHAIT** [comment]
I'm getting the same error with AES-ECB. I tried using "AES-ECB" and "ACVP-AES-ECB", but I get the same error.

[{"acvVersion":"1.0"},{"isSample":true,"algorithms":[{"algorithm":"ACVP-AES-ECB","revision":"1.0.0","direction":["encrypt"],"keyLen":[128]}]}]

Error: Incorrectly formatted JSON (1:140): unknown algorithm: ACVP-AES-ECB with mode: nullStaTUS???==>400

**Comment by hbooth** [comment]
it's should be just `1.0` for the revision

**Comment by ABUBSHAIT** [comment]
Confirming that it works. I changed revision to 1.0 and algorithm to "AES-ECB".

[ {
  "acvVersion" : "1.0"
}, {
  "isSample" : true,
  "algorithms" : [ {
    "algorithm" : "AES-ECB",
    "revision" : "1.0",
    "direction" : [ "encrypt" ],
    "keyLen" : [ 128 ]
  } ]
} ]

Thanks Harold.

**Comment by fliphil** [comment]
Okay, that seemed to work for me as well.
