### ISSUE TITLE
testSession "passed" is null

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#618]
**testSessionId**
2997

**vsId**
20593

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443//acvp/v1/testSessions/2997/results GET

Hello, the JSON that I receive:
```json
[ {
  "acvVersion" : "1.0"
}, {
  "passed" : null,
  "results" : [ {
    "vectorSetUrl" : "/acvp/v1/testSessions/2997/vectorSets/20593",
    "status" : "incomplete"
  }, {
    "vectorSetUrl" : "/acvp/v1/testSessions/2997/vectorSets/20592",
    "status" : "incomplete"
  }, {
    "vectorSetUrl" : "/acvp/v1/testSessions/2997/vectorSets/20591",
    "status" : "incomplete"
  }, {
    "vectorSetUrl" : "/acvp/v1/testSessions/2997/vectorSets/20590",
    "status" : "incomplete"
  }, {
    "vectorSetUrl" : "/acvp/v1/testSessions/2997/vectorSets/20589",
    "status" : "incomplete"
  } ]
} ]
```

As you can see, the "passed" value is null. This isn't valid JSON. A boolean can only be "true" or "false". If the intent is to communicate that the overall testSession status is incomplete, then the field should be "status" : "incomplete" instead.

**Comment by hbooth** [comment]
I am a bit unsure how to resolve this. `null` is a perfectly acceptable value for any property. See: http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf or https://json.org.

The section in the ACVP spec which describes the output for this operation is one of the earliest sections and is very much under specified, and this section of code hasn't changed in quite some time. Given all of that, I do understand that the output violates the principle of least surprise.

For lack of a better option, currently, null, is intended to communicate that the testSession is incomplete, but I can certainly always output false if that's what is desired here. If the only thing someone wants to know is pass/fail then I can update the output, but I would suggest the spec be updated to better specify the contract of the output to avoid any future surprises.

**Comment by hbooth** [comment]
To add-on to this, I can certainly be the one to document what it does now. I just want to be sure everyone will be happy with documentation that says something to the effect that:
```
passed: boolean, true if all vectors have passed, false if any vectors have not passed or are incomplete, a null if all vectors are currently incomplete.
```
the documentation could also be:
```
passed: boolean, true if all vectors have passed, false if any vectors have not passed or are incomplete
```
and i can update the code as well to make it agree

**Comment by fliphil** [comment]
I think having 3 different states is good (passed, fail, incomplete). I'm just not so sure that having the value set to null is the most clear way. Generally, it's not a good idea to mix value types, which is what using null here does. Usually, null is used to flag something as existing without any specific value attached i.e. implicit value.

**Comment by hbooth** [comment]
In SQL terms NULL generally means, "don't know" which is where this data derives.

Let's give this a day and see if anyone else wishes to opine.

But as an alternative to the current state:

```
status: string,
  - a "passed" value indicates all vectors have passed,
  - a "failed" value indicates that at least one vector has failed, and
  - a "incomplete" value indicates there are no vectors which have failed but not all vectors have been processed yet
```
