### ISSUE TITLE
SHAKE MCT: message length not according to SPEC

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#622]
After using also a sample test result, I got the SHAKE MCT working.

Yet, it only works correctly when I set the message length to 16 bytes (i.e. truncate it to the 16 leftmost bytes). The test vector provides a message of 32 bytes.

**Comment by smuellerDD** [comment]
After fixing my /large support I am able to upload the test response. The ACVP server does not like my MCT result because the msg part does not match. But as mentioned above, I would think that the ACVP server should apply a different msg.

**Comment by Kritner** [comment]
Hey @smuellerDD this seems like it's only an issue w/ shake-256, are you able to confirm this is not occuring with shake-128?

**Comment by smuellerDD** [comment]
It applies to SHAKE 128 too - the closed issue #623 implied that :-)

Let me clarify: the min/maxoutlen generates a new vlue for the SHAKE output length. That is generated, but only the leftmost 16 bytes are the next message.

Judging on the sample, the ACVP server seems to require that the msg entry in the MCT responses contain the entire SHAKE message digest length instead of the applied 16 bytes.

So, the issue is not only limited to the first test-vector-provided message, but all intermediate messages that are to be reported.

**Comment by smuellerDD** [comment]
Just FYI: the latest update fixes the initial message length, but not the intermediate message lengths.

**Comment by Kritner** [comment]
@smuellerDD I'm not very familiar with this MCT test so maybe you or @celic would be able to better confirm - it *looks* like we are using 128 bits of the previous digest as the next iteration's message, though this trimming of the digest is happening *after* the output stage.  

I'm thinking this means it's just an issue on our output, but shouldn't have an impact on the results of the run (since you can't use the message from each 1k iteration anyway).  Are you able to confirm this?

I see you have #564 out there as well - @celic do you see any issues with not including the message on the output?  Though the message could be viewed as a nice checkpoint value, I guess we'd need to output the correct value 👍

**Comment by smuellerDD** [comment]
Am Mittwoch, 10. April 2019, 14:32:14 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD I'm not very familiar with this MCT test so maybe you or @celic
> would be able to better confirm - it *looks* like we are using 128 bits of
> the previous digest as the next iteration's message, though this trimming
> of the digest is happening *after* the output stage.  
 
> I'm thinking this means it's just an issue on our output, but shouldn't have
> an impact on the results of the run (since you can't use the message from
> each 1k iteration anyway).  Are you able to confirm this?

The MCT works like the following:

1. calculate the SHAKE output length

2. create SHAKE with the given length

3. output the SHAKE message digest

4. take the 16 leftmost bytes from the SHAKE message digest as message for 
next round


It is expected that the message for the current round and its message digest 
are output at every 1000 iterations.

Now, what ACVP *seems* to require is that the message to be printed is the 
*full* message digest from the previous round and *not* just the 16 leftmost 
bytes.

Here you have a sample from the ACVP server:

```
{
        "msg" : 
"9E2DAB24815E0E998FCEC689D29329593108ABE9319006EFC76EC64D2F49235D24CADD8BE0D21837B6FC1F4....
        "md" : 
"CDDF2081AD3F363D6FD8D8B230746803E13CE966EDBD3E657744A5F64371311EB70926FACB06ADD823BFE098...
        "outLen" : 18584
      }
```

And here is the output I generate:

```
{
      "msg":"9e2dab24815e0e998fcec689d2932959",
      "md":"cddf2081ad3f363d6fd8d8b230746803e13ce966edbd3e657744a5f64371311eb7...
      "outLen":18584
    },
```

You see that the message digest is as expected, but the actual input message 
that I output (and apply to the SHAKE algo) is only the 16 leftmost bytes and 
not the full previous SHAKE.

And I think that is why the ACVP fails my results, since ACVP cannot match the 
message.

Thus, what the ACVP server should do is to simply truncate its expected 
message to the 16 leftmost bytes.
 
> I see you have #564 out there as well - @celic do you see any issues with
> not including the message on the output?  Though the message could be
> viewed as a nice checkpoint value, I guess we'd need to output the correct
> value 👍 
 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/usnistgov/ACVP/issues/622#issuecomment-481671054



Ciao
Stephan

**Comment by Kritner** [comment]
Ah gotcha! Sorry I didn't realize that we were also validating the "correct msg" in our validation process. I suppose that would prevent getting a success if we're validating against the incorrect checkpoint message.

**Comment by smuellerDD** [comment]
Am Mittwoch, 10. April 2019, 17:34:19 CEST schrieb Russ Hammett:

Hi Russ,

> Ah gotcha! Sorry I didn't realize that we were also validating the "correct
> msg" in our validation process. I suppose that would prevent getting a
> success if we're validating against the incorrect checkpoint message.

I think that is the case based on the error messages the ACVP server returns 
indicating that the "messages" are wrong.

Ciao
Stephan

**Comment by smuellerDD** [comment]
With the latest code drop removing the msg requirement, the SHAKE MCT works.
