### ISSUE TITLE
SHAKE: MCT sample incorrect?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#623]
When obtaining the sample for MCT, the msg buffer that is to be printed is always either the 32 byte input or the complete SHAKE output of the previous round. According to the SPEC (and as reported already), MCT requires the message to be exactly 16 bytes in size.

**Comment by Kritner** [comment]
@smuellerDD this can be attributed to the same underlying issue as #622.  This would seemingly only be impacting shake-256 as well, not shake-128.

I'll close this for now, it should be corrected with the #622 fix
