### ISSUE TITLE
GET / PUT /testSessions/{testSessionId}* fails

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#626]
I issue the following request: GET //acvp/v1/testSessions/2819

The server responds:

```
{
  "acvVersion" : "1.0",
  "error" : "Cannot properly validate tsId because the claim type isn't supported"
}
```

**Comment by smuellerDD** [comment]
Issuing a PUT with the following content to the aforementioned endpoint returns the same error:

```
{
  "moduleUrl":"/acvp/v1/modules/10584",
  "oeUrl":"/acvp/v1/oes/19621"
}
```

**Comment by hbooth** [comment]
If the testsession creation predates the last deployment you will receive this error. You will need to create a new testsession.

**Comment by smuellerDD** [comment]
I see, closing
