### ISSUE TITLE
SHA: generation of test vectors failed

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#629]
All SHA2 test vectors cannot be generated:

```
}, {
  "vsId" : 20893,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 20893"
} ]
```

vsIds 20893 through 20896

**Comment by Kritner** [comment]
@smuellerDD did your registrations change? or rather, have you had success with sha2 since after the `messageLength` was implemented?

looking at 20897 as an example:

```json
{
	"vsId": 20897,
	"isSample": false,
	"algorithm": "SHA2",
	"revision": "1.0",
	"messageLength": [0, 96, 128, 1024, 1036, 2040, 2048, 4088, 4096, 65536],
	"digestSize": ["512"]
}
```

The registration validation step checks that the digest size is a part of the `messageLength` domain, that does not appear to be the case in any of the registrations posted from this issue.

Ideally, you'd post your entire applicable domain within the messageLength object, such as with:

```json
{
  "messageLength": [{"min": 0,"max": 65335,"increment": 1}
}
```

I believe the requirement of the `messageLength` containing the digest size is a function of the testing.  Additionally, it looks like the cut off for the max registration is 65335, not 65336, though I'm not sure on the reasoning, @celic do you recall?

**Comment by smuellerDD** [comment]
Am Freitag, 12. April 2019, 14:08:13 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD did your registrations change?

Yes, I added messageLength.

> or rather, have you had success
> with sha2 since after the `messageLength` was implemented?

I have not checked it after that.


> The registration validation step checks that the digest size is a part of
> the `messageLength` domain, that does not appear to be the case in any of
> the registrations posted from this issue.

The registration was successful. So, I guess, the registration should have 
already failed.

And why would there be such a limit to require that there must be one 
messageLen == digestLen?
> 
> Ideally, you'd post your entire applicable domain within the messageLength
> object, such as with:
> 
> ```json
> {
>   "messageLength": [{"min": 0,"max": 65335,"increment": 1}
> }
> ```

I understand that this is the desired way (but I assume you meant increment of  
modulo 8 as I am only doing byte-wise).
> 
> I believe the requirement of the `messageLength` containing the digest size
> is a function of the testing.  Additionally, it looks like the cut off for
> the max registration is 65335, not 65336, though I'm not sure on the
> reasoning, @celic do you recall?

Ok, but again, shouldn't the registration catch that?

Ciao
Stephan

**Comment by Kritner** [comment]
> I understand that this is the desired way (but I assume you meant increment of
modulo 8 as I am only doing byte-wise).

Yes

> And why would there be such a limit to require that there must be one
messageLen == digestLen?

Currently the MCT test relies on the `digestSize` as a message size.  This does not always necessarily have to be the case, but it is currently.

>The registration validation step checks that the digest size is a part of
 the `messageLength` domain, that does not appear to be the case in any of
 the registrations posted from this issue.
>> The registration was successful. So, I guess, the registration should have
already failed.

> I believe the requirement of the `messageLength` containing the digest size
 is a function of the testing.  Additionally, it looks like the cut off for
 the max registration is 65335, not 65336, though I'm not sure on the
 reasoning, @celic do you recall?
>> Ok, but again, shouldn't the registration catch that?

Yes, ideally the client would get notified immediately upon attempted submission of a bad registration, and with details for the rejection.  Currently we have two separate capability registration validation processes, the first being sort of a "spot check", the second being more detailed.  This second check does not occur until after a response has been sent upon the initial capabilities registration.

We are looking into making the initial "spot check" the actual check, but have not yet done so.  It is on our list of things to do, to be sure.

**Comment by celic** [comment]
Yes a message length of 65536 should be valid. If it isn't then that is a bug. All those upper bounds should be nice round numbers. 

As well, the MCT assumes a message length is valid (might be 3x the digest size for the case of SHA1/2, I don't recall). 

Far down the road, we'd like to look at simplifying the MCTs in general and a specified message length could be a feature we look for in a new MCT format. (The original intention is to find a simple, easy to code 'shell' that can be easily applied to many algorithms that provides the same assurances as the current model.)

**Comment by smuellerDD** [comment]
Please note that I updated my register request to use a range domain as requested. Yet, the SHA generation fails.

test session 3124.

**Comment by Kritner** [comment]
@smuellerDD can you use 65528 as your max instead? Per @celic's previous message, it sounds like it's a bug that we're cutting off the max at 65535 instead of 65536

**Comment by smuellerDD** [comment]
Confirmed, working.

I am not sure, however, whether to keep that issue open.

**Comment by Kritner** [comment]
@smuellerDD 65536 should be supported now.

**Comment by smuellerDD** [comment]
Am Freitag, 19. April 2019, 15:18:44 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD 65536 should be supported now.

confirmed, working.

Ciao
Stephan
