### ISSUE TITLE
Switch KAT to some other term to avoid overloading

### ISSUE THREAD

**Issue by hbooth** [usnistgov/ACVP#63]
KAT is an existing term in other documentation and it would be desirable to switch the ACVP documentation to use another term/acronym that accurately communicates the test type while not colliding with other terms. My initial thought was something functional test, but any non-conflicting term is fine by me.

**Comment by bfussell** [comment]
So, Algorithm Functional Test (AFT) ?

**Comment by hbooth** [comment]
Works for me.

**Comment by atvassilev** [comment]
I like it too.

**Comment by celic** [comment]
Can this be closed then?

**Comment by bfussell** [comment]
Fine by me.
