### ISSUE TITLE
GET /testSessions/<ID>: inconsistent entries

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#631]
When issuing a GET on the testsession ID, I get the following for a module where I requested a HMAC and SHA and the SHA vectors failed to generate:

```
"publishable":true,"passed":null
```

I guess, the vector set should not be publishable?!

testsession: 3124

**Comment by hbooth** [comment]
The publishable flag is independent of the passed flag. The publishable flag only indicates whether the testSession is/will be publishable when `"passed": true`.

**Comment by smuellerDD** [comment]
Thanks for the clarification.
