### ISSUE TITLE
Feature request: GET /testSessions/<ID> should return certificate ID

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#632]
This is a feature request: once the final PUT on the /testSessions/<ID> is issued and the certificate is issued, may I recommend to add a field indicating the certificate ID? Otherwise, I would not know how one can query the server for the certificate ID.

**Comment by hbooth** [comment]
You can query the returned request id returned from the certify step (the PUT verb) for the validations record id.

**Comment by smuellerDD** [comment]
Am Freitag, 3. Mai 2019, 13:44:54 CEST schrieb Harold Booth:

Hi Harold,

> You can query the returned request id returned from the certify step (the
> PUT verb) for the validations record id.

Is this really the way to go? Shouldn't the testID have a flag containing this 
info in the very end? I through the request IDs are transient.

Ciao
Stephan

**Comment by hbooth** [comment]
The request id needs to be long-lived to allow requesters to obtain the status information. There is nothing in place that will prune the request ids. Perhaps at some later date it will be necessary to do so, but at the moment I don't think there is any need.

**Comment by smuellerDD** [comment]
Ok, then let us close this issue as there is a way to get the ID.
