### ISSUE TITLE
DSA pqgVer GDT: IUT and ACVP server disagree

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#635]
My IUTs for DSA pqgVer returns always pass. Naturally, the ACVP server disagrees. But it is quite unlikely that my IUT passes the verification if the vectors are fudged.

Note, this behavior is shown for OpenSSL and GnuTLS (I have not tested others).

Example: vsID 33301

**Comment by Kritner** [comment]
@smuellerDD I see an issue on our end regarding this, a fix should be in the next deploy.  Just confirming that as far as you can tell this issue only exists for PQ Ver, and not G Ver, correct?  Your IUT seemed to be picking out the "failure" tests on the G Ver side

**Comment by smuellerDD** [comment]
Am Montag, 22. April 2019, 22:00:58 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD I see an issue on our end regarding this, a fix should be in the
> next deploy.  Just confirming that as far as you can tell this issue only
> exists for PQ Ver, and not G Ver, correct?  Your IUT seemed to be picking
> out the "failure" tests on the G Ver side

Yes, the G ver tests are not affected, only PQ ver.

Ciao
Stephan

**Comment by Kritner** [comment]
This has been deployed to demo; let me know if there are any issues.
