### ISSUE TITLE
DSA sigver: spurious error during vector generation

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#636]
The ACVP server failed to generate a test vector for DSA sigVer.

Note, I generated many DSA sigVer vectors with idenical requests. But only for this one it failed.

vsID 32992

**Comment by celic** [comment]
Seems like a rare error... I'll see if i can replicate it locally but if you received it just once I'm not sure if I can. I can however add more tracking around where the error was reported. I _think_ that our system had trouble generating domain parameters for one of the groups causing it to error out unexpectedly.

**Comment by smuellerDD** [comment]
Am Dienstag, 23. April 2019, 19:43:06 CEST schrieb Chris Celi:

Hi Chris,

> Seems like a rare error... I'll see if i can replicate it locally but if you
> received it just once I'm not sure if I can. I can however add more
> tracking around where the error was reported. I _think_ that our system had
> trouble generating domain parameters for one of the groups causing it to
> error out unexpectedly.

I am just reporting it because that issue will be triggered again during 
production. Such errors, however, may decrease the acceptance.

Thus, what about you add some tracking around it and then you try to generate 
1000 test vectors of DSA sigver. My particular issue happened with 2048/224.

Ciao
Stephan

**Comment by celic** [comment]
That seems like what we will have to do. I'll work on this and see what I can dig up.

**Comment by smuellerDD** [comment]
I have another one: 34137

**Comment by celic** [comment]
I have added additional logging which will go out with Server v1.0.4 (hopefully Friday). When you see v1.0.4 is out there, fire away and we should get the information we need.

**Comment by smuellerDD** [comment]
Error: see vsID 36257

**Comment by smuellerDD** [comment]
Others: 37251, 36379

**Comment by celic** [comment]
What is the rate of error you are seeing for these? 1 out of 10? 100?

**Comment by smuellerDD** [comment]
Am Montag, 29. April 2019, 17:52:37 CEST schrieb Chris Celi:

Hi Chris,

> What is the rate of error you are seeing for these? 1 out of 10? 100?

Maybe 1 in 10 considering that I have only a few sigver requests per module.

Ciao
Stephan

**Comment by celic** [comment]
Thanks. The error logging we added in did not catch anything. I've added more and we will run this internally and see if we can reproduce an error with your registration.

**Comment by celic** [comment]
We've tracked down the error. Unfortunately it doesn't seem that straightforward a fix. Some asynchronous calls are being tied up while we try to generate the test cases. We will get this fixed and tested ASAP. Thank you for the information here.

**Comment by celic** [comment]
As a heads up, this would apply to any vector set with "complex" objects within the group properties. So anywhere that needs a key or domain parameters in the group properties could potentially crash due to this issue. DSA, RSA, EcDSA are the visible culprits. Our fix has tested well (no errors in 250+ iterations) and we are applying the fix to these other locations.

**Comment by celic** [comment]
This fix was deployed with the update to demo today. Please verify the fix.

**Comment by smuellerDD** [comment]
I downloaded a full set of OpenSSL vectors right now and have not seen any missing vectors so far.

Let us close the issue.
