### ISSUE TITLE
Feature request: GET /oes/ID shall return complete dependencies

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#638]
An OE can have multiple dependencies. When registering multiple dependencies with one OE POST, multiple dependencyUrls are returned. Now, one needs to assign the retrieved depUrls to the original dependencies for storage.

To support that, may I request that a GET /oes/ID returns the complete dependency definition to be functionally identical to a GET /vendor/ID which returns the addressUrl and the address?

**Comment by hbooth** [comment]
The change is easy to make on the server side (literally two lines). Any objections? @bfussell

**Comment by bfussell** [comment]
I'm good with that.

**Comment by hbooth** [comment]
Change has been made (and deployed out to demo). Still need to update the spec.

**Comment by Kritner** [comment]
This specification update was rolled out in recent metanorma conversion https://usnistgov.github.io/ACVP/draft-fussell-acvp-spec.html#name-retrieve-information-for-an
