### ISSUE TITLE
PUT /testsessions/ID/vectorsets/ID/results fails

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#639]
The PUT operation to update the vector set test results submission fails:

```
{
  "acvVersion" : "1.0",
  "error" : "Results for Vector Set id: 37824 cannot be updated with status: FAILED"
}
```

**Comment by hbooth** [comment]
The logic for this has been fixed up. Please try again.

**Comment by smuellerDD** [comment]
Am Dienstag, 21. Mai 2019, 20:47:19 CEST schrieb Harold Booth:

Hi Harold,

> The logic for this has been fixed up. Please try again.

Confirmed, working (both cases: already passed vectors cannot be updated, 
failed vectors can be updated).

Ciao
Stephan
