### ISSUE TITLE
How to obtain Validation Number

### ISSUE THREAD

**Issue by mikolaj-Rianta** [usnistgov/ACVP#640]
I've submitted two sessions for validation (PUT /testSessions/{testSessionId})
The test sessions (3017 and 3030) are close to being expired.
My requests (/requests/68 and /requests/69) both have "status" = "processing".

What else do I need to do in order to get a Validation Number?

**Comment by smuellerDD** [comment]
Ask Harold to approve your request :-)

**Comment by hbooth** [comment]
the latest deployment will make processing of the requests a bit easier. Please resubmit.
