### ISSUE TITLE
Feature request: Data search or filter

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#643]
Using Paging to find a specific item within thousands of records is very painful.

Can we have a feature to search a record by its properties?
For example, to search a vendor by using its name or its website.

**Comment by hbooth** [comment]
Coincidentally, I put out an outline of a proposal yesterday, which can be found here:

https://htmlpreview.github.io/?https://github.com/usnistgov/ACVP/blob/features/Query-Parameters/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.11.6

It's not yet implemented on the server, but it is the direction we are planning on going.

**Comment by AndrewHYang** [comment]
> Coincidentally, I put out an outline of a proposal yesterday, which can be found here:
> 
> https://htmlpreview.github.io/?https://github.com/usnistgov/ACVP/blob/features/Query-Parameters/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.11.6
> 
> It's not yet implemented on the server, but it is the direction we are planning on going.

Great! It definitely can be something very useful.
Looking forward to it.

Thanks!

**Comment by hbooth** [comment]
The pull request associated with the Query Parameters has been accepted and is now part of the master. The server has implemented the query parameters and this feature is available for testing
