### ISSUE TITLE
POST "vendor" metadata JSON error

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#644]
Hello,

I have a program that is trying to POST to the /vendors endpoint. This server is sending an error back:

{'acvVersion': '1.0', 'error': 'Incorrectly formatted JSON (1:157): Unknown field: phoneNumbers'}

This is the JSON that is being POSTed:

[{'acvVersion': '1.0'}, {'name': 'Acme Fictional Corporation', 'website': 'www.acme-fictional.com', 'emails': ['acme@acme-fictional.com'], 'phoneNumbers': [{'number': '000-000-0000', 'type': 'voice'}], 'addresses': [{'street1': 'Street', 'locality': 'Town', 'region': 'State', 'country': 'USA', 'postalCode': '00000'}]}]

Am I formatting the message incorrectly? The spec in section 11.7.2.1 example shows "phoneNumbers" as the field name.

Thanks!
Phil

**Comment by smuellerDD** [comment]
Am Dienstag, 7. Mai 2019, 00:54:46 CEST schrieb Philip Perricone:

Hi Philip,

> Hello,
> 
> I have a program that is trying to POST to the /vendors endpoint. This
> server is sending an error back:
> 
> {'acvVersion': '1.0', 'error': 'Incorrectly formatted JSON (1:157): Unknown
> field: phoneNumbers'}
> 
> This is the JSON that is being POSTed:
> 
> [{'acvVersion': '1.0'}, {'name': 'Acme Fictional Corporation', 'website':
> 'www.acme-fictional.com', 'emails': ['acme@acme-fictional.com'],
> 'phoneNumbers': [{'number': '000-000-0000', 'type': 'voice'}], 'addresses':
> [{'street1': 'Street', 'locality': 'Town', 'region': 'State', 'country':
> 'USA', 'postalCode': '00000'}]}]
> 
> Am I formatting the message incorrectly? The spec in section 11.7.2.1
> example shows "phoneNumbers" as the field name.

One that definitely worked was:

/vendors:

[
  {
    "acvVersion":"1.0"
  },
  {
    "name":"atsec corp.",
    "website":"www.atsec.com",
    "addresses":[
      {
        "street1":"9130 Jollyville Rd",
        "locality":"Austin",
        "region":"TX",
        "country":"USA",
        "postalCode":"78759"
      }
    ]
  }
]

and /persons

[
  {
    "acvVersion":"1.0"
  },
  {
    "fullName":"Stephan Müller",
    "vendorUrl":"/acvp/v1/vendors/10646",
    "emails":[
      "smueller@atsec.com"
    ],
    "phoneNumbers":[
      {
        "number":"+1-512-615-7300",
        "type":"voice"
      }
    ]
  }
]
> 
> Thanks!
> Phil



Ciao
Stephan

**Comment by fliphil** [comment]
@smuellerDD Thanks for the help. When I take off "phoneNumbers" as you have, it accepts the JSON. Maybe the spec needs to be updated if that field is really not allowed for /vendors. I'll continue with this fix until we get word from NIST.

**Comment by hbooth** [comment]
Thanks for pointing this out.

I just looked at this, and there was a mismatch in the implementation and the spec. I have updated the implementation to more closely match the spec. The fix will go out with the next update. I will need to adjust the spec slightly though, as we can only support a single voice and a single fax number on an organization; both can be provided.

**Comment by hbooth** [comment]
the fix for this has been deployed
