### ISSUE TITLE
Update capability registration functionality/partial CAVS testing

### ISSUE THREAD

**Issue by acronymhaterheidi** [usnistgov/ACVP#647]
With algorithm testing that is not currently in CAVS added to ACVP, will it be possible to add new capabilities to already validated implementations (i.e. an update request in CAVS parlance)? Forgive me if there is already mention of this in the documentation. 
In addition to updates to existing ACVP validations when new testing becomes available, we anticipate a situation during the transition period where some vendors may want to use CAVS for all of the algorithms that have available CAVS testing and use ACVP for algorithms that do not have CAVS testing. Since many vendors have existing implementations with CAVS test harnesses, they will not want to expend the development effort if it is not necessary to transition to the new format wherever possible. Will this be possible to do?
We anticipate that this will occur especially in the situation of SP 800-56A revision 3, for which there is not currently testing but which has a hard transition that has been published in a draft IG.

**Comment by celic** [comment]
Hi, I'll forward this along to Gavin. He's not on our GitHub at the moment, but will be the one making these decisions as Program Manager for the CAVP.

**Comment by acronymhaterheidi** [comment]
Thanks Chris

**Comment by gwobrien** [comment]
Hi Heidi,

Below is an answer sent to me from Harold.  As we move forward I will attempt to fill Harold's large shoes.  I will also take advantage of all the great folks on the team.

> With algorithm testing that is not currently in CAVS added to ACVP, will it be possible to add new capabilities to already validated implementations (i.e. an update request in CAVS parlance)?

Yes, but within ACVP, the way you will update a validation record will require you to use the same Module URL as whatever is currently in use on the validation record.

> In addition to updates to existing ACVP validations when new testing becomes available, we anticipate a situation during the transition period where some vendors may want to use CAVS for all of the algorithms that have available CAVS testing and use ACVP for algorithms that do not have CAVS testing. Since many vendors have existing implementations with CAVS test harnesses, they will not want to expend the development effort if it is not necessary to transition to the new format wherever possible. Will this be possible to do?

While we would prefer that all testing move to ACVP as quickly as possible, this is possible during the transition, but in order for them to share the same validation record, the CAVS entry will need to be submitted and processed first, and then the ACVP submission will need to be submitted (certify step) using the same module URL as what is found on the record. You can find the module URL by using the /validations resource and viewing the specific record.

Gavin

**Comment by smuellerDD** [comment]
Am Dienstag, 21. Mai 2019, 19:55:43 CEST schrieb gwobrien:

Hi gwobrien,

> > In addition to updates to existing ACVP validations when new testing
> > becomes available, we anticipate a situation during the transition period
> > where some vendors may want to use CAVS for all of the algorithms that
> > have available CAVS testing and use ACVP for algorithms that do not have
> > CAVS testing. Since many vendors have existing implementations with CAVS
> > test harnesses, they will not want to expend the development effort if it
> > is not necessary to transition to the new format wherever possible. Will
> > this be possible to do?
> While we would prefer that all testing move to ACVP as quickly as possible,
> this is possible during the transition, but in order for them to share the
> same validation record, the CAVS entry will need to be submitted and
> processed first, and then the ACVP submission will need to be submitted
> (certify step) using the same module URL as what is found on the record.
> You can find the module URL by using the /validations resource and viewing
> the specific record.

The ACVP Parser tool allows the development of an ACVP2CAVS and CAVS2ACVP 
converter. We have implemented that and it seems to work fairly well. So, 
bottom line is that if a vendor wants to stay with its CAVS framework, this is 
surely possible if it observes some caveats:

- CCM cannot be converted

- asymmetric ciphers requre that the CAVS tool uses the same keys for all 
cipher operations

Ciao
Stephan

**Comment by acronymhaterheidi** [comment]
Gavin and Harold, thank you for the response. Gavin, will you be active on GitHub in the future or would it be better to reach out to you through email for future questions along these lines?

Stephan, you have mentioned this functionality before but I don't think we (i.e. me :)) have plans to implement that converter. Of course, I cannot speak for the plans of the other labs!

**Comment by celic** [comment]
If you have questions about the CAVP, it would be best to email. We'd like to keep the GitHub for the protocol and issues with the server(s) itself. Though, maybe a FAQ on the Wiki here might be helpful.
