### ISSUE TITLE
Questions on DRBG 

### ISSUE THREAD

**Issue by ashman-p** [usnistgov/ACVP#65]
Just a few questions on DRBG Test vector handling ...
Take the following example from the spec ...

1. persoStringLen and additionalInputLen are 0 however the fields persoString and additionalInput are populated. Should they be ignored?

2. entropyInputPR and entropyInput will always be the same size?
3. Should "additionalInput"  and "entropyInputPR" be displayed in an array called "predResistanceInput" ?

                {
                  "version": "0.2",
                  "vectorSetId": "1146",
                  "algorithm": "hmacDRBG",
                  "mode": "AES-256",
                  "predResistance": "yes",
                  "entropyInputLen":"256",
                  "nonceLen":"128",
                  "persoStringLen":"0",   ******
                  "additionalInputLen":"0",  **** 
                  "returnedBitsLen":"1024",
                  "testGroups": [
                    {
                      "type": "long",
                      "tests": [
                        {
                          "tcId": "2111",
                          "entropyInput":"ee3392c5f3de6f3f8c4f28d852afacd2cbaa89ed48d1c5d4311662962aa70a98",
                          "nonce":"b991a820fac75fd02642ad8fa651eda4",
                          "persoString":"30f3a50b0e2309dab93ea2aa095e5df8e4b2a42690572b31e53fb79a195481e5",
                          "additionalInput":"4ea46abe95b2e4184113f908ae30123207d481908b7af7ef348657bbf3b4a002",
                          "entropyInputPR": "e4413a2e404f12c644b0b1d7a49a0fbf3d8703d571ffd02168c11b4ade6fc903",
                          "additionalInput" : "61b7204c8fef294f2a9f2e73a83a8a7a04c38e3b3eaaed1b920abfceab912492",
                          "entropyInputPR" : "968ea185d1439fa2d67eb55ac93ba596b1ea679de7c6e44f80dc6f213455f1ed"
                          },
                        {
                          "tcId": "2112",
                          "entropyInput" : "a0ace75784b97224de2957e5f60dc85b25331fcf7901f37418d3c9de17ed4261",
                          "nonce": "b671308068fc7909a360c772f62a4c5e",
                          "persoString" : "338d5f2bd93262da154385e9ed90b7862e3c892f13e1d7d19924b2eb8b3bab21",
                          "additionalInput" : "7acd8bfae17ff4edbac3437817d6b3fce12a04c4034ac6bef0b1b88f7dcd7c85",
                          "entropyInputPR" : "47b26bbe93a5cc19a410523a072e04333f06c54af0049fc41e66213763020ef7",
                          "additionalInput" : "d4b24c74538e3a1083a2cc0a4414a9f558f0a2dc186e3b9a5294cd541acdad87",
                          "entropyInputPR" : "acb63f3b5995608a1331641cd43208444a9ec95e4bb2a438f614156b6a77c8c3"
                        }
                      ]
                    }
                  ]
}

4. If the array  predResistanceInput is used, the test results
"testResults": [
                        {
                            "tcId": "2111",
                            "returnedBits": "e42130fd1d920a2bcd177c0de0d5834c9b05a6ecdf3bc46e3733869f762dc2e7d97357934d8061db033670c3739369924b321216c30b3e45d9bc8c0bad61d8fdc03dffd70725e793ebfe98bc15358764402f4e2c71be4acfad898649b51c5d2625374a61be2b59833d2dfcc593eddcffbac79016b22a992ae6f5f82bae194e06"

(Second generated value???)
"e42130fd1d920a2bcd177c0de0d5834c9b05a6ecdf3bc46e3733869f762dc2e7d97357934d8061db033670c3739369924b321216c30b3e45d9bc8c0bad61d8fdc03dffd70725e793ebfe98bc15358764402f4e2c71be4acfad898649b51c5d2625374a61be2b59833d2dfcc593eddcffbac79016b22a992ae6f5f82bae194e06"

},

**Comment by atvassilev** [comment]
There are errors in the spec, sorry. In CAVS there are two default settings (values) for persoStringLen and additionalInputLen. These should be arrays with two elements, with values {0, maxSupportedStrength} or {someLength, someOtherLength} or {someLength, someLength} if the DRBG supports only one length. If the persoStringLength is 0, then the corresponding values should not be set in the first place. The set of examples in the spec must be fixed. 

The entropyIniput and entropyInutPR can be assumed to be of the same length. 

I like the idea of combining additionalInput and entropyInputPR into an array. 

In CAVS there is only one generated value for all prediction resistance inputs. In other words, the system will check only the final result that depends on all inputs, not intermediate values. I am open to reporting the  intermediate result, if everybody is on board. 

I can work on cleaning the spec up next week but if you would like to take a stab at it let me know.

**Comment by ashman-p** [comment]
Thank you Apostol.
Norm

See inline.
On Mar 8, 2017, at 6:19 PM, Apostol Vassilev <notifications@github.com<mailto:notifications@github.com>> wrote:


There are errors in the spec, sorry. In CAVS there are two default settings (values) for persoStringLen and additionalInputLen. These should be arrays with two elements, with values {0, maxSupportedStrength} or {someLength, someOtherLength} or {someLength, someLength} if the DRBG supports only one length. If the persoStringLength is 0, then the corresponding values should not be set in the first place. The set of examples in the spec must be fixed.

The entropyIniput and entropyInutPR can be assumed to be of the same length.

[Norman] ok.

I like the idea of combining additionalInput and entropyInputPR into an array.

[Norman] I think the spec already have them combined that way.

In CAVS there is only one generated value for all prediction resistance inputs. In other words, the system will check only the final result that depends on all inputs, not intermediate values. I am open to reporting the intermediate result, if everybody is on board.

I can work on cleaning the spec up next week but if you would like to take a stab at it let me know.

[Norman] Sure, let make sure I will learn how to generate the files.

**Comment by atvassilev** [comment]
Norman,

Yesterday I pushed PR #74 that takes care of the errors in the previous version. Please take a look at it and let me know if you have questions.

**Comment by atvassilev** [comment]
All issues so far have been addressed in PR #77. Closing ...
