### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#650]
Albeit the performance was significantly enhanced with the last round, there is some issue. I invoked a download of more than 600 vsIDs in a row covered by some 54 test sessions.

Almost all of them went through very fast. However, one just hangs. Almost all test requests do not return any vectors after now even 2 hours. There are standard ciphers like all SHA1/2 hashes, their HMACs included which also do not get test vectors.

Thus, I think that the performance improvement somehow triggers another issue.

test session: 14763

**Comment by smuellerDD** [comment]
Still the case: testID 69

**Comment by celic** [comment]
Thanks for the report. I've been out for roughly 10 days. I'll investigate this today.

**Comment by Kritner** [comment]
There is a fix being tested in our internal environments related to this FYI @celic

**Comment by celic** [comment]
For some clarity, the previous issue was the number of tasks the driver would try to accomplish at once. That has been updated (just a configuration update) resulting in the initial speed increase. Since then, we have seen the driver struggle to hold some of the DB connections open simultaneously, now that we have a lot more throughput on the driver. We have a fix in the works that addresses the problem (a more involved code update).

**Comment by hbooth** [comment]
Please try again after the latest deployment which has addressed a number of issues that were discovered during further testing.

**Comment by smuellerDD** [comment]
It works now - 636 from 646 vsIDs were obtained within 30 minutes. The 10 remaining vsIDs are all SHAKE not having pre-generated vectors.

Note, SHAKE seems to be coming into fashion fast now. We see it coming in quite some newly designed and updated IUTs.

Yet, after 1 hour I got all 646 vsIDs.

**Comment by smuellerDD** [comment]
Using 256 threads for vsID downloads, I could shrink it to 25 (all except SHAKE) vs 50 (incl. SHAKE) minutes

**Comment by atvassilev** [comment]
@smuellerDD this is quite encouraging. Great job on both ends!

**Comment by smuellerDD** [comment]
An upload of test results of close to 1300 vsIDs and fetching the associated test verdicts took about one hour using 256 threads.
