### ISSUE TITLE
RSA keygen: identical test vectors received

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#652]
For one IUT with different cipher implementations,  I requested several RSA keygen test vectors. The ACVP server returned test vectors, which are all identical:

```
diff -urN testvectors/atsec_corp_/OpenSSL__32_bit___SHA_SSSE3_/1.1.0/14542/43651/testvector-request.json testvectors/atsec_corp_/OpenSSL__32_bit___SHA_AVX_/1.1.0/14505/43277/testvector-request.json
--- testvectors/atsec_corp_/OpenSSL__32_bit___SHA_SSSE3_/1.1.0/14542/43651/testvector-request.json      2019-05-23 07:59:53.161724778 +0200
+++ testvectors/atsec_corp_/OpenSSL__32_bit___SHA_AVX_/1.1.0/14505/43277/testvector-request.json        2019-05-23 07:40:03.549310682 +0200
@@ -1,7 +1,7 @@
 [ {
   "acvVersion" : "1.0"
 }, {
-  "vsId" : 43651,
+  "vsId" : 43277,
   "algorithm" : "RSA",
   "mode" : "keyGen",
   "revision" : "1.0"
```

vsID (at least): 43651, 43277, 43235

**Comment by Kritner** [comment]
@smuellerDD it seems that the duplicate tests are "Known Answer Tests" which are the same tests for each run (at least coming from algorithm testing that I'm more familiar with), that appears to be the case here no?

More of the RSA keyGen testing appears to be covered via a combination of the KATs (unchanging) and the completely deferred tests where it is up to the IUT to provide keys.

**Comment by smuellerDD** [comment]
Am Dienstag, 28. Mai 2019, 11:20:05 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD it seems that the duplicate tests are "Known Answer Tests" which
> are the same tests for each run (at least coming from algorithm testing
> that I'm more familiar with), that appears to be the case here no?

Correct. It is RSA keygen verification and thus could count as a KAT.
> 
> More of the RSA keyGen testing appears to be covered via a combination of
> the KATs (unchanging) and the completely deferred tests where it is up to
> the IUT to provide keys.

I just mentioned it as I think that unchanging KATs are not desired by NIST.

Ciao
Stephan

**Comment by Kritner** [comment]
I don't believe that to be the case, we are using the same KATs from RSA in the previous tool and have gone a similar route with the KATs under the symmetric ciphers.

I'll close for now, but if any NISTers have additional input, feel free to add.
