### ISSUE TITLE
Vendor address.region wrong value

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#653]
Hello,

I recently had my client register a new Vendor on the demo server for testing purposes. It appears that the resource created has the wrong value for the address.region inside the Vendor. In all of my tests so far, the "region" value appears to be copied from the "locality" value. For example:

approvedUrl: /acvp/v1/vendors/11175
requestUrl: /acvp/v1/requests/1
Server Resource: {'url': '/acvp/v1/vendors/11175', 'name': 'Acme Fictional', 'website': 'http:fictional-acme.com', 'emails': ['acme@acme.com'], 'phoneNumbers': [{'number': '1-800-000-0000', 'type': 'voice'}], 'contactsUrl': '/acvp/v1/vendors/11175/contacts', 'addresses': [{'url': '/acvp/v1/vendors/11175/addresses/11138', 'street1': 'Beach Dr.', 'street2': None, 'street3': None, 'locality': 'Acme Town', 'region': 'Acme Town', 'country': 'USA', 'postalCode': '00000'}]}

I double checked the JSON that my client sent over, and the "region" in this case should be "NC".
Is this a bug in the server Vendor metadata creation? Please let me know.

Thanks!
Phil

**Comment by bfussell** [comment]
@smuellerDD Have you seen anything like this ?

**Comment by smuellerDD** [comment]
I have not seen this. I always use the following entry which I validate with a GET /vendors before the final PUT:

```
  {
    "name":"atsec corp.",
    "website":"www.atsec.com",
    "addresses":[
      {
        "street1":"9130 Jollyville Rd",
        "locality":"Austin",
        "region":"TX",
        "country":"USA",
        "postalCode":"78759"
      }
    ]
```

The region always showed as TX when retrieving the entry from the server

**Comment by fliphil** [comment]
@smuellerDD How old is that Vendor entry? Was it created recently? I'm wondering if this a newly introduced issue.

**Comment by smuellerDD** [comment]
Am Freitag, 31. Mai 2019, 21:08:47 CEST schrieb Philip Perricone:

Hi Philip,

> @smuellerDD How old is that Vendor entry? Was it created recently? I'm
> wondering if this a newly introduced issue.

I created it some time ago, maybe 3 to 4 weeks. So, yes, you may have hit a 
new issue.

Though, just now I am registering my vendor again as the latest server update 
seem to have changed the database completely. I.e. the vendor ID I used to 
have does not point to my entry any more.

I will let you know whether I encountered any issues for this register 
operation.

Ciao
Stephan

**Comment by jarnold01** [comment]
Hi Stephan,

I can confirm that the latest server update was database-oriented in nature and did remove existing data per the following statement that I sent out with the maintenance notification (repeated here in case anyone missed it):

"Please note that any existing session data will be cleared out as a result of this change, to include any resources created in the Demo environment, such as Modules, Vendors, Persons, Operational Environments, Dependencies and Validations."

I hope this info helps in the troubleshooting process.

Jason

**Comment by smuellerDD** [comment]
Am Freitag, 31. Mai 2019, 21:19:41 CEST schrieb Jason Arnold:

Hi Jason,

> Hi Stephan,
> 
> I can confirm that the latest server update was database-oriented in nature
> and did remove existing data per the following statement that I sent out
> with the maintenance notification (repeated here in case anyone missed it):
> 
> "Please note that any existing session data will be cleared out as a result
> of this change, to include any resources created in the Demo environment,
> such as Modules, Vendors, Persons, Operational Environments, Dependencies
> and Validations."
> 
> I hope this info helps in the troubleshooting process.

Thanks for the clarifications. I seem to have misinterperted the term "session 
data" :-)
> 
> Jason



Ciao
Stephan

**Comment by jarnold01** [comment]
Hi Stephan,

My apologies if my word choice was ambiguous and caused confusion.

Thanks,
Jason

**Comment by hbooth** [comment]
Following up on the original issue described. There is an error with how it is output. The data is stored correctly. A fix is being tested and will be pushed out shortly.

**Comment by hbooth** [comment]
Please check now. This should now be resolved.

**Comment by fliphil** [comment]
Thanks for fixing that!
