### ISSUE TITLE
Search in /dependencies - is it wired up?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#654]
My client issues a search request for dependencies. Yet, the server returns a next pointer without the search information. Thus I think I have to believe that the dependencies are not searchable?

**Comment by hbooth** [comment]
/acvp/v1/dependencies?name[0]=contains:linux

worked for me (in my test environment). What searches are you attempting?

**Comment by smuellerDD** [comment]
Strange, I see it working now as well. Closing the issue as it may be my problem.
