### ISSUE TITLE
Documented paths incorrect

### ISSUE THREAD

**Issue by agl** [usnistgov/ACVP#656]
I believe the paths for the demo server documented on [the wiki](https://github.com/usnistgov/ACVP/wiki) are wrong. Specifically, I understand that the URL prefix should be `acvp/v1/`.

It's not possible, as far as I know, to submit a pull request for wiki content on GitHub. However I think the needed changes are [here](https://github.com/agl/ACVP-wiki/commit/fbcfc7344c7e299da78516dfc561c4fcfc9f420b), which can be integrated on the command line. (Or reproduced if that's easier.)

**Comment by celic** [comment]
Done. That was changed a while back in the specification but did not make it to the wiki. Thanks for the catch.
