### ISSUE TITLE
Additional granularity from login failures would be useful.

### ISSUE THREAD

**Issue by agl** [usnistgov/ACVP#657]
It would be useful for the `login` endpoint on the demo server to provide more detailed error messages. At the moment it returns generic 401 messages. Because of that, I'm at a loss to figure out what's wrong.

In order to reduce the number of unknowns, I've tried with the suggested [libacvp client](https://github.com/cisco/libacvp):

```
% export ACV_TOTP_SEED=<omitted base64 value provided in a .txt file from NIST>
% ACV_URI_PREFIX=acvp/v1/ ACV_SERVER=demo.acvts.nist.gov ACV_CERT_FILE=/agl/acvp/acvp.pem ACV_KEY_FILE=/agl/acvp/acvp.key.pem ./acvp_app --verbose --aes

***ACVP [STATUS][log_network_status:818]--> POST Login...
        Status: 401
        Url: https://demo.acvts.nist.gov:443/acvp/v1/login
        Resp:
<html><head><title>JBWEB000065: HTTP Status 401 …
```

That's the same response as I get from our own client too. Our client is POSTing `[{"acvVersion":"1.0"},{"password":"40890413"}]` and I've confirmed that the server is triggering a TLS renegotiation and that the second handshake is sending the certificate.

The time on the system is correctly synchonised, at least with respect to https://time.gov/HTML5/. The certificate in acvp.pem is as provided by NIST: issued by &ldquo;NIST CVP Demo CA&rdquo;, expiring in 2021.

**Comment by jarnold01** [comment]
Hi Adam, please give it another try now.

**Comment by agl** [comment]
> Hi Adam, please give it another try now.

Whatever it was worked, thanks!

Please feel free to close this issue although, if some manual action was needed on your part, perhaps a 500 error would be more informative in this context? (Although perhaps that's difficult to do.)
