### ISSUE TITLE
Testvector not generated

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#658]
The ACVP server failed to generate a test vector and yet returns successful HTTP return code.

I.e. I have no test vector and yet did not receive an error from the ACVP server.

vsID: 2439

**Comment by smuellerDD** [comment]
Typo: vsID 2429

**Comment by celic** [comment]
From our end we can see that a prompt was generated (SHAKE-256). What is the full return from trying to GET that vsId from the server?

**Comment by celic** [comment]
One thing I do notice is that the prompt file generated is quite large (1.6MB) this should not be an issue from the server perspective.

**Comment by smuellerDD** [comment]
Am Freitag, 7. Juni 2019, 17:21:18 CEST schrieb Chris Celi:

Hi Chris,

> From our end we can see that a prompt was generated (SHAKE-256). What is the
> full return from trying to GET that vsId from the server?

That is what I do not have, because I just detected that missing vector after 
adding the support for listing all test results.

If you do not see anything on your end, let us close the issue and I will 
reopen it in case I see it again and have the result of the HTTP GET.

Ciao
Stephan

**Comment by celic** [comment]
Ah, well if you cannot access the vsId again there isn't too much for us to do. All of our systems and logs say it should be available with the JWT. Of course, report the issue again if it comes up.

**Comment by smuellerDD** [comment]
Am Freitag, 7. Juni 2019, 17:50:36 CEST schrieb Chris Celi:

Hi Chris,

> Ah, well if you cannot access the vsId again there isn't too much for us to
> do. All of our systems and logs say it should be available with the JWT. Of
> course, report the issue again if it comes up.

My bad, I programmed the proxy to retrieve vectors later, but forgot about it 
:-)

I requested the vector again and I got it. So I am not sure about the cause of 
the vector not being downloaded initially.

Closing the issue is the right course of action.

Ciao
Stephan
