### ISSUE TITLE
RSA keyGen: request GDT only possible?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#660]
Question: Is it possible to request RSA keyGen B.3.3 test vectors that only allow GDT? I.e. test vectors requesting the IUT to generate a key.

But the AFT for keyGen where the IUT is expected to process the ACVP-server-provided p and q to generate a key from it is not supported by my IUT.

With CAVS, this split was possible.

**Comment by celic** [comment]
For B.3.3, GDT _should_ be the only test type generated if the client ONLY supports random keys.

**Comment by smuellerDD** [comment]
Am Montag, 10. Juni 2019, 17:28:59 CEST schrieb Chris Celi:

Hi Chris,

> For B.3.3, GDT _should_ be the only test type generated if the client ONLY
> supports random keys.

Could you please point me to the option how to specify the type of keys for 
the register operation?

Ciao
Stephan

**Comment by celic** [comment]
An example registration would be this...

```
{
  "capabilities": [
    {
      "randPQ": "B.3.3",
      "properties": [
        {
          "modulo": 2048,
          "hashAlg": [
            "sha2-224"
          ],
          "primeTest": [
            "tblC2",
            "tblC3"
          ]
        },
        {
          "modulo": 3072,
          "hashAlg": [
            "sha2-224"
          ],
          "primeTest": [
            "tblC2",
            "tblC3"
          ]
        }
      ]
    },
  ],
  "algorithm": "RSA",
  "mode": "KeyGen",
  "revision": "1.0",
  "infoGeneratedByServer": true,
  "pubExpMode": "random",
  "keyFormat": "crt"
}
```

The interesting part is `"pubExpMode": "random",`. I misspoke. The public exponent must be random.

**Comment by smuellerDD** [comment]
Am Montag, 10. Juni 2019, 18:05:46 CEST schrieb Chris Celi:

Hi Chris,
> 
> The interesting part is `"pubExpMode": "random",`. I misspoke. The public
> exponent must be random.

Thank you very much.

Based on your statement then, if my IUT uses a fixed exponent, I always get 
the KAT testing as well?

Ciao
Stephan

**Comment by celic** [comment]
Hmm... Apologies. The KATs for B.3.3 use a subset of static keys on our end. Because of that, they can only be added if the IUT supports a "random" e (i.e. the IUT can take any public exponent). The GDT should always be present for B.3.3. So to not have the KATs occur, an IUT would need to only support a fixed public exponent.

**Comment by smuellerDD** [comment]
Thanks a lot for the clarification.
