### ISSUE TITLE
Question about querying operating envvironment

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#661]
Is there a way to query the /oes endpoint filtered not only based upon the "name" but also the "dependencyUrls"? I've tried something similar to this and the server only seems to recognize the name paremeter:

name[0]=eq:<NAME>&dependencyUrl[0]=eq:<DEPENDENCYURL-0>&dependencyUrl[1]=eq:<DEPENDENCYURL-1>

**Comment by agl** [comment]
(The available query operators are listed [in the spec](https://usnistgov.github.io/ACVP/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.11.12.1) and, for `oes`, only `name` specified to be indexed. So this is not currently possible, although may be a good idea.)

**Comment by fliphil** [comment]
Okay thanks
