### ISSUE TITLE
ECDSA: add signature generation component test support

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#663]
With CAVS, it is possible to request test vectors for ECDSA signature generation component (similarly to the RSA components).

The current ECDSA spec however does not allow such a request. Thus, may I ask for having it added to be en-par with CAVS?

**Comment by smuellerDD** [comment]
Please note that after a talk with Allan Roginsky and Lily Chen at ICMC, there will be the request for RSA and ECDSA signature verification component testing to be added to ACVP.

**Comment by celic** [comment]
It does exist, it just might not be present in the specification. It is not a separate algorithm like it was in the past. It is an option on the existing ECDSA Signature Generation algorithm. Let me find a registration that enables this...

**Comment by celic** [comment]
ECDSA SigGen has a property `"componentTest": <boolean>` that denotes this. It is not captured in the specification. 

Here is an example:
```
{
  "algorithm": "ECDSA",
  "mode": "SigGen",
  "revision": "1.0",
  "capabilities": [
    {
      "curve": [
        "p-224"
      ],
      "hashAlg": [
        "sha2-224"
      ]
    }
  ],
  "componentTest": true
}
```

**Comment by smuellerDD** [comment]
Am Mittwoch, 12. Juni 2019, 16:48:38 CEST schrieb Chris Celi:

Hi Chris,

> ECDSA SigGen has a property `"componentTest": <boolean>` that denotes this.
> It is not captured in the specification.
> 
> Here is an example:
> ```
> {
>   "algorithm": "ECDSA",
>   "mode": "SigGen",
>   "revision": "1.0",
>   "capabilities": [
>     {
>       "curve": [
>         "p-224"
>       ],
>       "hashAlg": [
>         "sha2-224"
>       ]
>     }
>   ],
>   "componentTest": true
> }
> ```

Thanks for the note. Shall we leave that issue open for updating the SPEC?

Ciao
Stephan

**Comment by celic** [comment]
Yes. I'm in the process of revamping how we write our specifications (via Metanorma). I'll get to this soon.

**Comment by smuellerDD** [comment]
I just obtained test vectors for ECDSA sigver component testing. Though, the vectors seem odd: irrespective of the chosen hash and curve, the message is always 128 bytes.

vsID: 79396

**Comment by celic** [comment]
This is the case for any ECDSA SigGen or SigVer registration I believe. The messages are a constant 1024-bits.

**Comment by smuellerDD** [comment]
Am Donnerstag, 21. November 2019, 20:49:16 CET schrieb Chris Celi:

Hi Chris,

> This is the case for any ECDSA SigGen or SigVer registration I believe. The
> messages are a constant 1024-bits.

Oh, so you provide the already formatted message and not just the hash?

Ciao
Stephan

**Comment by celic** [comment]
I'm not sure SigVer component testing exists. Apologies. I misunderstood the question. For ECDSA SigGen with `"componentTest": false` and SigVer overall, the messages will always be 1024 bits. There is no option for `"componentTest"` on ECDSA SigVer nor DSA SigVer. 

There is no guarantee that a client will always receive messages of a certain format for verification. Whether that format refers to the length, or if the message is already a hash digest. So we didn't see value in offering the component test for SigVer at the moment.
