### ISSUE TITLE
BigInteger removes leading 0x00 bytes

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#664]
I have run the same data thru the crypto module using the CAVS test harness and it says the test case should not verify as well.

https://demo.acvts.nist.gov:443/acvp/v1/testSessions/1443/vectorSets/5579

vsId  5579
tgId 21
tcId 124

The client says the signature does not verify, the server says it should.

    "tgId" : 21,
    "sigType" : "ansx9.31",
    "modulo" : 3072,
    "hashAlg" : "SHA2-384",
    "saltLen" : 0,
    "n" : "CDA21D4355821677782C62B1C300FC458349EB9AFADFCF23D5195B29E412E7505A0F7BF5CEF73C08B384AF9B2515E8F21929EB4552C341FF821C41E29A473F7CE074F8540D656D183642C89756770542910F20B4D981F4ACF2828401A59B3C908978BDF6B9D65253233B6B4B30A0538FCFBD88EE34F5DDB30AD98E0259A37161BE564C259DD46DFEEDD80C437051909211E56DE48241B982F502052E863CD88CA430FE543D430FFFAA8C4A4384570A4B714DBD84EE96CE66003BAD2DA3B778BE9EAFD86595115A297F1866845964B2762ED66796F27A9B6271BAEDD531ECDAA0A92BF19962F3D07E711FDBA7B09838B4CD4F4B81C5331D58012FC03DA59F0819DE503298149E8E2676F7255DD25E282511B3A8B3CA423A24EB588F11D10E7A2D5F4C2D5F6C77489908D946B1A84F16A2A7273D32E8513D5E0F4417676865DAD97DDF267E0B445356C72CEC23A2EAB4CC1F8BE092D4A71B1FF3040D9A1F2966D14BE6A1319116294ED1FBF514CDDC90AEE5177D2D763DE53A68894C22004B0EFB",
    "e" : "010001",
    "testType" : "GDT",
    "tests" : [ {
....
      "tcId" : 124,
      "message" : "76E4DE4F293094EFDD72FF805538EE063BEE70EFE789108F33B68800A5D1C29969E91146D9F22FF4D6AC65886667ECC5DF2E3BFE15B009882BB74258246B9C43FA65E741FECD3577EC85A0F1123B47750EAD6B4114BDFF502B10140E691B7A769D78C4ADDCFA734A7050BB140134993FC6AB739FE23ABBBE13C43C7218A5C8A79AA126AB7A0D20824D4D7BD07C121467822CB331C31518C4243FBBFD7CC098EB203727169C1B6B7ADD36B4FAFEDFFDCEC1B932B090E8DFC1B7C3C7E688FEB901",
      "signature" : "81F8FE2EAB6E76145FD5B67A1E77DEB03090FEF407167E41CEDC11BD6CB56AF3694B67AB18C11EF0D6C29C8ABC4DBB14C10AA0AD8B52066CFC9824E723887F041C68661A647C583532F3FCE91E874332DD78EF9CD3EB4A9ED9F8114DCEA29598145F927BF4AE384C04BD21919C10F15FDC1A44DD3565802E20B0F2625CF853AD35E786AC3C5902FA8BC64C13BE1F6C5AC193919DAA40E5C472D4115B3CB298241550AB1C45817E812C5388B4AC83BCF323569DCECCD34B3D14F104DF03FD6D46D78CF78C3587D6FF7CB2E40277104C835C37818D466C619CA7F91F15EFC60797A48E3D31A227E5244BC3AC112995B2C1FFF33A012B5A0EC06A03159729493BB6FDE7E3C6B4152D6941D0B041DD411ABE9C8C95AC924778F460B3F92B562164896F5876EE7A1F891BCE2EF436CEB17318FEDE2CA63C266CAE4BAF2160CEBC9BCD3E22991EE29A01FC74CA8AB6339EEB904128467DEACF748056D1B2A3659A3F1A5B8829BA0918036F9E078383923E8D32EDA6E5F160B1D1E517C7071713BC3B"

Client returns:

                "tgId": 21,
                "tests": [
                    {
                        "tcId": 121,
                        "testPassed": false
                    },
                    {
                        "tcId": 122,
                        "testPassed": false
                    },
                    {
                        "tcId": 123,
                        "testPassed": false
                    },
                    {
                        "tcId": 124,
                        "testPassed": false   <----
                    },
                    {
                        "tcId": 125,
                        "testPassed": false
                    },
                    {
                        "tcId": 126,
                        "testPassed": false
                    }
                ]
            },

Server says:

    "tcId" : 124,
    "result" : "failed",
    "reason" : "No modification"
  }, {

**Comment by smuellerDD** [comment]
Am Donnerstag, 13. Juni 2019, 17:15:05 CEST schrieb Barry Fussell:

Hi Barry,

> I have run the same data thru the crypto module using the CAVS test harness
> and it says the test case should not verify as well.

Please check your padding:

$ echo -n 
81F8FE2EAB6E76145FD5B67A1E77DEB03090FEF407167E41CEDC11BD6CB56AF3694B67AB18C11EF0D6C29C8ABC4DBB14C10AA0AD8B52066CFC9824E723887F041C68661A647C583532F3FCE91E874332DD78EF9CD3EB4A9ED9F8114DCEA29598145F927BF4AE384C04BD21919C10F15FDC1A44DD3565802E20B0F2625CF853AD35E786AC3C5902FA8BC64C13BE1F6C5AC193919DAA40E5C472D4115B3CB298241550AB1C45817E812C5388B4AC83BCF323569DCECCD34B3D14F104DF03FD6D46D78CF78C3587D6FF7CB2E40277104C835C37818D466C619CA7F91F15EFC60797A48E3D31A227E5244BC3AC112995B2C1FFF33A012B5A0EC06A03159729493BB6FDE7E3C6B4152D6941D0B041DD411ABE9C8C95AC924778F460B3F92B562164896F5876EE7A1F891BCE2EF436CEB17318FEDE2CA63C266CAE4BAF2160CEBC9BCD3E22991EE29A01FC74CA8AB6339EEB904128467DEACF748056D1B2A3659A3F1A5B8829BA0918036F9E078383923E8D32EDA6E5F160B1D1E517C7071713BC3B  
| wc
      0       1     766

--> the signature needs to be padded on the left by a NULL byte - are you 
adding this one?

Ciao
Stephan

**Comment by bfussell** [comment]
Hmmm, I thought that was going to be fixed at the server. For DSA domainSeed we prepend the byte if there are leading null bytes. Seems like we should do it the same way in both cases.

**Comment by smuellerDD** [comment]
Am Donnerstag, 13. Juni 2019, 18:00:48 CEST schrieb Barry Fussell:

Hi Barry,

> Hmmm, I thought that was going to be fixed at the server. For DSA domainSeed
> we prepend the byte if there are leading null bytes. Seems like we should
> do it the same way in both cases.

I am not sure that this issue is to be fixed by the server.

Our domainSeed issue was that when we provided a leading zero byte, it was 
discarded by the ACVP server.

Here, the server provides data without the leading zero byte. Some IUTs can 
handle that, some do not. In the case of OpenSSL, for example, I have a helper 
function which always adds zero bytes if the input buffer is of insufficient 
size for all asymmetric cipher test vector data.

See [1] and all similar occurrences.

[1] https://github.com/smuellerDD/acvpparser/blob/master/backends/
backend_openssl.c#L1006

Ciao
Stephan

**Comment by bfussell** [comment]
Understand, but the problem is that if we take the approach that *some* strings need to be evaluated for padding then to me that means any string could potentially need padding.  Do we need to check every string length we receive and pad ? Many strings don’t carry a predefined length so that seems an untenable option. If that’s not case, then why is this string any different than any other string including the case of domainSeed.

Coding to handle this isn’t an issue for us, but it seems to be a special case we have not encountered in other areas of the protocol.

**Comment by celic** [comment]
It is a fair assumption to make that the message provided is complete. This is something we've observed anywhere we use the underlying `BigInteger` C# library when converting to our custom `BitString` type. It is directly related to that `DomainSeed` issue. If the first few bytes happen to be 00s, they will be dropped. We have talked about this internally and have plans to fix it but it is a pretty wide problem (every algorithm that uses `BigInteger`).

**Comment by celic** [comment]
This has been on our radar. We should be able to address it within a couple weeks. This involves a somewhat large back-end change to some of our data models on the gen/vals on a wide variety of algorithms.

**Comment by bfussell** [comment]
Thanks Chris !

**Comment by Kritner** [comment]
Didn't realize I hadn't picked this ticket up.  I believe we discussed on the last call, but these changes will be going in for the next release to demo.

**Comment by Kritner** [comment]
This change has been deployed to demo. Please let us know if there are any issues.

**Comment by celic** [comment]
Closing. Let us know if there are any lingering issues here. We know of #680 and are preparing a more sustainable fix.
