### ISSUE TITLE
Guidance on access tokens for test sessions.

### ISSUE THREAD

**Issue by agl** [usnistgov/ACVP#666]
When creating a test session, a new access token is returned [as specified](https://usnistgov.github.io/ACVP/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.11.15.2.2). Why?

I can imagine that it's intended to subset the authority of the original access token so that a less-trusted subprocess can perform the actual tests. But, if that's the case:

1. Why is the original (i.e. superior) access token unable to see its test sessions?
1. Will the per-session token function on a different connection without the client certificate? Without a `/login`?

Also, test sessions expire in a month (at least on the demo server), but the session-specific access token expires in 30 minutes. Are all test sessions expected to be completed in 30 minutes or are the session-specific access tokens intended to be renewed using the [renewal login flow](https://usnistgov.github.io/ACVP/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.9.1) at least every 30 minutes?

If a module experiences a failure during testing, it would seem polite to try and delete the test session. However, although a DELETE operation returns a 200, the test session is still provided in response to a GET and repeated DELETEs keep returning 200.

Lastly, after creation, test sessions return 404 for a while before appearing.

**Comment by smuellerDD** [comment]
Am Mittwoch, 19. Juni 2019, 01:43:08 CEST schrieb Adam Langley:

Hi Adam,

> When creating a test session, a new access token is returned [as
> specified](https://usnistgov.github.io/ACVP/artifacts/draft-fussell-acvp-sp
> ec-00.html#rfc.section.11.15.2.2). Why?
> 
> I can imagine that it's intended to subset the authority of the original
> access token so that a less-trusted subprocess can perform the actual
> tests. But, if that's the case:
> 
> 1. Why is the original (i.e. superior) access token unable to see its test
> sessions? 1. Will the per-session token function on a different connection
> without the client certificate? Without a `/login`?
> 
> Also, test sessions expire in a month (at least on the demo server), but the
> session-specific access token expires in 30 minutes. Are all test sessions
> expected to be completed in 30 minutes or are the session-specific access
> tokens intended to be renewed using the [renewal login
> flow](https://usnistgov.github.io/ACVP/artifacts/draft-fussell-acvp-spec-00
> .html#rfc.section.9.1) at least every 30 minutes?

Yes.
> 
> If a module experiences a failure during testing, it would seem polite to
> try and delete the test session. However, although a DELETE operation
> returns a 200, the test session is still provided in response to a GET and
> repeated DELETEs keep returning 200.
> 
> Lastly, after creation, test sessions return 404 for a while before
> appearing.



Ciao
Stephan

**Comment by celic** [comment]
We do not expect test sessions to be completed within the 30 minute window. You can refresh that specific token associated with the test session at any time to begin a new 30 minute window. @Kritner might be able to verify better, but I believe that each token is closely tied with the client certificate. 

Deletion is in the works. 

The last one might make sense as its own issue. It may be intended (or at least a consequence of the architecture). The server receiving the test session request and issuing a corresponding status code is not quite the same as the server being ready to respond to requests about the test session. At most this difference would be 30 seconds, if the problem is caused by what I think it is.

**Comment by Kritner** [comment]
> We do not expect test sessions to be completed within the 30 minute window. You can refresh that specific token associated with the test session at any time to begin a new 30 minute window. @Kritner might be able to verify better, but I believe that each token is closely tied with the client certificate.

Yes, both the original token at login and the token at test session creation contain information tying the JWT to the certificate used at its creation.  The test session token (received after a post to the testSessions endpoint) additionally contains claims for the specific test session, as well as vector sets tied to that session.

> Why is the original (i.e. superior) access token unable to see its test sessions?

The original token at its creation time does not have any context to what will be registered in a follow up endpoint when a test session is creation, so those claims cannot exist at the point of initial login. I don't remember all the specific differences regarding expiration between the two JWTs, but the register endpoint returned JWT ***could*** in some aspects be considered an "update" to the original, in that it contains the claims.

> Will the per-session token function on a different connection without the client certificate? Without a `/login`?

AFAIK the certificate is always required for communication to and from the ACVP server.

Note these tokens can be renewed at the login endpoint by supplying the token to be renewed as well as the TOTP as described in: https://usnistgov.github.io/ACVP/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.11.3.2

**Comment by celic** [comment]
Has this been clarified or are there still questions about the tokens?
