### ISSUE TITLE
Requesting a List of available Dependency properties

### ISSUE THREAD

**Issue by ABUBSHAIT** [usnistgov/ACVP#671]
I am attempting the GET request that returns a paged list of available dependency properties, as detailed in section 11.13.3. List Dependency Properties of the spec. However, in doing so I get a 404 error.
I found a response from @hbooth in this [closed issue](https://github.com/usnistgov/ACVP/issues/603), in which he says that the spec is not fully baked. Does this mean that this GET request is currently not implemented?

**Comment by smuellerDD** [comment]
Am Dienstag, 25. Juni 2019, 03:00:15 CEST schrieb ABUBSHAIT:

Hi ABUBSHAIT,

> I am attempting the GET request that returns a paged list of available
> dependency properties, as detailed in section 11.13.3. List Dependency
> Properties of the spec. However, in doing so I get a 404 error. I found a
> response from @hbooth in this [closed
> issue(https://github.com/usnistgov/ACVP/issues/603), in which he says that
> the spec is not fully baked. Does this mean that this GET request is
> currently not implemented?

The paged operation and the search operation are both fully functional.

See [1] and [2] for examples.

[1] https://github.com/smuellerDD/acvpproxy/blob/master/lib/acvp_paging.c#L76

[2] https://github.com/smuellerDD/acvpproxy/blob/master/lib/
acvp_meta_module.c#L352

Ciao
Stephan

**Comment by ABUBSHAIT** [comment]
Hi @smuellerDD ,

Thanks for the examples. However, I currently have the paging operation implemented and it works with other listing GET requests.

For example, I just tried GET /algorithms and received a list of available algorithms with no issues (11.14.1. Algorithms Listing). However, every time I try the GET /dependencies/properties request I get a 404 Not Found error.

So I am suspecting that either the Url is incorrect or that this specific GET request is not working.
For your reference, this is the entire URL that I am pining:
GET https://demo.acvts.nist.gov/acvp/v1/dependencies/properties

I am wondering if anyone has tried this and got it to work.

Thanks,
Abdullah

**Comment by smuellerDD** [comment]
Am Dienstag, 25. Juni 2019, 18:12:44 CEST schrieb ABUBSHAIT:

Hi ABUBSHAIT,

> Hi @smuellerDD ,
> 
> Thanks for the examples. However, I currently have the paging operation
> implemented and it works with other listing GET requests.
> 
> For example, I just tried GET /algorithms and received a list of available
> algorithms with no issues (11.14.1. Algorithms Listing). However, every
> time I try the GET /dependencies/properties request I get a 404 Not Found
> error.
> 
> So I am suspecting that either the Url is incorrect or that this specific
> GET request is not working. For your reference, this is the entire URL that
> I am pining:
> GET https://demo.acvts.nist.gov/acvp/v1/dependencies/properties

I see, you want to get the object definitions for dependencies. I have not 
seen the need for doing this operation so I have not implemented it.
> 
> I am wondering if anyone has tried this and got it to work.
> 
> Thanks,
> Abdullah



Ciao
Stephan
