### ISSUE TITLE
Unable to login to demo server, getting status code 401

### ISSUE THREAD

**Issue by shawnyang1** [usnistgov/ACVP#672]
Hi guys,

I'm getting an error where it states: "The supplied one time password could not be verified". I'm not sure if what I'm doing is correct, but here's the process I followed:

- Clone acvp client 
- Build client by following the README on https://github.com/cisco/libacvp
- Update nist_setup.sh with:
```
#!/bin/bash
export ACV_URI_PREFIX=/acvp/v1/
export ACV_API_CONTEXT=acvp/
export ACV_CA_FILE=certs/demo_server.crt
export ACV_KEY_FILE=certs/client-key.pem
export ACV_CERT_FILE=certs/demo_server.cer (provided by NIST)
export ACV_TOTP_SEED="content of .txt file provided by NIST"
export ACV_PORT=443
export ACV_SERVER=demo.acvts.nist.gov
```
- Run ./app/acvp_app --aes

The output I got was:
Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    certs/demo_server.crt
    ACV_CERT_FILE:  certs/demo_server.cer
    ACV_KEY_FILE:   certs/client-key.pem

***ACVP [STATUS][log_network_status:1001]--> POST Login...
Status: 401
Url: https://demo.acvts.nist.gov:443/acvp/v1/login
Resp:
{
  "acvVersion" : "1.0",
  "error" : "The supplied one time password could not be verified"
}

***ACVP [STATUS][acvp_login:1821]--> Login Send Failed
***ACVP [ERR][acvp_run:2197]--> Failed to login with ACVP server

Current environment:
Client: Ubuntu16.04
Openssl: OpenSSL 1.0.2g  1 Mar 2016

I believe I've followed every step correctly to run the app, the only uncertainty was getting the CA file as it was required in the nist_setup.sh. This is what I've tried to get the .crt file, though I'm not too sure if this command is the right way to do so:
openssl x509 -req -in demo.csr -CA certs/demo_server.cer -CAkey certs/client-key.pem -CAcreateserial -out certs/demo_server.crt -days 1000 -sha256

So if there are any pointers on how to get the CA file, I will be very grateful. I will try a different way in the meantime. 

Any help is much appreciated so thanks in advance!

**Comment by smuellerDD** [comment]
Am Dienstag, 25. Juni 2019, 09:08:31 CEST schrieb shawnyang1:

Hi shawnyang1,

> Hi guys,
> 
> I'm getting an error where it states: "The supplied one time password could
> not be verified". I'm not sure if what I'm doing is correct, but here's the
> process I followed:

Do you have the correct time on your local system?


Ciao
Stephan

**Comment by shawnyang1** [comment]
Hi Stephan,

Yes, I have synced up the time with time.nist.gov, still getting the same result.

**Comment by smuellerDD** [comment]
Am Dienstag, 25. Juni 2019, 09:50:53 CEST schrieb shawnyang1:

Hi shawnyang1,

> Hi Stephan,
> 
> Yes, I have synced up the time with time.nist.gov, still getting the same
> result.

I can log on.

Ciao
Stephan

**Comment by celic** [comment]
Sometimes the `==` at the end of the TOTP_SEED need to be trimmed for the libacvp client.

**Comment by shawnyang1** [comment]
Hi celic,
> Sometimes the `==` at the end of the TOTP_SEED need to be trimmed for the libacvp client.

 I tried that and no luck.

I've also just double checked my system's time and fetched the CA file using openssl s_client but I'm still getting: "error" : "The supplied one time password could not be verified"

**Comment by celic** [comment]
@Kritner can you and Jason take a look at this? @shawnyang1 can you send a login request and post here the approximate time it was issued?

**Comment by celic** [comment]
It should be noted that the `ACV_CA_FILE` should be the file provided by the `libacvp` client within the `certs/` folder. It is titled `acvp.nist.gov.crt` and if you do not have that file, you can download it by pulling the latest of the `libacvp` client. The TOTP algorithm uses information from this file to construct the login token. 

Just to be very explicit, `ACV_CA_FILE` is the `acvp.nist.gov.crt` file provided in the `libacvp` client and corresponds to ONLY the NIST Demo server. The `ACV_CERT_FILE` is your personal cert which was provided from the CSR to NIST. @jarnold01 correct me if I'm wrong here on the CSR. 

If you have any other questions about the cert files specifically, use the `libacvp` repository issues as they will be able to help better than we can.

**Comment by bfussell** [comment]
One note about using ACV_CA_FILE=acvp.nist.gov.crt. It does not always work for us, that's why we've included certs/mozzila_trust_anchors.pem. In any case, that should not be triggering the TOTP error you are seeing.

**Comment by celic** [comment]
Correct, you'd receive a cURL related error SSL if that file was incorrect. @bfussell I'm curious to hear that the cert doesn't work sometimes. I have not had any issues with it on the demo server. That discussion might make sense in a different issue if it persists.

**Comment by shawnyang1** [comment]
Thanks for the clarifications. I've pulled the latest version and switched to using that CA file from certs folder, though the TOTP issue still occur. Here's my login request:

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    certs/acvp.nist.gov.crt
    ACV_CERT_FILE:  certs/demo_cert.cer
    ACV_KEY_FILE:   certs/client_key.pem

***ACVP [STATUS][log_network_status:1000]--> POST Login...
	Status: 401
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp:
{
  "acvVersion" : "1.0",
  "error" : "The supplied one time password could not be verified"
}

***ACVP [STATUS][acvp_login:1847]--> Login Send Failed
***ACVP [ERR][acvp_run:2225]--> Failed to login with ACVP server

And here's the time I sent this request: Fri Jun 28 10:32:16 NZST 2019

**Comment by jarnold01** [comment]
@shawnyang1 Can you login to https://nfiles.nist.gov and send to me (using jason.arnold@nist.gov) the certificate you're using and the TOTP seed value please?  (Please do not send via regular email.) I want to verify that you're properly configured and everything matches server side.

If you can't login and need me to send you an invite, just send me the email address you want me to use and I'll send the nfiles invite to that address. Thanks.

**Comment by shawnyang1** [comment]
Hi @jarnold01 I have sent you an email through https://nfiles.nist.gov. Please have a look at the attachments.
Thanks.

**Comment by manuvimalmohan** [comment]
Hi @jarnold01 , please note that I have mailed you the requested information.

**Comment by jarnold01** [comment]
Okay thanks gentlemen - appreciate the follow up. I'll have a look now.

**Comment by jarnold01** [comment]
Hi @manuvimalmohan , I found the email you sent me via nfiles (thanks), but I can't access the attachments on the message - I get a message saying "Access has been withdrawn by the sender." 
![AccessWithdrawnBySender](https://user-images.githubusercontent.com/41693372/61103164-ed705380-a43e-11e9-871c-b0dff76bc954.PNG)

You are welcome to try sending them again, or just pasting the contents of each file into the nfiles message itself if that's easier. Apologies for the trouble.

**Comment by manuvimalmohan** [comment]
Thanks @jarnold01, I have mailed you now.

**Comment by shawnyang1** [comment]
Thanks @jarnold01 and everyone, can access the demo server now with the new TOTP seed.
