### ISSUE TITLE
Documentation for ECDSA is internally inconsistent

### ISSUE THREAD

**Issue by mlindner** [usnistgov/ACVP#673]
The file acvp_sub_ecdsa.txt specifies that results should be returned in a "testResults" array, but the example json given for all tests uses "testGroups" followed by "tests" sections.

Additionally, for signature generation the tests seem to require that the same Qx and Qy be used for all tests, however that was not done using previous CAVS testing methodology where every test had a different Qx and Qy.

**Comment by smuellerDD** [comment]
Am Donnerstag, 27. Juni 2019, 01:34:17 CEST schrieb mlindner:

Hi mlindner,

> The file acvp_sub_ecdsa.txt specifies that results should be returned in a
> "testResults" array, but the example json given for all tests uses
> "testGroups" followed by "tests" sections.

Feel free to provide a patch :-)
> 
> Additionally, for signature generation the tests seem to require that the
> same Qx and Qy be used for all tests, however that was not done using
> previous CAVS testing methodology where every test had a different Qx and
> Qy.

That is the intention and here ACVP starts deviating from the old CAVS.

Ciao
Stephan

**Comment by celic** [comment]
Yes, patches are welcome. Otherwise it'll take a little bit of time for us to get to this. And ACVP will deviate from CAVS as @smuellerDD says.
