### ISSUE TITLE
ACVP server takes unreasonable time for generation of test vectors

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#674]
The ACVP server seems to take unreasonable amount of time to generate test vectors.

I am waiting now for 2 hours where most vectors are generated, but some are yet outstanding (187 of 208 are obtained).

testID 2859, 2860

**Comment by smuellerDD** [comment]
Something must be broken. I am still waiting for my remaining 21 test vectors after 5 hours.

**Comment by celic** [comment]
Yeah this one died rather quickly during the run. Do not expect a response from it. We know the issue and are working on a fix. It's not an easy fix unfortunately. I think you had a previous issue where you reported the same behavior which helped us identify the problem. This is the same bug.

**Comment by smuellerDD** [comment]
ok, as you know the issue and working on a fix, let us close the bug

**Comment by celic** [comment]
@smuellerDD You mentioned that _some_ of the vector sets did return. Do you have a vsId for one that did not return?

**Comment by smuellerDD** [comment]
Am Montag, 1. Juli 2019, 17:42:55 CEST schrieb Chris Celi:

Hi Chris,

> @smuellerDD You mentioned that _some_ of the vector sets did return. Do you
> have a vsId for one that did not return?

Pick your choice :-)

ACVPProxy (14:09:02) Status: (Re)Try testID 2859 / vsID 9547 (187 / 208 done)
ACVPProxy (14:09:03) Status: (Re)Try testID 2858 / vsID 9523 (187 / 208 done)
ACVPProxy (14:09:04) Status: (Re)Try testID 2860 / vsID 9618 (187 / 208 done)
ACVPProxy (14:09:04) Status: (Re)Try testID 2859 / vsID 9553 (187 / 208 done)
ACVPProxy (14:09:04) Status: (Re)Try testID 2858 / vsID 9502 (187 / 208 done)
ACVPProxy (14:09:05) Status: (Re)Try testID 2860 / vsID 9625 (187 / 208 done)
ACVPProxy (14:09:05) Status: (Re)Try testID 2859 / vsID 9554 (187 / 208 done)
ACVPProxy (14:09:05) Status: (Re)Try testID 2858 / vsID 9500 (187 / 208 done)
ACVPProxy (14:09:06) Status: (Re)Try testID 2860 / vsID 9633 (187 / 208 done)
ACVPProxy (14:09:06) Status: (Re)Try testID 2859 / vsID 9555 (187 / 208 done)
ACVPProxy (14:09:07) Status: (Re)Try testID 2860 / vsID 9598 (187 / 208 done)
ACVPProxy (14:09:07) Status: (Re)Try testID 2859 / vsID 9559 (187 / 208 done)
ACVPProxy (14:09:07) Status: (Re)Try testID 2860 / vsID 9641 (187 / 208 done)
ACVPProxy (14:09:08) Status: (Re)Try testID 2859 / vsID 9578 (187 / 208 done)
ACVPProxy (14:09:08) Status: (Re)Try testID 2860 / vsID 9615 (187 / 208 done)
ACVPProxy (14:09:09) Status: (Re)Try testID 2859 / vsID 9582 (187 / 208 done)
ACVPProxy (14:09:09) Status: (Re)Try testID 2860 / vsID 9617 (187 / 208 done)
ACVPProxy (14:09:10) Status: (Re)Try testID 2860 / vsID 9619 (187 / 208 done)
ACVPProxy (14:09:32) Status: (Re)Try testID 2859 / vsID 9594 (187 / 208 done)
ACVPProxy (14:09:32) Status: (Re)Try testID 2858 / vsID 9539 (187 / 208 done)
ACVPProxy (14:09:33) Status: (Re)Try testID 2860 / vsID 9626 (187 / 208 done)
ACVPProxy (14:09:33) Status: (Re)Try testID 2859 / vsID 9547 (187 / 208 done)
ACVPProxy (14:09:34) Status: (Re)Try testID 2858 / vsID 9523 (187 / 208 done)
ACVPProxy (14:09:35) Status: (Re)Try testID 2860 / vsID 9618 (187 / 208 done)
ACVPProxy (14:09:35) Status: (Re)Try testID 2859 / vsID 9553 (187 / 208 done)
ACVPProxy (14:09:35) Status: (Re)Try testID 2858 / vsID 9502 (187 / 208 done)
ACVPProxy (14:09:36) Status: (Re)Try testID 2860 / vsID 9625 (187 / 208 done)
ACVPProxy (14:09:36) Status: (Re)Try testID 2859 / vsID 9554 (187 / 208 done)
ACVPProxy (14:09:36) Status: (Re)Try testID 2858 / vsID 9500 (187 / 208 done)
ACVPProxy (14:09:37) Status: (Re)Try testID 2860 / vsID 9633 (187 / 208 done)
ACVPProxy (14:09:37) Status: (Re)Try testID 2859 / vsID 9555 (187 / 208 done)
ACVPProxy (14:09:38) Status: (Re)Try testID 2860 / vsID 9598 (187 / 208 done)
ACVPProxy (14:09:38) Status: (Re)Try testID 2859 / vsID 9559 (187 / 208 done)
ACVPProxy (14:09:38) Status: (Re)Try testID 2860 / vsID 9641 (187 / 208 done)
ACVPProxy (14:09:39) Status: (Re)Try testID 2859 / vsID 9578 (187 / 208 done)
ACVPProxy (14:09:39) Status: (Re)Try testID 2860 / vsID 9615 (187 / 208 done)
ACVPProxy (14:09:40) Status: (Re)Try testID 2859 / vsID 9582 (187 / 208 done)
ACVPProxy (14:09:40) Status: (Re)Try testID 2860 / vsID 9617 (187 / 208 done)
ACVPProxy (14:09:41) Status: (Re)Try testID 2860 / vsID 9619 (187 / 208 done)
ACVPProxy (14:10:03) Status: (Re)Try testID 2859 / vsID 9594 (187 / 208 done)
ACVPProxy (14:10:03) Status: (Re)Try testID 2858 / vsID 9539 (187 / 208 done)
ACVPProxy (14:10:04) Status: (Re)Try testID 2860 / vsID 9626 (187 / 208 done)
ACVPProxy (14:10:04) Status: (Re)Try testID 2859 / vsID 9547 (187 / 208 done)
ACVPProxy (14:10:05) Status: (Re)Try testID 2858 / vsID 9523 (187 / 208 done)
ACVPProxy (14:10:05) Status: (Re)Try testID 2860 / vsID 9618 (187 / 208 done)
ACVPProxy (14:10:06) Status: (Re)Try testID 2859 / vsID 9553 (187 / 208 done)
ACVPProxy (14:10:06) Status: (Re)Try testID 2858 / vsID 9502 (187 / 208 done)
ACVPProxy (14:10:07) Status: (Re)Try testID 2860 / vsID 9625 (187 / 208 done)
ACVPProxy (14:10:07) Status: (Re)Try testID 2859 / vsID 9554 (187 / 208 done)
ACVPProxy (14:10:07) Status: (Re)Try testID 2858 / vsID 9500 (187 / 208 done)
ACVPProxy (14:10:08) Status: (Re)Try testID 2859 / vsID 9555 (187 / 208 done)
ACVPProxy (14:10:08) Status: (Re)Try testID 2860 / vsID 9633 (187 / 208 done)
ACVPProxy (14:10:09) Status: (Re)Try testID 2860 / vsID 9598 (187 / 208 done)
ACVPProxy (14:10:09) Status: (Re)Try testID 2859 / vsID 9559 (187 / 208 done)
ACVPProxy (14:10:09) Status: (Re)Try testID 2860 / vsID 9641 (187 / 208 done)
ACVPProxy (14:10:10) Status: (Re)Try testID 2859 / vsID 9578 (187 / 208 done)
ACVPProxy (14:10:10) Status: (Re)Try testID 2860 / vsID 9615 (187 / 208 done)
ACVPProxy (14:10:11) Status: (Re)Try testID 2859 / vsID 9582 (187 / 208 done)
ACVPProxy (14:10:11) Status: (Re)Try testID 2860 / vsID 9617 (187 / 208 done)
ACVPProxy (14:10:12) Status: (Re)Try testID 2860 / vsID 9619 (187 / 208 done)

Ciao
Stephan
