### ISSUE TITLE
Formerly working credentials now failing

### ISSUE THREAD

**Issue by agl** [usnistgov/ACVP#675]
Credentials that worked within the last couple of weeks (subject `O = Google Inc., CN = BoringCrypto ACVP` and previously provided TOTP seed) now result in

```
HTTP/1.1 403 Forbidden
Expires: 0
Connection: keep-alive
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Content-Type: text/html;charset=UTF-8
Content-Length: 68
Date: Tue, 09 Jul 2019 20:03:02 GMT

<html><head><title>Error</title></head><body>Forbidden</body></html>
```

I don't think I've changed anything.

**Comment by celic** [comment]
@jason.arnold1

**Comment by celic** [comment]
@jarnold01 might be able to help here.

**Comment by jarnold01** [comment]
Hey @agl can you give me an idea of the date/time you received the error (or run it and see if it happens again) please? I'm trying to dig through the logs to investigate. Thanks.

**Comment by jarnold01** [comment]
@agl I'm searching through the logs to investigate, will follow back up on this

**Comment by jarnold01** [comment]
@agl What's interesting is that I don't see the credentials (aka subject) being recorded into the log entry for that timestamp. This makes me think it's not being passed and therefore throwing the FORBIDDEN error message.

`[09/Jul/2019:16:03:02 -0400] &quot;0.232 sec&quot; &quot;POST /acvp/v1/login HTTP/1.1&quot; 403 68 &quot;-&quot; &quot;Go-http-client/1.1&quot;`

In all other entries in the log file, I see the cert subject listed as the first item in each log entry (from other certs), identifying themselves.

Any thoughts from your end? I'm not sure what client you're using.

**Comment by jarnold01** [comment]
I found an older log entry (2019-07-01) for your cert and they usually look something like this:

`CN=BoringCrypto ACVP,O=Google Inc. [01/Jul/2019:16:45:08 -0400] &quot;0.267 sec&quot; &quot;POST /acvp/v1/login HTTP/1.1&quot; 200 381 &quot;-&quot; &quot;Go-http-client/1.1&quot;`

just to show the difference.

**Comment by agl** [comment]
Thanks for pin-pointing that it was a missing certificate. (Including a hint about the source of the error in the HTTP message would be great!)

Is it possible that the configuration of the server has changed recently? From looking into what's happening from the client, I can see that no certificate is being sent. That's because the server is sending a list of acceptable CAs in its TLS CertificateRequest message, but none are the `O = NIST, OU = ITL, CN = NIST CVP Demo CA` CA that has signed the certificate that I have. Therefore it is considered inapplicable and filtered by the client libraries.

Instead, the acceptable CAs appears to be a list of all the users of the demo server. One of them is the `O = Google Inc., CN = BoringCrypto ACVP` certificate that I have, but that's the subject name of the certificate, not the issuer, so doesn't match.

I would guess that there's a PEM file on the server that's supposed to contain the "NIST CVP Demo CA" certificate, but which currently contains all of the issued leaf certificates. The TLS library is thus extracting all the subjects from those certificates and advertising them as the acceptable CAs — but they aren't CA certificates so that doesn't work.

If patch the client library to ignore the server's instructions, then things work. But I fear that this will trip up others.

**Comment by jarnold01** [comment]
Thank you for the insight. I've gone ahead and made a change, can you see if the NIST CVP Demo CA cert appears in the TLS CertificateRequest message now?

**Comment by agl** [comment]
Yep, NIST CVP Demo CA is now advertised as an acceptable CA and that makes it work, thanks!

(Everyone else's subjects are still included too, which includes a bunch of people's names and emails. I don't know if that's a concern.)

**Comment by jarnold01** [comment]
Thanks for confirming it. I'd like to try an experiment with your cert, if you're game to help me test it? Let me know.
