### ISSUE TITLE
Draft versioning

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#677]
@celic @atvassilev 

I was going to update the protocol draft and submit to the IETF datatracker after a PR here.
Since the datatracker requires a bump in the version number shall we create new files here with -01 or just keep -00 and rename/update content before submitting to IETF ?

Thanks !

**Comment by celic** [comment]
It would make sense if everything was kept consistent, but that means every time we submit to the datatracker we have to update all the links within this project. README, wiki, etc. 

So it is probably easier to just give the datatracker what it asks for and nothing more. I am working on updating files to use Metanorma, and they take out the pain with updating versions and such.

**Comment by celic** [comment]
Can this be closed out?
