### ISSUE TITLE
FIPS DRBG prediction resistance and reseed question

### ISSUE THREAD

**Issue by mlindner** [usnistgov/ACVP#678]
For DRBG800-90A (CTR), the FIPS certifications specify that testing should be run with prediction resistance set to True OR reseed set to True. However it seems that the test vectors that can and are generated have both of these set to True. What is the expected behavior when both of these are true? It would appear to me that this is an invalid configuration that shouldn't be supported by ACVP.

**Comment by smuellerDD** [comment]
Am Freitag, 19. Juli 2019, 02:13:51 CEST schrieb mlindner:

Hi mlindner,

> For DRBG800-90A, the FIPS certifications specify that testing should be run
> with prediction resistance set to True OR reseed set to true. However it
> seems that the test vectors that can and are generated have both of these
> set to true. What is the expected behavior when both of these are true? It
> would appear to me that this is an invalid configuration that shouldn't be
> supported by ACVP.

Why would that test approach be invalid? You would have to run the following:

Instantiate DRBG(EntropyInput, PersonalizationString, Nonce, ...)
Reseed(EntropyInputReseed, AdditionalInputReseed)
Generate(EntropyInputPR1, AdditionalInputPR1) but don't output
Generate(EntropyInputPR2, AdditionalInputPR2) and output
Uninstantiate

See an example implementation at https://github.com/smuellerDD/
acvpparser/blob/master/backends/backend_openssl.c#L2168

Ciao
Stephan

**Comment by celic** [comment]
The expectations are outlined in the DRBG specification. See this table taken directly from the specification...

```
   +---------------------------------------+---------------------------+
   | Prediction Resistance Assurance       | Test Procedure            |
   | Options                               |                           |
   +---------------------------------------+---------------------------+
   | "predResistanceEnabled" : true;       |                           |
   | "reseedImplemented": true             |                           |
   |                                       | Instantiate DRBG          |
   |                                       | Generate but don't output |
   |                                       | Generate output           |
   |                                       | Uninstantiate             |
   |                                       |                           |
   | "predResistanceEnabled" : false;      |                           |
   | "reseedImplemented" : true            |                           |
   |                                       | Instantiate DRBG          |
   |                                       | Reseed                    |
   |                                       | Generate but don't output |
   |                                       | Generate output           |
   |                                       | Uninstantiate             |
   |                                       |                           |
   | "predResistanceEnabled" : true/false; |                           |
   | "reseedImplemented": false            |                           |
   |                                       | Instantiate DRBG          |
   |                                       | Generate but don't output |
   |                                       | Generate output           |
   |                                       | Uninstantiate             |
   +---------------------------------------+---------------------------+
```

Could you point me to the guidance that makes you think this is invalid? Perhaps we could clean that up.

**Comment by mlindner** [comment]
> Instantiate DRBG(EntropyInput, PersonalizationString, Nonce, ...)
Reseed(EntropyInputReseed, AdditionalInputReseed)
Generate(EntropyInputPR1, AdditionalInputPR1) but don't output
Generate(EntropyInputPR2, AdditionalInputPR2) and output
Uninstantiate

This isn't a valid procedure according to previous CAVP documentation. https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/drbg/DRBGVS.pdf

It's either ReSeed OR Prediction Resistance, not both. Additionally common criteria/FIPS certification also specifies that these two tests be done independently and not at the same time.

**Comment by mlindner** [comment]
> ```
>    +---------------------------------------+---------------------------+
>    | Prediction Resistance Assurance       | Test Procedure            |
>    | Options                               |                           |
>    +---------------------------------------+---------------------------+
>    | "predResistanceEnabled" : true;       |                           |
>    | "reseedImplemented": true             |                           |
>    |                                       | Instantiate DRBG          |
>    |                                       | Generate but don't output |
>    |                                       | Generate output           |
>    |                                       | Uninstantiate             |
>    |                                       |                           |
>    +---------------------------------------+---------------------------+
> ```

That seems to imply that the reseed values are ignored, according to that test procedure, if prediction resistance is true.

**Comment by smuellerDD** [comment]
Am Freitag, 19. Juli 2019, 23:52:26 CEST schrieb mlindner:

Hi mlindner,

> > Instantiate DRBG(EntropyInput, PersonalizationString, Nonce, ...)
> 
> Reseed(EntropyInputReseed, AdditionalInputReseed)
> Generate(EntropyInputPR1, AdditionalInputPR1) but don't output
> Generate(EntropyInputPR2, AdditionalInputPR2) and output
> Uninstantiate
> 
> This isn't a valid procedure according to previous CAVP documentation.
> https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validatio
> n-Program/documents/drbg/DRBGVS.pdf

The old CAVS test definitions are not applicable any more.
> 
> It's either ReSeed OR Prediction Resistance, not both. Additionally common
> criteria/FIPS certification also specifies that these two tests be done
> independently and not at the same time.



Ciao
Stephan

**Comment by mlindner** [comment]
> The old CAVS test definitions are not applicable any more.

Hi, the CAVS tests may not be but the certification documents certainly are.

**Comment by celic** [comment]
Can you point us to the certification documents? They could potentially require an update. And yes, if prediction resistance is enabled, the reseed option is essentially ignored.

**Comment by mlindner** [comment]
> Can you point us to the certification documents? They could potentially require an update. And yes, if prediction resistance is enabled, the reseed option is essentially ignored.

Ok, thanks, that basically answers the situation and makes this compatible with CAVP then. So this hasn't changed.

**Comment by celic** [comment]
Ok. If you think the issue is resolved please mark it as closed.
