### ISSUE TITLE
FF1 issue - possible maxlen issue

### ISSUE THREAD

**Issue by dghgit** [usnistgov/ACVP#681]
**testSessionId**
7314

**vsId**
22350

**Algorithm registration**
[ACVP-AES-FF1.zip](https://github.com/usnistgov/ACVP/files/3440634/ACVP-AES-FF1.zip)
(start point is request.json, .req.json file is vectors from server, .rsp.json our response, .res.json the server response to our response).

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443/acvp/v1/testSessions GET

**Expected behavior**
Expecting test to pass.

We're finding that as messages get longer we start to get errors - it's also dependent on the radix, the larger the radix, errors in messages appear at shorter lengths. For example with a radix of 10, errors start showing up on input lengths of around 31.

**Additional context**
We've checked the problem messages against another implementation in go, and they appear to pass there as well. We're using Java, so our implementation is based on the BigInteger library. SP 800-38G does rely on being able to represent radix**u and radix**v where u and v are the two "half lengths" of the input - for what we are getting back from the server it seems the value of radix**u and radix**v is limited on the server, while it is not in our library. At radix values longer than 10 errors start showing up correspondingly earlier.

Assuming this is really what is happening, I should point out I'm not saying there shouldn't be any limit in size of acceptable inputs for a given radix (clearly this could get out of hand), but if there is it would help if it was documented and the server should refuse to generate out of range inputs.

**Comment by Kritner** [comment]
@dghgit I'll take a look at our implementation, thanks for the heads up.

**Comment by Kritner** [comment]
@dghgit would you be able to provide your `P` and from the first round `Q`, `R`, `S`, `y`, `c`, and `C` values for the following test? I did find an issue on our end, but I'm still coming up with a different answer for at a minimum several of the values from your issue vector set:

```json
{
	"tgId": 1,
	"testType": "AFT",
	"direction": "Encrypt",
	"keyLen": 128,
	"alphabet": "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ",
	"radix": 62,
	"tweakLen": [{
		"min": 0,
		"max": 128,
		"increment": 8
	}],
	"tests": [{
		"tcId": 2,
		"tweak": "C82E75AE4361F965648FE5BF5B83C195",
		"tweakLen": 128,
		"pt": "lUnLs5KrrKXwJu6axnE2obK6",
		"key": "01B6932FF610BC056CCF223F5BB10C92"
	}]
}
```

**Comment by dghgit** [comment]
Sure, if it's us as well I'd certainly like to know about it! Here's a full dump - it didn't turn out to be that big, so I thought it might help. If you need anything else, please let me know.

P: 01020100003e0a0c0000001800000010
round: 0
Q: c82e75ae4361f965648fe5bf5b83c19500000000000000804f717cc5db8aa5f6
R: 845d8d41d53e5d4c8979578706572a60
S: 845d8d41d53e5d4c8979578706572a60
y: 845d8d41d53e5d4c8979578706572a60
c: 706938d58104c523da
C: 1538172f1c052e1b1b2e3b20
(q, r): (1d02613f5b1a01539, c)
(q, r): (77c7c3161d529a1, 3b)
(q, r): (1ee93a9a5a25d5, b)
(q, r): (7fa1fa3b42ac, 2d)
(q, r): (20effe82e7e, 28)
(q, r): (87fff9da7, c)
(q, r): (2318c49b, 1d)
(q, r): (90ea65, 25)
(q, r): (2565c, 1d)
(q, r): (9a6, 28)
(q, r): (27, 34)
(q, r): (0, 27)
round: 1
Q: c82e75ae4361f965648fe5bf5b83c19500000000000001706938d58104c523da
R: 130df4a3e836c8b5288706cef21746d3
S: 130df4a3e836c8b5288706cef21746d3
y: 130df4a3e836c8b5288706cef21746d3
c: a83bf119864610dcc9
C: 2d1e060a21172802180b2e06
(q, r): (2b6a4ebc43aefc17f, 7)
(q, r): (b343559dfeb17c4, 7)
(q, r): (2e42eccdef258b, 1a)
(q, r): (bf03d1c5ebf5, 35)
(q, r): (314b4ee8c10, 15)
(q, r): (cb8987e21, 12)
(q, r): (348696ad, 3b)
(q, r): (d8e165, 37)
(q, r): (37f81, 27)
(q, r): (e71, 23)
(q, r): (3b, 27)
(q, r): (0, 3b)
round: 2
Q: c82e75ae4361f965648fe5bf5b83c19500000000000002a83bf119864610dcc9
R: 3855fb11a7e347f3f8e62a9776a045c8
S: 3855fb11a7e347f3f8e62a9776a045c8
y: 3855fb11a7e347f3f8e62a9776a045c8
c: 1e4b8c755be12a19a2
C: 2734281d251d0c282d0b3b0c
(q, r): (7d16e91e62997406, 2e)
(q, r): (2047fa185b82708, 16)
(q, r): (854a3a33063b9, 3a)
(q, r): (2265bc7043ac, 11)
(q, r): (8e072b19dd, 26)
(q, r): (24a702dd6, 9)
(q, r): (9756c18, 6)
(q, r): (270e21, 1a)
(q, r): (a142, 25)
(q, r): (299, 34)
(q, r): (a, 2d)
(q, r): (0, a)
round: 3
Q: c82e75ae4361f965648fe5bf5b83c195000000000000031e4b8c755be12a19a2
R: a78b534d571ea462f659fe6fae53a675
S: a78b534d571ea462f659fe6fae53a675
y: a78b534d571ea462f659fe6fae53a675
c: 3b2f617e94d25fd33e
C: 3b272327373b1215351a0707
(q, r): (f4608a4cb9120fcb, 14)
(q, r): (3f10a7d1bc25b17, 39)
(q, r): (10465cdb49540c, 2f)
(q, r): (43330bcb815b, 2)
(q, r): (11577eea31e, 17)
(q, r): (479ad23a9, 30)
(q, r): (127a88d5, 13)
(q, r): (4c4c87, 23)
(q, r): (13b0a, 1b)
(q, r): (514, 32)
(q, r): (14, 3c)
(q, r): (0, 14)
round: 4
Q: c82e75ae4361f965648fe5bf5b83c195000000000000043b2f617e94d25fd33e
R: 79e7afd2578b2501e2c1f9ecba410d0c
S: 79e7afd2578b2501e2c1f9ecba410d0c
y: 79e7afd2578b2501e2c1f9ecba410d0c
c: 88e58414e1b99706ae
C: 0a2d34251a060926113a162e
(q, r): (2354010da59b3fbfa, 22)
(q, r): (91defc1750f4a41, 3c)
(q, r): (25a4e63790c343, 7)
(q, r): (9b6f11698f89, 15)
(q, r): (281ca9a7a0e, 25)
(q, r): (a59fa3bc6, 1a)
(q, r): (2abdd7ac, 1e)
(q, r): (b07b38, 1c)
(q, r): (2d8b2, 1c)
(q, r): (bc0, 32)
(q, r): (30, 20)
(q, r): (0, 30)
round: 5
Q: c82e75ae4361f965648fe5bf5b83c1950000000000000588e58414e1b99706ae
R: 685f206768024b275c7661d9c1d8382f
S: 685f206768024b275c7661d9c1d8382f
y: 685f206768024b275c7661d9c1d8382f
c: 5bff2149006bf8ab6d
C: 143c321b23133017022f3914
(q, r): (17bdb60252b0823cc, 5)
(q, r): (6207108db8863ac, 24)
(q, r): (194c254ddd09dd, 26)
(q, r): (687436eeeb83, 23)
(q, r): (1af4b3566e5, d)
(q, r): (6f4d37124, 2d)
(q, r): (1cb91678, 14)
(q, r): (769922, 3c)
(q, r): (1e9b2, 6)
(q, r): (7e5, 3c)
(q, r): (20, 25)
(q, r): (0, 20)
round: 6
Q: c82e75ae4361f965648fe5bf5b83c195000000000000065bff2149006bf8ab6d
R: f325c23b88ed62538194a96b01241b56
S: f325c23b88ed62538194a96b01241b56
y: f325c23b88ed62538194a96b01241b56
c: 67c49fd3bd7eee9204
C: 3020321c1c1e1a2515073c22
(q, r): (1ac7630d5a3145d31, 26)
(q, r): (6e921d1e5ba2289, 3)
(q, r): (1c88cdb540f00a, 1d)
(q, r): (75d1c4fceb18, 3a)
(q, r): (1e67aeb4e1d, 12)
(q, r): (7d8b136ef, 3b)
(q, r): (2065f47f, 2d)
(q, r): (85c602, 3)
(q, r): (2285a, 36)
(q, r): (8e8, 2a)
(q, r): (24, 30)
(q, r): (0, 24)
round: 7
Q: c82e75ae4361f965648fe5bf5b83c1950000000000000767c49fd3bd7eee9204
R: f2e87d33db4654d0ced8e4b66112a802
S: f2e87d33db4654d0ced8e4b66112a802
y: f2e87d33db4654d0ced8e4b66112a802
c: 102c325415ff71436f
C: 20253c063c142d0d23262405
(q, r): (42c7015b318a15bb, 25)
(q, r): (113b9d40d2fa583, 1)
(q, r): (4727b2980c4bb, 39)
(q, r): (125cd340032c, 13)
(q, r): (4bd1dbdf04, 34)
(q, r): (1390feef3, 2a)
(q, r): (50ca4e2, 37)
(q, r): (14d95e, 1e)
(q, r): (5616, a)
(q, r): (163, 1c)
(q, r): (5, 2d)
(q, r): (0, 5)
round: 8
Q: c82e75ae4361f965648fe5bf5b83c19500000000000008102c325415ff71436f
R: f164b37f63257a1d9b6f9fd85099ac32
S: f164b37f63257a1d9b6f9fd85099ac32
y: f164b37f63257a1d9b6f9fd85099ac32
c: 82595ae7c256c2fe36
C: 24302a36032d3b123a1d0326
(q, r): (21a3724c532f2a100, 36)
(q, r): (8ae4f0b704e3c67, e)
(q, r): (23d7fc0e32cf6d, 1)
(q, r): (93ffefb67f37, 1b)
(q, r): (2631882f189, 9)
(q, r): (9db3beb1f, 7)
(q, r): (28b283ca, 33)
(q, r): (a80a62, e)
(q, r): (2b5d8, 12)
(q, r): (b30, 38)
(q, r): (2e, c)
(q, r): (0, 2e)
round: 9
Q: c82e75ae4361f965648fe5bf5b83c1950000000000000982595ae7c256c2fe36
R: 23ca796cd6831a67108cf11160cf11f3
S: 23ca796cd6831a67108cf11160cf11f3
y: 23ca796cd6831a67108cf11160cf11f3
c: 9b3a6f091625d69562
C: 052d1c0a1e372a3413390125
(q, r): (280f1465711205d3f, 20)
(q, r): (a5678e05f3e751d, 39)
(q, r): (2aaf5e75262b2d, 37)
(q, r): (b03f75809d99, 1f)
(q, r): (2d7bbb39f71, 3b)
(q, r): (bbcd57a50, 11)
(q, r): (30770e5c, 8)
(q, r): (c81d22, 20)
(q, r): (33a46, 2e)
(q, r): (d53, 2c)
(q, r): (37, 1)
(q, r): (0, 37)
ct: KcUieP79r1eST1IKw8hXvTVw

**Comment by Kritner** [comment]
@dghgit tyvm! that was most helpful! :)
Was getting an unchecked overflow in our `c` calculation due incorrect data type; a fix should be in the next deployment to demo.

**Comment by dghgit** [comment]
Great to hear. Will test on next update.

**Comment by Kritner** [comment]
@dghgit this update has been pushed to demo, please let us know if there are any issues encountered.

**Comment by dghgit** [comment]
I've run a few separate runs now, all looks good at this end.  No issues detected.
