### ISSUE TITLE
Error with RSA Vector Generation

### ISSUE THREAD

**Issue by iabent** [usnistgov/ACVP#682]
Hey there, I am getting an error when asking the server for an RSA Keygen Vector Set:

Registration:
[{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"RSA","revision":"1.0","mode":"keyGen","prereqVals":[{"algorithm":"SHA","valValue":"same"},{"algorithm":"DRBG","valValue":"same"}],"infoGeneratedByServer":false,"pubExpMode":"random","keyFormat":"standard","capabilities":[{"randPQ":"B.3.3","properties":[{"modulo":2048,"hashAlg":["SHA2-256"]}]}]}]}]

Response:
[ {
  "acvVersion" : "1.0"
}, {
  "vsId" : 22923,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 22923"
} ]

Any idea what problem we could be hitting? Thanks so much.

**Comment by smuellerDD** [comment]
Am Dienstag, 30. Juli 2019, 15:08:59 CEST schrieb iabent:

Hi iabent,

> Hey there, I am getting an error when asking the server for an RSA Keygen
> Vector Set:
> 
> Registration:
> [{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"RSA","revision":"1.0","mo
> de":"keyGen","prereqVals":[{"algorithm":"SHA","valValue":"same"},{"algorithm
> ":"DRBG","valValue":"same"}],"infoGeneratedByServer":false,"pubExpMode":"ran
> dom","keyFormat":"standard","capabilities":[{"randPQ":"B.3.3","properties":[
> {"modulo":2048,"hashAlg":["SHA2-256"]}]}]}]}]
> 
> Response:
> [ {
>   "acvVersion" : "1.0"
> }, {
>   "vsId" : 22923,
>   "status" : "error during vector generation",
>   "message" : "failed to generate tests for: 22923"
> } ]
> 
> Any idea what problem we could be hitting? Thanks so much.

Prime test missing?

My request that is successful looks like

```
      {
        "revision":"1.0",
        "algorithm":"RSA",
        "mode":"keyGen",
        "infoGeneratedByServer":false,
        "pubExpMode":"random",
        "keyFormat":"standard",
        "capabilities":[
          {
            "randPQ":"B.3.3",
            "properties":[
              {
                "modulo":2048,
                "primeTest":[
                  "tblC2"
                ]
              },
              {
                "modulo":3072,
                "primeTest":[
                  "tblC2"
                ]
              }
            ]
          }
        ],
        "prereqVals":[
          {
            "algorithm":"SHA",
            "valValue":"same"
          },
          {
            "algorithm":"DRBG",
            "valValue":"same"
          }
        ]
      }
```

Ciao
Stephan

**Comment by iabent** [comment]
We figured out the issue, thank you for your time! Much appreciated.
