### ISSUE TITLE
More thorough validation of `testSession` [POST] prior to returning a test session.

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#684]
**testSessionId**
n/a

**vsId**
n/a

**Algorithm registration**
n/a

**Endpoint in which the error is experienced**
https://[acvpUrl]/acvp/testSessions [POST]

**Expected behavior**
When a capabilities/registration object is posted, the registration should be validated as fully as possible prior to returning a success status and/or test session id.  Certain algorithms due to their complex rules around their registration are able to get past this "initial test session creation" and are not "failed" until the internal processing takes over.  Ideally, this more complex validation could be done immediately, rather than waiting until the internal processing takes over.

Example issues where "bad registration values" were not detected until internal processing took over:
#682, #629, probably a few others

**Comment by celic** [comment]
Coming with Web Public release.
