### ISSUE TITLE
Additional error information provided to clients in case of failure

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#685]
**testSessionId**
n/a

**vsId**
n/a

**Algorithm registration**
n/a

**Endpoint in which the error is experienced**
n/a

**Expected behavior**
Messages relevant to "client fixable" errors should be passed in responses to the client where possible.  Currently clients will receive errors like:

```json
[ {
  "acvVersion" : "1.0"
}, {
  "results" : {
    "vsId" : 0,
    "disposition" : "error",
    "message" : "generation executable failed for: 0"
  }
} ]
```

and

```json
[ {
  "acvVersion" : "1.0"
}, {
  "results" : {
    "vsId" : 0,
    "disposition" : "error",
    "message" : "validation executable failed for: 0"
  }
} ]
```

Often, there is more information that could be provided to the client, information such as (from the generation side) issues with the registration (note this is seems like it will have a fair amount of overlap with #684).  From the validation side, we would be able to provide information to the client such as missing information that was expected in their submitted answers, if data is in an unexpected format, etc.

Related issues:
#680, #682, #629

**Comment by celic** [comment]
Coming with Web Public release.
