### ISSUE TITLE
FF3-1 testing troubles

### ISSUE THREAD

**Issue by dghgit** [usnistgov/ACVP#689]
**testSessionId**
20270

**vsId**
37755

**Algorithm registration**
Zip contains registration request, response from server (.req.json), our response (.rsp.json), results from server (.res.json).
[ACVP-AES-FF3-1.zip](https://github.com/usnistgov/ACVP/files/3513932/ACVP-AES-FF3-1.zip)

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443/acvp/v1/testSessions/20270 GET

**Expected behavior**
I guess I was expecting this one to pass. FF3-1 is a bit trickier though, but instead I got total failure. We've tested the output against a modified version FF3 with tweak change we found in go and it produces the same results we do.

**Additional context**
Here's some sample output for the first vector:

"tgId": 1,
"testType": "AFT",
"direction": "Encrypt",
"keyLen": 128,
"alphabet": "0123456789",
"radix": 10,
"tests": [
{
"tcId": 1,
"tweak": "3F096DE35BFA31",
"tweakLen": 56,
"pt": "319155",
"key": "339BB5B1F2D44BAABF87CA1B7380CDC8"
}]

key: 339bb5b1f2d44baabf87ca1b7380cdc8
radix: 10
tweak: 3f096de35bfa31
pt: 319155
modified tweak: 3f096de05bfa3130
i: 0
y: b405424d3989c3cecab1569b14293cc0
c: 239
i: 1
y: 2e46a4b10b22e856cbce753d7ccd01c
c: 3bb
i: 2
y: 4a2a5ed9b38b754db2e2b938f8acec39
c: e2
i: 3
y: 40b78c82a29420a835e19fd56eabcf5e
c: 149
i: 4
y: 285c967333c8167121b0b83c7cbc522e
c: 250
i: 5
y: cd433e7a84094545337ed7b859706d51
c: 10a
i: 6
y: 6104e2a0c10e8560e3215aa502abcea
c: 22a
i: 7
y: 4f6f6db8864c1b10be4e3d73f9155d0
c: ea
ct: 455432

If you need anything else, please let me know.

**Comment by Kritner** [comment]
@dghgit thanks, I'll take a look; yeah this one was a fun one having no existing nist vectors to test against.  I'm guessing it has something to do with the breaking up of the tweak value but I'll try to confirm that sometime today.

**Comment by Kritner** [comment]
Looks like it was indeed an issue with how the tweak value was split up, a fix should be in the next deployment to demo.

**Comment by dghgit** [comment]
I can confirm that the hot fix deployment yesterday fixed this one. Looks good from our end. Thanks.
