### ISSUE TITLE
Update symmetric spec to account for valid AAD length values for AES-CCM

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#69]
From the symmetric spec:

![image](https://cloud.githubusercontent.com/assets/8814983/23761702/a559f5de-04c1-11e7-80d5-1a9597f8ac73.png)

Currently the CCM -> AAD information does not account for the fact that AAD lengths of 2^16 can be tested.  It may make sense to state that AAD lengths of 2^16 can be specified, as that is currently the maximum value allowed ***for testing purposes***.  

If ranges are implemented as suggested in #67, the `aadLen` registration could become:
```

{
	"aadLen": {
		"min": 0,
		"max": 65536
	}
}

```

In the above, test vectors would continue to be generated for aadLens of 0 through 32, but additional testing would also be done on 2^16.  At this time, the additional testing would be minimal to help keep json sizes smaller.

**Comment by bfussell** [comment]
Sounds good to me.
