### ISSUE TITLE
ACVP-AES-CBC-CS1 MCT tests weirdness

### ISSUE THREAD

**Issue by dghgit** [usnistgov/ACVP#694]
**testSessionId**
21820

**vsId**
41231

**Algorithm registration**
This is the full transcript. The *.rsp.* file contains our responses. request.json is the original registration.
[ACVP-AES-CBC-CS1.zip](https://github.com/usnistgov/ACVP/files/3558615/ACVP-AES-CBC-CS1.zip)

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443//acvp/v1/testSessions GET

**Expected behavior**
I think this one should be passing. CS3 and CS2 are now both passing fully and all the CS1 AFT tests pass. It fails from round zero but I can't see anything different in the setup for CS1 compared with the others.

**Additional context**
We're using common code for the MCT test for all 3, so I'm reasonably sure nothing's crept in (mind you, I have thought that before...)

**Comment by Kritner** [comment]
@dghgit yeah thankfully we're using the same code for all 3 MCTs as well, and just differing transformation strategies for the differences between the CS1,2,3 modes.

Here's what I have for a CBC-CS1 MCT encrypt with a 128 bit key:

inner loop

```
i: 0, j: 0
Iv: 00000000000000000000000000000000
Key: 00000000000000000000000000000000
Payload: 000000000000000000000000000000000000000000000000
Ciphertext: 66E94BD4EF8A2C3BF795BD4A52E29ED713D313FA20E98DBC
i: 0, j: 1
Iv: F795BD4A52E29ED713D313FA20E98DBC
Key: 00000000000000000000000000000000
Payload: 0000000000000000000000000000000066E94BD4EF8A2C3B
Ciphertext: A10CF66D0FDDF340F800D5A85882F8029F6B44A40D9BF012
i: 0, j: 2
Iv: F800D5A85882F8029F6B44A40D9BF012
Key: 00000000000000000000000000000000
Payload: 66E94BD4EF8A2C3BF795BD4A52E29ED713D313FA20E98DBC
Ciphertext: 75B1290665D7BBEC847E8E8DFA610BDAA2E68BD6C73E54FE
i: 0, j: 3
Iv: 847E8E8DFA610BDAA2E68BD6C73E54FE
Key: 00000000000000000000000000000000
Payload: A10CF66D0FDDF340F800D5A85882F8029F6B44A40D9BF012
Ciphertext: 33AF76C0F76B33CB4C421BEF2C46035FD441FA7066BB306A
i: 0, j: 4
Iv: 4C421BEF2C46035FD441FA7066BB306A
Key: 00000000000000000000000000000000
Payload: 75B1290665D7BBEC847E8E8DFA610BDAA2E68BD6C73E54FE
Ciphertext: 1EC74898C1AF2DC59816C496918BA55995B082F3CFBFD933
i: 0, j: 5
Iv: 9816C496918BA55995B082F3CFBFD933
Key: 00000000000000000000000000000000
Payload: 33AF76C0F76B33CB4C421BEF2C46035FD441FA7066BB306A
Ciphertext: 47B4900EFE4AD48632ED8EFD79EE582EBFDB99F2DD99A097
i: 0, j: 6
Iv: 32ED8EFD79EE582EBFDB99F2DD99A097
Key: 00000000000000000000000000000000
Payload: 1EC74898C1AF2DC59816C496918BA55995B082F3CFBFD933
Ciphertext: 69A5C128501EE55F4F5C31B5A7ACF5DAF4FC00A6D5125841
i: 0, j: 7
Iv: 4F5C31B5A7ACF5DAF4FC00A6D5125841
Key: 00000000000000000000000000000000
Payload: 47B4900EFE4AD48632ED8EFD79EE582EBFDB99F2DD99A097
Ciphertext: BFA9914BE22F37D5CB5B830162AB3BFC988B5BF7BD24C56C
i: 0, j: 8
Iv: CB5B830162AB3BFC988B5BF7BD24C56C
Key: 00000000000000000000000000000000
Payload: 69A5C128501EE55F4F5C31B5A7ACF5DAF4FC00A6D5125841
Ciphertext: A7B4CA261B9A10FBF3CC2340003237AA46C7E5B5B3D072DE
i: 0, j: 9
Iv: F3CC2340003237AA46C7E5B5B3D072DE
Key: 00000000000000000000000000000000
Payload: BFA9914BE22F37D5CB5B830162AB3BFC988B5BF7BD24C56C
Ciphertext: 5AAC33A31670EF233311640142F89B2640AD4A5D8CF46DF9
i: 0, j: 10
Iv: 3311640142F89B2640AD4A5D8CF46DF9
Key: 00000000000000000000000000000000
Payload: A7B4CA261B9A10FBF3CC2340003237AA46C7E5B5B3D072DE
Ciphertext: 562EAEA1067A04A99C54FD35C63D591F04782BD2D0636549
```

outer loop:

```
i: 0
Iv: 00000000000000000000000000000000
Key: 00000000000000000000000000000000
Payload: 000000000000000000000000000000000000000000000000
CipherText: A7E528E9067C5283A37EDE6AF708A5DC734C5E77EF6DDBD0
i: 1
Iv: A7E528E9067C5283A37EDE6AF708A5DC
Key: A7E528E9067C5283A37EDE6AF708A5DC
Payload: E6E4ED0CE205564DA16BB5B8695AD66F8E65C44D6D52375F
CipherText: 7D6AAD50C052B99A620727B357500AF42D3D6745D4D7721E
i: 2
Iv: 7D6AAD50C052B99A620727B357500AF4
Key: DA8F85B9C62EEB19C179F9D9A058AF28
Payload: A0C00124D10BDA6D0573FB0D0C0E01FD52D9A985B02B9C46
CipherText: 574C36E3641E09FB5C8AB4CCCE08776F381A09845857714C
i: 3
Iv: 574C36E3641E09FB5C8AB4CCCE08776F
Key: 8DC3B35AA230E2E29DF34D156E50D847
Payload: C61D4E1CE9E0B53E184047F7DF2744B0A89D3017BDD029CF
CipherText: D35334AEEDC701178FFA5F66A323CC72BF3A9DD360533BEB
i: 4
Iv: D35334AEEDC701178FFA5F66A323CC72
Key: 5E9087F44FF7E3F512091273CD731435
Payload: 288806F98FC5A7AB3D1A173ADB54C49E4B76E8E98F69E8D0
CipherText: 29A16FF9530041EBE3A50B43C20771DC28112F361C12C805
i: 5
Iv: 29A16FF9530041EBE3A50B43C20771DC
Key: 7731E80D1CF7A21EF1AC19300F7465E9
Payload: 0C18F9D37EBE6945F482792F9BC7B7C2396CB623E48FC30C
CipherText: 5E50A2F8EB689BBBCF338268C11A1163073B3FC768688AD6
i: 6
Iv: 5E50A2F8EB689BBBCF338268C11A1163
Key: 29614AF5F79F39A53E9F9B58CE6E748A
Payload: 681437EAFD598E7BF21848DDBD86CADFC8DFB7746AD06714
CipherText: B59AFA255B4508D346BB5C8266180E40A60EE526270CFABF
i: 7
Iv: B59AFA255B4508D346BB5C8266180E40
Key: 9CFBB0D0ACDA31767824C7DAA8767ACA
Payload: 051E9E67FBD67817E9CF5DCB73CD2488D89AC97F01BC4D26
CipherText: B46EFA55F44C742C3ADFFDE2A873EDB1E176CE297085DADB
i: 8
Iv: B46EFA55F44C742C3ADFFDE2A873EDB1
Key: 28954A855896455A42FB3A380005977B
Payload: BAFE83988B11E344AE4E9F52AA95E8C23E80FE53A9F3275C
CipherText: E27625974886D75776AB3FF3D25EE96FDE976C4098F9D16A
i: 9
Iv: E27625974886D75776AB3FF3D25EE96F
Key: CAE36F121010920D345005CBD25B7E14
Payload: A08BD4C1FFC0A980D3D1B3FEC6FDF59F5C87345CA09607E3
CipherText: 042F5BC2D281956CB53D301EF356B41EA603ADDBFE24C7FE
i: 10
Iv: 042F5BC2D281956CB53D301EF356B41E
Key: CECC34D0C2910761816D35D5210DCA0A
Payload: CABCB56C5DB4ED94376BF7D5491A2A7F5D1F831B7137666C
CipherText: ACDA38D3288220CD30DE0B7070FD0BF3A45EE7586FE839C2
```

**Comment by dghgit** [comment]
I can reproduce, but I'm not entirely sure what is going on.

The source of my confusion is that, in the sample for CS3 encrypt there was:

i: 0, j 0
Iv: 00000000000000000000000000000000
Key: 00000000000000000000000000000000
Payload: 000000000000000000000000000000000000000000000000
CipherText: F795BD4A52E29ED713D313FA20E98DBC66E94BD4EF8A2C3B
i: 0, j 1
Iv: F795BD4A52E29ED713D313FA20E98DBC
Key: 00000000000000000000000000000000
Payload: 00000000000000000000000000000000F795BD4A52E29ED7
CipherText: 7187BFD1F3F23F0A34559761B6027FEBA10CF66D0FDDF340

In this case the iv at the second step is the first 16 bytes of the previous cipher text, The same also applies for CS2.

in CS1 encrypt we've got:

i: 0, j: 0
Iv: 00000000000000000000000000000000
Key: 00000000000000000000000000000000
Payload: 000000000000000000000000000000000000000000000000
Ciphertext: 66E94BD4EF8A2C3BF795BD4A52E29ED713D313FA20E98DBC
i: 0, j: 1
Iv: F795BD4A52E29ED713D313FA20E98DBC
Key: 00000000000000000000000000000000
Payload: 0000000000000000000000000000000066E94BD4EF8A2C3B
Ciphertext: A10CF66D0FDDF340F800D5A85882F8029F6B44A40D9BF012

in which case the iv at the second step is the last 16 bytes of the previous cipher text.

CS1 is a bit different from the other two, and I can certainly take this difference in construction of the IVs into account but I'm curious to know what the rational for the difference is? Would appreciate clarification. Thanks.

**Comment by dghgit** [comment]
I guess I should add I don't have access to the underlying cipher, I'm using the JCE so I have to work out what the IV should be from the padded output. Thinking about it the expected output would be correct if you could go directly off the underlying cipher, so I probably should be handling this differently from CS2 and CS3. Would appreciate confirmation. If that is the case, it might be worth mentioning this property of the CS modes in the RFC as well the finalization step on each iteration is quite different from the other MCT tests.

**Comment by Kritner** [comment]
@dghgit we're not making any modifications to the IV per inner loop round for any of the CS1,2,3 modes.  

The underlying crypto updates the original byte array passed in to it, which is then passed in for the next inner loop round.  The only time we're making any modifications for the IV from the MCT standpoint is when we're setting up the next iteration of the outer loop.

Does that make sense?  It shouldn't be any different from any of the CS1,2,3 modes, unless I've missed something. 

> In this case the iv at the second step is the first 16 bytes of the previous cipher text, The same also applies for CS2.
> in which case the iv at the second step is the last 16 bytes of the previous cipher text.

I don't think it's a function of first or last bytes, as it sounds like you're looking at it from the standpoint of *after* the CS1,2,3 transform.  Additionally if you were always using the first 16 bytes of the CT for CS2, that would also run into problems, as CS2 is a conditional swap of the last two blocks of CT when working with complete blocks.

**Comment by dghgit** [comment]
That makes sense. Yes, it's not quite first/last bytes, that was more a product of the payload size. To make it clear for anyone looking at this later, the actual expression in Java, when trying to recover the iv from the result of the transform while executing the inner loop is:

        int ivStart = mode.equals("CS1") ? 
                                    input.length - iv.length : 
                                    input.length - (input.length % iv.length + iv.length);

I've tried a few different payload sizes now with all variants. This one can be classified as working. Thanks for the help.
