### ISSUE TITLE
AES-GMAC: Testvector seems to not contain an IV

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#695]
Requesting an AES-GMAC test vector returns the vector without an IV although ivLen is larger than zero.

Wouldn't I need an IV?

vsID: 41951

**Comment by Kritner** [comment]
@smuellerDD your registration:

```json
{
	"vsId": 41951,
	"isSample": false,
	"algorithm": "ACVP-AES-GMAC",
	"revision": "1.0",
	"direction": ["encrypt", "decrypt"],
	"keyLen": [128, 192, 256],
	"ivLen": [8, 96, 1024],
	"ivGen": "internal",
	"ivGenMode": "8.2.2",
	"aadLen": [128, 1024, 120, 960],
	"tagLen": [32, 64, 96, 104, 112, 120, 128]
}
```

specifies an "internal" IV generation (from the perspective of the IUT) - meaning that the expectation is the IUT should supply the IVs within their response file.  External should be used when the ACVP server is to generate the IVs.

**Comment by smuellerDD** [comment]
Oops, my bad.

Thanks for spotting this!
