### ISSUE TITLE
RSA keygen test results not processed

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#697]
When uploading RSA keygen results, I get the following verdict:

```
[ {
  "acvVersion" : "1.0"
}, {
  "results" : {
    "vsId" : 41966,
    "disposition" : "error",
    "message" : "validation executable failed for: 41966"
  }
} ]
```

**Comment by Kritner** [comment]
@smuellerDD I'm not super familiar with the validation process of RSA perhaps @celic can confirm, but with a cursory look, it seems that the validator is being tripped up due to missing some required information in your response file.

The registration:

```json
{
	"vsId": 41966,
	"isSample": false,
	"algorithm": "RSA",
	"mode": "keyGen",
	"revision": "1.0",
	"infoGeneratedByServer": false,
	"pubExpMode": "random",
	"keyFormat": "standard",
	"capabilities": [{
		"randPQ": "B.3.6",
		"properties": [{
			"modulo": 2048,
			"hashAlg": ["SHA2-224", "SHA2-256", "SHA2-384", "SHA2-512"],
			"primeTest": ["tblC2"]
		}, {
			"modulo": 3072,
			"hashAlg": ["SHA2-224", "SHA2-256", "SHA2-384", "SHA2-512"],
			"primeTest": ["tblC2"]
		}]
	}]
}
```

Expected some values (may not be a comprehensive list) for the B.3.6 type:

```
XP
XQ
Bitlens[]
XP1
XP2
XQ1
XQ2
```

**Comment by Kritner** [comment]
#685 also related

**Comment by smuellerDD** [comment]
With a new test response I think I provide all data. Yet, ACVP server returns:

```
[ {
  "acvVersion" : "1.0"
}, {
  "results" : {
    "vsId" : 42540,
    "disposition" : "error",
    "message" : "validation executable failed for: 42540"
  }
} ]
```

vsID: 42540

**Comment by celic** [comment]
The client as well needs to provide the public exponent `e` in this case. The JSON for vsId 42540 does not contain an `e` value. 

Aside from that, there was a separate error on the server in this case where the `bitlens[]` was not being passed to the key reconstruction mechanism properly. I have fixed that for the next deployment, but the current files cannot be validated without a public exponent in the JSON.

**Comment by smuellerDD** [comment]
I added the e and the n values (both were missing last time). Yet, the ACVP server does not process the response with the error given above.

vsID: 45092

**Comment by celic** [comment]
There were 2 issues. I fixed a bug on our end for the next demo release.
The second issue was that the e value was not included. Stay tuned for the
hotfix to go on demo this week.

**Comment by smuellerDD** [comment]
Thank you. We now get verdicts from the ACVP server. Though, some show failures (i.e. some results show a pass and some a failure). Allow us to keep this issue open until we have debugged whether these failures are caused on our side or on the ACVP server side.

If you want to see the results with the partial failures: vsID 48202

**Comment by smuellerDD** [comment]
I found the issue for the partial failures on our side. RSA keygen B.3.6. now fully works.

Thanks.
