### ISSUE TITLE
AES-CCM: test responses rejected

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#698]
During upload of the test response for CCM, I get the following server error:

```
{
  "acvVersion" : "1.0",
  "error" : "Incorrectly formatted JSON (34653:4): no result values for tcId: 542"
}
```

Looking at tcId 542, I see nothing wrong:

```
    }, {
      "tcId" : 542,
      "key" : "192D18A583E1D508C842A20347B28E94",
      "aad" : "",
      "iv" : "602C38C89EE23C",
      "ct" : "46667893"
```

Do you happen to have any ideas?

vsID 42524

**Comment by Kritner** [comment]
@smuellerDD is this:

```
 }, {
      "tcId" : 542,
      "key" : "192D18A583E1D508C842A20347B28E94",
      "aad" : "",
      "iv" : "602C38C89EE23C",
      "ct" : "46667893"
```

from the prompt file? or your response? I'm not exactly sure what you're asking about here, but this is the first failure test from this particular group, where we'd expect from the IUT a `"testPassed": false`, or a `"pt": "[plain text]"` in instances of a successful decrypt.

**Comment by smuellerDD** [comment]
Am Mittwoch, 4. September 2019, 14:53:58 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD is this:
> 
> ```
>  }, {
>       "tcId" : 542,
>       "key" : "192D18A583E1D508C842A20347B28E94",
>       "aad" : "",
>       "iv" : "602C38C89EE23C",
>       "ct" : "46667893"
> ```
> 
> from the prompt file? or your response?

This is from the response. The ACVP server says it rejects my response file 
for exactly this tcId. It looks pretty identical to all other responses.

> I'm not exactly sure what you're
> asking about here, but this is the first failure test from this particular
> group, where we'd expect from the IUT a `"testPassed": false`, or a `"pt":
> "[plain text]"` in instances of a successful decrypt.

Note, the test requests an encryption which we performed here and listed the 
ciphertext.



Ciao
Stephan

**Comment by Kritner** [comment]
From this vector's prompt file delivered to the IUT:

```
{
      "tgId": 55,
      "testType": "AFT",
      "direction": "decrypt",
      "keyLen": 128,
      "ivLen": 56,
      "payloadLen": 0,
      "aadLen": 0,
      "tagLen": 32,
      "tests": [
        {
          "tcId": 541,
          "key": "16A401B603472F10996243AE65A1A3FE",
          "aad": "",
          "iv": "56E584202000EE",
          "ct": "70E5CDB9"
        },
        {
          "tcId": 542,
          "key": "192D18A583E1D508C842A20347B28E94",
          "aad": "",
          "iv": "602C38C89EE23C",
          "ct": "46667893"
        },
```

@smuellerDD I'm still not following, this group is a decrypt group, but I'm interpreting:

> Note, the test requests an encryption which we performed here and listed the
ciphertext.

as you're attempting to run an encrypt on the provided test?

The expectation for the provided two tests would be:

```
"tgId": 55,
      "tests": [
        {
          "tcId": 541,
          "pt": ""
        },
        {
          "tcId": 542,
          "testPassed": false,
        },
```

Is that what you're providing in your submitted response? I can't see enough in what information is currently recorded for this vector set to see the response file you're attempting to post

**Comment by smuellerDD** [comment]
I am terribly sorry to waste your time, this was an issue on my side.
