### ISSUE TITLE
RSA PSS: fail to generate a test vector with saltlen > 0

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#699]
When I request an RSA PSS vector with saltlen == 0, I get vectors.

When I request an RSA PSS vector with saltlen > 0, I get:

```
[ {
  "acvVersion" : "1.0"
}, {
  "vsId" : 43419,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 43419"
} ]
```

**Comment by Kritner** [comment]
I don't know the specific reasoning behind this particular validation logic, but the salt len of 64 is not valid for sha-512 and a modulo of 1024, the max allowed salt len in this case is 62. #685 also related.

**Comment by smuellerDD** [comment]
thanks
