### ISSUE TITLE
Need hooks for data expiration policy and management in ACVP

### ISSUE THREAD

**Issue by atvassilev** [usnistgov/ACVP#7]
A new issue from NIST Sprint 1:

Need to establish some boundaries around when data will expire. This includes:
How long should registration/capabilities be available before test vectors are retrieved?
How long should test vectors be available after they are retrieved? It is it even necessary to keep them?
How long should a test id be active before it is no longer possible to submit test results?
Should the length of time be based on last interaction or total time taken?

Need to think how all these should be handled by the ACV protocol.

**Comment by jfigus** [comment]
I'll take a look at this and draft a new section in the top-level spec to address expiration.

**Comment by atvassilev** [comment]
I reviewed the text. It looks good, just a couple of suggestions for improvement.

1. Section 12, end of first paragraph" "... when the the client attempts to download the vector set or submit KATs for validation. 

2. In section 12.1 the implied behavior is that submitting results for validation does NOT extend the expiry date. In my view the text also implies that the client can submit as many corrected responses as needed as long as all of them arrive before the expiry date. This is fine with me, just suggest the following sentence be added to third paragraph in Section 12, right after the first sentence" "... The server may change the expiration timestamp of a previously issued vector set to either extend or shorten its lifetime subject to server policy." Here I am thinking about cases when the server discovers an error in the tests and wants to invalidate vector sets already sent to clients.

Please let me know if you have have questions or concerns.

**Comment by jfigus** [comment]
Thanks for the feedback.  I'll add the suggested text that you provided.

**Comment by atvassilev** [comment]
Fixed with revisions 15234a8 and 2ae0dfa
