### ISSUE TITLE
DSA key gen with Sophie Germain prime

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#700]
This may relate to issue #529.

I uploaded test results for DSA key gen where my IUT is only able to generate keys with MODP 14, i.e. a Sophie Germain prime.

The definition takes the P and G values implemented by the IUT and hard-codes the Q value to (P-1)/2.

The ACVP server is unable to verify the keys but does not tell what exactly is wrong.

May I ask for your help identifying the issue?

vsID: 45091

**Comment by celic** [comment]
Yeah I'll take a look this week. Our DSA implementation is a strict following of FIPS 186-4. I haven't given thought to how/if a hard-coded Q value would be supported by our implementation.

**Comment by celic** [comment]
Is this appropriate to close now?
