### ISSUE TITLE
ECDSA siggen P-521 failures

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#701]
My IUT generates signatures for P224/256/384 and 521. All signatures are verified by the ACVP server as correct signatures except those for P521. As the ECC implementation is identical for all curves, the IUT is expected to calculate the P521 signatures correctly.

Yet, the ACVP server flags the P521 signatures all as wrong but does not give a specific hint on what is wrong. Looking at the sizes of the buffers, we have:

R and S are always 66 bytes.
Qx and Qy are 65 or 66 bytes, depending on the fact whether the leading bit is set or not. I expect that the issue lies in the formatting of these point values.

May I ask to help me in identifying the issue?

Thanks

vsID: 45136

**Comment by celic** [comment]
I'll take a look this week on this. As long as the values are a complete number of bytes in hex (even number of characters), the parsing we have shouldn't be the issue. I'll try to confirm soon.

**Comment by smuellerDD** [comment]
Apologies for the noise, again an issue on our side where I did not get the output lengths of the R and S buffers straight for P-521.
