### ISSUE TITLE
ACVP server rejects response with KAT_RECEIVED

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#702]
When uploading a seemingly fine response, I sometimes get:

```
{
  "acvVersion" : "1.0",
  "error" : "Results for Vector Set id: 47071 cannot be submitted with status: KAT_RECEIVED"
}
```

What does that mean?

**Comment by smuellerDD** [comment]
I also get errors like these:

```
{
  "acvVersion" : "1.0",
  "error" : "Results for Vector Set id: 47069 cannot be submitted with status: PASSED"
}
```

Note, all responses are uploaded for the first time.

**Comment by smuellerDD** [comment]
it seems that they are issues when a KAT is already uploaded - my proxy contained a bug where I uploaded data twice

**Comment by celic** [comment]
Regardless, this error could be a bit cleaner for the client to understand what is happening. We will note it for our side of things at least... It is definitely not one I've seen before.
