### ISSUE TITLE
RSA decryption primitive: generate key once

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#704]
Currently the RSA spec requires that for each tcID a key needs to be provided. For signature generation, however, the key is only needed to be provided once for a given modulus (i.e. tgId). Shouldn't the RSA decryption primitive be changed to match the signature generation definition wrt the key generation? I.e. require a key generation to be performed for one given tgId?

**Comment by celic** [comment]
Decryption Primitive is a very odd case for the CAVP. It is not directly tied to a crypto standard but is related to some of NIST's PIV standards if I recall correctly. We have plans of reevaluating these tests down the road but do not have a timeframe. 

The way it is implemented now was to match CAVS. Unfortunately I don't think we will make any changes to it until we are looking at it in its entirety.

**Comment by dmchodnicki** [comment]
ACVP Technical Team has decided to not do much on Decryption Primitive tests. Overall, the tests are not that useful and are not expected to be used with any frequency.  No action is currently planned and this item is being Closed.
