### ISSUE TITLE
AES-GCM-SIV does not provide IV length

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#705]
Hello!

It appears that the demo server does not currently provide the ivLen field in JSON for the AES-GCM-SIV algorithm. In the block cipher spec documentation ("Prompt Test Group Authenticated Block Cipher Applicability Grid"), it appears that this field is supposed to be provided.

(Note that tagLen, which also has a static value for this algorithm and is in the table, is provided by the server JSON).

Thanks!

**Comment by celic** [comment]
Ah. I see the confusion. I'm not sure if this warrants a fix though. The specification outlines the static values used for the properties. It could imply that those properties should appear, but that is not the intention. I'll clean this up a little.
