### ISSUE TITLE
Key Derivation Function ANS9.42 and PB Documentation Seems Incorrect

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#707]
The documentation for these two algorithms seems incorrect:
https://usnistgov.github.io/ACVP/artifacts/draft-celi-acvp-ans-x942.html
and
https://usnistgov.github.io/ACVP/artifacts/draft-celi-acvp-pbkdf.html

In the case of ANS9.42, the table describes the registration payload with the following table:
![image](https://user-images.githubusercontent.com/3537360/65833366-bb33fc80-e29d-11e9-99e6-c5b45caaebab.png)

But the example looks like this:
![image](https://user-images.githubusercontent.com/3537360/65833370-c6872800-e29d-11e9-8ae9-17ebb3dd9314.png)

I believe that the table is the one that is incorrect.

In the second example, the table lists the following:
![image](https://user-images.githubusercontent.com/3537360/65833381-ee768b80-e29d-11e9-89ac-87eb6d52f645.png)

But the example provided is:
![image](https://user-images.githubusercontent.com/3537360/65833393-ffbf9800-e29d-11e9-9c2d-66fd0c479637.png)

The table suggests that there are 6 keys with the object of the _capabilities_ array, but the example doesn't mirror this structure.  The table also suggests the the _prereqVals_ are contained within the capabilities array object which might also be incorrect.

**Comment by celic** [comment]
I'm not sure I follow for ANS x9.42, could you be more specific on the discrepancy? 

For PBKDF, the table is (mostly) correct, the example is incorrect. Prereqvals are indeed NOT in the capabilities array.

**Comment by AlexThurston** [comment]
@celic 
I guess my confusion is bred from the example having a key called `capability_exchange` which is an array of the objects described in the table.  This structure is different from of the other sections I read.  Section 5 of that document has this in it:
```
ACVP requires crypto modules to register their capabilities. This allows the crypto module to advertise support for specific algorithms, notifying the ACVP server which algorithms need test vectors generated for the validation process.

The algorithm capabilities are advertised as JSON objects within the 'algorithms' value of the ACVP registration message. The 'algorithms' value is an array, where each array element is an individual JSON object defined in this section. The 'algorithms' value is part of the 'capability_exchange' element of the ACVP JSON registration message. See the ACVP specification for more details on the registration message.
```

But when I register other algorithms, the payload of the POST does not contain anything about a `capability_exchange`

**Comment by AlexThurston** [comment]
I'll mention that I also think my question about the PBKDF section was also because the style in which the payload is documented is different from the others.  I might be wrong, but it seemed that normally this information would be divided into two tables, one contain the root wrapper, and another table defining what would/could be expected within the objects of the `capabilities`.

Since they were different, I wasn't sure if there was a concept I was missing.

**Comment by celic** [comment]
Yeah the `capabilities_exchange` does seem a bit odd. These examples are meant to highlight the individual capabilities, not as much the outer structure. But even with that in mind, they should at least be consistent across various documents. 

For PBKDF here, I was using a new tool (metanorma) to generate the XML that was used to generate the TXT and HTML files. As a result some of the formatting might be a bit different than previous documents. It still probably makes sense to break out those into separate tables as it isn't the clearest to have a self-referencing table.
