### ISSUE TITLE
Submission, Re-submission, and Request of Vector Set Responses Seem "Stuck"

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#709]
**testSessionId**
`33210`

**vsId**
`61776`

**Algorithm registration**
```json
{
    "algorithm": "RSA",
    "mode": "sigGen",
    "revision": "1.0",
    "prereqVals": [],
    "capabilities": [
        {
            "sigType": "pkcs1v1.5",
            "properties": [
                {
                    "modulo": 4096,
                    "hashPair": [
                        {
                            "hashAlg": "SHA2-224"
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Endpoint in which the error is experienced**
`https://demo.acvts.nist.gov/acvp/v1/testSessions/33210/vectorSets/61776/results`

**Expected behaviour**
As I tested interacting with the ACVP, I was observing the responses and results to submitting vector set response payloads with errors in them.  As I did so, I ended up in a situation where the route above seems to permanently be returning:
```json
{
  "results": {
    "disposition": "incomplete",
    "vsId": 61776
  },
  "retry": 30
}
```

Based on the discussions in the linked issues below, it seems as though this isn't something that should be happening.  The expectation would be that I can continue to update responses until they all pass.

**Additional context**
As I trolled through the issue to see if this had already been covered addressed, I came across https://github.com/usnistgov/ACVP/issues/258 and https://github.com/usnistgov/ACVP/issues/214

They are both closed but they did seem related.

**Comment by celic** [comment]
Do you still have the last JSON you sent to the server through the POST? The latest I see from the server contains 
```
2AB502EB335B77D023155609464BD640C88C21BFD255AA392D076DFFA166A541238D7F1D641ADF093A61562FA1525708B33332258C103A71140E522C5107BDCC122EBAEB041B55D867630FECFE33F535057A6D5AEC168576105DCFFB74F8AD4025E20DDFD7143FE0CCFC9475DE554ED2723D28A582DC81A12BBD214031392DEDB988F45FE68502A4097C999B23FF1CB827D66552B37B200173353A51EAE2028A31BF204316B7F7AAE21C6FBC9EF040B702D8B9D50581DBA6CC1556832FEAC0CDFB5882BDBB92B527C2E9ED0C6F0FD9653551FD1CB7B769719825AF31ADC19C141C38C5E117A9E6632014D03FB81C4512B34B74C9C132382FD3135325EFA9CEE3FB52278B0247658EC217980B4E9932EFE683F82A8AC8C9AF2ACA9A77EB76CB4B223DE579E6D6617E30C27EEDC64DF60374C633703231644EEB9617BD2C0DCCBC22D945984947EB2D31ECC87712D1AE739D6898F7A754442B038D01CB89F908C63904752EA994B549459146C4C2F9E3FC59B1F093331F93AD0294C4C4ED998448B999F5A2B172E9FBC57D3DD7C082EEF0230B10066211FA4112B0C60FE7CD8076F5C290B1A3F58E74807772DDB1C39B45C81E362BFCB8C73644F3A953187A9924BC7A6A385F6DB79CA29885ED4C272681708B826B717460A701308456B82BAAAA406E8C85A6E5502FD3CBBC2E36A8F9E67D8A80A97B885C22EB6653DBAA8C78D5
```
as a signature for the first test case. Does that match up with the last file you sent? 

And just to confirm, this only happens for resubmission for a vector set you had already sent a response JSON file for?

It has definitely terminated from the back end (and failed). I'll pass this along to the right person.

**Comment by AlexThurston** [comment]
I was actually POSTing/PUTting several times with varying failures in different places to see how it responded so I'm not entirely sure where it messed up.

> And just to confirm, this only happens for resubmission for a vector set you had already sent a response JSON file for?

I can't say for certain since I haven't done this a huge number of times but I do seem to remember observing this kind of behaviour before.  This is the first time I made a concerted effort to capture empirical data.

**Comment by smuellerDD** [comment]
Am Donnerstag, 3. Oktober 2019, 22:05:24 CEST schrieb Chris Celi:

Hi Chris,
> 
> And just to confirm, this only happens for resubmission for a vector set you
> had already sent a response JSON file for?

Are you now saying that updating of submitted test responses with the PUT 
operation finally works?

I tried that several weeks ago and it was not working at that time.


Ciao
Stephan

**Comment by AlexThurston** [comment]
I did some more testing and have a few more data points.  It appears as though if you submit responses with failures and follow up with submitting responses that are correct, the system behaves as you would expect.

However, if you submit vector response with failures and subsequent submit a second set that also contains failures, this is when the ACVP system gets into the unexpected state listed above.

TsID: `33353` VsID: `61955` contains an example where the first and second submit contained errors and the behaviour exhibits the issue described originally.

TsID: `33354` VsID: `61956` contains an example where the first submit contains errors and the second is correct.  In this situation the system behaved as expected.
