### ISSUE TITLE
KAS - "error during vector generation"

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#711]
We're trying to generate test vector sets for KAS FFC/ECC.
We tried KAS ECC-static unified and the component test,
KAS FFC-MQV2, DH Hydrid One Flow, MQV1-all with the same issue below.

**testSessionId**
33693

**vsId**
62303

**Algorithm registration**
KAS ECC

**Comment by Kritner** [comment]
@AndrewHYang this is due to a parameter set not being provided in your scheme registration:

```json
{
	"vsId": 62303,
	"isSample": true,
	"algorithm": "KAS-ECC",
	"revision": "1.0",
	"function": ["keyRegen"],
	"scheme": {
		"staticUnified": {
			"kasRole": ["initiator"],
			"kdfKc": {
				"parameterSet": {},
				"kdfOption": {
					"concatenation": "uPartyInfo||vPartyInfo"
				},
				"kcOption": {
					"nonceType": ["randomNonce"],
					"kcRole": ["recipient"],
					"kcType": ["unilateral"]
				},
				"dkmNonceTypes": ["timestamp", "sequence"]
			}
		}
	}
}
```

Parameter set registration information starts at https://usnistgov.github.io/ACVP/artifacts/acvp_sub_kas_ecc.html#rfc.section.3.6.1 in the spec.

Related #684

**Comment by AndrewHYang** [comment]
@Kritner Thanks. But how about KAS-ECC CDH-Component. It does not have a parameter set.
For example,

testSessionId
33808

vsId
62617

Algorithm registration
KAS ECC

**Comment by AndrewHYang** [comment]
And I still experienced the same issue while testing KAS-ECC ephemeralUnified with "parameterSet".

testSessionId
33933

vsId
62742

Algorithm registration
KAS ECC

**Comment by Kritner** [comment]
62617:

```json
{
	"vsId": 62617,
	"isSample": true,
	"algorithm": "KAS-ECC",
	"mode": "CDH-Component",
	"revision": "1.0",
	"curve": ["P-256", "K-283", "B-283"]
}
```

This looks like it may be a bug on our side, it looks like CAVS required assurance functions (the `functions` property in the registration), that carried over to this algorithm's registration.  This seems like it should not be the case.  We can put in a fix that will correct this, but in the meantime if you could supply any valid function you should at least be able to get test vectors.

62742

```json
{
	"vsId": 62742,
	"isSample": true,
	"algorithm": "KAS-ECC",
	"revision": "1.0",
	"function": ["dpGen"],
	"scheme": {
		"ephemeralUnified": {
			"kasRole": ["initiator"]
		}
	}
}
```

above is the registration I have as being posted, can you confirm?  This seems to have less properties than the previous attempt.

**Comment by AndrewHYang** [comment]
For 62742
I might send more than just these for registration. I'll check whether something is wrong on my side or yours. Will get back to you later.

**Comment by AndrewHYang** [comment]
For vsId 62742, my end should have sent more than what your end received.

Please also check the test session below,
testSessionId
34086

vsId
62924

Algorithm registration

```sh
[ 
   { 
      "acvVersion":"1.0"
   },
   { 
      "algorithms":[ 
         { 
            "prereqVals":[ 
               { 
                  "algorithm":"CCM",
                  "valValue":""
               },
               { 
                  "algorithm":"CMAC",
                  "valValue":""
               },
               { 
                  "algorithm":"DRBG",
                  "valValue":""
               },
               { 
                  "algorithm":"ECDSA",
                  "valValue":""
               },
               { 
                  "algorithm":"HMAC",
                  "valValue":""
               },
               { 
                  "algorithm":"SHA",
                  "valValue":""
               }
            ],
            "function":[ 
               "dpGen"
            ],
            "scheme":{ 
               "ephemeralUnified":{ 
                  "kasRole":[ 
                     "initiator"
                  ],
                  "kdfKc":{ 
                     "parameterSet":{ 
                        "eb":{ 
                           "hashAlg":[ 
                              "SHA2-224"
                           ],
                           "macOption":{ 
                              "HMAC-SHA2-256":{ 
                                 "keyLen":[ 
                                    256
                                 ],
                                 "macLen":64
                              }
                           },
                           "curve":"K-233"
                        }
                     },
                     "kdfOption":{ 
                        "asn1":"uPartyInfo||vPartyInfo"
                     },
                     "kcOption":{ 
                        "nonceType":[ 
                           "randomNonce"
                        ],
                        "kcRole":[ 
                           "recipient"
                        ],
                        "kcType":[ 
                           "unilateral"
                        ]
                     }
                  }
               }
            },
            "algorithm":"KAS-ECC",
            "revision":"1.0"
         }
      ],
      "encryptAtRest":false,
      "isSample":true
   }
]
```

**Comment by Kritner** [comment]
@AndrewHYang sorry I missed it previously, but `KeyConfirmation` is not possible for the scheme `EphemeralUnified`.  This very much touches on #684 as mentioned previously; but we have not yet been able to get to this enhancement.

**Comment by AndrewHYang** [comment]
@Kritner And can you update the spec of KAS ECC/FFC? With some of the info you mentioned, and there is no "dkmNonceTypes" in the spec, which is needed by dhStatic

**Comment by Kritner** [comment]
I covered the dkmNonceTypes in #715, though I think the other two things were covered in the spec already, though easy to miss.  If you have a better way in mind to call these specific things out, feel free to suggest or open a PR.

At least one parameter set is required:

![image](https://user-images.githubusercontent.com/8814983/66566135-2ef1c700-eb32-11e9-90c5-082a4c976e4c.png)

KeyConfirmation not allowed for specific scheme:

![image](https://user-images.githubusercontent.com/8814983/66566095-184b7000-eb32-11e9-990e-5d3784923d65.png)

Same holds true for the ECC spec.

I believe that was everything, but let me know if anything was missed, thanks!

**Comment by AndrewHYang** [comment]
Got it. Thanks @Kritner

**Comment by Kritner** [comment]
No problem @AndrewHYang, was there anything outstanding in this issue that you can see? If not feel free to close.
