### ISSUE TITLE
Dependency Route Body Format

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#713]
**testSessionId**
n/a

**vsId**
n/a

**Algorithm registration**
n/a

**Endpoint in which the error is experienced**
GET `https://demo.acvts.nist.gov/acvp/v1/dependencies/75`
GET `https://demo.acvts.nist.gov/acvp/v1/dependencies`

**Expected behaviour**
The object that is returned when you list or get a dependencies is somewhat confusing.  The object appears to have an empty key who's value is the name, and the `name` field is empty.

The documentation describes the structure as the following:
https://htmlpreview.github.io/?https://github.com/usnistgov/ACVP/blob/master/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.11.13

But `GET`ing on these routes produces objects that look more like:
```json
{
          "": "TI OMAP4",
          "description": null,
          "name": "",
          "type": "",
          "url": "/acvp/v1/dependencies/17"
}
```

I would expect them to look more like:
```json
{
          "name": "TI OMAP4",
          "description": null,
          "type": "",
          "url": "/acvp/v1/dependencies/17"
}
```

**Additional context**

**Comment by Kritner** [comment]
This should be corrected on dependencies going forward, but may require data updates to correct any data that's currently out there.  Let us know if does not seem to be the case
