### ISSUE TITLE
Requests that appear to be "stuck" processing

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#716]
**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
POST https://demo.acvts.nist.gov/acvp/v1/persons
and
GET https://demo.acvts.nist.gov/acvp/v1/requests/1024

**Expected behaviour**
I might be drawing some parallels between this issue and another (https://github.com/usnistgov/ACVP/issues/709) that are unrelated, but I have a situation where I requested the creation of an entity (in this case a *person*) and the request appears to stuck in the `processing` state.  In the linked issue, I had a similar situation where I attempted to update a set of vector set responses after a failure where the backend had failed but the status was still being reported as *processing*. 

**Additional context**
The request ID that is _stuck_ is `1024`

In this vein, when I list all my request, I have a couple that are _stuck_ in processing and have been for quite some time.  I would have expected that over time I'd have some resolution on whether they have been approved or not and a reason associated with it if it failed.

**Comment by celic** [comment]
#719 duplicate it seems.

**Comment by AlexThurston** [comment]
Are you certain that these are duplicates?  I believe the issue @smuellerDD raised was about creating a test session with a large number of algorithms and the test vector generation getting stuck.

Mine was about creating a new person and it getting stuck.

**Comment by Kritner** [comment]
@celic this issue seems to relate to the auto approval process on demo, so I would say it's a separate issue

**Comment by celic** [comment]
Hmm. Was this item not auto-approved to be stuck in `processing`?

**Comment by Kritner** [comment]
@AlexThurston I've discovered an issue on this endpoint and am implementing a fix.  It should be in our next fix to demo.  Have you discovered this issue on any other endpoints you can recall?

**Comment by Kritner** [comment]
Unfortunately it was minor tweak to the person endpoint, so it wouldn't be further reaching than that.  The issue specifically was around not properly handling null email addresses.

**Comment by Kritner** [comment]
The fix for this is out on demo.  Let us know if you have any issues.

**Comment by AlexThurston** [comment]
I can confirm on demo that I can now create a person without an email address and it worked.  Thanks for the fix.
