### ISSUE TITLE
Generation of vectors stuck

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#719]
I am trying to get a whole new set of vectors for a large number of cipher implementations from the ACVP server (some 350 vsIDs in total). Unfortunately, I get about 90%, the rest appears stuck. After stopping the request and starting a new fresh request for the 350 vsIDs, the ACVP server again gets stuck.

See, for example:

test sessions 34560, 34548, 34550
vsIDs: 63968, 63948, 63986, 64082 and others

**Comment by Kritner** [comment]
@smuellerDD we've tweaked some settings on the demo side, hopefully you'll see some improvement.

**Comment by Kritner** [comment]
@AlexThurston that's... interesting... it doesn't look like that particular session has been picked up for processing yet, that was being returned from the 

https://acvts.nist.gov/acvp/v1/testSessions/34591/vectorSets/64420

endpoint?  Are you still seeing that? I wonder if it could have been in some sort of state change at the time of being queried.

**Comment by AlexThurston** [comment]
This is very strange.  I am now able to get test vectors for that test session.  It just took a lot longer than I normally observe but perhaps I just need to be more patient.

**Comment by Kritner** [comment]
We're hopeful that the queues won't ever be excessive, we have the capability to scale, but are currently tweaking to find the right balance.

**Comment by smuellerDD** [comment]
Am Dienstag, 15. Oktober 2019, 17:07:28 CEST schrieb Russ Hammett:

Hi Russ,

> We're hopeful that the queues won't ever be excessive, we have the
> capability to scale, but are currently tweaking to find the right balance.

Ok, but maybe you can report how many queues you support during a logon 
(similarly to the report of the maximum size for large file submission). In 
this case, you can limit queues the hard way.

Ciao
Stephan

**Comment by celic** [comment]
It isn't the queues that we are concerned about. It is how many items we can pop off the queue at a time on our processing cluster. We do not want to limit the number of items a client can request. The server should seamlessly handle any number.

**Comment by Kritner** [comment]
We see that things are still getting stuck, we'll be doing some additional tweaking

**Comment by smuellerDD** [comment]
To me, it is working now.

**Comment by bfussell** [comment]
@Kritner @celic 
I'm seeing something similar to #732 after submitting the simplest RSA keyGen registration.

[{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"RSA","revision":"1.0","mode":"keyGen","prereqVals":[{"algorithm":"SHA","valValue":"same"},{"algorithm":"DRBG","valValue":"same"}],"infoGeneratedByServer":true,"pubExpMode":"fixed","fixedPubExp":"010001","keyFormat":"standard","capabilities":[{"randPQ":"B.3.4","properties":[{"modulo":2048,"hashAlg":["SHA2-256"]}]}]}]}]


  "vsId" : 72162,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 72162"

Did I miss a change in the registration requirements ?

**Comment by celic** [comment]
No change in registration. This is an issue on our part. We are working on it.

**Comment by Kritner** [comment]
Hey @bfussell, we found an issue on our end that may crop up for RSA until we can get another hotfix out.  Opening your specific problem into another issue as to keep this one more focused on our environment tweaking efforts.
