### ISSUE TITLE
Undocumentated API for validations

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#720]
**environment**
Demo

**testSessionId**
`34612`

**vsId**
`64612`

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/validations

The initial issue here is that the validations route doesn't seem to be documented in the API documentation.

In lieu of it not being there, I started poking the system to find out what it supported.  If I do a `GET` on `https://demo.acvts.nist.gov/acvp/v1/validations`, I half expected it to give me a list of the validations similar to how the other routes on resources works.  Barring that, I thought it might give me a 404 not found.  However, it looks like it's causing a 500 on the back end.
```
{
  "acvVersion" : "1.0",
  "error" : "Internal Server Error. Please contact administrator for assistance."
}
```

**Expected behaviour**
That the routes available would be documented and the ones that aren't wouldn't cause a 500.

**Additional context**
It looks like a get with a validation specified (ie. `https://demo.acvts.nist.gov/acvp/v1/validations/31206`) works OK but again is not documented.

This might actually end up being two separate issues.  The first would be the missing documentation and then second would be causing the 500s on the backend.

**Comment by AlexThurston** [comment]
Curiously, I just tried again after raising this issue and it appears to be working now.

**Comment by smuellerDD** [comment]
Am Dienstag, 15. Oktober 2019, 18:48:00 CEST schrieb Alex Thurston:

Hi Alex,


Just for the records, I am not using such a RESTAPI endpoint for my ACVP 
Proxy. Yet, I successfully validated different IUTs.

Ciao
Stephan

**Comment by AlexThurston** [comment]
Fair enough.  While it's true that I was able to exercise submitting a test session with passing results and have it return to me a validation without this route, the object that is returned has a field which suggest that a `GET` would be valid.  That's what lead to me try GET on that route.  The GET does appear to be working (aside from my previous instances of receiving 500s when trying) but I believe that it should be documented (along with the other operations that are valid on that resource).

In addition, the question has come up about how FIPS validators would go about editing certificates going forward.  I have the idea that (for example) OEs are sometimes added to existing certificates which were achieve through CAVS and was wondering if perhaps that functionality was added as `PUT`s or `POST`s to that route `/acvp/v1/validations/{id}` route.

**Comment by smuellerDD** [comment]
Am Dienstag, 15. Oktober 2019, 22:04:58 CEST schrieb Alex Thurston:

Hi Alex,

> Fair enough.  While it's true that I was able to exercise submitting a test
> session with passing results and have it return to me a validation without
> this route, the object that is returned has a field which suggest that a
> `GET` would be valid.  That's what lead to me try GET on that route.  The
> GET does appear to be working (aside from my previous instances of
> receiving 500s when trying) but I believe that it should be documented
> (along with the other operations that are valid on that resource).
> 
> In addition, the question has come up about how FIPS validators would go
> about editing certificates going forward.  I have the idea that (for
> example) OEs are sometimes added to existing certificates which were
> achieve through CAVS and was wondering if perhaps that functionality was
> added as `PUT`s or `POST`s to that route `/acvp/v1/validations/{id}` route.

This is currently performed for all public certs of A3 or A6 through A12 - 
just monitor those in the next days. The update of the cert is transparent for 
us "users" as long as we use the same module reference during publication.

Ciao
Stephan

**Comment by AlexThurston** [comment]
I think perhaps the scope and intention of this issue is drifting slightly.

When you publish a test session for validation, it results in a request being created.  That request - when approved - looks as follow:
```
{
  "url": "/acvp/v1/requests/1029",
  "status": "approved",
  "approvedUrl": "/acvp/v1/validations/31206"
}
```

The resource created in this case is `/acvp/v1/validations/31206`.  This route/resource doesn't appear to be documented on: https://htmlpreview.github.io/?https://github.com/usnistgov/ACVP/blob/master/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.11.15.2

I'll raise a separate issue describing my other question.

**Comment by AlexThurston** [comment]
Bump.

I'm still curious about this route that appears to work but is not documented.  Is it suppose to work?  What other HTTP verbs can I use?  Does it have any other query parameters?  Is it something that will continue to work?

**Comment by Kritner** [comment]
I believe this issue was mostly a documentation issue at this point, updated the specification with information on this endpoint in #967.  

Closing this for now, but feel free to update if I've missed something.

**Comment by AlexThurston** [comment]
Sorry, I just noticed this got closed.  Before it does, I'd like to circle back one more time to the fact @jlramage brought up about it being useful to see the registration objects that were used in validated certificates.  The API now had OE which is useful for re-used.

I was wondering what the appetite and possibility of having that would be?
