### ISSUE TITLE
ACVP Production: Website should honor vendorUrl

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#722]
The ACVP Production website lists the vendor, but does not use a hyperlink to the website with the vendorUrl.

For CAVS, this is working.

May I suggest to add that back to ACVP?

**Comment by shaneshaffer** [comment]
There was an issue in the handling of the vendorUrl in ACVP that resulted in a malformed link when it appeared on CSRC. The erroneous data has been corrected in Prod and the fix should be in a deployment soon.

**Comment by smuellerDD** [comment]
Confirmed, fixed.
