### ISSUE TITLE
'fixedPubExp' format of RSA

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#723]
If I generate a test session with 'fixedPubExp' as '010001' as the example in the spec, everything is fine.
However, if I just simply put '10001', then it failed to generate the test vectors.
So, do we need to follow some kind of format for the 'fixedPubExp'? Like at least how many digits?

**testSessionId**
36069

**vsId**
67094

**Comment by Kritner** [comment]
@AndrewHYang all of our hex input is expected as a full byte, I could not actually find reference to that in the base protocol specification around bitstrings, but it should be the case.

**Comment by AndrewHYang** [comment]
@Kritner Got it. I guess it should be. Thanks
