### ISSUE TITLE
Vector Request Timeout

### ISSUE THREAD

**Issue by RandallSteck** [usnistgov/ACVP#724]
**environment**
Demo environment

**testSessionId**
35868

**vsId**
66620

**Algorithm registration**
-- Too long to list --

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443/acvp/v1/testSessions/35868/vectorSets/66620

**Expected behavior**
Expected full vector set to be returned

**Additional context**
I made a request for a particularly large set of vectors -- OpenSSL FOM + KAS + KW + KDF135 + KDF108.  After an hour, I received the following reply:

Maximum wait time with server reached! (Max: 3600 seconds).

Can this be altered to allow for the retrieval of large vector sets?

**Comment by celic** [comment]
The servers are going down for the weekend as a part of scheduled NIST infrastructure maintenance. We started shutting down our servers at around 3pm EDT. If you were making requests after that point, you will still see responses such as the retry: 30, but they will never progress beyond that.

**Comment by RandallSteck** [comment]
Thanks for the reply.  This request was done earlier in the week, and it occurred on a subsequent attempt after the first failure.  It's not related to the weekend outage.

**Comment by Kritner** [comment]
That is a pretty large registration, so some delay may be expected, but when the vector set is not yet ready to be returned, it *should* be returning a response to retry after 30, until it's available.

The "Maximum wait time with server reached" was returned with a `get` to https://demo.acvts.nist.gov:443/acvp/v1/testSessions/35868/vectorSets/66620 ? I don't think i've actually seen the server return that response, I wonder if the vector could have been in the middle of a state change, or something transient.

I'm showing that particular id as having been processed, is this something you eventually worked through?

**Comment by RandallSteck** [comment]
I found the issue.  It's an arbitrary limit set within libacvp.  I've bumped it up to 8h and the vector set completes without issue. I plan to submit a pull request to fix it on their end.  

Thanks for looking into it.
