### ISSUE TITLE
Cannot support only a single HMAC output length

### ISSUE THREAD

**Issue by agl** [usnistgov/ACVP#728]
When requesting an HMAC algorithm (e.g. `HMAC-SHA2-256`), it's not possible to support only a single MAC output length.

Given this:

```json
{
  "algorithm": "HMAC-SHA2-256",
  "revision": "1.0",
  "keyLen": [{"min": 8, "max": 2048, "increment": 8}],
  "macLen": [{"min": 256, "max": 256, "increment": 8}]
}
```

The demo server says:

> Property value(increment must be less than or equal to the difference between min and max) for (mac) in Algorithm (HMAC-SHA2-256 (null)) is not valid. Validation: (Number Between (32) and (256) modulus 1)

Fair enough, let's make the increment be zero:

```json
{
  "algorithm": "HMAC-SHA2-256",
  "revision": "1.0",
  "keyLen": [{"min": 8, "max": 2048, "increment": 8}],
  "macLen": [{"min": 256, "max": 256, "increment": 0}]
}
```

Still nope:

> Property value(increment value must be a positive integer: 0) for (mac) in Algorithm (HMAC-SHA2-256 (null)) is not valid. Validation: (Number Between (32) and (256) modulus 1)

**environment**
Demo

**Comment by Kritner** [comment]
@agl this type should be a `Domain` type, which can accept its information as an array of objects of `Range` type, and/or of literal values.  See https://usnistgov.github.io/ACVP/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.16.4

This registration should work:

```json
{
  "algorithm": "HMAC-SHA2-256",
  "revision": "1.0",
  "keyLen": [{"min": 8, "max": 2048, "increment": 8}],
  "macLen": [256]
}
```

Let me know if it does not

**Comment by Kritner** [comment]
@agl have you had a chance to try out the provided registration?

**Comment by agl** [comment]
Yep, that works. Thank you.
