### ISSUE TITLE
Implementations may not support IV for Feedback KDF

### ISSUE THREAD

**Issue by celic** [usnistgov/ACVP#729]
Some implementations do not support an IV for Feedback KDF (SP800-108). Under ACVP, the current `supportsEmptyIv = true` flag will generate groups that have an empty IV and groups that utilize the IV.

I propose a new boolean `requiresEmptyIv` to go alongside the existing boolean that will behave identically but remove the groups that utilize an IV. I like an additional flag to keep existing clients compatibility without work. This flag would be completely optional and assumed to be `false` if not provided.

**Comment by smuellerDD** [comment]
Am Dienstag, 29. Oktober 2019, 16:19:06 CET schrieb Chris Celi:

Hi Chris,

> Some implementations do not support an IV for Feedback KDF (SP800-108).
> Under ACVP, the current `supportsEmptyIv = true` flag will generate groups
> that have an empty IV and groups that utilize the IV.
> 
> I propose a new boolean `requiresEmptyIv` to go alongside the existing
> boolean that will behave identically but remove the groups that utilize an
> IV. I like an additional flag to keep existing clients compatibility
> without work. This flag would be completely optional and assumed to be
> `false` if not provided.

I see no concerns.

Ciao
Stephan
