### ISSUE TITLE
SPEC: Prerequisites in PUT /testSessions/<ID>

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#733]
The spec section 11.15.4 defines the prerequisites as follows:

```
         *prerequisites* - "string", array of prerequiste objects

            *algorithm* - "string", required

            *validationId* - "string", required
```

The used keywords however are different for all other use cases of prerequisites, for example when looking into the symmetric cipher definition:

```
           "prereqVals" :
               [{
                   "algorithm" : "ACVP-AES-ECB",
                   "valValue" : "123456"
               },
```

Please update the main SPEC for the PUT operation to be consistent with all other prerequisite definitions.

**Comment by smuellerDD** [comment]
When updating the spec, could you also please consider the following issue: It is permissible for one test session to request multiple vsIds for the same algorithm / mode type. E.g. it is permissible to request DSA PWGgen for 2k and 3k with different vsIds.

The current specification of the prerequisite listing during publication does not seem to account for that. I have IUT definitions where the aforementioned concept is applied. When adding prerequisite requests to the publication, I get ambiguous requests as follows:

```
    {
      "algorithm":"DSA",
      "mode":"pqgGen",
      "prereqVals":[
        {
          "algorithm":"SHA",
          "valValue":"same"
        },
        {
          "algorithm":"DRBG",
          "valValue":"same"
        }
      ]
    },
    {
      "algorithm":"DSA",
      "mode":"pqgGen",
      "prereqVals":[
        {
          "algorithm":"SHA",
          "valValue":"same"
        },
        {
          "algorithm":"DRBG",
          "valValue":"same"
        }
      ]
    },
    {
      "algorithm":"DSA",
      "mode":"pqgGen",
      "prereqVals":[
        {
          "algorithm":"SHA",
          "valValue":"same"
        },
        {
          "algorithm":"DRBG",
          "valValue":"same"
        }
      ]
    },
    {
      "algorithm":"DSA",
      "mode":"pqgVer",
      "prereqVals":[
        {
          "algorithm":"SHA",
          "valValue":"same"
        },
        {
          "algorithm":"DRBG",
          "valValue":"same"
        }
      ]
    },
    {
      "algorithm":"DSA",
      "mode":"pqgVer",
      "prereqVals":[
        {
          "algorithm":"SHA",
          "valValue":"same"
        },
        {
          "algorithm":"DRBG",
          "valValue":"same"
        }
      ]
    },
    {
      "algorithm":"DSA",
      "mode":"pqgVer",
      "prereqVals":[
        {
          "algorithm":"SHA",
          "valValue":"same"
        },
        {
          "algorithm":"DRBG",
          "valValue":"same"
        }
      ]
    },
```

**Comment by smuellerDD** [comment]
As I have not heard - is this proposal valid? I am asking whether I need add a separate prerequisite handling for the publication now or whether i can wait. As now more and more folks start to use the protocol, such protocol changes become harder and harder.

**Comment by dmchodnicki** [comment]
Duplicate #753

**Comment by dmchodnicki** [comment]
This item has been incorporated into a new Prerequisite Processing ticket and is therefore being Closed.  Please refer to #1071  for future updates.
