### ISSUE TITLE
Add FIPS186-5 Testing

### ISSUE THREAD

**Issue by celic** [usnistgov/ACVP#735]
The draft standard has been published at https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5-draft.pdf. 

This adds...
* More key sizes for RSA
* Slightly adjusted key generation for RSA
* Support for p mod 8 and q mod 8 RSA primes
* Removes ANSX 9.31 Signature Scheme
* Adds alternative mask generating functions for PSS Signature Scheme
* Removes DSA
* Adds EdDSA
* Adds Deterministic ECDSA
* Removes binary curves
(and other things I may have missed)

Updates to the specifications are in the works.

**Comment by smuellerDD** [comment]
Am Freitag, 1. November 2019, 17:39:47 CET schrieb Chris Celi:

Hi Chris,

> The draft standard has been published at
> https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5-draft.pdf.
> 
> This adds...
> * More key sizes for RSA
> * Slightly adjusted key generation for RSA
> * Support for p mod 8 and q mod 8 RSA primes
> * Removes ANSX 9.31 Signature Scheme
> * Adds alternative mask generating functions for PSS Signature Scheme
> * Removes DSA
> * Adds EdDSA
> * Adds Deterministic ECDSA
> * Removes binary curves
> (and other things I may have missed)
> 
> Updates to the specifications are in the works.

Are you saying that DSA is now going to be removed from ACVP?

If yes, how is FFC-DH with its dependency to DSA keygen handled?

Ciao
Stephan

**Comment by celic** [comment]
DSA will not be removed entirely. A transition period for 186-4 -> 186-5 will exist once this standard is fully published. After that period, DSA will only exist in a legacy manner, so only KeyVer and SigVer. Different KAS tests are being developed to handle those assurances. This goes along with the issue you had previously on the DSA assurance needed for safe primes.
