### ISSUE TITLE
failed to generate tests for HMAC_DRBG

### ISSUE THREAD

**Issue by kwong-cygnacom** [usnistgov/ACVP#736]
**environment**
Demo

**testSessionId**
37257

**vsId**
[ {
  "acvVersion" : "1.0"
}, {
  "vsId" : 70830,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 70830"
} ]

**Algorithm registration**
[ {
  "acvVersion" : "1.0"
}, {
  "isSample" : true,
  "publishable" : false,
  "algorithms" : [ {
    "algorithm" : "hmacDRBG",
    "revision" : "1.0",
    "prereqVals" : [ {
      "algorithm" : "SHA"
    } ],
    "predResistanceEnabled" : [ true, false ],
    "reseedImplemented" : false,
    "capabilities" : [ {
      "mode" : "SHA2-256",
      "derFuncEnabled" : false,
      "entropyInputLen" : [ {
        "min" : 128,
        "max" : 256,
        "increment" : 128
      } ],
      "nonceLen" : [ {
        "min" : 64,
        "max" : 128,
        "increment" : 64
      } ],
      "persoStringLen" : [ {
        "min" : 0,
        "max" : 256,
        "increment" : 256
      } ],
      "additionalInputLen" : [ {
        "min" : 0,
        "max" : 256,
        "increment" : 256
      } ],
      "returnedBitsLen" : 1024
    } ]
  } ]
} ]

**Endpoint in which the error is experienced**
GET https://demo.acvts.nist.gov/acvp/v1/testSessions/37257/vectorSets/70830

**Expected behavior**
I expected to get request JSON from Demo.

**Additional context**
None

**Comment by celic** [comment]
Here are the errors reported from the gen/vals...

```
Invalid Entropy Range supplied: 128.  Values were not between 256 and 34359738368;
Invalid Nonce Range for SHA2-256 supplied: 64.  Values were not between 128 and 34359738368
```

**Comment by kwong-cygnacom** [comment]
Thanks for the quick response.

**Comment by Kritner** [comment]
related #684
