### ISSUE TITLE
SPEC: draft-ietf-acvp-submac-1.0

### ISSUE THREAD

**Issue by kwong-cygnacom** [usnistgov/ACVP#745]
Section 6.1 AES-GMAC Algorithm Capabilities Registration

Please update algorithm's Valid Values ACVP-AES-GMAC to AES-GMAC for consistence.

**Comment by Kritner** [comment]
@kwong-cygnacom shouldn't this be the other way around? I was under the impression `ACVP-AES-GMAC` was the valid one, I believe other algorithms (at some point) will be updated to fit that style of identifier.

**Comment by kwong-cygnacom** [comment]
Other algorithm values in draft-ietf-acvp-submac-1.0 are shown without the ACVP- prefix:
CMAC-AES
CMAC-TDES
HMAC-SHA-1
...
HMAC-SHA3-512

So eventually they would become:
ACVP-CMAC-AES
ACVP-CMAC-TDES
ACVP-HMAC-SHA-1
...
ACVP-HMAC-SHA3-512

Right?

**Comment by celic** [comment]
The decision to use ACVP as a prefix started with the symmetric algorithms. At the time, GMAC was part of that specification. At a later time GMAC was moved to the MAC specification but kept the same title to not cause confusion.
