### ISSUE TITLE
 Curl failed with code 35 (SSL connect error)

### ISSUE THREAD

**Issue by hexiangqwqwqw** [usnistgov/ACVP#748]
**environment**
The environment the issue was experienced (Demo or Prod)
Demo
**testSessionId**
The test session ID

**vsId**
The vectorSet ID displaying the issue

**Algorithm registration**
The pertinent algorithm registration pieces (algorithm tested, capabilities, etc) in json format

**Endpoint in which the error is experienced**
https://[acvpUrl]/acvp/[endpoint] GET

**Expected behavior**

**Additional context**

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /work/ACVT/libacvp-master/certs/acvp.nist.gov.crt
    ACV_CERT_FILE:  kevin.micciche_hpe_server.cer
    ACV_KEY_FILE:   myserver.key

***ACVP [ERR][acvp_curl_http_post:687]--> Curl failed with code 35 (SSL connect error)

***ACVP [STATUS][log_network_status:1397]--> POST Login...
	Status: 0
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp:
(null)

***ACVP [STATUS][acvp_login:2067]--> Login Send Failed
***ACVP [ERR][acvp_run:2585]--> Failed to login with ACVP server

**Comment by jarnold01** [comment]
Hi, I've just verified that your certificate is active and not expired. Did you recently update your libacvp  client software by any chance? Another user reported a similar login issue but received a different Curl error and stated they were using the "new libacvp-master". Thanks.

**Comment by bfussell** [comment]
I just tried the latest and it works fine, however I use
    ACV_CA_FILE:    certs/mozzila_trust_anchors.pem
because 
    ACV_CA_FILE:    certs/acvp.nist.gov.crt
doesn't work on my server.

**Comment by jarnold01** [comment]
Thanks Barry - that's good info to know. Hopefully @hexiangqwqwqw will try again and report back if that helps him (or not).

**Comment by hexiangqwqwqw** [comment]
hexiang@hexiang-VirtualBox:/work/ACVT/libacvp-master/app$ ./acvp_app  --aes

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /work/ACVT/libacvp-master/certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  kevin.micciche_hpe_server.cer
    ACV_KEY_FILE:   myserver.key

***ACVP [ERR][acvp_curl_http_post:687]--> Curl failed with code 35 (SSL connect error)

***ACVP [STATUS][log_network_status:1397]--> POST Login...
	Status: 0
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp:
(null)

***ACVP [STATUS][acvp_login:2067]--> Login Send Failed
***ACVP [ERR][acvp_run:2585]--> Failed to login with ACVP server

**Comment by hexiangqwqwqw** [comment]
Pinging ammd.nist.gov [52.204.191.193] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 52.204.191.193:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

C:\Users\xhe>

**Comment by hexiangqwqwqw** [comment]
hexiang@hexiang-VirtualBox:/work/ACVT/libacvp-master/app$ ./acvp_app  --aes

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /work/ACVT/libacvp-master/certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  kevin.micciche_hpe_server.cer
    ACV_KEY_FILE:   myserver.key

***ACVP [STATUS][log_network_status:1397]--> POST Login...
	Status: 401
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp:
{
  "acvVersion" : "1.0",
  "error" : "The supplied one time password could not be verified"
}

***ACVP [STATUS][acvp_login:2067]--> Login Send Failed
***ACVP [ERR][acvp_run:2585]--> Failed to login with ACVP serve

**Comment by bfussell** [comment]
Quick look at the recent 3 errors:
1. still not sure what your issue is when you get ode 35 (SSL connect error).
2. Certainly appears you have some network issues reaching nist.
3. Most likely your server is suffering from some drift causing your TOTP to fail, that or your TOTP seed is not set.

**Comment by jarnold01** [comment]
Hi @hexiangqwqwqw , 

1) I just sent you (via nfiles) what the TOTP seed value is that is associated with your certificate in Demo. Please verify that they match what you are attempting to use to access the Demo server.

2) ICMP traffic is filtered so pinging demo.acvts.nist.gov will not work; just FYI.

3) Barry brings up an excellent point about the time set on the machine you're running the client on - can you please verify you're using a reachable NTP server and that the time is synced?

**Comment by hexiangqwqwqw** [comment]
I have checked the string of “xiang-hep-totp.txt same as string that I am using, string of xiang-hpe-base64-cert.txt is same as string of “kevin.micciche_hpe_server.cer”

But one time password could not be verified" . Do you have any other advise? The log is 
hexiang@hexiang-VirtualBox:/work/ACVT/libacvp-master$ ./app/acvp_app --aes

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /work/ACVT/libacvp-master/certs/acvp.nist.gov.crt
    ACV_CERT_FILE:  kevin.micciche_hpe_server.cer
    ACV_KEY_FILE:   myserver.key

***ACVP [STATUS][log_network_status:1397]--> POST Login...
        Status: 401
        Url: https://demo.acvts.nist.gov:443/acvp/v1/login
        Resp:
{
  "acvVersion" : "1.0",
  "error" : "The supplied one time password could not be verified"
}

***ACVP [STATUS][acvp_login:2067]--> Login Send Failed
***ACVP [ERR][acvp_run:2585]--> Failed to login with ACVP server

My nist_setup.sh file :
#!/bin/bash
export ACV_URI_PREFIX=/acvp/v1/
export ACV_API_CONTEXT=acvp/
export ACV_CA_FILE=/work/ACVT/libacvp-master/certs/acvp.nist.gov.crt
export ACV_KEY_FILE=myserver.key
export ACV_CERT_FILE=kevin.micciche_hpe_server.cer
export ACV_TOTP_SEED="0rTXI6ot3GtL5qIt9NoOC6YQhARoBsLIKeIxXFmMhcw="
export ACV_PORT=443
export ACV_SERVER=demo.acvts.nist.gov

**Comment by Kritner** [comment]
@hexiangqwqwqw FYI I removed your seed from the post as that should be considered secret information, we'll probably have to reseed your account as it will be available in message history.

**Comment by jarnold01** [comment]
Yes, I'll have to re-issue you a new TOTP seed value, which I will do today. Please don't post your seed value publicly. Thanks @Kritner for removing it from the post.

@hexiangqwqwqw did you check the clock / time synchronization? I didn't see you comment at all on that troubleshooting point.

**Comment by hexiangqwqwqw** [comment]
How to check the clock cynchronization ?

**Comment by hexiangqwqwqw** [comment]
How to check the clock synchronization ?

**Comment by jarnold01** [comment]
Not sure which Linux distribution you're using, but a quick Google search for "linux ntp sync" turned up a list of results that included this page which may be helpful. If not, refine the search to include your particular distribution and I'm sure you'll find some step-by-step instructions to help you get it setup and working:

https://www.howtogeek.com/tips/how-to-sync-your-linux-server-time-with-network-time-servers-ntp/

Additionally, if you wish to sync to the NIST time servers (the ones we use for all of our servers, you can get the list of IP addresses for those here): https://tf.nist.gov/tf-cgi/servers.cgi 

a.k.a.  time.nist.gov

Hope this helps.

**Comment by hareesh-d** [comment]
facing the same issue with the master LibACVP. I have synced the time also to NTP. Please suggest.

timedatectl
      Local time: Mon 2019-12-23 21:50:18 HKT
  Universal time: Mon 2019-12-23 13:50:18 UTC
        RTC time: Mon 2019-12-23 13:50:18
       Time zone: Asia/Hong_Kong (HKT, +0800)
 Network time on: no
NTP synchronized: yes
 RTC in local TZ: no


Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    certs/acvp.nist.gov.crt
    ACV_CERT_FILE:  certs/hareesh_dasari_acvpreq.pem.cer
    ACV_KEY_FILE:   certs/acvpkey.plain.pem

***ACVP [ERR][acvp_curl_http_post:687]--> Curl failed with code 35 (SSL connect error)

***ACVP [STATUS][log_network_status:1403]--> POST Login...
        Status: 0
        Url: https://demo.acvts.nist.gov:443/acvp/v1/login
        Resp:
(null)

***ACVP [STATUS][acvp_login:2072]--> Login Send Failed
***ACVP [ERR][acvp_run:2590]--> Failed to login with ACVP server

**Comment by jarnold01** [comment]
Hi @hareesh-d , please change env var ACV_CA_FILE:

ACV_CA_FILE:    certs/mozzila_trust_anchors.pem

and attempt again.

**Comment by hexiangqwqwqw** [comment]
The issue have solved , Thank you

**Comment by hareesh-d** [comment]
Hi @jarnold01  , Tried with export ACV_KEY_FILE=certs/acvpkey.plain.pem also. But same result. 
Hi @hexiangqwqwqw , can you please tell me how did you solve this issue. Thanks.

I actually tried with both curl (Error 35) and murl (TCP connect failed).

**Comment by jarnold01** [comment]
Hi @hareesh-d , Can you reach https://demo.acvts.nist.gov/home from the machine you are attempting to connect from? It should return a page that looks like this (though the row data may have changed from my attached screenshot.)
![image](https://user-images.githubusercontent.com/41693372/71477281-1c913c00-27b7-11ea-87aa-da28ee0ecf79.png)

**Comment by jarnold01** [comment]
> The issue have solved , Thank you

Thanks @hexiangqwqwqw
