### ISSUE TITLE
Publication: submission of prerequisites

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#749]
When submitting the prerequisites as part of the publication phase, it seems the ACVP server does not like the string "same" as a "validationId"

Publication request:

```
[{"acvVersion":"1.0"},{"moduleUrl":"/acvp/v1/modules/11495","oeUrl":"/acvp/v1/oes/19621","algorithmPrerequisites":[{"algorithm":"HMAC-SHA-1","prerequisites":[{"algorithm":"SHA","validationId":"same"}]},{"algorithm":"HMAC-SHA2-224","prerequisites":[{"algorithm":"SHA","validationId":"same"}]},{"algorithm":"HMAC-SHA2-256","prerequisites":[{"algorithm":"SHA","validationId":"same"}]},{"algorithm":"HMAC-SHA2-384","prerequisites":[{"algorithm":"SHA","validationId":"same"}]},{"algorithm":"HMAC-SHA2-512","prerequisites":[{"algorithm":"SHA","validationId":"same"}]}]}]
```

ACVP server error:

```
{
  "acvVersion" : "1.0",
  "error" : "I/O Error during processing. -- caused by --> invalid validationId string: same"
}
```

As the prerequisite type "same" is allowed for the valValue keyword and there is no clear indication that "validationId" is not allowed to have the "same" value, I am wondering what the ACVP server expects here.

**Comment by smuellerDD** [comment]
Chris, may I ping you on this one? Robert is asking where our prereqs for the publication phase are. At least, can you please point out which string should be used when the "same" test vector set is referred to?

Thanks.

**Comment by shaneshaffer** [comment]
The current implementation does not actually support self referential prerequisites. We are trying to determine if this was intentional (meaning we assume prerequisites are self satisfied unless explicitly stated) or an oversight, and what makes sense to do going forward.

**Comment by smuellerDD** [comment]
Just a note for completeness: at least our lab always tries to have self-sufficient test sessions. That said, it may be possible that for testing one IUT we have more vsIDs than strictly needed. However, this approach spares us the manual and error-prone tracking of vsId references.

Only if we cannot avoid referencing other vsIds, we will do that.

**Comment by smuellerDD** [comment]
In the not too far future, I have IUTs for which I have mixed prerequisites: some are provided by the IUT itself, but some are not. Unfortunately I cannot do anything to mitigate it, i.e. I need to publish the IUT with these mixed dependencies.

Thus, may I ask about the status of this issue - when can we expect this to be covered?

Thanks

**Comment by smuellerDD** [comment]
Is this issue solved with the new server implementation?

**Comment by smuellerDD** [comment]
May I ping on this one? We have now streamlined the testing on our side for the massive test blocks like OpenSSL or the kernel by adding a feature to perform an automated dependency handling. This implies that we soon now have requests with a mixed prerequisite settings: some prereqs point to the "same" test session and others to certificate IDs.

I am unsure how to handle them now without having this issue fixed.

Thanks.

**Comment by dmchodnicki** [comment]
This item has been incorporated into a new Prerequisite Processing ticket and is therefore being Closed.  Please refer to #1071  for future updates.
