### ISSUE TITLE
Fail to register KAS/KTS IFC

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#751]
I'm trying to create test session of KAS/KTS IFC.
And I got error message:
`"acvVersion" : "1.0",\r\n  "error" : "Incorrectly formatted JSON (1:1010): unknown algorithm: KTS-IFC with mode: null"`

I don't see any info about this '**mode**' in the example registration.
I guess it's not about the kdfMode or macMode, right?

Following my registration:

> [

	{"acvVersion": "1.0"}, 
	{
		"algorithms": [
			{
				"iutId": "CAFECAFE",
				"function": ["partialVal"],
				"scheme": {
					"KTS-OAEP-basic": {
						"kasRole": ["initiator"], 
						"keyGenerationMethods": {
							"rsakpg1-basic": {
								"modulo": [6144], 
								"fixedPublicExponent": "010001"
							}
						}, 
						"ktsMethod": {
							"hashAlgs": ["SHA2-256", "SHA3-512"],
							"supportsNullAssociatedData": true,
							"associatedDataPattern": "l||uPartyInfo||vPartyInfo",
							"encoding": ["concatenation"]
						}, 
						"macMethods": {
							"HMAC-SHA2-384": {
								"keyLen": 128,
								"macLen": 64
							}
						}, 
						"l": 512
					}
				},
				"algorithm": "KTS-IFC", 
				"revision": "1.0"
			}
		],
		"encryptAtRest": false, 
		"isSample": true
	}

> ]

**Comment by Kritner** [comment]
Ah I'm sorry I missed this in the one place in the spec, the expected revision for this mode is "Sp800-56Br2".

We're going to attempt to move toward a SP/FIPS/etc revision scheme (as opposed to 1.0, 1.1, etc) in the future.

I'll update the spec

**Comment by Kritner** [comment]
@AndrewHYang this was closed in my PR, hopefully that's the entirety of the issue.  If not feel free to update or open a new one.
