### ISSUE TITLE
Fail to generate test vectors of KAS IFC

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#754]
**environment**
Demo

**testSessionId**
44000

**vsId**
91304

**Algorithm registration**
KAS-IFC

**Endpoint in which the error is experienced**
"status": "error during vector generation",
"message": "failed to make working directory!"

**Comment by Kritner** [comment]
Hey @AndrewHYang I see we have a problem with our KeyGen in the 8192 mod size.  Can you attempt with a smaller value for the moment? 

I will use this issue to track the fix our end (when 8192 is available).

**Comment by AndrewHYang** [comment]
Hi @Kritner. When I'm trying with 2048 mod size. I got another error message:

> Internal Server Error. Please contact administrator for assistance.

And following my registration:


> {
	"algorithms": [{
		"prereqVals": [{
			"algorithm": "CMAC", 
			"valValue": ""
			}, 
			{
				"algorithm": "DRBG", 
				"valValue": ""
			}, 
			{
				"algorithm": "ECDSA", 
				"valValue": ""
			}
		], 
		"revision": "Sp800-56Br2", 
		"iutId": "CAFECAFE", 
		"function": [
			"partialVal", "keyPairGen"
		], 
		"scheme": {
			"KAS1-Party_V-confirmation": {
				"kasRole": ["responder", "initiator"], 
				"keyGenerationMethods": {
					"rsakpg2-crt": {"modulo": [2048]}
				}, 
				"kdfMethods": {
					"oneStepKdf": {
						"auxFunctions": [{
							"auxFunctionName": "KMAC-128", 
							"macSaltMethods": ["default", "random"]
						}], 
						"fixedInfoPattern": "algorithmId||l||uPartyInfo||vPartyInfo", 
						"encoding": ["concatenation"]
					}, 
					"twoStepKdf": {
						"capabilities": [{
							"macSaltMethods": [], 
							"fixedInfoPattern": "algorithmId||l||uPartyInfo||vPartyInfo", 
							"encoding": ["concatenation"], 
							"kdfMode": "feedback", 
							"macMode": ["HMAC-SHA3-256"], 
							"fixedDataOrder": ["after fixed data"], 
							"counterLength": [32], 
							"supportedLengths": [512], 
							"supportsEmptyIv": false, 
							"requiresEmptyIv": false
						}]
					}
				}, 
				"macMethods": {
					"KMAC-128": {
						"keyLen": 128, 
						"macLen": 64
					}
				}, 
				"l": 512
			}
		}, 
		"algorithm": "KAS-IFC"
	}], 
	"encryptAtRest": false, 
	"isSample": true
}

>

**Comment by Kritner** [comment]
@AndrewHYang looks like you're missing valid macSaltMethods for your twoStep kdf registration. Tagging #685 as that ticket will help alleviate issues such as this one.

**Comment by Kritner** [comment]
I haven't heard back regarding this, closing for now.  @AndrewHYang let me know if you did or didn't end up getting through with the issue.
