### ISSUE TITLE
Production server: "unreceived" verdicts

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#755]
We uploaded a large set of test responses to the ACVP production server.

There are a large number of cases where the server returned the verdict of:

```
[ {
  "acvVersion" : "1.0"
}, {
  "results" : {
    "vsId" : 5565,
    "disposition" : "unreceived"
  }
} ]
```

Even when re-trying to fetch a new verdict at a later time, the server reports this verdict.

**Comment by smuellerDD** [comment]
With a different production submission, we had no issue. But for this submission, I throttled my ACVP Proxy.

For the successful upload where no aforementioned errors were seen, I used 16 threads to upload.

With the upload having the failures, we used 256 threads to upload.

Could there be some concurrency problem on the production server?

**Comment by smuellerDD** [comment]
I just see that on a large scale also at the demo server. Entire test sessions with all their vsIds suffer from it.

For example: test session 58233, 58221, 58218, 58220, 58227, 58232, 58235, 58238, 58225, 58222, 58239, 58231, 58237

**Comment by Kritner** [comment]
> I just see that on a large scale also at the demo server. Entire test sessions with all their vsIds suffer from it.

> For example: test session 58233, 58221, 58218, 58220, 58227, 58232, 58235, 58238, 58225, 58222, 58239, 58231, 58237

What exactly is the issue with those test sessions on demo? I just checked and at a glance it *looks* like they have all produced prompt files, but have not yet been submitted for validation.  

Have they been submitted for validation with a failure? are you still waiting on a response under validation?

**Comment by smuellerDD** [comment]
Am Freitag, 10. Januar 2020, 15:39:24 CET schrieb Russ Hammett:

Hi Russ,

> > I just see that on a large scale also at the demo server. Entire test
> > sessions with all their vsIds suffer from it.
> > 
> > For example: test session 58233, 58221, 58218, 58220, 58227, 58232, 58235,
> > 58238, 58225, 58222, 58239, 58231, 58237
> What exactly is the issue with those test sessions on demo? I just checked
> and at a glance it *looks* like they have all produced prompt files, but
> have not yet been submitted for validation.

That is the case - I uploaded result data and then received the mentioned 
error message for all vsIds.
> 
> Have they been submitted for validation with a failure? are you still
> waiting on a response under validation?



Ciao
Stephan

**Comment by Kritner** [comment]
Ah this is all falling under the:

```
[ {
  "acvVersion" : "1.0"
}, {
  "results" : {
    "vsId" : 5565,
    "disposition" : "unreceived"
  }
} ]
``` 

? 

I'll send this on to a few that have access to these environments to double check.  Apologies for the delay on this, have a lot of vacations and conferences and whatnot going on this time of year.

**Comment by Kritner** [comment]
@smuellerDD I'll have to look at this a bit more on monday, but at a glance it doesn't seem like the response submission made it through the front end API, so the result of your "response" would never make it through, as far as the system state is showing, they were never submitted.

We'll take a look at our logs on monday, but just for fun, if you're able, can you attempt to submit your response file to one of the problematic vector sets? (Note not check on the status of your response validation, but actually resubmit the response.)

**Comment by smuellerDD** [comment]
Am Freitag, 10. Januar 2020, 20:55:34 CET schrieb Russ Hammett:

Hi Russ,

> @smuellerDD I'll have to look at this a bit more on monday, but at a glance
> it doesn't seem like the response submission made it through the front end
> API, so the result of your "response" would never make it through, as far
> as the system state is showing, they were never submitted.
> 
> We'll take a look at our logs on monday, but just for fun, if you're able,
> can you attempt to submit your response file to one of the problematic
> vector sets? (Note not check on the status of your response validation, but
> actually resubmit the response.)

When we try to submit the result again using POST, we get the same error. As 
PUT is not yet supported, we are unable to attempt doing a PUT.

Ciao
Stephan

**Comment by Kritner** [comment]
@smuellerDD for the vector set you attempted to post again (as per https://github.com/usnistgov/ACVP/issues/755#issuecomment-573401932), can you please provide:

* environment
* vector set id
* datetime of attempt
* full endpoint URI

Thanks!

**Comment by smuellerDD** [comment]
How strange. Now I get the verdict.

Just tested:
- demo server
- vsID 113830
- Di 14. Jan 12:11:50 CET 2020

**Comment by smuellerDD** [comment]
I checked with the other test sessions and I got the verdicts. Can you please help me understand in which situation the ACVP server may generate the initially mentioned response?

**Comment by Kritner** [comment]
I'm a little confused about some of the situation as well, as far as the actions your client is performing and when, so hopefully this will help shed some light...

1. Client POST https://acvts.nist.gov/acvp/v1/testSessions
  * Server response:
```  
	  [{
		"acvVersion": "1.0"
	}, {
		"url": "/acvp/v1/testSessions/1",
		"vectorSetUrls": ["/acvp/v1/testSessions/1/vectorSets/1"],
		"accessToken": "[token]"
	}]
```
2. Client GET https://acvts.nist.gov/acvp/v1/testSessions/1/vectorSets/1
  * If vector set not ready:
```
	[{
		"acvVersion": "1.0"
	}, {
		"vsId": 1,
		"retry": 30
	}]
```
  * when vector set ready return the vector set
3. Client POST https://acvts.nist.gov/acvp/v1/testSessions/1/vectorSets/1/results
  * Server response:
```
  [{
    "acvVersion": "1.0"
}, {
    "url": "/acvp/v1/testSessions/1/vectorSets/1"
}]
```
4. Client GET https://acvts.nist.gov/acvp/v1/testSessions/1/vectorSets/1/results
  * If validation not yet complete:
```
  [{
    "acvVersion": "1.0"
}, {
    "results": {
        "vsId": 36294,
        "disposition": "incomplete"
    },
    "retry": 30
}]
```
  * If attempting to get on this endpoint prior to the results being posted (step 3):
```
	[ {
  "acvVersion" : "1.0"
}, {
  "results" : {
    "vsId" : 1,
    "disposition" : "unreceived"
  }
} ]
```
  * When validation results are available:
```
  [{
    "acvVersion": "1.0"
}, {
    "vsId": 1,
    "disposition": "passed",
	...
}]
```


The only time that I'm seeing that "unreceived" should be encountered (granted I'm not super familiar with this particular part of the code so take that with a grain of salt) is when you attempt to get the "results" of validation (step 4), prior to the posting of answers (step 3).

A few possibilities:
* Some vector sets within the test sessions mentioned are not yet posted prior to requesting the validation results
* The posting of the vector set results fails (I'm not even sure what this would look like, but I know you've mentioned that the client can be attempting ~128 vector set uploads simultaneously), is it possible some of the posts are failing?
* Some sort of transient state change issue on our end in between the vector set being validated and the results being available

We did not change anything in the system between the time when you attempted in https://github.com/usnistgov/ACVP/issues/755#issuecomment-573401932 vs https://github.com/usnistgov/ACVP/issues/755#issuecomment-574125021, so I'm pretty baffled by this behavior myself.

**Comment by shaneshaffer** [comment]
To expand on Russ' comment above, 

> The posting of the vector set results fails (I'm not even sure what this would look like, but I know you've mentioned that the client can be attempting ~128 vector set uploads simultaneously), is it possible some of the posts are failing?

According to the web server logs in the Prod environment, for test session 510 (the one which vector set 5565 is a part of, back in the first message on this ticket), results for only 10 of the 41 vector sets were ever posted.

**Comment by smuellerDD** [comment]
Am Dienstag, 14. Januar 2020, 15:44:00 CET schrieb shaneshaffer:

Hi shaneshaffer,

> To expand on Russ' comment above,
> 
> > The posting of the vector set results fails (I'm not even sure what this
> > would look like, but I know you've mentioned that the client can be
> > attempting ~128 vector set uploads simultaneously), is it possible some
> > of the posts are failing?
> According to the web server logs in the Prod environment, for test session
> 510 (the one which vector set 5565 is a part of, back in the first message
> on this ticket), results for only 10 of the 41 vector sets were ever
> posted.

I think I found the error:

Some time ago you mentioned that the large file support is deactivated. As I 
was not sure when and how you deactivate it, I left the large file support in 
my code.

The following happens now:

During logon, the ACVP server still sends the maximum file size constraint 
compliant to the large file support definition. The ACVP server still sends 
"4194304" as maximum file size.

My ACVP Proxy honors this: when the response is larger than this, it requests 
a large file endpoint, i.e. to https://demo.acvts.nist.gov:443/acvp/v1/large

The ACVP server responds and provides a large URL: https://
demo.acvts.nist.gov:7443/acvp/v1/upload/
Mf21r19EIJ6Ah6eqVlTVZYvRhdIZMopfGeS0Iq0qtan2xa29MlXqVbskg9x00wCl

Now, my ACVP Proxy uses that URL and tries to connect unsuccessfully.

* Connection failed
* connect to 52.204.191.193 port 7443 failed: Operation timed out
* Failed to connect to demo.acvts.nist.gov port 7443: Operation timed out

Here is where my ACVP Proxy fails: it still obtains a verdict even though the 
upload failed: GET /acvp/v1/testSessions/69225/vectorSets/129577/results.


Thus, I will make sure that my ACVP Proxy will honor the connection error.

Yet, may I ask you to change the ACVP server to either completely eliminate 
the large support, or report the correct maximum supported file size?

Ciao
Stephan

**Comment by smuellerDD** [comment]
Now the issue is much more interesting: I disabled the large file support to send the 9MB response file directly.

I get an HTTP error 403 and:

<html><head><title>Error</title></head><body>Forbidden</body></html>

So, how can I submit a large response?

**Comment by Kritner** [comment]
@celic @shaneshaffer do you recall the status of the large end point? I was under the impression it was still in use and required in some situations (after my impression that it was no longer required from several months ago).

@smuellerDD is it possible that your JWT or TLS connection is expiring prior to, or during the upload of the results?

**Comment by smuellerDD** [comment]
Am Donnerstag, 16. Januar 2020, 22:50:03 CET schrieb Russ Hammett:

Hi Russ,

> @celic @shaneshaffer do you recall the status of the large end point? I was
> under the impression it was still in use and required in some situations
> (after my impression that it was no longer required from several months
> ago).
> 
> @smuellerDD is it possible that your JWT or TLS connection is expiring prior
> to, or during the upload of the results?

This is highly unlikely, because the round trip was within 24 hours.

Ciao
Stephan

**Comment by smuellerDD** [comment]
I may want to add (without further testing though): there are other vectors (IIRC GCM) which are typically larger than 4 MB. Those worked so far (at least I have not seen any problems). Till yesterday, my proxy always used the large-file upload if the response size is larger than the max size reported by the ACVP server.

**Comment by smuellerDD** [comment]
Another observation: large vector support DOES work and IS required for GCM. I just tested without large support and got an error from the server during uploading a result > 4MB. But when enabling the large support, upload works and I do get a verdict.

Jiust for SHAKE, the large endpoint does not seem to be accessible.

**Comment by smuellerDD** [comment]
After trying that again with SHAKE, it works now and I get verdicts.

I am not sure what solved the issue, but it is good now.
