### ISSUE TITLE
Production server: DSA keygen failure

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#756]
The ACVP production server indicates a failure of one of our DSA keys returned to the server as part of the ACVP DSA keygen.

The server response says:

```
 [ {
  "acvVersion" : "1.0"
}, {
  "vsId" : 5525,
  "disposition" : "failed",
  "tests" : [ {
    "tcId" : 1,
    "result" : "failed",
    "reason" : "Validation failed: Fail"
  }, {
```

As we do not have seen any such issue before and the error information is not helpful, may I ask for some details? Note, the IUT is OpenSSL.

Thank you.

**Comment by Kritner** [comment]
@smuellerDD, I confirmed in our crypto implementation as well as a separate repl https://repl.it/@Kritner/modPow-test-keyVer that tcId 1 appears to be a legitimate failure.

The first test in the above repl is one of the passing tests from your vector set, the second is the failing one you mentioned.

**Comment by smuellerDD** [comment]
How interesting. OpenSSL has a bug?!

Thank you for the help.

**Comment by celic** [comment]
@smuellerDD if you confirm that the issue is in OpenSSL, please send me an email with more information. This is very curious.
