### ISSUE TITLE
Update of published IUT

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#760]
After publishing an IUT on the production site (A64 and others) I identified a typo in the module description.

Now I wanted to update the description with a PUT operation. Yet, the operation was discarded with the following error:

```
{
  "acvVersion" : "1.0",
  "error" : "Test Session has already been published."
}
```

This error seems to indicate that I cannot update any aspect of a published certificate. Is that correct? If yes, is that the intended approach?

Why would there be an update operation possible in the first place? Usually all published information are eventually tied together in one or more certificates. So, all meta data eventually would then be frozen?

**Comment by shaneshaffer** [comment]
You need to use the module PUT endpoint to change the module description, not the test session PUT.

A published certificate is really just relationships between metadata and test sessions. All of the metadata types (module/person/vendor/OE/dependency) can be updated through their PUT endpoints as much as you want, the test session PUT can only be done once.

**Comment by smuellerDD** [comment]
rrrriiight - bug was between desk and chair. Sorry for the noise.
