### ISSUE TITLE
Introduce Specification Changes for ECDSA SigVer Component

### ISSUE THREAD

**Issue by celic** [usnistgov/ACVP#764]
Allow pre-hashed messages to be used for ECDSA SigVer via a `componentTest` flag similar to ECDSA SigGen.

**Comment by smuellerDD** [comment]
Using the following request, I still get full ECDSA signature verification test vectors:

```
      {
        "algorithm":"ECDSA",
        "mode":"sigVer",
        "revision":"1.0",
        "componentTest":true,
        "capabilities":[
          {
            "curve":[
              "P-256",
              "P-384",
              "P-521"
            ],
            "hashAlg":[
              "SHA-1",
              "SHA2-224",
              "SHA2-256",
              "SHA2-384",
              "SHA2-512"
            ]
          }
        ],
        "prereqVals":[
          {
            "algorithm":"SHA",
            "valValue":"same"
          }
        ]
      }
```

**Comment by Kritner** [comment]
@smuellerDD I think the intention of this issue was to have something for tracking purposes in a forthcoming PR.  This functionality is not yet present in any environment.

**Comment by smuellerDD** [comment]
Confirmed, working.

Please close it at your discretion as I am not sure whether you want to add some documentation update.

**Comment by celic** [comment]
Great! I'll keep this open until we can update the specification.
