### ISSUE TITLE
Is SHAKE supported on the production server ?

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#765]
I submitted the capabilities and received:

testSessions 562

"vsId": 6286,
    "status": "error during vector generation",
    "message": "failed to generate tests for: 6286"
}, {
    "vsId": 6287,
    "status": "error during vector generation",
    "message": "failed to generate tests for: 6287"

It works fine on demo.

**Comment by Kritner** [comment]
@bfussell did you attempt this again and get a success? One of the two registrations from the vsIds you posted I tried in our other environment and they passed; but I have not had a chance to dig into prod.

**Comment by bfussell** [comment]
@Kritner No, I searched your website and found this:

https://csrc.nist.gov/projects/hash-functions

Currently only the four fixed-length SHA-3 algorithms are approved hash algorithms, providing alternatives to the SHA-2 family of hash functions. The XOFs can be specialized to hash functions, subject to additional security considerations. Guideline for using the XOFs will be provided in the future.

Did that change with ACVP ?

**Comment by bfussell** [comment]
I re-ran with a simple SHAKE registration, no other algorithms and same result, worked on demo not on prod.

Sending registration... [{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"SHAKE-128","revision":"1.0","inBit":false,"inEmpty":true,"outBit":false,"outputLen":[{"min":16,"max":1024,"increment":8}]},{"algorithm":"SHAKE-256","revision":"1.0","inBit":false,"inEmpty":true,"outBit":false,"outputLen":[{"min":16,"max":1024,"increment":8}]}]}]

testSessions 565
vectorSets 6396 and 6397

  "vsId" : 6396,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 6396"
} ]
  "vsId" : 6397,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 6397"
}

**Comment by Kritner** [comment]
@bfussell we're going to try to get a production push out early next week to fix this issue, sorry for the delay.

**Comment by bfussell** [comment]
Thanks !

**Comment by bfussell** [comment]
@Kritner A related question.  I've run a set of algorithms on the demo server using a specific module/OE and then later run additional algorithms using the same module/OE and the validation information for that module/OE will include both sets.  The reason I ask is if we run everything except SHAKE now on prod and then run SHAKE on prod later for the same module/OE it should end up in the same validation number, correct ?

**Comment by shaneshaffer** [comment]
Correct - validations are per module. Whether you do 1 test session with 10 algorithms or 10 test sessions with 1 algorithm each, they should all wind up on the same validation.

**Comment by Kritner** [comment]
@bfussell a prod release went out this morning, can you check shake at your earliest convenience?

**Comment by bfussell** [comment]
Sending registration... 
[{"acvVersion":"1.0"},
 {"algorithms": [{"algorithm":"SHAKE128","revision":"1.0","inBit":false,"inEmpty":true,"outBit":false,"outputLen":[{"min":16,"max":1024,"increment":8}]},
{"algorithm":"SHAKE-256","revision":"1.0","inBit":false,"inEmpty":true,"outBit":false,"outputLen":[{"min":16,"max":1024,"increment":8}]}]}]

***ACVP [STATUS][log_network_status:1506]--> POST Registration...
	Status: 500
	Url: https://acvts.nist.gov:443/acvp/v1/testSessions
	Resp:
{
  "acvVersion" : "1.0",
  "error" : "Internal Database Error."
}

***ACVP [ERR][acvp_register:1673]--> Failed to send registration
***ACVP [ERR][acvp_run:2751]--> Failed to register with ACVP server

**Comment by Kritner** [comment]
@bfussell can you try again?

**Comment by bfussell** [comment]
That worked, testSession 678, vectorSets 8252-8253.
Thanks !

**Comment by smuellerDD** [comment]
When uploading the response to the server, I get:

```
{
  "acvVersion" : "1.0",
  "error" : "The current user is not authorized for the requested action."
}
```

vsID: 8287, 8288

**Comment by bfussell** [comment]
When it worked for me I used a simple registration with the domain values being (16, 1024, 8), however I also tested on demo and found that (16, 65536, 8) returned a forbidden status 403.

**Comment by smuellerDD** [comment]
Am Dienstag, 28. Januar 2020, 04:14:20 CET schrieb Barry Fussell:

Hi Barry,

> When it worked for me I used a simple registration with the domain values
> being (16, 1024, 8), however I also tested on demo and found that (16,
> 65536, 8) returned a forbidden status 403.

I use exactly the large definition of (16, 65536, 8) which fully worked on 
demo.

Ciao
Stephan

**Comment by Kritner** [comment]
@smuellerDD both of those vector sets (8287 and 8288), are fully passed through validation. Did you work out the issue?

**Comment by smuellerDD** [comment]
Am Dienstag, 28. Januar 2020, 11:23:50 CET schrieb Russ Hammett:

Hi Russ,

> @smuellerDD both of those vector sets (8287 and 8288), are fully passed
> through validation. Did you work out the issue?

During a new upload, I get the answer

```
{
  "acvVersion" : "1.0",
  "error" : "Results for Vector Set id: 8287 cannot be submitted with status: 
PASSED"
}
```

So, I downloaded the verdict and got an all passing test session.

But I am not sure I can work out the issue: The ACVP server returned an error 
message initially as indicated.

Ciao
Stephan

**Comment by bfussell** [comment]
That does not work on demo for me, however I don’t have the large submission enabled presently – that may be why.

Regards,

Barry

**Comment by smuellerDD** [comment]
You need large submission support since SHAKE with these parameters has a response size of > 9MB.

**Comment by Kritner** [comment]
from https://github.com/usnistgov/ACVP/issues/765#issuecomment-579057166

```json
{
  "acvVersion" : "1.0",
  "error" : "The current user is not authorized for the requested action."
}
```

Stephan it looks like your session was invalid at that time, though I'm not certain why.  It looks like the TLS sessions should last 24 hours, which at this point it hadn't even been 24 hours since the system was up.  

I don't know why your session was invalid, but that would be what had to have occurred in order to get the message you got.  This would also seemingly fit into the behavior you were seeing previously from this issue: #755 where the post of your answers does not succeed but the client proceeds on in an attempt to get the validation, and in turn "unreceived" verdict.

-----

```
{
  "acvVersion" : "1.0",
  "error" : "Results for Vector Set id: 8287 cannot be submitted with status:
PASSED"
}
```

I'm assuming that's at the posting results endpoint? that would be encountered if you attempted to post answers to a test session that's already passed.

**Comment by Kritner** [comment]
Haven't heard back in a bit, so closing for now.  

@smuellerDD a lot of the issue we seem to be having in the back and forth in this issue and in #755 does seem to point to something strange happening between the client and ACVP server when attempting to submit answers (after some time has passed?).  

In many cases we're not actually showing an attempt at answer submission. Not sure if there's some additional logging you could put into place on your client that writes out the response after the answer submit, but I think we'll need to try to reproduce the issue at some point in the demo environment to really dig in.
