### ISSUE TITLE
Production server: PBKDF rejects "keyLen" keyword

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#766]
**environment**
Prod

**testSessionId**
556, 557

**vsId**

6127, 6093

The server returns the following during vector upload:

```
{
  "acvVersion" : "1.0",
  "error" : "Incorrectly formatted JSON (922:2): Unknown or disallowed submission property: keyLen"
}
```

Note, the test response worked on demo server.

**Comment by Kritner** [comment]
@smuellerDD it doesn't look like we expect the `keyLen` in your response file.  Submitting the `keyLen` on demo was fine?

We can take a look at any potential differences between demo and prod early next week; but in the meantime can you try submitting your results without `keyLen`?

A response should look like:

```
{
  "vsId": 1,
  "algorithm": "kdf-components",
  "mode": "pbkdf",
  "revision": "1.0",
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "derivedKey": "986B212420E3B977068244E6BD..."
        },
        {
          "tcId": 2,
          "derivedKey": "B8F3EEC6B5FA270FB05644DE40..."
        }
      ]
    }
  ]
}
```

**Comment by smuellerDD** [comment]
sure, I should read the received response correctly, sorry for the noise.
