### ISSUE TITLE
DELETE vsId: test session verdict is undefined

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#769]
After falling into the trap of issue #765 I had to delete the two SHAKE vsIds from my test session.

I did and I got a successful response back. I re-downloaded the test session verdict which now contains "expired" for the DELETEd vsIDs (as expected), but the final verdict referenced with the keyword "passed" is NULL:

```
[ {
  "acvVersion" : "1.0"
}, {
  "passed" : null,
  "results" : [ {
```

I guess that should contain passed considering that all other vsIDs in my vector set are pass.

Production server: test session 674

**Comment by smuellerDD** [comment]
I am now about to request the certificate for this session. But I cannot.

1. A GET on /acvp/v1/testSessions/674 shows:
```
[ {
  "acvVersion" : "1.0"
}, {
  "url" : "/acvp/v1/testSessions/674",
  "acvpVersion" : "1.0",
  "createdOn" : "2020-01-23T14:32:01.886Z",
  "expiresOn" : "2020-02-22T14:32:01.886Z",
  "encryptAtRest" : false,
  "vectorSetsUrl" : "/acvp/v1/testSessions/674/vectorSets",
  "publishable" : true,
  "passed" : null,
  "isSample" : false
} ]
```
--> So I should be able to publish

2. a PUT /acvp/v1/testSessions/674 fails:

```
{
  "acvVersion" : "1.0",
  "error" : "Test Session has not yet passed all tests."
}
```

Could you please help me what to do?

Thanks

**Comment by smuellerDD** [comment]
Note, this is a production request.

**Comment by smuellerDD** [comment]
As SHAKE works now, I will re-obtain a complete new test session. Yet, I will keep the issue open to test it.

**Comment by Kritner** [comment]
@smuellerDD scenarios like this should now work on demo (and prod once the release makes it there).  Let me know if there are any issues, thanks!
