### ISSUE TITLE
ACVP Production server unavailable

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#772]
Although I can login to the production server, I am not getting any data from it. I only get the retry answer.

This applies to both, fetching test vectors and submitting responses.

**Comment by Kritner** [comment]
@smuellerDD acknowledged, I don't have access to the environment but trying to get a hold of someone who does.

**Comment by Kritner** [comment]
@smuellerDD prod should be up and running now

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. Januar 2020, 14:10:31 CET schrieb Russ Hammett:

Hi Russ,

> @smuellerDD prod should be up and running now

I am trying to restart the download of test vectors I registered for. This 
seems to not work as I am still waiting.

Shall I request new test sessions? If yes, then please accept that there are 
now a number of stale test sessions on the prod server.

Ciao
Stephan

**Comment by Kritner** [comment]
Hmm... yeah depending on when in the flow through our system the failure occurred, I can see how vector sets could be stuck; we're working on a better way to handle this.

The fastest way would be to resubmit the sessions, though I think I could get the sessions back to a good state with a bit of time. @shaneshaffer

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. Januar 2020, 15:29:49 CET schrieb Russ Hammett:

Hi Russ,

> Hmm... yeah depending on when in the flow through our system the failure
> occurred, I can see how vector sets could be stuck; we're working on a
> better way to handle this.
> 
> The fastest way would be to resubmit the sessions, though I think I could
> get the sessions back to a good state with a bit of time. @shaneshaffer

If you are fine with it, I can easily re-sumit the request.

All I want to make sure is we are not getting blamed for "developing" on the 
prod server. :-)

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. Januar 2020, 15:29:49 CET schrieb Russ Hammett:

Hi Russ,

> Hmm... yeah depending on when in the flow through our system the failure
> occurred, I can see how vector sets could be stuck; we're working on a
> better way to handle this.
> 
> The fastest way would be to resubmit the sessions, though I think I could
> get the sessions back to a good state with a bit of time. @shaneshaffer

Note, I even have several test sessions where I uploaded responses and now I 
am not getting the verdicts.

Again, I can easily get new vectors.

Ciao
Stephan

**Comment by Kritner** [comment]
> All I want to make sure is we are not getting blamed for "developing" on the
prod server. :-)

No blame, this is on our end for sure.

> Note, I even have several test sessions where I uploaded responses and now I
am not getting the verdicts.

I'm assuming this is in regards to the vectors submitted from when initially opening this issue? Because yeah that makes sense too.

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. Januar 2020, 15:48:14 CET schrieb Russ Hammett:

Hi Russ,

> 
> > Note, I even have several test sessions where I uploaded responses and now
> > I
> am not getting the verdicts.
> 
> I'm assuming this is in regards to the vectors submitted from when initially
> opening this issue? Because yeah that makes sense too.

I am still not getting anything. The new test sessions are: 740, 741, 742.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. Januar 2020, 16:32:30 CET schrieb Stephan Mueller:

Hi,

> Am Mittwoch, 29. Januar 2020, 15:48:14 CET schrieb Russ Hammett:
> 
> Hi Russ,
> 
> > > Note, I even have several test sessions where I uploaded responses and
> > > now
> > > I
> > 
> > am not getting the verdicts.
> > 
> > I'm assuming this is in regards to the vectors submitted from when
> > initially opening this issue? Because yeah that makes sense too.
> 
> I am still not getting anything. The new test sessions are: 740, 741, 742.

They are just starting to pour in - strange, it takes quite a bit longer than 
it used to.
> 
> Ciao
> Stephan



Ciao
Stephan

**Comment by Kritner** [comment]
@smuellerDD there's a bit of a backlog of work to get through (some of which may even be your previous test sessions) due to the issue from earlier

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. Januar 2020, 16:35:08 CET schrieb Stephan Mueller:

Hi Russ,

> Am Mittwoch, 29. Januar 2020, 16:32:30 CET schrieb Stephan Mueller:
> 
> Hi,
> 
> > Am Mittwoch, 29. Januar 2020, 15:48:14 CET schrieb Russ Hammett:
> > 
> > Hi Russ,
> > 
> > > > Note, I even have several test sessions where I uploaded responses and
> > > > now
> > > > I
> > > 
> > > am not getting the verdicts.
> > > 
> > > I'm assuming this is in regards to the vectors submitted from when
> > > initially opening this issue? Because yeah that makes sense too.
> > 
> > I am still not getting anything. The new test sessions are: 740, 741, 742.
> 
> They are just starting to pour in - strange, it takes quite a bit longer
> than it used to.

I was able to get 3 test sessions. But when uploading the results, I get two 
verdicts, but for the remaining verdicts, I am waiting now for an hour.

Also, in the mean time I requested some 20 new test sessions and I am waiting 
now for 2h to get data.
> 
> > Ciao
> > Stephan
> 
> Ciao
> Stephan



Ciao
Stephan

**Comment by smuellerDD** [comment]
works again

**Comment by smuellerDD** [comment]
Again, the prod server does not (or does very slowly) provide test vectors. My request now runs for 5h and I got 20 out of 280 vsIds

**Comment by smuellerDD** [comment]
After some 10h I left my code requesting the download of test vectors, the ACVP server starts responding and delivers data.

**Comment by smuellerDD** [comment]
currently the server does not deliver anything

**Comment by Kritner** [comment]
@smuellerDD related to #774 we're been doing some tweaking of concurrency values on our end, and it looks that prod is much more stable, are you able to verify that?

**Comment by smuellerDD** [comment]
Am Freitag, 31. Januar 2020, 14:56:28 CET schrieb Russ Hammett:

Hi Russ,

> @smuellerDD related to #774 we're been doing some tweaking of concurrency
> values on our end, and it looks that prod is much more stable, are you able
> to verify that?

Yesterday it delivered, but much slower than it used to - this is a gut 
feeling though.

I will have to download more vectors today and will report afterwards.

Ciao
Stephan

**Comment by smuellerDD** [comment]
I am trying to download 48 vsIds for each test session. I have two test sessions with equal requests (807 vs 809)

When I hit the server with at most 16 request threads, I get all vectors (even ones that take longer) in a reasonable time - this is test session 807.

When I hit the server with 48 threads (one for each vsID), the long running vsIds take much longer (I am waiting now for more than 1h that took some 10 minutes for the other test session).

**Comment by smuellerDD** [comment]
A colleague of mine independently is hitting the prod server too with 2 vsIds (test session 809) and he sees also the slow response.

**Comment by smuellerDD** [comment]
now, even the authentication is slow - it takes a minute for an authentication

**Comment by smuellerDD** [comment]
The uploading of test results and getting of verdicts works reasonably fast compared to the demo server.

**Comment by Kritner** [comment]
@smuellerDD I'm not sure what was going on with authentication, that's on a completely separate server that we were not doing any tweaking with.

And just to be clear:

> The uploading of test results and getting of verdicts works reasonably fast compared to the demo server.

You're saying that the demo server is slower than the prod server currently?  We have done our tweaks (which limit concurrency) AFAIK only on the prod server, so that's interesting. Though it's pretty safe to say there's a lot more traffic occurring on the demo server in comparison to prod.

Things on prod seem pretty stable right now, and we have a few changes in the works based on this ticket that will allow us to better handle activity ramp ups. Stay tuned, and thanks for the patience!

**Comment by smuellerDD** [comment]
Re auth: it is now back to normal.
Re getting verdicts: I wanted to express that the prod and the demo server both have about the same speed (gut feeling).

With the reports above I wanted to let you know about the current state I saw. If you have updated the settings and the prod server is now stable (most important), I am fine when the prod server is slower compared to the demo server.

Close the issue at your discretion.

**Comment by smuellerDD** [comment]
I have to open that issue again: I currently trying to validate the results for test vectors obtained in October on the prod server. I got some verdicts, but for the majority, I am currently now waiting for 3 hours without progress.

For example: test sessions 230, 233, 226, 235, 229, 293, 297, 360, 347

**Comment by Kritner** [comment]
in reference to: https://github.com/usnistgov/ACVP/issues/772#issuecomment-582854237

> I have to open that issue again: I currently trying to validate the results for test vectors obtained in October on the prod server. I got some verdicts, but for the majority, I am currently now waiting for 3 hours without progress.

> For example: test sessions 230, 233, 226, 235, 229, 293, 297, 360, 347

**Comment by smuellerDD** [comment]
First of all, all works now and the server seems to be faster than last week.

I am waiting on a GET <VSID>/results endpont and I get always a retry. But this morning, all works.

**Comment by Kritner** [comment]
Ok, I'll close this for now as prod has seemed pretty stable after the last round of tweaks and the release.
