### ISSUE TITLE
Prod: failed to generate test vectors

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#774]
When I hit the production server with a larger number of requests, I see several of the following errors:

```
[ {
  "acvVersion" : "1.0"
}, {
  "vsId" : 9217,
  "status" : "error during vector generation",
  "message" : "failed to generate tests for: 9217"
} ]
```

I do not see those issues any more on the demo server using the same request sizes.

When I use a lower number of threads to more serialize the requests, I do not see such issues.

vsID: 9217, 9222, 9245, 9243

Shall I decrease the number of threads? If yes, what would be sensible?

Note, I need to re-obtain the affected test sessions to allow a publication of my IUT.

**Comment by Kritner** [comment]
@smuellerDD we're going through some additional tweaking of things on our side.  This shouldn't need to be something you need to change on your side, it's something that we'll just hopefully find the sweet spot with with these tweaks.

Sorry for the inconvenience.

**Comment by smuellerDD** [comment]
Am Freitag, 31. Januar 2020, 14:55:30 CET schrieb Russ Hammett:

Hi Russ,

> @smuellerDD we're going through some additional tweaking of things on our
> side.  This shouldn't need to be something you need to change on your side,
> it's something that we'll just hopefully find the sweet spot with with
> these tweaks.
> 
> Sorry for the inconvenience.

No worries. For those offending vectors, I already got new vectors.

Close the issue at your discretion.

Ciao
Stephan

**Comment by Kritner** [comment]
With the prod release and the tweaks performed on concurrency values on our end, I believe this can be closed.

Let us know if you do or don't notice a difference! 👍

**Comment by smuellerDD** [comment]
Am Freitag, 7. Februar 2020, 14:26:11 CET schrieb Russ Hammett:

Hi Russ,

> With the prod release and the tweaks performed on concurrency values on our
> end, I believe this can be closed.
 
> Let us know if you do or don't notice a difference! 👍 

Hehe, so I should stay silent then :-)

Thank you, it is now much more performant that it used to be. I cannot comment 
on vector generation on a large scale. But expect that I need to generate a 
couple hundred test session with about 2000 vsIds near term.

Ciao
Stephan
