### ISSUE TITLE
Unclear way forward given error while submitting vector responses for RSA Key Gen

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#776]
**environment**
Demo

**testSessionId**
58386

**vsId**
115359

**Algorithm registration**
RSA Key Gen

**Endpoint in which the error is experienced**
Submitting vector set responses

**Expected behaviour**
When submitting a vendor's vector set responses, I am returned the error:
```json
{
  "acvVersion" : "1.0"
}, {
  "results" : {
    "vsId" : 115359,
    "disposition" : "error",
    "message" : "validation executable failed for: 115359"
  }
}
```

I'm not entirely sure what that means but it's wording suggests perhaps a server-side, backend error but I have no context as to what it is that I am doing incorrectly.

This also appears to be similar to:
https://github.com/usnistgov/ACVP/issues/257

**Comment by Kritner** [comment]
This is related to the "e" value submitted:

```
BitStrings are expected to have an even number of hex characters. Value was "10001".
```

from our system.  These errors will be more easily diagnosable from clients once we roll out #685

**Comment by Kritner** [comment]
Hopefully this helped with your issue @AlexThurston. Let me know if there's anything else.
