### ISSUE TITLE
Empty Test Group and Test Cases in RSA Key Gen vector set

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#777]
**environment**
Demo

**testSessionId**
71972

**vsId**
141110

**Algorithm registration**
```json
{
    "algorithm": "RSA",
    "mode": "keyGen",
    "revision": "1.0",
    "infoGeneratedByServer": true,
    "pubExpMode": "random",
    "keyFormat": "standard",
    "capabilities": [
        {
            "randPQ": "B.3.3",
            "properties": [
                {
                    "modulo": 2048,
                    "primeTest": [
                        "tblC2"
                    ]
                }
            ]
        }
    ]
}
```

This may be expected and normal, but I thought it was unusual.  The test vector that is generated for this capability has a test group and test cases with ID that are empty:
```json
{
   "infoGeneratedByServer": false,
   "keyFormat": "standard",
   "modulo": 2048,
   "primeTest": "tblC2",
   "pubExp": "random",
   "randPQ": "B.3.3",
   "testType": "GDT",
   "tests": [
    {
     "tcId": 48
    },
    {
     "tcId": 49
    },
    {
     "tcId": 50
    }
   ],
   "tgId": 2
  }
```

I would expected this entire group to be left out, if everything inside is also empty.  I thought I'd ask because it might cause issues for vendors generate results and pushing those results up to ACVP.

**Comment by Kritner** [comment]
The expectation is that the IUT will provide valid keys back in each test case generated with the test properties described at the group level.
