### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by hbooth** [usnistgov/ACVP#78]
Need to expand error handling section.

Possible Error message:
```json
{
   "acv_version" : "0.3",
   "error" : "Example error message goes here." 
}
```

Some example HTTP Error codes:
404 if a resource is not found (i.e. a Vector Set Id is provided and it does not exist)
400 if the input to the server is not correct
500 Internal Server Error (i.e. internal database connection issue)

**Comment by atvassilev** [comment]
Reclassifying as enhancement to help prioritize for the v0.3 branch.

**Comment by hbooth** [comment]
422 Unprocessable Entity if a request parameter is missing i.e.:
/validation/acvp/vectors without the vsId (or vs_id) parameter

**Comment by atvassilev** [comment]
This is already implemented and appears to work in most cases. Other related issues have already been open and specific problems will tracked there.
