### ISSUE TITLE
Certificate information not updated

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#781]
**environment**
Prod

**testSessionId**
839 / 840

**vsId**
10287, 10285, 10321, 10319

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
N/A

**Expected behavior**
We filed an updated to existing certificates A115 and A116. The test vectors contain RSA sigver with all hash types (SHA-1 through SHA2-512). The ACVP provided a passing verdict for the responses. The entire test session with the RSA sigver was published. Yet, for the RSA sigver entry, the ACVP server returns that only SHA2-256 (the old information) was tested. The updates were seemingly discarded.

**Additional context**
N/A

**Comment by dsikkema-atsec** [comment]
Is there an update to this issue. The certificates A115 and A116 did not get properly updated with the last publication as listed above.

**Comment by shaneshaffer** [comment]
Our process does not handle updates properly for algorithms where the registration uses a certain structure, apparently. These validations have been updated.

**Comment by dsikkema-atsec** [comment]
Thank you, the certificates look to have the correct information now.

**Comment by smuellerDD** [comment]
Shall we keep that issue open? Close it at your discretion.
