### ISSUE TITLE
Creation of module on demo stuck at processing

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#783]
**environment**
Demo

Has auto-acceptance/creation of resources on demo been disabled?  I am trying to test something out that requires creating a module.  When I do so, I'm returned the request ID (2091 and 2093), but the request seems to be stuck in processing.

It's also possible that my request for creation of a module is incorrect, but if that's the case, I am not receiving any output as to what about the request is not correct.

**Comment by shaneshaffer** [comment]
The ultimate issue is that no address is assigned to the module you are creating, and our system requires each module to have an address.

The specification does not specify whether the addressUrl is optional or required, but in our implementation it is optional. If a module create is received with no addressUrl then the system uses the address of the vendor associate with the module. However vendors are not required to have addresses, and the vendor you specified has no address. This resulted in an unhandled exception.

To avoid this in future creation attempts, add an address to the Vendor record

**Comment by AlexThurston** [comment]
Awesome.  That explains it well.

Given that it seems to me that this does warrant a potential fix on ACVPs end (perhaps to force the vendor resource to have an address since it's required down the road), should I keep this open to track that?

Another potential improvement could be that the feedback of a failing request is that the module is missing an address and it could not be inferred from the vendor since it too doesn't have an address.

**Comment by AlexThurston** [comment]
Related but not quite the same, updating a vendor with an address seems to also be causing my grief.  I've submitted request 12101, and it too seems to be stuck in processing.  I'd imagine that there is something incorrect with my request, but am not seeing any indication as to what.

**Comment by AlexThurston** [comment]
@shaneshaffer I've run into the issue again where I am trying to update a vendor (`11161`) on demo to have an address and the request continues to remain in the `processing` state without any indication of progress or failure.  The request ID this time is: `12291`

The request that I made 24 days ago (`12101`) is also still sitting in the `processing` state.  And I believe it was of a similar nature (adding an address to a vendor that has none).

**Comment by Kritner** [comment]
Changes to the auto approval process has been pushed to demo, this should account for the issues you were experiencing, but if something pops up feel free to reopen and comment
