### ISSUE TITLE
AES-CTR "error during vector generation"

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#784]
**environment**
Demo

**testSessionId**
72826

**vsId**
146452

**Algorithm registration**

> {
        "algorithm": "ACVP-AES-CTR",
        "revision": "1.0",
        "direction": [
            "encrypt"
        ],
        "keyLen": [
            256
        ],
        "payloadLen": [
            64,
            96
        ],
        overflowCounter: false,
        incrementalCounter: true
        },

**Endpoint in which the error is experienced**

> {
    "vsId": 146452,
    "status": "error during vector generation",
    "message": "failed to generate tests for: 146452"
}

And we found that '128' need to be one of the 'payloadLen'.

**Comment by Kritner** [comment]
Yeah 128 is a required bit length for aes-ctr mode - IIRC because the KATs defined for varying AES modes of operation are reliant on a full block.  I thought that was mentioned somewhere in the spec, but if not, could be added.

**Comment by AndrewHYang** [comment]
Hi @Kritner , I still can't find it in the spec.
Anyway, I'll close this issue first.
Thanks!
