### ISSUE TITLE
HMAC-SHA2-256 - error during vector generation

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#786]
**environment**
Demo

**testSessionId**
73435

**vsId**
149902

**Algorithm registration**

> {
  "algorithm": "HMAC-SHA2-256",
  "revision": "1.0",
  keyLen: [{min:8, max: 524288, increment:1 }],
   macLen: [{min:32, max: 256, increment: 1 }]
}

**Endpoint in which the error is experienced**
{
    "vsId": 149902,
    "status": "error during vector generation",
    "message": "failed to generate tests for: 149902"
}

We tested HMAC-SHA-1, and it was fine. But when it comes to HMAC-SHA2-256, this error occurs.

**Comment by Kritner** [comment]
All HMAC flavors have a requirement of a mod 8 keylen, the same should hold true for HMAC-SHA-1.

```json
{
"algorithm": "HMAC-SHA2-256",
"revision": "1.0",
"keyLen": [{"min":8, "max": 524288, "increment":8 }],
"macLen": [{"min":32, "max": 256, "increment": 1 }]
}
```

Should work

Related: #684

**Comment by AndrewHYang** [comment]
Thanks
