### ISSUE TITLE
Update DRBG testGroups Examples

### ISSUE THREAD

**Issue by ashman-p** [usnistgov/ACVP#79]
The DRBG spec identifies the following as being  part of the test group.
                  "derFunc":"yes",
                  "predResistance": "yes",
                  "entropyInputLen":"112",
                  "nonceLen":"56",
                  "persoStringLen":"112",
                  "additionalInputLen":"112",
but the the example does not reflect this.

Current example ....
     {
                  "version": "0.2",
                  "vectorSetId": "1133",
                  "algorithm": "ctrDRBG",
                  "mode": "3KeyTDEA",
                  "derFunc":"yes",
                  "predResistance": "yes",
                  "entropyInputLen":"112",
                  "nonceLen":"56",
                  "persoStringLen":"112",
                  "additionalInputLen":"112",
                  "returnedBitsLen":"256",
                  "testGroups": [
                    {
                      "type": "long",
                      "tests": [
                        {
"tcId": "1815",

Correction needed is ...

Current example ....
     {
                  "version": "0.2",
                  "vectorSetId": "1133",
                  "algorithm": "ctrDRBG",
                  "mode": "3KeyTDEA",
                  "derFunc":"yes",
                  "predResistance": "yes",
                  "entropyInputLen":"112",
                  "nonceLen":"56",
                  "persoStringLen":"112",
                  "additionalInputLen":"112",
                  "returnedBitsLen":"256",
                  "testGroups": [
                    {
                      "type": "long",
                      "tests": [
                        {
                        "tcId": "1815",

Correction should include.

   {
                  "version": "0.2",
                  "vectorSetId": "1133",
                  "algorithm": "ctrDRBG",
                  "mode": "3KeyTDEA",
                  "derFunc":"yes",
                  "predResistance": "yes",
                  "entropyInputLen":"112",
                  "nonceLen":"56",
                  "persoStringLen":"112",
                  "additionalInputLen":"112",
                  "returnedBitsLen":"256",
                  "testGroups": [
                  **"derFunc":"yes",
                  "predResistance": "yes",
                  "entropyInputLen":"112",
                  "nonceLen":"56",
                  "persoStringLen":"112",
                  "additionalInputLen":"112",**
                    {
                      "type": "long",
                      "tests": [
                        {
                        "tcId": "1815",

**Comment by atvassilev** [comment]
Yeah, the examples are incorrect with respect to the schema definition but the corrected examples should be as follows:

{
"version": "0.2",
"vectorSetId": "1133",
"algorithm": "ctrDRBG",
"mode": "3KeyTDEA",
"testGroups": [
{
"derFunc":"yes",
"predResistance": "yes",
"entropyInputLen":"112",
"nonceLen":"56",
"persoStringLen":"112",
"additionalInputLen":"112",
"returnedBitsLen":"256",
"tests": [
{
"tcId": "1815",


Note that each test group should include a set of parameters values unique for that group. A vector set may include more than one test group, each with its own parameters. There is no need to have "type" here, and the schema does not define it. 

Take a look and let me know if you disagree. I will fix the spec later today.

**Comment by ashman-p** [comment]
Thank you. Yes, want you have is correct.
