### ISSUE TITLE
KeyLen 192 of AES-XPN

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#791]
In the spec, "192" can be the keyLen of AES-XPN. But in the demo server, it gets rejected.

**Comment by Kritner** [comment]
Can you provide the registration you're attempting with @AndrewHYang ?

**Comment by AndrewHYang** [comment]
> [
   {
      "acvVersion":"1.0"
   },
   {
      "algorithms":[
         {
            "prereqVals":[
               {
                  "algorithm":"AES",
                  "valValue":""
               },
               {
                  "algorithm":"DRBG",
                  "valValue":""
               }
            ],
            "direction":[
               "decrypt"
            ],
            "keyLen":[
               192
            ],
            "payloadLen":[
               {
                  "min":8,
                  "max":65536,
                  "increment":8
               }
            ],
            "ivLen":[
               {
                  "min":8,
                  "max":1024,
                  "increment":8
               }
            ],
            "ivGen":"external",
            "ivGenMode":"8.2.2",
            "saltGen":"external",
            "aadLen":[
               {
                  "min":0,
                  "max":65536,
                  "increment":8
               }
            ],
            "tagLen":[
               112,
               104
            ],
            "algorithm":"ACVP-AES-XPN",
            "revision":"1.0"
         }
      ],
      "encryptAtRest":false,
      "isSample":true
   }
]

**Comment by Kritner** [comment]
This is an issue with the specification, I can issue an update. Additionally note that only 96 bit IVs are valid for AES-XPN, so that part of the registration would be rejected as well had a 128 or 256 bit key been used.
