### ISSUE TITLE
Canceling of vsIds - work queue is not freed?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#792]
I have two totally separate operations registering the very same cipher options. The 2nd request operation is performed about 10 minutes after the first.

Both requests result in 5 test sessions with about 250 vsIDs.

The first gets the test vectors reasonably fast, the second request is kept waiting, as expected.

Now, I cancel the first request and issue a DELETE on all vsIDs. About 150 test vectors were returned for the first request until the deletion operation.

The second request now should receive its test vectors reasonably fast considering that the queue is freed up. But it is still kept waiting as if the first request is still processed.

Side note: the first and second requests have test session IDs which are almost adjacent:

1st request: 74535 74536 74533 74538 74537

2nd request: 74540 74541 74542 74543 74544

**Comment by celic** [comment]
This is something we can look at in the refactor. In the current system, the DELETEs will have no bearing on what is in the queue, so everything will still be processed. This should be rather simple to do though, if a DELETE on a TS (or VS) is received, check the queue for ongoing processes.

**Comment by shaneshaffer** [comment]
Today's deployment adds cancellation of related queued tasks upon a vector set or test session cancellation. It won't stop tasks that are actively being processed, but any that are waiting in the queue to be processed will be eliminated.

**Comment by smuellerDD** [comment]
Am Freitag, 29. Mai 2020, 21:44:40 CEST schrieb shaneshaffer:

Hi shaneshaffer,

> Today's deployment adds cancellation of related queued tasks upon a vector
> set or test session cancellation. It won't stop tasks that are actively
> being processed, but any that are waiting in the queue to be processed will
> be eliminated.

Very good. I think we can close that.


Ciao
Stephan
