### ISSUE TITLE
Prod: GET /acvp/v1/algorithms times out

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#794]
Note, it used to work.

The demo server works as well.

**Comment by jarnold01** [comment]
Hi Stephan, 

I'm checking in the logs and at the time of your connections, the server is reporting a lot of attempted (but failed) TLSv1.1 connection attempts, which just seems very odd all the way around. I'm going to restart the web server service as a precautionary measure.... there, it's done. 

Please attempt your connection again when you can. Thanks.

**Comment by smuellerDD** [comment]
Am Mittwoch, 4. März 2020, 14:11:04 CET schrieb Jason Arnold:

Hi Jason,

> Hi Stephan,
> 
> I'm checking in the logs and at the time of your connections, the server is
> reporting a lot of attempted (but failed) TLSv1.1 connection attempts,
> which just seems very odd all the way around. I'm going to restart the web
> server service as a precautionary measure.... there, it's done.
> 
> Please attempt your connection again when you can. Thanks.

Demo works

Prod still does not return anything:

```*   Trying 52.204.191.193:443...
* TCP_NODELAY set
*   Trying 2600:1f18:268d:1d01:acfb:16e5:57b4:96ac:443...
* TCP_NODELAY set
* Immediate connect fail for 2600:1f18:268d:1d01:acfb:16e5:57b4:96ac: Network 
is unreachable
* Connected to acvts.nist.gov (52.204.191.193) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /run/media/sm/PRIVATE/cst-acvp/digitcert_bundle.pem
  CApath: none
* SSL connection using TLSv1.2 / AES128-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Maryland; L=Gaithersburg; O=National Institute of 
Standards and Technology; OU=STVM ACVP; CN=acvts.nist.gov
*  start date: Aug  8 00:00:00 2019 GMT
*  expire date: Aug  8 12:00:00 2020 GMT
*  subjectAltName: host "acvts.nist.gov" matched cert's "acvts.nist.gov"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /acvp/v1/algorithms HTTP/1.1
Host: acvts.nist.gov
User-Agent: ACVPProxy/1.2.6
Accept: */*
Authorization: Bearer foo

* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Expires: Wed, 11 Mar 2020 12:12:59 GMT
< Connection: keep-alive
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Transfer-Encoding: chunked
< Content-Type: application/json;charset=UTF-8
< Date: Wed, 04 Mar 2020 13:12:59 GMT
<

```

At the end of the last line, there should be the response from the server, but 
there is none.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Mittwoch, 4. März 2020, 14:11:04 CET schrieb Jason Arnold:

Hi Jason,

> Hi Stephan,
> 
> I'm checking in the logs and at the time of your connections, the server is
> reporting a lot of attempted (but failed) TLSv1.1 connection attempts,
> which just seems very odd all the way around. I'm going to restart the web
> server service as a precautionary measure.... there, it's done.
> 
> Please attempt your connection again when you can. Thanks.

Whoops, update: the server did return something, but too large (134233778 
bytes).

After re-trying, it fails to get me something:

After retrying again, I get the massive download again.

Ciao
Stephan

**Comment by jarnold01** [comment]
I'm monitoring the server and one of the processes is slamming the CPU. I'm just going to restart the server. Stand by...

**Comment by jarnold01** [comment]
Okay please give it another try

**Comment by smuellerDD** [comment]
Am Mittwoch, 4. März 2020, 14:30:11 CET schrieb Jason Arnold:

Hi Jason,

> Okay please give it another try

Another massive download starts.

After receiving 128MB my client terminated the connection.

Note, the beginning of the data does contain the cipher listing. Yet, I do not 
think that you want to send more than 128 MB.

Ciao
Stephan

**Comment by celic** [comment]
Would it be possible to email us the response you are getting? 128MB is definitely more than we want to send.

**Comment by Kritner** [comment]
@smuellerDD we're still looking into this on prod (if that was unclear) could you send us what you did receive, if you still have it, through nfiles?

**Comment by celic** [comment]
It seems the server is a little too excited to share KAS-FFC (algo ID 71) causing the response to explode in size. We are trying to address this, though it is curious to only happen in a single environment.

**Comment by smuellerDD** [comment]
Am Mittwoch, 4. März 2020, 18:45:24 CET schrieb Russ Hammett:

Hi Russ,

> @smuellerDD we're still looking into this on prod (if that was unclear)
> could you send us what you did receive, if you still have it, through
> nfiles?

Easier said than done:

* OpenSSL SSL_read: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert 
certificate unknown, errno 0
* Closing connection 0

I seem to get a wrong cert from the prod server?

This is the POST for authentication.

Ciao
Stephan

**Comment by Kritner** [comment]
Hey @smuellerDD we're still looking into things and have more or less locked down the environment until things are sorted out.  Will keep you updated when we have some!

**Comment by jarnold01** [comment]
Hi @smuellerDD , can you please test it now and let us know? I have restored access. Thanks.

**Comment by smuellerDD** [comment]
Confirmed, working.
