### ISSUE TITLE
ECDSA component testing

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#798]
ECDSA siggen component testing contains "componentTest" in the vector.

ECDSA sigver component testing contains "component" in the vector.

Should that be consolidated?

**Comment by celic** [comment]
Within the prompt itself? Yeah, I'll double check.

**Comment by smuellerDD** [comment]
Am Freitag, 6. März 2020, 20:18:21 CET schrieb Chris Celi:

Hi Chris,

> Within the prompt itself? Yeah, I'll double check.

The testvectors that the server generates contain that.

Ciao
Stephan

**Comment by celic** [comment]
Yup. Thanks for the heads up. This will appear in the next deployment. As this is a small issue, I'll go ahead and close this out now.
