### ISSUE TITLE
SP800-56 rev3: FixedInfo definition update request

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#800]
SP800-56 rev3 section 3.4.1.3 specifies the fixed info. The FixedInfo encoding that is allowed is concatenation (with ASN.1 coming eventually).

The example outlines that the fixed info data for concatenation looks like:

```
          "fixedInfoPattern": "algorithmId||l||uPartyInfo||vPartyInfo",
          "encoding": [
            "concatenation"
          ]
```

I have several concerns with this:

1. There is double information: first, the encoding is specified as "concatenation" and second, the concatenation is defined in in the fixed info string with the "||" sign. I dislike duplication.

2. With the given structure, I am unsure how the array of encodings is there. Since the structure of the fixedInfo is already hard-wired to, say, "concatenation", there cannot be a different encoding type.

Thus, may I propose to use an array for the fixedInfo definition to get something like:

```
 "fixedInfoPattern":  [ "algorithmId", "uPartyInfo", "literal[fobar]" ],
"encoding": [
            "concatenation"
          ]
```

Note, the JSON array order matters and thus you have a given order for concatenation.

Then the parsing is simpler for you.

**Comment by Kritner** [comment]
Hey @smuellerDD I do like this suggestion, but I'm not sure that I'll be able to make the time to do these updates and make them specific to the newer revisions of kas (that would be SP800-56Ar3 as well as SP800-56Br2).

There's currently a lot of code reuse in this particular functionality between the new kases, as well as the existing "1.0" revision of kas testing.  If I can make enough headway in the other things I'm working on, I can try to work this in, but I can't make any promises right now.

**Comment by smuellerDD** [comment]
Note, this applies to the KAS/KTS IFC definition as well.

**Comment by awolf-bc** [comment]
I have a related comment about the "fixedInfo" specification in the registration JSON. It seems to me there are some important 'formatting' decisions **implied**, instead of explicitly listed.
I mean the choice of formatting:
 * a 'fixed field' (and what length) or
 * a 'variable field' 'Datalen||Data' (and what size the 'Datalen' parameter has).

According to the spec (Section 5.8), this shall be part of the 'protocol specification', which the JSON field in question is describing (see a quote at the end). For example: The data field of 'uPartyInfo' is not well defined, since it may contain the 'U' id data (and maybe the nonce) in any kind of formatting, so right now I have no clear idea what is used.

A simple suggestion would be to add a field ```"fixedInfoFormat"``` with a string or array value that (somehow) describes the *fixed* and/or *variable* sizes (of the data or datalen parts) in bytes.

> Each such substring shall have one of these two formats: either it is a fixed-length bit string, or it has the form Datalen|| Data–where Data is a variable-length  string  of  zero  or  more  (eight-bit)  bytes,  and Datalen is  a  fixed-length, big-endian counter  that  indicates  the  length  (in  bytes)  of Data.  (In  this  variable-length  format,  a  null string  of  data shall be  represented  by  a  zero  value  for Datalen,  indicating  the  absence  of following  data.)  A  protocol  using  this  format  for FixedInfo shall specify  the  number, ordering and meaning of the information-bearing substrings that are included in each of the subfields AlgorithmID, PartyUInfo, and PartyVInfo,and shall also specify which of the two formats  (fixed-length  or  variable-length)  is  used  by  each  such  substring  to  represent  its distinct  item  of  information.  The  protocol shall specify  the  lengths  for  all  fixed-length quantities, including the Datalen counters.

**Comment by Kritner** [comment]
@awolf-bc you're correct, I probably did make a few decisions that I meant to revisit.

The `fixedInfoFormat` you're referring to is what's described from https://usnistgov.github.io/ACVP/artifacts/acvp_sub_kas_ffc_Sp800-56Ar3.html#rfc.section.3.4.1.3

The current method supported is only `concatenation`, though I did write another encoding format of `concatenationWithLengths` (though have not yet enabled it).  Concatenation with lengths was to use a 32 bit counter (not configurable, I wanted to be safe) but is effectively the same thing as `concatenation` just... with lengths.  I can try to get this enabled if you're interested.  I did not end up finding an easy way to get the asn.1 encoding in, hoping I'll be able to at some point.

The uPartyInfo and vPartyInfo you're correct their construction was not explicit, I will try to pull the construction from our implementation, but IIRC it's `[n]PartyId||[n]PublicKey`.

Regarding the additional fields such as `algorithmId`, `context`, and `label` the server was just substituting in 128 bit random values for those fields, and providing them to the IUT to be used for their own fixed input construction.

I'll follow up with this a bit more tomorrow, but having not actually seen an implementation of this out in the wild and (as you've discovered) a lot of ambiguity around this particular portion of the standard, I'm curious if you have any recommendations to make this as interoperable as possible.

**Comment by awolf-bc** [comment]
Thank you for that in-depth description and the help with 'xPartyInfo'.

I agree that using ```concatenation``` as a description of 'not-ASN.1' and 'fixed-length format' may work just fine. The issue that made me aware of the 'missing length' in the JSON specification was the example of ```l``` (length of returned DKM data in bits), which can be added to the "FixedInfo". The 'length' of that entry (8, 16 or 32 bits) is not 'set' with the tools available in the JSON specs. The current server implementation seems to use a 32 bit entry.

Communicating these lengths between the IUT and the test server during registration should make it easier to match the data in 'FixedInfo' between the two.
