### ISSUE TITLE
SP800-56A rev3 SPEC issues

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#802]
- dependencies: Isn't the dependency on SP800-108 KDFs missing?

- 3.5 example registration: remove vsId entry?

- definition of requiresEmptyIv: This keyword is not defined in SP800-108 SPEC.
Why does it show up here and not in SP800-108?

- example in 3.5 does not contain "function" entry

**Comment by Kritner** [comment]
> definition of requiresEmptyIv: This keyword is not defined in SP800-108 SPEC.
Why does it show up here and not in SP800-108?

This was a somewhat recent addition to the SP800-108 specification #730

> example in 3.5 does not contain "function" entry

I think this is ok as it's an optional field

I'll make a PR addressing the other issues

**Comment by smuellerDD** [comment]
Am Dienstag, 10. März 2020, 15:44:29 CET schrieb Russ Hammett:

Hi Russ,

> > definition of requiresEmptyIv: This keyword is not defined in SP800-108
> > SPEC.
> Why does it show up here and not in SP800-108?
> 
> This was a somewhat recent addition to the SP800-108 specification #730

I see it, thanks for the pointer
> 
> > example in 3.5 does not contain "function" entry
> 
> I think this is ok as it's an optional field
> 
> I'll make a PR addressing the other issues

Thx

Ciao
Stephan
