### ISSUE TITLE
What are `scenarios` in a validation and how are they represented in a certificate (ie. CAVP list)

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#810]
I was performing some testing to better understand the interplay of how certificates can be updated.  This all stemmed from the conversation within this other issue https://github.com/usnistgov/ACVP/issues/799

I'm also using what appears to be an undocumented API to read validations.  I'm not sure if this is meant to work on not, but it's been useful to understand what a certificate might end up looking like on production.  The issue I raised about that undocumented API is https://github.com/usnistgov/ACVP/issues/720

In my experiments, I've added a new algorithm to an existing certificate with a single OE, and I've added a new OE to an existing certificate.  These all appear to work as expected.

My next experiment was to attempt to add a new algorithm to a certificate that currently has two OEs.

I created a test session with the previous algorithms and the new one and submitted it associating it with the first OE.  Once that was done, I noticed that a new `scenario` within the validation object was created and within it had the additional algorithm.  The previous `scenario` remained the same.  When I then submit another test session which would represent the testing on the second OE, the second scenario was updated to contain both OEs.

My question is what are these `scenarios` and how do they correlate with that is scene as a certificate on the [CAVP list](https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/validation-search?searchMode=validation&family=1&productType=-1&ipp=25)?

**Comment by AlexThurston** [comment]
Incidentally, my validation ID on demo is `41360`

**Comment by AlexThurston** [comment]
Related to this as well.  I also wanted to see what happens when I try to remove algorithms from a certificate by publishing a test session with  reduced number of algorithms against a module an OE.  I tried this and the request appears to be stuck processing.

This is on Demo
Module ID: `11728`
Test Session: `76048`
OE: `21419`

Request ID: `12324`

**Comment by Kritner** [comment]
We were/are in the process of deprecating scenarios, sorry for the delayed response.
