### ISSUE TITLE
Demo server altering website field in vendor post

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#811]
Hello,

It appears that when we post vendors (e.x. 11382) to the demo server, the demo server appends an http: to the front when it approves it, making it http:www.example.com.

Is this desired behavior? The formatting of that string seems rather off-standard (as opposed to http://www.example.com), and I can't find any mention in the spec if the ACV server is expected to modify posted vendor data at all. Just curious what the reasoning would be (and if there is a specific pattern we should follow for this posting vendors in general).

Thanks,
Andrew

**Comment by shaneshaffer** [comment]
This was rather incorrect behavior in the ACV server, and has been corrected.
