### ISSUE TITLE
SSL Certificate Connection Issue

### ISSUE THREAD

**Issue by JacobBarthelmeh** [usnistgov/ACVP#812]
I was recently issued a certificate and TOTP. To test the credentials I gave the accompanying ACVP client linked in the README a try with them. The connection is failing for me with a SSL certificate error.

```
$ export ACV_TOTP_SEED=<my totp string>
$ ./app/acvp_app --vector_req test-req.req --aes

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    <path to>/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  <path to>/demo.cer
    ACV_KEY_FILE:   <path to>/demo.key

***ACVP [ERR][acvp_curl_http_post:686]--> Curl failed with code 58 (Problem with the local SSL certificate)

***ACVP [STATUS][log_network_status:1394]--> POST Login...
	Status: 0
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login

***ACVP [STATUS][acvp_login:2099]--> Login Send Failed
***ACVP [ERR][acvp_run:2722]--> Failed to login with ACVP server
```

With a second attempt I tried to connect with a simple TLS client capable of running the HTTP command GET on sites (just to do the connection not to go farther and handle TOTP). I was expecting the connection to get closed down after the TLS handshake had finished but it is getting closed by the server right after the client hello is sent. Is there specific TLS extensions / protocol versions that the demo server accepts?

~jacob

**Comment by jarnold01** [comment]
Hi @JacobBarthelmeh , TLSv1.2 is fully supported, TLSv1.3 has been recently enabled but is still in a "test mode". So it is stated, TLSv1.1 is NOT supported. TLSv1.2 is the recommended version at this time.

**Comment by JacobBarthelmeh** [comment]
Thanks @jarnold01 for the protocol versions. I was able to get the accompanying ACVP client to connect so the credentials are good. I'll work some more on the simple TLS client but having a successful connection case I consider this issue closed.
