### ISSUE TITLE
KAS_IFC documentation comments

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#814]
After implementing SP800-56B rev2 KAS/KTS IFC, I have the following comments:

3.4.1.1.1: Modulo -> modulo

3.4.1.1.1: FixedPublicExponent -> fixedPubExp to be consistent with RSA

3.2: "algorithm": the specification seems to be internally inconsistent here. It allows the specification of only one algorithm, but the "scheme" definition allows a list of objects which may include KAS and KTS. I think there needs to be one and only valid value for algorithm.

3.4.1: names of schema inconsistent with examples (see capitalization)

3.4.1.1.1: the modulo size of 7168 seems to be not accepted:

```
{
  "acvVersion" : "1.0",
  "error" : "Property value(7168) for (scheme/KAS1-Party_V-confirmation/keyGenerationMethods/rsakpg1-basic/modulo) in Algorithm (KAS-IFC (null)) is not valid. Validation: (Values must be one of: 2048, 3072, 4096, 6144, 8192)"
}
```

**Comment by Kritner** [comment]
> 3.2: "algorithm": the specification seems to be internally inconsistent here. It allows the specification of only one algorithm, but the "scheme" definition allows a list of objects which may include KAS and KTS. I think there needs to be one and only valid value for algorithm.

The intention here is that "KAS-IFC" should be used for KAS-IFC schemes, and "KTS-IFC" should be used for KTS-IFC schemes; the distinction between the schemes available for each algorithm is called out in https://usnistgov.github.io/ACVP/artifacts/acvp_sub_kas_ifc.html#supported_schemes

Would it make more sense if this was also called out under the description of algorithm in https://usnistgov.github.io/ACVP/artifacts/acvp_sub_kas_ifc.html#cap_ex ?

**Comment by smuellerDD** [comment]
I am wondering why there should be a KAS-IFC and KTS-IFC algorithm type. Why not just have one name and let the schema specification decide what the user wants. At the moment there are two pieces of information which in essence provide the same information. This can only lead to inconsistencies.

The term KTS == key transport schema and KAS == key agreement schema seems to be not used consistently with FIPS IG D.9. Thus, why not use the IG-compliant name for the "algorithm" type - i.e. "KES" == key encapsulation schema and use the SP800-56B naming convention (KAS/KTS types) in the "schema" keyword.
