### ISSUE TITLE
RSA signaturePrimitive Test Has Incomplete CRT Parameters

### ISSUE THREAD

**Issue by tobyp** [usnistgov/ACVP#817]
When requesting vectors for an RSA `signaturePrimitive` test with `"keyFormat": "crt"`, the keys in the test cases are provided with the parameters `n`, `dmpq`, `dmq1`, and `iqmp`. At least one of the factors `p` or `q` are required as well to perform the test; cf. RFC 3447 5.2.1, which lists the parameters (p, q, dP, dQ, qInv) for RSASP1 in CRT variant.

**environment**
Demo

**testSessionId**
77792

**vsId**
174648

**Algorithm registration**
```[{"acvVersion": "1.0"}, {"isSample": false, "algorithms": [{"algorithm": "RSA", "mode": "signaturePrimitive", "revision": "1.0", "keyFormat": "crt"}]}]```

**Comment by Kritner** [comment]
Sorry for the delay in this... the change has been pushed to demo.  I'll update the issue again once the change is pushed to production 
![image](https://user-images.githubusercontent.com/8814983/91082646-ef7f7c80-e616-11ea-84ff-dfe5077ebb64.png)

**Comment by tobyp** [comment]
Thanks for the response, the parameters in your screenshot look good.
I'm unable to test this, however, due to the capability registration issue described in #714.

**Comment by tobyp** [comment]
All necessary parameters are now available. Thanks for the good work here!

**Comment by Kritner** [comment]
this change is now on production https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.12
