### ISSUE TITLE
RSA signaturePrimitive Test Does Not Support Fixed Exponent

### ISSUE THREAD

**Issue by tobyp** [usnistgov/ACVP#818]
The RSA `signaturePrimitive` test does not support `pubExpMode` and `fixedPubExp` like the `sigVer` test does.
This makes it impossible to test implementations that only support a fixed exponent, as the key parameters are fully server-selected in this test.

**Comment by celic** [comment]
This is being worked on and was requested previously.

**Comment by Kritner** [comment]
closing this issue as a dupe of the linked #714
