### ISSUE TITLE
Investigate DRBG prediction resistance testing

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#82]
Wanted to keep this as generic as possible (can update as details get fleshed out).

The spec does not currently account for CAVS parameters `EntropyInputReseed` and `AdditionalInputReseed`.  Both of these parameters were utilized for tests with the following options:

Prediction Resistance Not Enabled = true
Reseeding not Implemented = false, 

There is some potential confusion around why reseeding would be tested in a non PR scenario.  While details and potential solutions are considered, this issue is here to track the conversation.

**Comment by atvassilev** [comment]
Addressed with PR #85
