### ISSUE TITLE
No spec for ECDSA mode: sigGenComponent

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#820]
ECDSA mode: sigGenComponent  is listed in README.md. But it cannot be found in the spec of ECDSA. Is it still being implemented or missed in the spec?

**Comment by smuellerDD** [comment]
Am Freitag, 27. März 2020, 00:58:04 CET schrieb Andrew H. Yang:

Hi Andrew,

> ECDSA mode: sigGenComponent  is listed in README.md. But it cannot be found
> in the spec of ECDSA. Is it still being implemented or missed in the spec?

Granted, it is not really documented, but it is available. Use the boolean 
"componentTest" for either siggen or sigver to request the component test 
vectors.

Ciao
Stephan
