### ISSUE TITLE
HMAC MAC length with one value

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#821]
HMAC MAC Length is it possible to have Min and Max as the same value say 256. the current error when you try and do this says "Fail to save session, please check: Property value(increment must be less than or equal to the difference between min and max) for (mac) in Algorithm (HMAC-SHA2-256 (null)) is not valid. Validation: (Number Between (32) and (256) modulus 1)"

**environment**
Demo

**Algorithm registration**

> {
"algorithms": [{
"keyLen": [{"min": 8, "max": 524288, "increment": 8}], 
"macLen": [{"min": 256, "max": 256, "increment": 1}], 
"algorithm": "HMAC-SHA2-256", "revision": "1.0"}], 
"encryptAtRest": false, "isSample": true
}

**Endpoint in which the error is experienced**
Fail to save session, please check: Property value(increment must be less than or equal to the difference between min and max) for (mac) in Algorithm (HMAC-SHA2-256 (null)) is not valid. Validation: (Number Between (32) and (256) modulus 1)

**Comment by smuellerDD** [comment]
Am Freitag, 27. März 2020, 01:10:10 CET schrieb Andrew H. Yang:

Hi Andrew,

> HMAC MAC Length is it possible to have Min and Max as the same value say
> 256. the current error when you try and do this says "Fail to save session,
> please check: Property value(increment must be less than or equal to the
> difference between min and max) for (mac) in Algorithm (HMAC-SHA2-256
> (null)) is not valid. Validation: (Number Between (32) and (256) modulus
> 1)"

Instead of using a range domain, use an absolute number?
> 
> **environment**
> Demo
> 
> **Algorithm registration**
> 
> > {
> 
> "algorithms": [{
> "keyLen": [{"min": 8, "max": 524288, "increment": 8}],
> "macLen": [{"min": 256, "max": 256, "increment": 1}],
> "algorithm": "HMAC-SHA2-256", "revision": "1.0"}],
> "encryptAtRest": false, "isSample": true
> }
> 
> **Endpoint in which the error is experienced**
> Fail to save session, please check: Property value(increment must be less
> than or equal to the difference between min and max) for (mac) in Algorithm
> (HMAC-SHA2-256 (null)) is not valid. Validation: (Number Between (32) and
> (256) modulus 1)



Ciao
Stephan

**Comment by Kritner** [comment]
As @smuellerDD stated, the `Domain` type can take an array of `Range` objects mixed along with literals.

https://usnistgov.github.io/ACVP/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.16.4

**Comment by AndrewHYang** [comment]
Thanks. It's really helpful.
