### ISSUE TITLE
Server health endpoint?

### ISSUE THREAD

**Issue by fliphil** [usnistgov/ACVP#822]
Hello,

I'm wondering if there's an endpoint that the server provides for clients to determine the "health" of the server. I see there's https://demo.acvts.nist.gov/home but not sure if that is intended to communicate that the server is functioning properly.

Something along the lines of this: https://docs.microsoft.com/en-us/azure/architecture/patterns/health-endpoint-monitoring

This is useful for clients to determine whether the the server is up or down without needing to perform a login or use the ACVP spec.

Please let me know, thanks!
Phil

**Comment by Kritner** [comment]
There is not currently @fliphil but it is something I'd like to roll out at some point when we're through our currently workload.

**Comment by fliphil** [comment]
Thanks I'll keep an eye on this issue!

**Comment by fliphil** [comment]
Wondering where this currently falls in your development roadmap? With the latest changes http://demo.acvts.nist.gov/ top level page now requires a peer certificate which broke my rudimentary server status check of just checking the homepage.

**Comment by celic** [comment]
Yes, the homepage no longer exists, so every endpoint on the server requires a certificate. 

We do not have plans for this at the moment.

**Comment by fliphil** [comment]
@celic Okay, I hope that this can become a thing at some point. Needing the credentials and to perform a login is very heavy to check the status of the server, especially if you are trying to limit which services have access to the NIST credentials.

**Comment by celic** [comment]
Minor update to this issue for completeness... `/health` was added and does not require a JWT to access. `/algorithms` was also modified in 2020 to not require a JWT to access. Both of these should provide a full server status to users.

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.18](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.18)

Wiki documentation on the endpoint is here: https://github.com/usnistgov/ACVP-Server/wiki/Health-Check---Server-Version-Endpoint

**Comment by Kritner** [comment]
This change has been released to prod in release [v1.1.0.18](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.18).
