### ISSUE TITLE
Empty vectors for KAS-FFC Sp800-56Ar3

### ISSUE THREAD

**Issue by awolf-bc** [usnistgov/ACVP#823]
**environment**
Demo

**testSessionId**
78785

**vsId**
178998

**Algorithm registration**
```
{
 "algorithms":[
 {
  "algorithm": "KAS-FFC",
  "revision": "Sp800-56Ar3",
  "function": [
    "keyPairGen"
  ],
  "iutId": "123456ABCD4242",
  "scheme": {
    "dhEphem": {
      "kasRole": [
        "initiator",
        "responder"
      ],
      "kdfMethods": {
        "oneStepKdf": {
	  "auxFunctions": [
	    { "auxFunctionName": "SHA2-256" }
	  ],
	  "fixedInfoPattern": "literal[123456789CAFECAFE]||uPartyInfo||vPartyInfo",
	  "encoding": [
	    "concatenation"
	  ]
	}
      },
      "l": 256
    }
  },
  "domainParameterGenerationMethods": [
    "MODP-2048"
  ]
 }
]
}
```

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443/acvp/v1/testSessions GET

**Expected behavior**
I expect a test group of test vectors to be returned.

**Additional context**
The returned test group consists of an empty array.
I see other issues related to this algorithm, here, and I am wondering if this is hitting the same bug. Since I am new to this system, I am also questioning the validity of the registration data.
Any help is appreciated!

Returned JSON:
```
[ {
  "acvVersion" : "1.0"
}, {
  "vsId" : 178998,
  "algorithm" : "KAS-FFC",
  "revision" : "Sp800-56Ar3",
  "isSample" : false,
  "testGroups" : [ ]
} ]
```

**Comment by Kritner** [comment]
This is definitely a new one... I'll take a look, thanks!

**Comment by Kritner** [comment]
I'm putting in a correction on our end, will keep you updated when it's on demo.

The specific issue is around using a hash under the "auxFunction", right now the groups are not properly being generated for hashes, but should be for MACs; though there are other issue corrections already in the pipeline to demo that would probably prevent successful generation as well.

Additionally, though it is in the specification, the literal specified under your fixedInfoPattern has an odd amount of characters. `BitString`s into the system are expected to be an even number of hex characters.  I'll make sure to update the specification related to this.

I'll make sure this fix makes it out with the other changes already on their way to demo.

**Comment by awolf-bc** [comment]
Thank you for your fast feedback!
I will adjust the `fixedInfoPattern` value, it definitely makes sense that it always must be an even number!

**Comment by Kritner** [comment]
A push related to this has been pushed out to demo.  Let me know if there are any further issues.

**Comment by awolf-bc** [comment]
Thanks! This is working well, now.

Is this 'fixed' for the DEMO service only? If so, what is the time line to have this code on PRODUCTION service?

**Comment by Kritner** [comment]
56Ar3 is not yet on prod, we were waiting on some folks to get through testing successfully on demo with it to try to figure out if anything needed to change regarding the format of the json and the like before we were more or less "locked in" after making the algorithm live.  

Not sure on timeline to prod yet but since there are several successful runs through 56Ar3 on demo, going to prod is at least now an option.
