### ISSUE TITLE
Unknown error with AES-ECB 

### ISSUE THREAD

**Issue by JacobBarthelmeh** [usnistgov/ACVP#825]
**environment**
Demo

**testSessionId**
80061

**vsId**
184747

**Algorithm registration**

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions/80061/vectorSets/184747/results GET

**Expected behavior**
Expecting fail/incomplete/unreceived/expired/pass or error message to guide resolving issue. What is returned is a disposition of error with no message.

```
[ {
  "acvVersion" : "1.0"
}, {
  "results" : {
    "vsId" : 184747,
    "disposition" : "error",
    "message" : ""
  }
} ]

```

**Additional context**
Was seeing "pass" with AES-CBC before, and then this unknown error when submitting AES-ECB.

**Comment by JacobBarthelmeh** [comment]
As an update now when trying to get the test vectors a second time on this vector set it is showing an error for vector generation.

https://demo.acvts.nist.gov/acvp/v1/testSessions/80061/vectorSets/184747 GET

```
[ {                                                      
  "acvVersion" : "1.0"                                                        
}, {                                                                          
  "vsId" : 184747,                                                            
  "status" : "error during vector generation",                                
  "message" : ""                                                              
} ]
```

**Comment by Kritner** [comment]
Hey @JacobBarthelmeh this is related to #685, but here's what I'm getting back internally:

```
BitStrings are expected to have an even number of hex characters. Value was "AC7BE7B46A75C9DC4C24661467DA025".
```

**Comment by JacobBarthelmeh** [comment]
Thanks @Kritner , should I change something in the JSON sent to request the test vectors? Am just curious how to move forward after hitting the error or if I should delete the session and create a new one?

**Comment by Kritner** [comment]
the simplest thing would be to create a new session for the moment, we're working on a few updates that will make cases like this simpler to retry.  If you want to save this particular session, I can try to have someone update the vector set to allow resubmission.

**Comment by JacobBarthelmeh** [comment]
Deleting the session and creating a new one works, no worries about fiddling with the vector set on your side. Just checking to see if there was something that should be tweaked in the client code while developing it. Thanks Kritner.

**Comment by Kritner** [comment]
aside from ensuring the hex strings are an even number of characters no that should be it. The bitstrings should be passed on the MSB
