### ISSUE TITLE
Difference In CMAC-AES Advertising  

### ISSUE THREAD

**Issue by JacobBarthelmeh** [usnistgov/ACVP#826]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**

```
{
				"algorithm":	"CMAC-AES",
				"revision":	"1.0",
				"capabilities":	[{
						"direction":	"gen",
						"keyLen":	128,
						"keyingOption":	0,
						"msgLen":	[{
								"min":	8,
								"max":	2048,
								"increment":	8
							}],
						"macLen":	[{
								"min":	8,
								"max":	128,
								"increment":	8
							}]
					}, {
						"direction":	"ver",
						"keyLen":	128,
						"keyingOption":	0,
						"msgLen":	[{
								"min":	8,
								"max":	2048,
								"increment":	8
							}],
						"macLen":	[{
								"min":	8,
								"max":	128,
								"increment":	8
							}]
					}, {
...
...
```

Response from server is

```
{
  "acvVersion" : "1.0",
  "error" : "Incorrectly formatted JSON (93:5): expected array value and detected scalar: direction"
}
```

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions POST

**Expected behavior**
Just as a FYI that the document here (https://github.com/usnistgov/ACVP/blob/master/src/acvp_sub_mac.xml) has a different format for CMAC-AES in the example than it appears the server is expecting.

**Additional context**
I've worked around this by taking a guess based on other algorithms and using the following. It seems to work so far and generate test vectors. 

```
{
				"algorithm":	"CMAC-AES",
				"revision":	"1.0",
				"capabilities":	[{
						"direction":	["gen", "ver"],
						"keyLen":	[128, 192, 256],
						"keyingOption":	0,
						"msgLen":	[{
								"min":	8,
								"max":	2048,
								"increment":	8
							}],
						"macLen":	[{
								"min":	8,
								"max":	128,
								"increment":	8
							}]
					}]
			}
```

**Comment by AlexThurston** [comment]
I can't help with inconsistencies between the example and the documentation, but the error says this:
`expected array value and detected scalar: direction"`

Looking at the documentation, it says direction should be an array, not a value.
![image](https://user-images.githubusercontent.com/3537360/79582154-63be7800-8099-11ea-95ff-386755604f46.png)

So your direction should be: `["gen"]`  or `["gen", "ver"]` or `["ver"]`

There are a number of places throughout the documentation where the examples aren't totally correct.  I'd take those examples with a grain of salt and try to adhere to what the documentation tables say.

It's like that with the `keyingOption` as well.  The example has them listed for CMAC-AES, but the documentation doesn't have them.

**Comment by Kritner** [comment]
@JacobBarthelmeh sorry I missed this one come in, but yeah what @AlexThurston responded with is accurate.

Our json samples are often generated via code that handles more than a single "algorithm" (aes and tdes cmac in this case) so I guess taking out the the "default values" for the property like `keyingOption` for AES was missed.  This can be corrected in the specification.
