### ISSUE TITLE
Suggestion/Poll:  Convert "values" with valid response of "yes/no" to boolean

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#83]
I know we're getting close to our branch date of the spec, so wanted to get this out there just to get an opinion.  We have several parts of the spec that state an expectation of a value with valid responses being `yes` or `no`; what are everyone's thoughts on using the primitive `boolean` instead?

I'm not (necessarily) suggesting this change be made prior to the branch, but was curious on what everyone's thoughts are - if it's wanted at all, and if it should be done before or after the branch.

**Comment by hbooth** [comment]
I would be supportive of converting to the use of boolean, and I would want to be consistent through out. I can handle changing it now or later.

**Comment by atvassilev** [comment]
I am also supportive of converting to boolean. Timing would depend in part on when the client implementation would like to take the hit on conversion.

**Comment by atvassilev** [comment]
Reclassifying as Enhancement, to help prioritize for branching v0.3.

**Comment by celic** [comment]
Along a similar line here, boolean variables should be named positively. So with `optional = true` this means we do NOT need a variable. While not an immediate problem it is not intuitive. I'd suggest changing the `optional` column to `required` so that `required = true` is a positive affirmation.

**Comment by celic** [comment]
Fixed for SHA, RSA, Symmetric with #161, #162 

This should be kept in mind for other algorithms as we look more in depth at them.

**Comment by celic** [comment]
Needs to be updated:
* protocol
* drbg
* hmac
* kas_ecc
* kas_ffc
* sha3
* sha

**Comment by celic** [comment]
@Kritner was this fixed for HMAC/MAC in #173 ?

**Comment by Kritner** [comment]
@celic yes it was, i forgot to mention that.  Thanks!

**Comment by atvassilev** [comment]
Can this issue be closed now?

**Comment by celic** [comment]
No, there are some documents that haven't been looked at yet that need this conversion. Unless a more specific issue is opened, we need some way to keep track of the remaining documents. As I see, the protocol, kas_ecc, and kas_ffc need this fix but aren't critical issues right now.

**Comment by celic** [comment]
All the algorithms that would be included in v0.4 have been fixed regarding this issue. Its milestone can be changed to "Far Horizons".

**Comment by atvassilev** [comment]
As indicated above, many of the fixes are already in place. I will keep this issue open in the "Far horizons" milestone in case other instances of this coding style are discovered.
