### ISSUE TITLE
Test responses: "unreceived" verdict

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#830]
**environment**
Demo

**testSessionId**
77493

**vsId**
173024

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
POST https://demo.acvts.nist.gov:443/acvp/v1/testSessions/77493/vectorSets/173024/results

After responding with twice a 30-second retry, we receive 

```
[ {
  "acvVersion" : "1.0"
}, {
  "results" : {
    "vsId" : 173024,
    "disposition" : "unreceived"
  }
} ]
```

Note, even when we repeat the posting, we get the same result.

**Comment by Kritner** [comment]
@smuellerDD we do occasional cleanup of old data, this particular test session has been removed in one of those cleanups.  We have it on our radar to set these particular test sessions and vector sets to a different status to make that more apparent.
