### ISSUE TITLE
Help with 'error' as disposition of a test vector (KAS-FFC)

### ISSUE THREAD

**Issue by awolf-bc** [usnistgov/ACVP#831]
**environment**
Demo

**testSessionId**
80641

**vsId**
186844

**Algorithm registration**
```
{
 "algorithms":[
 {
  "algorithm": "KAS-FFC",
  "revision": "Sp800-56Ar3",
  "function": [
    "keyPairGen"
  ],
  "iutId": "123456ABCD",
  "scheme": {
    "dhEphem": {
      "kasRole": [
        "initiator",
        "responder"
      ],
      "kdfMethods": {
	"twoStepKdf": {
          "capabilities": [
	    {
              "macSaltMethods": [
                "default"
              ],
	      "fixedInfoPattern": "label||literal[00]||context||l",
              "encoding": [
                "concatenation"
              ],
              "kdfMode": "feedback",
              "macMode": [
                "HMAC-SHA2-256"
              ],
              "supportedLengths": [
                256
              ],
              "fixedDataOrder": [
                "after fixed data"
              ],
              "counterLength": [
                8
              ],
              "requiresEmptyIv": true,
              "supportsEmptyIv": false
            }
          ]
        }
      },
      "l": 256
    }
  },
  "domainParameterGenerationMethods": [
    "MODP-2048",
    "MODP-3072",
    "MODP-4096",
    "MODP-6144",
    "MODP-8192",
    "FB",
    "FC"
  ]
 }
]}
```

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443/acvp/v1/testSessions/80641/vectorSets/186844/results GET

**Expected behavior**
After uploading the results, I'd like to check for a 'fail' or 'passed' disposition of the vector set. In case of an 'error' a non-empty message text might be helpful to identify problems with the result data.

**Additional context**
The returned JSON is
```
[ {
  "acvVersion" : "1.0"
}, {
  "results" : {
    "vsId" : 186844,
    "disposition" : "error",
    "message" : ""
  }
} ]
```
I presume that my submitted result contains bad data (not bad JSON formatting). How can I find a hint on what parts of the result set are bad? Some kind of non-empty message would be great.

**Comment by Kritner** [comment]
We're actively working toward #685 and #684, apologies for the inconvenience it's causing in the interim.

This particular issue I have a fix for in our internal environment (i think it matches another issue, but don't have time atm to double check)

I'll let you know when the fix is on demo

**Comment by Kritner** [comment]
The fix related to this particular ticket has been pushed through to demo, and I reran the validation process on vs 186844.  You should not be able to retrieve the results

**Comment by awolf-bc** [comment]
Excellent! I can see all the results.

Thank you!
