### ISSUE TITLE
No vectors returned for 'SHA2-384' and 'SHA2-512'

### ISSUE THREAD

**Issue by awolf-bc** [usnistgov/ACVP#832]
**environment**
DEMO

**testSessionId**
81374
81375

**vsId**
189677
189678

**Algorithm registration**
```
{"algorithms":[
{
  "algorithm": "SHA2-384",
  "revision": "1.0",
  "messageLength": [{"min": 0, "max": 256, "increment": 8}]
}
]}
```
```
{"algorithms":[
{
  "algorithm": "SHA2-512",
  "revision": "1.0",
  "messageLength": [{"min": 0, "max": 256, "increment": 8}]
}
]}
```

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443/acvp/v1/testSessions/81374/vectorSets/189677 GET
https://demo.acvts.nist.gov:443/acvp/v1/testSessions/81375/vectorSets/189678 GET

**Expected behavior**
Expected the return of test vectors for SHA2-384 and SHA22-512.
The server returned an error.

I bundled both issues in one, since those might be related.

**Additional context**
Received instead
```
[ {
  "acvVersion" : "1.0"
}, {
  "vsId" : 189678,
  "status" : "error during vector generation",
  "message" : ""
} ]
```

**Comment by Kritner** [comment]
@awolf-bc One of the current requirements of testing the shas is that a message length of the digest size must be supported and registered.  for the 384 sha2, a message length of 384 is required as an example.

**Comment by awolf-bc** [comment]
Thanks, I must have missed that, somehow.
Will fix the bad registration values.

**Comment by Kritner** [comment]
I'm not sure if it's actually documented in the specification or not, I know it's a carry over from the CAVS MCT implementations.

It probably should be if it's not ;)
