### ISSUE TITLE
What contacts are used on the CAVP listing page

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#833]
This is hopefully a pretty simple question.

When an ACVP validation is successful and listed on the CAVP list, what contacts are used for the contact section.  Are they the contacts of the vendor or those of the module?

**Comment by shaneshaffer** [comment]
Those are the contacts for the module, as listed under the contactUrls in a module create/update,

**Comment by AlexThurston** [comment]
Perfect.  Thanks for the clarification.
