### ISSUE TITLE
Message Authentication AES GMAC Documentation

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#838]
Another inconsistency between the table documentation and the example.  In this case, it seems like the example might be correct but the documentation is wrong.  The table describing the registration payload is specifies the keyLen as a value:
![image](https://user-images.githubusercontent.com/3537360/80015569-f1d29e00-849f-11ea-8998-75d661780987.png)

But the example, has it as an array of values:
![image](https://user-images.githubusercontent.com/3537360/80015595-fc8d3300-849f-11ea-8e06-bb9f568ab7ed.png)

I'm guessing it's supposed to be an array of values since that would match other similar algorithms, but I can't be sure.

**Comment by celic** [comment]
Yeah we have some changes to these documents in the works. "value" is not descriptive even if this particular variable expected a single element not an array. The types should be proper, so integer > value. But not to get confusing... Yes this should be array.
