### ISSUE TITLE
Update Results Submission failed

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#839]
**environment**
Demo

**testSessionId**
81932

**vsId**
191623

After one of the test cases is failed. I tried to upload another result. Got rejected with error message "Request method 'PUT' not supported".

**Comment by smuellerDD** [comment]
Am Donnerstag, 23. April 2020, 06:24:30 CEST schrieb Andrew H. Yang:

Hi Andrew,

> **environment**
> Demo
> 
> **testSessionId**
> 81932
> 
> **vsId**
> 191623
> 
> After one of the test cases is failed. I tried to upload another result. Got
> rejected with error message "Request method 'PUT' not supported".

Support for updating of results is not (yet) supported. It should come in the 
near future.

Ciao
Stephan

**Comment by celic** [comment]
Yes as @smuellerDD said. We do not currently support this, but will on Demo only in the near future.

**Comment by Kritner** [comment]
demo now supports PUT operations on vector sets.  Please let us know if you find any issues.

**Comment by smuellerDD** [comment]
Am Dienstag, 26. Mai 2020, 16:14:03 CEST schrieb Russ Hammett:

Hi Russ,

> demo now supports PUT operations on vector sets.  Please let us know if you
> find any issues.

confirmed, working.

Ciao
Stephan
