### ISSUE TITLE
Certificate details cannot be obtained

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#840]
**environment**
Prod

**testSessionId**
1109

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
GET /acvp/v1/validations/32482

**Expected behavior**
Get the certificate details

**Additional context**
The certificate request was approved. The approval ID that was returned by the server is 32482. The server returned the following error when requesting the certificate details:

```
{
  "acvVersion" : "1.0",
  "error" : "Internal Server Error. Please contact administrator for assistance."
}
```

Note, the certificate was issued (A389).

**Comment by AlexThurston** [comment]
It would also be really handy to have some documentation on this route (ie https://github.com/usnistgov/ACVP/issues/720)

Most pertinently, does this route accept any query parameters other than **offset** and **limit**

**Comment by smuellerDD** [comment]
Am Donnerstag, 23. April 2020, 14:13:43 CEST schrieb Alex Thurston:

Hi Alex,

> It would also be really handy to have some documentation on this route (ie
> https://github.com/usnistgov/ACVP/issues/720)

I am not sure my request relates to issue 720. I have a specific endpoint 
which delivers the certificate details, including the certificate number (e.g. 
A389).

Granted, it is not well documented, but the URL to this object is provided by 
the ACVP server.
> 
> Most pertinently, does this route accept any query parameters other than
> **offset** and **limit**

There is no query option, the URL returns one and only one object.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Donnerstag, 23. April 2020, 16:30:09 CEST schrieb shaneshaffer:

Hi shaneshaffer,

> You are correct, this is an undocumented endpoint for which a URL is
> provided upon certification of a test session. As part of our ongoing
> rewrite of our Public component we are reevaluating this endpoint. The
> current output is for all practical purposes duplicative of the data
> displayed on CSRC - it is really just a slight variation of the original
> validation list demonstrated by ACVTS several years ago, before its
> validations were included on CSRC.
> 
> We now realize that a different kind of validation endpoint may be more
> useful for ACVP - one that provides the IDs of the various metadata objects
> so they can be reused, as an alternative to using the various search
> endpoints (which don't work will when there is duplicate data). We have not
> yet decided what we're ultimately going to do with this endpoint, but when
> the new version of our Public component is deployed we do not plan to
> support the current output.
> 
> A related note - we will be making a change to our internal model for
> validations in a few months which would be incompatible with the current
> output of this endpoint.

I am fine with any way you want to change it provided that there is way that 
for a provisioned certificate I can obtain the real certificate ID.

We rely heavily on this technical mechanism as this allows us to automatically 
manage a complete data base of the test operation and querying the status of 
that database.

> 
> All that said, it isn't clear why the endpoint is not currently working.
> We'll look into it.

Thank you.

Ciao
Stephan

**Comment by shaneshaffer** [comment]
The error with the endpoint appears to have been caused by an internal value that was incorrectly set on two capability records. Those values have been corrected, so the endpoint should now work for that validation.

An internal application update, probably deployed tomorrow, will prevent this from occurring again. We'll fix any more instances that happen to pop up until then.

**Comment by smuellerDD** [comment]
Confirmed, working.
