### ISSUE TITLE
KDF: IKEv2 Documentation

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#843]
The KDF IKEv2 documentation for registration payload is looks like this:
![image](https://user-images.githubusercontent.com/3537360/80098849-8c33ef80-853b-11ea-81d2-69b12296f4a2.png)

The **capabilities** field is listed as an array of objects.

However, the example is shown as an object not an array:
![image](https://user-images.githubusercontent.com/3537360/80099147-019fc000-853c-11ea-88fb-f32ee3df603a.png)

**Comment by celic** [comment]
Yes, capabilities expects an array so that different combinations of values could be used for the same KDF.
