### ISSUE TITLE
RSA SigVer 184-4 generation failure

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#845]
**environment**
Demo

**testSessionId**
81971

**vsId**
191840

```
[ {
  "acvVersion" : "1.0"
}, {
  "vsId" : 191840,
  "status" : "error during vector generation",
  "message" : ""
} ]
```

**Comment by Kritner** [comment]
Hey @smuellerDD we have a fix in working through the environments now regarding this.  I'll let you know when it's on demo.

(and note it was actually an RSA SigVer generation that failed, not SHA)

**Comment by smuellerDD** [comment]
Am Freitag, 24. April 2020, 13:42:08 CEST schrieb Russ Hammett:

Hi Russ,

> Hey @smuellerDD we have a fix in working through the environments now
> regarding this.  I'll let you know when it's on demo.
> 
> (and note it was actually an RSA SigVer generation that failed, not SHA)

Thank you.

Ciao
Stephan

**Comment by smuellerDD** [comment]
As I thought this was a spurious error (other identical sigver requests were successful), I generated production vectors. But one of them failed as well: 1113 / 12668.

Shall I simply delete that test session and obtain a new one on prod?

**Comment by celic** [comment]
You may for the time being. The fix on the server is just stating that this individual test case failed rather than not returning a result.

**Comment by celic** [comment]
Were you able to retest this @smuellerDD ?

**Comment by smuellerDD** [comment]
Issue did not occur any more. Considered fixed.
