### ISSUE TITLE
KAS ECC (and maybe others) and Mode Question

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#846]
Looking at the documentation for KAS ECC, the mode is listed as optional.
![image](https://user-images.githubusercontent.com/3537360/80226491-6df0f100-861a-11ea-8c72-5d34a08484cb.png)
The KAS ECC can be registered as per the examples.
```
{
    "algorithm": "KAS-ECC"
    ...
}
```
 Or
```
{
    "algorithm": "KAS-ECC",
    "mode": "component",
    ...
}
```
But the rest of the registration payload doesn't appear to differ which is surprising to me given my experience with the other sections.  I'm wondering what the difference is between registering KAS algorithm as component or not.

**Comment by smuellerDD** [comment]
Am Freitag, 24. April 2020, 16:58:44 CEST schrieb Alex Thurston:

Hi Alex,

> Looking at the documentation for KAS ECC, the mode is listed as optional.
> ![image](https://user-images.githubusercontent.com/3537360/80226491-6df0f100
> -861a-11ea-8c72-5d34a08484cb.png) The KAS ECC can be registered as per the
> examples.
> ```
> {
>     "algorithm": "KAS-ECC"
>     ...
> }
> ```
>  Or
> {
>     "algorithm": "KAS-ECC",
>     "mode": "component",
>     ...
> }
> ```
> But the rest of the registration payload doesn't appear to differ which is
> surprising to me given my experience with the other sections.  I'm
> wondering what the difference is between registering KAS algorithm as
> component or not.

Basically the hashing. The component testing is without the hashing. the 
"regular" is with hashing of Z.

Ciao
Stephan

**Comment by AlexThurston** [comment]
Perfect.  Thanks.  It was _different_ and I wanted to make sure it wasn't a typo before I went too far.

As always, thanks @smuellerDD
