### ISSUE TITLE
TDES-CBC KeyingOption Value '3' in Test Vector

### ISSUE THREAD

**Issue by awolf-bc** [usnistgov/ACVP#847]
**environment**
DEMO

**testSessionId**
81951

**vsId**
191737

**Algorithm registration**
```
    {
        "algorithm": "ACVP-TDES-CBC",
        "revision": "1.0",
        "direction": [
            "encrypt",
            "decrypt"
        ],
        "keyingOption": [
            1
        ],
        "keyLen": [
            192
        ]
    }
```

**Expected behavior**
Expected to only see value '1' as the ```keyingOption```. Instead I see
```
            "tgId": 1,
            "direction": "encrypt",
            "testType": "AFT",
            "keyingOption": 3,
            "tests": [
                {
                    "tcId": 1,
                    "pt": "0000000000000000",
                    "key1": "1046913489980131",
                    "key2": "0101010101010101",
                    "key3": "1007103489988020",
                    "iv": "0000000000000000"
                },
```

**Additional context**
Is '3' a valid value at all? Per RFC only '1' and '2' are.

**Comment by smuellerDD** [comment]
Am Freitag, 24. April 2020, 17:06:54 CEST schrieb awolf-bc:

Hi awolf,

> Is '3' a valid value at all? Per RFC only '1' and '2' are.

Keying option 2 is legacy as per SP800-131A - i.e. only do be used for 
decryption.

Keying option 1 is the only approved method.

Ciao
Stephan

**Comment by celic** [comment]
Internally we work with `number of keys`, not `keying option`, this is probably a missed conversion between the two. We'll take a look.

**Comment by celic** [comment]
Oh I see. We use keying option 3 as a reference to a KAT, as previously the KATs were set up in a way so that the keys were the same. We had some implementations that couldn't handle this, so we updated the KATs to use three distinct keys, but ended up keeping the keying option value listed here. This can be updated to the true keying option for the group.

**Comment by celic** [comment]
I'm not sure keying option is relevant to the group as it is apparent from the test cases themselves. Thoughts on removal of the property altogether?

**Comment by smuellerDD** [comment]
Am Freitag, 24. April 2020, 17:53:34 CEST schrieb Chris Celi:

Hi Chris,

> I'm not sure keying option is relevant to the group as it is apparent from
> the test cases themselves. Thoughts on removal of the property altogether?

IIRC it is still relevant as there is the legacy 2key TDES operation still 
allowed as per SP800-131A.

And not too long ago I requested an ACVP vector for 2key TDES.

Ciao
Stephan

**Comment by awolf-bc** [comment]
I would agree with Stephan. Keep it and make sure it is '1' or '2' as per request in the registration.

**Comment by awolf-bc** [comment]
The latest update to the DEMO server has fixed this value. It is now '1' with the given registration data. Thank you!
