### ISSUE TITLE
TDES-CBC test vector key values for MCT do not conform to parity requirement

### ISSUE THREAD

**Issue by awolf-bc** [usnistgov/ACVP#848]
**environment**
DEMO

**testSessionId**
81951

**vsId**
191737

**Algorithm registration**
```
    {
        "algorithm": "ACVP-TDES-CBC",
        "revision": "1.0",
        "direction": [
            "encrypt",
            "decrypt"
        ],
        "keyingOption": [
            1
        ],
        "keyLen": [
            192
        ]
    }
```

**Expected behavior**
All initial keys for 'MCT' provided by the server should conform the 'odd-parity' requirement in all bytes.
The returned keys do not:
```
        {
            "tgId": 13,
            "direction": "encrypt",
            "testType": "MCT",
            "keyingOption": 1,
            "tests": [
                {
                    "tcId": 689,
                    "pt": "5D48672E103F88AA",
                    "key1": "B5946228720E1410",
                    "key2": "7B90D30D6ED5BAAB",
                    "key3": "25F80E575CE4986E",
                    "iv": "A4C4E38BB3E3EDC0"
                }
            ]
        }
```

**Additional context**
When the IUT echoes back the 0-th keys they look like this (and have the correct parity):
```
"tcId": 689,
"resultsArray": [
{
"key1": "B5946229730E1510",
"key2": "7A91D30D6ED5BAAB",
"key3": "25F80E575DE5986E",
...
}
```
This problem does not seem to occur for 'AFT' test keys.

**Comment by celic** [comment]
Do you have the vsID for this? As far as I see, keys are generated the same way for AFTs as MCTs.

**Comment by celic** [comment]
Oh sorry, I see what you mean. The response keys are not in parity. The initial keys are fine. As I understand TDES, this should just be a shift to the parity conformance and would not impact the results itself. Also this may have been hidden for a while as it only appears in the expected results with the isSample flag. This likely occurs in other TDES modes.

**Comment by awolf-bc** [comment]
My current IUT fails the 'MCT' tests with these error strings returned:
```
{
    "tcId" : 689,
    "result" : "failed",
    "reason" : "Key does not match on iteration 0"
  }, {
    "tcId" : 690,
    "result" : "failed",
    "reason" : "Key does not match on iteration 0"
  }
```
I am suspecting that all other data in returned the 'MCT' results are actually valid, since no other error is generated.

I was hoping the mismatch in the 'parity' bits may explain the issue and only a 'small fix' on the ACVTS side would be needed. Am I correct?

**Comment by celic** [comment]
We haven't seen any issues on TDES MCT from other clients with the non-parity keys. Yes, with the error message provided, it seems like the only error is the keys not matching. 

Hmm. There are a couple of issues here. According to SP800-20 which originally outlined the MCTs for TDES, during the key transition, key parity is not maintained. XORs are performed, and the keys are NOT shifted if parity is lost. However SP800-20 was withdrawn in 2018. But the MCTs used today are still using that same pseudo-code. Because of this I would argue that shifting the keys back into parity is incorrect, so the implementation is incorrect. 

But clearly, this is more likely a problem with the test itself at this point.

**Comment by smuellerDD** [comment]
Am Dienstag, 28. April 2020, 17:55:44 CEST schrieb Chris Celi:

Hi Chris,

> We haven't seen any issues on TDES MCT from other clients with the
> non-parity keys. Yes, with the error message provided, it seems like the
> only error is the keys not matching.
> 
> Hmm. There are a couple of issues here. According to SP800-20 which
> originally outlined the MCTs for TDES, during the key transition, key
> parity is not maintained. XORs are performed, and the keys are NOT shifted
> if parity is lost. However SP800-20 was withdrawn in 2018. But the MCTs
> used today are still using that same pseudo-code. Because of this I would
> argue that shifting the keys back into parity is incorrect, so the
> implementation is incorrect.
> 
> But clearly, this is more likely a problem with the test itself at this
> point.

If it helps: my test harness always fixes the parity after each key update 
performed by the TDES MCT.

See https://github.com/smuellerDD/acvpparser/blob/master/parser/
parser_sym.c#L83

Ciao
Stephan

**Comment by celic** [comment]
@smuellerDD Thanks. I double checked the code and it DOES do parity fixing on MCT keys. Sorry for the confusion. 

If we look at `B5946228720E1410` for the first key... We have `B5` as the first byte, which is `1011 0101` which has the last bit set to `1` for parity. @awolf-bc The IUT you have agrees.

For `14`, the expanded key is `0001 0100`, has an even number of bits which is incorrect for a TDES key. 

Definitely an error on the server then. Let me do some more digging here and see if I can find the issue and prepare a fix.

**Comment by celic** [comment]
I see the issue. For MCT cases, keys were just random 64-bits rather than 56-bit converted into parity like for AFT. This will affect all modes of TDES that have MCT. A fix is prepared internally and will go out in a future deployment.

**Comment by awolf-bc** [comment]
Great! Thanks for checking!

**Comment by celic** [comment]
As a heads up, in the vsID @awolf-bc posted, there are _some_ AFTs with bad keys. Namely ones that don't use a static key. We group staticly generated KATs and randomly generated AFTs together under the same testType because they are processed the same way. If you look at tcID: 688, the key also doesn't match parity: `FA438D825F673865` (See `82` byte). This fix will also apply to these cases as well.

**Comment by awolf-bc** [comment]
I retried the TDES-CBC MCT test with test vectors generated by the latest code version on DEMO. All keys now have a good 'parity value' and the IUT passes when echoing those initial key values at iteration step '0'.
Thanks!

**Comment by celic** [comment]
Great! Thanks for the report and testing to confirm. We precompute large amounts of MCTs ahead of time because they are the most time consuming part of block cipher registrations. Because of this fix I had to clear out those caches. They will refill naturally, with properly formatted keys.
