### ISSUE TITLE
error 403 trying to get to server

### ISSUE THREAD

**Issue by dsikkema-atsec** [usnistgov/ACVP#850]
**environment**
demo and prod

**testSessionId**
 testID 0 

**vsId**
vsID

**Algorithm registration**
issued command to get cipher list from server

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443/acvp/v1/login

**Expected behavior**
expected login to succeed and to get a list of cipher options

**Additional context**
I tried on both the demo and production server
.  
ACVPProxy (15:34:17) () Status - TOTP MQ System: Requesting OTP value, waiting ...
ACVPProxy (15:34:18) () Status: Logging into ACVP server
ACVPProxy (15:34:18) () Error - HTTP operation: HTTP error status code: 403
ACVPProxy (15:34:29) () Error - HTTP operation: HTTP error status code: 403
ACVPProxy (15:34:40) () Error - HTTP operation: HTTP error status code: 403
ACVPProxy (15:34:41) () Error: Failure in processing testID 0 with vsID 0 (-61)

**Comment by smuellerDD** [comment]
Note, the reported logs may not be helpful to the NIST developers. But it is the very same issue I reported this morning via the mailing list.

**Comment by jarnold01** [comment]
Hi @dsikkema-atsec and @smuellerDD  - @Kritner  and I have been doing some testing on our end and discovered something interesting. 

When you reported that no one at atsec could access Demo any longer, that translated in my head to common factor that everyone at atsec is using the acvp_proxy client. So acvp_proxy clearly didn't like something about the cipher suite change that was made. I then ran a test with the libacvp client installation that I have, and it ran successfully. That got us thinking that perhaps the underlying components (curl and openssl) that the clients rely on might be a good place to focus some testing with next. 

Russ suggested testing with curl first, and in his tests, Demo returned the Forbidden error message. When I ran the same command using my version of curl, I was able to login successfully. I wanted to point out the version differences, in the hopes that you could check what acvp_proxy was built against, and see if you could perhaps run a connection test using an acvp_proxy build using >= the version that I'm using successfully.

Russ' version of curl and openssl (does not work):

$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

Jason's version of curl and openssl (works):

curl 7.64.1 (x86_64-pc-linux-gnu) libcurl/7.64.1 OpenSSL/1.1.1f
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets

This is presently where we are in our troubleshooting, and wanted to share it. Thanks for working with us on this.

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. April 2020, 17:38:04 CEST schrieb Jason Arnold:

Hi Jason,

> This is presently where we are in our troubleshooting, and wanted to share
> it. Thanks for working with us on this.

Thanks, but I do not think that the SSL is the issue. I do get a successful 
TLS channel established. And I can POST the credentials.

And I do get a HTML server response. So, the TLS channel is clearly not the 
issue.

Besides, our code uses CURL on Linux and MacOS native TLS support. Both 
establish a full TLS channel and both can POST data and both do receive the 
HTML response.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. April 2020, 17:38:04 CEST schrieb Jason Arnold:

Hi Jason,

just a note, if you want to see the issue with a noop on the server, you could 
simply use our proxy:

acvp-proxy --cipher-list

This operation logs in and tries to fetch the algorithm list.

Ciao
Stephan

**Comment by jarnold01** [comment]
Hi Stephan,

Thanks for your thoughts. Unfortunately I haven't yet gotten my installation of acvp_proxy to work as yet - just haven't had the bandwidth. If memory serves, when I enabled verbose mode, it complained about not being able to create a message queue or something along those lines. It's probably something with my configuration. I'll put some effort into trying to get that figured today. 

In the meantime, I've temporarily reverted Demo back to the exact configuration it had before I was instructed to update the ciphers. You are welcome to run a test since you have a working client, and I'd be interested in knowing if it works again or not so we can rule TLS out.

Thanks,
Jason

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. April 2020, 18:24:27 CEST schrieb Jason Arnold:

Hi Jason,

> Hi Stephan,
> 
> Thanks for your thoughts. Unfortunately I haven't yet gotten my installation
> of acvp_proxy to work as yet - just haven't had the bandwidth. If memory
> serves, when I enabled verbose mode, it complained about not being able to
> create a message queue or something along those lines. It's probably
> something with my configuration. I'll put some effort into trying to get
> that figured today.
> 
> In the meantime, I've temporarily reverted Demo back to the exact
> configuration it had before I was instructed to update the ciphers. You are
> welcome to run a test since you have a working client, and I'd be
> interested in knowing if it works again or not so we can rule TLS out.
> 
> Thanks,
> Jason

I found the issue after trying libacvp: libacvp uses the OpenSSL cipher of 
AES128-SHA (ie. CBC AES 128 with SHA1)

My proxy used a different cipher, ECDHE-RSA-AES256-GCM-SHA384. And this 
failed.

After hard-coding my proxy to AES128-SHA, it works.

Could you check your advertised cipher and how your server links the cipher 
spec to the authentication?

Ciao
Stephan

**Comment by smuellerDD** [comment]
The demo server now works again without changes in our code. But the prod server is still not accessible.

**Comment by smuellerDD** [comment]
We are now back that the demo server also offers ECDHE-RSA-AES256-GCM-SHA384 that is used by either CURL or the macOS TLS implementation and we cannot log in.

**Comment by Kritner** [comment]
@smuellerDD believe it was mentioned, but we found with differing versions of curl (and as such differing versions of openSsl) we were having luck (or not) with the same ciphers.

IIRC that first cipher you were getting failures on was ecdhe-rsa-aes256-gcm-sha384, where it was working with a more up to date version of curl/openssl.

I don't really know how to interpret this behavior, because like you said you'd think the TLS negotiation would fail, but it isn't.  Not quite sure what it is, but using a more up to date version of curl/openSsl would seemingly fix it no?  Is that a potential option?

**Comment by smuellerDD** [comment]
Am Donnerstag, 30. April 2020, 18:00:48 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD believe it was mentioned, but we found with differing versions
> of curl (and as such differing versions of openSsl) we were having luck (or
> not) with the same ciphers.

How interesting. But I rather think that it has nothing to do with the OpenSSL 
/ libcurl version, but rather how they are compiled, i.e. whether support for 
cipher suite X or Y are there, no?

When I force my libcurl to use the particular cipher suite, it works. I am 
using OpenSSL 1.1.1d which supports and actually prefers the newer ciphers.

The issue with the macOS TLS implementation is that I cannot force it to a 
cipher.
> 
> IIRC that first cipher you were getting failures on was
> ecdhe-rsa-aes256-gcm-sha384, where it was working with a more up to date
> version of curl/openssl.

Are you sure? I am using Fedora 31 which is very bleeding edge:

openssl 1.1.1d
libcurl 7.66.0

And problems started at the beginning of this week when you said you changed 
some TLS updates. Before, with the same OpenSSL/curl / macOS TLS code base, it 
worked flawless.

> 
> I don't really know how to interpret this behavior, because like you said
> you'd think the TLS negotiation would fail, but it isn't.  Not quite sure
> what it is, but using a more up to date version of curl/openSsl would
> seemingly fix it no?  Is that a potential option?

Maybe one idea about a potential issue that I have seen before:

I think it has nothing to do with the version of OpenSSL or libcurl, but 
rather the used cipher spec. In the past for another project I tried an ECDHE 
based cipher suite with an RSA key and that was not really supported by 
different TLS implementations. What about removing the ECDHE ciphers for 
testing and use the DHE ones?

Ciao
Stephan

**Comment by jarnold01** [comment]
Hi Stephan,

In reading your comment back to Russ, I saw your suggestion and implemented the DHE ciphers, removing the ECHDE ones. Unfortunately the results were not acceptable to our security team after they conducted their testing (this is why we were mandated to change the ciphers in the first place.) So far the only ciphers I've found that are acceptable are the ECHDE ciphers. Appreciate the suggestion.

Jason

**Comment by smuellerDD** [comment]
This is very interesting, because you allow TLS_RSA_WITH_AES_128_CBC_SHA which is even the worst cipher (RSA wrapping without PFS). I am looking for a working cipher.

**Comment by jarnold01** [comment]
Yeah, I know. I added it back in, just at a lower server preference in an attempt to ensure continuity, at least until I could validate that the newer ciphers were being utilized successfully. Then I would remove it during some future maintenance cycle - that was the original plan, anyway.

**Comment by smuellerDD** [comment]
Are you sure you have enabled any cipher apart from the old one?

ADH-AES128-GCM-SHA256               fail
ADH-AES128-SHA                      fail
ADH-AES128-SHA256                   fail
ADH-AES256-GCM-SHA384               fail
ADH-AES256-SHA                      fail
ADH-AES256-SHA256                   fail
ADH-CAMELLIA128-SHA                 fail
ADH-CAMELLIA128-SHA256              fail
ADH-CAMELLIA256-SHA                 fail
ADH-CAMELLIA256-SHA256              fail
ADH-DES-CBC3-SHA                    fail
ADH-DES-CBC-SHA                     fail
ADH-RC4-MD5                         fail
ADH-SEED-SHA                        fail
AECDH-AES128-SHA                    fail
AECDH-AES256-SHA                    fail
AECDH-DES-CBC3-SHA                  fail
AECDH-NULL-SHA                      fail
AECDH-RC4-SHA                       fail
AES128-GCM-SHA256                   fail
AES128-SHA                          fail
AES128-SHA256                       fail
AES256-GCM-SHA384                   fail
AES256-SHA                          fail
AES256-SHA256                       fail
CAMELLIA128-SHA                     fail
CAMELLIA128-SHA256                  fail
CAMELLIA256-SHA                     fail
CAMELLIA256-SHA256                  fail
DES-CBC3-MD5                        fail
DES-CBC3-SHA                        fail
DES-CBC-MD5                         fail
DES-CBC-SHA                         fail
DH-DSS-AES128-GCM-SHA256            fail
DH-DSS-AES128-SHA                   fail
DH-DSS-AES128-SHA256                fail
DH-DSS-AES256-GCM-SHA384            fail
DH-DSS-AES256-SHA                   fail
DH-DSS-AES256-SHA256                fail
DH-DSS-CAMELLIA128-SHA              fail
DH-DSS-CAMELLIA128-SHA256           fail
DH-DSS-CAMELLIA256-SHA              fail
DH-DSS-CAMELLIA256-SHA256           fail
DH-DSS-DES-CBC3-SHA                 fail
DH-DSS-DES-CBC-SHA                  fail
DH-DSS-SEED-SHA                     fail
DHE-DSS-AES128-GCM-SHA256           fail
DHE-DSS-AES128-SHA                  fail
DHE-DSS-AES128-SHA256               fail
DHE-DSS-AES256-GCM-SHA384           fail
DHE-DSS-AES256-SHA                  fail
DHE-DSS-AES256-SHA256               fail
DHE-DSS-CAMELLIA128-SHA             fail
DHE-DSS-CAMELLIA128-SHA256          fail
DHE-DSS-CAMELLIA256-SHA             fail
DHE-DSS-CAMELLIA256-SHA256          fail
DHE-DSS-RC4-SHA                     fail
DHE-DSS-SEED-SHA                    fail
DHE-RSA-AES128-GCM-SHA256           fail
DHE-RSA-AES128-SHA                  fail
DHE-RSA-AES128-SHA256               fail
DHE-RSA-AES256-GCM-SHA384           fail
DHE-RSA-AES256-SHA                  fail
DHE-RSA-AES256-SHA256               fail
DHE-RSA-CAMELLIA128-SHA             fail
DHE-RSA-CAMELLIA128-SHA256          fail
DHE-RSA-CAMELLIA256-SHA             fail
DHE-RSA-CAMELLIA256-SHA256          fail
DHE-RSA-CHACHA20-POLY1305           fail
DHE-RSA-SEED-SHA                    fail
DH-RSA-AES128-GCM-SHA256            fail
DH-RSA-AES128-SHA                   fail
DH-RSA-AES128-SHA256                fail
DH-RSA-AES256-GCM-SHA384            fail
DH-RSA-AES256-SHA                   fail
DH-RSA-AES256-SHA256                fail
DH-RSA-CAMELLIA128-SHA              fail
DH-RSA-CAMELLIA128-SHA256           fail
DH-RSA-CAMELLIA256-SHA              fail
DH-RSA-CAMELLIA256-SHA256           fail
DH-RSA-DES-CBC3-SHA                 fail
DH-RSA-DES-CBC-SHA                  fail
DH-RSA-SEED-SHA                     fail
ECDH-ECDSA-AES128-GCM-SHA256        fail
ECDH-ECDSA-AES128-SHA               fail
ECDH-ECDSA-AES128-SHA256            fail
ECDH-ECDSA-AES256-GCM-SHA384        fail
ECDH-ECDSA-AES256-SHA               fail
ECDH-ECDSA-AES256-SHA384            fail
ECDH-ECDSA-CAMELLIA128-SHA256       fail
ECDH-ECDSA-CAMELLIA256-SHA384       fail
ECDH-ECDSA-DES-CBC3-SHA             fail
ECDH-ECDSA-NULL-SHA                 fail
ECDH-ECDSA-RC4-SHA                  fail
ECDHE-ECDSA-AES128-GCM-SHA256       fail
ECDHE-ECDSA-AES128-SHA              fail
ECDHE-ECDSA-AES128-SHA256           fail
ECDHE-ECDSA-AES256-GCM-SHA384       fail
ECDHE-ECDSA-AES256-SHA              fail
ECDHE-ECDSA-AES256-SHA384           fail
ECDHE-ECDSA-CAMELLIA128-SHA256      fail
ECDHE-ECDSA-CAMELLIA256-SHA384      fail
ECDHE-ECDSA-CHACHA20-POLY1305       fail
ECDHE-ECDSA-DES-CBC3-SHA            fail
ECDHE-ECDSA-NULL-SHA                fail
ECDHE-ECDSA-RC4-SHA                 fail
ECDHE-RSA-AES128-GCM-SHA256         fail
ECDHE-RSA-AES128-SHA                fail
ECDHE-RSA-AES128-SHA256             fail
ECDHE-RSA-AES256-GCM-SHA384         fail
ECDHE-RSA-AES256-SHA                fail
ECDHE-RSA-AES256-SHA384             fail
ECDHE-RSA-CAMELLIA128-SHA256        fail
ECDHE-RSA-CAMELLIA256-SHA384        fail
ECDHE-RSA-CHACHA20-POLY1305         fail
ECDHE-RSA-DES-CBC3-SHA              fail
ECDHE-RSA-NULL-SHA                  fail
ECDHE-RSA-RC4-SHA                   fail
ECDH-RSA-AES128-GCM-SHA256          fail
ECDH-RSA-AES128-SHA                 fail
ECDH-RSA-AES128-SHA256              fail
ECDH-RSA-AES256-GCM-SHA384          fail
ECDH-RSA-AES256-SHA                 fail
ECDH-RSA-AES256-SHA384              fail
ECDH-RSA-CAMELLIA128-SHA256         fail
ECDH-RSA-CAMELLIA256-SHA384         fail
ECDH-RSA-DES-CBC3-SHA               fail
ECDH-RSA-NULL-SHA                   fail
ECDH-RSA-RC4-SHA                    fail
EDH-DSS-DES-CBC3-SHA                fail
EDH-DSS-DES-CBC-SHA                 fail
EDH-RSA-DES-CBC3-SHA                fail
EDH-RSA-DES-CBC-SHA                 fail
EXP1024-DES-CBC-SHA                 fail
EXP1024-DHE-DSS-DES-CBC-SHA         fail
EXP1024-DHE-DSS-RC4-SHA             fail
EXP1024-RC4-SHA                     fail
EXP-ADH-DES-CBC-SHA                 fail
EXP-ADH-RC4-MD5                     fail
EXP-DES-CBC-SHA                     fail
EXP-DH-DSS-DES-CBC-SHA              fail
EXP-DH-RSA-DES-CBC-SHA              fail
EXP-EDH-DSS-DES-CBC-SHA             fail
EXP-EDH-RSA-DES-CBC-SHA             fail
EXP-RC2-CBC-MD5                     fail
EXP-RC4-MD5                         fail
GOST2001-GOST89-GOST89              fail
GOST2001-NULL-GOST94                fail
GOST94-GOST89-GOST89                fail
GOST94-NULL-GOST94                  fail
IDEA-CBC-MD5                        fail
IDEA-CBC-SHA                        fail
NULL-MD5                            fail
NULL-SHA                            fail
NULL-SHA256                         fail
PSK-3DES-EDE-CBC-SHA                fail
PSK-AES128-CBC-SHA                  fail
PSK-AES256-CBC-SHA                  fail
PSK-RC4-SHA                         fail
RC2-CBC-MD5                         fail
RC4-64-MD5                          fail
RC4-MD5                             fail
RC4-SHA                             fail
RSA-PSK-3DES-EDE-CBC-SHA            fail
RSA-PSK-AES128-CBC-SHA              fail
RSA-PSK-AES256-CBC-SHA              fail
RSA-PSK-RC4-SHA                     fail
SEED-SHA                            fail
SRP-3DES-EDE-CBC-SHA                fail
SRP-AES-128-CBC-SHA                 fail
SRP-AES-256-CBC-SHA                 fail
SRP-DSS-3DES-EDE-CBC-SHA            fail
SRP-DSS-AES-128-CBC-SHA             fail
SRP-DSS-AES-256-CBC-SHA             fail
SRP-RSA-3DES-EDE-CBC-SHA            fail
SRP-RSA-AES-128-CBC-SHA             fail
SRP-RSA-AES-256-CBC-SHA             fail

**Comment by jarnold01** [comment]
Right now Demo is configured with the original configuration, pre-cipher changes, so that people can work. Prod has the updated configuration. I need to get this worked out in Demo before I can make any changes to Prod though.

**Comment by locksmithone** [comment]
Just as information, the acvp-proxy under windows linux subsystem (wsl)
works without error to both demo and production servers.

MP

**Comment by smuellerDD** [comment]
Jason, can you enable on demo the TLS configuraiton you would like to have? Maybe I can find a cipher that is good for all use cases.

**Comment by jarnold01** [comment]
It's done. Thanks!

**Comment by smuellerDD** [comment]
As far as saw, there are 4 cipher suites supported: TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384.

I can successfully connect and authenticate with the two CBC ciphers. The two GCM ciphers do not work. Thus, could you change your config to remove the two GCM ciphers and leave the CBC ciphers?

**Comment by jarnold01** [comment]
I have removed the two GCM ciphers and reloaded the configuration. Here's what's currently in the list:

TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

I have removed the TLS 1.0 cipher entries; thanks for pointing that out, I thought I had gotten them all.

**Comment by jarnold01** [comment]
Well, without the GCM cipher entries, we're no longer passing the TLS security tests (Authenticated encryption (AEAD) cipher suites are no longer supported)... just FYI. I'll see if I can find another cipher that supports this functionality since the TLS_ECDHE_RSA_WITH_AES_*_GCM_SHA* ciphers are proving problematic for the clients.

**Comment by smuellerDD** [comment]
libcurl works with the non-GCM ciphers, macOS does not, digging into it.

But anyhow, the interesting point is why would authentication fail with a GCM cipher? The symmetric cipher should not have any bearing on the authentication.

Can you see which part of the authentication fails? I.e. the TOTP or the certificate-based authentication?

**Comment by smuellerDD** [comment]
Sorry, I take it back, macOS DOES work with the given CBC ciphers.

**Comment by smuellerDD** [comment]
As a replacement for GCM, what about a CCM cipher?

**Comment by smuellerDD** [comment]
The demo server seems to be accessible still using the CBC cipher. The production server is not unless I force the use of CBC.

As we cannot select the cipher in the macOS native implementation and we start being in need to access the production server, may I ask about the status here? Thanks.

**Comment by jarnold01** [comment]
The cipher suite change has been reverted back (as of 5/13/20) so all clients should now be working again in both Demo and Prod.

**Comment by smuellerDD** [comment]
Confirmed, working.
