### ISSUE TITLE
AES-CCM tagLen field

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#852]
**environment**
DEMO

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
`ACVP-AES-CCM`

**Endpoint in which the error is experienced**
`POST https://demo.acvts.nist.gov/acvp/v1/testSessions`

The documentation for the field `tagLen` is specified as a domain:
![image](https://user-images.githubusercontent.com/3537360/81336373-3c930f00-9077-11ea-9847-76e1232a6115.png)

However, sending a domain specification for Domain:
```JSON
{
    "direction": ["encrypt", "decrypt"],
    "keyLen": [
        128,
        192,
        256
    ],
    "payloadLen": [
        {
            "min": 8,
            "max": 32,
            "increment": 8
        }
    ],
    "aadLen": [
        {
            "min": 8,
            "max": 32,
            "increment": 8
        }
    ],
    "tagLen": [
        {
            "min": 32,
            "max": 128,
            "increment": 16
        }
    ],
    "ivLen": [
        {
            "min": 56,
            "max": 64,
            "increment": 8
        }
    ],
    "algorithm": "ACVP-AES-CCM",
    "revision": "1.0"
}
```

Results in an error:
```JSON
{
  "acvVersion" : "1.0",
  "error" : "Invalid JSON input (1:323): Expected numeric integer value not found."
}
```

It looks as though what ACVP is actually expecting is an array of integers.  This table suggests that maybe that was the intention:
![image](https://user-images.githubusercontent.com/3537360/81336616-a6abb400-9077-11ea-90b4-ac6d24606f08.png)
But that table is documented slightly differently for the CCM case than the others that make use of `tagLen`

It seems like `tagLen` is actually expected to be an array of the following possible values:
```
32, 64, 96, 104, 112, 120, 128
``` 

Is that the case?

**Comment by celic** [comment]
That is correct. I believe we bounced a bit between domain and array for this, but as the tag lengths are intentionally chosen values that only coincidentally share an increment, they should be an array and not a domain. This is a documentation issue only.

**Comment by kwong-cygnacom** [comment]
I just want to re-confirm tagLen is actually expected to be an array of the following values:
32, 48, 64, 80, 96, 112, 128  (from SP 800-38C), 
not 32, 64, 96, 104, 112, 120, 128.

**Comment by celic** [comment]
Correct.
