### ISSUE TITLE
Empty conformances fields causes 500: Internal Server Error

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#853]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
```json
{
    "capabilities": [
        {
            "l": 2048,
            "n": 224,
            "hashAlg": [
                "SHA2-224"
            ]
        }
    ],
    "conformances": [],
    "algorithm": "DSA",
    "mode": "sigGen",
    "revision": "1.0"
}
```

**Endpoint in which the error is experienced**
```POST https://demo.acvts.nist.gov/acvp/v1/testSessions```

It looks as though if a test session is created with an empty array for the `conformances` field, it causes as Internal Server Error:
```
{
  "acvVersion" : "1.0",
  "error" : "Internal Server Error. Please contact administrator for assistance."
}
```

I'm not sure if this only applies to this particular algorithm and mode, or if the others also result in this behaviour.

**Comment by celic** [comment]
I think in the current state, the expectation is that the empty array be excluded from the JSON. This would apply to any algorithm as the individual algorithm logic hasn't been hit at this point in the process. 

We are currently performing internal testing on the new Web Public, so this issue will not be relevant past the next few weeks.

**Comment by AlexThurston** [comment]
That’s fair. I just wanted to let you guys know this was the case.  I’ll
make sure that they are removed going forward.

Generally a user initiated call that results in a 500 is something service
providers wanna know about.

In addition from my perspective, it wasn’t totally obvious from the error
what the problem was which made it all that much more difficult to debug.

Looking forward to giving the new Web Public API a spin when it’s ready.
Sounds like a lot of these issues have been addressed.

**Comment by celic** [comment]
Oh yeah don't get me wrong. This is bad behavior from any Web API. We are not fixing the old platform anymore though. In the future, if a property is mis-formed, the proper response should be to tell the user what is wrong... not returning a generic message and a 500. This was a core point we focused on while designing the new platform. Hopefully that is apparent when it releases.

**Comment by AlexThurston** [comment]
All good. Very much looking forward to using it

**Comment by AlexThurston** [comment]
Is there any information/documentation on this new API?  Is it going to be
the next version or continue being 1.0?

**Comment by Kritner** [comment]
This has been corrected on the recent release to demo.

@AlexThurston I think the idea was to try to keep the API as close as possible to what's currently out there for the specification.
