### ISSUE TITLE
Test session vector sets failing to generate: 83987

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#854]
**environment**
Demo

**testSessionId**
83987

**vsId**
203048, 203035, 203026, 203015, 203012

**Algorithm registration**
A bunch of them :)

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions/83987/vectorSets/<ID>

The vector sets listed above have failed to generate.  The error I receive for each of them is:
```json
{
    "vsId": 203048,
    "status": "error during vector generation",
    "message": ""
}
```

There isn't much information there to debug what the reason might be as the message is blank.  In addition, it doesn't even give me the algorithm that failed.  As far as I can tell, at this point in the process, there is no way for me to correlate the `VSID` with a particular algorithm that I registered.

**Comment by celic** [comment]
For 203048 - HMAC DRBG, the `returnedBitsLen` values are expected to be a multiple of the digest length.

For 203035 - DSA SigVer, the (L, N) pair of (2048, 160) is not valid. 

For 203026 - RSA SigVer for FIPS186-2, it doesn't look like truncated SHAs are supported. This is a little awkward, and I think it is intended. The truncated SHAs didn't come out until after 186-2 was deprecated for 186-3, so they were never supported by that version.

For 203015 - Hash DRBG, same as HMAC DRBG.

For 203012 - Counter DRBG, seems to be a bunch of values only working on byte boundaries not bit boundaries... Here is a lengthy error message...
```
Invalid Personalization String Modulus supplied: Invalid Domain Segment supplied. 
Domain Segment {Min: 0, Max: 112, Increment 1} contained values (1) that were not a multiple of 8.
Personalization String Modulus contained values that were not a multiple of 8;
Invalid Additional Input Modulus supplied: Invalid Domain Segment supplied.
Domain Segment {Min: 0, Max: 112, Increment 1} contained values (1) that were not a multiple of 8.  
Additional Input Modulus contained values that were not a multiple of 8
```

**Comment by smuellerDD** [comment]
Am Montag, 11. Mai 2020, 17:23:25 CEST schrieb Chris Celi:

Hi Chris,

thanks a lot for digging up these errors. To alleviate your burden for such 
debugging, will the new ACVP frontend be more chatty about such issues?

I fear that very soon when a large number of folks hitting ACVP, you will be 
only doing debugging work for the caller's code.

Ciao
Stephan

**Comment by AlexThurston** [comment]
Hey Chris,

I mirror @smuellerDD sentiments, thanks very much for the response.

I'm also hoping that the new API will give us more a little more feedback so we can bug you less :). Not that I don't like chatting with you.

**Comment by celic** [comment]
All the errors I provided came directly from the error messages we will communicate outwards in the new system. We've had them stored internally for a bit, the update will simply provide them to users. Still doing internal testing on the new system, but should be wrapping things up soon. Expect an email this week announcing the update.

**Comment by Kritner** [comment]
The error messages are now being communicated via the public API on demo.  Let me know if there are issues.
