### ISSUE TITLE
Test results returned without description on the nature of the failure

### ISSUE THREAD

**Issue by yeongk** [usnistgov/ACVP#855]
**environment**
Demo

**testSessionId**
84257

**vsId**
205344

**Algorithm registration**
{
  "algorithms": [
    {
      "algorithm": "RSA",
      "revision": "1.0",
      "mode": "keyGen",
      "prereqVals": [
        {
          "algorithm": "SHA",
          "valValue": "same"
        },
        {
          "algorithm": "DRBG",
          "valValue": "same"
        }
      ],
      "infoGeneratedByServer": true,
      "pubExpMode": "fixed",
      "fixedPubExp": "010001",
      "keyFormat": "standard",
      "capabilities": [
        {
          "randPQ": "B.3.4",
          "properties": [
            {
              "modulo": 2048,
              "hashAlg": [
                "SHA2-256"
              ]
            }
          ]
        }
      ]
    }
  ]
}

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443/acvp/v1/testSessions/84257/results GET

**Expected behavior**
Test results; in case of failure, provide reason for the failure

**Additional context**

We see the following from the log with passed=null and status=error, but no description is provided on the nature of the test failure.

***ACVP [STATUS][acvp_login:2341]--> Logging in...
***ACVP [INFO][acvp_http_user_agent_handler:477]--> HTTP User-Agent: libacvp/1.0;Darwin;18.7.0;x86_64;Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz;GCC/4.2.1

***ACVP [INFO][log_network_status:1439]--> POST Login...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp: Recieved

***ACVP [STATUS][acvp_login:2361]--> Login successful
***ACVP [INFO][log_network_status:1427]--> GET Vector Set Result...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/84257/results
	Resp:
[ {
  "acvVersion" : "1.0"
}, {
  "passed" : null,
  "results" : [ {
    "vectorSetUrl" : "/acvp/v1/testSessions/84257/vectorSets/205344",
    "status" : "error"
  } ]
} ]

**Comment by celic** [comment]
Verbose logging is not an option we provide. That might be a flag for the client you are using. We have an update coming out soon with better error messages for the user. The most common issue we see on GitHub is users trying to understand where they went wrong as error messages were not helpful. The fix is coming. I do not have an exact date, but this is something we have referenced in many issues on here. Stay tuned for an email to all ACVP users about this soon.

The error for this particular vector set was...
```
BitStrings are expected to have an even number of hex characters. Value was "9c492bae6d7f597e8b381a4bd2c2e5d818368f65b967c08cdfe753eab43a7e44ee0f5774eae917c8f64380825fa2c66180a5e9df48d0f8ac6e93889b9e9b102a9304a666b8761782c811aac132803dddf98e4814a6843fbe82cb9e738415d5fac8c2b231b3ece24587debfa6e153e3c39e9f617110e8612f1d377aec3f9878fcd4717bd23684ca64352cb50cea04fa76c2ee5906c341a7360ceabe0d846e5f1831c51b5e7a62bd15b294848fa414d776a0b12c8956794259ecaa050d38030bfe993fda9093922e1fdd3c2b66bfb949f6a1f0684414de367c378a1a8ad9b3fbc9882739a88d64285aba01823c25da536970e1375f3e6025f46c7ca0ea5abb501".
```

Simply append a `0` hex character to the front of the bitstring. This does not change the integer value of the bitstring. All bits are always communicated in terms of complete bytes for ACVP. This means all hexadecimal must have an even number of characters.

**Comment by yeongk** [comment]
Thanks for the info. Will make an adjustment for the bit string. Rough timeline for the upcoming update?

**Comment by yeongk** [comment]
Is bitlens[] required for p,q,n,d validation?

**Comment by yeongk** [comment]
environment
Demo

testSessionId
84530

vsId
206595

Submitted another validation request, and got the following response:
$ ./app/acvp_app --get_results testSession_84530.json --verbose

[ {
  "acvVersion" : "1.0"
}, {
  "passed" : null,
  "results" : [ {
    "vectorSetUrl" : "/acvp/v1/testSessions/84530/vectorSets/206595",
    "status" : "unreceived"
  } ]
} ]
***ACVP [ERR][acvp_get_result_test_session:2639]--> Missing submissions for one or more vector sets. Please submit responses for all vector sets.

There is one vector set, and as far as I can see, all test groups were included in the submission. 
Could you check the logging on the server side for this submission?
Thanks for your help

**Comment by Kritner** [comment]
Looks like we lost track of this one.   I'm going to close for the moment since there hasn't been any activity for some time (and the vector sets in question have long expired out).  Feel free to open a new issue/reopen this if the problem persists for new vector sets.
