### ISSUE TITLE
Sample vector for GCM misses IV

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#856]
When requesting a sample vector for GCM, it misses the IV entry for the KAT tests:

Sample vector:
```
[ {
  "acvVersion" : "1.0"
}, {
  "vsId" : 180025,
  "algorithm" : "ACVP-AES-GCM",
  "revision" : "1.0",
  "isSample" : true,
  "testGroups" : [ {
    "tgId" : 1,
    "tests" : [ {
      "tcId" : 1,
      "ct" : "4148662770519814500D09F7910541",
      "tag" : "93576BD2"
    }, {
      "tcId" : 2,
      "ct" : "7DAC3C08E17D96945170584F3A9568",
      "tag" : "A895FEE8"
    }, {
```

Appropriate result expected by ACVP server:

```
[
  {
    "acvVersion":"1.0"
  },
  {
    "vsId":180025,
    "testGroups":[
      {
        "tgId":1,
        "tests":[
          {
            "tcId":1,
            "iv":"b71b488a3954ee16ddc9b2d8",
            "ct":"4148662770519814500d09f7910541",
            "tag":"93576bd2"
          },
          {
            "tcId":2,
            "iv":"879975e6620c87cf7f3629fb",
            "ct":"7dac3c08e17d96945170584f3a9568",
            "tag":"a895fee8"
          },
```

**Comment by Kritner** [comment]
@smuellerDD that particular vector set is old enough that it's already been cleaned from demo - can you provide your registration?  Is that the prompt file you're providing in the ticket (GET "/vectorSets/{vsId} or the expected results (GET "/vectorSets/{vsId}/results")?

Depending on which file that is, and the nature of the registration - namely internal vs external IV, this may be expected behavior.

**Comment by smuellerDD** [comment]
Am Mittwoch, 13. Mai 2020, 13:07:24 CEST schrieb Russ Hammett:

Hi Russ,

> 
> Depending on which file that is, and the nature of the registration - namely
> internal vs external IV, this may be expected behavior.

It is the external IV generation that I used. What I am wondering is that the 
server would reject a response without IV.

The request would be

```
  {
    "isSample":false,
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "algorithms":[
      {
        "revision":"1.0",
        "algorithm":"ACVP-AES-GCM",
        "prereqVals":[
          {
            "algorithm":"AES",
            "valValue":"same"
          },
          {
            "algorithm":"DRBG",
            "valValue":"same"
          }
        ],
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          128,
          192,
          256
        ],
        "payloadLen":[
          128,
          256,
          120,
          248
        ],
        "ivLen":[
          96,
          128
        ],
        "ivGen":"external",
        "ivGenMode":"8.2.1",
        "aadLen":[
          128,
          256,
          120,
          0
        ],
        "tagLen":[
          32,
          64,
          96,
          104,
          112,
          120,
          128
        ]
      },
```

Ciao
Stephan

**Comment by celic** [comment]
With external IV, the client is required to generate the IV and include it in the submitted results. @Kritner was asking which endpoint you noticed missing from. I see `isSample` is `false`, so the `/results` endpoint is not available.

With external IV, the prompt WILL NOT have an IV from the server. The IV is expected to come from a source external to the implementation that is outside of the bounds of testing.

**Comment by smuellerDD** [comment]
Am Mittwoch, 13. Mai 2020, 17:16:57 CEST schrieb Chris Celi:

Hi Chris,

> With external IV, the client is required to generate the IV and include it
> in the submitted results. @Kritner was asking which endpoint you noticed
> missing from. I see `isSample` is `false`, so the `/results` endpoint is
> not available.

Sorry for not being clear.

I performed the mentioned request with isSample `true` and downloaded the 
sample vector. That sample vector does not include the IV.

In my interpretation, the sample vector should be able to be immediately sent 
back to the ACVP server as a response data. But in this case, where the IV is 
missing, it cannot be returned to the ACVP server.
> 
> With external IV, the prompt WILL NOT have an IV from the server. The IV is
> expected to come from a source external to the implementation that is
> outside of the bounds of testing.


Ciao
Stephan

**Comment by celic** [comment]
Sorry. I read into it a bit too much there then. For `isSample: true`, the IV on external _should_ occur in the `/results` file. I see you are correct. I'll make an issue for this on our internal tracker.

**Comment by celic** [comment]
For `internal` IV, the client is responsible for generating and including the IV in the response. For `external` IV, the server is responsible for generating and including the IV in the prompt. This appears to be the case for the server. I don't think any change is needed. (I mixed up internal and external in the previous comment). 

So when you registered for `external` IV generation, the IV was included in the prompt only, regardless of the sample flag.

**Comment by smuellerDD** [comment]
Am Mittwoch, 13. Mai 2020, 21:22:15 CEST schrieb Chris Celi:

Hi Chris,

> For `internal` IV, the client is responsible for generating and including
> the IV in the response. For `external` IV, the server is responsible for
> generating and including the IV in the prompt. This appears to be the case
> for the server. I don't think any change is needed. (I mixed up internal
> and external in the previous comment).
> 
> So when you registered for `external` IV generation, the IV was included in
> the prompt only, regardless of the sample flag.

Thanks for the explanation, but I think I still did not make myself clear. 
When registering a vector with the sample flag and downloading data from /
expected, I assume the data I get follows the specification given in [1].

The data from /expected obtained for a GCM cipher seems to miss the IV 
information. Thus, (a) I expect this data cannot be used to be submitted to /
results, and (b) the data that ought to be generated by the IUT cannot be 
compared with the data from /expected.

[1] https://github.com/usnistgov/ACVP/blob/master/artifacts/draft-celi-acvp-block-ciph-00.txt#L2281

Ciao
Stephan

**Comment by celic** [comment]
When `ivGen: external` the IV will appear in the prompt. When `ivGen: internal`, with `isSample: true`, the IV will appear in `/expected` (expected results file). When `ivGen: internal` with `isSample: false`, the `/expected` file does not exist and it is the client's job to provide an IV during their POST. 

I ran some tests with GCM and found it matched this expected behavior. The example vector set posted earlier in this issue had `ivGen: external` and correctly, the IV only appeared in the prompt file.

**Comment by smuellerDD** [comment]
Am Donnerstag, 14. Mai 2020, 18:23:21 CEST schrieb Chris Celi:

Hi Chris,

> When `ivGen: external` the IV will appear in the prompt.

with ivGen external and sample set to true, /expected did not include the IV 
for me. Hence the bug report. If you say that works now, I will stay silent 
and close the report.

Ciao
Stephan

**Comment by celic** [comment]
That is correct. With ivGen external, /expected WILL NOT have the IV. Regardless of any other property. This means an implementation can accept an externally generated IV so the server provides one in the prompt. So when ivGen external, the IV WILL ALWAYS be provided by the prompt, meaning it has no role to appear in /expected.

**Comment by smuellerDD** [comment]
Ok, if this is the defined behavior, then I will stay silent.
