### ISSUE TITLE
AES GMAC aadLen is not documented

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#857]
The table for the registration payload of AES-GMAC is:
![image](https://user-images.githubusercontent.com/3537360/81981767-c22a3800-95fe-11ea-8885-336569dbea20.png)

The example has:
```json
{
  "algorithm": "ACVP-AES-GMAC",
  "revision": "1.0",
  "direction": [
    "encrypt",
    "decrypt"
  ],
  "keyLen": [
    128
  ],
  "ivLen": [
    96,
    120
  ],
  "ivGen": "external",
  "aadLen": [
    8,
    120
  ],
  "tagLen": [
    32,
    128
  ]
}
```

The field `aadLen` is in the example and it looks like that is required.  However, from the example, it's tough to know if `aadLen` is a domain field or an array of scalars.

**Comment by celic** [comment]
Domain. Limits should be 0-4096 bits. Will double check for you.

**Comment by celic** [comment]
Max is 65536. Same bounds as used for GCM.

**Comment by AlexThurston** [comment]
Perfect.  Thanks for the info @celic
