### ISSUE TITLE
Demo: test vector not generated

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#858]
After the update I still get spurious errors for generating test vectors, such as test ID 84776 / vsID 209633.

**Comment by Kritner** [comment]
@smuellerDD The recent update didn't have any changes related to DRBG AFAIK.  The internal response from that attempt was:

```
Invalid Returned Bits Modulus supplied: 384.  Values were not a multiple of 512
```

**Comment by smuellerDD** [comment]
Am Montag, 18. Mai 2020, 16:47:49 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD The recent update didn't have any changes related to DRBG AFAIK.
>  The internal response from that attempt was:
> 
> ```
> Invalid Returned Bits Modulus supplied: 384.  Values were not a multiple of
> 512 ```

I am slightly suprised yet - I have now implemented the exact limits defined 
in the SPEC. But I think it is related to issue #808 then.

Closing this issue.

Ciao
Stephan
