### ISSUE TITLE
failure to get verdict

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#859]
**environment**
Prod

**testSessionId**
1320

**vsId**
15637

When fetching the verdict, I get

```
{
  "acvVersion" : "1.0",
  "error" : "Internal Server Error. Please contact administrator for assistance."
}
```

**Comment by Kritner** [comment]
Hey @smuellerDD I'm not seeing your results submitted for that particular vs, could this be the situation with the large endpoint that you were seemingly only hitting on demo?

**Comment by smuellerDD** [comment]
Am Dienstag, 19. Mai 2020, 18:55:33 CEST schrieb Russ Hammett:

Hi Russ,

> Hey @smuellerDD I'm not seeing your results submitted for that particular
> vs, could this be the situation with the large endpoint that you were
> seemingly only hitting on demo?

That might be the case - it is a GCM response > 4MB.

But the interesting thing is that as part of my entire testing effort, I have 
several of those large files and the others were accepted.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Issue seems fixed with other fixes
