### ISSUE TITLE
Update symmetric spec to use AFT instead of KAT

### ISSUE THREAD

**Issue by atvassilev** [usnistgov/ACVP#86]
Per agreement, the symmetric spec shall use AFT, not KAT.

**Comment by celic** [comment]
Is this relevant to any other specs? Or was KAT only used in the symmetric spec?

**Comment by atvassilev** [comment]
So far I have reviewed only the specifications that are likely to be included in v0.3. It is possible other specs have used KAT and they too need to be updated.

**Comment by atvassilev** [comment]
Fixed with PR#89.
