### ISSUE TITLE
/acvp/v1/algorithms : use of different key word

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#862]
With the new frontend, the endpoint /acvp/v1/algorithms uses `algorithmList` instead of `algorithms`.

**Comment by smuellerDD** [comment]
One followup: I see that the entire structure of the response is different. Is this intended? If yes, I guess we should update the SPEC.

**Comment by Kritner** [comment]
The endpoint was updated to return the appropriate "algorithms" rather than "algorithmList".  Regarding the structure of the endpoint though, we'll have to discuss internally first considering the previous iteration returned a URL pointing to an endpoint that we are currently not supporting.

**Comment by smuellerDD** [comment]
Am Dienstag, 26. Mai 2020, 13:38:31 CEST schrieb Russ Hammett:

Hi Russ,

> The endpoint was updated to return the appropriate "algorithms" rather than
> "algorithmList".

Confirmed, working

> Regarding the structure of the endpoint though, we'll
> have to discuss internally first considering the previous iteration
> returned a URL pointing to an endpoint that we are currently not
> supporting.

Take your time on this. This issue should not be kept open for this algo 
details.

But I am referring to the "name" : "AES-CBC", (old) vs "algorithm" : "AES-
CBC", (new).

Ciao
Stephan

**Comment by Kritner** [comment]
ah gotcha, sorry missed that.  I'll get that corrected for the next push to demo which should be within the next few hours

**Comment by Kritner** [comment]
This change has been pushed out to demo

**Comment by smuellerDD** [comment]
Am Mittwoch, 27. Mai 2020, 01:12:41 CEST schrieb Russ Hammett:

Hi Russ,

> This change has been pushed out to demo

Confirmed, working


Ciao
Stephan
