### ISSUE TITLE
Error response for new web frontend

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#863]
It was reported that the error response for the new frontend was changed. Thus I tried it.

One of the most common issues is that we uploaded a test response but somehow failed to obtain the verdict (e.g. network outage, it took too long, etc).

As the client did not get any message from the server that the response was successfully received, any subsequent retry must try to POST the response again. The old ACVP server frontend returned an error that it already received the data and we should simply request the verdict.

The new frontend however returns:

```
{
  "error":"Invalid JSON provided",
  "context":[
    "Vector set not in Processed status"
  ]
}
```

This error does not seem to show whether the message was received. Moreover, there is no machine-readable status.

Thus, may I request that somehow a status code is returned allowing the client to know that there is a permanent failure or whether the upload was rejected since it was already fully uploaded.

Thanks.

**Comment by Kritner** [comment]
A few questions/clarifications:

* You did not receive a response from the POST to `/acvp/v1/testSessions/{tsId}/vectorSets/{vsId}/results` initially? how did this present?
* What is your expectation for a return message? I was intending to add the vector sets "current status" as an additional response within the context body, but is there anything else?

**Comment by smuellerDD** [comment]
Am Samstag, 23. Mai 2020, 22:54:09 CEST schrieb Russ Hammett:

Hi Russ,

> A few questions/clarifications:
> 
> * You did not receive a response from the POST to
> `/acvp/v1/testSessions/{tsId}/vectorSets/{vsId}/results` initially?

Actually not - for the inducing of the error I terminated the request before 
retrieving the response. This issue is the most common "error condition" we 
see: interrupting the "retry" wait times and trying to resume it afterwards.

> how did
> this present?

I simply terminated the network link during the retry requests. Thus, we have 
the support to resume such interruption from the state known to the client.

> * What is your expectation for a return message? I was
> intending to add the vector sets "current status" as an additional response
> within the context body, but is there anything else?

In general, there should be an error response message format defined in the 
SPEC. That format MAY include a human-readable string. But it MUST include a 
response that is machine-parsable. For example, you can use the error message 
format mentioned at the beginning of this thread, but add a keyword 
"errorCode". That format should be used for all types of error conditions.

For the machine-parsable part, I think using an ASCII word for the error code 
is totally fine as long as it is well defined.

Note, a RESTAPI is, well, an API. Thus we should treat it as such  with input 
parameters, output parameters and error return codes. Thus, for each endpoint, 
the SPEC should define the list of error conditions that may be returned with 
the aforementioned error message type to allow the client to understand what 
the server has a problem with.

Coming back to our specific issue for posing responses: I think having an 
errorCode of, say, ACVP_ERR_RESPONSE_RECEIVED_VERDICT_PENDING should be 
returned. This indicates to the client that the server fully received the 
response and that it may proceed to polling for the verdict.


Ciao
Stephan

**Comment by smuellerDD** [comment]
On second thoughts, instead of an ASCII string for the error code, an integer number that is well-defined like for HTTP would be equally acceptable.

**Comment by AlexThurston** [comment]
:+1: for this for sure.

A proper HTTP response code should always be returned.  If desired putting a custom ACVP specific error code within the payload is also pretty useful.

It would end up that you'd get a 400 (Bad Request) as the HTTP status code and then perhaps a payload which contains:
```json
{
   err_code: 12345,
   msg: You done messed up, son!
}
```

The error code: 12345 gives me the flavour of the ACVP specific error and the msg gives me actual context.

Ultimately this makes it the easier to handle errors programatically.

**Comment by smuellerDD** [comment]
Am Montag, 25. Mai 2020, 14:17:35 CEST schrieb Alex Thurston:

Hi Alex,

> :+1: for this for sure.
> 
> A proper HTTP response code should always be returned.

I think it is always the case that an HTTP error is returned.

> If desired putting a
> custom ACVP specific error code within the payload is also pretty useful.

This is the key, the HTTP error codes do not map to ACVP error/response state 
information. Thus, there needs to be an additional layer.
> 
> It would end up that you'd get a 400 (Bad Request) as the HTTP status code
> and then perhaps a payload which contains: ```json
> {
>    err_code: 12345,
>    msg: You done messed up, son!

Right - see the first entry for the current return information that you get 
after HTTP 400 (or a similar applicable HTTP error code). That JSON message 
should just be extended with an errorCode (either nummeric or ASCII where I 
would prefer numeric, but since all else is intended to be human-readable, I 
am also fine with ASCII error codes) to return any specific state.

> }
> ```
> 
> The error code: 12345 gives me the flavour of the ACVP specific error and
> the msg gives me actual context.
> 
> Ultimately this makes it the easier to handle errors programatically.

Ack.

Ciao
Stephan

**Comment by celic** [comment]
We did a lot of updates to ensure proper HTTP status codes are returned. If you think one is incorrect, let us know. But machine readable errors are something we can look at and see how an implementation would look for the server.

**Comment by smuellerDD** [comment]
Am Dienstag, 26. Mai 2020, 17:20:48 CEST schrieb Chris Celi:

Hi Chris,

> We did a lot of updates to ensure proper HTTP status codes are returned. If
> you think one is incorrect, let us know. But machine readable errors are
> something we can look at and see how an implementation would look for the
> server.

I am not talking about HTTP error codes, I am referring to ACVP status / error 
codes.

Currently it gives a nice descriptive return information when, say, I already 
uploaded a test response, but that is not machine parsable.

Ciao
Stephan

**Comment by celic** [comment]
I understand. Both are important.

**Comment by smuellerDD** [comment]
Am Dienstag, 26. Mai 2020, 17:45:29 CEST schrieb Chris Celi:

Hi Chris,

> I understand. Both are important.

100% agreement - and I am definitely not saying any word about the HTTP error 
code.

Ciao
Stephan

**Comment by awolf-bc** [comment]
I would also like to see a _numerical_ return code in the _JSON data_. Error handling on the client side would be made much more resilient to code changes on the server side.

**Comment by dmchodnicki** [comment]
[https://github.com/usnistgov/ACVP/issues/927](url)

**Comment by dmchodnicki** [comment]
#927

**Comment by dmchodnicki** [comment]
**Test result dispositions: "error" not mentioned in the spec** #927

**Comment by dmchodnicki** [comment]
#1064

**Comment by dmchodnicki** [comment]
This item has been incorporated into a new Error Code Enhancement ticket and is therefore being Closed.  Please refer to #1070  for future updates.
