### ISSUE TITLE
DRBG Registration Issues with hmacDRBG mode

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#864]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
The pertinent algorithm registration pieces (algorithm tested, capabilities, etc) in json format
[{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"hashDRBG","revision":"1.0","prereqVals":[{"algorithm":"SHA","valValue":"same"}],"predResistanceEnabled":[true],"reseedImplemented":true,"capabilities":[{"mode":"SHA-1","derFuncEnabled":false,"entropyInputLen":[{"max":256,"min":128,"step":64}],"nonceLen":[{"max":128,"min":96,"step":32}],"persoStringLen":[{"max":256,"min":0,"step":128}],"additionalInputLen":[{"max":256,"min":0,"step":128}],"returnedBitsLen":160},{"mode":"SHA2-224","derFuncEnabled":false,"entropyInputLen":[{"max":256,"min":192,"step":64}],"nonceLen":[{"max":160,"min":128,"step":32}],"persoStringLen":[{"max":256,"min":0,"step":128}],"additionalInputLen":[{"max":256,"min":0,"step":128}],"returnedBitsLen":224},{"mode":"SHA2-256","derFuncEnabled":false,"entropyInputLen":[{"max":320,"min":256,"step":64}],"nonceLen":[{"max":160,"min":128,"step":32}],"persoStringLen":[{"max":256,"min":0,"step":128}],"additionalInputLen":[{"max":256,"min":0,"step":128}],"returnedBitsLen":256},{"mode":"SHA2-384","derFuncEnabled":false,"entropyInputLen":[{"max":320,"min":256,"step":64}],"nonceLen":[{"max":160,"min":128,"step":32}],"persoStringLen":[{"max":256,"min":0,"step":128}],"additionalInputLen":[{"max":256,"min":0,"step":128}],"returnedBitsLen":384},{"mode":"SHA2-512","derFuncEnabled":false,"entropyInputLen":[{"max":320,"min":256,"step":64}],"nonceLen":[{"max":160,"min":128,"step":32}],"persoStringLen":[{"max":256,"min":0,"step":128}],"additionalInputLen":[{"max":256,"min":0,"step":128}],"returnedBitsLen":512}]},{"algorithm":"hmacDRBG","revision":"1.0","prereqVals":[{"algorithm":"SHA","valValue":"same"},{"algorithm":"HMAC","valValue":"same"}],"predResistanceEnabled":[true],"reseedImplemented":true,"capabilities":[{"mode":"SHA-1","derFuncEnabled":true,"entropyInputLen":[{"max":256,"min":160,"step":32}],"nonceLen":[64],"persoStringLen":[{"max":256,"min":0,"step":128}],"additionalInputLen":[{"max":256,"min":0,"step":128}],"returnedBitsLen":160},{"mode":"SHA2-224","derFuncEnabled":true,"entropyInputLen":[{"max":256,"min":192,"step":64}],"nonceLen":[96],"persoStringLen":[{"max":192,"min":0,"step":64}],"additionalInputLen":[192],"returnedBitsLen":224},{"mode":"SHA2-256","derFuncEnabled":true,"entropyInputLen":[{"max":512,"min":256,"step":64}],"nonceLen":[128],"persoStringLen":[{"max":256,"min":0,"step":128}],"additionalInputLen":[{"max":256,"min":0,"step":128}],"returnedBitsLen":256},{"mode":"SHA2-384","derFuncEnabled":true,"entropyInputLen":[{"max":512,"min":384,"step":64}],"nonceLen":[128],"persoStringLen":[{"max":256,"min":0,"step":128}],"additionalInputLen":[{"max":256,"min":0,"step":128}],"returnedBitsLen":384},{"mode":"SHA2-512","derFuncEnabled":true,"entropyInputLen":[{"max":1024,"min":512,"step":64}],"nonceLen":[128],"persoStringLen":[{"max":256,"min":0,"step":128}],"additionalInputLen":[{"max":256,"min":0,"step":128}],"returnedBitsLen":512}]},{"algorithm":"ctrDRBG","revision":"1.0","prereqVals":[{"algorithm":"AES","valValue":"same"}],"predResistanceEnabled":[true],"reseedImplemented":true,"capabilities":[{"mode":"AES-128","derFuncEnabled":true,"entropyInputLen":[{"max":256,"min":128,"step":128}],"nonceLen":[128],"persoStringLen":[{"max":256,"min":0,"step":256}],"additionalInputLen":[{"max":256,"min":0,"step":256}],"returnedBitsLen":256},{"mode":"AES-192","derFuncEnabled":true,"entropyInputLen":[{"max":512,"min":256,"step":128}],"nonceLen":[128],"persoStringLen":[{"max":256,"min":0,"step":256}],"additionalInputLen":[{"max":256,"min":0,"step":256}],"returnedBitsLen":256},{"mode":"AES-256","derFuncEnabled":true,"entropyInputLen":[{"max":512,"min":256,"step":128}],"nonceLen":[128],"persoStringLen":[{"max":256,"min":0,"step":256}],"additionalInputLen":[{"max":256,"min":0,"step":256}],"returnedBitsLen":256}]}]}]

**Endpoint in which the error is experienced**
 https://demo.acvts.nist.gov:443/acvp/v1/testSessions

**Expected behavior**
Accepted registration

**Additional context**
Server response:
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Invalid JSON provided",
    "context": [
      "hashDRBG-1.0: Invalid Entropy Modulus supplied: Invalid Domain Segment supplied.  Domain Segment {Min: 128, Max: 256, Increment 1} contained values (1) that were not a multiple of 8.  Entropy Modulus contained values that were not a multiple of 8;Invalid Nonce Modulus supplied: Invalid Domain Segment supplied.  Domain Segment {Min: 96, Max: 128, Increment 1} contained values (1) that were not a multiple of 8.  Nonce Modulus contained values that were not a multiple of 8;Invalid Personalization String Modulus supplied: Invalid Domain Segment supplied.  Domain Segment {Min: 0, Max: 256, Increment 1} contained values (1) that were not a multiple of 8.  Personalization String Modulus contained values that were not a multiple of 8;Invalid Additional Input Modulus supplied: Invalid Domain Segment supplied.  Domain Segment {Min: 0, Max: 256, Increment 1} contained values (1) that were not a multiple of 8.  Additional Input Modulus contained values that were not a multiple of 8",
      "hmacDRBG-1.0: Invalid Algorithm/Mode provided.",
      "ctrDRBG-1.0: Invalid Entropy Modulus supplied: Invalid Domain Segment supplied.  Domain Segment {Min: 128, Max: 256, Increment 1} contained values (1) that were not a multiple of 8.  Entropy Modulus contained values that were not a multiple of 8;Invalid Personalization String Modulus supplied: Invalid Domain Segment supplied.  Domain Segment {Min: 0, Max: 256, Increment 1} contained values (1) that were not a multiple of 8.  Personalization String Modulus contained values that were not a multiple of 8;Invalid Additional Input Modulus supplied: Invalid Domain Segment supplied.  Domain Segment {Min: 0, Max: 256, Increment 1} contained values (1) that were not a multiple of 8.  Additional Input Modulus contained values that were not a multiple of 8"
    ]
  }

**Comment by smuellerDD** [comment]
Am Montag, 25. Mai 2020, 16:11:51 CEST schrieb Barry Fussell:

Hi Barry,

for what its worth - I am able to get test vectors for (ctr)DRBG. I did not 
check the others though.

But note that there is a peculiar set of limits for the DRBG requests mandated 
by the SPEC which used to be not enforced but lately is more and more 
enforced.

Besides, consider issue #808 that should be hopefully fixed eventually.

Ciao
Stephan

**Comment by bfussell** [comment]
Hmmm, hadn't heard about the DRBG changing enforcement, I'll check into that.
I'm getting far enough for #808, but thanks for passing that along.

**Comment by smuellerDD** [comment]
Am Montag, 25. Mai 2020, 17:14:21 CEST schrieb Barry Fussell:

Hi Barry,

> Hmmm, hadn't heard about the DRBG changing enforcement, I'll check into
> that. I'm getting far enough for #808, but thanks for passing that along.

I recognized that since I had a DRBG registration without a nonce (but the 
entropy length was sufficient) that worked in the past, but not any more. 
There was also another item where suddenly my DRBG registration failed.

This was the reason to implement https://github.com/smuellerDD/acvpproxy/blob/
master/lib/request_cipher_drbg.c#L47

Ciao
Stephan

**Comment by bfussell** [comment]
Turns out the main issue is that DRBG domains stopped using "step" and now use "increment" like all other algorithms. Only issue remaining is the mode error on hmacDRBG. Anyone aware of a change in the representation of SHA flavors ? I'm using SHA-1, SHA2-224, SHA2-256, etc. for mode.

BTW, the mode in the spec for hmacDRBG is  "mode": "AES-256" which is apparently a cut/paste error.

**Comment by Kritner** [comment]
The step size is an issue with the spec. Regarding the hmac "invalid algo/mode combination" that seems to be because the derFuncEnabled = true is not a valid property to include for drbgs except ctr.

This could obviously be clearer from our error message.

**Comment by bfussell** [comment]
Will give that a try, thanks !

**Comment by bfussell** [comment]
That worked, thanks for the pointers.
