### ISSUE TITLE
Server response: Failed to read the request form. Form key length limit 2048 exceeded.

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#865]
**environment**
Demo

**testSessionId**
86047

**vsId**
215767

**Algorithm registration**
Happens on most algorithms, but this example is CMAC
[{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"CMAC-AES","revision":"1.0","prereqVals":[{"algorithm":"AES","valValue":"same"}],"capabilities":[{"direction":["gen","ver"],"msgLen":[{"min":0,"max":65536,"increment":8}],"macLen":[128],"keyLen":[128]}]}]}]

**Endpoint in which the error is experienced**
POSTing vsID 215767 results

**Expected behavior**
vectorSet results

**Additional context**
Response from server was:
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "|ea23753d-4b32a0696452591a.",
  "errors": {
    "": [
      "Failed to read the request form. Form key length limit 2048 exceeded."
    ]
  }
}

**Comment by Kritner** [comment]
thanks @bfussell taking a look now

**Comment by celic** [comment]
Do you have the results you tried to send available? Either post here, or if they are too large, email me and I will pass them around internally.

**Comment by celic** [comment]
From what we are seeing this is an intermittent issue with the framework we are using. Retrying the POST should work. We didn't process the vectors on our end, so no need to PUT or anything.

**Comment by bfussell** [comment]
I'm trying to pull new results data, but I'm seeing different results based on our releases. One release seems to work 100%, then other rarely works. However, the POST data between the two is identical.
I'll dig into further on our end and provide a new vectorSet with the POST data when it fails.

**Comment by celic** [comment]
Thanks. We did testing with libacvp on our end before opening the server back up to everyone, so hopefully these don't occur on every run.

**Comment by bfussell** [comment]
I ran a kas_ecc test this time and generated a request file and response file(emailed) using a known working release of ours. The response file has the testSession and vectorSet values in it. It failed when I POSTed the results just like it did previously. Retrying the POST did not work.

In addition I processed the request file using the open source github version and both response files are identical.  So the response data is correct.  I'll keep digging, but if you see anything on your end that is different about how we present the responses let me know.



Thanks.

**Comment by Kritner** [comment]
Thanks for the update Barry, we'll continue to look at well.  

@jarnold01 have you seen anything like this in your running of libacvp against demo?  If Barry is getting consistent results of failures for specific registrations, would be worth trying that same registration with your running version.

**Comment by jarnold01** [comment]
No @Kritner I haven't as yet. My running of the clients thus far has mostly been focused on validating that TLS and cert auth is working but this is certainly something that I can look to do, sure.

**Comment by bfussell** [comment]
Our released code was missing Content-Type:application/json, but only on POSTs.
I assume something changed on the server side that started checking for that ?

Anyway, now we know what error is triggered when that is missing.  Closing the case.

Thanks.

**Comment by Kritner** [comment]
> Our released code was missing Content-Type:application/json, but only on POSTs.
I assume something changed on the server side that started checking for that ?

The entire stack has been switched out, so that's possible; though any json parsing issues that make it past the "front door" generally present with a less generic return message.

Here's an example of what I mean:

![image](https://user-images.githubusercontent.com/8814983/82958600-b554ff00-9f83-11ea-87dd-81c2d3ca9a9e.png)

![image](https://user-images.githubusercontent.com/8814983/82958763-2bf1fc80-9f84-11ea-80de-26e2f48efa9f.png)


It seems like your particular issue was getting rejected prior to our handling even taking over.

> Anyway, now we know what error is triggered when that is missing. Closing the case.

Awesome!
