### ISSUE TITLE
Incorrect HTTP Status Code

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#866]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
```json
{
    "engineId": [
        "80000dce0300d01f010ce9",
        "80000dce0300d01f010ce9"
    ],
    "passwordLength": [
        {
            "min": 64,
            "max": 232
        }
    ],
    "algorithm": "kdf-components",
    "mode": "snmp",
    "revision": "1.0"
}
```

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions POST

**Expected behaviour**
I would have expected given this is a user error of the body being provided by the client, that this would result in a HTTP status code of 400 rather than 500.  The contextual message returned is clear that this is a client error (ie. "kdf-components-snmp-1.0: Engine IDs must be unique") but the HTTP status code would suggest that it is a server side error.

**Comment by Kritner** [comment]
This change has been pushed out to both demo and prod.
