### ISSUE TITLE
DEMO: Can no longer list requests

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#868]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/requests?limit=20&offset=0

**Expected behaviour**
Previously, and as documented in the [API documentation](https://htmlpreview.github.io/?https://github.com/usnistgov/ACVP/blob/master/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.11.7.1), I was able to list my requests using this route.  However, now, I seem to get:
```json
{
    "acvVersion": "1.0"
  },
  {
    "error": "Internal service error. Contact service provider."
  }
]
```

**Comment by Kritner** [comment]
This change has been pushed out to demo.  Let us know if there are any issues

**Comment by AlexThurston** [comment]
This still appears to be happening on demo.  Was this accidentally closed perhaps?

**Comment by Kritner** [comment]
You're still experiencing this @AlexThurston ? I'm getting successful pulls from the `/requests` endpoint on demo:

Base:
![image](https://user-images.githubusercontent.com/8814983/83205781-7fe41900-a11d-11ea-8a9a-155e61eda090.png)

**Comment by AlexThurston** [comment]
Yup.  It looks like I am:
`GET https://demo.acvts.nist.gov/acvp/v1/requests`

Response:
```json
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Internal service error. Contact service provider."
  }
]
```

**Comment by AlexThurston** [comment]
I made an attempt at Thu 28 May 2020 20:05:06 EDT

Just in case that helps you narrow down what I'm maybe doing incorrectly in your internal logs.

**Comment by AlexThurston** [comment]
And I confirmed that if I point at prod, the call succeeds.

**Comment by Kritner** [comment]
OK I'll take a look at this in the morning, thanks

**Comment by tobyp** [comment]
The same error occurs for me on demo for the `acvp/v1/login` endpoint, both yesterday and today (at Fri 29 May 2020 06:47:56 EDT).

**Comment by Kritner** [comment]
@tobyp that looks to be a separate issue.  It seems you're trying to login with an old JWT, as communicated through email and #861, JWTs created prior to the release of the new web public code will no longer be valid.

**Comment by Kritner** [comment]
@AlexThurston can you give it another shot?

**Comment by AlexThurston** [comment]
Huzzah!  Success!  Thanks @Kritner it looks as though I can now list the requests.
