### ISSUE TITLE
New endpoint: /login/refresh

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#869]
This is an RFC: I would like to propose to increase the validity time of a JWT from 30 minutes to 1 day.

All my publications of meta data for getting a cert covers multiple OEs, implementations or modules. For example, for the Linux kernel crypto API it takes some 50 logins for each step during the publication (SW dependency, proc dependency, OE, vendor, module, certificate). In the worst case I need to wait 50 * 30 sec = 25 minutes per publication process.

The NIST team usually responds quite fast to approve the requests. But when I can perform the next round of publication, the JWTs are expired and I have again to wait 25 minutes due to the TOTP step size.

I think reducing the step size of the TOTP is not good, but increasing the validity time may spare the re-logins and a ton of waiting time.

What do you think?

**Comment by celic** [comment]
I'm not opposed to this. We would definitely be looking at something <24hrs, but maybe something more in line with a "normal work session", whether that be 8 hours or some other amount. I need to find out a bit more on how we arrived at the original value of 30 minutes, and see what others think about this.

**Comment by Kritner** [comment]
Agreed, not opposed to it.  

> All my publications of meta data for getting a cert covers multiple OEs, implementations or modules. For example, for the Linux kernel crypto API it takes some 50 logins for each step during the publication (SW dependency, proc dependency, OE, vendor, module, certificate). In the worst case I need to wait 50 * 30 sec = 25 minutes per publication process.

@smuellerDD can you elaborate on the above? I get that if the JWTs are expired that it would take multiple login "sessions" in order to get them all renewed, but I'm not following the scenario described in the quote above.

**Comment by celic** [comment]
I wonder if this could be solved by allowing multiple tokens to be updated at once. As long as each one is individually valid, I don't see why that couldn't happen.

**Comment by smuellerDD** [comment]
@celic that might be an equally good solution.

@Kritner, please have a look at the table with the awarded certificates. There you see a plethora of certificates from us whose names all have some short strings in parenthesis. These strings refer to different cipher implementations that are tested with the respective certificate.

Staying with the Linux kernel crypto API example (almost all other Linux-based modules have the same issue, as well as the Apple certificates), the following list denominates the set of test sessions for an x86 and S390 system. So, if you happen to validate both systems, the entire list is applicable. If you have more systems to test, respectively more tests will need to be performed (e.g. for the SUSE certificates, we validated x86, S390 and ARM).

Jason has an installation of our ACVP Proxy at hist disposal covering OpenSSL. Just check with him the following command ```acvp-proxy -m OpenSSL -f -l``` which lists all cipher definitions for all different cipher implementations that will be validated.

Now, each line in that list refers to an individual test session that will be created for one round.

```
Vendor Name |        OE | Proc |                                    Module Name | Version | vsIDs
atsec corp. | Fedora 29 |   i7 |            Linux Kernel crypto API (AESNI_ASM) |     5.3 |     8
atsec corp. | Fedora 29 |   i7 | Linux Kernel crypto API (RFC4106IIV_AESNI_ASM) |     5.3 |     5
atsec corp. | Fedora 29 |   i7 | Linux Kernel crypto API (RFC4106EIV_AESNI_ASM) |     5.3 |     5
atsec corp. | Fedora 29 |   i7 |              Linux Kernel crypto API (AESNI_C) |     5.3 |    11
atsec corp. | Fedora 29 |   i7 |   Linux Kernel crypto API (RFC4106IIV_AESNI_C) |     5.3 |     5
atsec corp. | Fedora 29 |   i7 |   Linux Kernel crypto API (RFC4106EIV_AESNI_C) |     5.3 |     5
atsec corp. | Fedora 29 |   i7 |           Linux Kernel crypto API (KW_AESNI_C) |     5.3 |     1
atsec corp. | Fedora 29 |   i7 |          Linux Kernel crypto API (CFB_AESNI_C) |     5.3 |     1
atsec corp. | Fedora 29 |   i7 |          Linux Kernel crypto API (OFB_AESNI_C) |     5.3 |     1
atsec corp. | Fedora 29 |   i7 |          Linux Kernel crypto API (CTS_AESNI_C) |     5.3 |     1
atsec corp. | Fedora 29 |   i7 |             Linux Kernel crypto API (X86ASM_C) |     5.3 |    15
atsec corp. | Fedora 29 |   i7 |  Linux Kernel crypto API (RFC4106IIV_X86ASM_C) |     5.3 |     5
atsec corp. | Fedora 29 |   i7 |  Linux Kernel crypto API (RFC4106EIV_X86ASM_C) |     5.3 |     5
atsec corp. | Fedora 29 |   i7 |          Linux Kernel crypto API (KW_X86ASM_C) |     5.3 |     1
atsec corp. | Fedora 29 |   i7 |         Linux Kernel crypto API (CFB_X86ASM_C) |     5.3 |     2
atsec corp. | Fedora 29 |   i7 |         Linux Kernel crypto API (OFB_X86ASM_C) |     5.3 |     2
atsec corp. | Fedora 29 |   i7 |         Linux Kernel crypto API (CTS_X86ASM_C) |     5.3 |     1
atsec corp. | Fedora 29 |   i7 |           Linux Kernel crypto API (X86ASM_ASM) |     5.3 |     5
atsec corp. | Fedora 29 |   i7 |                Linux Kernel crypto API (SSSE3) |     5.3 |    14
atsec corp. | Fedora 29 |   i7 |                  Linux Kernel crypto API (AVX) |     5.3 |    14
atsec corp. | Fedora 29 |   i7 |                 Linux Kernel crypto API (AVX2) |     5.3 |    14
atsec corp. | Fedora 29 |   i7 |                 Linux Kernel crypto API (DH_C) |     5.3 |    16
atsec corp. | Fedora 29 |   i7 |               Linux Kernel crypto API (ECDH_C) |     5.3 |    17
atsec corp. | Fedora 29 |   i7 |                  Linux Kernel crypto API (C_C) |     5.3 |    27
atsec corp. | Fedora 29 |   i7 |               Linux Kernel crypto API (KW_C_C) |     5.3 |     1
atsec corp. | Fedora 29 |   i7 |             Linux Kernel crypto API (SHA3_C_C) |     5.3 |     8
atsec corp. | Fedora 29 |   i7 |              Linux Kernel crypto API (CFB_C_C) |     5.3 |     2
atsec corp. | Fedora 29 |   i7 |              Linux Kernel crypto API (OFB_C_C) |     5.3 |     2
atsec corp. | Fedora 29 |   i7 |              Linux Kernel crypto API (CTS_C_C) |     5.3 |     1
atsec corp. | Fedora 29 |   i7 |       Linux Kernel crypto API (RFC4106IIV_C_C) |     5.3 |     5
atsec corp. | Fedora 29 |   i7 |       Linux Kernel crypto API (RFC4106EIV_C_C) |     5.3 |     5
atsec corp. | Fedora 29 |   i7 |                Linux Kernel crypto API (CTI_C) |     5.3 |    11
atsec corp. | Fedora 29 |   i7 |             Linux Kernel crypto API (KW_CTI_C) |     5.3 |     1
atsec corp. | Fedora 29 |   i7 |     Linux Kernel crypto API (RFC4106IIV_CTI_C) |     5.3 |     5
atsec corp. | Fedora 29 |   i7 |     Linux Kernel crypto API (RFC4106EIV_CTI_C) |     5.3 |     5
atsec corp. | Fedora 29 |   i7 |            Linux Kernel crypto API (CFB_CTI_C) |     5.3 |     1
atsec corp. | Fedora 29 |   i7 |            Linux Kernel crypto API (OFB_CTI_C) |     5.3 |     1
atsec corp. | Fedora 29 |   i7 |            Linux Kernel crypto API (CTS_CTI_C) |     5.3 |     1
atsec corp. | Fedora 29 |  z13 |                 Linux Kernel crypto API (DH_C) |     5.3 |    16
atsec corp. | Fedora 29 |  z13 |               Linux Kernel crypto API (ECDH_C) |     5.3 |    17
atsec corp. | Fedora 29 |  z13 |                  Linux Kernel crypto API (C_C) |     5.3 |    27
atsec corp. | Fedora 29 |  z13 |               Linux Kernel crypto API (KW_C_C) |     5.3 |     1
atsec corp. | Fedora 29 |  z13 |             Linux Kernel crypto API (SHA3_C_C) |     5.3 |     8
atsec corp. | Fedora 29 |  z13 |              Linux Kernel crypto API (CFB_C_C) |     5.3 |     2
atsec corp. | Fedora 29 |  z13 |              Linux Kernel crypto API (OFB_C_C) |     5.3 |     2
atsec corp. | Fedora 29 |  z13 |              Linux Kernel crypto API (CTS_C_C) |     5.3 |     1
atsec corp. | Fedora 29 |  z13 |       Linux Kernel crypto API (RFC4106IIV_C_C) |     5.3 |     5
atsec corp. | Fedora 29 |  z13 |       Linux Kernel crypto API (RFC4106EIV_C_C) |     5.3 |     5
atsec corp. | Fedora 29 |  z13 |                Linux Kernel crypto API (CTI_C) |     5.3 |    11
atsec corp. | Fedora 29 |  z13 |             Linux Kernel crypto API (KW_CTI_C) |     5.3 |     1
atsec corp. | Fedora 29 |  z13 |     Linux Kernel crypto API (RFC4106IIV_CTI_C) |     5.3 |     5
atsec corp. | Fedora 29 |  z13 |     Linux Kernel crypto API (RFC4106EIV_CTI_C) |     5.3 |     5
atsec corp. | Fedora 29 |  z13 |            Linux Kernel crypto API (CFB_CTI_C) |     5.3 |     1
atsec corp. | Fedora 29 |  z13 |            Linux Kernel crypto API (OFB_CTI_C) |     5.3 |     1
atsec corp. | Fedora 29 |  z13 |            Linux Kernel crypto API (CTS_CTI_C) |     5.3 |     1
atsec corp. | Fedora 29 |  z13 |            Linux Kernel crypto API (CPACF_ASM) |     5.3 |    13
atsec corp. | Fedora 29 |  z13 | Linux Kernel crypto API (RFC4106IIV_CPACF_ASM) |     5.3 |     5
atsec corp. | Fedora 29 |  z13 | Linux Kernel crypto API (RFC4106EIV_CPACF_ASM) |     5.3 |     5
atsec corp. | Fedora 29 |  z13 |              Linux Kernel crypto API (CPACF_C) |     5.3 |    27
atsec corp. | Fedora 29 |  z13 |   Linux Kernel crypto API (RFC4106IIV_CPACF_C) |     5.3 |     5
atsec corp. | Fedora 29 |  z13 |   Linux Kernel crypto API (RFC4106EIV_CPACF_C) |     5.3 |     5
atsec corp. | Fedora 29 |  z13 |           Linux Kernel crypto API (KW_CPACF_C) |     5.3 |     1
atsec corp. | Fedora 29 |  z13 |          Linux Kernel crypto API (CFB_CPACF_C) |     5.3 |     2
atsec corp. | Fedora 29 |  z13 |          Linux Kernel crypto API (OFB_CPACF_C) |     5.3 |     2
atsec corp. | Fedora 29 |  z13 |          Linux Kernel crypto API (CTS_CPACF_C) |     5.3 |     1
atsec corp. | Fedora 29 |  z13 |           Linux Kernel crypto API (CPACF_SHA3) |     5.3 |     8
```

**Comment by Kritner** [comment]
@smuellerDD thanks for the list but that makes me think that perhaps there is some room for improvement in your application flow, if possible:

* Upon the `/login` endpoint you are given a JWT `jwt0` that can be used for interacting with both the metadata and test session endpoints
* Issuing a post to `/testSessions` will initiate a test session `ts1` that returns a new JWT `jwt1` that has claims for that particular test session
* `jwt1` is required for interacting with `ts1`, but `jwt0` ***has not*** been invalidated.
* continuing to use `jwt0` against the `/testSessions` endpoint would allow you to continue creating additional test sessions for the life of `jwt0`, you would just need to keep track of `jwt[n]` belongs to `ts[n]`

Does that make sense? Maybe I'm misunderstanding your situation here, but it sounds like you're currently doing separate logins for each individual line item in the list posted from the comment in https://github.com/usnistgov/ACVP/issues/869#issuecomment-637271913; where it could all be accomplished in a single login.

**Comment by smuellerDD** [comment]
Am Dienstag, 2. Juni 2020, 13:25:53 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD thanks for the list but that makes me think that perhaps there
> is some room for improvement in your application flow, if possible:
> 
> * Upon the `/login` endpoint you are given a JWT `jwt0` that can be used for
> interacting with both the metadata and test session endpoints * Issuing a
> post to `/testSessions` will initiate a test session `ts1` that returns a
> new JWT `jwt1` that has claims for that particular test session * `jwt1` is
> required for interacting with `ts1`, but `jwt0` ***has not*** been
> invalidated. * continuing to use `jwt0` against the `/testSessions`
> endpoint would allow you to continue creating additional test sessions for
> the life of `jwt0`, you would just need to keep track of `jwt[n]` belongs
> to `ts[n]`

Oh, I never knew that one!

Indeed, if the system works that way, I definitely do not need to re-login 
time and again.
> 
> Does that make sense? Maybe I'm misunderstanding your situation here, but it
> sounds like you're currently doing separate logins for each individual line
> item in the list posted from the comment in
> https://github.com/usnistgov/ACVP/issues/869#issuecomment-637271913; where
> it could all be accomplished in a single login.

You hit the nail - created a separate log-on for each test session.

But then, can you please elaborate on the following issue. My app works fully 
asynchronously, i.e. there is no timewise relationship between a registering 
of a test session and an upload of test responses. For that, I store the 
obtained JWT for each test session together with the test session. Now, when 
posting the test responses I validate whether the JWT for the test session 
expired and log in posting the existing JWT.

In this case, I would be forced to perform individual log-ins for each test 
session, would I not?

Ciao
Stephan

**Comment by Kritner** [comment]
> In this case, I would be forced to perform individual log-ins for each test
session, would I not?

yeah currently that is the case unfortunately, but @celic's suggestion in https://github.com/usnistgov/ACVP/issues/869#issuecomment-637096126 would probably allow alleviation of that particular issue.

**Comment by smuellerDD** [comment]
Confirmed: initial login tokens can be reused for multiple test sessions. But note, as the gathering of test data takes some time, this reuse of initial login tokens does not speed up things too much.

The key would be the prevention of testsession re-logins during publication since there is no wait time on server responses.

**Comment by smuellerDD** [comment]
Confirmed, working.

It is truly awesome how fast the operation now is it is like night and day! Thanks for adding it and avoiding more twiddling of thumbs.

I keep the issue open to track it for a documentation update.
