### ISSUE TITLE
Empty phoneNumbers array absent sometimes and not others

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#871]
On demo GET of an existing vendor, 11189, used to show phoneNumbers even though empty.
After the maintenance it does not.  However GET on an existing persons, 14969, still shows the empty phoneNumbers array.  

On the production server empty phoneNumbers arrays are always shown in both cases.

Was this an intended change as part of the maintenance ?
And if so will production work identically after its maintenance tomorrow ?

Thanks,

Barry

**Comment by Kritner** [comment]
I'm assuming your preference is for the property to be absent if an empty array is encountered? I can knock this out probably in the morning after hearing your (and any others) response.  This would likely need to be handled on a case by case basis unfortunately, but I can definitely handle this situation.

**Comment by Kritner** [comment]
A release has been pushed to demo that removes the empty `"phoneNumbers": []`

**Comment by bfussell** [comment]
For vendors or contacts or both ? Just looking for consistency across all of the metadata.

**Comment by Kritner** [comment]
Sorry the phoneNumbers array was removed when empty from both vendors and persons.  The intention is consistency, if we discover any other inconsistencies or they're pointed out we'll fix them when they come up.

**Comment by bfussell** [comment]
Still seeing it when I query contacts on demo. Does the change roll out after another maintenance release ?

   "totalCount": 2,
    "incomplete": false,
    "links": {
      "firstPage": "/acvp/v1/vendors/11189/contacts?offset=0\u0026limit=0",
      "lastPage": "/acvp/v1/vendors/11189/contacts?offset=0\u0026limit=20"
    },
    "data": [
      {
        "url": "/acvp/v1/persons/14970",
        "fullName": "Clint Winebrenner",
        "vendorUrl": "/acvp/v1/vendors/0",
        "emails": [
          "cwinebre@cisco.com",
          "certteam@cisco.com"
        ],
        "phoneNumbers": [
          {
            "number": "919-392-6520",
            "type": "voice"
          }
        ]
      },
      {
        "url": "/acvp/v1/persons/15283",
        "fullName": "Bubba Team",
        "vendorUrl": "/acvp/v1/vendors/0",
        "emails": [
          "certteam@bubba.com"
        ],
        "phoneNumbers": []
      }
    ]
  }

**Comment by Kritner** [comment]
Hey @bfussell didn't realize this was also impacting the `/contacts` endpoint, will put in a fix momentarily

**Comment by Kritner** [comment]
@bfussell `/contacts` endpoint should be corrected now
