### ISSUE TITLE
Missing website value in newly approved vendors

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#873]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
/acvp/v1/vendors/11561 GET

**Expected behavior**
An approved vendor containing the "website" json field specified in the submitted metadata

**Additional context**
Submitted vendors on demo appear to be stripped of the "website" value when they are approved. Is this intentional?

Thanks,
Andrew

**Comment by Kritner** [comment]
Not intentional, next release will have a fix, thanks!

**Comment by Kritner** [comment]
This change has been pushed out to demo (note that vendors that were created or updated (with website changes) between the initial deploy to demo starting in #861 and now, will not have their websites populated.  Vendor create/updates going forward should work properly however.

Let us know if there are any issues.

**Comment by bfussell** [comment]
@Kritner Is this issue similar to #871 ?

**Comment by Kritner** [comment]
Sorry bfussell, I haven't had a chance to look into that one yet. I'll try to get that one next
