### ISSUE TITLE
Demo: For a period of time, a 500 is returned if you try to download vector sets after a test session is created

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#874]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
Just for an example.
```json
{
    "algorithm": "RSA",
    "mode": "keyGen",
    "revision": "1.0",
    "infoGeneratedByServer": false,
    "pubExpMode": "random",
    "keyFormat": "standard",
    "capabilities": [
        {
            "randPQ": "B.3.2",
            "properties": [
                {
                    "modulo": 2048,
                    "hashAlg": [
                        "SHA-1"
                    ]
                }
            ]
        }
    ]
}
```

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions/86562/vectorSets/219337 GET

**Expected behaviour**
I would have expected that after the resources is returned as created that the response would not be a 500 when I perform actions on that resource.  After a certain period of time (appreciating that the vector sets have not been generated yet) I do get the response that they are not ready yet and that I should wait 30 seconds and retry.  But I would have expected to get that response immediately rather than have a period of time where 500s are returned.

**Comment by Kritner** [comment]
@AlexThurston I'm having trouble reproducing this for the `https://demo.acvts.nist.gov/acvp/v1/testSessions/{tsId}/vectorSets/{vsId}` endpoint, though I was able to get this behavior from the `https://demo.acvts.nist.gov/acvp/v1/testSessions/{tsId}` endpoint.  Can you confirm that it was on attempting to get a prompt file for a vector set, not checking test session status?

**Comment by AlexThurston** [comment]
@Kritner Right you are, it's when I am trying the bottom two endpoints.  Not that actual route which returns the vector set.

**Comment by Kritner** [comment]
This fix has been pushed to demo.  Let me know if there are any issues, thanks!
