### ISSUE TITLE
Incorrect HTTP status code when a bug request is made

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#879]
**environment**
Demo (but likely also production since it's the same code at this point)

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
Doesn't really matter.  In my case I was pushing up a set of capabilities for SHA-1 with a message length that did not contain digest itself

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions POST

**Expected behaviour**
This might have been mentioned in other contexts/issues but I wanted to raise a more generic issue if it is indeed true of all situations when an error is made in a registration of algorithm capabilities.  When an error is found in the body of the POST, the http status code that is returned is 500 but I would have expected a 400.  500s are normally use for a server side error that is un-expected and not obviously the fault of the client.  In this case though, the error is purely on the part of client and about the contents of the request.  An HTTP response code of 400 would be more appropriate as it would denote that this is a client error.

**Comment by Kritner** [comment]
Hey Alex, since this is close enough to #866 mind if it's closed? The plan is to return 400s for any json / payload validation errors.  Will be available in the next release.

> Doesn't really matter. In my case I was pushing up a set of capabilities for SHA-1 with a message length that did not contain digest itself

I'm assuming the server did respond with something that was more actionable than the previous stacks? (hopefully? :D)

**Comment by AlexThurston** [comment]
Totally fine with me.  I knew that I had raised something similar, but I wasn't sure it if was route specific or a more global issue with it.

The server definitely did respond with something more actionable which was wonderful.  Way easier to debug my own user error :P

**Comment by Kritner** [comment]
Awesome! 

I'll update #866 once this change has been deployed
