### ISSUE TITLE
Error 500 on Login

### ISSUE THREAD

**Issue by rt-acumen** [usnistgov/ACVP#881]
**environment**
PROD

**testSessionId**
1144

**vsId**
vectorSet ID 13073 & 13074

**Algorithm registration**
```json
 "algorithms": [
            {
                "algorithm": "ACVP-AES-XTS",
                "direction": [
                    "encrypt",
                    "decrypt"
                ],
                "keyLen": [
                    256
                ],
                "payloadLen": [
                    4160,
                    32832
                ],
                "revision": "1.0",
                "tweakMode": [
                    "hex"
                ]
            },
            {
                "algorithm": "ACVP-AES-ECB",
                "direction": [
                    "encrypt",
                    "decrypt"
                ],
                "keyLen": [
                    256
                ],
                "payloadLen": [
                    256
                ],
                "revision": "1.0"
```

**Endpoint in which the error is experienced**
https://acvts.nist.gov/acvp/v1/login

**Expected behavior**
We are having an issue accessing our test sessions. We are receiving a 500 internal service error during login. We are seeing this error with test sessions on both the prod and demo server. Specifically, I am trying access the prod test session URL: /acvp/v1/testSessions/1144

**Additional context**
Login string: 
```json
[{"acvVersion":"1.0"},{"password":"{otp}","accessToken":"{jwt}"}]
```

500 error received from server: 
```json
[{"acvVersion":"1.0"},{"error": "Internal service error. Contact service provider."}]
```

**Comment by Kritner** [comment]
Note that JWTs should be considered "secret" and should not be shared within public space.  That being said, that JWT is from prior to the deployment of the new front end code - see more information here: https://github.com/usnistgov/ACVP/issues/861

Specifically: 
> As stated in the email sent out all JWTs that were created prior to the maintenance are no longer valid, the same goes for the in progress sessions. This JWT invalidation is also the case for when the production release goes out after the changes are verified on demo. Make sure to finish up your production testing before then. The current plan for the production release as per the email that went out is 2020/05/29 starting at 10a EDT.

**Comment by rt-acumen** [comment]
Noted on the JWTs. 

Can you please advise if monthly maintenance will invalidate Prod/Demo sessions going forward? If so, this could be a large problem as most vendors/labs request vectors and apply them to the IUT offline.

**Comment by Kritner** [comment]
No this was a one time invalidation due to moving out public api to a new tech stack

**Comment by rt-acumen** [comment]
Phew okay. Thank-you for the clarification. We were aware of the ~one month of inactivity expiration. Closing.
