### ISSUE TITLE
Module type: case of word changed

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#884]
In the past, the module type used to be "Firmware" or "Software" or "Hardware". Now it is "firmware", "hardware", "software".

I noticed that on prod.

For example:

old

```
{
  "name":"Apple Secure Key Store CoreCrypto Module Firmware (c_glad)",
  "version":"10.0",
  "type":"Firmware",
  "vendorUrl":"/acvp/v1/vendors/11541",
  "addressUrl":"/acvp/v1/vendors/11541/addresses/11533",
  "contactUrls":[
    "/acvp/v1/persons/15564"
  ],
  "description":"Cryptographic library offering various cryptographic 
mechanisms to Apple frameworks in the Secure Enclave Processor environment. 
The following cipher implementation is covered: Gladman AES implementation."
}
```

new:

```
{
  "name":"Apple Secure Key Store CoreCrypto Module Firmware (c_glad)",
  "version":"10.0",
  "type":"firmware",
  "vendorUrl":"/acvp/v1/vendors/11541",
  "addressUrl":"/acvp/v1/vendors/11541/addresses/11533",
  "contactUrls":[
    "/acvp/v1/persons/15564"
  ],
  "description":"Cryptographic library offering various cryptographic 
mechanisms to Apple frameworks in the Secure Enclave Processor environment. 
The following cipher implementation is covered: Gladman AES implementation."
}
```

**Comment by Kritner** [comment]
I believe a fix for this is already on demo, and the next release to prod will take care of the issue.

**Comment by smuellerDD** [comment]
ok, then nevermind, please

**Comment by smuellerDD** [comment]
Prod was updated, was it not? I still see that issue on prod

**Comment by smuellerDD** [comment]
Note, I saw this issue on demo, too

**Comment by Kritner** [comment]
which endpoint is this @smuellerDD ? the endpoint (/modules/) I'm hitting is not exhibiting this behavior:

![image](https://user-images.githubusercontent.com/8814983/84438909-4c1cef00-ac05-11ea-9cf6-84883e12f979.png)

![image](https://user-images.githubusercontent.com/8814983/84439038-7d95ba80-ac05-11ea-8cde-7ecb5252403b.png)

**Comment by Kritner** [comment]
.... nevermind... I now see that the "Firmware" is what you were saying it *should* be.

**Comment by Kritner** [comment]
Sorry, I was misreading this issue the whole time.  Every other "casing" correction I've done over the past few weeks it seems like was to *lowercase* the first character, but this one is different. I'll put in a correction in the morning.

**Comment by dsikkema-atsec** [comment]
This was see again, where the type was Hardware, it failed to register. Once I changed to hardware it worked.

**Comment by smuellerDD** [comment]
Am Mittwoch, 1. Juli 2020, 18:00:35 CEST schrieb dsikkema-atsec:

Hi dsikkema,

> This was see again, where the type was Hardware, it failed to register. Once
> I changed to hardware it worked.

It is changed for demo, but not for prod yet.

Ciao
Stephan

**Comment by celic** [comment]
Can this be closed? Anything on demo should be on prod now.
