### ISSUE TITLE
old: addressUrl, new: addressUrls

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#885]
In the module definition, the new frontend contains "addressUrls" which used to be "addressUrl".

**Comment by smuellerDD** [comment]
Fixed in new version

**Comment by smuellerDD** [comment]
Issue is still visible on prod

**Comment by Kritner** [comment]
Sorry @smuellerDD I had missed this issue, I'll put in a correction so it matches the spec and old implementation.

**Comment by smuellerDD** [comment]
Confirmed, fixed.
