### ISSUE TITLE
Invalid cipher text

### ISSUE THREAD

**Issue by surajshardade** [usnistgov/ACVP#887]
Hi,

I have downloaded some test vectors for FF1 and after performing crypto operation I have posted it for validation. In result request, I got the result as _" result": "failed", "reason": "Cipher Text does not match"_. Is there any way to debug this or could we get more detailed validation for it?

Thanks.

**Comment by smuellerDD** [comment]
Am Donnerstag, 11. Juni 2020, 08:58:34 CEST schrieb surajshardade:

Hi surajshardade,

> Hi,
> 
> I have downloaded some test vectors for FF1 and after performing crypto
> operation I have posted it for validation. In result request, I got the
> result as _" result": "failed", "reason": "Cipher Text does not match"_. Is
> there any way to debug this or could we get more detailed validation for
> it?

Yes, you can obtain a sample for the offending result during POST or PUT by 
adding

"showExpected":true

to the test response.

> 
> Thanks.


Ciao
Stephan

**Comment by surajshardade** [comment]
Thanks, Stephan for the input.
I think when we used _"showExpected": true"_ , it will return what will be the expected cipher or plain text. Can't we get the steps/rounds expected results for the sample like NIST will provide for their samples?

**Comment by smuellerDD** [comment]
Am Donnerstag, 11. Juni 2020, 11:08:45 CEST schrieb surajshardade:

Hi surajshardade,

> Thanks, Stephan for the input.
> I think when we used _"showExpected": true"_ , it will return what will be
> the expected cipher or plain text. Can't we get the steps/rounds expected
> results for the sample like NIST will provide for their samples?

Sure, you need to set isSample:true during the initial registration and then 
download the expected data via the /expected endpoint as documented in the 
SPEC.

Ciao
Stephan

**Comment by Kritner** [comment]
Though note, we do not give the internal state of the algorithms as they run through the operations regardless of `sample` or `showExpected`.

**Comment by surajshardade** [comment]
ohk. got it.
Thanks, Stephan and Russ. :)
