### ISSUE TITLE
Multiple endpoint timeouts/dropping connection

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#888]
I try to use the /login/refresh endpoint to refresh the auth tokens of test sessions 89924 89926 89935 89931 89942 89938 89937 89933 89934 89939 89932 89928 89943 89930 89945 89944.

The connection is stalled after uploading and the connection times out - here is the CURL log

```
*   Trying 52.204.191.193:443...
* TCP_NODELAY set
* Connected to demo.acvts.nist.gov (52.204.191.193) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /home/sm/hacking/sources/cavs/acvp/acvp-keys/digitcert_bundle.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Maryland; L=Gaithersburg; O=National Institute of Standards and Technology; OU=STVM ACVP; CN=demo.acvts.nist.gov
*  start date: Jun  1 00:00:00 2020 GMT
*  expire date: Jun 20 12:00:00 2021 GMT
*  subjectAltName: host "demo.acvts.nist.gov" matched cert's "demo.acvts.nist.gov"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> POST /acvp/v1/login/refresh HTTP/1.1
Host: demo.acvts.nist.gov
User-Agent: ACVPProxy/1.4.1
Accept: */*
Content-Type: application/json
Content-Length: 7822
Expect: 100-continue

* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* old SSL session ID is stale, removing
* Empty reply from server
* Connection #0 to host demo.acvts.nist.gov left intact
ACVPProxy (10:42:12) (acvp-proxy) Warning - HTTP operation: Curl HTTP operation failed with code 52 (Server returned nothing (no headers, no data))
* Connection 0 seems to be dead!
```

I am sending (credentials are obfuscated)
```
[
  {
    "acvVersion":"1.0"
  },
  {
    "password":"00000000",
    "accessToken":[
      "token 1",
      "token 2",
...
```

**Comment by smuellerDD** [comment]
Note, individual logins with the test sessions via /login work.

**Comment by smuellerDD** [comment]
Note 2: It was working for a different set of test sessions. Though, during initial login where I used the same first-level login to register all test sessions, there were 2 test sessions that received an authentication error. I was not sure why and wanted to retest it.

**Comment by smuellerDD** [comment]
Note 3: Using individual logins now also show a stall in GET of the test vector:

```
*   Trying 52.204.191.193:443...
* TCP_NODELAY set
* Connected to demo.acvts.nist.gov (52.204.191.193) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /home/sm/hacking/sources/cavs/acvp/acvp-keys/digitcert_bundle.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Maryland; L=Gaithersburg; O=National Institute of Standards and Technology; OU=STVM ACVP; CN=demo.acvts.nist.gov
*  start date: Jun  1 00:00:00 2020 GMT
*  expire date: Jun 20 12:00:00 2021 GMT
*  subjectAltName: host "demo.acvts.nist.gov" matched cert's "demo.acvts.nist.gov"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /acvp/v1/testSessions/89943/vectorSets/234338 HTTP/1.1
Host: demo.acvts.nist.gov
User-Agent: ACVPProxy/1.4.1
Accept: */*
Authorization: Bearer foo

* old SSL session ID is stale, removing
* Empty reply from server
* Connection #0 to host demo.acvts.nist.gov left intact
ACVPProxy (10:59:03) (acvp-proxy) Warning - HTTP operation: Curl HTTP operation failed with code 52 (Server returned nothing (no headers, no data))
* Connection 0 seems to be dead!
```

**Comment by smuellerDD** [comment]
Note 4: see such stallings now also on other endpoints, e,g. /acvp/v1/testSessions/89939/results

**Comment by Kritner** [comment]
Hey @smuellerDD I see this ticket has been opened, it's still early here but I'll try to get back to you once people start waking up and can pull some logs for me.

**Comment by Kritner** [comment]
Hey @smuellerDD we tweaked a setting regarding concurrency, can you try the same sort of scenario that was giving issue earlier in the day?

**Comment by smuellerDD** [comment]
GET /acvp/v1/testSessions/89945/vectorSets/234361  times out

**Comment by smuellerDD** [comment]
note, this last GET was signle-threaded

**Comment by Kritner** [comment]
Ah that's a pretty large file, I think that's a db timeout rather than what we were dealing with earlier, I'll give another message once a fix is put in for that.

**Comment by smuellerDD** [comment]
Ok, if you like I can try others.

**Comment by Kritner** [comment]
could you try on another first? we might be dealing with multiple things here... we did get a change pushed out to demo, but looking at the logs on that particular GET you did from https://github.com/usnistgov/ACVP/issues/888#issuecomment-642655076 I'm not sure that the change would have fixed it.

**Comment by smuellerDD** [comment]
Single threaded: The /login/refresh was successful (like last time). GET /acvp/v1/testSessions/89945/vectorSets/234361 still times out. GET /acvp/v1/testSessions/89945/vectorSets/234364 times out. GET /acvp/v1/testSessions/89943/vectorSets/234338 times out.

I leave it running...

**Comment by smuellerDD** [comment]
Time out:
GET /acvp/v1/testSessions/89939/vectorSets/234260
GET /acvp/v1/testSessions/89934/vectorSets/234263
GET /acvp/v1/testSessions/89934/results
GET /acvp/v1/testSessions/89946/vectorSets/234392

**Comment by smuellerDD** [comment]
Note, for some I do get successful connections and can download data.

**Comment by Kritner** [comment]
@smuellerDD we've made a few more changes, this seems like it may be stemming around the large GCM/CCM registrations.  Can you try your large vector set gets again? we're keeping an eye on the system to try and get a better idea of where we're getting the bottleneck.

**Comment by smuellerDD** [comment]
Looks good, I got all single threaded. Note, I also got them with a decent speed of around 80 to 100 MBit /s 

Shall I retry multi-threaded?

**Comment by Kritner** [comment]
Sure go for it. 

We may at some point want to do some smaller scale tests with you, as we are seeing very different behavior between you running your client and jason running your client.

**Comment by smuellerDD** [comment]
commencing shortly - re the smaller tests: let me know what you are interested in as I think I should be able to accommodate your requests easily

**Comment by Kritner** [comment]
@shaneshaffer did you want @smuellerDD to hit us with anything in particular?

**Comment by smuellerDD** [comment]
Download of another large test round with some 250 vsIDs worked. I am going to generate test responses and throw all of them at once at the server. I will report back.

**Comment by smuellerDD** [comment]
The handling of test responses was appropriate - no more lags or similar.

I am good now. If I should create specific tests, let me know separately.
