### ISSUE TITLE
New algorithm specification - KAS-FFC-SSC SP800-56Ar3

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#891]
KAS-FFC-SSC will be introduced on demo in the coming weeks; SSC being "shared secret computation". 

This new algorithm will encompass testing of the DH/MQV primitives against the defined KAS-FFC schemes from [SP800-56Ar3](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Ar3.pdf).

The registrations will look very similar to the full KAS registrations albeit smaller. The registration will be made up of:

* Schemes to test
* Roles to test per scheme
* Domain parameter generation methods  (safe prime groups)
* an optional `hashFunctionZ` to accommodate clients with the inability to return `z` in the clear.

An example registration:

```json
{
  "algorithm": "KAS-FFC-SSC",
  "revision": "Sp800-56Ar3",
  "scheme": {
    "dhEphem": {
      "kasRole": [
        "initiator",
        "responder"
      ]
    },
    "mqv1": {
      "kasRole": [
        "initiator",
        "responder"
      ]
    }
  },
  "domainParameterGenerationMethods": [
    "FB",
    "ffdhe2048"
  ],
  "hashFunctionZ": "SHA3-512"
}
```

**Comment by smuellerDD** [comment]
testvectors obtained successfully

**Comment by smuellerDD** [comment]
Siuccessfully tested with and without hash on OpenSSL with MODP 2048, 3072, 4096, 6144, 8192

Note, the VAL tests passed  - though I am wondering that only two out of 10 tests are expected to fail.

**Comment by smuellerDD** [comment]
I have successful tests with the Linux kernel, NSS, GnuTLS and OpenSSL.
