### ISSUE TITLE
GET /testSessions/{testSessionId}/vectorSets/{vectorSetId}/expected returns 404

### ISSUE THREAD

**Issue by surajshardade** [usnistgov/ACVP#892]
**environment**
Demo

**testSessionId**
90701

**vsId**
237258

**Algorithm registration**
[
   {
      "acvVersion": "1.0"
   },
   {
      "isSample": false,
      "algorithms": [
         {
            "algorithm": "ACVP-AES-FF1",
            "revision": "1.0",
            "direction": [
               "encrypt"
            ],
            "keyingOption": [
               1
            ],
            "keyLen": [
               128
            ],
            "tweakLen": [
               {
                  "min": 0,
                  "max": 128,
                  "increment": 8
               }
            ],
            "capabilities": [
               {
                  "alphabet": "0123456789",
                  "radix": 10,
                  "minLen": 10,
                  "maxLen": 60
               }
            ]
         }
      ]
   }
]
**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443/acvp/v1/testSessions/90701/vectorSets/237258/expected GET

**Expected behavior**
json formatted Expected CT values

**Additional context**
I have downloaded test vector set, performed FF1 crypto on operation on that and submitted respose. I was able to download results but not expected value. 
_{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
  "title": "Not Found",
  "status": 404,
  "traceId": "|7be9bfb6-4d255c08444de3ed."
}_

**Comment by smuellerDD** [comment]
isSample is false, hence there is no /expected endpoint for your vsId

**Comment by surajshardade** [comment]
I got the expected result for _"isSample" = "true"_.
Thanks, Stephan.
