### ISSUE TITLE
Difference about “extra bits” and “testing candidates”

### ISSUE THREAD

**Issue by joymcg** [usnistgov/ACVP#893]
Hi,
   I have a question about ecdsa keygen, in the document , it mention about “secretGenerationMode”, it have two value “extra bits” and “testing candidates”. What’s the difference between these two mode?

**Comment by smuellerDD** [comment]
See FIPS 186-4 sections B.1.1 an B.1.2

**Comment by celic** [comment]
See @smuellerDD 's comment. In terms of the testing there is no difference. Additional groups will be provided if you select both options.
