### ISSUE TITLE
KDF IKEv2 Documentation/Examples/Expected Response Inconsistencies

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#896]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
N/A/

**Expected behaviour**
There seems to be some inconsistencies in the documentation for the responses.  The table shows:
![image](https://user-images.githubusercontent.com/3537360/84822263-66324500-afea-11ea-9836-12e81d72daac.png)
Note the **derivedKeyingMaterialDh**, **derivedKeyingMaterialChild**, **derivedKeyingMaterialChildDh**

The example shows:
![image](https://user-images.githubusercontent.com/3537360/84822466-b4474880-afea-11ea-9f07-2a5b72403281.png)
Note the ** derivedKeyingMaterialDh**, **derivedKeyingMaterialChild**, **derivedKeyingMaterialDh**

The expected responses come back as:
![image](https://user-images.githubusercontent.com/3537360/84822572-e8bb0480-afea-11ea-8ea0-b4e66d60d5a1.png)
Note the **derivedKeyingMaterial**, **derivedKeyingMaterialChild**, **derivedKeyingMaterialDh**

**Additional context**

**Comment by celic** [comment]
Thanks. I have a large sweeping change to our documentation in the works. Switching from raw XML to an ASCIIDoc format. Compilation will be done with metanorma. The documents should be a bit more descriptive in properties, and less ambiguous on when certain properties should appear. Also they will be much easier for others to edit to help us with fixes such as this.

I'll share more as this progresses, but our conversion base point has already happened from the raw XML, so I would like to keep these issues around to remind us to make these fixes in the ASCIIDoc files.
