### ISSUE TITLE
Response when failing to create a person isn't helpful

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#897]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
`https://demo.acvts.nist.gov/acvp/v1/persons` **POST**

**Expected behaviour**
When creating a new person resource, a vendor and an email are required.  However, when you try to create one without either of those pieces of information, the response that comes back is only:

```json
[
    {
        "acvVersion": "1.0"
    },
    {
        "error": "Internal service error. Contact service provider."
    }
]
```

It'd probably be more helpful if the error was more descriptive detailing what is missing and was a 400 instead of a 500.

**Comment by celic** [comment]
We added a lot of validation to Web Public to check for these. I see name and vendor being the required fields. Not email. Do you have the JSON you used to try to create this person? I'd like to see what fields were included.

**Comment by AlexThurston** [comment]
If I try to create a person with this:
```json
{
	"fullName": "Alex Thurston"
}
```

I get:
```json
[
	{
	  "acvVersion": "1.0"
	},
	{
	  "error": "Internal service error. Contact service provider."
	}
]
```

**Comment by celic** [comment]
Ah ok. Yeah this is an easy null check missing. Fixed on our end and will be packaged in the next release.

**Comment by celic** [comment]
Fixed with patch today.
