### ISSUE TITLE
Vendor field of person within the list of vendor contacts is wrong

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#898]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
`https://demo.acvts.nist.gov/acvp/v1/vendors/11379/contacts`  **GET**

**Expected behaviour**
When you list the contacts of a vendor, the object that comes back for each person has a field for `vendorUrl`, but the value is not correct.

For example:
**GET** `https://demo.acvts.nist.gov/acvp/v1/vendors/11379/contacts`
Results in:
```json
[
  {
    "acvVersion": "1.0"
  },
  {
    "totalCount": 2,
    "incomplete": false,
    "links": {
      "firstPage": "/acvp/v1/vendors/11379/contacts?offset=0&limit=0",
      "lastPage": "/acvp/v1/vendors/11379/contacts?offset=0&limit=20"
    },
    "data": [
      {
        "url": "/acvp/v1/persons/14911",
        "fullName": "James Ramage",
        "vendorUrl": "/acvp/v1/vendors/0",
        "emails": [
          "james.ramage@lightshipsec.com"
        ]
      },
      {
        "url": "/acvp/v1/persons/15320",
        "fullName": "Alex Thurston",
        "vendorUrl": "/acvp/v1/vendors/0",
        "emails": [
          "alex.thurston@lightshipsec.com"
        ]
      }
    ]
  }
]
```

Note the **vendorUrl** for each entry.

If I read myself, it looks correct:
```json
[
  {
    "acvVersion": "1.0"
  },
  {
    "url": "/acvp/v1/persons/15320",
    "fullName": "Alex Thurston",
    "vendorUrl": "/acvp/v1/vendors/11379",
    "emails": [
      "alex.thurston@lightshipsec.com"
    ]
  }
]
```

**Comment by celic** [comment]
Yeah, the `vendorUrl` is a bit redundant here as you used it as a precursor to the `contacts` endpoint, but still the information should be correct in the return result. I added it in. This will be available in the next release.

**Comment by celic** [comment]
Fixed with patch today.
