### ISSUE TITLE
Improve the OE description as part of the registration for ACVP

### ISSUE THREAD

**Issue by atvassilev** [usnistgov/ACVP#9]
A new issue from NIST Sprint 1:

Need to identify how to improve the description of the operation environment field contained within the registration step of the ACV protocol.

Some thoughts include:
- Need a unique identifier for the module/implementation;
- interoperable way to talk about OS, hardware platform, module;
- valid values list for OE.

**Comment by hbooth** [comment]
The below is focused on just the part of registration that discussed what was in the OE originally. Note that  a new top-sibling to the operationalEnvironment property has been created to describe the module, separately from the environment in which the module was being tested. We can discuss this further on the call, but just wanted to get this out there to start the discussion.

{
....
      "module": {
         "name": "Module Name",
         "version": "1.1",
         "type": "Software",
      },
      "operationalEnvironment": {
         "dependencies": [{
          "software": {
              "cpe": "cpe:2.3:o:linux:linux:3.1",
              "swid": "swid-tag"
          },
          "hardware": {
              "type": "processor",
              "name": "Intel Xeon Processor",
              "modelNumber": "LV 5148"
          }
      }]
    }
....
}

**Comment by hbooth** [comment]
From our phone discussion today:
          "hardware": {
              "type": "processor",
              "manufacturer": "Intel"
              "family": "ARK",
              "name": "Xeon",
              "series": "5100",
              "features": ["feature1", "feature2"]
          }

Additional Hardware attributes:
"family"
"architecture"
"core"
"instructionSet"
"microcode"

References for thought:
https://en.wikipedia.org/wiki/List_of_ARM_microarchitectures
https://en.wikipedia.org/wiki/Intel_Core
ISO-19770-2
NIST-IR 8060

**Comment by atvassilev** [comment]
Can this issue be closed now?

**Comment by celic** [comment]
Is there a reason this is still open?

**Comment by atvassilev** [comment]
No, I don't think so. At the time when I wrote previous comment, @hbooth's PR was still pending. Now that it is merged, this can be closed.
