### ISSUE TITLE
Branching for v0.3

### ISSUE THREAD

**Issue by atvassilev** [usnistgov/ACVP#90]
It looks to me the specs are ready to branch for v0.3. Let’s plan accordingly to rev up every spec to 0.3 prior to the branch. Once this is done and the v0.3 branch is created we need to rev the main line up to v0.4.

Please let me know what you think and which specs you are planning to touch.

**Comment by bfussell** [comment]
I'll try to up-rev all the specs and pull the new branch later today or tomorrow if that works for everyone.

**Comment by atvassilev** [comment]
Sounds great, thanks!

**Comment by bfussell** [comment]
One question, the protocol spec used the version information in the name here:

<rfc category="info" docName="draft-ietf-acvp-protocol-0.3" ipr="trust200902">

However all the sub specs used:

<rfc category="info" docName="draft-ietf-acvp-subecdsa-00" ipr="trust200902">

In addition to up-reving the examples and any comments, do we want to bump all the sub spec doc docName as well ?

**Comment by atvassilev** [comment]
I would vote for revving up everything, including examples and such. I realize this is quite a chore so would like to offer my help. If you like we could split the work in two.

**Comment by bfussell** [comment]
I got it, all done.  I'll be sending a PR in a bit.

**Comment by atvassilev** [comment]
OK, thank you - I'll be looking for it. Do you want me to merge it into the master first and then branch out into a formal v0.3?

**Comment by atvassilev** [comment]
I merged PR #91 into master and then created a separate branch v_0.3, which at this stage is the same as master.  This means we have v_0.3 for the demo and will make only changes to fix critical bugs.

**Comment by atvassilev** [comment]
Resolved with PR #91.
