### ISSUE TITLE
KAS ECC - key confirmation with curves of fieldsize greater than 384 bits causes failure message with some schemes.

### ISSUE THREAD

**Issue by dghgit** [usnistgov/ACVP#900]
**environment**
Demo

**testSessionId**
91544

**vsId**
239796

**Algorithm registration**
[{"acvVersion":"1.0"},{"isSample":false,"algorithms":[{"algorithm":"KAS-ECC","revision":"1.0","prereqVals":[{"algorithm":"DSA","valValue":"same"},{"algorithm":"DRBG","valValue":"same"},{"algorithm":"SHA","valValue":"same"},{"algorithm":"AES-CCM","valValue":"same"},{"algorithm":"CMAC","valValue":"same"},{"algorithm":"HMAC","valValue":"same"}],"function":["keyPairGen","dpGen"],"scheme":{"onePassUnified":{"kasRole":["responder","initiator"],"kdfKc":{"kdfOption":{"concatenation":"uPartyInfo||vPartyInfo"},"kcOption":{"kcRole":["recipient","provider"],"kcType":["unilateral","bilateral"],"nonceType":["randomNonce"]},"parameterSet":{"ee":{"curve":"K-571","hashAlg":["SHA2-512"],"macOption":{"HMAC-SHA2-512":{"keyLen":[256],"macLen":128}}}},"dkmNonceTypes":["randomNonce"]}}}}]}]

**Endpoint in which the error is experienced**
 https://demo.acvts.nist.gov:443/acvp/v1 GET

**Expected behavior**
Expect a results json, instead got back:

[{"acvVersion":"1.0"},{"error":"Object reference not set to an instance of an object."}]

**Additional context**
The attached transcripts (including the response  JSON (.rsp.json)) are for onePassUnified, but the same appears to also apply for onePassMqv and staticUnified. The behavior appears to start occurring as soon as B-409 or K-409 or any curve with a larger fieldsize is added. P-384 and smaller appear to work.

In case it's any further help it seems to take an inordinately long time to generate the initial test vectors. I'm wondering if the issue is about memory as much as math. While in the failing cases not a single validation vector is passed, I can do testing up to B-571/K-571 for  fullMqv, onePassDh, fullUnified, ephemeralUnified, and CDH-Component so it seems the issue is specific to the schemes rather than the underlying math library. The server also appears to be able to generate sample data, it just fails on submission.

[transcripts.zip](https://github.com/usnistgov/ACVP/files/4796222/transcripts.zip)

**Comment by Kritner** [comment]
@dghgit should have a fix for this in an upcoming release.  This is related to the `N` value on the curve and how it relates to the size of the expected ephemeral nonce.

This particular issue would seemingly be present on any curve where `(N * 2) % 8 != 0` and an ephemeral nonce is required by the scheme.

**Comment by dghgit** [comment]
Makes sense. I'll test when the new release comes out. Thanks.

**Comment by Kritner** [comment]
Sorry @dghgit I missed updating this when the release went out, should be out there and available for confirmation now.
