### ISSUE TITLE
Prod: ACVP cert awarded but not shown at website

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#908]
Test sessions 1568 and 1491 are completed and received a certificate (A494), but they do not show up on the CSRC website.

**Comment by shaneshaffer** [comment]
Looks like there was an unexpected resource contention issue that occurred during simultaneous approvals of the certify requests, resulting in some data not being generated properly.

However I don't know that you would have liked the results even if it had not had this problem. Those two test sessions had the same algorithms on them, and the certify requests referenced the same OE. If it worked as intended, the first certify would have gone as expected, then the second would have deleted the data for the OE, and replaced it with data based on the second test session. If these test sessions happened to be identical (I didn't check) then it would have been fine, but if there were differences there would be an issue.

Were the test sessions in fact identical? If so then I'll use one to redo what should have happened.

**Comment by smuellerDD** [comment]
Yes, both cover the same testing. Actually 1491 is one that came before the last transition where the JWT expired. I did not know how 1491 ever came back to life, but you can disregard it. 1568 is the same request just after the transition. So, if you could trigger the update of the web site for either one, I would be thankful.

But the interesting thing is that the same issue of two identical tests is present  for A495 through A500 and there you see two identical entries for the CPU A12X. So, I am not sure I understand your reasoning :-)

**Comment by shaneshaffer** [comment]
The missing OE has been added to A494.

On A495 to A500 it looks like what happened is that the approvals weren't running so simultaneously that they collided, but were interleaved so closely that between the first one determining that it needed to create a record for that OE and actually creating that record the second one did its check to determine if it needed to be created. So the second one didn't find the record since the first hadn't yet created it, and then created one of its own. I'll need to clean up one of the occurrences in each of those validations.

**Comment by smuellerDD** [comment]
Am Mittwoch, 24. Juni 2020, 17:11:41 CEST schrieb shaneshaffer:

Hi shaneshaffer,

> The missing OE has been added to A494.

Thanks.
> 
> On A495 to A500 it looks like what happened is that the approvals weren't
> running so simultaneously that they collided, but were interleaved so
> closely that between the first one determining that it needed to create a
> record for that OE and actually creating that record the second one did its
> check to determine if it needed to be created. So the second one didn't
> find the record since the first hadn't yet created it, and then created one
> of its own. I'll need to clean up one of the occurrences in each of those
> validations.

Sure, remove one of the two occurrences.

Ciao
Stephan

**Comment by smuellerDD** [comment]
A494 does not seem to show an entry for A12X

**Comment by shaneshaffer** [comment]
Looks like it is there to me, at the bottom. There were 18 OEs, now there are 19.

**Comment by smuellerDD** [comment]
fixed, thanks
