### ISSUE TITLE
suggestion for cSHAKE AFT testing

### ISSUE THREAD

**Issue by dghgit** [usnistgov/ACVP#912]
We've run a few rounds now and other than some issues with getting the MCT test correct, our cSHAKE implementation has been passing. It turned out recently that it still wasn't quite correct, the reason been that we'd made a mistake in the padding described in Section 2.3.3 bytepad() function of SP 800-185 where we (or rather I) had overlooked the fact that our implementation would add a full block of padding when the encoded N and S data resulted in a string that was block aligned, rather than add no padding, which is what the function really requires.

A bit of study shows that block aligned data doesn't happen that often (I should add the issue was found as a result of 3rd party review of the code, not as a result of invalid output)  and that given an N of length 0, S needs to be 265 octets for cSHAKE-256 and 329 octets for cSHAKE-128 for the problem to occur in the first instance. The condition should also be triggered if the combined length of N and S comes to those lengths as well.

I would like to suggest that where an implementation's parameters can be big enough to allow this to happen a couple of AFT vectors **should always be generated** that would trigger this condition, as this error might be easy to miss and the chance of triggering it randomly is small. The bug, if present, is a bit of "lurker". 

Apart from the questions it might raise about issues of comprehension and coding, many algorithms require padding to be added even if none would be required and while the context in which that is done is generally different to here, I think I may discovered not worrying about extra padding can be quite habit forming as well. I fear others may accidentally follow in my footsteps with the result that a "working" implementation may suddenly fail when the right circumstances arise if this condition is not explicitly checked for.

**Comment by celic** [comment]
This is great. This is exactly the sort of thing ACVP allows us to do. The test case would look exactly like an AFT, and seamlessly be included, but hopefully cause implementations to catch this error.

**Comment by Kritner** [comment]
Hey @dghgit I'll be getting around to this shortly, did you happen to have any sample test that depict the behavior from before and after your fix?

**Comment by celic** [comment]
Would you be able to provide some more detailed justification on where the 265 byte or 329 byte values came from?

**Comment by dghgit** [comment]
@celic I've checked this again, S of 129 octets for cSHAKE256 and an S of 161 for cSHAKE128 appears to reproduce the problem as well. 265 and 329 represent the second time the issue occurs. I think our earlier implementation used a different approach to calculating the delta, it seems it must have needed two blocks before the error occurred. I've updated added these values to our tests as well and confirmed introducing a padding bug causes an error.

@Kritner Here's our (revised!) Java test code:

        byte[] buf = new byte[20];

        CSHAKEDigest cshake1 = new CSHAKEDigest(256, new byte[0], new byte[129]);
        cshake1.doOutput(buf, 0, buf.length);
        isTrue("256 first block", areEqual(Hex.decode("79c201347df0003cfa837df03bc0e62baa195643"), buf));

        CSHAKEDigest cshake2 = new CSHAKEDigest(128, new byte[0], new byte[161]);
        cshake2.doOutput(buf, 0, buf.length);
        isTrue("128 first block", areEqual(Hex.decode("c48d423e9f2a37809d64155c29afad16d3e413ec"), buf));

        CSHAKEDigest cshake3 = new CSHAKEDigest(256, new byte[0], new byte[265]);
        cshake3.doOutput(buf, 0, buf.length);
        isTrue("256 second block", areEqual(Hex.decode("6e393540387004f087c4180db008acf6825190cf"), buf));

        CSHAKEDigest cshake4 = new CSHAKEDigest(128, new byte[0], new byte[329]);
        cshake4.doOutput(buf, 0, buf.length);
        isTrue("128 second block", areEqual(Hex.decode("309bd7c285fcf8b839c9686b2cc00bd578947bee"), buf));

So they both have a zero length function string (N), the customization string (S) for cSHAKE256 is a 129 and 265 octets strings of zero octets and cSHAKE128 has strings of length 161 and 329 octets with all octets zero. Both functions are asked for 20 bytes of output which are compared to the expected values (the arguments to Hex.decode()). Input message length is 0 in all cases.

**Comment by celic** [comment]
I'm going to try to spend some time with this and see what I can learn. If this applies to cSHAKE, it may apply to the base SHAKE in addition to other cSHAKE variants.

**Comment by dghgit** [comment]
I don't think it will apply to SHAKE, the padding step I've referred to here is in cSHAKE (although it would be worth checking something similar couldn't happen in SHAKE, off the top of my head I'll admit I'm not 100% sure). I think you're correct that everything under cSHAKE, such as KMAC et al could also use a test like this though, I think the magic numbers will change slightly due to the function string, but I think the padding condition (where things are a multiple of the blocksize) will still apply.

**Comment by dghgit** [comment]
Some more Java test vectors for byte padding with KMAC keys:

        byte[] data = Hex.decode("01880204187B3E43EDA8D51EC181D37DDE5B17ECCDD8BE84C268DC6C9500700857");
        byte[] out = new byte[32];

        KMAC k128 = new KMAC(128, new byte[0]);
        k128.init(new KeyParameter(new byte[163]));
        k128.update(data, 0, data.length);
        k128.doOutput(out, 0, out.length);

        isTrue("128 failed", Arrays.areEqual(out, Hex.decode("6e6ab56468c7445f81c679f89f45c90a95a9c01afbaab5f7065b7e2e96f7d2bb")));

        KMAC k256 = new KMAC(256, new byte[0]);
        k256.init(new KeyParameter(new byte[131]));
        k256.update(data, 0, data.length);
        k256.doOutput(out, 0, out.length);

        isTrue("256 failed", Arrays.areEqual(out, Hex.decode("f6302d4f854b4872e811b37993b6bfe027258089b6a9fbb26a755b1ebfc0d830")));

These are specific to KMAC initialization, but represent a similar problem where the key is just long enough mean the initialization data is a multiple of the block size.

**Comment by Kritner** [comment]
This change is now on prod in release https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.13
