### ISSUE TITLE
X9.63, odd field sizes still incorrect.

### ISSUE THREAD

**Issue by dghgit** [usnistgov/ACVP#914]
For a fieldsize of 409, an input of:

"z":"DA88B869D2647FBC447F996B0899E7AE1EDEBB677148B6E4231C7169F4A28858DA6309396C551BCCDF2EF9F40CDD94A517A32C"
"sharedInfo":""

for the test group:

"hashAlg":"SHA2-512",
"sharedInfoLength":0,
"keyDataLength":128,
"fieldSize":409,
"testType":"AFT",

produces:

"keyData":"68040D8805BF59C557AD592F3A98EFAF"

in the .smp file, whereas the correct answer should be (I think):

"77197ad34a37613236c5100cd9468da4"

One thing which may help, the z value is short so gets padded to become:

"00DA88B869D2647FBC447F996B0899E7AE1EDEBB677148B6E4231C7169F4A28858DA6309396C551BCCDF2EF9F40CDD94A517A32C"

This is consistent with what works for vectors where the field size is octet aligned. I've confirmed they are padded correctly, but there is something very strange going on still with the odd ones.

**Comment by celic** [comment]
Yes. I think previously I mentioned that odd-length values should be taken at exactly the field size bit length, so truncation would occur of the left-most bits. This is not the case. The specification is ambiguous in what should occur, but CAVS would take the full padded value into the internal hashing of the KDF, so I have updated ACVP to do the same. If there is still an issue, let me know and I can take a look. I verified our implementation with CAVS on odd-length field sizes which was accidentally neglected during the initial implementation a few years ago.

**Comment by dghgit** [comment]
Okay, so the issue I have is for:

{"tgId":14,"hashAlg":"SHA2-512","sharedInfoLength":0,"keyDataLength":128,"fieldSize":571,"testType":"AFT","tests":[{"tcId":261,"z":"0350091ADD45E696B812C21618B2D64A9D07A1811044101559B358D732224CF6C08D96742411F8A36446F33B8443C20656F36755933195F2C52D2CD5E84BDCAB4D4659DBB82D3D04","sharedInfo":""},

I get:

{"tcId":261,
"keyData":"4ece87b43419f3fa2e55a3f8a0b8e131"}

while the sample response is:

{"tcId":261,"keyData":"163EF8C0D0C4CD89A6C6996CF83EED09"},

What exactly gets passed into the KDF as the Z value in this case?

Also can you tell me what you get for:

[SHA-512]
     [shared secret length = 571]
     [SharedInfo length = 1024]
     [key data length = 512]

     COUNT = 0
     Z = 03331b883f01f41568a41b9314964e6fc8f11a076cc0ef79fd1cf55e3ade5fd85b1dc88c146d0350c7017d928baad06656ec4e2457e80d91ae6d7bc9b5d5583b80f5f5756b51d85c
     SharedInfo = d4964cdb1b47549e3be0d495eff88469d6e187e3f5e1f53530ebcec125bb4df405d31057952362b16003caffde63c2563cfdcc40e905a57bc38fcec6ae5bf2f677532e8ece00cfb1e4b400cc8b8ae5dfeea0e8b21f21f9c8daa15a233b0466e75431608b311780f3472ce81b58c8f8d88711dd43cbdba43a6e337c5e5fdfb438
     key_data = dcf73e3170e837422026eed28e2acc1cd5dfc5ef98142153006dafc3c78c6097d3e7934dabd1701129fe469f76f59ad43957182b1bfc464541384017fb7cd660

The above was correct for the CAVS system and I have rerun our implementation against a number of CAVS test files and it is still generating the same results.

**Comment by celic** [comment]
For the CAVS case, our implementation matches and gets the correct result.

For the other case, our implementation matches the result you get. I'll double check the changes, but can you provide me the vsId for this?

**Comment by celic** [comment]
I see the issue. This will be fixed ASAP.

**Comment by celic** [comment]
For some context, only when we were generating `z` values, we were still strictly following the field size. All other occurrences were handling it properly so it would "appear" correct in all other situations.

**Comment by celic** [comment]
The fix is going to Demo now. Please test when you can.

**Comment by dghgit** [comment]
I've now tried every field size, all seems to be working on both sides. Closing this as fully resolved. Thanks.
