### ISSUE TITLE
URLs such as 'nextPage' 'prevPage' are not URL encoded

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#915]
Hello!

Currently, we can send a query to the vendor list containing a Name and URL for the vendor we are looking for, and it works as expected -

`/acvp/v1/vendors?name[0]=eq:Cisco%20Systems%2C%20Inc.&website[0]=eq:www.cisco.com`

However, trying to use the provided nextPage entry, which is formatted as so:

`/acvp/v1/vendors?offset=20\u0026limit=20\u0026name[0]=eq:Cisco Systems, Inc.\u0026website[0]=eq:www.cisco.com"`

results in this error being returned:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request</h2>
<hr><p>HTTP Error 400. The request is badly formed.</p>
</BODY></HTML>

```

If i use contains:Cisco instead of eq:Cisco%20Systems etc in my original query, nextPage works as anticipated.

 1.) It would be preferred for provided query endpoints to be pre-formatted as needed for queries if possible
2.) It would be preferred to not receive HTML blocks as error messages for ACVP

Thanks for your time,
Andrew

**Comment by celic** [comment]
HTML errors are ones that occur before our processing even happens. These are being caught by IIS and returned. We can look and see if we can come up with a solution, but as I said, these errors are returned before anything has touched our code.

**Comment by celic** [comment]
The invalid or poorly constructed URL in the `nextPage` property is the real issue here, not what type of error was returned. You should be able to trust that if we provide you a URL, it will work (unless of course the element we link to is deleted). I'm going to rename the issue so we don't lose track of the goal here.

**Comment by abkarcher** [comment]
Thank you @celic for the information! I suppose the HTML errors are not an issue if the URLs are encoded correctly - just always trying to return the most coherent messages to the user possible! :) I look forward to whenever the URLs might be addressed.

Andrew

**Comment by Kritner** [comment]
The fix for this is on both demo and prod; let me know if there are any issues.
