### ISSUE TITLE
KAS Sp800-56Ar3 Production Availability

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#916]
**environment**
Demo and Production

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
KAS ECC/FCC
Revision: `Sp800-56Ar3`

**Endpoint in which the error is experienced**
https://[demo.]acvts.nist.gov/acvp/v1/algorithms  GET

Is `Sp800-56Ar3` available on production?  Listing the algorithms seems to suggest that it is not.  I might be mis-remembering, but I was pretty sure I could get vectors if I tried on production though.

**Comment by celic** [comment]
It's on demo, not on prod. 

With the CAVP dropping support for CAVS (mostly, some limited exceptions exist) on July 1st, any algorithm at that time that was supported on Prod ACVTS would no longer allow vendor affirmation after a certain date later this year. We chose to hold on to 56Ar3 algorithms until after that date to allow a bit more of a window for vendors and labs to prepare for testing as we felt a June release with only a couple months before vendor affirmation was discontinued for it was a bit unfair. 

I expect this to go out on the upcoming Prod release this week (with the fixes hitting Demo last week). That's not 100% certain yet though.

**Comment by AlexThurston** [comment]
Thanks @celic as always for the info.
