### ISSUE TITLE
RSA KeyGen B.3.3 tblC2 always get wrong result

### ISSUE THREAD

**Issue by NorthHill-16** [usnistgov/ACVP#917]
Hi, I have requested a RSA keygen module, with 2048 bits, B.3.3, tblC2, random exponent. I could generate the result, however, server always say my results are failed, something like,

{
        "tcId": 48,
        "result": "failed",
        "reason": "P does not match; Q does not match; N does not match; D does not match"
      },

Firstly, I choose e=010001(65537), but if I use same e as server, it also fails. Secondly, my d has no problem, since I input same n, e, p, q from server, I get same d. I am following FIPs 186-3 here except I don't have parameter i, which I think it is not related, https://csrc.nist.gov/csrc/media/publications/fips/186/3/archive/2009-06-25/documents/fips_186-3.pdf

What is the possible problem, or is this server's bug?

Key pair is generated by openssl function, RSA_generate_key_ex(rsa, 2048, bne, NULL), where bne is 010001, input no problem.

**Comment by smuellerDD** [comment]
Am Mittwoch, 8. Juli 2020, 03:55:11 CEST schrieb GX-Joe:

Hi GX,

> Hi, I have requested a RSA keygen module, with 2048 bits, B.3.3, tblC2,
> random exponent. I could generate the result, however, server always say my
> results are failed, something like,
> 
> {
>         "tcId": 48,
>         "result": "failed",
>         "reason": "P does not match; Q does not match; N does not match; D
> does not match" },
> 
> Firstly, I choose e=010001(65537), but if I use same e as server, it also
> fails. Secondly, my d has no problem, since I input same n, e, p, q from
> server, I get same d. Hence, it seems something wrong. I am following FIPs
> 186-3 here,
> https://csrc.nist.gov/csrc/media/publications/fips/186/3/archive/2009-06-25
> /documents/fips_186-3.pdf
> 
> What is the possible problem, or is this server's bug?

I think it is quite unlikely that there is a server bug, because I use RSA 
keygen with random e and B.3.3 for OpenSSL successfully for large numbers of 
tests.

But in the past, we had issues with padding.

If you need a reference code, look here: https://github.com/smuellerDD/
acvpparser/blob/master/backends/backend_openssl.c#L2909

Ciao
Stephan

**Comment by celic** [comment]
This is for the KATs? You should use the `e` provided by the server in these cases. If `p` or `q` (or both) don't match, then both `n` and `d` will also not match even if you compute them correctly. 

The KATs for RSA here come directly from CAVS and have been around for many years before ACVP. If you have a particular case I could help debug some.

**Comment by NorthHill-16** [comment]
Hi, @smuellerDD 

I even use the same code as you provide, ebuf->len set to 6, but still get error. The request capability is 

[{"acvVersion":"1.0"},{"isSample":true,"algorithms":[{"algorithm":"RSA","revision":"1.0","mode":"keyGen",
"prereqVals":[{"algorithm":"SHA","valValue":"same"}],"infoGeneratedByServer":true,"pubExpMode":"random","keyFormat":"standard",
"capabilities":[{"randPQ":"B.3.3","properties":[{"modulo":2048, "primeTest": ["tblC2"]}]}]}]}]

One of the "wrong" output is,
{
             "tcId": 48,
             "e": "270ED7EE7C23",
             "n": "D30688FF4928BE39B1076787F45D587D0754BA7D0B6A53F3E092DCDED7FDF9DE0BD972FF2D56EE54BC8300BE4116061B30E98A9206347CA7BB5721BBCEB918E7C186A951BD0A629697A9D57FB2608ABDF51459E906BC35D9E65ADB6F2C88F1A5699D6F9C036ACB771E4C41306D88C4B44BE236E7E39BF4E2C9F26759DAABFF143CDBD898124DB7576F3E026B090650853AA3FE96297A467C80FF35B3ED72AFB2ACFFCAC128E9CD018741CE1B2C4BFC750F0936F0BD028F5AF4B6AD7F5DE8D5F819DB2B0C7FE8BDE6F477E4807DD082C20D3A76CB71DE192B93B6513B69129F2B37999A8502CA943EDC4A5E61A3BBB71C9CB93C0D5397B2CE10578AEFFC0440BF",
             "p": "EF7E7DF161248A3B6C5DE1CCF14B3FDFBA144BD3B9953BBAB7585F4DCFB092F2FECA016FFA70B936AC44CA96DBC59DE4CECB20E08FE4B40CBD8FE4AB20D3A4DBA23C481E575636DD1C984A22FD8064A521B0286C23F73449F9BD86BF7D7EDF87545C15468135CC79D8A1E14DFA5CB3B9DE4FECB0805CAAB8F29B964F17CDBA6F",
             "q": "E191C22DE74C543966C5752A49A7D5959A278F60AE25FAE7E41B4425D9825F092A06B37EF59632BBF9CBBA0FB899C021B2B3D9D6A6929902F128A790A7198B4DB43AB3775F0E796F07EF6BD275CB3EFA190D179031665999B6B08730735E81EB315F439B2B2542E7EFE33CB5D02CFF4077E3DD9486B2499649503CFAACF446B1",
             "d": "37B9FD0FDC93004FB680CD24C46735ACA194129A52CBA0617E337F39494403BB82A90308EEA89CB336DFE2D34AF11838F05608023393E7EC55C8E8219542F82FAB4C15046AD967B7F5E2EDC8FBC3E7C6D633A52314458D8020BBAA63382162DF85924CD77B6C14EBA4A3928699C510B43948D7DB39A7FC829B438BA33410C79B295088194AB9A6B89BA58F8CD882546FC285B6FA1297DC5AFF2605170DE2B941A9B18496EE0208230E2391D29801E7E749053434B9CDE84490A7311284DFDD12D01E52D5164EA8F01FF790DDD693D4CE079A65C096D1868C0D03B0B3BDC6EB3DA4F875A7434C9CCFF40E403579FA45CA0CB64729F9A9C3D972E70E2E1846A0EB"
           }

And I get the same error,  "reason": "P does not match; Q does not match; N does not match; D does not match"

Hi, @celic 

  I have no problem with KAT, only GDT with B.3.3, tblC2 and random.

**Comment by celic** [comment]
For GDT, the client is expected to generate a key that meets the listed properties. For B.3.3, the requirements are a bit loose. The validation follows the B.3.3 Key Generation method plugging in the provided `p` and `q` values for the "random" values. If the provided `p` and `q` are valid, then there should be no modifications as they will pass their initial primality test. 

So what is happening here is they are likely not passing their primality test. Can I have the vsId for the tests you ran so I can take a deeper look?

**Comment by NorthHill-16** [comment]
Hi, @celic 

1.  The implementation is done by openssl, and key is been checked. Plus, the idea is very similar to the sample code that @smuellerDD provided.

2. I have run many tests, but I would like to choose testSession 94680 as an example, it uses 65537 as my e value.

3.  I upload the sample answer that is provided by server, and I get the "failed" again.

**Comment by celic** [comment]
I think I see the issue. When `isSample` is set to true, the GDT behind the scenes generates a key using B.3.3. This is used for internal testing so that we have a key to submit to the server. We expect the client to provide a full RSA key for the test with no input from the server. We take the p and q values and run the key generation method and if the p and q are valid, then they should not be changed during key generation. We should be comparing the generated key with the client's key. Instead we are comparing the internally generated key with the client's key. 

This is only an issue when `isSample` is set to true though, so you may proceed with your testing by setting that flag to false while we work on a fix.

**Comment by NorthHill-16** [comment]
Hi, @celic ;

  I set sample be false, and still get same result.

**Comment by celic** [comment]
Do you have a vsid for one with isSample set to false? I don't see any using a quick search.

**Comment by NorthHill-16** [comment]
Hi, @celic 

TestSession 94680 , vector set 256742, is the one with sample be false,

**Comment by NorthHill-16** [comment]
Hi, @celic 

oh, sorry, it is sample true. Wait a sec.

**Comment by NorthHill-16** [comment]
Hi, @celic 

  Thank you very much! The problem is solved when sample set to false.

**Comment by celic** [comment]
Sorry, not going to close this. There is still an issue here. When isSample is set to true, we are performing the wrong validation check on GDT for B.3.3. 

Sometimes you don't want to generate a full vector set of keys to check if something is working so we'd prefer if isSample behaved correctly here ;) 

I'm going to use this issue to track the fix.

**Comment by NorthHill-16** [comment]
Hi, @celic 

OK, thanks. At least my test session 94685 is all successfully passed.

**Comment by celic** [comment]
Great, sorry for the trouble. This will be fixed soon. Thanks for the report. 

Essentially we will be marking the GDTs as `"deferred": true` as that helps determine the validation logic. When sample was set to true, the deferred flag was not set for GDTs.

**Comment by NorthHill-16** [comment]
OK, get it.
