### ISSUE TITLE
RSA KeyGen B.3.5 Results return 'error' Status

### ISSUE THREAD

**Issue by awolf-bc** [usnistgov/ACVP#918]
**environment**
DEMO

**testSessionId**
95085

**vsId**
260536

**Algorithm registration**
```
{
 "algorithms": [
   {
     "algorithm": "RSA",
     "mode": "keyGen",
     "revision": "1.0",
     "pubExpMode": "fixed",
     "fixedPubExp": "010001",
     "infoGeneratedByServer": false,
     "keyFormat": "standard",
     "capabilities": [
       {  
         "randPQ": "B.3.5",
         "properties": [
           {
             "modulo": 2048,
             "primeTest": [
               "tblC3"
             ],
             "hashAlg": [
               "SHA2-256"
             ]
           }
         ]
       }
     ]
   }
 ]
}
```

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443/acvp/v1/testSessions/95085/results

**Expected behavior**
I expect a 'failed' or 'passed' status of the submission.

**Additional context**
This is the returned result:
```
[
  {
    "acvVersion": "1.0"
  },
  {
    "passed": false,
    "results": [
      {
        "vectorSetUrl": "/acvp/v1/testSessions/95085/vectorSets/260536",
        "status": "error"
      }
    ]
  }
]
```
I cannot figure out the problem with the JSON data, since no readable log text is generated.

The created response JSON uses the **same** formatting when the creation of the 'input' data is deferred to the IUT or generated by the server. The response for the *same* algorithm, but with ```"infoGeneratedByServer": true``` (sess=95083, vs=260529), was successfully accepted (and settled on the 'passed' status).

**Comment by celic** [comment]
The client is not providing the `bitlens` array to the server. 

I'll work on getting this error to be a bit more clear...

We definitely focused on providing responses to errors when the generator fails. When the validator fails, we relied on the existing means of providing context. This error though caused the validator to stop running so the normal means of providing an error didn't work.

**Comment by awolf-bc** [comment]
Thanks! So it does have a problem with the ```bitlens``` array. It is definitely included. 

This is first test case data object in the response:
```
{
"tcId": 1,
"seed": "F0FAD41C010B1E52ADA41959888A25516DC3DE83C53CB7311144E28B",
"bitlens": [430,278,214,265],
"xP": "E764EE5747092853829939BD8C76FB1.....",
"xQ": "C646A10A632257C164B8CDFEC10B02.....",
"e": "010001",
"n": "B337E7808A3FC7ACA9C21B8BAAF153E.....",
"p": "E764EE5747092853829939BD8C76FB1A.....",
"q": "C646A10A632257C164B8CDFEC10B02D.....",
"d": "2BCD942594A4B616FB7ED7E0B12D3EC....."
}
```
As I said before, the same format is used when the ```"infoGeneratedByServer": true``` registration is used. Somehow, ```bitlens``` does not create a problem for that test vector. Is it not parsed for the other case and now it is?

**Comment by celic** [comment]
When `"infoGeneratedByServer": true` the server doesn't need to read in the `bitlens`, it only cares about the key values. When the client generates the content for the test cases the server needs to read in more properties to attempt to re-generate the same key the client generated. I'll do some debugging and figure out what is causing the problem. The responses look like they have all the content they need and are formatted properly.

**Comment by celic** [comment]
Server error here. Bitlens were not being passed in as they should only for B.3.5 KeyGen. With the fix, I ran your JSON and it passes FYI.

**Comment by awolf-bc** [comment]
Thanks for looking into this! Nice to hear that the format the IUT generates is valid.

**Comment by awolf-bc** [comment]
The latest code update for DEMO has fixed this.
Thanks!
