### ISSUE TITLE
Getting the OE ID of a Validation 

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#919]
**environment**
N/A

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
N/A

This is more of a workflow question than it is an issue with anything in particular but might require some thought on the API.  It is related to the manner by which existing validation are edited/altered.  

Given I have a validation that has been already put through and I want to add to the algorithms.  How would one go about getting the OE ID that was used.  This would presumably be required if I wanted to create a new test session with all the existing algorithms and the new one.  I would then have to submit the test session (along with the module ID, and OE) for the certificate to be updated.

This is related to the discussing about the validation API route, the recent (ish) API change, and the fact that this information is no longer easily pulled from ACVP.  

It's also somewhat related to this question https://github.com/usnistgov/ACVP/issues/720

I did try to do a search fo the OE by name but was returned 8 different records all of which were named the same (so that's not gonna work).

**Comment by celic** [comment]
The re are a good amount of duplicate records each tied to different things that makes searches like this a bit difficult. Searches are much easier when data is canonical. 

For finding the OE ID that was used with a validation, I suppose we don't have a way to directly access that via the API. I do see the need you are highlighting though.

**Comment by AlexThurston** [comment]
This used to be achievable with the way the validation route worked before, but after the _great API redesign of 2020_ (:P) this started returning less information.

**Comment by jlramage** [comment]
As a lab, we're planning to re-use as many records as possible and not to spawn new ones. To assist with this effort, we need to find objects, such as the OE, related to existing validations so we can promote reuse. Fetching validation details was a great way to obtain all objects required.

**Comment by smuellerDD** [comment]
Just to give some ideas how I am handling it: my tool stores the different IDs locally as you can see in [1]. These IDs are processed as follows during a publication round:

1. The tool fetches the data associated with the ID from the server

2. The server data is compared with the local data you also see in [1].

3. If all match, the tool proceeds and uses the record. Otherwise the tool issues an update request.

If there are no IDs in the local files, the tool does:

1. Perform a search query with using the name of the respective meta data

2. Iterate over the returned data to find a match

3a. If there is a match, it uses this ID, stores it locally and proceeds with the next meta data part

3b. If there is no match, the tool requests the creation of a new meta data entry.

[1] https://github.com/smuellerDD/acvpproxy/blob/master/module_definitions/openssl_fedora29_1.1.1/module_info/openssl_1.1.0_64bit.json#L9

or

https://github.com/smuellerDD/acvpproxy/blob/master/module_definitions/openssl_fedora29_1.1.1/oe/fedora29_x86.json#L13

**Comment by celic** [comment]
I think the original idea was for local storage on the client side. This doesn't really work (or is much harder) when multiple members of a lab, for example, need to share some IDs for validations.

**Comment by AlexThurston** [comment]
Wouldn't it also be the case if there were multiple labs involved with a vendor?

**Comment by Kritner** [comment]
The most recent deploy to demo now includes the oeUrls as a property at the GET "/validations/{validationId}" endpoint, and the specification has been updated in #976.  Was there anything outstanding on this issue otherwise?

**Comment by AlexThurston** [comment]
That looks great.  It's definitely beneficial to be able to get that information.

Somewhat related to the same idea, but currently it's only the `GET` route that appears to be supported and the parameters to it is the internal validation ID.  However, this information is not what is presented when looking at the ACVP certificates from the CAVP list.

Take [this](https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/details?validation=31757) certificate for example.

The URL contains the ID 31757 which happens to the the validation ID, but this doesn't seem to be the case always.  The actual validation number is *A35*.  It'd be nice if I could get the validation record based on the A35 or at least search that field using the query structure like other resources provide.

**Comment by celic** [comment]
There are two systems at play here. We manage ACVP which has it's own databases and servers. When a finalized certificate is requested, the relevant information is sent to CSRC which is a different system. We do not necessarily know from our system which number is going to be assigned to any certificate... that is decided by CSRC when a request is sent over to them. I'm not saying it's impossible, but it would require an unexpectedly large amount of work to handle the back-and-forth where we usually interact with CSRC by pushing data, never receiving.

**Comment by AlexThurston** [comment]
That's fair, but it looks like at least the validation ID is already being stored.

This is what I get back from prod for certificate `31757`

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "url": "/acvp/v1/validations/31757",
    "validationId": "A35"
  }
]
```

**Comment by AlexThurston** [comment]
Alternatively, could the CSRC list that is showing the certificate show the ACVP validation ID that was used to create their record?  That would also satisfy the use case I'm thinking of.

**Comment by celic** [comment]
I see. Might be worth opening up a new suggestion issue for that as it's a bit past the intended topic here. I'll pass it along to Shane though.

**Comment by AlexThurston** [comment]
Opened a new issue to capture this particular discussion.  As @celic stated, the intention of this original issue has been resolved and was drifting.
