### ISSUE TITLE
Must SHA-1 Message Length Contain Digest?

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#920]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
```json
{
  "revision": "1.0",
  "algorithm": "SHA-1",
  "messageLength": [
    {
      "min": 128,
      "max": 2048,
      "increment": 128
    }
  ]
}
```

**Endpoint in which the error is experienced**
`POST` `https://demo.acvts.nist.gov/acvp/v1/testSessions`

A vendor requires that the message length range from 16-256 bytes and the messages be 16 byte aligned.  This results in a registration like above, but it looks like when that is attempted, I get an error saying that the digest (160 bits or 20 bytes for SHA-1) is a required message length (which this domain does not contain).

Error message:
```json
{
  "error": "Validation error(s) on JSON payload.",
  "context": [
    "SHA-1-1.0: Message Length must contain the digest size itself."
  ]
}
```
Is having the digest message length for the SHA algorithm a requirement?

**Comment by celic** [comment]
This is done for the MCTs. They require processing a message that is 3x the digest length. A multiplier was missed in the parameter check though. It should require that the client is capable of handling a message that is 480-bits which is still not in the capabilities you list.

**Comment by Kritner** [comment]
It's a requirement for the current mct implementations. There's a few issues out there about potential changes to mct tests sometime in the future, but not in the radar at the moment afaik

**Comment by AlexThurston** [comment]
Thanks as always for the info @celic and @Kritner
