### ISSUE TITLE
POST /acvp/v1/login causes 500 error

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP#922]
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Internal service error. Contact service provider."
  }
]

This was the full URL. https://demo.acvts.nist.gov/acvp/v1/login

Using NIST supplied totp and .cer.

The authentication via cert behaved like it succeeded. Trying to figure out what caused the crash. Using wincrypt for cert handle and wininet for http. 

HTTP Headers
User Agent : Microsoft ACVP Client
Content-Type : application/json

Would appreciate any help.

**Comment by jarnold01** [comment]
Hi. Need a few pieces of information please: Date and timestamp of the attempted login(s), and does your client produce any more verbose output? Thanks.

**Comment by jarnold01** [comment]
Okay, in just doing a scan through the web server logs, I can see entries for your client attempts. I am seeing a bunch of attempts to other endpoints, such as "/" and "/login" which are either resulting in 404 or 500 errors but are not valid. The /acvp/v1/login is the correct URL to be using (to confirm that), and I'm seeing the 500 errors from those attempts as well per your original post. Hopefully you can provide some additional information from the client-side of things so we can see what is actually being sent and why the server is unhappy with it. Thanks.

**Comment by jbarnesweb** [comment]
Hey thanks. Maybe a pcap dump?

**Comment by celic** [comment]
Is this new behavior with this recent deployment? Is this your first attempt to login? Or has this happened before?

**Comment by jbarnesweb** [comment]
first attempt

**Comment by Kritner** [comment]
can you post the payload you're hitting the `/login` endpoint with any secret values omitted?

**Comment by jarnold01** [comment]
Thanks for the offer of the pcap dump @jbarnesweb , but we aren't permitted to open them per our security policy. So we'll have to figure out something else.

**Comment by jbarnesweb** [comment]
I'm hitting /acvp/v1/login with
with these headers
Content-Type : application/json
and this payload
[ { "acvVersion": 0.x"}, {"password": "AewsU... (truncated)" }]

I hit this point sharing my certificate provided programmatically by wininet from a pfx store that includes the private key.

**Comment by celic** [comment]
The password should be the computed TOTP value when you use your seed in a TOTP implementation. It should be an 8-digit number. Our wiki provides some more information about this.

**Comment by jbarnesweb** [comment]
The totp I used was what was sent to me along with the nist-signed .cer file.

Is that the wrong file? If so, what is the totp file sent to me for?

**Comment by celic** [comment]
That is the seed used in the TOTP computation to generate a password. TOTP is a time-based one-time password. We provide you a seed which you use each time you need to login to generate a one-time password which is an 8 digit number.

**Comment by Kritner** [comment]
Based on #924 I'm guessing that means this issue can be closed @jbarnesweb ?
