### ISSUE TITLE
What is the use of preReqVals? 

### ISSUE THREAD

**Issue by s-c-c** [usnistgov/ACVP#923]
Hi, I can't find out what preReqVals are used for in the ACVP RSA protocol. How does valValue works?

**Comment by smuellerDD** [comment]
Am Montag, 20. Juli 2020, 10:02:34 CEST schrieb s-c-c:

Hi s,

> Hi, I can't find out what preReqVals are used for in the ACVP RSA protocol.
> How does valValue works?

Description: see RSA ACVP spec Table 2

Example:

```
      {
         "algorithm": "RSA",
         "mode": "decryptionPrimitive",
         "revision": "1.0",
         "prereqVals":
           [
               {"algorithm": "DRBG", "valValue": "123456"},
               {"algorithm": "DRBG", "valValue": "654321"},
               {"algorithm": "SHA", "valValue": "7890"}
           ]
      }
```

Ciao
Stephan

**Comment by s-c-c** [comment]
That means SHA will use valValue as seed or something？

**Comment by smuellerDD** [comment]
Am Montag, 20. Juli 2020, 14:34:50 CEST schrieb s-c-c:

Hi s,

> That means SHA will use valValue as seed or something？

valValue points to another certificate number satisfying the dependency for 
the given cipher.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/usnistgov/ACVP/issues/923#issuecomment-661001902


Ciao
Stephan

**Comment by s-c-c** [comment]
What does the value "same" mean?

**Comment by celic** [comment]
That the capabilities for SHA for example exist in the same test session as the algorithm that depends on SHA.

**Comment by s-c-c** [comment]
There are two mode for ecdsa keygen specified in FIPS 186-4. "extra bit" and "testing candidates". 
Does openssl support both two modes? and in the api EC_KEY_generate_key, i dont find the param to controll 
which mode to be used for keygen. i want to know how to select the mode for application?

**Comment by smuellerDD** [comment]
Am Dienstag, 21. Juli 2020, 08:07:56 CEST schrieb s-c-c:

Hi s,

> There are two mode for ecdsa keygen specified in FIPS 186-4. "extra bit" and
> "testing candidates". Does openssl support both two modes? and in the api
> EC_KEY_generate_key, i dont find the param to controll which mode to be
> used for keygen. i want to know how to select the mode for application?

This is a bug tracker for ACVP development. Your question is about OpenSSL. I 
think this question does not belong to this thread.

The answer is given in [1]

[1] https://github.com/smuellerDD/acvpproxy/blob/master/lib/
module_implementations/definition_impl_openssl.c#L544

Ciao
Stephan

**Comment by dmchodnicki** [comment]
The original questions raised by this item have been answered.  Therefore, the issue is being Closed.  Future updates related to Prerequisite Processing are being tracked in issue #1071 .
