### ISSUE TITLE
HTTP 404 for /acvp/v1/register

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP#924]
**environment**
The environment the issue was experienced (Demo )

**testSessionId**

**vsId**

**Algorithm registration**

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/register POST

**Expected behavior**
Receive a session access token

**Additional context**
I received a good response from /acvp/v1/login.
[
  {
    "acvVersion": "1.0"
  },
  {
    "accessToken": "eyJ...",
    "largeEndpointRequired": false,
    "sizeConstraint": -1
  }
]

Then I received a 404 when I tried to get a session token at /acvp/v1/register.

I'm trying to follow the pattern at https://github.com/usnistgov/ACVP/wiki after /login

Help appreciated.

**Comment by jbarnesweb** [comment]
The http headers were
Content-type: application/json
Authorization: Bearer <accessToken from above>

**Comment by Kritner** [comment]
@jbarnesweb Can you provide the payload of what you POSTed to `/register` with?

**Comment by jbarnesweb** [comment]
No payload. Just headers.

**Comment by jbarnesweb** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/12917479/87965147-24c10980-ca70-11ea-93ae-62589cfa1f81.png)

**Comment by Kritner** [comment]
ah that endpoint always requires a payload of the crypto algorithms that you'd like to get test vectors for.  I'm not sure if I've ever actually tried to hit that endpoint without a payload, but apparently we aren't handling it properly as we're returning a 500.  I'll put in a fix for that.

In the meantime, you'll need to hit that endpoint with a set of capabilities that you want to receive test vectors for.  Here is an example payload:

```json
[{
		"acvVersion": "1.0"
	},
	{
		"isSample": true,
		"algorithms": [
			{
			  "algorithm": "ACVP-AES-CBC",
			  "revision": "1.0",
			  "direction": [
			    "encrypt",
			    "decrypt"
			  ],
			  "keyLen": [
			    128,
			    192,
			    256
			  ]
			}
		]
	}
]
```

But we support many different algorithms, you can check out the full list on the readme (and their subsequent specifications) at: https://usnistgov.github.io/ACVP/

**Comment by jbarnesweb** [comment]
Oh, ok.

BTW it wasn't a 500, it was a 404 (Not found). Led me to believe there isn't a /register endpoint.

**Comment by Kritner** [comment]
Ah sorry I think I was mixing up this and another issue in my head.  "Register" isn't actually a valid endpoint, I'm not sure if that diagram on the wiki is outdated, or if it's just more to convey a flow.  The endpoint that's actually used to create a test session is this one: https://usnistgov.github.io/ACVP/artifacts/draft-fussell-acvp-spec-00.html#testSessions_post

**Comment by jbarnesweb** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/12917479/88073267-d91f6600-cb2a-11ea-8b1c-3727998bd015.png)
I'm getting 404 errors on resources that should be there, I think. I'm using the /acvp/v1 path prefix to all the endpoints. It works on /login but it doesn't work on /vendors or /algorithms.

**Comment by Kritner** [comment]
Could you have a line break in between "https://demo.acvts.nist.gov/" and "acvp/v1/algorithms"? 

I see a few 404s in our logs today notably:

```
HTTP "GET" "/" responded 404 in 0.0070 ms
```

We don't have an endpoint at root, could that be your attempts? I see 11 of them from today from the last time logs were pulled.

**Comment by jbarnesweb** [comment]
Thank you so much for that feedback. Yes, that was the issue.
