### ISSUE TITLE
AES-XTS - No mention of "sequenceNumber" in spec for block cipher

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#926]
Hello,

My understanding from the spec documentation for block ciphers for AES-XTS:

 for a tweakMode of "number", we would expect "tweakValue" in test cases to be an integer in hex string form. 
`Number refers to the tweakValue being an integer number represented as a hex string.`

However, it appears that the current implementation for AES-XTS with number mode is that instead of getting a "tweakValue", test cases get "sequenceNumber" with a regularly formatted integer. I can't find any mention of sequenceNumber in the spec.

Just seeking clarification - is the current spec or the current implementation the long-term way forward? 

Thanks,
Andrew

**Comment by celic** [comment]
`"sequenceNumber"` is used when the `"tweakMode": "number"` for the group. The documentation update is coming.

**Comment by abkarcher** [comment]
Awesome, thank you for the clarification!
