### ISSUE TITLE
Test result dispositions: "error" not mentioned in the spec

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#927]
Hello,

Based on the spec, it seems the valid dispositions for test results are:
fail, unreceived, incomplete, expired, passed

However, based on an issue we received, https://github.com/cisco/libacvp/issues/452
It seems the server can sometimes insert "error" as a disposition.

It would be useful if the spec defined what this entailed. Is the error an issue with the user submissions or the server? Is there an endpoint that can be accessed to find out what the "error" was if it is a client/user issue?

Thanks,
Andrew

**Comment by celic** [comment]
Error might happen if the client sends something malformed or unexpected. This is picked over "failed" in cases where the validation cannot be run with the provided file. We will keep this as a flag, but I do see it doesn't exist in the list of valid dispositions. 

Briefly, to distinguish between "failed" and "error"... "failed" means the crypto was run and the results were incorrect. "error" means at some point the crypto was unable to run so no verdict could be determined. The error message should always be included but at the moment they are just plain english (no status codes for example).

**Comment by dmchodnicki** [comment]
Given the clarification provided distinguishing processing errors from disposition results, this item is being Closed.  Future error code improvements (e.g., more detailed messages and their associated documentation in the spec) will be aggregated into a single Gitub issue.
