### ISSUE TITLE
ACVP seemingly sent empty vsID array for test session

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#929]
I am on the hunt for a bug that is hard to reproduce. I am not fully sure it is an issue on the server side, but I think it is worth checking.

Once in a long while it seems that we fail to get some test vectors. My proxy does not log any error in the entire communication. After some debugging, I found only one instance where my client does not flag any error on unexpected data received from the server as follows: when the client performs a POST /testSessions, eventually the server returns an answer that contains an array of vsIDs. If that array is empty, my client would not flag that as an error (it does now) for that test session. Yet, it would not download any test vector because the array was empty.

We have identified the following test session where we did not get any test vectors, but also my client had no errors logged. Thus, may I ask you whether you can briefly check the server side whether the test session has any vsIDs created or whether you see some issues in general relating to the issue that we have not received any test vectors?

Production server, test sessions 1925, 1912.

Thanks a lot

**Comment by jarnold01** [comment]
Hi Stephan, yes, I can confirm that vsIDs exist for both of these test session IDs you have provided. tsID 1912 has one vsID, and tsID 1925 has five vsIDs.

**Comment by jarnold01** [comment]
additionally, after checking today's web public server logs, I can find no entries for either test session present, but no errors, either. I do see a bunch of other test session GET queries and such, though.

**Comment by Kritner** [comment]
@smuellerDD do you have the JWTs for those two test session, but for whatever reason don't have the vector set IDs and prompt files they correspond to?  If you do have the JWTs, here are the vector set IDs for the test sessions you pointed out:

ts 1912:
```
21502
```

ts 1925:
```
21559
21560
21561
21562
21563
```

From our side we did produce a set of files, and they are visible to our internal system, curious (assuming you have the JWTs) if you can pull the prompt files now.

Nothing really looks amiss from our end so far.

If you *don't* have the JWTs, we'll have to explore other options.  Do you have handy the response from the server when doing the `/testSession` POSTs?

**Comment by smuellerDD** [comment]
Am Freitag, 24. Juli 2020, 17:56:16 CEST schrieb Jason Arnold:

Hi Jason,

> additionally, after checking today's web public server logs, I can find no
> entries for either test session present, but no errors, either. I do see a
> bunch of other test session GET queries and such, though.

It seems you are saying that my client did not query the test session even 
though they were created.


Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Freitag, 24. Juli 2020, 18:11:54 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD do you have the JWTs for those two test session, but for
> whatever reason don't have the vector set IDs and prompt files they
> correspond to? 

Actually I do not have the JWTs because due to this issue I do not have a 
local test session created and store the JWT. I fixed that in my new code.

> If you do have the JWTs, here are the vector set IDs for
> the test sessions you pointed out:
> 
> ts 1912:
> ```
> 21502
> ```
> 
> ts 1925:
> ```
> 21559
> 21560
> 21561
> 21562
> 21563
> ```
> 
> From our side we did produce a set of files, and they are visible to our
> internal system, curious (assuming you have the JWTs) if you can pull the
> prompt files now.
> 
> Nothing really looks amiss from our end so far.
> 
> If you *don't* have the JWTs, we'll have to explore other options.  Do you
> have handy the response from the server when doing the `/testSession`
> POSTs?

That is it, I do not, because my client thinks all was nice and good. Then it 
does not produce error log messages with the server response. :-(


Ciao
Stephan

**Comment by jarnold01** [comment]
> Am Freitag, 24. Juli 2020, 17:56:16 CEST schrieb Jason Arnold: Hi Jason,
> additionally, after checking today's web public server logs, I can find no entries for either test session present, but no errors, either. I do see a bunch of other test session GET queries and such, though.
> It seems you are saying that my client did not query the test session even though they were created. Ciao Stephan

Correct; in the server logs I see no attempts by the client to issue a GET request to either of those test session IDs. @Kritner will take it from here.

Thanks,
Jason

**Comment by smuellerDD** [comment]
Thanks for your help and getting me an updated JWT. I tested 1912.

That JWT allows me to log in and I get a new JWT back. But when I use that to GET /acvp/v1/testSessions/1912/vectorSets/21502 I get an HTTP code of 403.

Looking at the received JWT and decoding it, I do NOT find the test session ID in there:

```
{"alg":"HS256","typ":"JWT"}{"sub":"E=cst-acvp@atsec.com, CN=ACVP Team, OU=CST Laboratory, O=atsec information security corp, L=Austin, S=Texas, C=US","nbf":1595
```

Thanks

**Comment by Kritner** [comment]
@smuellerDD are you sure that you refreshed the provided JWTs? I confirmed the JWTs sent to you do have the appropriate claims, and on a refresh process those claims are transferred over to the new JWT.  Can you double check that your refresh login was using the appropriate JWTs for refresh?

**Comment by smuellerDD** [comment]
I re-added manually the provided token again, which works now.

But the test vector returned by the server is:

```
[{"acvVersion":"1.0"},{"error":"The provided JWT expired at 2020-07-24 17:47:29Z and is no longer valid. The JWT claims may be refreshed through the renewal process described in the specification."}][
  {
    "acvVersion": "1.0"
  },
  {
    "vsId": 21502,
    "algorithm": "ACVP-AES-OFB",
    "revision": "1.0",
    "isSample": false,
    "testGroups": [
      {
        "tgId": 1,
        "testType": "AFT",
        "direction": "encrypt",
        "keyLen": 128,
        "tests": [
          {
            "tcId": 1,
            "iv": "B26AEB1874E47CA8358FF22378F09144",
            "pt": "00000000000000000000000000000000",
            "key": "00000000000000000000000000000000"
          },
```

Note, this is from the raw communication protocol which makes me believe that the server truly sent this information

**Comment by Kritner** [comment]
@smuellerDD I haven't had any luck reproducing the response from https://github.com/usnistgov/ACVP/issues/929#issuecomment-664594031, I either get the JWT is expired message or get the prompt after a JWT refresh, not both in a single response. Is there any way the client wrote to the "prompt" file the JWT expired response, then on the second attempt to pull appended onto the original file?  Or are you saying you saw the response directly from the curl command?

**Comment by smuellerDD** [comment]
Am Dienstag, 28. Juli 2020, 11:59:00 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD I haven't had any luck reproducing the response from
> https://github.com/usnistgov/ACVP/issues/929#issuecomment-664594031, I
> either get the JWT is expired message or get the prompt after a JWT
> refresh, not both in a single response. Is there any way the client wrote
> to the "prompt" file the JWT expired response, then on the second attempt
> to pull appended onto the original file?

All is possible. But that is why I said I took the message from the raw 
communication log where there is no data processing on my client side yet. 
Thus, I would suspect that the server sent me the data.

> Or are you saying you saw the
> response directly from the curl command?

Steps I used:

1. log in without a JWT -> server sent a new JWT with an empty test session

2. use the JWT with the empty test session to log in for a test session and 
try to GET  the vsID

3. after a day, replace the JWT with the one that is known to work (i.e. the 
one received from you)

4. the server sent the test vector.

If you cannot reproduce it, I would not spend cycles on it, because it was the 
first time ever I saw that.

But on the demo server I try to reproduce the original issue - yesterday I got 
one of these errors, the server sent some data I could not parse. But my 
debugging log was insufficient to indicate what exactly was the cause of the 
inability to parse. Thus, I need more test rounds.


Ciao
Stephan

**Comment by smuellerDD** [comment]
I found the issue causing this discussion: it was a hard to debug race condition on my client due to its massive parallel threading. Thanks a lot to all your help!

Russ, close the thread at your discretion as you may want to keep it open to check on the issue of the error message in the test vector
