### ISSUE TITLE
CMAC-AES issue

### ISSUE THREAD

**Issue by kwong-cygnacom** [usnistgov/ACVP#930]
**environment**
Demo

**testSessionId**

**vsId**
The vectorSet ID displaying the issue

**Algorithm registration**
[ {
  "acvVersion" : "1.0"
}, {
  "isSample" : true,
  "publishable" : false,
  "algorithms" : [ {
    "algorithm" : "CMAC-AES",
    "revision" : "1.0",
    "prereqVals" : [ {
      "algorithm" : "AES",
      "valValue" : "same"
    } ],
    "capabilities" : [ {
      "direction" : [ "gen", "ver" ],
      "keyLen" : 128,
      "msgLen" : [ {
        "min" : 0,
        "max" : 65536,
        "increment" : 8
      } ],
      "macLen" : [ {
        "min" : 64,
        "max" : 128,
        "increment" : 8
      } ]
    } ]
  } ]
} ]

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions POST

**Expected behavior**
A successful registration is expected. (CMAC-TDES also has the same issue.)

**Additional context**
Error Message :
[
 {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "CMAC-AES-1.0: Error converting value 128 to type \u0027System.Int32[]\u0027. Path \u0027capabilities[0].keyLen\u0027, line 1, position 191."
    ]
  }
]

**Comment by Kritner** [comment]
You're providing a scalar `int`, when an `array of int` is expected in your `keyLen` property registration.

**Comment by celic** [comment]
The error message states this too.

**Comment by kwong-cygnacom** [comment]
According to draft-ietf-acvp-submac-1.0, section 4.1. CMAC-AES Algorithm Capabilities Registration

keyLen is a JSON type value

Did I look at an outdated specs? keyLen is actually implemented as a JSON type array.

**Comment by celic** [comment]
Spec is wrong. Will be updated in the batch release I have prepared.

**Comment by kwong-cygnacom** [comment]
The new GitHub specifications (https://www.github.com/usnistgov/ACVP) in Metanorma still show keyLen is JSON type integer. Please also update the example if possible.
