### ISSUE TITLE
Vectors never generated, now 500 on login

### ISSUE THREAD

**Issue by jk-acumen** [usnistgov/ACVP#935]
**environment**
Demo

**testSessionId**
99692

**vsId**
288867

**Endpoint in which the error is experienced**
GET https://demo.acvts.nist.gov/acvp/v1/testSessions/99692/vectorSets/288867
POST https://demo.acvts.nist.gov/acvp/v1/login

**Expected behavior**
I created a test session, but even after several hours I was still not able to GET the vectors and would just receive a retry response. Now when I try to login I receive a 500 error, both for an initial login or renewal login:
[{
    "acvVersion": "1.0"
  },
  {
    "error": "Internal service error. Contact service provider."
  }]

**Additional context**
Prior to the 500 on login, we had created two other test sessions besides 99692 with the same issue that the vector sets never generated.

**Comment by Kritner** [comment]
A notice email was sent to demo users regarding an extended maintenance of the environment starting yesterday at 10a EDT; this maintenance is likely the cause of both concerns in this issue.

A maintenance complete notice has not yet been sent out, but I have been successful in starting and finishing a test session this morning.

**Comment by jk-acumen** [comment]
Thanks for the update. For some reason we did not receive the email about the maintenance.

**Comment by jarnold01** [comment]
@jk-acumen If you'd like me to add an email address to our maintenance notification list, just send me an email jason.arnold@nist.gov with the address(es) you'd like added, and I'll get it taken care of.
