### ISSUE TITLE
Cannot list resources on Demo

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#936]
**environment**
DEMO

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
`GET https://demo.acvts.nist.gov/acvp/v1/vendors?limit=20&offset=0`

Since the completion (or rollback) of the update to demo this morning (10am EST), I don't seem to be able to list any resources.  When I try to list vendors for example, I'm getting a 500:
```json
[
    {
        "acvVersion": "1.0"
    },
    {
        "error": "Internal service error. Contact service provider."
    }
]
```

I'm receiving the same error when listing modules, oes, etc...

Strangely, I am able to create test session.

**Comment by celic** [comment]
When the system was coming back up some permissions were missed as the databases moved. We have built these into our start up checks now so it shouldn't happen again. Everything should be good now.

**Comment by AlexThurston** [comment]
Working for me.  Thanks.
