### ISSUE TITLE
SRTP KDF errata should be supported

### ISSUE THREAD

**Issue by RKinsey** [usnistgov/ACVP#950]
At least one major SRTP implementation, [libSRTP](https://github.com/cisco/libsrtp/), uses a KDF that is incorrect according to both SP 800-135 and the original RFC 3711 because it treats SRTP and SRTCP IVs identically (both specs say SRTCP's index should be 16 bits shorter, which moves the label position in the IV).  

However, there has been [errata](https://www.rfc-editor.org/errata/eid3712) issued for RFC 3711 that changes the KDF behavior to match libSRTP's. The amended KDF has been approved by NIST since 2016 (see: https://csrc.nist.gov/CSRC/media/Publications/sp/800-135/rev-1/final/documents/sp800-135r1-informative-note-20160919.pdf), but is still unsupported by both ACVTS and the legacy ASKDFVS.

**Comment by celic** [comment]
Thanks for the information. I'll make sure this gets included.

**Comment by livebe01** [comment]
The fix for this is on Demo in release [v1.1.0.28](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.28).
