### ISSUE TITLE
Introduce specification for KAS-IFC-SSC / null / Sp800-56Br2

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#955]
KAS-IFC-SSC / null / Sp800-56Br2 is intended to test just the shared secret computation component of KAS IFC from https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Br2.pdf

This issue tracks the introduction of the specification for this algorithm

**Comment by Kritner** [comment]
Sample registration until the specification is completed:

```json
{
  "algorithm": "KAS-IFC-SSC",
  "revision": "Sp800-56Br2",
  "scheme": {
    "kas1": {
      "kasRole": [
        "initiator",
        "responder"
      ]
    },
    "kas2": {
      "kasRole": [
        "initiator",
        "responder"
      ]
    }
  },
  "keyGenerationMethods": [
    "rsakpg2-basic",
    "rsakpg2-crt"
  ],
  "modulo": [
    2048
  ],
  "hashFunctionZ": "SHA2-512"
}
```

The above registration should be very similar to the "full" kas testing for IFC if referencing is needed until the specification for KAS-IFC-SSC is introduced.

**Comment by smuellerDD** [comment]
Am Dienstag, 18. August 2020, 17:37:08 CEST schrieb Russ Hammett:

Hi Russ,

> KAS-IFC-SSC / null / Sp800-56Br2 is intended to test just the shared secret
> computation component of KAS IFC from
> https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Br2.pdf
> 
> This issue tracks the introduction of the specification for this algorithm

After having the registration capability implemented, I am wondering about the 
hierarchy of the keyGenerationMethods.

The KAS-IFC defines the keyGenerationMethods as part of the schema. KAS-IFC-
SSC defines it at the highest level. Shouldn't it be more like KAS-IFC?

Ciao
Stephan

**Comment by Kritner** [comment]
@smuellerDD Have you attempted KAS-IFC recently? I wasn't aware of many people testing against it yet (part of the reason it's not yet on prod).  Just recently in issue https://github.com/usnistgov/ACVP/issues/945, which spawned from https://github.com/usnistgov/ACVP/issues/942#issuecomment-669990159, I updated KAS-IFC to make the registration more flat, which should be *closer* to how the other kas flavors of ECC and FFC are.

KAS-IFC:
```json
[{
		"acvVersion": "1.0"
	},
	{
		"isSample": true,
		"algorithms": [{
			"algorithm": "KAS-IFC",
			"revision": "Sp800-56Br2",
			"isSample": true,
			"iutId": "123456ABCD",
			"modulo": [2048],
			"keyGenerationMethods": ["rsakpg1-basic"],
			"fixedPubExp": "010101",
			"scheme": {
				"KAS1-basic": {
					"kasRole": ["initiator", "responder"],
					"kdfMethods": {
						"oneStepKdf": {
							"auxFunctions": [{
								"auxFunctionName": "KMAC-128",
								"macSaltMethods": ["default"]
							}],
							"fixedInfoPattern": "algorithmId||l||uPartyInfo||vPartyInfo",
							"encoding": ["concatenation"]
						},
						"twoStepKdf": {
							"capabilities": [{
								"macSaltMethods": ["random"],
								"fixedInfoPattern": "l||label||uPartyInfo||vPartyInfo||context",
								"encoding": ["concatenation"],
								"kdfMode": "feedback",
								"macMode": ["HMAC-SHA3-224"],
								"supportedLengths": [512],
								"fixedDataOrder": ["after fixed data"],
								"counterLength": [32],
								"requiresEmptyIv": false,
								"supportsEmptyIv": false
							}]
						}
					},
					"macMethods": {
						"KMAC-128": {
							"keyLen": 128,
							"macLen": 224
						}
					},
					"l": 512
				}
			}
		}]
	}
]
```

KAS-IFC-SSC:
```json
[{
		"acvVersion": "1.0"
	},
	{
		"isSample": true,
		"algorithms": [{
			"algorithm": "KAS-IFC-SSC",
			"revision": "Sp800-56Br2",
			"isSample": true,
			"scheme": {
				"kas1": {
					"scheme": "KAS1",
					"kasRole": ["initiator", "responder"]
				},
				"kas2": {
					"scheme": "KAS2",
					"kasRole": ["initiator", "responder"]
				}
			},
			"keyGenerationMethods": ["rsakpg2-basic", "rsakpg2-crt"],
			"modulo": [2048],
			"hashFunctionZ": "SHA2-512"
		}]
	}
]
```

KAS-ECC:
```json
[{
		"acvVersion": "1.0"
	},
	{
		"isSample": true,
		"algorithms": [{
			"vsId": 0,
			"algorithm": "KAS-ECC",
			"revision": "Sp800-56Ar3",
			"isSample": true,
			"iutId": "123456ABCD",
			"scheme": {
				"fullMqv": {
					"scheme": "fullMqv",
					"underlyingAlgorithm": "Ecc",
					"kasRole": ["initiator", "responder"],
					"kdfMethods": {
						"oneStepKdf": {
							"kdfType": "oneStep",
							"auxFunctions": [{
								"auxFunctionName": "KMAC-128",
								"macSaltMethods": ["default"]
							}],
							"fixedInfoPattern": "algorithmId||l||uPartyInfo||vPartyInfo",
							"encoding": ["concatenation"]
						},
						"twoStepKdf": {
							"kdfType": "twoStep",
							"capabilities": [{
								"macSaltMethods": ["random"],
								"fixedInfoPattern": "l||label||uPartyInfo||vPartyInfo||context",
								"encoding": ["concatenation"],
								"kdfMode": "feedback",
								"macMode": ["HMAC-SHA3-224"],
								"supportedLengths": [512],
								"fixedDataOrder": ["after fixed data"],
								"counterLength": [32],
								"requiresEmptyIv": false,
								"supportsEmptyIv": false
							}]
						}
					},
					"keyConfirmationMethod": {
						"macMethods": {
							"KMAC-128": {
								"macType": "KMAC-128",
								"keyLen": 128,
								"macLen": 128
							}
						},
						"keyConfirmationDirections": ["unilateral"],
						"keyConfirmationRoles": ["provider", "recipient"]
					},
					"l": 512
				}
			},
			"domainParameterGenerationMethods": ["P-224"]
		}]
	}
]
```

KAS-ECC-SSC:
```json
[{
		"acvVersion": "1.0"
	},
	{
		"isSample": true,
		"algorithms": [{
			"algorithm": "KAS-ECC-SSC",
			"revision": "Sp800-56Ar3",
			"scheme": {
				"ephemeralUnified": {
					"kasRole": ["initiator", "responder"]
				}
			},
			"domainParameterGenerationMethods": ["P-224"]
		}]
	}
]
```

KAS-FFC:
```json
[{
		"acvVersion": "1.0"
	},
	{
		"isSample": true,
		"algorithms": [{
			"vsId": 0,
			"algorithm": "KAS-FFC",
			"revision": "Sp800-56Ar3",
			"isSample": true,
			"iutId": "123456ABCD",
			"scheme": {
				"dhEphem": {
					"scheme": "dhEphem",
					"underlyingAlgorithm": "FFC",
					"kasRole": ["initiator", "responder"],
					"kdfMethods": {
						"oneStepKdf": {
							"kdfType": "oneStep",
							"auxFunctions": [{
								"auxFunctionName": "KMAC-128",
								"macSaltMethods": ["default"]
							}],
							"fixedInfoPattern": "algorithmId||l||uPartyInfo||vPartyInfo",
							"encoding": ["concatenation"]
						},
						"twoStepKdf": {
							"kdfType": "twoStep",
							"capabilities": [{
								"macSaltMethods": ["random"],
								"fixedInfoPattern": "l||label||uPartyInfo||vPartyInfo||context",
								"encoding": ["concatenation"],
								"kdfMode": "feedback",
								"macMode": ["HMAC-SHA3-224"],
								"supportedLengths": [512],
								"fixedDataOrder": ["after fixed data"],
								"counterLength": [32],
								"requiresEmptyIv": false,
								"supportsEmptyIv": false
							}]
						}
					},
					"l": 512
				}
			},
			"domainParameterGenerationMethods": ["FB", "MODP-2048"]
		}]
	}
]
```

KAS-FFC-SSC:
```json
[{
		"acvVersion": "1.0"
	},
	{
		"isSample": true,
		"algorithms": [{
			"algorithm": "KAS-FFC-SSC",
			"revision": "Sp800-56Ar3",
			"scheme": {
				"dhHybridOneFlow": {
					"kasRole": ["initiator", "responder"]
				}
			},
			"domainParameterGenerationMethods": ["MODP-2048"]
		}]
	}
]
```

All KAS flavors (at least in the newer kases, not the 1.0 revision of testing) should have their key generation methods specified at the "root" level of the algorithm, unless I've missed something in the documentation somewhere.

**Comment by smuellerDD** [comment]
Am Donnerstag, 20. August 2020, 20:14:03 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD Have you attempted KAS-IFC recently? 

I tested it when it was released to verify my registration code. Maybe it was 
2 months ago. But I am aware that some changes were pushed. Those changes are 
on my TODO stack to have them implemented.


> I wasn't aware of many
> people testing against it yet (part of the reason it's not yet on prod). 
> Just recently in issue https://github.com/usnistgov/ACVP/issues/945, which
> spawned from
> https://github.com/usnistgov/ACVP/issues/942#issuecomment-669990159, I
> updated KAS-IFC to make the registration more flat, which should be
> *closer* to how the other kas flavors of ECC and FFC are.

The both registrations indeed look similar now. Please disregard my comment 
then :-)

Ciao
Stephan

**Comment by Kritner** [comment]
@smuellerDD KTS doesn't have a SSC component, only the KAS schemes do.  The reasoning behind that is the "KTS" schemes steps are:

* RSA-OAEP
* Optionally key confirmation

With the above two steps there's no real place to "break out" shared secret computation, since the encryption/decryption key `k` using RSA-OAEP is already the singular step to the KTS scheme not making use of key confirmation.

On the other hand, with the KAS IFC (as well as ECC and FFC) schemes you have:

* SSC
* KDF
* Optionally key confirmation

All of the KAS schemes were at a minimum testing "SSC" and "KDF", with several schemes testing the "KC" portion as well.  The purpose of the SSC testing was to stop after the SSC, similar to the "component only tests" in previous KAS testing.  The "KAS-xxx-SSC" type testing is intended to take place of the "component only tests" where applicable; but it does not really apply to the KTS schemes as far as we can tell.

**Comment by smuellerDD** [comment]
Am Montag, 24. August 2020, 11:32:52 CEST schrieb Russ Hammett:

Hi Russ,

Thanks for the description - it was a typo on my side using KTS instead of 
KAS. It fetches the vectors.

Ciao
Stephan
