### ISSUE TITLE
acvp.nist.gov -> acvts.nist.gov

### ISSUE THREAD

**Issue by hbooth** [usnistgov/ACVP#96]
Just logging an issue to note that we will be switching from acvp.nist.gov to acvts.nist.gov for the domain name. We will likely want to update the examples to reflect this change. NOTE: The application context will remain the same, so that the URL will be:

https://acvts.nist.gov/acvp/validation/acvp/register

**Comment by atvassilev** [comment]
FYI, acvts stands for Automated Cryptographic Validation Testing Service and we plan to have two application contexts: acvp and amvp. The latter is for module testing, when available.

**Comment by atvassilev** [comment]
Resolved with PR #105.

**Comment by atvassilev** [comment]
Sorry, it should have said PR #102.
