### ISSUE TITLE
Refresh accessToken for TestSession fails with Failed to validate OTP

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP#960]
I have a simple test session I'm trying to submit results for.

I did an initial login to /acvp/v1/login with my 8 character OTP. It succeeded. This is the TestSession in question.

```
[
    {
        "acvVersion": "1.0"
    },
    {
        "accessToken": "eyJhbGci...<truncated>",
        "createdOn": "2020-08-10T10:05:22.0896228-04:00",
        "expiresOn": "2020-09-09T10:05:22.089625-04:00",
        "isSample": true,
        "passed": false,
        "publishable": false,
        "url": "/acvp/v1/testSessions/100981",
        "vectorSetUrls": [
            "/acvp/v1/testSessions/100981/vectorSets/293876",
            "/acvp/v1/testSessions/100981/vectorSets/293877"
        ]
    }
]


```

I had retrieved the vector sets a while back. The access token has expired. 

I POSTed the results to /testSessions/100981/vectorSets/293876/results. It bounced because the access token expired. I follow up with a POST to /acvp/v1/login with the following

```
[
   {"acvVersion": "0.x"},
   {"password":"<THE 8 CHARACTER OTP I LOGGED IN WITH EARLIER>",
    "accessToken":"<EXPIRED ACCESS TOKEN FROM ABOVE TEST SESSION>"}
]


```

It bounces with OTP failed to verify.

Is there something wrong with this process?

**Comment by Kritner** [comment]
when you say:

```
[
{"acvVersion": "0.x"},
{"password":"<THE 8 CHARACTER OTP I LOGGED IN WITH EARLIER>",
"accessToken":""}
]
```

"logged in with earlier" do you mean the OTP that was used at the initial login when the JWT was initially created?  The OTP will never be valid more than a single time, when hitting the login endpoint it should always be with the *current* timestamp OTP.  Additionally if the same OTP is attempted to be used more than once in a 30 second window it will be rejected.

**Comment by jbarnesweb** [comment]
Thank you!
