### ISSUE TITLE
Need help please with new module endpoint

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP#966]
I posted the following to the demo server at the /acvp/v1/modules endpoint to create a new module.
```
[
    {
        "acvVersion": "1.0"
    },
    {
        "implementationDescription": "SymCrypt Windows 2004 release",
        "name": "SymCrypt Cryptographic Implementations",
        "type": "Software",
        "vendorUrl": "/acvp/v1/vendors/11776",
        "version": "10.0.19041"
    }
]

I received the following reply.
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "module.addressUrl must be provided.",
      "module.contactUrls must be provided.",
      "module.description must be provided."
    ]
  }
]
```
I can't find anything about the missing items at https://tools.ietf.org/id/draft-fussell-acvp-spec-00.html#modules_post. It looks like two of them (addressUrl and contactUrls) should belong to the vendor at the vendorUrl in the post request. If not, where can I find information about the JSON types associated with the missing items?

The spec says only the vendor name is required to create a new vendor. https://tools.ietf.org/id/draft-fussell-acvp-spec-00.html#vendors_post

I'm quite confused.

**Comment by celic** [comment]
To create a vendor, only the name is needed. To use the vendor in a Certify, it needs the address and contacts. The naming here is a bit awkward in the error message. Those properties are grabbed from the Vendor to be used in the Module. The Module and Vendor are linked during a Certify in the sense that the Module now 'has a' Vendor, so complaining about the lack of a Module Address falls back on the underlying element that has an Address... the Vendor.

**Comment by jbarnesweb** [comment]
Thank you!
