### ISSUE TITLE
Certificate from Multiple Test Session

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#969]
**environment**
Either

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
*PUT* /testSessions/{testSessionId}

This is more of a question than issue, but in the situation where testing of the vectors has occurred over multiple test sessions, when you submit for validation, is it simply a function of submitting each of them against the same OE and Module and the ACVP sub-system will be smart enough to consolidate them into one single certificate?

I apologize in advance because I think I've asked this question before, but can't seem to find the answer and wanted to make sure.

**Comment by celic** [comment]
Yes that should be the case. Feel free to try it out on Demo.

**Comment by AlexThurston** [comment]
Perfect.  I was almost 95% certain, but wanted to confirm.

**Comment by smuellerDD** [comment]
I can confirm that this is the case. I have multiple test sessions - one for each OE where all are collapsed into one cert. One example is https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/details?product=12557

**Comment by smuellerDD** [comment]
Note, even when you come back months after the cert is created and you make a new test on another OE with the same cipher options, the existing cert is updated.
