### ISSUE TITLE
PUT vendors/{vendorID} fails with 405

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP#972]
I issued a GET for /acvp/v1/vendors/11776. I got the following response.

```

[
    {
        "acvVersion": "1.0"
    },
    {
        "contactsUrl": "/acvp/v1/vendors/11776/contacts",
        "name": "Microsoft Corp.",
        "url": "/acvp/v1/vendors/11776"
    }
]

```

I then issued a PUT to /acvp/v1/vendors/11776 with the following payload. (Note no url per spec)

```

[{
	"acvVersion": "1.0"
}, {
	"contacts": [{
		"address": {
			"country": "USA",
			"locality": "Redmond",
			"postalCode": "98034",
			"region": "WA",
			"street": "123 Redmond Way"
		},
		"emails": ["mgrimm@microsoft.com"],
		"name": "Mike Grimm"
	}],
	"contactsUrl": "/acvp/v1/vendors/11776/contacts",
	"name": "Microsoft Corp."
}]

```

I got a 405 Method Not Allowed with no error message. I also tried it without a "contactsUrl" and got the same result.

So I thought I would just create another vendor, this time making sure I would add contact info to the POST request this time. I got the following response with status 200.

```

[
    {
        "acvVersion": "1.0"
    },
    {
        "status": "initial",
        "url": "/acvp/v1/requests/14118"
    }
]


```
Hmm. Not sure what to do with that. Help appreciated.

**Comment by Kritner** [comment]
Are you sure you're attempting a `PUT` operation at `/acvp/v1/vendors/11776`? I just attempted on demo and got through. You cannot edit contacts directly from the vendor, contacts are managed at the "Person"s endpoint(s) https://usnistgov.github.io/ACVP/draft-fussell-acvp-spec.html#name-create-a-new-person, a vendor is attributed to a person at person creation/update.

Were you attempting to update the address for the vendor, or update a person that's currently attributed to the vendor?  If it's the former, you'd need the "addresses" property as a property of the root, not contacts.  if it's the latter, you'd need to either add/update a person with a vendorUrl matching the vendor.

**Comment by jbarnesweb** [comment]
Oh, heavens...

I have been consuming the spec by the same name at ietf.

Thanks for the link.
