### ISSUE TITLE
"MAC does not match" on the submission of the results

### ISSUE THREAD

**Issue by RoyHSYoo** [usnistgov/ACVP#975]
**environment**
The environment the issue was experienced (Demo or Prod): Demo

**testSessionId**
The test session ID: 103239

**vsId**
The vectorSet ID displaying the issue: 306301

**Algorithm registration**
The pertinent algorithm registration pieces (algorithm tested, capabilities, etc) in json format

```json
[
	{"acvVersion":"1.0"},
	{
		"isSample":true,
		"algorithms": [
			{
				"algorithm": "HMAC-SHA2-256",
				"revision": "1.0",
				"keyLen": [
					{
						"min": 64,
						"max": 512,
						"increment": 8
					}
				],
				"macLen": [
					256
				]
			}
		]
	}
]
```

**Endpoint in which the error is experienced**
https://[acvpUrl]/acvp/[endpoint] GET

**Expected behavior**

**Additional context**

Hello, I have tested for getting Test vectors and uploading the test results.
I refer to the last spec documents which was used for the legacy CAVP.
In this document, there is the spec for our device to verify HMAC:
    Algorithm: w/SHA-256 SHA2
    Key size(In bytes): SHA256 for KS(KeySize) > BS(BlockSize)
                  1st Value: 8, 2nd Value: 64
    Mac Size(In bytes): 32
Based on this information, I made the JSON data for the request like above and downloaded the test vector.
It was successful to create the result of mac values but I saw "MAC does not match" error when I had uploaded the result to the server.
Can you explain what was the problem? Was the request or the result wrong?

**Comment by Kritner** [comment]
The answers do not match the expected output for the given input for every test case in the file.

Example:

```json
{
	"tgId": 1,
	"testType": "AFT",
	"keyLen": 304,
	"msgLen": 128,
	"macLen": 256,
	"tests": [{
		"tcId": 1,
		"key": "0371479C93FE205C23D24CC32F594C3D00AEC70FD53CDBE3ABFDEE2A15DE02A082010AE0ED36",
		"msg": "F720E78A9551C333D677318A8B9CEFF0"
	}]
}
```

we expected:

```
56970F2991C045CED0CC47646A8CFD6E6AB0D413C7809FFD5EA88AC85EF82CE3
```

we received from your response file for that test case:

```
34C5E2A5018F852BF6D474474F05F5F7C4D11086A10BEBCE7408A226E3F240E0
```

**Comment by celic** [comment]
Because this algorithm has `isSample` set to true, at any point you can obtain the results the server expects by hitting the `GET testSessions/{tsId}/vectorSets/{vsId}/expected` endpoint.

**Comment by RoyHSYoo** [comment]
@Kritner @celic 
Thanks for your replies, I have found the reason to make the wrong test results :)
The shared expected values are very helpful to debug!
