### ISSUE TITLE
Validation request never passes "initial" status

### ISSUE THREAD

**Issue by DekraTC** [usnistgov/ACVP#976]
I've been trying to validate a few vectors in the demo server.

I uploaded the vector responses and the validation data last Wednesday, August 19th and I got an answer like:

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "url": "/acvp/v1/requests/14077",
    "status": "initial"
  }
]
```

I assumed that it would eventually change its status to "approved" (like it happened with vendor, module, etc requests). But it's been over a week now and there has been no change.

Did I miss a step to finish the demo validation? Is it normal to take so long?

**Comment by celic** [comment]
Requests are auto-approve in Demo. What likely happened was that there was an error that wasn't reported back out to you. Since then we've done some updates in demo especially around certify requests. Would you be able to send the request again? If there's still an error we can debug from there.

**Comment by Kritner** [comment]
This request is now approved
