### ISSUE TITLE
Managing and Understanding PreReqVals

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#980]
I saw that that there was somewhat old discussion [here](https://github.com/usnistgov/ACVP/issues/235) about the expectation when using the `same` tag to indicate that the prerequisite algorithms are being tested within the same registration/test session.

I was wondering if this was still the case.  There were some comments in the issue (and it's been quite some time) where perhaps there were some enhancements or improvements in the area.

Here's the catalyst and example use case to my question.

Let's say I have a test session where 3 algorithms have been registered: A, B, and C into test session X.

B and C depend on A, but since they are all in the same registration, the test session is registered indicating that they are `same`.  The vendor's responses for B and C are passing, but there is a problem with A.  So as per guidance, A is removed from the test session X and a new one is create with just A ( test session Y ).  At this point, the test session X should now be passing since B, C are cool.  Test session Y contains only A.  The vendor fixes the issues and now it's passing.  Great!  The problem is that test session X had been registered where their prereqs pointing to same which is no longer the case.

What should happen in this case?  The obvious answer is that the B and C need to be redone again and the prereqs would then have to point to the certificate created from only test session Y containing A.

Alternatively, you could, when A is found to be flawed, create test session Y with B and C as well and ask the vendor to re-do all the responses.

Both of those seem a little awkward.  Is there any other option to this situation?  I seem to remember seeing that you can specify the prerequisites when you submit the test session for validation rather than when you are registering.  In that case, you'd already have your passing test session(s) and therefore, setting the prerequisite values would be easy and straight-forward.  Maybe that's a better workflow to avoid this situation.

**Comment by celic** [comment]
Prerequisites are not well defined in specification and in code. This situation is definitely awkward to handle. I don't want to say anything definitive because prerequisites are not a system we have looked at much yet. Setting prerequisites during submission seems like the best way to do it, or allowing them to be overwritten/resolved during submission.

**Comment by AlexThurston** [comment]
Thanks for that insight.  Do you want to leave this issue open as a reminder?

**Comment by celic** [comment]
There's a lot of work that needs to happen here. At the moment it is not scheduled. I'll close out the issue, but I hope to have a discussion on prerequisites with the team soon.
