### ISSUE TITLE
Demo server PUT vendor with all vendor info loses phone numbers on approval

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP#984]
I created a vendor with POST "/acvp/v1/vendors". The request was eventually approved with vendor url "/acvp/v1/vendors/11799".

I called PUT /acvp/v1/vendors/11799 with the following JSON put data.

```


[{
	"acvVersion": "1.0"
}, {
	"addresses": [{
		"country": "US",
		"locality": "Redmond",
		"postalCode": "98054",
		"region": "WA",
		"street1": "950 148th Ave NE",
		"street2": "Studio E"
	}],
	"emails": ["v-jeffrb@microsoft.com"],
	"name": "Microsoft Corp.",
	"phoneNumbers": [{
		"number": "(215) 964-2227",
		"type": "voice"
	}],
	"website": "https://www.microsoft.com"
}]



```

When the request was approved, I checked the approvedUrl and my Vendor now looks like the following.

```



[
  {
    "acvVersion": "1.0"
  },
  {
    "url": "/acvp/v1/vendors/11799",
    "name": "Microsoft Corp.",
    "website": "https://www.microsoft.com",
    "emails": [
      "v-jeffrb@microsoft.com"
    ],
    "contactsUrl": "/acvp/v1/vendors/11799/contacts",
    "addresses": [
      {
        "url": "/acvp/v1/vendors/11799/addresses/11653",
        "street1": "950 148th Ave NE",
        "street2": "Studio E",
        "locality": "Redmond",
        "region": "WA",
        "country": "US",
        "postalCode": "98054"
      }
    ]
  }
]




```

The phoneNumbers array was lost. Is this a server bug or were the requests incorrect?

**Comment by Kritner** [comment]
Looks like the specification and code don't match up with what's expected for phone numbers on a vendor.  

Right now we're expecting (from the code):

POST "/acvp/v1/vendors"

```json
{
  "voiceNumber": "",
  "faxNumber": ""
}
```

While from the specification we're expecting:

```json
{
  "phoneNumbers": [{
    "number": "(215) 964-2227",
    "type": "voice"
  }]
}
```

I believe the spec should reflect what's in the code, and not the other way around, but let me do some additional checking on that.

**Comment by Kritner** [comment]
Just as an update, I'm updating the code to match the spec, so this functionality will be a bit off until this gets released to demo.  The information provided in https://github.com/usnistgov/ACVP/issues/984#issuecomment-684702057 shows what the current code is expecting, though the code will match the spec in the next release.

**Comment by Kritner** [comment]
This change is now on demo

**Comment by Kritner** [comment]
this change is now on production https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.12
