### ISSUE TITLE
RSA KeyGen bitlens not true to auxiliary primes

### ISSUE THREAD

**Issue by celic** [usnistgov/ACVP#992]
Sighted in at least B.3.6 (probableWithProbableAux) KeyGen. Some test cases have large 00 padding upfront of some auxiliary primes, and some just do not match the expected bitlen based on the test case.

See the following example
```
"tgId": 2,
"infoGeneratedByServer": true,
"modulo": 3072,
"testType": "AFT",
"keyFormat": "crt",
"primeTest": "tblC3",
"randPQ": "B.3.6",
"pubExp": "random",
"tests": [
    {
        "tcId": 4,
        "bitlens": [
            1312,
            194,
            849,
            647
        ],
        "xP": "DAD7FE7AF9478BAD3D0F1AAD82873273AF34C195870EF81757710E74C8D77A06C32B1970412224B689AE8D5D61163937C0DCE0D061431B05B71636B799014CDA5134BAF17DD35D188A831CFCA04C0F95A56EB3FB2BE74B8FDFDC4CB56334BE945FF3250437F0A5859D793467DD2D561D4A124BDBEC2CE82A5FDE43815D50E35322651FD2372E0B127E33C8D146457C490BC22E09963B42C0F2AAC5C4BBC640C2F4317CEB738862D663253D94AAA2F4C6D990FB15D52E4749F3EBD3CDCFD6912A",
        "xQ": "D17364E78B15195834D3EC09180E5B719EA86A2B609AA77314EA8A53908F91DCE8ED8F0F2AA49C9175322B1A28F7031C752D18F5E4ECE772F06526C0417B7B6FD2CEF751E8B0AB4123B05CA39934BB4228920BF27981BBF101BDC8EE0E46C5C18B88CB76C63DAE90E5FDF35AE81CA3D2D1AC6689918712526CA6EFF546E68FAC43B0B719D56053B050311A4A08C2A7176126FC600062BA82CDED6B99A7A2495BF2B0EC21332C7C2C54AB12B2C5AA6179782A4B0803D820DB7540BE85590FB4D2",
        "xP1": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005E47861FD27E924A06208A911EE576A2061A5DFDAAFFFE1D3811F52FD87807D8D18D333C8631CE98DBF7EAD81A5FA9F20FE1010F41C64691830C50A1166E41F1F8A5F1C8D78684082A9FC3F091812989B20B9D1969",
        "xP2": "019155A0C0D4E8652F4AACA245D55B4A23660D5986447A17211AB54A1081A2F51E44B4FD1B468D6B86E896997D12F508F1A0B696193E769C8E71E74D3F6E4DC5E32AB43ADE4CEBD9FD2698FDE009890868F5B9",
        "xQ1": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000D9306F4DE668E0895A3337B056CE85BD4489D14A55C5EA3D9",
        "xQ2": "1CFB359E66FD304D7BA2EFAD81A422726E1875B547D184B58A7C4CDF567DCFC1E877A2851A7BB9FD6C8CA07CCB392E5567F2D30552B9013F804F1A1FFA9CD91C1EBBE7B0F98964421DC76F49100405A59C477C2F99EE7CCF279C0E7FBDD7C4DBD5B180D0DECB9CE3216CF4CE8929DB8FCED8F6BF78AECD9F8CC57B966C86AE1196F872EC93D5",
        "e": "06978BDDCF01"
    },
```

`xP1` and `xQ1` are padded to the provided `bitlen[0]` and `bitlen[2]` respectively but should naturally match that boundary. While `xQ2` is around 400 bits longer than the provided `bitlen[3]`.

**Comment by celic** [comment]
This seems to be related to an old error where Pool values were being generated with a shared RNG. Sometimes long values would come out shorter than expected. This was fixed long ago but some values remained in the pools.

**Comment by mtdownz** [comment]
Chris,
We are still seeing this problem in the RSA KeyGen vectors:

                {
                    "tcId": 30,
                    "bitlens": [
                        1336,
                        178,
                        263,
                        888
                    ],
                    "xP": "B7646D26BB2F7CBCCCB69DAC51D68DDB2C3D419EED7B5A540C5AB99FC73CA028E899E18F70F657C28E2D9A776C29136BA891A64FCDE0FAAB62B3B6AB8EF7DB7913C3CB9C0117775B1270C543B259EACA840FD5892FD0FCC5F828B10178EFB84125124CEA7FA97A8DE0409D85B225472D34A7FAC98E81A615D535A6D7AAAEED442FE15FD555F3D6A00CF6AB931A6B0BC5AE74D82942416CC613F071D7032B0AE87E6EBF4FE91D236C17813161038225E7443BB62F59C27699D4A06AAC2B577AAD",
                    "xQ": "FEFFFAB806F4051E75B7BEE33220B62FFB13CE62BD99D3BC6864291D3661317EDAB62C31E9B69E295F1765FF96DF27915FF7559C5B5038BCA0BB083EB85226EC9C10B98F6FF731D93689F852E30F597820A9AC44C7E99EA607E23333B75B37461E0E8B83E459391D008903B4017311ED6C38F973EDC614DBBB894B071889B3CE7663BCD2CC9A153A502CAA99F8F33E789763E42E3807F41B0DA5B17B4E2CD107CDB276D1EAD0D3B0AE73A2469CEAA10D3B2AE66352D84498D7FF1BD3162C0860",
                    "xP1": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000967675E7CF29FB47A5E990513968FF9F16C0C4961EE720968D43E32F89B75DE363EEE4C24D519F13D7FCADCA8FD68948875D989195ACF38B48B3496E3DC33453A42037C2A186FCBF626A4302726959C6B210F2CE1B0203ABB196493A01017E1B0F2023D99D4B697A1BB393A948A51181FD4A6FABEE3373D",
                    "xP2": "7CF5F265F0AB3B7BCF0EAB969EF4FA707F3F3A7BB358D225D1A50AA109584B9344211645302A58BC2BE3ADE4F31DDC699F959356557D3D133A2391",
                    "xQ1": "5DB9B6C12DA8D5A4268A9EB64800DC34CB245D17206B2AF4EC0A2DC2862BEEF502F2A26CFC78882E5CF18B1E6BC5510137BE3930A0A9E0FF25B339B5D73295B2A90A7C9A0113F30455FDC1",
                    "xQ2": "00000000000000000000000000000001DEA7B4055C15EE53484D1714AD5C0EFDCD2F6DA87529CAF0801FD49E10823AAD694F885509DD545B43BA29EF13C9D790D3079627DD012C66FDBDE3B170320E713D2BDD84EDE20464564BAAA290C7AD63D144D01FF477D947D375370D41ABA7",
                    "e": "E51119C84E693D"
                },

Please advise on a workaround for this situation?
Thanks

**Comment by celic** [comment]
When did you request this vector set?
