### ISSUE TITLE
Failed to login with ACVP server

### ISSUE THREAD

**Issue by srinivasyelisetti** [usnistgov/ACVP#993]
We have received access to the https://demo.acvts.nist.gov server and seeing the following error

root@sjc-fw-nvm04:~/libacvp/libacvp/app# ./acvp_app --hash

 Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /home/nvm/libacvp/libacvp/certs/acvp.nist.gov.crt
    ACV_CERT_FILE:  /home/nvm/libacvp/libacvp/certs/Microchip_Srinivas_Yelisetti_Demo.cer
    ACV_KEY_FILE:   /home/nvm/libacvp/libacvp/certs/Private.key

 
***ACVP [STATUS][acvp_login:2476]--> Logging in...
Enter PEM pass phrase:
***ACVP [ERR][log_network_status:1491]--> 403 error received from server. Message:
***ACVP [ERR][log_network_status:1492]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Access denied! Reason: TOTP failed to verify"
  }
]
***ACVP [STATUS][acvp_login:2488]--> Login Send Failed
***ACVP [ERR][acvp_run:3167]--> Failed to login with ACVP server

Please help us to resolve this issue.

Thank you

**Comment by jarnold01** [comment]
Hi @srinivasyelisetti 

First, the TOTP SEED value is a secret and should never be posted publicly. I will re-generate a new TOTP value for you and send it over via nfiles shortly.

The double quotes are the likely issue - remove them from the variable assignment in your setup script.

Ensure that your server is synchronizing it's time via NTP.

Look for the new seed value momentarily. Thanks.

**Comment by srinivasyelisetti** [comment]
Thank you, Jason. Yes. I have realized after posting it. Thank you for sending another TOTP seed. We will try your suggestions and let you know.

**Comment by jarnold01** [comment]
You're welcome.

Also change the ACV_CA_FILE var to point to the "mozzila_trust_anchors.pem" file in the certs directory.

**Comment by srinivasyelisetti** [comment]
After changing the ACV_CA_FILE var to point to the "mozzila_trust_anchors.pem", we were able to communicate with the demo server without any issues.
