### ISSUE TITLE
ctrDRBG capability registration "General exception. Contact service provider."

### ISSUE THREAD

**Issue by tobyp** [usnistgov/ACVP#996]
**Environment** Demo

**Algorithm registration**
```
[{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"ctrDRBG","revision":"1.0","prereqVals":[{"algorithm":"AES","valValue":"same"}],"predResistanceEnabled":[false],"reseedImplemented":true,"capabilities":[{"mode":"AES-256","derFuncEnabled":true,"entropyInputLen":[256],"nonceLen":[128],"persoStringLen":[0],"additionalInputLen":[0],"returnedBitsLen":512}]}]}]
```

**Endpoint** `https://demo.acvts.nist.gov/acvp/testSessions POST`

**Error** Validation error(s) on JSON payload.

**Context** ctrDRBG-1.0: General exception. Contact service provider.

Scanning through the DRBG spec again, it seems there was some effort to rename `mode`s to names like `ACVP-ctrDRBG-AES-256` from the former `AES-256`, similar to the AES algorithm registry scheme. The prose and examples do not currently match. Perhaps this issue arises from code changes related to this?

**Comment by Kritner** [comment]
Thanks this looks to have been a miss in some new functionality introduced with the demo deployment yesterday, we need to issue a patch due to the problem described in #990, I'll get a fix in for this at that time as well.

**Comment by Kritner** [comment]
The fix for this has been pushed to demo.  Let me know if there are any other issues
