### ISSUE TITLE
DEMO: Cannot List Any Resources

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#997]
**environment**
Demo

**Endpoint in which the error is experienced**
`GET https://demo.acvts.nist.gov/acvp/v1/vendors?limit=20&offset=0`
`GET https://demo.acvts.nist.gov/acvp/v1/modules?limit=20&offset=0`
`GET https://demo.acvts.nist.gov/acvp/v1/oeslimit=20&offset=0`

After the update for September 10, 2020, it seems as though any list operation is causing 500s

```json
[
    {
        "acvVersion": "1.0"
    },
    {
        "error": "Internal service error. Contact service provider."
    }
]
```

GETs on a specific resource ID seem to still work though.

**Comment by Kritner** [comment]
Thanks @AlexThurston we'll be getting this fixed shortly

**Comment by Kritner** [comment]
This should be fixed now, note this does not fix some of the other issues that came in this morning #990, #996, #995, a fix for those is forthcoming

**Comment by AlexThurston** [comment]
Wow!  What prompt service.  This looks to be good now.
