### ISSUE TITLE
FYI: new ACVP-Server repository

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#998]
A new repository has been started at https://www.github.com/usnistgov/ACVP-Server/ for use in tracking demo / prod releases and the changes associated with those releases.  Additionally, we'd like to try to start opening issues there for *implementation issues* from the code's perspective, and leave this repo for protocol related issues.

On the new repository you'll see this:

![Releases location on the new repository](https://user-images.githubusercontent.com/8814983/92945738-b66f4680-f423-11ea-8e6c-7eb1503ce6f9.png)

Which will point you to release notes for changes to the environments (at least as of the v1.0.1.11 release when this repo was started).

Looking at the releases, you'll be able to see a "Latest Release", and potentially a "Pre-release".  "Latest Release" should reflect what is on production, and "Pre-release" should reflect what is on demo.

Examples:
![The latest production release notes](https://user-images.githubusercontent.com/8814983/92946460-b0c63080-f424-11ea-93f9-4e644a0a06a4.png)

![The most recent demo release notes](https://user-images.githubusercontent.com/8814983/92946368-92f8cb80-f424-11ea-8c09-06e013ca9d48.png)

We hope that this repository will help better convey what changes are on which environment.

I'll leave this pinned issue up for a bit for awareness, and will likely post some of this information on the readme and/or the wiki.

We'll probably start transferring issues that are specific to our implementations to the new repo at some point in the near future as well.

**Comment by dmchodnicki** [comment]
Item is being Closed.  It has been Open for more than 2 months and has served its purpose of notifying Users about the new ACVP-Server repository.
